### ISSUE TITLE
destroy() method needed

### ISSUE THREAD

**Issue by Davidx7** [mistic100/Photo-Sphere-Viewer#10]
A `.destroy()` method is needed and not just nullify. 
For some reason even after nullify of the main object and clearing everything, after a few uses (different 360s in different places), even with proper unloading, it takes up more and more memory. 

Maybe some ThreeJS objects not unloading ?
For mobile use 4,5 load/unload of totally different routes for `PSV` will crash due to `out of memory` which is common for big WebGL based apps

**Comment by mistic100** [comment]
I agree.

Can you try calling `dispose` on ThreeJS components http://stackoverflow.com/a/13915402/1207670 and see if it clear the heap correctly ?

**Comment by Davidx7** [comment]
I was just doing that now. 
Will submit findings after stress test

`Null` does not delete, it just removes for future disposal by the `gc`
I'll try `dispose` and `deallocateTexture` from `rederer`

**Comment by mistic100** [comment]
There is also all event handlers of the various sub components but that's the simplest part.

**Comment by mistic100** [comment]
https://github.com/mrdoob/three.js/issues/5175#issuecomment-52006131

**Comment by mistic100** [comment]
So I added a "destroy" method, the biggest has actually been to unregister the event handlers.

But from my (very quick) tests, although I clean every ThreeJS objects as everyone told to do, my memory usage still gain 100Mo on each destroy/create cycle.
https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/src/js/PhotoSphereViewer.js#L176-L194

I don't think ThreeJS has ever been

**Comment by cyruscuenca** [comment]
I'm currently having this issue. Was this never fixed? My panorama viewer fills hundreds of megabytes of memory every time I load it. I set up a `viewer.destroy()` call whenever the viewer component is destroyed to dispose of it. However, I still see increasing memory usage each time I close and open the viewer.
