### ISSUE TITLE
gyroscope - starting position

### ISSUE THREAD

**Issue by invincible09** [mistic100/Photo-Sphere-Viewer#100]
Hey guys,

for some reason the starting position for gyroscope is always facing the wrong position. For my case, it is always facing at the back of the vehicle? is this a image data issue?

Thanks for your help!

**Comment by mistic100** [comment]
Example ?

**Comment by invincible09** [comment]
sorry... unfortunately i cannot show you the image due to company policy.. but can this be an image related data issue?

**Comment by mistic100** [comment]
I just cannot help you without seeing what's going on.

**Comment by invincible09** [comment]
i mean the gyroscope is functional.. all I am doing is setting it to true when initializing PSV

gyroscope: true

**Comment by invincible09** [comment]
so it looks like the fault is on the 360 image itself.. the "stitch point" is at the back of the vehicle.. is there a way to offset this in the code at all?

Thanks!

**Comment by mistic100** [comment]
No, but nothing prevents you to edit the image to translate it.

**Comment by mistic100** [comment]
The starting position is absolute to the phone, turn around on your chair and enable gyroscope control, you will face the other side of the image.

I'm trying to always start gyro control from current point of view.

**Comment by MedleyMedia** [comment]
Same issue here, I've tried spinning around in my chair as I also thought it may just be the compass but still always loads at the same position. Seems to always start at the seam of my photo. It would be great if it could start at the custom start point that is set for desktop, but if not just starting in the dead center of the photo would suffice. Any idea what I can do?

**Comment by mistic100** [comment]
Wait

**Comment by MedleyMedia** [comment]
Thank you for looking into this, not sure if this helps but attached is an image I've been using for testing. No matter what with gyroscope enabled is starts in between the left and right (the edges of the photo), would be great to start on "center"

![gryrotest](https://cloud.githubusercontent.com/assets/4609014/23716257/92a227a0-03fd-11e7-9ed0-23ff31d7e8a6.jpg)

**Comment by MedleyMedia** [comment]
Any luck mistic? Sorry to be a pester, just not too sure how long I should wait :P

**Comment by mistic100** [comment]
Certainly not 22 hours, I have a day work you know, and hollidays too.
It can take several weeks.

**Comment by MedleyMedia** [comment]
Sure thing, sorry your last message just said wait and wasn't sure what to expect from it. I appreciate your help!  Thank you!

**Comment by kopiro** [comment]
I think that the problem is related to: https://github.com/mrdoob/three.js/issues/10552

**Comment by zengdongbao** [comment]
The same issue, I found the issue only happened in iOS.
I am so deal with it:

```
        if(/iPhone/i.test(navigator.userAgent)){
              PSV.doControls.updateAlphaOffsetAngle(3);
        }
        PSV.startGyroscopeControl();
```

**Comment by mistic100** [comment]
Where does "3" come from ?

Personally I reproduce the problem on Android too. And i wasn't able to correctly compute a good alpha offset that works every time.

**Comment by zengdongbao** [comment]
@mistic100 sorry,"3" Only apply to my project.
You can explain this: `PSV.doControls.updateAlphaOffsetAngle(Math.PI);` , come from the exchange formula of Angle and radian. 

You can check the source code of  DeviceOrientationControls.js in line 98:
```
var alpha = scope.deviceOrientation.alpha ? THREE.Math.degToRad( scope.deviceOrientation.alpha ) + this.alphaOffsetAngle : 0; // Z
```
