### ISSUE TITLE
How do i add a custom element in maker

### ISSUE THREAD

**Issue by rowdy-dowdy** [mistic100/Photo-Sphere-Viewer#1009]
### Describe your problem

how do i add a custom element in maker. The html attribute can only add strings. Even I just want an empty div tag and add some of my stuff in it

### Photo Sphere Viewer version

5.1.7

**Comment by rowdy-dowdy** [comment]
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/33823245/6893bd79-dc8e-4ff7-8844-d890e7b579f5)
i want to add a custom element that has its own shapes and events as hotspots

**Comment by rowdy-dowdy** [comment]
I hadn't thought of using innerhtml to get the string. js events are not available from innerhtml. I'm using it with svelte and which I used before with marzipano, i'm confused when everything works differently
```
var wrapper = document.createElement('div')
    
new Hotspot({
  target: wrapper,
  props: {
    title: "title"
  }
})

wrapper.addEventListener('click', function() {
  // change scene
})

// add wrapper to hotspot
```

**Comment by mistic100** [comment]
So being able to provide an existing DOM element would work for you ?

Note that you will have to provide the expected size, PSV doesn't not allow makers with dynamic size.

Sent from MailDroid

-----Original Message-----

**Comment by mistic100** [comment]
I did some testing, with minor modification of the plugin you will be able to do that.

```js
const element = document.createElement('div');
element.innerText = 'Loading...';

markersPlugin.addMarker({
   id: 'marker1',
   html: element,
   position: ....,
});

setTimeout(() => {
   element.innerHtml = '.....'; // whatever you want to fill the element, like attaching a framework component
   viewer.needsUpdate(); // required to recompute the marker size
}, 5000);
```

-----

By the way you don't need custom element or events handling to detect clicks on the marker, this is already available https://photo-sphere-viewer.js.org/plugins/markers.html#events

**Comment by rowdy-dowdy** [comment]
i can't simulate your way, it just shows [object HTMLDivElement], if replace with element.innerHTML nothing changes.
It would be nice to be able to pass the dom element straight in but I'd probably start with innerHTML

**Comment by mistic100** [comment]
I didn't said this was already possible, this is a proposal.

**Comment by mistic100** [comment]
Why closed ? You don't need this evolution ?

**Comment by mistic100** [comment]
I someone else find this thread, it will be (is) possible since version 5.3.1 or 5.4.0 with the marker of type `element`

https://github.com/mistic100/Photo-Sphere-Viewer/blob/5df185bc09abcd85b32d0ed172a742ce58749534/examples/plugin-markers.html#L311-L316

in the demo I use a native Web Component but a simple element would work too, as well as components from frameworks (probably).
