### ISSUE TITLE
dblclick

### ISSUE THREAD

**Issue by dekemega** [mistic100/Photo-Sphere-Viewer#101]
can you provide me with dblclick event .... there is 'click' but its not enough for me 
thank you in advance :)

**Comment by mistic100** [comment]
Important: the "click" event is always fired before a "dblclick"
Similarly, there is always a "select-marker" with dblkclick=false, before "select-marker" with dblclick=true

So if you want simple clicks and double clicks to be exclusive you will have to set a timer and wait 300 milliseconds after a simple click to be sure it's not a double click

**Comment by dekemega** [comment]
thank you very very very much

**Comment by dekemega** [comment]
can you provide me with your email please .. or any social media account you have 
you can send it to me on this email 
dekemega@gmail.com

i sent you an email on this email contact@git.strangeplanet.fr but no response
