### ISSUE TITLE
Blur both sides of the viewer

### ISSUE THREAD

**Issue by rowdy-dowdy** [mistic100/Photo-Sphere-Viewer#1012]
### Describe the feature

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/33823245/e30e51ce-be63-4cce-8104-eb594a1ebeca)
I don't know if there is a way to blur the 2 sides of the viewer like the photo on the side. I have some text on the sides, it's hard to read and hard to correct. I think it would be better if both sides were blurred and clearer in the middle

**Comment by mistic100** [comment]
That is not something I know how to do in ThreeJS and more importantly not something I want to add (how ever this is achievable it would require post-processing effects, which are not enabled at all in PSV).
