### ISSUE TITLE
The  photo  is not clear  on the mobie phone's browser

### ISSUE THREAD

**Issue by Edinburgh-D** [mistic100/Photo-Sphere-Viewer#1013]
### Describe your problem

i wonder know why the photo is not clear on mobie browser, and my  miniprogram

### Online demo URL

https://www.marcold.top/Preview

### Photo Sphere Viewer version

5.1.6

**Comment by mistic100** [comment]
Your page is not found, also you should upload a screenshot and tell which phone and which browser. And explain what "not clear" means.

**Comment by Edinburgh-D** [comment]
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/37974072/3ffb30ec-8eff-4cb2-9b3a-a8a2ede103b1)
![6e6741fc5fa212b1f54f62e2680165b](https://github.com/mistic100/Photo-Sphere-Viewer/assets/37974072/4e653b64-bfd5-42b9-b66a-b1d146985a3c)
The 'not clear' means the photo is blurry.Please look these photos.

**Comment by mistic100** [comment]
This is a limitation of WebGL on mobiles phones where the maximum texture size is 4096 pixels.

You must use https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html if you want to bypass this limitation.
