### ISSUE TITLE
How to convert pitch and yaw to latitude and longitde

### ISSUE THREAD

**Issue by EthanDini** [mistic100/Photo-Sphere-Viewer#1014]
### Describe your problem

I have created a viewer using Photo Sphere. I want to find the latitude and longitude of the point marker that I have created in the click event. I know that pitch and yaw are not same as latitude and logitude of GPS. In the click event I got  pitch, yaw, textureX, textureY,  viewerX, viewerY, clientX, clientY. What I want to know is is there any way to get the latitude and longitude of marker in GPS degrees.

### Photo Sphere Viewer version

5.1.7

### Plugins loaded

Marker Plugin

**Comment by mistic100** [comment]
How could it be know ? It is just a flat photo, the viewer cannot know if the zone where if you click is a mountain 10 kilometers away or a wall right in front of the camera.

So no : it is not possible, and it even does not make any sense, sorry.
