### ISSUE TITLE
Map Plugin Bug

### ISSUE THREAD

**Issue by ROTblog** [mistic100/Photo-Sphere-Viewer#1017]
### Describe the bug

When I zoom out of the map, the mouse hover can still click on the hot spots on the map, which is a bug.

Sometimes it is accidentally touched, triggering a click event

### Online demo URL

https://photo-sphere-viewer.js.org/plugins/map.html#usage

### Photo Sphere Viewer version

5.1.7

### Plugins loaded

map plugin

### OS & browser

chrome latest

### Additional context

![bug1](https://github.com/mistic100/Photo-Sphere-Viewer/assets/43842999/43ca6886-f0c6-4618-963f-3cca6b89382e)
![bug2](https://github.com/mistic100/Photo-Sphere-Viewer/assets/43842999/c1ac8c29-b6ed-4a86-807f-3718ed7bb486)

**Comment by mistic100** [comment]
Nice one :)
