### ISSUE TITLE
map zooming with keyboard

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1019]
### Describe your problem

When the map is maximized the keyboard actions works with the pano beneath.  zoom in or out and so on

Is there a way to use keyboard when the map is maximized...   for instance zoom in or out the map and not the pano beneath?

Thank You

### Photo Sphere Viewer version

5.1.7

### Plugins loaded

map

**Comment by mistic100** [comment]
The map will now be controllable with the keyboard when maximized (according to the viewer `keyboard` config, "fullscreen" or "always").

It will also exits from maximized mode when Escape key is pressed (regardless of keyboard config).

**Comment by haldo98** [comment]
Great!!!   Thank You...
