### ISSUE TITLE
How can I place a image over a panorama and stretch it the way I want programmatically?

### ISSUE THREAD

**Issue by framesbyharsh** [mistic100/Photo-Sphere-Viewer#1022]
### Describe your problem

I want to place an image (a png file with transparent background) over a panorama. The image needs to be rotated/stretched to be properly placed. Is there a way to do this in Photo-sphere-viewer? perhaps an overlay layer which can hold the image but moves in tandem with panorama?
I know that an image can be placed as a marker but my requirement requires the images to be stretched from the corners for proper placement.
I understand this is a viewer so this might not be a valid usecase, but is there any way I can do this? 

### Photo Sphere Viewer version

5.1.7

**Comment by mistic100** [comment]
like this ? https://photo-sphere-viewer.js.org/demos/basic/overlay.html

**Comment by mistic100** [comment]
I really don't understand. So it must not be possible.

**Comment by framesbyharsh** [comment]
Damien,
apologies if I was not clear. we need to overlay a small image on top of a panorama. Imagine if I have to hang a photo frame image on the wall. shown in the panorama. 

thanks
Harsh

**Comment by mistic100** [comment]
Why don't you just use an img tag and some CSS to position it above the viewer ?

**Comment by framesbyharsh** [comment]
Damien, it needs to move along with the pano. Image overlay is the closest thing but it is not convenient to create an image overlay which is the size of entire pano. I need a way to place a small image on top of pano and adjust it for proper placement. This is very similar to a image hotspot but with the added capability to control it from 3 side or 4 side.

**Comment by mistic100** [comment]
I found no way in Three JS to do that.

Your only options are :
- the overlay option
- the `imageLayer` marker
