### ISSUE TITLE
I need these HTML move with the walls, help me please

### ISSUE THREAD

**Issue by liuruiqi1993** [mistic100/Photo-Sphere-Viewer#1023]
### Describe your problem

I use version 4.8.1 and CubemapAdapter, and I need to attach these html on 4 walls, and let it move along the wall but not a circle. 
In the second picture, the left HTML and the right HTML should be set with rotateY, and all letters on the center wall should be the same size.
like this: 
![](https://github.com/mistic100/Photo-Sphere-Viewer/assets/33003931/e4aeb32e-30e3-4832-84fb-c61fa074253f)
![](https://github.com/mistic100/Photo-Sphere-Viewer/assets/33003931/29578d7b-f77d-4700-b8df-c586e64b87e4)

### Photo Sphere Viewer version

other

**Comment by mistic100** [comment]
Update to version 5 and check the overlay feature (there is a demo on the documentation)

That all I can provide.
