### ISSUE TITLE
"setCurrentNode" on "node-changed" event gets stuck

### ISSUE THREAD

**Issue by Mr-Kanister** [mistic100/Photo-Sphere-Viewer#1028]
### Describe the bug

# Context
A little while back, I opened a pull request with the feature of "chaining nodes" (https://github.com/mistic100/Photo-Sphere-Viewer/pull/933). I'll try to explain the feature again briefly with an example:

Imagine you want to map a long corridor with 360° images and it would be very annoying for the user to click several images further until he has reached the end. At the same time, the creator wants to show the whole corridor and not just one image at the beginning and one at the end. One could include a mechanism here that, as soon as a node is loaded, looks to see if there is a configuration that specifies which next node should be loaded without any click and if so, it is loaded.

It was being said, that this feature could easily be implemented via event listener ("`nextNodeId` are advanced features that can be easily implemented with event listeners, it is be much more versatile") and I also do think, that this would be significantly more versatile. I've been working on it again after a break, but I can't get it to work via event listeners. I guess I've already identified the problem too and that's what this issue is actually about:

# Problem
If you call `setCurrentNode` within a function that is fired via a `node-changed` event listener, an `AbortError` is thrown. This is because the internal `this.state.loadingNode` is not reset to null until after the event is fired:
https://github.com/mistic100/Photo-Sphere-Viewer/blob/2cbe45da45b3a5ef1835f7417097e6c04c81ee17/packages/virtual-tour-plugin/src/VirtualTourPlugin.ts#L423-L431

This means that the loading process of the original node is not yet 100 % complete, but a new loading process has already been instantiated. This is where the error then gets thrown: 
https://github.com/mistic100/Photo-Sphere-Viewer/blob/2cbe45da45b3a5ef1835f7417097e6c04c81ee17/packages/virtual-tour-plugin/src/VirtualTourPlugin.ts#L347-L351

I created a JSFiddle for you to investigate. The error is not being displayed in it's inbuilt console (probably related to the version, see the PS section), however you can see, that the loader isn't being hidden and the program gets stuck.
https://jsfiddle.net/t5o3a7wp/3/

# Possible solution
Is it necessary to clear `this.state.loadingNode` after the `node-changed` event, or could those two be swapped? I briefly tested it and this change would make my plan work out. If the change is without concern, I'd be happy to create a Pull Request.

Best Regards

PS: After writing the above, I tested it again on 5.1.7. Here I don't get the `AbortError` either, but the loader still gets stuck and the program stops. With the swap, it works flawlessly.

### Online demo URL

https://jsfiddle.net/t5o3a7wp/3/

### Photo Sphere Viewer version

5.1.7

### Plugins loaded

Virtual Tour Plugin

### OS & browser

Debian 12, Firefox 102.13.0esr

**Comment by mistic100** [comment]
The simplest solution is to just wrap your call in a setTimeout of 0ms. This way you don't mess up with the events loop.

**Comment by Mr-Kanister** [comment]
Okay, that's a simple workaround, thank you for that. But still: wouldn't it make sense to fire the event after everything is finished? Why exclude this one command to reset the loadingNode?

**Comment by mistic100** [comment]
I could change it, but it does not mean you will not have to use setTimeout anyway.

This a basic recursion problem which is not limited to this event ("panorama-loaded" + "setPanorama" probably have some issues too) nor this library, I personnally encountered it many times. setTimeout is the way to go to break such recursions.
