### ISSUE TITLE
Pixelated images in Samsung S5

### ISSUE THREAD

**Issue by MedleyMedia** [mistic100/Photo-Sphere-Viewer#103]
I'm having an issue in Samsung phones where my 360s are appearing very pixelated. In iPhone they look fantastic. Specifically I'm noticing it with with the Samsung S3, maybe more but don't have too many devices to test on. 

I also notice in Firefox for mac the 360s are not as good of quality as they are in Safari and Chrome. I chalked this up to Firefox's image smoothening algorithm? 

Any idea why it would display significantly worse in Samsung? Bonus points if you know why it's happening in Firefox as well. 👍

**Comment by mistic100** [comment]
I really can't help you. 

My only guess is that the old S3 does not support webgl, I because of the poor performances of the canvas render I downscale the texture to 4096 pixels https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/js/PhotoSphereViewer.utils.js#L11

**Comment by invincible09** [comment]
same thing is happening with the Samsung S5

![2017-03-08_13-36-29_720](https://cloud.githubusercontent.com/assets/25088226/23718366/3af7325e-0405-11e7-9336-1fb7982c41e9.jpg)

**Comment by mistic100** [comment]
what does https://people-mozilla.org/~mbrubeck/test/ratio.html reports ?

**Comment by invincible09** [comment]
55.0.2883.91

**Comment by mistic100** [comment]
???? that's not even a number !
For the S5 it should be 3

Because this value is a nonsense the renderer fallbacks to 1 hence the blurriness.

I couldn't help you to know why you have this.

**Comment by invincible09** [comment]
sorry gave you the wrong number.. that was the version of the browser hahaha

it spit out this

ratio:3

**Comment by mistic100** [comment]
Reopening for having a real case but I still cannot help, never had this kind of problem.

**Comment by invincible09** [comment]
list of errors reported from S5

![screen shot 2017-03-08 at 2 21 46 pm](https://cloud.githubusercontent.com/assets/25088226/23719775/a6e08132-040a-11e7-8a44-c8f824e1d6fc.png)
