### ISSUE TITLE
Multiple viewers on one page showing broken panorama

### ISSUE THREAD

**Issue by mtran21** [mistic100/Photo-Sphere-Viewer#1030]
### Describe your problem

I am not sure if this is a bug or an issue with my code but I am having trouble understand this error.

This demo URL has about 19 viewers: https://jsfiddle.net/mtran21/q87gt1es/16
If you click on any modal of the first row, it shows this
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/13279623/65820e34-82ec-4c8d-b96e-aac9a868148f)

If you click on any of them below that then they are working just fine. 

So I removed some of them, I keep only the first 2 rows of the modals. Then they are working just fine and here it the demo for only about 6 modals https://jsfiddle.net/mtran21/nc9Ltzjm/7/

This bug is on Chrome and Edge. So far it is working with Firefox and Safari.

I hope you could help me find out what the problem and how to fix it.

Thank you

### Online demo URL

https://jsfiddle.net/mtran21/q87gt1es/16

### Photo Sphere Viewer version

5.1.7

**Comment by mistic100** [comment]
I will take a look. BUT you should not do that, it consumes an excessive amount of resources (actually it may be the reason it is broken, there is a limit of how many WebGL context the browser can manage). You should only initialize one viewer when needed, and if possible reuse it.

**Comment by mistic100** [comment]
Yes I confirm this is a browser limitation. And as I said, a very bad practice to initialize many WebGL contexts.

You must create the viewer once the modal is opened (with a placeholder image during the Bootstrap opening animation for example) and destroy it when the modal is closed (this is very important or you will never free the resources).
