### ISSUE TITLE
Photosphere Image Cache removal.

### ISSUE THREAD

**Issue by SHIJOScaria** [mistic100/Photo-Sphere-Viewer#1032]
How can i solve the Image cache problem while loading the next image. Each time the intial image where i started the navigation remains in the viewer and overlapping the current image.

**Comment by mistic100** [comment]
Please provide a demo.

**Comment by 6ar8nas** [comment]
If you don't want to remount the viewer, I think you're looking for [`setPanorama`](https://photo-sphere-viewer.js.org/guide/methods.html#setpanorama-panorama-options-promise).
