### ISSUE TITLE
Marker at wrong position/not working when using EquirectangularTilesAdapter

### ISSUE THREAD

**Issue by altr54** [mistic100/Photo-Sphere-Viewer#1033]
### Describe the bug

The code below will generate a marker with a click at the mouse position. The marker is created, but not at the mouse position. Whilte panning the panorama, the markers shift. The same happens with lines and polygons.
The same code works fine, when the EquirectangularTilesAdapter is not used.

```
POIPhotoSphere.#viewer.addEventListener('click', ({ data }) => {
    const markersPlugin = POIPhotoSphere.#viewer.getPlugin(PhotoSphereViewer.MarkersPlugin);
    if ( markersPlugin == null ){
        console.log("Marker plugin not registered");
        return;
    }

    if (!data.rightclick) {
        console.log("Add Marker: yaw: " + data.yaw + " pitch: " +  data.pitch);
        markersPlugin.addMarker({
            id: '#' + Math.random(),
            position: { yaw: data.yaw, pitch: data.pitch },
            image: 'img/marker.png',
            size: { width: 32, height: 32 },
            anchor: 'bottom center',
            tooltip: 'Generated pin',
            data: {
                generated: true,
            },
        });
    }
});
```

### Photo Sphere Viewer version

5.1.7

### Plugins loaded

MarkersPlugin

### OS & browser

Windows 10, Chrome, Firefox, Edge

**Comment by mistic100** [comment]
Did you load the CSS file for the plugin ?

**Comment by altr54** [comment]
> Did you load the CSS file for the plugin ?

I did, but there was a typo in the path. Thanks a lot!
