### ISSUE TITLE
Clickable aditional transparent panorama

### ISSUE THREAD

**Issue by rustambakov** [mistic100/Photo-Sphere-Viewer#1034]
### Describe your problem

Dear Jérémy,

According to the documentation, we can provide an additional transparent panorama with the required opacity. Is it possible to make it somehow clickable? I need to make some areas highlighted and clickable(screenshot attached).

<img width="969" alt="Screenshot at Aug 06 08-28-08" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/30320621/b3d00260-6875-471c-8bb3-c06d448d26da">

BR, Rustam

### Photo Sphere Viewer version

5.1.7

**Comment by mistic100** [comment]
I am not Jeremy, this is a fork of its library.

----

To answer your question : no this is not possible, the overlay is a single image and not interactive.

But you can use [`polylinePixels` markers](https://photo-sphere-viewer.js.org/plugins/markers.html), those are dynamic SVG defined by a series of coordinates on the panorama, with configurable style and tooltip.
