### ISSUE TITLE
[VirtualTour] Arrows colors not as bright

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#1048]
### Describe the bug

In versions <= 5.1.7, arrows used for Virtual Tour Plugin were by default using "raw" (unlighted ?) colours :
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1349014/47cbb26d-8ff0-4944-9cce-b6035da28df5)

[Example 5.1.7](https://files.pavie.info/clients/panoramax/next_ui/#focus=pic&map=19.03/48.1426081/-1.6950464&pic=408ed948-9f17-4c82-89cc-30362f0e8bb3&xyz=333.54/-4.77/30)

In version 5.2.0, arrows are having a more gray colour by default, like if they were not sufficiently lighted :
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1349014/20e68248-20b5-4215-b613-fd75dc9431c4)

[Example 5.2.0 (reflected in demo in official docs)](https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#example)

Changing manually colours with `arrowStyle` changes the colour but doesn't fix the lighting.

### Photo Sphere Viewer version

5.2.0

### Plugins loaded

Virtual Tour

### OS & browser

Linux + Chromium 115 or Firefox 116

**Comment by mistic100** [comment]
This is already fixed on main branch, you can downgrade three.js to r154 as a temporary fix.
