### ISSUE TITLE
[Virtual Tour] More options for animation between nodes

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#1049]
### Describe the feature

For now, when using Virtual Tour plugin, the behaviour when clicking on an arrow can be managed through :
- `rotateSpeed` : either rotate to look in direction of arrow, or keep current rotation
- `transition` : duration of transition, or no transition at all

For the use we have on [GeoVisio](https://panoramax.ign.fr/), there is at least two situations where this is limiting.

__Switching between unrelated nodes__

Considering we have two independent series of linked pictures, we can programmatically switch from one to another serie. When this happens, we don't want an animation. But when pictures are in same series, we want to keep a smooth animation.

Here, having a static-defined `transition` on plugin init prevents to choose which behaviour we want on `setCurrentNode` call. It would help to define `transition` as a parameter of `setCurrentNode`.

__Moving rear on cropped panoramas__

Considering we have a series of cropped panoramas (for example, classic pictures taken with a basic camera, 70° field of view). This serie is taken in a curved road. If we click on an arrow going to previous picture (going on reverse), we have the choice between:
- `rotateSpeed=false` : we see the picture, but with a slight rotation (depending on the road curve)
- `rotateSpeed=number` : we see the overwhelming void as viewer rotates in direction of arrow, but no image is available in this part of cropped panorama

Note that this issue only concerns cropped panorama, as classic panorama would do well with both parameters.

Here, having a way to say _rotate to given yaw/pitch_ would be helpful. This may be added as options of the received node (`animateOptions` ?) for more flexibility.

### Alternatives you've considered

On current GeoVisio viewer (with PSV 5.1.7), we do the following :
- Hack the `setPanorama` function to make it send an event before switching the shown panorama ([here](https://gitlab.com/geovisio/web-viewer/-/blob/develop/src/Viewer.js?ref_type=heads#L295))
- Listen to this event to do custom `animate` call and pass all wanted options ([here](https://gitlab.com/geovisio/web-viewer/-/blob/develop/src/Viewer.js?ref_type=heads#L326))

This is limiting because animation is not always synced with PSV transition, making weird visual effect. I tried to change the hack to pass custom animation options before calling original `setPanorama`, but it breaks when using virtual tour arrows. Also, this is not very robust to internal changes of PSV.

### Additional context

I open this feature request to discuss what would be the best solution to handle this. I can offer a bit of time to implement necessary changes in PSV.

**Comment by PanierAvide** [comment]
Here is an example of a sequence of flat pictures, with the hack described : https://panoramax.ign.fr/#focus=pic&map=19/44.0820015/3.8150464&pic=119c6c2a-024a-4edb-be64-2c0501ef9077&xyz=302.00/0.00/30

I can provide a more raw codepen with only PSV involved if neeeded :wink: 

Yes Mapillary uses a system called [OpenSFM](https://opensfm.org/) to do the 3D work, on GeoVisio/Panoramax we decided to stick with simpler things like a smooth blurring between pictures :sweat_smile: This is more than enough in many cases, as long as everything animated goes synced.

**Comment by mistic100** [comment]
Proposal :

```ts
export type VirtualTourTransitionOptions = { 
    transition?: boolean | number;
    rotateSpeed?: false | string | number;
    position?: Position;
};

export type VirtualTourLink = {
    .....
    transitionOptions?: VirtualTourTransitionOptions;
};

setCurrentNode(nodeId: string, options?: VirtualTourTransitionOptions) {
   // will use clicked link "transitionOptions" if available or "options" for programatic call
   // and merge with the default config and position computation
}
```

A link to an unrelated node can be configured with `transitionOptions: { rotateSpeed: false }` 

A link to the next partial node can be configured with `transitionOptions: { position: { yaw: 5.27, pitch: 0 }}` (assuming the position of the center of the target node)

A link to an unrelated partial node can be configured with `transitionOptions: { rotateSpeed: false, position: { yaw: 5.32, pitch: 0 } }`

And you still can disable the panorama transition if needed.

**Comment by mistic100** [comment]
I wonder if this solves the same problem as `linkOffset` added for #933, it is a different approach but perhaps serves the same goal.

(`linkOffset` is not useable in your case, or it would require to heavily cheat on the gps coordinates)

**Comment by PanierAvide** [comment]
> A link to an unrelated node can be configured with `transitionOptions: { rotateSpeed: false }`

:heavy_check_mark: Checks out

> A link to the next partial node can be configured with `transitionOptions: { position: { yaw: 5.27, pitch: 0 }}` (assuming the position of the center of the target node)
> 
> A link to an unrelated partial node can be configured with `transitionOptions: { rotateSpeed: false, position: { yaw: 5.32, pitch: 0 } }`

OK for pitch, but in this case, yaw is only known when getting metadata from server for incoming node, as it is based on `sphereCorrection.pan` we're getting from API call.

What if `VirtualTourPluginConfig` offered instead a `transitionOptions` which would be a function like `(fromNode, toNode) => VirtualTourTransitionOptions` ? It could be called in `setCurrentNode` after getting metadata on incoming node, and be flexible enough to work in all cases :

- Going to unrelated node (no virtual link, external `setCurrentNode` called) :arrow_right: OK because we would see that fromNode and toNode aren't part of same series
- Moving to related 360° pano (with virtual link)  :arrow_right:  OK because we check that fromNode & toNode picture types (360°) and the fact that they are in same series
- Moving to related cropped pano (with virtual link pointing to void) :arrow_right: OK because we see that fromNode & toNode are in same series, but not 360°
- And many more cases I don't know about, but as long as one have info about previous and next node, any checks or logic can be done.

I guess it would also impact less current code ?

**Comment by mistic100** [comment]
**Proposal V2:  **
(renamed "transition" to "fade" and "position" to "rotateTo")

```ts
/**
 * Behaviour of the transition between nodes
 */
export type VirtualTourTransitionOptions = { 
    /**
     * Duration of the fade effect between nodes
     * @default '1500'
     */
    fade?: boolean | number;
    /**
     * Speed of rotation when clicking on a link, if 'false' the viewer won't rotate at all
     * @default '20rpm'
     */
    rotateSpeed?: false | string | number;
    /**
     * Define where to rotate the current panorama before switching to the next
     * if not defined it will use the link's position
     */
    rotateTo?: Position;
};

export type VirtualTourPluginConfig = {
    .....
    /**
     * Configuration of the transition between nodes. Can be a callback.
     * @default `{ fade: 1500, rotateSpeed: '20deg' }`
     */
    transitionOptions?: 
        Pick<VirtualTourTransitionOptions, 'fade' | 'rotateSpeed'> 
        | ((fromNode: VirtualTourNode, toNode: VirtualTourNode, fromLink?: VirtualTourLink) => VirtualTourTransitionOptions);
    /**
     * @deprecated Use {@link VirtualTourPluginConfig#transitionOptions "rotateSpeed"}
     */
    rotateSpeed?: false | string | number;
    /**
     * @deprecated Use {@link VirtualTourPluginConfig#transitionOptions "fade"}
     */
    transition?: boolean | number;
};

setCurrentNode(nodeId: string, options?: VirtualTourTransitionOptions) {
     .....
      const transitionOptions: VirtualTourTransitionOptions = {
          fade: 1500,
          rotateSpeed: '20rpm',
          rotateTo: fromLinkPosition,
          ...(typeof this.config.transitionOptions === 'function'
              ? this.config.transitionOptions(fromNode, node, fromLink)
              : this.config.transitionOptions
          ),
          ...options
      };
}
```

**Comment by PanierAvide** [comment]
Perfect :100: :clap: Should I offer a PR following your proposal, or will you implement it on your side ?

**Comment by mistic100** [comment]
c'est en cours :D

**Comment by mistic100** [comment]
You can test this branch if you want https://github.com/mistic100/Photo-Sphere-Viewer/tree/virtual-tour

**Comment by PanierAvide** [comment]
Hmm I'm trying to test locally your branch by importing in my own project with a `npm link`. Something might be wrong somewhere, I can't make it work...

What I tried:
- In PSV repo folder, `npm run build` then `npm link`
- In my repo, `npm link photo-sphere-viewer`
- :arrow_right: in that case, imports are messed up, either because of package name being different, or typescript loader issue

Other try:
- In PSV repo, `npm run build`, then go to each package and do `npm link` there
- In my repo, `npm link @photo-sphere-viewer/...` for each necessary package
- :arrow_right: "export was not found, module has no exports" for each used package

I didn't find docs for this use case (local dev/testing of the library), did I miss something obvious ? :disappointed_relieved:

**Comment by mistic100** [comment]
I think you need the link from the dist folder of each package

**Comment by PanierAvide** [comment]
Tried also, didn't work either... Gone for a simpler approach and did testing directly on your demo files :grin: 

Would it be possible to make rotate animation happen simultaneously to fading ? Currently it goes:
- Viewer rotates
- Next panorama loads
- Viewer fades from previous to next panorama

Otherwise, with cropped pano scenario, viewer would point to void during next pano loading. As a reference, on Mapillary viewer, everything happens all at once : next panorama loads, then viewer rotates/fades.

**Comment by mistic100** [comment]
The problem is `setPanorama` starts by loading the image, which takes un unknown time then transfert the texture to the GPU, which is a blocking operation, if an animation is ongoing it will stutter.

I will see if a solution is not to handle the rotation in `setPanorama` (actually `Renderer#transition`) directly, currently this function jumps to the new configured position, but it could be included in the fading animation.

**Comment by PanierAvide** [comment]
For sure, it's not dramatic that nothing happens during texture loading, the loader is here to let user know about the blocking process that is ongoing. Doing all animation after texture loading could do the trick.

In the while, I managed to make my hack on PSV 5.1.7 fully synced with setPanorama's fading, [example](https://files.pavie.info/clients/panoramax/next_ui/#focus=pic&map=19.57/48.8030389/2.4861222&pic=adbe879f-2e99-444f-9585-8c1217dde3e4&pic_type=flat&xyz=347.00/0.00/30) and [code](https://gitlab.com/geovisio/web-viewer/-/blob/feature/shortcuts/src/Viewer.js?ref_type=heads#L328). As you explained, it lacks rotation for now, but that already isn't that bad by just fading :grinning: 

Having all this managed natively in PSV will ensure less trouble on PSV updates though :smile:

**Comment by PanierAvide** [comment]
Tested, that's perfect :100: :clap: :fire: :grin:

**Comment by PanierAvide** [comment]
For info, I integrated your release 5.3 on our next version of GeoVisio viewer, result is very convincing :star2: 

https://files.pavie.info/clients/panoramax/next_ui/#focus=pic&map=20/47.126079/-0.2181881&pic=8f1fc52c-5865-49c5-942f-83808eca8345&pic_type=flat&xyz=282.00/0.00/30

Thanks again for being so reactive and open to new features :grinning:
