### ISSUE TITLE
Black background in Mobile

### ISSUE THREAD

**Issue by hotbrainy** [mistic100/Photo-Sphere-Viewer#1050]
### Describe the bug

when rendering on mobile, background is black screen in v5.2.0

### Photo Sphere Viewer version

5.2.0

### Plugins loaded

autorotate, visible-range, markers, gyroscope

### OS & browser

Android 9, Chrome 115

**Comment by mistic100** [comment]
It would be cool if you could explain a bit more like with a screenshot. You never provided such information in your previous issues either and they where rejected.

**Comment by makeCarry** [comment]
Had a black screen problem on my Apple phone, then realized it was the size of the image that was too large
