### ISSUE TITLE
How to add videos on a large screen in a panoramic view

### ISSUE THREAD

**Issue by it206it** [mistic100/Photo-Sphere-Viewer#1051]
### Describe the feature

In a 360 panoramic view, add a screen where you can play videos

**Comment by mistic100** [comment]
Please explain in details what you want, with a mockup.

**Comment by it206it** [comment]
Here is example:

https://www.kuleiman.com/151803/

How to add the left and right carousel images and videos in the following figure to follow the rotation

![1692428663516](https://github.com/mistic100/Photo-Sphere-Viewer/assets/5466600/4b5fcbc1-b89c-4fae-bfa9-b0ecd8a3572e)

**Comment by mistic100** [comment]
that's not possible, I already searched a way to do this (for still images), and found no solution available with this rendering library and my knowledge
