### ISSUE TITLE
Change current panorama by clicking on icon in navbar

### ISSUE THREAD

**Issue by tiYusupov** [mistic100/Photo-Sphere-Viewer#1058]
### Describe your problem

Doing a virtual tour of the office. Everything works fine, but the panoramas that have windows have day/night variations. I added an icon to the navbar, but I don't understand how to change exactly the current panorama? So it's like the lights are on, when you click on the icon, they turn off. Thanks in advance for any hints.

### Photo Sphere Viewer version

5.3.0

### Plugins loaded

VirtualTourPlugin

**Comment by mistic100** [comment]
Here you have an example of a cutom button switching between two panoramas 

https://github.com/mistic100/Photo-Sphere-Viewer/blob/ad2f0d1b723cbf77e3d406f8997820f23ee403c4/examples/adapter-equirectangular.html#L81-L97
