### ISSUE TITLE
black gap on FF 64bit and Edge

### ISSUE THREAD

**Issue by michaelh99** [mistic100/Photo-Sphere-Viewer#106]
When viewing the image at https://www.dragonseye.com/photos/picture.php?/19881-pano_20170317_164455/category/974-hot_springs_2017  in 64bit FF 52.0.1 and Edge on Windows 10 I see a black band cutting the image, vertically.  This does not appear in FF 32b or Chrome.

![pano-hole](https://cloud.githubusercontent.com/assets/2307675/24213202/a4a6bf1c-0eff-11e7-8230-78b145fb43e6.jpg)

More discussion at
https://github.com/mistic100/Piwigo-PhotoSphere/issues/5#issuecomment-288472167

**Comment by Biboba** [comment]
I noticed the same problem but in my case it was  a much bigger black band image.
I believe it has to do with the quality of the picture. If you downgrade a bit the quality of the image you should be able to display it fully.
