### ISSUE TITLE
Map Plugin: option to hide buttons and change map shape/show full map always

### ISSUE THREAD

**Issue by mattdalpii** [mistic100/Photo-Sphere-Viewer#1060]
### Describe the feature

Hello there. First thank you so much for this amazing project. I've just started to mess around with it to use in a future project and it's been great.

There's two small things in my way right now and since it's not a bug I think this is most suitable to a feature request (or even a support request):

1. Is it possible to hide the buttons around the map, or display it programmatically (like only showing some of them)? I've manage to hide it with CSS and `!important`, but maybe there's a better way.
2. Is it possible to change de map "shape"? Like to a square, or even better (for my case), to show the full map respecting the size setting, and with the markets, hotspots, etc.?

A small bug request came to mind: I was testing the map zoom when showing the full map (top right button) and it goes to a `NaN` state, I think it's related to horizontal wheel/scroll, since I'm using a Magic Mouse, it scrolls vertically and horizontally at the same time with no much control of my part.

Thanks!

**Comment by mistic100** [comment]
1. that's a good solution for me

2. it would be incredibly hard to allow any shape for the map, I can only advice to set the `size` option to the width or height of your image, or the max of both

**Comment by mistic100** [comment]
To make the map square you can set `.psv-map__container { overflow: visible }` and change the `overlayImage` to a square one, or hide it with `null`.

**Comment by mistic100** [comment]
https://github.com/mistic100/Photo-Sphere-Viewer/blob/de207a81e668dfce615700079f7d18354c9aa5e8/examples/plugin-map.html#L69-L74
