### ISSUE TITLE
Can't override XMP data when using equirectangular tiling adapter

### ISSUE THREAD

**Issue by alexsaleh** [mistic100/Photo-Sphere-Viewer#1062]
### Describe your problem

I'm using the equirectangular tiling adapter to load a cropped panorama (360 degree horizontally but very narrow vertically). Using the default adapter I can display it fine when overriding XMP data. 

Using the tiling adapter, it stretches the overall image to cover 360 degrees vertically and it seems to ignore my XMP data overrides. 

Is what I want to achieve compatible with the tiling adapter? Looking at the adapter code it seems like the XMP data is hardcoded. 

[Code snippet for hardcoded value](https://github.com/mistic100/Photo-Sphere-Viewer/blob/de207a81e668dfce615700079f7d18354c9aa5e8/packages/equirectangular-tiles-adapter/src/EquirectangularTilesAdapter.ts#L207-L217)

Thanks!

### Photo Sphere Viewer version

5.2.0

### Plugins loaded

compass

**Comment by mistic100** [comment]
XMP data are not applied to the tiles, only the low resolution loaded at init.  
Note that if the 'tileUrl' function returns "null" it will not try to load the corresponding tile.
