### ISSUE TITLE
`viewer.rorate` makes `sphericalCoordsToViewerCoords` returns wrong positions

### ISSUE THREAD

**Issue by Amoki** [mistic100/Photo-Sphere-Viewer#1065]
### Describe the bug

I manage my own marker without using the MarkerPlugin.
To do so, I call
```js
    viewer.addEventListener("position-updated", () => {
        // Converting textureCoords to CanvasCoord
        const sphericalCoords = viewer.dataHelper.textureCoordsToSphericalCoords(markerPosition);
        const {x, y} = viewer.dataHelper.sphericalCoordsToViewerCoords(sphericalCoords);
        const element = document.querySelector('#marker');
        element.style.top = y + "px";
        element.style.left = x + "px";
    });
```
When calling `viewer.rotate()`, the event `position-updated` is triggered, but the function `sphericalCoordsToViewerCoords` returns a wrong `viewerCoords`.

When moving the camera with the mouse, `sphericalCoordsToViewerCoords` returns the expected result.

Reproduction example:
The marker (letter A with a red background) should be seen on the main door on load, but it's only seen after a manual camera move.

### Online demo URL

https://jsfiddle.net/pgbd9qrw/

### Photo Sphere Viewer version

5.3.0

### Plugins loaded

None

### OS & browser

Tester on Linux, Firefox and Chrome

**Comment by mistic100** [comment]
Use the "render" event instead, it will happens after updating the Camera projection matrix.

**Comment by Amoki** [comment]
Thanks, it works!
