### ISSUE TITLE
Is it possible to use this lib in react native?

### ISSUE THREAD

**Issue by algopert** [mistic100/Photo-Sphere-Viewer#1066]
### Describe your problem

Hi,
Hope you are well.
It would be STUPID question, but can I use it in react native?
I think it is impossible, but want to find the way to do so.
Thanks.

### Photo Sphere Viewer version

5.3.0

**Comment by mistic100** [comment]
Hi

I have zero knowledge of React Native. You should try it yourself.

A quick Google search yields multiple result about using standard web libraries into React Native (generally inside a WebView)
