### ISSUE TITLE
panorama moving bug

### ISSUE THREAD

**Issue by xuanwubing** [mistic100/Photo-Sphere-Viewer#107]
when panorama is moving, click the area out of the panoram viewer(such as navbar or others), then the panorama will move to wrong direction, like random jumping.
you can reproduce this bug easily on the official website(http://photo-sphere-viewer.js.org/)  demo.
just stop the autorotate throug the navbar, and move the panorama, click the navbar before the animation stoped.

**Comment by ChristianLJ** [comment]
I am also experiencing this behaviour.

**Comment by mistic100** [comment]
I cannot find what is causing this.
During the "_stopMoveInertia" animation I can log **one frame** with incoherent coordinates but I don't know where it comes from.
