### ISSUE TITLE
Perspectives are jumping all over the place

### ISSUE THREAD

**Issue by Qs-cic** [mistic100/Photo-Sphere-Viewer#1073]
### Describe your problem

After the page renders the panorama, no click event is configured, and the Angle of view will jump randomly when the mouse clicks on some positions or above the panorama, version 5.1.5

### Photo Sphere Viewer version

5.1.5

### Plugins loaded

none

**Comment by Qs-cic** [comment]
import {
    Viewer,
} from '@photo-sphere-viewer/core'

new Viewer({
    container: 'pano',
    panorama: 'pic/sphere.jpg',
})

**Comment by mistic100** [comment]
I cannot help you without a live demo.

Did you imported the CSS stylesheet ?

**Comment by Qs-cic** [comment]
> I cannot help you without a live demo.
> 
> Did you imported the CSS stylesheet ?

Thanks, I found the solution, the problem is the same as the link below.
Clicking on the viewer while panning the animation causes the image to shake #977

> I cannot help you without a live demo.
> 
> Did you imported the CSS stylesheet ?

Thanks, I found the solution, the problem is the same as the link below.
Clicking on the viewer while panning the animation causes the image to shake #977
