### ISSUE TITLE
Billboard markers

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#1077]
Improve the exiting `imageLayer` to allow precise placement in the 3D scene.

Prototype :
![Capture d’écran du 2023-09-08 13-41-55](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41597/2e61c398-c3af-43aa-8a13-ed3fda0d8ccc)

and allow video textures (#1051 #1072)

**Comment by it206it** [comment]
here   is   embedded-hotspots    https://www.marzipano.net/demos/embedded-hotspots/

**Comment by mistic100** [comment]
Thanks but I already been clear I do not want to copy what others do. If you prefer the features of marzipano then go for it.
