### ISSUE TITLE
spotStyle Map Plugin

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1079]
### Describe your problem

Hi Damien.

I have this pano: 
https://www.tadini.it/panorama/test/panorama_cornagiera.html

with the new spotStyle option the spots on the map are now white as per default.

I want the spots to be in another color so I added this line in the map plugin configuration:

`     spotStyle: { color: 'black' },`

but now the spots are not showed at all.

https://www.tadini.it/panorama/test/panorama_cornagiera2.html 

Am I doing something wrong?

### Photo Sphere Viewer version

5.4.0

### Plugins loaded

map

**Comment by mistic100** [comment]
This is a bug so use the "bug" issue template :-)
