### ISSUE TITLE
Cannot load image error

### ISSUE THREAD

**Issue by Caspert** [mistic100/Photo-Sphere-Viewer#108]
I would like to use this plugin for viewing photospheres. I fork the code on Codepen to try it out by myself, but when I change the source path to the image, to one of my images, I receive the error `Cannot load image`. I tried different images, but non of them work. Only the one that is located at: https://cdn.rawgit.com/mistic100/Photo-Sphere-Viewer/master/example/Bryce-Canyon-National-Park-Mark-Doliner.jpg

How can I use my own images, without any problem?
Code: http://codepen.io/anon/pen/eWYQNj

**Comment by mistic100** [comment]
Did you oppened your web console ? Your image does not exist !! http://www.tomshousevision.nl/pano.jpg

Anyway, unless you configure your server with the necessary CORS header, it will not work because of Acces Control Origin, the image must be on the same server that the script loading the image.
