### ISSUE TITLE
Map shutting down after a little bit of navigation; Uncaught PSVError: Unknown angle "NaN"

### ISSUE THREAD

**Issue by fredy31** [mistic100/Photo-Sphere-Viewer#1080]
### Describe the bug

I've installed a pretty simple installation of PSV and the map seems to crash every once in a while, with the error Unknown angle NAN

I open it in a dialog and that error closes the dialog.

Any way to make that error just a warning? the map doesnt seem to be crashing with it, it just crashes the dialog its within.

### Photo Sphere Viewer version

5.4.1

### OS & browser

Chrome Windows

**Comment by mistic100** [comment]
Please provide an example

**Comment by fredy31** [comment]
Sadly, website is not public yet.

**Comment by mistic100** [comment]
Then create a demo on jsfiddle, codepen, etc.

I cannot help with such few info.

**Comment by jvink10** [comment]
The error may not be the cause of the crash. I have a website that only displays a photosphere on hover, and when the photosphere is rotating and I stop hovering over it, the same error comes up, likely because once it is hidden there is no angle, hence NaN.

**Comment by mistic100** [comment]
Yes, the viewer does not support do be hidden, it needs to be destroyed first (with the "destroy" method)
