### ISSUE TITLE
Initial tooltip loading and hover not working

### ISSUE THREAD

**Issue by mattdalpii** [mistic100/Photo-Sphere-Viewer#1081]
### Describe the bug

Hi. I've just updated to the latest release and I noticed a few things:
- When hovering the first time a Tour marker, the tooltip is messed up. Upon second hover, it shows just fine. **Edit:** the bug seems to happen only with Tour markers (links).
- When I enable hover scale `defaultHoverScale: { amount: 2, duration: 100 }`, the tooltip is positioned way higher than default, with no other changes.
- Also, the Tour markers doesn't scale on hover using the above global config.

Also a quick question: is possible to change the ripple effect color on the default Tour marker? Is it possible to use it on a custom image?

I'm attaching some videos/images for reference.

Thanks!

https://github.com/mistic100/Photo-Sphere-Viewer/assets/94379499/87e29510-0ee5-4781-8af7-d4ecf762ebbb

<img width="235" alt="Captura de Tela 2023-09-13 às 14 36 07" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/94379499/536dd7d3-43b1-4636-8d09-556f28ff348d">

https://github.com/mistic100/Photo-Sphere-Viewer/assets/94379499/037f4124-1215-4083-8e90-029b7eefbecf

### Photo Sphere Viewer version

5.4.1

### OS & browser

Chrome on Mac

**Comment by mistic100** [comment]
- problem with tooltip: fixed
- problem with hover scale: fixed
- changing the ripple color:
   1. use CSS to override the animation, the class name is `psv-virtual-tour-link`, if you want anything else you must provide your own marker with `markerStyle` (you can check [the default value](https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/virtual-tour-plugin/src/constants.ts#L13-L21))
   2. compile your own stylesheet form the SCSS source and change the `$psv-virtual-tour-link-button-ring` variable
