### ISSUE TITLE
During the process of using the marker, some exceptions or errors were found.

### ISSUE THREAD

**Issue by TrionLanister** [mistic100/Photo-Sphere-Viewer#1082]
### Describe the bug

I'm sorry to raise an issue under the main directory, but finding the warehouse for @ photo sphere viewer/markers plugin may be difficult for me. Please understand!. The specific situation is as follows:
During my use, I found some compatibility issues with the CSS of the marker plugin in the webview environment (which is normal in mainstream versions of Chrome), resulting in the incorrect position of the marker. Through debugging, I found that the reason is that the translate attribute of CSS is not supported in some webviews. If it is modified to 'translate'$ {position.x}px $ {position.y}px ）`Then it can be displayed normally
![20230914092410](https://github.com/mistic100/Photo-Sphere-Viewer/assets/51609062/43678d3d-f4a8-41ca-bfb5-a23de1d82aed)

### Photo Sphere Viewer version

5.2.0

### OS & browser

Android webview environment

**Comment by mistic100** [comment]
Hi, you are in the righ repository, this contains all the @photo-sphere-viewer packages.

I cannot apply the suggested change, it is required for other parts of the plugin to control translation and scale independently.

As it is supported by all major desktop and mobile browsers it is good enough for me. Third party webviews will have to be updated.
