### ISSUE TITLE
Zoom in-out and autorotation

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1084]
### Describe the bug

Hi Damien

I think there still an issue with the visiblerange plugin

In the demo:  

stop the rotation and zoom in ...like 80%-90% of the max...    hit the spacebar...    the viewer zoom out smoothly and then starts the rotation.

But if i do the same and before hitting the spacebar i move the viewer around a little, the viewer zoom out instantly and not smoothly anymore.

### Online demo URL

https://www.tadini.it/panorama/test/panorama_capelet.html

### Photo Sphere Viewer version

5.4.1

### OS & browser

win 11 - chrome 116

**Comment by haldo98** [comment]
5.4.2 but it seems that the problem is still there....

https://www.tadini.it/panorama/test/panorama_capelet.html

https://github.com/mistic100/Photo-Sphere-Viewer/assets/97630238/299a6d10-9d81-4c2e-8d80-0a8edd6280fb

**Comment by mistic100** [comment]
sorry I did what I could, these two plugins has always been clashing with each other. I don't think the "bug" is important enough to spend more time on it

**Comment by haldo98** [comment]
> sorry I did what I could, these two plugins has always been clashing with each other. I don't think the "bug" is important enough to spend more time on it

I totally agree....  there's no big deal.   Thanks to you for your time and patience....
