### ISSUE TITLE
Fullscreen not working on chrome

### ISSUE THREAD

**Issue by webfalcon** [mistic100/Photo-Sphere-Viewer#109]
I see that 3.2.2 version fullscreen not working. 3.2.1 version is work fine. Please resolve the issue.
thanks
**Issues guidelines**

- Please search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

**Comment by mistic100** [comment]
Seriously ?
#83 #96 #104 

I have other things planned before releasing.

**Comment by mistic100** [comment]
Release 3.2.3 includes the fix. sorry for the delay.
