### ISSUE TITLE
plugin:Gallery-plugin wheel event on laptop(like mac), swipe event seem weird

### ISSUE THREAD

**Issue by venmax** [mistic100/Photo-Sphere-Viewer#1090]
### Describe the bug

If TouchPad on laptop will be supported, only add deltaY * 50 to scrollLeft seems not enough, WheelEvent will be triggered too many times

```js
// packages/gallery-plugin/src/GalleryComponent.ts
    handleEvent(e: Event) {
        switch (e.type) {
            case 'wheel':
                this.container.scrollLeft += (e as WheelEvent).deltaY * 50
...
```

### Online demo URL
https://codesandbox.io/s/brave-matsumoto-7j77cd

### Photo Sphere Viewer version

5.4.2

### Plugins loaded

gallery-plugin

### OS & browser

Mac, chrome

**Comment by mistic100** [comment]
So what must be done ?

**Comment by mistic100** [comment]
do you have a video of what happens ?

**Comment by venmax** [comment]
> do you have a video of what happens ?

I fork a demo here (bad usage of same panorama but gallery works):
https://codesandbox.io/s/brave-matsumoto-7j77cd

on TouchPad swipe(mainly left and right), the scrollbar go forward and back, sometimes(swipe fast) back to the first item.

**Comment by mistic100** [comment]
Please provide a video, I do not have a Mac and with a standard pad there is no problem.

disclaimer : this will probably end with "wontfix" and "help needed" because I just cannot debug Apple specifics

**Comment by venmax** [comment]
> Please provide a video, I do not have a Mac and with a standard pad there is no problem.
> 
> disclaimer : this will probably end with "wontfix" and "help needed" because I just cannot debug Apple specifics

Ok, that's fine.

I uploaded a video, in the 4th seconds, I actually do is a 'swipe right' action
https://github.com/mistic100/Photo-Sphere-Viewer/assets/4507022/6a20c838-a09a-4916-96d7-3941405cf07e

**Comment by mistic100** [comment]
I don't think there is a specific peoblem with your track pad, upon testing even when using a standard mouse wheel the scroll distance is way higher than expected.
