### ISSUE TITLE
Intro animation  use EquirectangularTilesAdapter。 the effect is not ideal

### ISSUE THREAD

**Issue by html580** [mistic100/Photo-Sphere-Viewer#1093]
### Describe your problem

Intro animation
Use the Animation helper to create a cool intro.

Intro animation  use EquirectangularTilesAdapter
how to config the animation。

the examples  use load TilesAdapter then the effect is not ideal。

Tile loading is not like a whole.

Will not continuously load tiles.

help to how to config。thanks。

your examples:

const autorotate = viewer.getPlugin(AutorotatePlugin);

viewer.addEventListener('ready', intro, { once: true });

function intro() {
    autorotate.stop();
    viewer.navbar.hide();

    new utils.Animation({
        properties: animatedValues,
        duration: 2500,
        easing: 'inOutQuad',
        onTick: (properties) => {
            viewer.setOption('fisheye', properties.fisheye);
            viewer.rotate({ yaw: properties.yaw, pitch: properties.pitch });
            viewer.zoom(properties.zoom);
        },
    }).then(() => {
        autorotate.start();
        viewer.navbar.show();
    });
}

### Photo Sphere Viewer version

5.4.2

**Comment by mistic100** [comment]
Please explain what is the problem, I see nothing wrong.
