### ISSUE TITLE
EquirectangularTilesAdapter shows vertical line

### ISSUE THREAD

**Issue by rowdy-dowdy** [mistic100/Photo-Sphere-Viewer#1096]
### Describe the bug

When loading begins, the baseUrl image that appears first will have a vertical line at the point where the two edges of the image connect.
![ảnh](https://github.com/mistic100/Photo-Sphere-Viewer/assets/33823245/98116a58-2727-4dca-8819-88e87d1d6ff6)

### Online demo URL

https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html#example

### Photo Sphere Viewer version

5.4.2

### Plugins loaded

EquirectangularTilesAdapter

### OS & browser

Window 11, Edge & Firefox

**Comment by mistic100** [comment]
You can disable "baseBlur" if that bothers you, there is nothing I can do.
