### ISSUE TITLE
Video Layer problem

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1097]
### Describe the bug

Hi Damien,

I am playing a little with the video layers and I found something odd....

I tried first the positioning with a single point (position (one value) + size + anchor) and everything works as expected

![Screenshot 2023-09-30 183023](https://github.com/mistic100/Photo-Sphere-Viewer/assets/97630238/99f4ab5b-d4a3-497b-974b-39d6dbce024b)

I tried then the positioning with the four corners  but the result is kinda strange.
The size (ratio) of the video is almost the same but with four corner type of positioning, the result is as follows.

![Screenshot 2023-09-30 183045](https://github.com/mistic100/Photo-Sphere-Viewer/assets/97630238/d8c0760c-f6cd-4b93-938c-6c71fdbafff1)

The two live examples:

one point positioning

https://www.tadini.it/panorama/test/panorama_suretta.html

four point positioning

https://www.tadini.it/panorama/test/panorama_suretta2.html 

### Photo Sphere Viewer version

5.4.2

### Plugins loaded

marker

### OS & browser

win 11 - chrome 117

**Comment by mistic100** [comment]
The problem arises when the element overlaps the yaw origin (6.13rad to 0.14rad). Nice catch.
