### ISSUE TITLE
video-Image layer blur

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1099]
### Describe the feature

Does it makes sense to add some blur effect in image or video layer  ?
to make the transition between the pano and the layer less  sharp....

![Screenshot 2023-10-02 203223](https://github.com/mistic100/Photo-Sphere-Viewer/assets/97630238/3a32c48e-7309-40cb-b6a4-c4919379f89a)

**Comment by mistic100** [comment]
How to you propose to do that ?

Anyway I don't this the point.

**Comment by haldo98** [comment]
fair point.
