### ISSUE TITLE
Black "pillar" showing up in photoviewer

### ISSUE THREAD

**Issue by jarodium** [mistic100/Photo-Sphere-Viewer#11]
Hello there

My firefox for windows 8 ( latest version of FF ) is showing up a "black pillar" after the image is rendered.

In the following browsers, the script is working properly ( no "black pillar" )

Same windows 8:
Chrome works

MacOSX:
Firefox,Chrome and Safari works.

The link where i'm implementing the viewer is:
http://lifecharcos.lpn.pt/visita_virtual/2/index.html

I am also experiencing the same warning as #7, but it does not mess my viewer in MacOSX
I am using the latest threejs ( rev 73 )

Attached is a printscreen of what I am seeing
![bug_firefox](https://cloud.githubusercontent.com/assets/1470446/12448566/bc2c2b04-bf6e-11e5-8039-215c6beb1bbf.jpg)

I think the bug lies at the edges of the image, that the viewer cannot join them.

Thank you for your time.

**Comment by mistic100** [comment]
And have you tried the fix from  #7 ?
If so and it doesn't change, I can't help you.
Probably you cropped the sphere somehow and the data are falsy, but I do not have the knowledge on this part of the code.
