### ISSUE TITLE
动态修改adapter

### ISSUE THREAD

**Issue by hello-qu** [mistic100/Photo-Sphere-Viewer#1103]
### Describe your problem

当加载多张全景图时，如何在这多张全景图中来回的使用不同的adapter，现在我通过viewer.setPanorama({
adapter :xxx
}),无法修改

### Photo Sphere Viewer version

5.4.3

**Comment by mistic100** [comment]
![Capture](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41597/bdbdc5d3-b702-404f-a4a3-ec6470439a1f)
