### ISSUE TITLE
VirtualTourPlugin

### ISSUE THREAD

**Issue by jinxiangqiang** [mistic100/Photo-Sphere-Viewer#1104]
### Describe the feature

default view，After I drag the Angle of view, the Angle of jump through links also changes. How can I keep the Angle of jump consistent

**Comment by mistic100** [comment]
I don't understand what you are trying to say.

**Comment by jinxiangqiang** [comment]
const defaultView = [
        {yaw: 2.0834613002711686, pitch: -0.43232036370061966,},
        {yaw: 1.6327188471926903, pitch: -0.2050414347219207,},
        {yaw: 1.5341642065649392, pitch: -0.05698154259716137},
        {yaw: 0.10091725142509396, pitch: -0.10651454370497238},
        {yaw: 1.655784154532804, pitch: -0.39752881443295296},
        {yaw: 0.6256754024585988, pitch: -0.24192539721658468},
        {yaw: 2.503374202597148, pitch: -0.3751497645663293},
        {yaw: 0.6685516774452785, pitch: -0.4663671949861987},
        {yaw: 1.250052640205438, pitch: 0.01356115051418083},
        {yaw: 1.3926288881931863, pitch: -0.0619490575354793},
        {yaw: 1.7897179742176172, pitch: -0.02110494936313234},
        {yaw: 1.619400245754127, pitch: 0.1133402400375112},
        {yaw: 1.2060843901872493, pitch: 0.012088799395102434},
        {yaw: 6.09146173448272, pitch: 0.02304564304785872}
      ];

      virtualTour.addEventListener("node-changed", ({ node, data }) => {
        viewer.animate({speed: '10rps', ...defaultView[Number(node.id) - 1]});
      });
     

I want to switch gallery when always in the same perspective, not change，The above implementation will have a rotating process

**Comment by mistic100** [comment]
Did you try to change the [`transitionOptions`](https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#transitionoptions) ?  It allows a lot of liberties (click the "See details" button)

It is really to understand you broken english, especially without a clear example of what you want.

**Comment by jinxiangqiang** [comment]
Sorry, I don't know English。
I set the parameters to ` positionMode: "gps"` Solved my problem，How do I get the current gps location of the dot marker。

**Comment by mistic100** [comment]
I don't know what is the "dot marker"
