### ISSUE TITLE
How I can to disable move camera on tilt axis?

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#1108]
### Discussed in https://github.com/mistic100/Photo-Sphere-Viewer/discussions/1107

<div type='discussions-op-text'>

<sup>Originally posted by **ikiselev1989** October  9, 2023</sup>
Hi! I need disable move camera on tilt and axis, only pan. How i can do this?</div>

**Comment by mistic100** [comment]
@ikiselev1989 use https://photo-sphere-viewer.js.org/plugins/visible-range.html with `verticalRange: [0, 0]`

**Comment by ikiselev1989** [comment]
thanks!
