### ISSUE TITLE
Fullscreen button not working on IOS

### ISSUE THREAD

**Issue by ciadavid** [mistic100/Photo-Sphere-Viewer#111]
I have test the plugin on IOS (Safari, Chrome) and full screen button not working. Nothing happens whe you press the icon.

Is there any solution?

**Comment by mistic100** [comment]
Case already discussed many times https://github.com/mistic100/Photo-Sphere-Viewer/issues/92#issuecomment-280595163

iOS does not support fullscreen at all http://caniuse.com/#feat=fullscreen
