### ISSUE TITLE
container could only set like 'play' or 'player' as string?

### ISSUE THREAD

**Issue by KJRi** [mistic100/Photo-Sphere-Viewer#1113]
### Describe the bug

when I use {Viewer} form '@photo-sphere-viewer/core',I set a string be like `data-${id}` something complicated.Then the Viewer couldn't find the DOM at HTML,which I do create the DOM.

### Online demo URL

https://codesandbox.io/s/cranky-goodall-965hcq?file=/src/index.ts

### Photo Sphere Viewer version

5.4.3

### OS & browser

macOS & Chrome

**Comment by mistic100** [comment]
I think the error is clear enough

> Failed to execute 'querySelector' on 'Document': '12334565737' is not a valid selector.

The thing is HTML ids cannot start with a number, this has nothing to do with PSV.

----

And don't forget to update the stylesheet to give the viewer a size.
