### ISSUE TITLE
GalleryPlugin, lose current item after calling setItems twice

### ISSUE THREAD

**Issue by venmax** [mistic100/Photo-Sphere-Viewer#1114]
### Describe the bug

I using VirtualTourPlugin with gallery, when run virtualTourPlugin's setItems twice, galleryPlugin active status will lost. Please view in demo.

I think maybe galleryPlugin's setItems should receive a startNodeId also?

```typescript
    setItems(items: GalleryItem[], handler?: (id: GalleryItem['id']) => void, startNodeId?: string) {
       //...
    }
```

### Online demo URL

https://codesandbox.io/s/vibrant-maxwell-gwn3m3?file=/src/index.ts

### Photo Sphere Viewer version

5.4.3

### Plugins loaded

VirtualTourPlugin, GalleryPlugin

### OS & browser

Mac, chrome

**Comment by mistic100** [comment]
thanks
