### ISSUE TITLE
Embedding a Youtube Video player (Iframe) in the Viewer

### ISSUE THREAD

**Issue by agyson** [mistic100/Photo-Sphere-Viewer#1118]
### Describe the feature

Hello,

I noticed that Marzipano allows embedding of YouTube videos in their viewer, as seen here: [Marzipano: Embedded Hotspots](https://www.marzipano.net/demos/embedded-hotspots/). Is it possible to achieve the same with this viewer? If so, could you guide me on how to do it?

Thank you.

**Comment by mistic100** [comment]
No it is not possible and not planned. Why don't you just use Marzipano ?

**Comment by agyson** [comment]
It seems that Marzipano is no longer actively maintained. I'm interested in developing my project using your library, given its active development status.

I've noticed you've introduced the new "element" type for markers in 5.4.0. Have you considered adapting it into a rectangular placeholder?

**Comment by mistic100** [comment]
I have absolutely no clue of the math involved to make an HTML element behave like the `imageLayer` and `videoLayer` markers (those are simple because entirely handled by ThreeJS) and don't really want to do it.

**Comment by Mr-Kanister** [comment]
I don't know if it's implementable, but just wanted to share an interesting finding: https://codepen.io/orvilleChomer/pen/mYBJzE

**Comment by mistic100** [comment]
This uses the CSS3DRenderer, which handles the transformations.

It might be possible to have second rendered on top of the WebGL main one use by PSV, only containing these objects.

**Comment by mistic100** [comment]
I am working on an new "elementLayer" which will allow iframe (or any element like the existing `element` markers) renderer in the 3D scene.

**Comment by mistic100** [comment]
The `elementLayer` marker is available for testing in version 5.8.0-alpha.1

Exemples : https://github.com/mistic100/Photo-Sphere-Viewer/blob/e1bd5a7674fcb4406bfc94f47197f8c82af546ca/examples/plugin-markers-layers.html#L43-L68

**Comment by mistic100** [comment]
online demo https://photo-sphere-viewer.js.org/demos/markers/youtube-element.html
