### ISSUE TITLE
Issue with wrapping the image

### ISSUE THREAD

**Issue by IceyBlueFire** [mistic100/Photo-Sphere-Viewer#112]
I've been playing with the quick download, got everything working properly, dug through all the settings (seemingly), but can't figure out how to get the image to loop around smoothly.  Right now it gets to the edge of the image and just bounces, and rotates back.  How do i make it so that the image wraps around like the demos on the website show?

**Comment by mistic100** [comment]
remove longitude_range and latitude_range

**Comment by IceyBlueFire** [comment]
Thank you! I knew it had to be something i was overlooking.
