### ISSUE TITLE
@photo-sphere-viewer/equirectangular-tiles-adapter

### ISSUE THREAD

**Issue by wa0u** [mistic100/Photo-Sphere-Viewer#1123]
### Describe the bug

There is a black line during initialization when use @photo-sphere-viewer/equirectangular-tiles-adapter. 

### Photo Sphere Viewer version

5.1.7

### OS & browser

Chrome

**Comment by mistic100** [comment]
https://github.com/mistic100/Photo-Sphere-Viewer/issues/1096
