### ISSUE TITLE
tiles bug

### ISSUE THREAD

**Issue by ROTblog** [mistic100/Photo-Sphere-Viewer#1127]
### Describe the bug

When using the CubemapTilesAdapter adapter and a 200 million pixel picture for cutting use, the loading will be very slow, if the iPhone 13 Pro max mobile phone loading for a period of time will automatically refresh the page, and there is a serious jagged effect.

https://photo-sphere-viewer.js.org/guide/adapters/cubemap-tiles.html

https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html

Is there any way to successfully load a high-resolution panorama, such as 20000 x 10000 pixels？

### Photo Sphere Viewer version

5.4.4

### OS & browser

chrome latest/Safari ios latest

**Comment by mistic100** [comment]
Do you have an actual demo ? What is your tiles size ?

Disclaimer : there will **not** be any deep optmization of this adapter

Did you try the multi-tiles mode ? If you request your device to load too many tiles at once, of course it will lag.  
Exemple here with with a 300 millions pixels panorama https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/examples/adapter-equirectangular-tiles.html#L71-L107

**Comment by ROTblog** [comment]
Thank you very much for your reply, I view your reply in the link, I clone to the local operation, with mobile phone access will not be stuck, I learn from you. 

I check documents https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html#panorama-options, at the bottom of the sample is as follows
`magick.exe panorama.jpg \
  -crop 750x750 -quality 95 \
  -set filename:tile "%[fx:page.x/750]_%[fx:page.y/750]" \
  -set filename:orig %t \
  %[filename:orig]_%[filename:tile].jpg`
  
  And https://photo-sphere-viewer.js.org/guide/adapters/cubemap-tiles.html#example is also same as below

`magick.exe front.jpg \
  -crop 750x750 -quality 95 \
  -set filename:tile "%[fx:page.x/750]_%[fx:page.y/750]" \
  -set filename:orig %t \
  %[filename:orig]_%[filename:tile].jpg`
  
  How is your 300 millions pixels panorama sliced and name the pieces （filename）?

**Comment by mistic100** [comment]
the filename structure is in the `tileUrl` of the example

```js
return `${baseUrl}sphere-tiles-24k/tile_${level}_${col}_${row}.jpg`;
```

the ImageMagick code int the documentation is just an example, you have to adapt it to your needs (and in this case, run it multiple times with different parameters)

**Comment by ROTblog** [comment]
I want the user to be able to upload the image, and the server to help the user cut the image like ImageMagick, and then display it using the Photo-Sphere-Viewer.

` levels: [
                            {
                                width: 6144,
                                cols: 16,
                                rows: 8,
                                zoomRange: [0, 30],
                            },
                            {
                                width: 12288,
                                cols: 32,
                                rows: 16,
                                zoomRange: [30, 70],
                            },
                            {
                                width: 24576,
                                cols: 64,
                                rows: 32,
                                zoomRange: [70, 100],
                            },
                        ],
`

Is the original image compression divided into 3 levels


Level 1, width 6144px cut so that each piece is 6144/16=384px


Grade 2, width 6144*2=12288px cut so that each piece is 12288/32=384px

Level 3, width 6144*3=24576px cut so that each piece is 24576/64=384px

Finally, make sure each tile is smaller than 1024px

**Comment by ROTblog** [comment]
您的原图是24576px吗？

**Comment by mistic100** [comment]
yes

**Comment by ROTblog** [comment]
Thank you very much. The last question I have is how to cut a 2:1 panorama into 6 cubes and name the file 'left'|'front'|'right'|'back'|'top'|'bottom'. Like this https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/examples/adapter-cubemap-tiles.html#L90-L97

**Comment by mistic100** [comment]
Why don't you search that on Google ? There is this plugin on Photoshop http://www.flamingpear.com/flexify-2.html and ImageMagick also as transformations, search their documentation.

**Comment by ROTblog** [comment]
I've been searching for, I try to use the method of the ImageMagick http://www.fmwconcepts.com/imagemagick/cube2sphericalpano/index.php, but the effect is not ideal, When displayed using adapter-cubemap-tiles, the top and bottom orientation is found to be wrong.



It was also found that the cube2sphericalpano was extremely slow when cutting large pixel images, and the cpu was 13th Gen Intel(R) Core(TM) i7-13700.



In the end I still use this adapter, https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html, this is simple and I have to run it

**Comment by mistic100** [comment]
If you top and bottom tiles are reversed, use the `flipTopBottom` option https://photo-sphere-viewer.js.org/guide/adapters/cubemap.html#separate-files
