### ISSUE TITLE
Possibilty to add overlay when loading new sphere

### ISSUE THREAD

**Issue by ChristianLJ** [mistic100/Photo-Sphere-Viewer#113]
When loading the first sphere i see the grey background with the loader as expected.

Afterwards, when a user clicks on a link i call setPanorama() with a new image URL, like below:
```javascript
this.PSV.setPanorama(
    this.getSphereUrl(sphereID),
        {
            longitude: Math.PI,
            latitude: 0,
        },
        false
);
```
While loading the new sphere the user sees the grey loader but the background is not grey anymore.
It is the old sphere that is visible.

It is possible to add a standard overlay (background) on top of the sphere when calling setPanorama(), so the user doesn't see the old image?

**Comment by mistic100** [comment]
Actually the background is still here but under the image.

You could hide it with `this.PSV.canvas_container.style.opacity = 0;` and restore the opacity when the panorama is loaded (`setPanorama` returns a promise resolved when the new texture is ready)

**Comment by mistic100** [comment]
Now the previous sphere will be hidden when loading a new sphere without transition
