### ISSUE TITLE
谷歌浏览器（版本 81.0.4044.113）MarkersPlugin 绘制出的点无法获得translate位置属性

### ISSUE THREAD

**Issue by koyoyoo** [mistic100/Photo-Sphere-Viewer#1130]
### Describe the bug

在谷歌浏览器版本 81.0.4044.113（正式版本）下

MarkersPlugin 绘制出的点无法获得translate位置属性，如下图：
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/10239439/09509676-bf2c-4a5a-becf-1d661321c0c5)

这会导致所有点全都叠在屏幕左上角。

### Photo Sphere Viewer version

5.4.4

### OS & browser

谷歌浏览器版本 81.0.4044.113

**Comment by mistic100** [comment]
I don't speak chineese
