### ISSUE TITLE
video Marker 与 文本Marker叠加时，点击文本, 监听select-marker 只会触发 video marker, 希望触发文本marker点击事件

### ISSUE THREAD

**Issue by tjw-javen** [mistic100/Photo-Sphere-Viewer#1131]
### Describe the bug

video Marker 与 文本Marker叠加时，点击文本, 监听select-marker 只会触发 video marker 希望触发文本marker点击事件

### Photo Sphere Viewer version

5.4.4

### OS & browser

browser

**Comment by mistic100** [comment]
I don't speak chineese
