### ISSUE TITLE
video Marker and html Marker 

### ISSUE THREAD

**Issue by tjw-javen** [mistic100/Photo-Sphere-Viewer#1132]
### Describe the bug

When the video Marker and html Marker are superimposed, clicking the html Marker and listening to select-marker will only trigger the click event of the video marker that the html Marker  hopes to trigger

### Photo Sphere Viewer version

5.4.4

### OS & browser

browser

**Comment by mistic100** [comment]
Thank you, I fixed this issue as well as added a `zIndex` option.

Node : the zIndex will **not** allow to draw the video on top of the HTML marker, it will only only allow to order imageLayer/videoLayer and html/image/element, in two distinct groups
