### ISSUE TITLE
Video marker 

### ISSUE THREAD

**Issue by tjw-javen** [mistic100/Photo-Sphere-Viewer#1133]
### Describe the bug

The video Marker user-defined data does not take effect

### Photo Sphere Viewer version

5.4.4

### OS & browser

browser

**Comment by tjw-javen** [comment]
user-defined data: {
        loop: false,
        muted: true,
        autoplay: true
      },

**Comment by mistic100** [comment]
Because that is not what those data are for, it says "Any custom data you want to attach to the marker.", that does not mean it will be used to configure the video.

If you can to change the video config use this

```js
markersPlugin.getMarker('my-video').video.loop = false;
```
