### ISSUE TITLE
The AutorotatePlugin stop method does not take effect

### ISSUE THREAD

**Issue by tjw-javen** [mistic100/Photo-Sphere-Viewer#1134]
### Describe the bug

Set autostartOnIdle:true,autostartDelay: 3000, then call AutorotatePlugin stop method does not work

### Photo Sphere Viewer version

5.4.4

### OS & browser

browser

**Comment by mistic100** [comment]
The stop() method is here to stop the animation when it is running, it makes sense it doesn't do anything when the animation is not already running.

If for some reason you want to disable the autostart while configured, use the `setOption()` method

```js
viewer.getPlugin('autorotate').setOption('autostartOnIdle', false);
```

**Comment by tjw-javen** [comment]
thank you

**Comment by jhonjamesdc** [comment]
Hello, I am setting the property.
[AutorotatePlugin, {
                    autostartOnIdle: false,
                }],
but it still starts to rotate as soon as I open the panorama
