### ISSUE TITLE
Support for 360 view of an object ?

### ISSUE THREAD

**Issue by evanlegamer** [mistic100/Photo-Sphere-Viewer#1135]
### Describe your problem

Bonjour, juste une question

Est-ce que votre librairie supporte de faire une vue 360 d'un objet, par exemple une voiture ?

example : https://spins.spincar.com/vroommanheimnewengland/wddzf4kb9ha085539#hidecarousel!disabledrawer!disableautospin!disablewatermark!hidevehiclehits!stscolor=0F3A7B%2CFC4349%2CE7131A

Hello, just a question

Does your library support creating a 360 view of an object, for example a car?

### Photo Sphere Viewer version

5.4.4

**Comment by mistic100** [comment]
Bonjour
non ce n'est pas le but de cette librairie (votre exemple n'est meme pas une vue 3d c'est juste un slideshow amélioré)
