### ISSUE TITLE
video markers problem

### ISSUE THREAD

**Issue by tjw-javen** [mistic100/Photo-Sphere-Viewer#1136]
### Describe the bug

When the video markers and screen (width or height) are the same video markers will disappear, rotate the scene, video markers are not the same screen (width or height), video markers will appear

### Photo Sphere Viewer version

5.4.4

### OS & browser

browser

**Comment by tjw-javen** [comment]
image marker also has this problem

**Comment by tjw-javen** [comment]
marker.state.positions3D.some((vector) => this.viewer.dataHelper.isPointVisible(vector))   is this code problem

**Comment by mistic100** [comment]
thanks
