### ISSUE TITLE
How to draw marker like polyline,square and polygon

### ISSUE THREAD

**Issue by rohittb** [mistic100/Photo-Sphere-Viewer#1137]
### Describe your problem

Hello Team,

Is there any way we can draw a marker using marker plugin or any other plugin we want to draw square,polyline and polygon . i know we can using giving parameters but is there any way to draw .

### Photo Sphere Viewer version

5.4.4

**Comment by mistic100** [comment]
I don't understand your question. What do you want to do exactly ? What you already tried ?
