### ISSUE TITLE
Video Markers problem

### ISSUE THREAD

**Issue by tjw-javen** [mistic100/Photo-Sphere-Viewer#1141]
### Describe the bug

When the video is placed near the lower middle of the window, the video map in the lower left corner is distorted
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/36066822/38932c65-7e61-4d79-9962-6970eb6e62b9)

### Photo Sphere Viewer version

5.4.4

### OS & browser

browser

**Comment by mistic100** [comment]
You already reported this issue #1133
