### ISSUE TITLE
Can't loading panorama on IOS 16.7

### ISSUE THREAD

**Issue by tommasocisternino** [mistic100/Photo-Sphere-Viewer#1144]
### Describe the bug

I'm using the Virtual Tour Plugin, if I navigate with other devices, like PC or Android phone all run perfectly, but in IOS 16.7 the panorama can't be loaded

### Online demo URL

https://tommy-cisternino-testenv.site/

### Photo Sphere Viewer version

5.4.4

### Plugins loaded

VirtualTourPlugin

### OS & browser

IOS 16.7 chrome,safari,google app (?) iPhone X
Android 12 SKQ1.21103.001  Chrome Redmi

**Comment by mistic100** [comment]
Unfortunately I don't have an Apple device. I cannot really provide help.

I suggest you launch a debugging session I try to check browsers logs, http errors, etc.

**Comment by tommasocisternino** [comment]
Not working even in Android 12 sqk1.2110 (looks like to be one of the last version of Android 12 in 2023)

**Comment by tommasocisternino** [comment]
I don't have an iPhone device with ios 16.7 too. The preson wich reported to me the bug lives 700km away from me so i can't debug. I have an iPhone 13 with  IOS 17 too but it works

**Comment by mistic100** [comment]
I don't have an Android 12 either.

I'll keep this issue of others can contribute to the debuging but there is nothing I can do.

**Comment by tommasocisternino** [comment]
I apriciate that!

I'll try to test with other devices too and i'll update the list.

**Comment by tommasocisternino** [comment]
Update:
Not working on Safari MAC OS 14.1.1, but is working in Chrome on the same machine. I recovered some logs.

That's strange.
The application is built in Laravel/InertiaJS/React with the ReactPhotoSphere package.

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/71891129/063842e3-2152-40c7-9a14-9f8319b0f2c1)

**Comment by mistic100** [comment]
For me the error is clear : this is a CORS issue, it might not be totally configured correctly as expected by Safari.
