### ISSUE TITLE
Marker Show Error

### ISSUE THREAD

**Issue by html580** [mistic100/Photo-Sphere-Viewer#1145]
### Describe the bug

https://photo-sphere-viewer.js.org/demos/markers/hover-scale.html

Open the link above in the mobile browser, and all marker icon will be displayed in the upper right corner, which cannot display the corresponding position correctly. But when the marker icon is turned on on the computer, it displays normally.
![0ba6d166e7aa8f5a58583bf11a617c8](https://github.com/mistic100/Photo-Sphere-Viewer/assets/4509324/86959bfa-c652-46cb-86c9-24dbacd23af4)

### Online demo URL

https://photo-sphere-viewer.js.org/demos/markers/hover-scale.html

### Photo Sphere Viewer version

5.4.4

### OS & browser

android

**Comment by mistic100** [comment]
No problem here

 ![Screenshot_2023-11-09-11-34-33-886_org.mozilla.firefox.jpg](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41597/3a6aaff9-dbf7-4583-afc1-ca0ccfc09c7f)

You might have a network issue which cause the stylesheet to not be loaded.

**Comment by html580** [comment]
when i use uc browser
![727f4cefb8a6e9dbca3630d19cdbf38](https://github.com/mistic100/Photo-Sphere-Viewer/assets/4509324/1bf35209-0aea-4611-b62b-c5c7f1f532b2)

https://www.[kuqixiu.com/test.mp4](https://www.kuqixiu.com/test.mp4)

**Comment by html580** [comment]
the tooltip position is normal, but the icon is not normal

**Comment by html580** [comment]
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/4509324/399c0146-3e0b-45f5-b9df-7fc8d19480f8)
web browser is normal

**Comment by mistic100** [comment]
You are welcome to try to debug it on your device and find what the problem is. As I don't have the issue on mine, there is nothing I can do.

**Comment by html580** [comment]
![1699529800943](https://github.com/mistic100/Photo-Sphere-Viewer/assets/4509324/992c40fa-5505-4287-8a4d-48fe6d01964d)
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/4509324/eb210a03-1c23-4903-b90a-ec3712e027a8)

use Photo-Sphere-Viewer v4  
the icon is normal。it use  transform: translate3d(892px, 110px, 0px);
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/4509324/35a61520-2b23-469b-8800-385278e62c09)

**Comment by html580** [comment]
![9c23160742b5cd1a834eb8398943f9a](https://github.com/mistic100/Photo-Sphere-Viewer/assets/4509324/74cc37a5-c266-4c9a-a238-d36bd0bcc4e5)
you  can fixed the bug: transform: translate3d

**Comment by mistic100** [comment]
Okay so this is the same as https://github.com/mistic100/Photo-Sphere-Viewer/issues/1082

The market of chinese browsers not supporting this feature is not big enough for me to make changes.

https://caniuse.com/?search=translate

**Comment by zhangrlhaha** [comment]
这个问题我测试过了是因为translate: 717px 121px; 的问题，使用transform:translateX(20px 20px)  这样就可以解决，此问题在鸿蒙3系统浏览器上已经测试过，但是源码我不会改

**Comment by html580** [comment]
> 这个问题我测试过了是因为translate: 717px 121px; 的问题，使用transform:translateX(20px 20px) 这样就可以解决，此问题在鸿蒙3系统浏览器上已经测试过，但是源码我不会改

I can make changes to the source code, but I suggest that the author can support older versions of browsers. Because too many are still old versions of browsers, otherwise they would have to be changed every time.

![image](https://github.com/user-attachments/assets/87512bf9-d0d7-498a-8c72-4cc8c13080d4)
