### ISSUE TITLE
Switch adapter by click navbar button

### ISSUE THREAD

**Issue by code-savior** [mistic100/Photo-Sphere-Viewer#1146]
### Describe the feature

Switch adapter by click navbar button

**Comment by code-savior** [comment]
So we can switch from Equirectangular adapter to Little planet
or we also can switch from Equirectangular adapter to EquirectangularVideoAdapter
thx :)

**Comment by mistic100** [comment]
Sorry this cannot be done without some heavy rework. I can destroy the viewer and recreate it.

**Comment by code-savior** [comment]
Thank you for your reply:)
so now we even can't use little planet effect in video scene
hope to make the implementation of the little planet effect more independent.

**Comment by code-savior** [comment]
Sorry,i found it
we can simulate the little planet effect by the fisheye mode, even in the video adapter
great job!👍
