### ISSUE TITLE
grunt

### ISSUE THREAD

**Issue by victor-geere** [mistic100/Photo-Sphere-Viewer#115]
C:\MAMP\htdocs\mistic100-photosphere>grunt

Loading "Gruntfile.js" tasks...ERROR

> SyntaxError: C:\MAMP\htdocs\mistic100-photosphere\node_modules\simple-cli\node_modules\opted\lib\opted.js:15
>         flag = `${flag}=${v}`;
>                ^
> Unexpected token ILLEGAL

**Comment by mistic100** [comment]
you need node.js => 6 to have ECMAScript 6 support

**Comment by mistic100** [comment]
Next time you see an error in a node module (here simple-cli), please open the issue on the repo of the said module, not on a project using it.
