### ISSUE TITLE
How to implement OverlaysPlugin with TypeScript and EquiRectangularTilesAdapter

### ISSUE THREAD

**Issue by juanbrk** [mistic100/Photo-Sphere-Viewer#1155]
### Describe the bug

I am using MarkersPlugin, CompassPlugin, VisibleRangePlugin and GalleryPlugin and since the introduction of [OverlaysPlugin](https://photo-sphere-viewer.js.org/plugins/overlays.html#overlaysplugin) I would like to give it a try and see if it serves the purpose of solving one issue that I currently have with my project. 

The thing is that I can't manage to get this plugin working. I've tried to implement It the same way I did with the other plugins and by following the [configuration](https://photo-sphere-viewer.js.org/plugins/overlays.html#configuration) and [example](https://photo-sphere-viewer.js.org/plugins/overlays.html#example) available on the Photo-Sphere web with no luck.

This is what My viewer configuration looks like with the error I'm getting on `OverlaysPlugin` implementation:

```
import { OverlaysPlugin } from '@photo-sphere-viewer/overlays-plugin';
...

const viewer = new Viewer({
      adapter: [
        EquirectangularTilesAdapter,
        {
          backgroundColor: 'rgb(0, 0, 0)',
        },
      ],
 .
  .
   .,
plugins: [
        [MarkersPlugin, { clickEventOnMarker: true }],
        [CompassPlugin, { backgroundSvg: RAW_COMPASS }],
        [
          VisibleRangePlugin,
          {
            verticalRange: [-0.5, 0.38],
          },
        ],
        [GalleryPlugin, { items: [] }],
        [
          OverlaysPlugin,
          {
            overlays: [
              {
                id: 'waypoint',
                path: '/assets/circle.jpg',
                opacity: '.8',
                zIndex: 1,
              },
            ],
          },
        ],
      ],
 .
  .
   .
});
```

And this is the error I get when trying to implement it using this configuration:

```
// ESLint error 

Type 'typeof OverlaysPlugin' is not assignable to type 'PluginConstructor'.
  Types of construct signatures are incompatible.
    Type 'new (viewer: Viewer, config?: OverlaysPluginConfig | undefined) => OverlaysPlugin' is not assignable to type 'new (viewer: Viewer, config?: any) => AbstractPlugin<any>'.

// Console error

config.ts:213 Uncaught PSVError: An undefined value was given for plugin 4.
    at config.ts:213:23
    at Array.map (<anonymous>)
    at Object.plugins (config.ts:206:24)
    at parser (psv.ts:414:33)
    at new Viewer (Viewer.ts:105:23)
    at setup-image-viewer.hook.ts:186:25
    at invokePassiveEffectCreate (react-dom.development.js:23487:20)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
```

I am also getting to use all the other plugins by doing the following: 

```
  const compassPlugin = viewer.getPlugin<CompassPlugin>(CompassPlugin);
  const markersPlugin = viewer.getPlugin<MarkersPlugin>(MarkersPlugin);
```

But when I do It with `OverlaysPlugin` an error is also shown:

```
  const overlaysPlugin = viewer.getPlugin<OverlaysPlugin>(OverlaysPlugin)

// ESLint Error
Type 'OverlaysPlugin' does not satisfy the constraint 'AbstractPlugin<any>'.
  Property 'viewer' is protected but type 'AbstractPlugin<TEvents>' is not a class derived from 'AbstractPlugin<TEvents>'
```

I've updated all my plugins to the latest version to see if that had anything to do with It but nothing seems to work. 

### Plugin versions:

```
@photo-sphere-viewer/compass-plugin@5.4.4
├── @photo-sphere-viewer/core@5.4.4
├── @photo-sphere-viewer/equirectangular-tiles-adapter@5.4.4
├── @photo-sphere-viewer/gallery-plugin@5.4.4
├── @photo-sphere-viewer/markers-plugin@5.4.4
├── @photo-sphere-viewer/overlays-plugin@5.5.0-alpha.1
├── @photo-sphere-viewer/visible-range-plugin@5.4.4
```

### Photo Sphere Viewer version

5.4.4

### Plugins loaded

@photo-sphere-viewer/compass-plugin@5.4.4 ├── @photo-sphere-viewer/core@5.4.4 ├── @photo-sphere-viewer/equirectangular-tiles-adapter@5.4.4 ├── @photo-sphere-viewer/gallery-plugin@5.4.4 ├── @photo-sphere-viewer/markers-plugin@5.4.4 ├── @photo-sphere-viewer/overlays-plugin@5.5.0-alpha.1 ├── @photo-sphere-viewer/visible-range-plugin@5.4.4

### OS & browser

macOS Sonoma Version 14.0  119.0.6045.123 (Build oficial) (arm64)

**Comment by mistic100** [comment]
Just use the same `5.5.0-alpha.1` version for everything.

**Comment by mistic100** [comment]
In version 5.5.0 final I will declare dependencies as peers & add a runtime version check between the core and the plugins
