### ISSUE TITLE
[Virtual Tour] Hover events for arrows

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#1157]
### Describe the feature

As now, only event available for Virtual Tour Plugin is `node-changed`. As a third-party, you can't access to events related to hovering over arrows/markers. Having such events could be helpful for rich interactions with other components.

For example, this could allow to show on a map where the picture is for a given arrow you're hovering. Helpful for previewing where you will land on a map :grinning: 

This would consist mainly on two events :
- `mouseenter` : cursor has entered over a single arrow
- `mouseleave`: cursor has gone from a single arrow

With each event sending data associated to arrow hovered (at least picture ID, but could be more if possible).

Implementing could be not too complex, as code is already structured like that (`onEnterMarker/Object` and `onLeaveMarker/Object`).

### Alternatives you've considered

A _hack_ of Virtual Tour prototype can lead to same result:

```js
const origVTourEnter = this._myVTour.__onEnterObject.bind(this._myVTour);
this._myVTour.__onEnterObject = (m, vp) => {
	console.log("Entered", m.userData.tourLink);
	origVTourEnter(m, vp);
};
```

But this is far less robust to PSV version changes, and less simpler for third party to implement.

### Additional context

I'm still working on GeoVisio/Panoramax project, and we started to work on going to pictures nearby, out of an ongoing sequence pictures (like taken by someone else, or at another date). The idea is to show on mini map where picture is for an hovered arrow. This will be helpful on complex intersections or in places where many sequences were taken.

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1349014/b0ebff07-871f-4f41-8e99-2f3a51427084)

Thanks again for making this greatly helpful library :clap:

**Comment by mistic100** [comment]
The default integration with the map-plugin already has somethiong similar.

Added the two events for custom integrations.

**Comment by PanierAvide** [comment]
Once again, a fast and efficient implementation, thanks ! :grinning:
