### ISSUE TITLE
.hdr support

### ISSUE THREAD

**Issue by ngocducdim** [mistic100/Photo-Sphere-Viewer#1158]
### Describe the feature

Hi, does this library support .hdr file? Thanks

**Comment by mistic100** [comment]
If I find an easy solution to allow to use any Three.js loaders like the RGBELoader and the EXRLoader it could be possible.

**Comment by mistic100** [comment]
Doing so requires some configuration on the WebGL Renderer (tone mapping), I don't really like adding such exotic settings.

HDR/EXR files are incredibly huge, do you plan to use on the web ? If so I think you'd better do the tone mapping to sRGB JPEG yourself.

**Comment by ngocducdim** [comment]
Thanks for the support!
