### ISSUE TITLE
VirtualTourPlugin support tiles 

### ISSUE THREAD

**Issue by missBlueWhite** [mistic100/Photo-Sphere-Viewer#1168]
### Describe your problem

In VirtualTourPlugin ,i change the nodes's panorama from string to object. i want VirtualTourPlugin support tiles.
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/130877626/46eb5b24-38aa-43ca-8dbe-d62ae02f524d)
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/130877626/5f315a8e-63da-4994-8a4c-78b87a004419)

### Photo Sphere Viewer version

5.5.0

**Comment by Elius94** [comment]
Ok, this is a issue of CodeSandbox.

You only have to edit your Viewer class adding `adapter: EquirectangularTilesAdapter,` and it should work.

**Comment by missBlueWhite** [comment]
thanks   very much!  i forget  EquirectangularTilesAdapter.
