### ISSUE TITLE
The image quality will be much worse in H5

### ISSUE THREAD

**Issue by NiKlaus-K** [mistic100/Photo-Sphere-Viewer#1171]
### Describe your problem

Using plugins in H5, picture quality is degraded.The image is about 40MB and the pixel size is 20000 × 10000.When a PC accesses a web page, the image quality is normal.
Are there any parameters or methods that can handle this.

### Photo Sphere Viewer version

5.5.0

**Comment by mistic100** [comment]
Smartphones have a maximum texture size of 4096 pixels, there is nothing that can be done to change that.

You can use the tiles adapter to mitigate the issue https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html
