### ISSUE TITLE
is there is any way to show custom error message in toast

### ISSUE THREAD

**Issue by Dhanushraj1** [mistic100/Photo-Sphere-Viewer#1173]
### Describe your problem

instead of showing error message like this ; i like to show my custom error in toast message is there is any way ??? 
![Screenshot from 2023-12-11 12-53-55](https://github.com/mistic100/Photo-Sphere-Viewer/assets/113611638/da7a9227-6f92-4d03-a24f-c525f8b6a3e8)

### Photo Sphere Viewer version

5.4.4

### Plugins loaded

VirtualTourPlugin,markerPlugin

### Additional context

i am using react-photo-sphere-viewer : 4.0.2-psv5.4.4

**Comment by mistic100** [comment]
This display is not from Photo Sphere Viewer at all ! This is from your build utility because you have un uncaught exception. It probably isn't visible in production mode (only in the console).

However this error should not exist, please create a demo https://codesandbox.io/

**Comment by Dhanushraj1** [comment]
i am getting this error because i am sending same name for two nodes  
i need a **.catch , onError** are something to get if there is any errors , is there is any method to do that ??

**Comment by mistic100** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

**Comment by mistic100** [comment]
Is your use case legit ? Do you really want to have two links to the same node ?

If so I can make a change in the markers generation to allow duplicates by altering the generated id
https://github.com/mistic100/Photo-Sphere-Viewer/blob/b1cade59ac87d5b3eed9da72bc14494cd28ba768/packages/virtual-tour-plugin/src/VirtualTourPlugin.ts#L530-L548
