### ISSUE TITLE
[Support]: Adding different 3D arrow models to the Virtual Tour Plugin and changing their vertical position

### ISSUE THREAD

**Issue by mete-cozer** [mistic100/Photo-Sphere-Viewer#1177]
### Describe your problem

Hi,

I am developing a web application using React library (https://github.com/Elius94/react-photo-sphere-viewer) and the Virtual Tour Plugin, but I have not been able to customize or change the 3D arrow models and give specific values to their vertical position. Can you provide information on how I can do this?

Best Regards

### Photo Sphere Viewer version

5.5.0

### Plugins loaded

Virtual Tour Plugin

**Comment by mistic100** [comment]
This is not possible. I don't not really plan to allow to change the model.
