### ISSUE TITLE
10MB size limit in chromium browsers

### ISSUE THREAD

**Issue by FuJa0815** [mistic100/Photo-Sphere-Viewer#1178]
### Describe the bug

There seems to be some kind of 10MB size limit for the fetch API on (at least; I haven't tested more browsers) chrome and edge. Firefox handles these huge images well.

The only error in the console is `TypeError: Failed to fetch`, but checking the network tab in the inspector shows that the request succeeded.

This can be replicated by uploading a huge image on https://photo-sphere-viewer.js.org/playground.html

I am not sure where this 10MB limit comes from, I haven't found anything online, but running `fetch('/hugepano.jpg').then(r => r.blob()).then(c => console.log(c))` also fails with the same error. I am unsure if this is even fixable.

### Photo Sphere Viewer version

5.5.0

### OS & browser

Chrome

**Comment by mistic100** [comment]
I have no problem loading a 30Mo and 65m files on both Chrome and Edge. 

If you have the same issue with your one-liner example it's not a problem with PSV.

**Comment by FuJa0815** [comment]
I am using Chrome Version 120.0.6099.110 (Official Build) (64-bit) on Windows 10 without any extensions. I also hit that limit on another Windows machine

**Comment by mistic100** [comment]
Perhaps it is a problem with your network. Anyway you proved yourself it is not a problem with the lib.

You can try tiling https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html
