### ISSUE TITLE
Safari browser crashes and reloads the page

### ISSUE THREAD

**Issue by NiKlaus-K** [mistic100/Photo-Sphere-Viewer#1180]
### Describe the feature

I recently ran into a problem with Photo-Sphere-Viewer. On the iphone platform, opening Photo-Sphere-Viewer causes the page to reload and opening it again brings up a crash screen.

I thought it was due to memory overflow, I did all kinds of debugging and found that there is always some memory not reclaimed after destory, so every time I open it, it will cause some memory to be left behind.

I found the page crash problem and solution in issues, but since my Photo-Sphere-Viewer is put into a popup component, I destroy the whole component via v-if, and I think it's not the same as the situation mentioned in issues. But then I realized that it was indeed still caused by the destory not being handled cleanly. Multiple new Viewer will inevitably lead to memory overflow, even if destory is used.

So I would suggest to add some notes in the documentation of new Viewer, or destory, suggesting that destory is not actually clearing the memory of Three.js, and that if you need to switch or hide Photo-Sphere-Viewer multiple times, you can do it by going to the setting of the panorama.

Finally, the plugin works great and the examples are very helpful!

**Comment by mistic100** [comment]
This was once indicated in the the documentation. I had a new issue every month asking why I don't not clean the memory totally ? How can this be fixed ? (and generally with off topic problems).

The fact is I do everything I can regarding ThreeJS API, so I decided to remove this informations from the documentation.

**Comment by code-savior** [comment]
Can we  clean the memory manually？
