### ISSUE TITLE
When using Equirectangular tiles, the parameter baseUrl is recommended and needs a low-resolution panoramic slice. May I ask what resolution can be set as the parameter of baseUrl

### ISSUE THREAD

**Issue by jiechengyang** [mistic100/Photo-Sphere-Viewer#1181]
### Describe the feature

Hello, Sir.
When using Equirectangular tiles, the parameter baseUrl is recommended and needs a low-resolution panoramic slice. May I ask what resolution can be set as the parameter of baseUrl

**Comment by mistic100** [comment]
I don't understand your question. Do you ask what is the recommended resolution of the low-resolution panorama ? It is entirely your decision, it impacts the initial loading time of the viewer (a target filesize of 500Ko - 1Mo is nice)
