### ISSUE TITLE
Equirectangular tiles load: using ImageMagick generate tiles problem

### ISSUE THREAD

**Issue by jiechengyang** [mistic100/Photo-Sphere-Viewer#1184]
### Describe the feature

Hello, sir, I’m here to bother you again. Today I need to ask you about a problem encountered when loading Equirectangular tiles using the ImageMagick tool.
When I use the following command to generate tiles:
```shell
magick /12/19/1702974122.jpg \
  -crop 416x416 -quality 95 \
  -set filename:tile "%[fx:page.x/416]_%[fx:page.y/416]" \
  -set filename:orig "%t" \
  "uploads/scene/test/cp_%[filename:tile].jpg"
```
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/33148475/ef1983a1-1dd9-47dc-9843-93f3fb05b4b7)

The panoramic image I used was a demo image downloaded from the photo-sphere-viewer website. Then I used the sample program to load the panorama. I encountered a different effect from the official website demo.

```js
    initPanorama() {
      let panorama = this.currentScene.panoramaUrl
      if (parseInt(this.currentScene.tileStatus) === 2) {
        panorama = {
          width: 6000, //this.currentScene.panoramaWidth,
          cols: 16,
          rows: 8,
          baseUrl: this.currentScene.panoramaSmallUrl,
          tileUrl: (col, row) => {
            // const num = row * 16 + col + 1
            return `${this.currentScene.tileUrl}/cp_${col}_${row}.jpg`
          },
        }
      }
      const a = Math.max(this.currentScene.panoramaWidth, 2 * this.currentScene.panoramaHeight)
      const r = Math.round(a / 2)
      const panoData = {
        fullWidth: a,
          fullHeight: r,
          croppedWidth: this.currentScene.panoramaWidth,
          croppedHeight:  this.currentScene.panoramaHeight,
          croppedX: Math.round((a - this.currentScene.panoramaWidth) / 2),
          croppedY: Math.round((r - this.currentScene.panoramaHeight) / 2)
      }
      this.vrViewer.overlay.hide()
      this.vrViewer.setPanorama(panorama, {panoData: panoData})
    },
```
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/33148475/2451abb9-c8ec-47a8-b719-7638c2fefe0c)

I want to know what tool is used to generate the tiles for the photo-sphere-viewer website demo:

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/33148475/1ddd6cb0-e4fa-4277-8320-c869fa515770)

**Comment by mistic100** [comment]
6000 is not divisble by 416 ! that's why your tiles are not all square and your are missing the last bit.

If you choose 16 columns, your tiles must be 375 pixels wide (6000 / 16)

**Comment by mistic100** [comment]
Please use the "question" issue template in the future, this not a "feature" request.
