### ISSUE TITLE
Markers from tour links have incorrect orientation

### ISSUE THREAD

**Issue by AndyBaird** [mistic100/Photo-Sphere-Viewer#1185]
### Describe your problem

I am using a GPS enabled camera that includes pose heading data. When I load those images into a virtual tour and use the pose heading data the automatic placement of the tour-link markers is wrong. If I change overwrite the pose heading data to 0 for every image, the links generally end up in the correct places but then the compass is wrong and no longer pointing to what is actually north. 

I've included a live demo where someone walked down a street taking photos, but the markers incorrectly point to houses etc. instead of down the street where the next shot was taken.

There are 2 arrays for comparison:
Line 31 - uses the camera pose heading: `nodesCameraPoseHeading` 
Line 875 - Pose heading set to zero: `nodesZeroPoseHeading`

The demo uses `nodesCameraPoseHeading` by default and the array can be changed to see the improvement when setting to 0, but notice the compass will no longer be correct (North is facing a house with green shutters on the initial node).

Any suggestions would be appreciated.

### Online demo URL

https://jsfiddle.net/tillerxr/703houbv/9/

### Photo Sphere Viewer version

5.5.1

### Plugins loaded

VirtualTourPlugin, GalleryPlugin, MarkersPlugin, CompassPlugin

### Additional context

Things I've tried: 

- multiple photoshoots
- reset the camera
- calibrated the GPS of the camera
- applying pose heading data to sphereCorrection:{pan}
- not setting pose heading data
- setting pose heading data to 0, 180, 360

**Comment by mistic100** [comment]
Please create a simpler example with only a few nodes.

**Comment by AndyBaird** [comment]
Wow, just figured out the issue creating a smaller demo. We store latitude longitude in that order but the API takes longitude before latitude. So when the GPS data was getting applied to each link it was flipped.
