### ISSUE TITLE
Click event?

### ISSUE THREAD

**Issue by Aldo111** [mistic100/Photo-Sphere-Viewer#12]
Hi, I just started using this (and am a beginner to three.js as well) and I basically wanted to be able to "attach" an image (or possibly a text box - whatever's easier) to a point on this photosphere and it should be able to move with the photosphere and be out of view when not in the photosphere's fov.

What would be the best way to go about this? There is no click event right off the bat and I'm not too sure how I should tackle this in a clean way that would work across different resolutions. My main issue is what positional values should I be using for such attachable elements - and how can I get them upon a click? (Since photospheres use an equirectangular projection, what would be a nice way to convert it to a meaning x/y that could be use to attach elements within the browser window to a specific point on the photosphere image)

**Comment by mistic100** [comment]
Hold-on ! This feature is already entirely developed #5

It's not released yet, the doc has to be written.

**Comment by Aldo111** [comment]
Hi, it's been a while but I just wanted to come back and say that I've been working with this photo sphere and it's great! Love the marker support!

I made a (very minor) addition to the photo sphere viewer js code - the id given to the marker, I set the marker's div to contain that 'id' as well so I could attach additional content to the div (not sure if there was a better way of doing that as I didn't want to use the side panel). I look forward to contributing more substantial changes (mostly regarding markers as it's so useful) as I get to know the code better.

I had 2 questions -

1. I encountered an issue on mobile where if I clicked/touched on a marker, it seemed to trigger the 'select-marker' trigger twice - was unable to find the right place in the js code to counteract this trigger/propagation. I tried to stop the propagation from within the _onClick but that didn't seem to prevent touching markers from firing select-marker event twice. Any suggestion/solution to this?

2. Since the divs being overlayed in the viewer actually contain text boxes, some of which can be a little wider or longer than a phone screen's dimensions - I was wondering if there's a good way to keep the markers visible (so while turning, I can still see the div/text boxes going off the screen instead of the markers' visibility being toggled when they can no longer be seen on the screen). I did try commenting out the code that toggles the visibility - but I also saw that doing so will have the markers showing up at different positions on the sphere as you turn around (assumably due to the clientX/Y involved in the calculations?) - wondering if there's a way around this (if any?).


Again, thanks for such a wonderful viewer!

**Comment by mistic100** [comment]
That's a good idea, at will make this change too, with a prefix "psv-marker-" to avoid any conflict.
There is actually another way to do it : the ` addMarker`  method returns the internal object which has a ` $el`  property, pointer to the corresponding DOM element.
It's not suitable for markers provided at initialization of course.

1. I'll investigate, as you may have seen I decided to do all the events management from scratch (no external lib) and it becomes messy...

2. I don't really understand, you would like the markers do not disappear immediately once they rich the edge ? It's possible, by adding an optional offset in the [_isMarkerVisible](https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/src/js/PSVHUD.js#L264) method, I'll try it.

**Comment by mistic100** [comment]
- 2. Well actually the whole container is in "overflow: hidden;" and this can't be easily changed. The best I can do is to display the markers but cropped, as long as a small part of the marker is visible.

**Comment by Aldo111** [comment]
Regarding 2, yeah it'd be nice if they didn't completely disappear because some of the textboxes I attach to each marker might contain a lot more text than can be seen in the viewport so they might need to drag down/up a bit to see the rest of the text below - but what happens right now is that the whole div disappears due to the _isMarkerVisible method.

I tried stopping the markervisible method from running and it worked out great until I realized that when you turn around in the sphere, the markers show up at different positions so just wondering what would be a good way to handle this. An easy thing on my end would be to just try and limit the amount of information shown in a marker but my goal is to be able to eventually work with this in VR so I'd need the markers to always be visible in 3D space, whether they're in my viewport or not (I'm not that familiar with threejs yet so not sure what's the best way to make it happen).

If the cropping could help ensure I can still read the remaining text/rest of the marker div, that could work!

**Comment by mistic100** [comment]
You can check right now I made the change in https://github.com/mistic100/Photo-Sphere-Viewer/commit/84a1755ea49bcc76949394d0c6e73f52dab0111c

**Comment by Aldo111** [comment]
I tried it out before you mentioned it and it's a nice little adjustment (also like the changes in the latest commit)! It also highlighted what my real problem was - I noticed in the code earlier that the marker visible calculations are based on marker.width and not on the actual element width (as different markers of mine can have differently-sized-text boxes that show up within them when I click upon the marker image, thus dynamically increasing the size of the marker container/div). 

Maybe if instead of marker.width, we tried using marker.$el.width, and could rid of absolutely specifying the width/height when creating a marker, this could help my issue and be useful in general (by allowing dynamically sized marker divs that can increase/decrease in size based on the content).

**Comment by mistic100** [comment]
The element width IS the marker width (unless you are hacking the lib).
I'll try to make the dimensions optional for text markers.

But you can still update the dimensions afterward via getMarker method.

To do
 - [ ] superMarket method

**Comment by Aldo111** [comment]
Oh that didn't seem to be the case with the version I was working with (prior to the latest commit you put up) but I'll try out the latest commit right now! Also is the dist js file just a combination of all the js files in src?

**Comment by mistic100** [comment]
I said "I will"...

And the fist files address only updated for a release, but you build it yourself with the grunt task
