### ISSUE TITLE
Marker Point Scaling Issue

### ISSUE THREAD

**Issue by 1519256257** [mistic100/Photo-Sphere-Viewer#1200]
### Describe the bug

When an external transformation scale is applied using "transform: scale" property, there is a significant difference in the yaw and pitch coordinates when setting markers. This inconsistency arises due to the scaling effect. How can we resolve this issue?

### Photo Sphere Viewer version

5.5.2

### OS & browser

windows11

**Comment by mistic100** [comment]
Please a **demo**

**Comment by 1519256257** [comment]
Adding the CSS rule transform: scale(0.6); to the outermost element with class=page in the example on the webpage https://photo-sphere-viewer.js.org/playground.html results in inaccurate placement of markers.

**Comment by mistic100** [comment]
Ok. Well I don't think I will try to fix this. For performances reason the library does not use `getBoudingClientRect()` but a custom function which does not support transformations

https://github.com/mistic100/Photo-Sphere-Viewer/blob/ae57d0f911a2b70f4fa5177e6d529bf25c8823bb/packages/core/src/utils/browser.ts#L79-L95
