### ISSUE TITLE
showAllTooltips() method doesn't correctly show tooltips for Virtual Tour markers in 5.5.2

### ISSUE THREAD

**Issue by sonniydsgn** [mistic100/Photo-Sphere-Viewer#1202]
### Describe the bug

Tooltips for markers created using the Markers plugin are shown as soon as they enter the screen. But for the tooltips for markers created using the Virtual Tour plugin, I need to hover over them first, and only then they are show up permanently.

### Online demo URL

https://jsfiddle.net/sonniydsgn/7vgw8qhx/

### Photo Sphere Viewer version

5.5.2

### Plugins loaded

VirtualTourPlugin, VisibleRangePlugin. MarkersPlugin

### OS & browser

Windows 11, Chrome 120

### Additional context

In version 5.5.1, everything worked fine

**Comment by sonniydsgn** [comment]
I forgot to note that if you look at the state of the virtual tour markers through the console, then showAllTooltips is set to true. In the demo, I gave an example of this

**Comment by mistic100** [comment]
Virtual Tour tooltips are fetched asynchronously on mouse-enter, I don't know how to solve this issue.
