### ISSUE TITLE
Gallery Plugin items are not clickable on mobile

### ISSUE THREAD

**Issue by Elius94** [mistic100/Photo-Sphere-Viewer#1203]
### Describe the bug

Hello @mistic100 hope you are well! :)

I think that in this line there's a issue.

https://github.com/mistic100/Photo-Sphere-Viewer/blob/ae57d0f911a2b70f4fa5177e6d529bf25c8823bb/packages/gallery-plugin/src/GalleryComponent.ts#L126C5-L126C5

Debugging in mobile mode on chorme dev tools (you can try using my link). Gallery items are not clickable on mobile.

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/14907987/19b81ff7-e707-4ea3-a5c4-aa5c344eea22)

Debugging I saw that sometimes "click" event fires after touching but the if condition returns always false. and then it is forced to skip the event.

P.s: I tried also with your official Gallery Plugin documentation page with my smartphone but it does not trigger touch/click events!

thanks

### Online demo URL

https://srv.eliusoutdoor.com/immersive/altissimo.html

### Photo Sphere Viewer version

5.5.2

### Plugins loaded

Gallery

### OS & browser

Android 14 - Google Pixel 7a - Chrome latest

**Comment by Elius94** [comment]
`if (Math.abs(this.state.initMouse - (e as MouseEvent).clientX) < 10)`

I don't know why, but I found that 10 is too low: when I touch on a gallery item the difference is always close to 50!

The other thing I saw is that if I put a breackpoint on "click" case it's not always fired but if you put it on the switch you can see all the incoming events and also the "click".

Thanks

**Comment by wcdmax** [comment]
I have the same problem, have you solved it?

**Comment by Elius94** [comment]
@mistic100 Hi Damien! I've made a PR to solve this issue.
I hope it's fine
Thanks
