### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by potremblay** [mistic100/Photo-Sphere-Viewer#1204]
### Describe the bug

The website with all demos and the documentation is currently down.

<img width="631" alt="Capture d’écran, le 2024-01-11 à 11 14 50" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/1883255/33988998-101a-46ab-b451-efea1baf8c61">

### Online demo URL

https://photo-sphere-viewer.js.org/

### Photo Sphere Viewer version

5.5.2

### OS & browser

MacOS 14 on Chrome

**Comment by mistic100** [comment]
Fixed
