### ISSUE TITLE
Load css file error with v5.4.4 by chrome 112.0.5614.0

### ISSUE THREAD

**Issue by lyrebirth** [mistic100/Photo-Sphere-Viewer#1206]
### Describe the bug

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/62588055/4cbec231-100c-4495-9b40-008e3623e722)

I see it in your official website

### Photo Sphere Viewer version

5.4.4

### Plugins loaded

marker plugin

### OS & browser

chrome 91.0.4472.124

**Comment by lyrebirth** [comment]
I find that when I use v112.0.5614.0，it's load error until I use v113.0.5663.0，it's not error

**Comment by mistic100** [comment]
Does the page and the demo works anyway ?

**Comment by lyrebirth** [comment]
> Does the page and the demo works anyway ?

no,You can reproduce it on the official website.

**Comment by mistic100** [comment]
I works on every browsers (all up to date) I have. It must be a problem on your side for which I cannot help.
