### ISSUE TITLE
Equirectangular Tile preview bad rendering - A black line is visible on the joint point until the tiles are loaded

### ISSUE THREAD

**Issue by Elius94** [mistic100/Photo-Sphere-Viewer#1214]
### Describe the bug

Hi Damien :)

I've found this issue in Equirectangular tile adapter.
It's present also in your official example.

The low quality preview of the pano is not connected right, if you see on the joint point (where the left and right side of the equirectangular picture are touching) there is a black line. 
It seems an approximation issue of the width but I don't know.

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/14907987/9fa7adf3-40df-4a1c-84c0-259b63c60943)

### Online demo URL

https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html#example

### Photo Sphere Viewer version

5.6.0

### Plugins loaded

EquirectangularTilesAdapter

### OS & browser

Windows, Chrome

**Comment by mistic100** [comment]
This is because of the blur effect. There is no solution.
