### ISSUE TITLE
Quickly improve functionality

### ISSUE THREAD

**Issue by renjiali68666** [mistic100/Photo-Sphere-Viewer#1216]
### Describe the feature

It can achieve the function of the link below, and it is best to add a method of cutting images, which will replace Krpano's position

https://4d6nwklth.wasee.com/wt/4d6nwklth?def_sid=0

**Comment by renjiali68666** [comment]
How did you do it? I will develop an editor that uses your kernel

**Comment by mistic100** [comment]
It is really hard to understand what you are talking about.

Do you want this ? https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html
