### ISSUE TITLE
Implement ground mask and top mask

### ISSUE THREAD

**Issue by jiechengyang** [mistic100/Photo-Sphere-Viewer#1217]
### Describe your problem

Hello, Sir. I would like to ask you about an effect: I want to implement the ground mask and the top mask, can you use markerPlugin or other methods to achieve it? And let the filled image can follow the vr view to rotate, zoom in and out

<img width="895" alt="image" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/33148475/be8bbd68-8c7c-4b98-af02-52e680aa6ce9">
<img width="997" alt="image" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/33148475/2d66ab69-630b-413f-8530-a1817a313d2a">

### Photo Sphere Viewer version

5.6.0

**Comment by Mr-Kanister** [comment]
I think he/she refers to a mask, which hides feet / a tripod / stitchlines at the bottom and the top of an image. You can do that via an overlay: https://photo-sphere-viewer.js.org/plugins/overlays.html
