### ISSUE TITLE
Responsive problem

### ISSUE THREAD

**Issue by Mmd84i** [mistic100/Photo-Sphere-Viewer#1218]
### Describe your problem

When I copy the CodePen codes from this page and create JS, CSS and HTML files with them and link them together.  In the computer, everything is displayed correctly, but in the mobile phone, it displays the desktop mode

https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#example

### Photo Sphere Viewer version

5.6.0

**Comment by mistic100** [comment]
what is "the desktop mode" ? care to share some screenshots ? and your own demo

**Comment by Mmd84i** [comment]
That is the demo : 
http://film4knew.sbs/test1.html

![IMG_۲۰۲۴۰۱۲۷_۱۲۵۵۰۷](https://github.com/mistic100/Photo-Sphere-Viewer/assets/157876330/a093443e-ba71-4545-8d15-33a1025a492c)
![IMG_۲۰۲۴۰۱۲۷_۱۲۵۵۱۶](https://github.com/mistic100/Photo-Sphere-Viewer/assets/157876330/d157e7b6-bb1e-47fe-b605-938b62ce73b1)
![IMG_۲۰۲۴۰۱۲۷_۱۲۵۶۰۹](https://github.com/mistic100/Photo-Sphere-Viewer/assets/157876330/7df96463-3c6e-459d-a0f6-0e76ae2cc706)

**Comment by mistic100** [comment]
This is probably because you didn't use `<meta name="viewport" content="width=device-width, initial-scale=1.0" />`

As mentionned in the getting started guide https://photo-sphere-viewer.js.org/guide/#your-first-viewer

**Comment by Mmd84i** [comment]
I always put that tag as a habit, but I don't know why I forgot this time, and I didn't even think that the problem was with that tag.

Thanks a lot 🙏🙂

**Comment by mistic100** [comment]
your's welcome
