### ISSUE TITLE
The circle loadingbar is not working properly when switch panorama fast or in poor network quality

### ISSUE THREAD

**Issue by venmax** [mistic100/Photo-Sphere-Viewer#1219]
### Describe the bug

When switch through virtualTourPlugin's gallery, or manually use `setPanorama` several times. The circle loading progress bar seems weird.

Please check the demo, then switch chrome devTools - Network - No throttling, to fast 3G, I record a video blow.

https://github.com/mistic100/Photo-Sphere-Viewer/assets/4507022/4b444e72-884e-4e6e-8b09-4118bf9af30b

It looks like all panorama added are sharing a same Loader instance.https://github.com/mistic100/Photo-Sphere-Viewer/blob/c5e4dee37e58e773d5c0689654fbde83451af55f/packages/core/src/components/Loader.ts#L68

I added a method by checking whether setProgress url is current panorama url.
```
  setProgress(value: number, panorama?: string) {
    if (panorama !== this.viewer.config.panorama) {
      return
    }
    // ...
}
```

But maybe it's better seperate the progress by panorama urls inside Loader.

I found a related issue before: https://github.com/mistic100/Photo-Sphere-Viewer/issues/544

### Online demo URL

https://codesandbox.io/p/sandbox/wizardly-platform-7tfdfq

### Photo Sphere Viewer version

5.6.0

### OS & browser

macos

**Comment by mistic100** [comment]
The real bug here is that the pending panorama loading should be cancelled if switching to another one.

**Comment by venmax** [comment]
> The real bug here is that the pending panorama loading should be cancelled if switching to another one.

Yes I've seen your comment there, the PR for threejs several years ago. How is the PR going?

**Comment by mistic100** [comment]
Nowhere, some peoplad seem interested in the feature but the maintainers just ignore it sadly.

PSV currently includes it's own cancellation system, which does not actually cancel the HTTP request but should ignore the result. This is clearly not working and creates this strange loader.

**Comment by mistic100** [comment]
okay after investigation, all the necessary checks are here in the loading chain, the only thing missing as you stated initially is to check which panorama is actually requested in the loader progression callback

**Comment by mistic100** [comment]
I made a branch where I copied FileLoader and ImageLoader from my PR on ThreeJS in order to allow request cancellation.

https://github.com/mistic100/Photo-Sphere-Viewer/tree/abort-loader

I didn't test it yet in your scenario.

**Comment by venmax** [comment]
> I made a branch where I copied FileLoader and ImageLoader from my PR on ThreeJS in order to allow request cancellation.
> 
> https://github.com/mistic100/Photo-Sphere-Viewer/tree/abort-loader
> 
> I didn't test it yet in your scenario.

Yeah it works! Thank you
