### ISSUE TITLE
VR support

### ISSUE THREAD

**Issue by fgfernandez0321** [mistic100/Photo-Sphere-Viewer#122]
Basically something like https://productcoalition.com/only-3-steps-to-create-a-vr-tour-from-your-360s-36313e3595ce because I need to navigate.

**Comment by mistic100** [comment]
Planned but I am not working on it.

**Comment by fdnetty** [comment]
Hi ! Any news about this feature ? 
Jeremy Heleine script have another feature for GoogleCardBoard, is it planned ? 
Thanks !

**Comment by mistic100** [comment]
I added VR support on the `dev` branch.

Any feedback is welcome.

**Comment by mistic100** [comment]
@dekemega Can you try with the last commit ?
It tries to use the "screen.orientation" API to lock the orientation or displays a message asking to rotate the screen.

My only device supports the API so I am not exactly sure if the message is correctly displayed.

**Comment by ChanderShekharKestone** [comment]
> For now the markers are totally disabled when entering VR mode, because they are not in the ThreeJS scene but on a layer on top of it, I have now idea how to display them in VR mode without having a ghosting effect.

Please tell how to display and it will work for tour (or change image).
