### ISSUE TITLE
Keyboard defaults

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1225]
### Describe your problem

I have a demo page where I tried to switch to ES modules  and everything works fine.....  except.....

for the advanced keyboard action

https://photo-sphere-viewer.js.org/guide/config.html#keyboardactions

in your guide there is the    `    ...PhotoSphereViewer.DEFAULTS.keyboardActions,`

but now clearly throws an error  PhotoSphereViewer not defined

### Photo Sphere Viewer version

5.6.0

**Comment by mistic100** [comment]
```js
import { DEFAULTS } from '@photo-sphere-viewer/core';

...DEFAULTS.keyboardActions
```

**Comment by haldo98** [comment]
Thank You very much. Damien
