### ISSUE TITLE
Panorama transition animation

### ISSUE THREAD

**Issue by nmthangdn2000** [mistic100/Photo-Sphere-Viewer#1226]
### Describe the feature

Hello, First of all, I would like to thank you for developing this project, it helped me a lot 😍😍😍😍.

I am inintegrating this library in my project.
I found the optional transition in your libraryy but it only has the type 'fade-only'
I want to create more transition effects in panorama but unfortunately, I haven't found a solution yet.

I want it to be similar to the transition on the website below:
https://www.vr-view.jp/keihanshin/toranomon/final/

I'd be grateful if there's a solution.

I would you

**Comment by mistic100** [comment]
If your talking about the loading square by square try this https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html

There is not other transition option.

**Comment by mistic100** [comment]
setPanorama method has a zoomLvl option

**Comment by nmthangdn2000** [comment]
That's correct, I can handle the zoom functionality. However, I also aim to incorporate opacity adjustments to pano1 to facilitate a transition to pano2, akin to the website I referenced.

Rather than utilizing the default image blurring technique for pano transitions (as seen in { transition: boolean | 'fade-only' } in [the documentation](https://photo-sphere-viewer.js.org/api/types/core.panoramaoptions)), **I prefer the flexibility to craft my custom transition animation.**

**Comment by yuan116** [comment]
@nmthangdn2000 
Hi, i think u can archive the similar result with custom [TextureLoader#preload](https://photo-sphere-viewer.js.org/api/classes/core.textureloader#preloadPanorama) and [Animation](https://photo-sphere-viewer.js.org/api/classes/core.utils.animation) helper
if you are using virtual-tour-plugin, you might wanted to remove the plugin's listener, else there will be conflict of animating

here is the sample demo i created previously with PhotoSphereViewer library
[https://yuan116.gitlab.io/demo-photosphere/](https://yuan116.gitlab.io/demo-photosphere/)

**Comment by nmthangdn2000** [comment]
@yuan116 
That's wonderful to hear, and it's almost like finding treasure. It would be even more delightful if I could reference your source code, wouldn't it? Especially considering I could learn a lot from it.

**Comment by nmthangdn2000** [comment]
While researching to find a solution, I suddenly came up with the idea to take a [screenshot](https://photo-sphere-viewer.js.org/demos/advanced/screenshot.html), attach it to an <img> tag, and customize the CSS.

After completing the animation I will delete them.

And the results were exactly as I expected.

` viewer.addEventListener(
    'render',
    () => {
      render.domElement.toBlob(
        (blob) => {
          if (!blob) return;
          const url = URL.createObjectURL(blob);
          const imgElement = document.createElement('img');
          imgElement.id = 'panorama-image-transition';
          imgElement.src = url;

          document.body.appendChild(imgElement);

          imgElement.onload = async () => {
            await setPanorama(panorama);


            imgElement.classList.add('panorama-image-transition');

            await delay(800);
            imgElement.remove();
          };
        },
        'image/jpeg',
        0.5
      );
    },
    { once: true }
  );`

**Comment by yuan116** [comment]
Hi, here are the steps

1. Create a variable to hold the status of change panorama
1. Preload panorama with [TextureLoader#preload](https://photo-sphere-viewer.js.org/api/classes/core.textureloader#preloadPanorama)
2. Start animation with [Animation](https://photo-sphere-viewer.js.org/api/classes/core.utils.animation)
3. Adjust the [AnimationOptions](https://photo-sphere-viewer.js.org/api/types/core.utils.animationoptions) (`properties`, `duration`, `easing`) as you wanted
4. On animation's `onTick`, check status and animation's `progress`
5. Once it meet the criteria, change panorama with [Viewer#setPanorama](https://photo-sphere-viewer.js.org/api/classes/core.viewer#setPanorama)
6. Adjust the [PanoramaOptions](https://photo-sphere-viewer.js.org/api/types/core.panoramaoptions) (`showLoader`, `transition`) as you wanted
7. That's all, you could modify more to meet your expectation

**NOTE:
the sample code used PhotoSphereViewer version 5.3, 
if you are using version later than 5.3, and facing any error or bug,
you will need to refer back to document**

Sample code:
```js
let changeNew = false;

viewer.textureLoader.preloadPanorama(panorama)
    .then((textureData) => {
        return new utils.Animation({
            properties: {
                fisheye: {
                    start: 0.5,
                    end: 0,
                },
                zoom: {
                    start: viewer.getZoomLevel(),
                    end: 40,
                },
            },
            duration: 1000,
            easing: 'inQuad',
            onTick: ({ fisheye, zoom }, progress) => {
                if (!changeNew && progress >= 0.3) {
                    changeNew = true;
                    viewer.setPanorama(textureData.panorama, {
                        panoData: textureData.panoData,
                        showLoader: false,
                        transition: 750
                    });
                }

                viewer.setOption('fisheye', fisheye);
                viewer.zoom(zoom);
            },
        });
    })
```

**Comment by nmthangdn2000** [comment]
That's great, thank @yuan116  and @mistic100  for supporting me.
Sincerely thank
