### ISSUE TITLE
Bug: Missing navbar on IE11

### ISSUE THREAD

**Issue by ronanmccoy** [mistic100/Photo-Sphere-Viewer#123]
When viewing on IE 11, the navbar (.psv-navbar) is set to display:none on page load.  This can be reproduced on the official website (http://photo-sphere-viewer.js.org).

**Comment by dustinpaluch** [comment]
It's also unresponsive to clicks for me. It just keeps spinning on auto.

**Comment by mistic100** [comment]
Seems to be solved on dev. Shipped with the next release
