### ISSUE TITLE
plan plugin

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1231]
### Describe the feature

maybe.. ( for sure... ) I'm doing something dumb...

https://www.tadini.it/temp/panorama_plan.html

i tried to implement the configureLeaflet option...   the pano loads but the maps are not loading .
the console says "a form field element should have an id......."

**Comment by haldo98** [comment]
sorry ... i use feature instead of question.....

**Comment by mistic100** [comment]
the configureLeaflet method takes a `leafletmap` parameter, you must attach your custom configuration to this instance, not create your own.
