### ISSUE TITLE
Is it possible to rotate a marker?

### ISSUE THREAD

**Issue by Fernando-Checa** [mistic100/Photo-Sphere-Viewer#1235]
### Describe your problem

In case os markers with text for example.
I can use yaw and pitch to create a marker but I'd like to rotate it in place to align text with the space for example.

### Photo Sphere Viewer version

5.7.0

### Plugins loaded

markersPlugin

**Comment by mistic100** [comment]
try this on the marker's properties

```js
style: {
    rotate: '45deg'
}
```

**Comment by Fernando-Checa** [comment]
Is not working.
Inspecting the docs I can see it doe snot work for imageLayer type.

`CSS properties to set on the marker (background, border, etc.) (ignored for imagerLayer, videoLayer)`

**Comment by mistic100** [comment]
Well you said you used text makers not imageLayer...

There is the `orientation` option you can try, but is hardcoded values to make it appear on the floor or a wall, the angle is not confgurable.

**Comment by Fernando-Checa** [comment]
Yes sorry, I did not express it correctly.
I use text but in an image.. something like this:
![CleanShot 2024-02-13 at 18 26 30](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/ea484f4a-3a2e-4ec0-834d-07ebd4d1bf15)



Why imageLayer can't be rotated like the others?

`orientation` is not good here because I need to rotate while `horizontal`

**Comment by mistic100** [comment]
Why ? Because it is no coded.

Please to a mockup of the desired orientation, so I know exactly what you want.

**Comment by Fernando-Checa** [comment]
Sorry, I didn't realize that it was a possibility.. I thought more of a technical reason.
Here is what I'd like to be able to do:
![ttt](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/72b9a0e5-ee71-4f8c-a642-d3fe1c6eb36f)

For example, having a pointing marker, be able to rotate it to point in a certain way. Maybe good for stairs, elevators...
The logo with text marker would be better if aligned to the grid of the tiles for example.

Is I can help with anything just let me know

**Comment by mistic100** [comment]
For the future 5.7.1 version

---

#### `rotation`

-   type: `string | number`

Rotation applied to the marker, in degrees or radians.

_(This option is ignored for polygons and polylines)._

**Comment by Fernando-Checa** [comment]
Thanks. Great news.

**Comment by mistic100** [comment]
@PanierAvide this could be useful for #1163  
You would still have to dynamically place the markers for them to be always visible.

Or as a baseline for a custom renderer like the ArrowsRenderer

**Comment by Fernando-Checa** [comment]
When using a marker that is not square in dimensions, if you rotate the marker it does not retain the proportions.
It seems if the proportion stays the same and the image rotates, distorting the result.

rotation 0deg
![CleanShot 2024-03-05 at 10 45 07](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/e063a6f4-b748-4efe-8127-4768110f9120)

rotati
![CleanShot 2024-03-05 at 10 46 27](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/71819327-5bb0-4e0a-b8c0-5228cb5d8a22)
on 90deg

**Comment by mistic100** [comment]
Please open a new issue with full code and/or demo
