### ISSUE TITLE
Can't change opacity of marker

### ISSUE THREAD

**Issue by Fernando-Checa** [mistic100/Photo-Sphere-Viewer#1237]
### Describe the bug

I made a web app to create tours and when editing markers, the opacity does not change.

This is the code I use:

`markersPlugin.updateMarker({
     'id' : 'mark1',
     'opacity' : 0.4
});`

the marker in question remains at 100% opacity

### Photo Sphere Viewer version

5.7.0

### Plugins loaded

markersPlugin

### OS & browser

MacOs Sonoma, Brave Versión 1.62.162 Chromium: 121.0.6167.164 (Build oficial) (arm64)

**Comment by mistic100** [comment]
It works https://codesandbox.io/p/sandbox/nifty-oskar-nknf8m?file=%2Fsrc%2Findex.ts%3A102%2C55

Please share a demo when you have a problem.

**Comment by Fernando-Checa** [comment]
Yes.. but not in my app.. let me try other things..

**Comment by Fernando-Checa** [comment]
Every other property gets changed but opacity.
I don't understand what's going on.

The property gets updated in the MarkersPlugin object but not visually and remains at 100% no matter what.
If I hide the marker it hides but does not change opacity.

![CleanShot 2024-02-14 at 18 44 37](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/c4c496df-2b3f-411b-9d0e-a384a8a4a6be)


Do you know anything that could be interfering?

**Comment by Fernando-Checa** [comment]
If I create the marker with less opacity it works but then I can't change it to anything else.

**Comment by mistic100** [comment]
Yes : the 3D markers do not support updating the opacity. I will fix it.

But first let me ask you something : when you have a problem you MUST start by providing an example of your code, or at least a snippet like you just did, I save you and me a LOT of time. Thanks in advance.

**Comment by Fernando-Checa** [comment]
Yes, I'm sorry. I will provide all the info I can next time.

This is how I create the marker:

`
{
               "id": 'mm'+id,
               "opacity": op,
               "imageLayer": baseUrl + iconUrl+ target[img],
               "hideList": hide,
               //hideList: element[2],
               //opacity: element[3],
               "position": {
               "yaw": yaw,
               "pitch": pitch
               },
               "size": {
               "width": x,
               "height": y
               },
               "orientation": orientation,
               "tooltip": {
               "content": 'mm'+id,
               "position": "top center",
               "trigger": "hover"
               }
          }
`

Are imageLayer markers the same as 3Dmarkers?
I can't find them in the docs

**Comment by mistic100** [comment]
yes imageLayer and videoLayer are 3D objects

**Comment by Fernando-Checa** [comment]
Just to confirm that both the opacity and the rotation work now like a charm.

Thank you!
