### ISSUE TITLE
rotate() method error

### ISSUE THREAD

**Issue by Fernando-Checa** [mistic100/Photo-Sphere-Viewer#1239]
### Describe your problem

When I try to rotate the view with:

```
viewer.rotate({
    pitch: 0
});
```

and I get an error:
![CleanShot 2024-02-15 at 11 25 03](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/be2608cb-8ec2-4836-a1f3-6f1fe004ce84)

also tried `defaultPitch` and same

And the docs say you can also use `pitch`
![CleanShot 2024-02-15 at 11 25 47](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/9f114c15-6968-4aa6-97ae-1799a71b0c8f)

### Photo Sphere Viewer version

5.7.1

### Plugins loaded

markersPlugin

**Comment by Fernando-Checa** [comment]
It looks like you need to provide BOTH `yaw` and `pitch` for this to work.
Otherwise it throws an error.

So if I want to change only the `pitch` I need to pass also `viewer.getPosition().yaw` to the `rotate()` method, which could be done internally if no `yaw` passed to the method.

Same thing with `animate()`, you need both properties.

**Comment by mistic100** [comment]
Your analysis is correct, and it the right way to go.
