### ISSUE TITLE
Bug: Dragging panorama fails on IE11

### ISSUE THREAD

**Issue by ronanmccoy** [mistic100/Photo-Sphere-Viewer#124]
When viewing on IE 11, I'm unable to drag the panorama in any direction. This happens whether the panorama is auto-rotating or not.

This can be easily reproduced on the official website (http://photo-sphere-viewer.js.org) when viewed on IE11.

**Comment by mistic100** [comment]
Seems to be solved on dev. Will be shipped in the next release.
