### ISSUE TITLE
Event that fires when motion stopped

### ISSUE THREAD

**Issue by Fernando-Checa** [mistic100/Photo-Sphere-Viewer#1240]
### Describe the feature

When I click and drag the panorama there is the `PositionUpdatedEvent` that fires as I move the view, but it would be nice to have an event that fires when you release the mouse and the movement stops.

The `stop-all` event fires when I click on the panorama to drag it, before I move anything.

### Alternatives you've considered

Could be a `mouseUp` event or `motionStopped` event or `stopDrag` event

**Comment by mistic100** [comment]
You can wrap your listener in a debounce function

For example with lodash https://lodash.com/docs/4.17.15#debounce

```js
viewer.addEventListener('position-updated', _.debounce((event) => {

});
```

**Comment by Fernando-Checa** [comment]
ok thanks.
I'll take a look.

**Comment by Fernando-Checa** [comment]
something like this works

```
viewer.addEventListener('position-updated', _.debounce(endMove, 300, {
     'leading': false,
     'trailing': true
   }));
```

but it would be easier to have an event.
