### ISSUE TITLE
Sometimes markers do not appear when clicking on the panorama

### ISSUE THREAD

**Issue by Fernando-Checa** [mistic100/Photo-Sphere-Viewer#1241]
### Describe the bug

Sometimes when I create a marker it does not appear on the screen.
The tooltip show when I hover over the spot though.
In this case I created one marker and the second did not appear.
![CleanShot 2024-02-15 at 22 06 23](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/bff845eb-914f-4559-97eb-35ec12bd3f0e)

then if I move the view or create a new marker it appears.
![CleanShot 2024-02-15 at 22 09 25](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/8ae241d6-3c5e-4ed1-bbf0-a54d0bd33640)

This also happens sometimes at first load. The panorama loads, I create the markers all at once and they do not appear until I move the view.

Is there a way to force rendering the markers?

### Photo Sphere Viewer version

5.7.1

### Plugins loaded

markersPlugin

### OS & browser

Tested with Safari and Brave

**Comment by mistic100** [comment]
Code ?

**Comment by Fernando-Checa** [comment]
Here is the method:

```
viewer.setPanorama(baseUrl + panoUrl + myPanos[currentPano], createPanoObj(currentPano))
           .then(() => { 
                   viewer.rotate({
                       yaw: panosConfig[currentPano].defaultYaw,
                       pitch: panosConfig[currentPano].defaultPitch,
                  })
                  viewer.zoom(panosConfig[currentPano].defaultZoomLvl)
          });


function createPanoObj(id){
     let pano = myPanos[id];
     let config = panosConfig[id]

     return {
       defaultYaw: config.defaultYaw,
       defaultPitch: config.defaultPitch,
       defaultZoomLvl: config.defaultZoomLvl,
       minFov: config.minFov,
       maxFov: config.maxFov,
       caption: config.caption,
       loadingImg: config.loadingImg,
       navbar: [
         'autorotate',
         'zoom',
         'moveLeft',
         'moveRight',
         'fullscreen',
         'markers',
         'markersList',
         'caption',
         'description',
         {
           id: 'I',
           title: 'Info',
           content: '<img src="'+iconUrl+'info.svg" height="22">',
           onClick: function() {
   
             },
         }
       ],
       plugins:[
         [CompassPlugin, {
           hotspots: [
           { yaw: '0deg' },
           { yaw: '90deg' },
           { yaw: '180deg', color: 'yellow' },
           { yaw: '270deg' },
           ],
           size: '80px',
         }],
         [MarkersPlugin, {
           gotoMarkerSpeed: '6rpm',
           markers: []
           }]
       ]
     }
   };
```

Also when changing panorama with this method, `yaw` and `pitch` stay the same as in the previous panorama (using the same viewer) and new `yaw` and `pitch` are ignored. That's why I need to `rotate()` the view after loading.
Is this how it's supposed to be?

**Comment by mistic100** [comment]
For your problem with "setPanorama" this is because you don't  use rights parameters at all. Here you are passing something looking like an initial configuration (with plugins and all), but "setPanorama" does not accept that. Check the API https://photo-sphere-viewer.js.org/api/classes/core.viewer#setPanorama

I'll look ate the other problem later.

**Comment by mistic100** [comment]
Your example code does  not contain anything related to creating markers... Please create a live demo on jsfiddle or other servoce (each example on the documentation has a button to setup a demo)

**Comment by Fernando-Checa** [comment]
I didn't realize the options for setPanorama() were different. my mistake.
I'll pay more attention to the API in the future.
Thank you for pointing that out.

That solved the problem with the initial position of new panoramas, but not quite.
When loading a new panorama with different position, loads the new panorama and then animates to the new position.
Is it possible to load the new panorama in the same position so it does not move?

This might no be possible depending on how the viewer is used I guess.

I'll check the API for the markers and prepare a demo

**Comment by mistic100** [comment]
`transition: false` or `transition: 'fade-only'`

**Comment by Fernando-Checa** [comment]
Yes, but then I don't get the fade affect.
I would like to have the panorama already in place but fading to the new one.

If fade-only is active, then the old panorama not only fades to the new one but also animates to the new position.

**Comment by mistic100** [comment]
It does not https://jsfiddle.net/Le82jmhd/

**Comment by Fernando-Checa** [comment]
Yes it is indicated but is not clear what `true` does (animate + fade).
I understand keeping this organized is a lot of work.
You are doing a great job and I really appreciate your fast response and dedication. 
Just pointing out things that could help others.

**Comment by Fernando-Checa** [comment]
Here is the demo

[https://jsfiddle.net/api/post/library/pure](url)

sometimes the marker is not shown when created (but the rest of the functionality is working)
If you move the panorama, then it appears
