### ISSUE TITLE
imageLayer rotation proportion

### ISSUE THREAD

**Issue by Fernando-Checa** [mistic100/Photo-Sphere-Viewer#1252]
### Describe the bug

When rotating imageLayer marker, proportion is not maintained.

using:
`markersPlugin.updateMarker({
                id: markerId,
		rotation: newDeg
            });`

Also if you try to access the `rotation` of a marker and you didn't previously set a `rotation`,  throws an error.
I think `rotation` should be set to 0 if not specified at creation.

for example here:
`markersPlugin.addEventListener('select-marker', ({ marker, doubleClick, rightClick }) => {
                let rot = marker.config.rotation;
          });`

### Online demo URL

https://jsfiddle.net/ferpando/cpm6b8gz/1/

### Photo Sphere Viewer version

5.7.1

### Plugins loaded

markersPlugin

### OS & browser

MacOs Sonoma, Brave Versión 1.62.162 Chromium: 121.0.6167.164 (Build oficial) (arm64)

**Comment by Fernando-Checa** [comment]
Hello,
I don't think this issue is resolved.. my local test and the fiddle I sent keep distorting the marker on rotation. 
I updated the version

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@photo-sphere-viewer/core5.7.2/index.min.css"/>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@photo-sphere-viewer/markers-plugin5.7.2/index.min.css"/>`

**Comment by Fernando-Checa** [comment]
if I switch back to `5.7.1` everything works fine

**Comment by mistic100** [comment]
again: new problem, new issue
