### ISSUE TITLE
preloadPanorama in worker

### ISSUE THREAD

**Issue by nmthangdn2000** [mistic100/Photo-Sphere-Viewer#1253]
### Describe your problem

I'm wondering if there's a way to use preloadPanorama in workers or something similar?

### Photo Sphere Viewer version

5.7.2

**Comment by mistic100** [comment]
you can preload images by calling `viewer.textureLoader.preloadPanorama`

I don't see the point in doing that in a WebWorker, it is just an HTTP request

**Comment by nmthangdn2000** [comment]
Well, actually, I'm having trouble loading large-sized images, it affects the running animation, so I thought of using a worker.

**Comment by mistic100** [comment]
HTTP calls do not run in the browser thread, this is not what affects performances. Generally what causes performances problems with large images is the transfer of the bitmap from the browser RAM to the GPU. Perhaps it is possible to that from a worker but this is not planned at all.

Consider using [tiling](https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html) if you want to use large panoramas.

**Comment by nmthangdn2000** [comment]
Yes,
I would consider using tiling.

Thank you very much for supporting me.

**Comment by jywarren** [comment]
Also I found that creating progressive jpg images means that something decent (somewhat blurry) loads very quickly and then increases resolution as the full larger file size download completes. I am considering ditching preloading in favor of this due to having many large photospheres in my app, since this suits my use case well: https://www.thewebmaster.com/progressive-jpegs/

**Comment by vekin03** [comment]
Performance aside, another point in favour of tiling: WebGL 2.0 textures have a maximum size! This limit varies according to browser and platform.

For example, on PC, in Firefox and Edge, the maximum size is 16384 pixels. On Android, it's 8192 in Firefox and only 4096 in Chrome. [Test by yourself](https://webglreport.com/?v=2).

In concrete terms, if you don't use tiling, the panorama will most likely appear in reduced (blurred) quality on mobile (the texture is downscaled to fit). [I've experienced this](https://github.com/mistic100/Photo-Sphere-Viewer/issues/696).

My advice: for [maximum compatibility](https://web3dsurvey.com/webgl/parameters/MAX_TEXTURE_SIZE), _always_ use tiling if the equirectangular image is wider (or taller) than 4096 pixels.
