### ISSUE TITLE
error loading new panorama

### ISSUE THREAD

**Issue by Fernando-Checa** [mistic100/Photo-Sphere-Viewer#1254]
### Describe the bug

I get this error when changing panorama

`setPanorama(panorama, options)`

this is the full error:

![CleanShot 2024-03-06 at 11 00 29](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/6982eaaf-7593-4d03-915b-6a332f22724e)

In the demo, click on the marker to load a new panorama and get the error.

if I switch back to 5.7.1 everything works fine.

### Online demo URL

https://jsfiddle.net/ferpando/f40v8ewu/2/

### Photo Sphere Viewer version

5.7.2

### OS & browser

MacOs Sonoma, Brave Versión 1.62.162 Chromium: 121.0.6167.164 (Build oficial) (arm64)

**Comment by mistic100** [comment]
Your example does not exhibit this problem. There is a problem however loading your panorama (probably a CORS issue). 

If I use `viewer.setPanorama( baseUrl + 'sphere-test.jpg'); ` instead there is no error.

Aren't you calling `markersPlugin.clearMarkers();` too ?

**Comment by Fernando-Checa** [comment]
Yes, it makes no difference.


https://jsfiddle.net/ferpando/f40v8ewu/3/￼



Change the panorama for another you have locally

￼

**Comment by mistic100** [comment]
There is a misundertanding : I am asking if you where already calling "clearMarkers" and forgot to add it to your first example ?

I identified a problem in the `removeMarker` method (and by extension `clearMarkers`). But if also have to problem **without** calling removeMarkers, this is another problem I didn't identified.

**Comment by Fernando-Checa** [comment]
In my own code yes I call the clearMarkers() method.

In the first example I didn’t call the method.

On the last example, I added the method, but the result es the same error.



Regards

**Comment by mistic100** [comment]
Well no, in your first demo the error is not the same !

**Comment by Fernando-Checa** [comment]
The error is the same on my end on both examples.

I’m gonna test the new release and tell you.



Un cordial saludo,

￼
Fernando Checa Manrique de Lara
ARQUITECTO
Certified Passivhaus Designer
+34 616 452 404 
***@***.***
https://fernandocheca.com

￼

**Comment by Fernando-Checa** [comment]
It seems the issue is fixed with this fix.1 release.


Regards

**Comment by Fernando-Checa** [comment]
Hello again.. the error is back with 5.7.2.
Can't load new panorama files

![CleanShot 2024-03-12 at 13 23 48](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/cce49112-efe7-44da-a43f-5870e1d18649)

Press the green marker in the demo to get this error

[https://jsfiddle.net/ferpando/f40v8ewu/4/](url)

my browser gives a bit more info

![CleanShot 2024-03-12 at 13 26 33](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/127b744f-4621-43dc-b672-edd30e765e94)

**Comment by mistic100** [comment]
If you got to NPM you will see there is fix of the markers plugin https://www.npmjs.com/package/@photo-sphere-viewer/markers-plugin

**Comment by Fernando-Checa** [comment]
That’s what it says but it is not fixed.Please check the demo.On 5.7.2.fix1 works but not in 5.7.2

**Comment by Fernando-Checa** [comment]
Just to clarify, I thought this fix was incorporated on the 5.7.2 release, with I see it not.
So I still need to use the fix1 release for the moment?

**Comment by mistic100** [comment]
When a version is published to NPM is cannot be replaced. That's why I marked 5.7.2 as deprecated.

**Comment by Fernando-Checa** [comment]
Ok then. I didn’t know that.
I’ll wait then for the next version to update the files.

Thank you and sorry for the confusion.
