### ISSUE TITLE
Tilting of camera in "roll" direction - Gyro plugin

### ISSUE THREAD

**Issue by jywarren** [mistic100/Photo-Sphere-Viewer#1258]
### Describe your problem

I've used another pano app which is not as nice as this one, but it does have gyroscope code which lets the user tilt the camera, and the scene follows the tilt, like this:

<img width="633" alt="image" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/24359/dc139710-9725-4a05-8a76-e0fd0bc66811">

Sorry I don't quite have the vocabulary to describe this kind of tilt -- maybe "device roll"? 

But when holding the camera it does really feel more like a window into the photosphere, vs. having this dimension fixed. 

To try this out, you can test here: https://spano.pyrik.dev/ (I'm testing on a Pixel 5 phone and an iPad Air)

I looked at this code a bit but it seems to use standard A-Frame controls so I don't quite know where this is happening. Is this possible using PSV? 

Thank you for your incredible documentation and a wonderful library! 

### Photo Sphere Viewer version

5.7.2

### Plugins loaded

Gyroscope

**Comment by jywarren** [comment]
Also sponsored for $30, grateful! I know not everyone can but wanted to show appreciation.

**Comment by mistic100** [comment]
Hello

you can try this plugin https://photo-sphere-viewer.js.org/plugins/gyroscope.html

**Comment by jywarren** [comment]
Thank you, i'm already using it - but it doesn't seem to allow "roll" tilting as in the illustration at top. It keeps "up" towards the top of the phone, rather than towards the zenith of the sky, does that make sense?

**Comment by jywarren** [comment]
That is, PSV does the right side from the below illustration, but I'm looking for the middle behavior:

<img width="626" alt="image" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/24359/79d3c3a0-270c-44b9-b1cd-563a8d14825a">

**Comment by mistic100** [comment]
Okay I understand. I'll see what can be done.

**Comment by jywarren** [comment]
Thank you so much! No worries.

**Comment by mistic100** [comment]
Added a "roll" option, enabled by default.

You might want to [build the lib](https://photo-sphere-viewer.js.org/guide/development.html) from the `main` branch to test it before the next release.

**Comment by jywarren** [comment]
Hi, I was wondering if you might consider creating a new release soon, as I'm hoping to use this in production soon. Thank you!

**Comment by jywarren** [comment]
Oh my god it's AMAZING -- the sense of realism in stereo mode in particular is immensely heightened! Thank you!!!

**Comment by jywarren** [comment]
It's so smooth! I feel like it'll be less likely to cause nausea in some viewers as well!
