### ISSUE TITLE
Can GalleryPlugin support video media

### ISSUE THREAD

**Issue by code-savior** [mistic100/Photo-Sphere-Viewer#1260]
### Describe the feature

may the GalleryPlugin support video
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/88306149/831e5c84-228e-4dec-91ab-c1d69c9fbdd9)

**Comment by mistic100** [comment]
the library does not support switching the adapter (which is responsible of displaying an image or a video)

you will have to create your own system to switch between two viewers or destroy + recreate with a different adapter.
