### ISSUE TITLE
Setting load cancel cache does not take effect

### ISSUE THREAD

**Issue by tmj1220** [mistic100/Photo-Sphere-Viewer#1261]
### Describe the bug

Cache.enabled = false;
Cache.ttl = 300;
Cache.maxItems = 3;
The setting does not take effect

### Photo Sphere Viewer version

5.7.2

### OS & browser

MacOS chrome

**Comment by tmj1220** [comment]
excuse me Whether this setting will take effect：
 viewerRef.current = new Viewer({
          container: ctRef.current,
          panorama: currMaterial?.fileUrl,
          lang,
        })
Cache.enabled = false
Cache.ttl = 300
Cache.maxItems = 3Ï

**Comment by mistic100** [comment]
What makes you say it has no effect ?

Are you importing `Cache` from `@photo-sphere-viewer/core` and not `three` ?

**Comment by tmj1220** [comment]
importing Cache from @photo-sphere-viewer/core  has no effect
I'll look at the documentation here：Photo Sphere Viewer contains a cache system to save resources when switching back and forth between multiple panoramas. This cache is global and shared across viewers (note: is not related to ThreeJS Cache, which should not be enabled)
so I want to disable caching，but it has no effect，I want to know how to set it up correctly

**Comment by mistic100** [comment]
You didn't answer my question : What makes you say it has no effect ?

I tested it right now and it works.

```ts
import { Viewer, Cache } from '@photo-sphere-viewer/core';

Cache.enabled = false;

setInterval(() => {
  console.log(Cache.items); // always logs empty
}, 1000);
```

**Comment by tmj1220** [comment]
Thank you very much for your support, I fixed the problem, which was caused by browser cache
