### ISSUE TITLE
Navbar setButtons() error

### ISSUE THREAD

**Issue by Fernando-Checa** [mistic100/Photo-Sphere-Viewer#1267]
### Describe the bug

I'm trying to replace the buttons on the navbar dynamically but when calling setButtons() it throws an error.

![CleanShot 2024-03-13 at 10 25 06](https://github.com/mistic100/Photo-Sphere-Viewer/assets/1741686/902500c0-816e-4ddd-93f6-3c2612a6a522)

### Online demo URL

https://jsfiddle.net/ferpando/9hm2nxgq/1/

### Photo Sphere Viewer version

5.7.2

### Plugins loaded

markersplugin

### OS & browser

Macos 14 + Firefox 123

**Comment by mistic100** [comment]
`viewer.navbar.setButtons('BYE')`

what do you expect this to do ? the method takes the same parameter as the `navbar` option. Check [the documentation](https://photo-sphere-viewer.js.org/api/classes/core.navbar#setButtons), it accepts an array only.

If you fix this it will then log a warning `PhotoSphereViewer: Unknown button BYE`

**Comment by Fernando-Checa** [comment]
Sorry, I created the demo wrong becasue the docs say `string` or `array`. 

`buttons: (string | NavbarCustomButton[]`

I corrected and added the array definition and now it works as expected.
I want to replace the buttons on the navbar when a new panorama is loaded.

`viewer.navbar.setButtons([
          {  
          id: 't2',
          title: 'Bye',
          content: 'Bye'
          }
        ])`

**Comment by mistic100** [comment]
No it says "array of strings or NavbarCustomButton" `(string | NavbarCustomButton)[]` the parenthesis is closed before the brackets ;-)

**Comment by Fernando-Checa** [comment]
Yes I see that.. but I got confused.. maybe it should be like 

`buttons: (strings[] | NavbarCustomButton[] )`

or something..

**Comment by mistic100** [comment]
Unfortunately I cannot change that, it is the notation used by TypeScript

**Comment by Fernando-Checa** [comment]
No worries. I'm not so used to typescript just yet. Still learning.
Don't let your great work be annoyed by my lack of knowledge :-)
