### ISSUE TITLE
Chrome > Fullscreen = Black Screen

### ISSUE THREAD

**Issue by YopLeMail** [mistic100/Photo-Sphere-Viewer#127]
Hi,

With Google Chrome on W10 fullscreen doesn't seems to work, even with the demo from your website : 
http://photo-sphere-viewer.js.org

It works fine with Firefox... not tried other broqsers, but don't know why on chrome it have a bug.

The original from Jérémy had this bug (search google for : "photo sphere viewer" fullscreen chrome bug) two first posts, extract from message : 

> Also, still from Photo Sphere Viewer, you can zoom on a mobile device, and the fullscreen bug in Chrome has been fixed.

Any idea for fix it in your version.

Thanks.

**Comment by YopLeMail** [comment]
I'd like to add than there's no "console errors" in Chrome... wut only black scrren, and when press escape it goes back to normal version... on Firefox goes fullscreen with control bar on bottom and exit button normally, on chrome nothing on scrreen.

**Comment by YopLeMail** [comment]
Also tested on iOS (iphone) the FullScreen button gives no results... testes with Safari & Chrome, normal version works (with finger and auto).

**Comment by mistic100** [comment]
Already discussed, already fixed, already planned, please search here too.
https://github.com/mistic100/Photo-Sphere-Viewer/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20fullscreen

**Comment by mistic100** [comment]
Release 3.2.3 includes the fix

**Comment by YopLeMail** [comment]
Hi, thanks for reply.

I tried with latest, and it didn't work (3.2.3), after installation on my server... after I tried the original page from your site to see if it was a misconfiguration in my installation, but it seems not to be a misconfiguration, because Firefox works well, just problem with chrome, and I downloaded today the file from GitHub...

**Comment by mistic100** [comment]
I afraid the problem is on your side, no problem here with any browser.
If you me to help, setup a demo.
