### ISSUE TITLE
Plan Plugin - Zoom and buttons

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1270]
### Describe your problem

I configured plan plugin with configureLeaflet option

https://www.tadini.it/temp/panorama_plan.html

two questions:

- zoom cannot be set with `setView`  leaflet option but only with `defaultZoom`  which is not updatable. Correct?

- position of the buttons are fixed. Correct? I can only hide or show them.

Thank You Damien....  Great work.

### Photo Sphere Viewer version

5.7.2

### Plugins loaded

plan

**Comment by mistic100** [comment]
```js
const map = viewer.getPlugin('plan').getLeaflet();

map.setZoom(15);

map.setView(map.getCenter(), 16);
```

everything works

---

the buttons cannot be moved

**Comment by haldo98** [comment]
I have already   `var planPlugin = viewer.getPlugin(PlanPlugin);
`

so I use 

`const map = planPlugin.getLeaflet();
map.setZoom(15);
map.setView(map.getCenter(), 16);
`

but I  have an error   Cannot read properties of undefined (reading 'getLeaflet')

Am I doing something wrong?

**Comment by mistic100** [comment]
I saw in your code you are inside "configureLeaflet", of course "getLeaftlet" returns undefined because you are currently configuring it !

If you want to access leaflet inside "configureLeaflet", just use the "leafletmap" variable.

**Comment by haldo98** [comment]
Yes. Thank You very much.   Now works. I'm playing around with the plugin doing some attempt in order to find the final configuration for me.

Thank You.
