### ISSUE TITLE
zoomDelta and zoomSnap options

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1274]
### Describe your problem

I'd love to implement the `zoomDelta` and `zoomSnap` options in the `configureLeaflet.` 

In leaflet these are declared at init, with `L.map` 

I need help. How can I have those two options?

Thank You.

### Photo Sphere Viewer version

5.7.2

### Plugins loaded

plan

**Comment by haldo98** [comment]
Update:
I found that `const map = planPlugin.getLeaflet();
  map.options.zoomDelta=(0.25);`

works with the buttons +/- I added on the map.   
But not with the keyboard +/- With keyboard the zoomDelta remains = 1

I noticed that  PgUp/PgDown zooms In or zooms out the pano even if the map is maximized.

https://www.tadini.it/temp/panorama_plan.html

Hope it helps.

**Comment by mistic100** [comment]
Unfortunatley Leaflet has no public API to update these options on the fly. I cannot make it configurable.

You can still change them in `configureLeaflet` as you did, you just have to additionally call this to make the keyboard behave correctly.

```
map.keyboard._setZoomDelta(map.options.zoomDelta);
```

**Comment by mistic100** [comment]
> I noticed that PgUp/PgDown zooms In or zooms out the pano even if the map is maximized.

Because Leaflet does not listen to PgUp/PgDown, only +/-
