### ISSUE TITLE
interpolateBackground

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1276]
### Describe your problem

Hi Damien, 

The changelog for 5.2.0 version says:

`fill the gaps in cropped equirectangular panoramas with interpolateBackground [adapter option] (this will become the default in a future version)`

Does this option will become true by default soon?

Just to know if I have to add the option or not for future drone 360 panoramas that does not fill the zenith part.

Thank You

### Photo Sphere Viewer version

5.7.2

**Comment by mistic100** [comment]
why don't you just set to true it if need it ? the option won't disappear even if it's default value changes
