### ISSUE TITLE
Add TextureX and textureY to marker right-click event to enable polygon and polyline marker focus

### ISSUE THREAD

**Issue by juanbrk** [mistic100/Photo-Sphere-Viewer#1277]
### Describe the feature

I would like to be able to focus the viewer on the selected marker once right-clicked. 
I've managed to find a solution (quite simple) for point markers by using their `textureX` and `textureY` values and simply rotating the viewer to that position. 

https://github.com/mistic100/Photo-Sphere-Viewer/assets/7840503/3e05f4c2-b44e-4da1-8e66-0cc300038e37

The thing gets complicated when I try to focus polygon and polyline markers as the polygon can span across the origin of the panorama image and Its centroid be wrongfully calculated, rotating the viewer in the opposite direction of where the marker is actually placed. 

https://github.com/mistic100/Photo-Sphere-Viewer/assets/7840503/7ee56772-4aa7-4ca4-b1c5-93527eae1ca2

There are quite a number of possibilities to be able to focus the selected marker, but these possibilities need a number of calculations in order to correctly position the viewer on the centroid of the viewer that complicate the code's readability and maintenance. Adding `textureX` and `textureY` to marker right-click event provides a simple, clean and easy-to-maintain way of doing It. 

### Alternatives you've considered

A couple of possible solutions have been considered:

- **Calculating polygon and line's centroid**: This involves taking into consideration every point coordinate of the marker and calculating Its centroid to be able to focus the viewer on It. It worked pretty well except for those markers that span across the origin of the panoramic image. In those cases, the centroid was wrongfully calculated, as there Is no easy way to tell if, given a line composed of two points: one at the very beginning of the panoramic image's x coordinate and one at the very end  (Either drawn from left-to-right or right-to-left), a line is a short one that span across the origin of the panoramic image or if that line actually spans across the totality of the panorama image without ever crossing the image's origin. 
<img width="1181" alt="Captura de pantalla 2024-04-02 a la(s) 08 44 08" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/7840503/99b7dca4-6493-48cb-9363-5b51eed26c40">

- **Polygon and line splitting**: Once detected that a line or polygon spans accross the origin of the panoramic image, the marker is split into segments, We can then calculate the centroid for each segment separately and find their weighted average to determine the overall centroid of the line. The thing is that is not always easy to find out if a polygon span across the origin as stated before.
- **Randomly selecting a point**: The last alternative involved selecting a random point of the line or polygon, and focusing the viewer on that point. This also worked well with relatively small polygon and lines. The problem arises when the line or polygon span large areas of the viewer, and we might end up focusing on a line that It has noting to do with the positioning of the right-click-menu, making the menu invisible.

### Additional context

This is how we handle marker click events (left and right click):

```
import {  events, ... } from '@photo-sphere-viewer/core';


const {
  ...,
  ClickEvent,
} = events;

useEffect(() => {
    viewerRef.current?.addEventListener(ClickEvent.type, handleClickEvent);
    const markersPlugin = viewerRef.current?.getPlugin<MarkersPlugin>(MarkersPlugin);
    markersPlugin?.addEventListener('select-marker', handleMarkerClickEvent);

    return () => {
      viewerRef.current?.removeEventListener(ClickEvent.type, handleClickEvent);
      markersPlugin?.removeEventListener('select-marker', handleMarkerClickEvent);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [handleClickEvent]);

```

We import `ClickEvent` from `events` of the `'@photo-sphere-viewer/core` library. 

I also know there is a `SelectMarkerEvent` available from the `'@photo-sphere-viewer/markers-plugin` package, but have failed to implement It on our setup, and I'm unsure It covers the aforementioned need for `textureX` and `textureY` values.

**Comment by mistic100** [comment]
There already is `textureX` and `textureY` on the [ClickEvent data](https://photo-sphere-viewer.js.org/api/types/core.clickdata), those represents where the user clicked, not the marker position. But if `event.data.marker` is not null you know there is a marker there, so you could just rotate to where the user clicked.

And this event also contains `rightClick`.

---

The `SelectMarkerEvent` only contains the marker, but you can access it's centroid with `event.marker.state.position` (this is not documented, I'll fix that). This is of course the the position in yaw+pitch, but not a problem if call `rotate()`  or `animate()`.

**Comment by mistic100** [comment]
You should be able to use `SelecMarkerEvent` the same way you use `ClickEvent`

```js
import {  events as markersEvents, ... } from '@photo-sphere-viewer/markers-plugin';


const {
  SelecMarkerEvent,
} = markersEvents;
```
