### ISSUE TITLE
Feature: support for video files

### ISSUE THREAD

**Issue by djiamnot** [mistic100/Photo-Sphere-Viewer#128]
I would like to be able to play video files as well. I have not looked at the code and I have never used Three.js so I am actually quite clueless about the feasibility of this but I am guessing it should be possible. Are there any plans for that? I would be willing to tackle this but would probably need some pointers/guidance. Any thoughts?

**Comment by mistic100** [comment]
It's not planned but it would be a nice feature. I don't know how to do it.

**Comment by djiamnot** [comment]
sorry, I just realized that I posted in a fork, I meant to post on the original repo.

**Comment by mistic100** [comment]
Sure. But I will keep the issue open. Like VR support it's a feature I would like to do.

**Comment by topherbuckley** [comment]
I'm not 100% sure how you are doing the mapping at the moment for photos, but you should just be able to use the ThreeJS video texture. See docs [here](https://threejs.org/docs/index.html#api/textures/VideoTexture)

Demo [here](https://threejs.org/examples/webgl_materials_video.html)

I might be able to help out with this after finishing the omnitone-PSV demo. It would be something I'd want to use in the future as well.

**Comment by mistic100** [comment]
WIP : https://github.com/mistic100/Photo-Sphere-Viewer/tree/video

Still a lot to do :

- Support multiple sources
- Video controls (progress bar, buffering indicator, start/pause)
- Audio controls
- Support cubemap videos (YT format on two rows : left, front, right, bottom, back, top)

**Comment by hmobs** [comment]
Hey guys. Is the status for video support still as it was in May 2018? Or has the new major version of PSV left the WIP in the dust a little?

**Comment by mistic100** [comment]
I didn't touch it since that day.

**Comment by Ouyang-Zhaoxing** [comment]
The problem with the videoTexture of three.js is that it cannot be played automatically on the mobile terminal. You must actively trigger it.
For this, I created a repository: https://github.com/Ouyang-Zhaoxing/AutoPlayVideoTexture

**Comment by mistic100** [comment]
@Ouyang-Zhaoxing that's a limitation of modern mobile browsers and I will certainly not try to bypass it.
By the way you are allowed to autoplay muted videos.

**Comment by hmobs** [comment]
I would be willing to offer compensation for this feature. If you would be interested in tackling this or if you know of any contributors who would be worth getting in touch with please let me know @mistic100 @Ouyang-Zhaoxing @topherbuckley

**Comment by maslybs** [comment]
> I would be willing to offer compensation for this feature. If you would be interested in tackling this or if you know of any contributors who would be worth getting in touch with please let me know 

Hi! @hmobs I'm working on this feature and you can see the current results here: https://elanta.app/dev/test-viever/ 
Some buttons (play/pause, volume and progress bar) have already been added to the script.
It works like a plugin in this new version and we will be able to update the script if needed.
If it's interesting for you please let me know. maslyb.tf@gmail.com
Thanks.

**Comment by w8w8w8** [comment]
@maslybs hi, thanks for your work, where can i find your code?

**Comment by jumpjosh** [comment]
@maslybs that looks great. Are you going to make this available as a plugin or are people meant to buy it? 

Video support is something I'd really like to add, have so many videos and most players aren't very good at handling them.

**Comment by yaozhufang-rits** [comment]
when i try to use the video sample(equirectangular-video.html), i got some waring as below. and the video did not rending on the window.
can you give some suggestion about how to render 360 video files?

waring:
THREE.MeshBasicMaterial: 'overdraw' is not a property of this material.
THREE.Material: .overdraw has been removed.

**Comment by mistic100** [comment]
The branch is really outdated (2018) no wonder it does not work anymore.

**Comment by mistic100** [comment]
https://github.com/videojs/videojs-vr
