### ISSUE TITLE
[Firefox Android] Camera reverses direction on quick swipe or pan.

### ISSUE THREAD

**Issue by timbotimbo** [mistic100/Photo-Sphere-Viewer#1280]
### Describe the bug

I was testing the compatibility of this package with various browsers and noticed this touch issue on Android Firefox.

Dragging a finger slowly over the viewer moves the camera as expected.
However on quicker movements, the camera will sometimes bounce back in the opposite direction.

It seems like the touch event of the finger lifting up is detected as a new movement.

**Video**
This screen recording starts with 3 slow swipes, that work normally. Followed by some fast swipes that sometimes show the bounce back in the wrong direction.

https://github.com/mistic100/Photo-Sphere-Viewer/assets/11444698/a9c07811-61e2-4fbd-abfd-2aa99ee8ae03

**Reproduction project**
You don't need any specific example to replicate this, I can do this on any demo or example on the documentation website.

**Android Browsers**
- [Firefox](https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en)
- [Firefox Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix&hl=en)
- [Firefox focus](https://play.google.com/store/apps/details?id=org.mozilla.focus&hl=en)

**Android devices**
I tested this on 2 android phones with different versions. It is easier to trigger on the S20FE, but happens on both devices.
- Samsung S20FE, Android 13
- Samsung S8, Android 9

### Online demo URL

https://photo-sphere-viewer.js.org/demos/basic/0-config.html

### Photo Sphere Viewer version

5.7.2

### Plugins loaded

None

### OS & browser

Android 9 & 13, FireFox app v124.3.0

### Additional context

I can not reproduce this using the developer tools of Firefox on Windows 10, it only shows up on mobile.

This does not show up on any chromium browsers on Android.
This does not sow up on Firefox on iOS.

testing with other projects based on threejs:
- I can't trigger anything similar in [google's model-viewer](https://modelviewer.dev/).
- In the deprecated [Panolens](https://pchen66.github.io/Panolens/) I occasionally see something similar happening, but the camera stops moving instead of bouncing in the other direction. (which is less annoying)

**Comment by mistic100** [comment]
I cannot reproduce this on the single phone I have at hand

**Comment by Rai-Rai** [comment]
Can't reproduce this
Tried on Pixel 4a with Android 13 and Firefox 124.2.0

**Comment by yuan116** [comment]
Hi, i able to reproduce it but it was in mobile app version wrap with capacitorjs

it happen in my device (Oppo Find X2)

i created the repo with steps written in README.md
https://github.com/yuan116/capacitor-photo-sphere-viewer-bug
