### ISSUE TITLE
privacy.resistFingerprinting=true degrades photo sphere viewer

### ISSUE THREAD

**Issue by hrdl-github** [mistic100/Photo-Sphere-Viewer#1281]
### Describe the bug

Running the demo https://photo-sphere-viewer.js.org/demos/basic/0-config.html with `privacy.resistFingerprinting` set to `true` using Firefox (set via `about:config`) degrades the image quality.

### Online demo URL

https://photo-sphere-viewer.js.org/demos/basic/0-config.html

### Photo Sphere Viewer version

5.7.2

### OS & browser

Firefox, GNU/Linux

### Additional context

`privacy.resistFingerprinting` needs to be enabled. Originally reported here: https://github.com/immich-app/immich/issues/8569

**Comment by vekin03** [comment]
Great find!

By enabling this setting in Firefox, [I can see](https://webglreport.com/?v=2) that the maximum size of WebGL textures drops from 16384 to just 2048 pixels. Therein lies the problem.

I doubt the author can do anything about it.

But **you** can do something: _always_ use [equirectangular tiles](https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html)! In this way, each tile will not exceed the maximum size allowed, with or without this setting ;-)

I tested it with one panorama that uses tiling, and I can confirm that the image is still sharp.

**Comment by mistic100** [comment]
@vekin03 is correct, it this also the only solution for high quality display on smartphones which generally have a maximum texture size of 4096px
