### ISSUE TITLE
Read and expose position-related metadata

### ISSUE THREAD

**Issue by hrdl-github** [mistic100/Photo-Sphere-Viewer#1282]
### Describe the feature

This was already mentioned in https://github.com/mistic100/Photo-Sphere-Viewer/issues/492, but never implemented. Example extracted using `exiftool -X`:
```
<Composite:GPSAltitude>300 m Above Sea Level</Composite:GPSAltitude>
<Composite:GPSLatitude>5 deg 32&#39; 9.82&quot; N</Composite:GPSLatitude>
<Composite:GPSLongitude>6 deg 22&#39; 6.22&quot; E</Composite:GPSLongitude>
<Composite:GPSPosition>5 deg 32&#39; 9.82&quot; N, 6 deg 28&#39; 6.22&quot; E</Composite:GPSPosition>
```

### Additional context

This is relevant for both the virtual tour plugin and the plan plugin.

**Comment by mistic100** [comment]
To be fair it seems to be very badly organized, there is `Composite:GPSLatitude` and `GPS:GPSLongitude` + `GPS:GPSLongitudeRef`. All those are XMP metadata, whereas I suspect most people use EXIF for tagging.

I will not be able to read EXIF data as it is much more complicated than XMP tags.

**Comment by mistic100** [comment]
Also it is NOT relevant for the virtual tour and plan plugins : the coordinates must be known without having to load every (large) files beforehand.
