### ISSUE TITLE
Plan - keep marker tooltip class

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1283]
### Describe the bug

Hi Damien...   when bandwidth will be restored....:

Custom tooltip on plan plugin is not showed as the ones on the pano. 
I think it's similar to #989 

In the demo URL the marker just on the right of the pinImage "Bolettone"

### Online demo URL

https://www.tadini.it/temp/panorama_plan.html

### Photo Sphere Viewer version

5.7.2

### Plugins loaded

plan

### OS & browser

win 11 - chrome 123

**Comment by mistic100** [comment]
Tooltips in the "plan" plugin are entirely managed by Leaflet itself, I have no plan (!!) to re-implement it using PSV tooltips.

But the CSS class is transmitted, see here
https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/plan-plugin/src/components/PlanComponent.ts#L371

**Comment by haldo98** [comment]
Thank You for the explanation Damien. I'll try...
