### ISSUE TITLE
The panorama image is bent

### ISSUE THREAD

**Issue by nmthangdn2000** [mistic100/Photo-Sphere-Viewer#1284]
### Describe the bug

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/44263120/646cdbfa-e168-4038-b303-ae96184933b7)
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/44263120/7d6bee77-2b5e-4b8e-9bdb-0a2633b55be6)

My images are normal on the 3DVista Virtual Tour

However, when using your library, my image is bent, and I still haven't found a solution.

Looking forward to receiving help.

Thank you

### Photo Sphere Viewer version

5.7.2

### OS & browser

win 11 - chrome 123

**Comment by HungFpoly** [comment]
I also got the same error

**Comment by mistic100** [comment]
This is inherent to the rendering system.

The only solution you have is to increase the `resolution` parameter https://photo-sphere-viewer.js.org/guide/adapters/equirectangular.html#configuration

```js
adapter: [EquirectangularAdapter, {
  resolution: 128
}]
```

**Comment by nmthangdn2000** [comment]
@mistic100,
Oh it worked very well, thank you very much

**Comment by nmthangdn2000** [comment]
@mistic100 

Because the performance is not good, I want to use resolution: 128 for detailed images, and 64 for other images.

I used the viewer.config.adapter to reassign the value but it doesn't seem to work.

I will be very grateful if you can guide me in this matter.

Thank

**Comment by mistic100** [comment]
This is not possible at all, sorry.
