### ISSUE TITLE
Non-default adapters ignore and override mast elements panoData

### ISSUE THREAD

**Issue by hrdl-github** [mistic100/Photo-Sphere-Viewer#1285]
### Describe the bug

Using e.g. the `EquirectangularTilesAdapter` sets the pose heading to 0, independently whether it is set via XMP in the base image or manually specified via `panoData`. This becomes apparent when using in combination with e.g. the plan plugin (which visualises the heading) or adding markers. Some pointers:
https://github.com/mistic100/Photo-Sphere-Viewer/blob/962331f3325010fb98493ba501450a43cec1a4f8/packages/equirectangular-tiles-adapter/src/EquirectangularTilesAdapter.ts#L196-L199
does not feature all the parameters as defined in https://github.com/mistic100/Photo-Sphere-Viewer/blob/962331f3325010fb98493ba501450a43cec1a4f8/packages/core/src/adapters/AbstractAdapter.ts#L84-L89
The default adapters loads the metadata as intended https://github.com/mistic100/Photo-Sphere-Viewer/blob/962331f3325010fb98493ba501450a43cec1a4f8/packages/core/src/adapters/EquirectangularAdapter.ts#L151-L172 using the private function https://github.com/mistic100/Photo-Sphere-Viewer/blob/962331f3325010fb98493ba501450a43cec1a4f8/packages/core/src/adapters/EquirectangularAdapter.ts#L204

### Photo Sphere Viewer version

5.7.2

### OS & browser

GNU/Linux + Firefox 124

**Comment by mistic100** [comment]
This is totally expected as XMP data are embedded in the file, and other adapters use multiple files.

This is explicitely documented https://photo-sphere-viewer.js.org/guide/config.html#panodata

Use `sphereCorrection` if you need the correct the orientation.
