### ISSUE TITLE
New Adapter: dual fish eyes

### ISSUE THREAD

**Issue by truongsinh** [mistic100/Photo-Sphere-Viewer#1288]
### Describe the feature

Insta360 and Gear 360 save their raw image as dual fish eye texture. I have Insta360 and can provide some of their video/picture for reference. Insta360 provide studio app on Mac and Windows with  different stitch strategy, but I think we can just get 1 to work first, and can improve later.

### Alternatives you've considered

Manually convert all Insta360 image and video to equirectangular

### Additional context
Stitching options from Insta360 studio

<img width="303" alt="Screenshot 2024-04-12 at 12 20 02 AM" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/358585/c179ae8f-7dbf-4ae6-8f76-47283ccbbdb8">

Prior art: https://github.com/acalcutt/Gear360_html5_viewer

_No response_

**Comment by mistic100** [comment]
yes please share some examples

**Comment by truongsinh** [comment]
> Not trying to hijack OP's feature request here; if I understood correctly this is identical feature/usecase, just a different camera. I have no experience with Insta360 cameras or files, but I imagine they use similar approach. Anyway:

Correct, same format, just different cam :)

Anyway,

**Comment by mistic100** [comment]
So I tried to adapt the linked code to newer versions of ThreeJS. The fact is I don't understand the math involved, but my version does not work, with or without the updates of UVs, the result is the same: there a big seam and deformation on the joint.

```ts
import { BufferAttribute, BufferGeometry, Material, Mesh, MeshBasicMaterial, SphereGeometry } from 'three';
import { type Viewer } from '../Viewer';
import { EquirectangularAdapter } from './EquirectangularAdapter';
import { SPHERE_RADIUS } from '../data/constants';

export class DualFisheyeAdapter extends EquirectangularAdapter {
    static override readonly id: string = 'dual-fisheye';
    static override readonly VERSION = PKG_VERSION;

    constructor(viewer: Viewer) {
        super(viewer);
    }

    override createMesh(): Mesh<BufferGeometry, Material> {
        const geometry = new SphereGeometry(
            SPHERE_RADIUS,
            this.SPHERE_SEGMENTS,
            this.SPHERE_HORIZONTAL_SEGMENTS
        ).scale(-1, 1, 1).toNonIndexed();

        const uvs = geometry.getAttribute('uv') as BufferAttribute;
        const normals = geometry.getAttribute('normal') as BufferAttribute;

        for (let i = 0; i < uvs.count; i++) {
            for (let j = 0; j < 3; j++) {
                const x = normals.getX(j);
                const y = normals.getY(j);
                const z = normals.getZ(j);

                if (i < uvs.count / 2) {
                    const correction = (x == 0 && z == 0) ? 1 : (Math.acos(y) / Math.sqrt(x * x + z * z)) * (2 / Math.PI);
                    uvs.setXY(j,
                        x * (1 / 4) * correction + (1 / 4),
                        z * (1 / 2) * correction + (1 / 2)
                    );
                } else {
                    const correction = (x == 0 && z == 0) ? 1 : (Math.acos(-y) / Math.sqrt(x * x + z * z)) * (2 / Math.PI);
                    uvs.setXY(j,
                        -1 * x * (1 / 4) * correction + (3 / 4),
                        z * (1 / 2) * correction + (1 / 2)
                    );
                }
            }
        }

        return new Mesh(geometry, new MeshBasicMaterial());
    }
}
```

**Comment by mistic100** [comment]
The adaptation was wrong, this one works much better. There is magic constant `c = 0.947` which might depend on the specific shot/lens...

```ts
import { BufferAttribute, BufferGeometry, Material, Mesh, MeshBasicMaterial, SphereGeometry } from 'three';
import { type Viewer } from '../Viewer';
import { SPHERE_RADIUS } from '../data/constants';
import { EquirectangularAdapter } from './EquirectangularAdapter';

export class DualFisheyeAdapter extends EquirectangularAdapter {
    static override readonly id: string = 'dual-fisheye';
    static override readonly VERSION = PKG_VERSION;

    constructor(viewer: Viewer) {
        super(viewer);
    }

    override createMesh(): Mesh<BufferGeometry, Material> {
        const geometry = new SphereGeometry(
            SPHERE_RADIUS,
            this.SPHERE_SEGMENTS,
            this.SPHERE_HORIZONTAL_SEGMENTS
        ).scale(-1, 1, 1).toNonIndexed();

        const uvs = geometry.getAttribute('uv') as BufferAttribute;
        const normals = geometry.getAttribute('normal') as BufferAttribute;

        for (let i = 0; i < uvs.count; i++) {
            for (let j = 0; j < 3; j++) {
                const index = i * 3 + j;

                const x = normals.getX(index);
                const y = normals.getY(index);
                const z = normals.getZ(index);

                const c = 0.947;
                if (i < uvs.count / 6) {
                    const correction = (x == 0 && z == 0) ? 1 : (Math.acos(y) / Math.sqrt(x * x + z * z)) * (2 / Math.PI);
                    uvs.setXY(index,
                        x * (c / 4) * correction + (1 / 4),
                        z * (c / 2) * correction + (1 / 2)
                    );
                } else {
                    const correction = (x == 0 && z == 0) ? 1 : (Math.acos(-y) / Math.sqrt(x * x + z * z)) * (2 / Math.PI);
                    uvs.setXY(index,
                        -1 * x * (c / 4) * correction + (3 / 4),
                        z * (c / 2) * correction + (1 / 2)
                    );
                }
            }
        }

        geometry.rotateX(-Math.PI / 2);
        geometry.rotateY(Math.PI);

        return new Mesh(geometry, new MeshBasicMaterial());
    }
}
```

There is still a visible seam, which I was still not able to hide, even with the other magic numbers on this version https://github.com/acalcutt/Gear360_html5_viewer/blob/master/lib/360-view-image.js

![Uploading Capture d’écran du 2024-06-06 13-34-20.png…]()

**Comment by mistic100** [comment]
@truongsinh @jtoppine do you have an example panorama I could use for a demo on PSV website ?  
prefarably less dark than the warehouse and less creeby than the bathroom :)

**Comment by mistic100** [comment]
Can someone answer Rai-Rai question ? To make sure adding this adapter is really useful.

**Comment by rishubil** [comment]
I'd like to share my use case here.

I travel and shoot 360-degree videos with an Insta360.
The original videos are stored as-is on my personal NAS.
I could convert the videos beforehand, but since I don't know which ones I'll end up using, I just keep them on the NAS in their original state.

Sometimes I want to look back on a trip later or show a video to others.
But there's no way to tell which of the original videos in the NAS's web-based file browser is the one I want.
So I wanted a web-based 360-degree video player that could quickly identify the contents of the files.

However, a few days ago, I found this project and based on the contents of the dual-fisheye branch,
I roughly created a DualFisheyeVideoAdapter and tested it.

The DualFisheyeVideoAdapter can read and play `.lrv` files, so I can quickly find the videos I want on the NAS.
(Videos shot with the Insta360 X3 are saved as low-resolution dual-fisheye MP4 files with the `.lrv` extension, and as two separate high-resolution videos with the `.insv` extension).

It would be nice if it could also read and play `.insv` files, but as it is, I'm very happy with it.

**Comment by mistic100** [comment]
The library will never be able to read obscure proprietary formats, it entirely relies on the browser decoding capability. Also I will not be able to read and synchronize two video files.

**Comment by rishubil** [comment]
> The library will never be able to read obscure proprietary formats, it entirely relies on the browser decoding capability. Also I will not be able to read and synchronize two video files, they will have to be glued in a single file beforehand, if the low-resolution version is not HQ enough.

I understand. What I meant to say was that the implementation of the DualFisheyeAdapter was very useful for my actual use case.
