### ISSUE TITLE
VirtualTour Plugin - How to set the initial view depending on origin

### ISSUE THREAD

**Issue by Rai-Rai** [mistic100/Photo-Sphere-Viewer#1289]
### Describe your problem

Hi,

you have this great demo on https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#usage which shows the possibilities of the tour plugin.

I took a look at this and there is one thing that I don't understand:
If I navigate from Image 1 to image 2, I then automatically look into the direction that i "moved" to (To the lighthouse). If i navigate from 2 to 3 this is the same (looking on the sea).

Also if I turn around on image 3 and go to image 2 I then look automatically in the direction of image 1 where I could/would also move as a human.

What I don't understand: How is this done? I first thought that the orientation is just not changed if you go through the tour, but this is not true. If I move the panorama so that the arrow is at the border of the screen then the orientation is still changed after I move to the next image.

My expectation would have been that there is an initial orientation set "If arrow on 'image 1' with target 'image 2' is pressed then set the target panorama to orientation xxx".
But apparently that is not there so I don't understand how this works in the demo.

Reason for my question: Looking into using your great lib for a virtual room tour (so without GPS coordinates).
Let's assume you have a "typical" flat where you have one central corridor that is used to access all room. If you enter the room the orientation of the room panorama is clear since there is only a single door to access the room. 
But if you move back to the corridor when you suddenly have multiple rooms that access the corridor and the orientation of the corridor needs to change according to the origin of the user. 
Same if you have rooms that are in addition connected with each other through a separate door
(Of course I could not use the tour plugin and implement my own tour by using markers. But before I send the time I'd ask if I just overlooked something. 

If what I described is really not there: is there a possibility that this will be added as a feature?

### Online demo URL

https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#usage

### Photo Sphere Viewer version

5.7.2

### Plugins loaded

Tour Plugin

**Comment by mistic100** [comment]
I have a very hard time understaning your question.

When you click on an arrow, the viewer first rotates in the direction if the arrow then loads the next panorama. It works because all panoramas are oriented with the north corresponding to yaw=0. You can see on the demo source that this is done by tweking the panoHeading for each panorama because my examples images are not correctly oriented (this also could be done in Photoshop by translating the image left or right).

This system is highly configurable with [`transitionOption`](https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#configuration) where you can define exactly where to look at before loading the next node.

**Comment by mistic100** [comment]
By the way picture 5 is linked to three other nodes in totally different orientation, and I think it works as you expect if comming from 3, 4 or 6

**Comment by Rai-Rai** [comment]
Thanks for the answer and information. Likely the north and/or pose Heading was the information that I've missed
I'll try this with some example images next week.

**Comment by Rai-Rai** [comment]
Just as a follow up if someone is looking for exactly this answer:
Creating the panorama so that yaw=0 is north or modifying this with `poseHeading` is not going to work for my project since one usecase is indoor panoramas. While it's possible to offer an option to the user to configure `poseHeading` this likely won't work well or will be hard to understand why it is needed.

For me, the attributes of the configured links solve the issue
For panorama1 the configuration is `position: { yaw: -0.5, pitch: -0.5 }, linkOffset: {yaw: 1, pitch: 1}`
Which means that panorama2 will be initializes with position `yaw: -0.5, pitch: -0.5`
Whereas the marker in panorama1 will be placed at `yaw: +0.5, pitch: +0.5` (-0.5 + 1 = +0.5)
I'll post the full example config at the end of this text.

@mistic100: A small feature request here would be to offer an alternative to `linkOffset`,  something like `linkPosition` which is the absolute position in the starting panorama. Of course it works with offset, but you need to calculate all the time to get it right.
To place the marker in the starting panorama I'd like to just click there, get the coordinates and I'm done.
Now I first need to get the wanted position of the target panorama if the link will be clicked, then I'm able to calculate the offset


```this.virtualTourPlugin.setNodes([
      {
        id: '1',
        panorama: './assets/testpanorama.jpg',
        name: 'One',
        caption: `One`,
        links: [
          { nodeId: '2', position: { yaw: -0.5, pitch: -0.5 }, linkOffset: {yaw: 1, pitch: 1} }
        ],
        // markers: [markerLighthouse],
      },
      {
        id: '2',
        // panorama: './assets/testpanorama.jpg',
        panorama: 'https://photo-sphere-viewer-data.netlify.app/assets/tour/key-biscayne-1.jpg',
        name: 'Two',
        caption: `Two`,
        links: [
          //position is the position in the target panorama.
          //offset moves the marker in the original panorama --> position+offset = Position of marker
          { nodeId: '1', position: { yaw: 0.5, pitch: 0.5 }, linkOffset: {yaw: -1, pitch: -1} }
        ],
        // markers: [markerLighthouse],
      },
    ]);```
