### ISSUE TITLE
Crashes WebGL frequently on Chrome & Safari, fine on Firefox

### ISSUE THREAD

**Issue by JoeGaebel** [mistic100/Photo-Sphere-Viewer#129]
PhotoSphere viewer version: 3.2.2 and 3.2.3
ThreeJS version: 0.84.0
Chrome version: 58.0.3029.110 (64-bit)
Safari version: 10.1.1 (12603.2.4)

I haven't been able to isolate a cause, but it seems that rendering and switching between multiple photospheres crashes this version of chrome and safari, but works perfectly on Firefox.

Please see https://asaudade.herokuapp.com. Clicking on the red textured markers changes photospheres, and this causes frequent crashes on chrome and safari.

Any suggestions on fixing it, or on more information to provide I'm happy to oblige.

Thanks!

**Comment by mistic100** [comment]
Hello,

I cannot even open the page on my office computer, it immediately crashes (it's not a small computer but hasn't any GPU).

What is the size of your panoramas ? You might consider to lower the resolution, have some mercy for small configurations and smartphones :-)

**Comment by JoeGaebel** [comment]
Thanks for the quick reply!

There are two photospheres that I'm transitioning between. They started at `18432px by 1998px` and `9102px by 5532px`, and after your suggestion, I reduced them to `2000px by 217px` and `500px by 304px`.

This had no effect on the crash. Transitioning between the first and second photospheres without cache still caused consistent crashing.

For this reason, and also given that it works fine in Firefox and on mobile browsers, I believe this is something that can be fixed in either Chrome's rendering, or in the PhotosphereViewer package.

Another interesting point, is that after the first page crash, subsequent reloads work fine. So there is some interaction about transitioning between spheres when the sphere image has been cached, versus when it has not been cached.

Any ideas?

**Comment by mistic100** [comment]
Nonetheless I think your 19kpx is too big, you have the risk to overflow the canvas internally used to store the texture.

I will try to reproduce on my home computer.

**Comment by fuyun2024** [comment]
Hi, i have encountered this problem, and on the phone is not open, in addition to low resolution, there are other ways

**Comment by mistic100** [comment]
What are you trying to say ? I don't understand.

**Comment by JoeGaebel** [comment]
@mistic100, I've got my images set to resize the sphere images to 1200px in width, and a proportional height. The bug however is still present when doing PSV.setPanorama

**Comment by sillygoose4u** [comment]
Clearing the panorama cache before setting the already loaded panorama seems to help.
------
PSV.clearPanoramaCache('panorama_image.jpg');
PSV.setPanorama('panorama_image.jpg');
------

**Comment by mistic100** [comment]
Sorry I didn't have time to look at this. You can disable the cache with `cache_texture: false`

@Strae did you encountered this problem ?
