### ISSUE TITLE
Polygon with Holes Marker

### ISSUE THREAD

**Issue by AliHasan71** [mistic100/Photo-Sphere-Viewer#1293]
### Describe your problem

I am able to successfully create polygon markers. Is there any way to define polygons with holes using this library?

### Photo Sphere Viewer version

5.4.2

**Comment by AliHasan71** [comment]
Is there any workaround solution in the meantime? Like using paths to define polygons instead or patterns along with polygons?

When spherical coordinates are given for the polygon attribute, how are they transformed into an SVG <polygon> points?

**Comment by mistic100** [comment]
Please give a try to this branch https://github.com/mistic100/Photo-Sphere-Viewer/tree/polygon-hole

The definition of a polygon with holes is similar to GeoJSON syntax if you are familiar with it.

```js
                                polygonPixels: [
                                    [
                                        // main shape
                                        [2941, 1413], [3042, 1402], [3041, 1555], [2854, 1559],
                                        [2739, 1516], [2775, 1469], [2941, 1413],
                                    ],
                                    [
                                        // first hole
                                        [2900, 1450], [2950, 1450], [2950, 1500], [2900, 1500],
                                    ]
                                ],
```

**Comment by AliHasan71** [comment]
Yes I am familiar with it. I actually tried that and it didn't work previously. But I see you have now made a Polygon into a Path.

I am using Photo Sphere Viewer via npm. Is there any way I can test this branch from there? How can I test it with my project?

**Comment by mistic100** [comment]
you will have to build it locally and use "npm link"/"yarn link"

https://photo-sphere-viewer.js.org/guide/development.html

**Comment by AliHasan71** [comment]
Works nicely! Just had to add the fillRule property to the svgStyle so that filled polygons also have the holes cutout.

Any chance this can be incorporated in the next release? Thanks a bunch.

**Comment by mistic100** [comment]
can you provide an example of your polygon where you have to change fillRule ? because I don't need it on the demo

**Comment by AliHasan71** [comment]
So firstly, after testing the branch locally, `plugin-markers.html` in the `examples` folder doesn't seem to open on the browser.

My polygon is not selfcrossing. Please refer to the below images.

**Without fillRule in SVGStyle:**

<img width="642" alt="Screenshot 2024-05-16 at 5 00 26 PM" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/83886516/6ac6dc6b-eb14-4b44-a3d3-c1af6d4b5cad">
<img width="1042" alt="Screenshot 2024-05-16 at 5 01 21 PM" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/83886516/7b17cded-e6cc-4be5-a0eb-17a59956bffe">

**With fillRule in SVGStyle**

<img width="598" alt="Screenshot 2024-05-16 at 5 02 27 PM" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/83886516/1e137552-29e4-484f-8f41-2f4ed9f3c04d">
<img width="1039" alt="Screenshot 2024-05-16 at 5 02 42 PM" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/83886516/9ee5c214-165b-4e88-bf83-bbecdad41dc9">

**Comment by mistic100** [comment]
I need the actual data !

**Comment by AliHasan71** [comment]
Sorry about that. I have attached the entire MarkerConfig JSON, which includes the polygon vertices.
[polygon.json](https://github.com/mistic100/Photo-Sphere-Viewer/files/15335902/polygon.json)

**Comment by mistic100** [comment]
Ok I understand the problem : I forced the holes coordinates to be in reverse order, but as you already did it (rightfully), it cancels out

https://github.com/mistic100/Photo-Sphere-Viewer/blob/0ec9d422df780056c2b3f0523059f54e5232af14/packages/markers-plugin/src/markers/MarkerPolygon.ts#L68

I will remove this array inversion.

**Comment by AliHasan71** [comment]
Yes that makes complete sense why the `evenodd` value for the `fillStyle` property made it work regardless.

I have tested it and everything works perfectly including hovering, tooltip, etc. Thank you for the feature! Looking forward to the `5.8.0` release.
