### ISSUE TITLE
how to setCursor 

### ISSUE THREAD

**Issue by HungFpoly** [mistic100/Photo-Sphere-Viewer#1294]
### Describe your problem

Hi everybody,
I want to reset the mouse pointer like this,
then how should I do it?
thank you
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/70883077/4fe6a556-dea4-443b-bf96-c1ae7c5b0659)
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/70883077/766b12a3-c1a8-4f8f-a8f4-bae240302e96)

### Online demo URL

https://matterport.com/discover/space/wBEFkyJTUnW

### Photo Sphere Viewer version

5.7.2

**Comment by mistic100** [comment]
I don't understand, there is no mouse cursor in you screenshots

**Comment by HungFpoly** [comment]
yeah I get it.
Thank you for your support.
