### ISSUE TITLE
StereoPlugin must be start from potrait mode, wrong gyro sensor move if start from landscape mode

### ISSUE THREAD

**Issue by riloraspopo** [mistic100/Photo-Sphere-Viewer#1298]
### Describe the bug

StereoPlugin must be start from potrait mode, wrong gyro sensor move if start from landscape mode

even i try on example, i still got this issue too
https://photo-sphere-viewer.js.org/demos/plugin-stereo.html

some on say using  
absolutePosition: true,
but i still got this issue..
help

### Online demo URL

https://photo-sphere-viewer.js.org/demos/plugin-stereo.html

### Photo Sphere Viewer version

5.7.3

### Plugins loaded

 GyroscopePlugin,             StereoPlugin,

### OS & browser

android 14, chrome

**Comment by mistic100** [comment]
I might have found the issue, still have to test the fix.
