### ISSUE TITLE
Video Plugin

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1299]
### Describe your problem

I  tried to switch one video that I have with the use of the video Plugin.

No errors but the video is zoomed in and not fully displayed. I enabled the keyboard controls and with + and - key I can zoom out or in a little. But the full frame of the video is not displayed.

I tried also panodata option but no luck.

the actual video is here:  https://www.tadini.it/video/suretta/index.html

with the video plugin here: https://www.tadini.it/video/suretta/video_suretta.html

can You help me?

### Photo Sphere Viewer version

5.7.3

### Plugins loaded

video

**Comment by mistic100** [comment]
Only full equirectangular videos are supported.

**Comment by haldo98** [comment]
Ok. Thank You.
