### ISSUE TITLE
Gyroscope interaction

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#13]
Try to use the gyro API to rotate the panorama like the native Google viewer.

http://www.tomg.co/gyrojs seems a promising wrapper

**Comment by ZackMattor** [comment]
:+1: I'm using Jeremy's version still because it supports device orientation :)

..it does have some glitches though.

**Comment by ZackMattor** [comment]
Also... This is the shim called out on MDN.

https://github.com/dorukeker/gyronorm.js
https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation

**Comment by marcin1337** [comment]
I managed to do this using a modified version of 
http://threejs.org/examples/js/controls/DeviceOrientationControls.js

and adding a toggle button to the nav bar to switch from Gyroscope movement and normal touch movement
![togglegyro](https://cloud.githubusercontent.com/assets/1388065/13460921/8fc15db0-e07e-11e5-9d4b-7c411d51c092.PNG)

the button stops the normal camera go to direction

this can be seen here
http://spotbrowser.com/spot/56d2e5742375c3751018e77f/0
*note the button is only active in the navbar when the user agent is mobile*

**Comment by mistic100** [comment]
Nice ! If it's built in THREE directly it will be much easier to implement.

Glad to see a implementation for virtual visit. I'm planning a full-featured specific library for this https://github.com/mistic100/Photo-Sphere-Tour (automatic creation and position of hotspots, transition, etc).
