### ISSUE TITLE
issue using this library

### ISSUE THREAD

**Issue by tsotneguti** [mistic100/Photo-Sphere-Viewer#130]
I wanted to use Photo Sphere Viewer in my project. So I ran

`npm i photo-sphere-viewer`
It appears to have downloaded the modules.

Then inside my project I did:

`import PhotoSphereViewer from 'photo-sphere-viewer/dist/photo-sphere-viewer';`
But I get error:

> Failed to compile.
> 
> Error in ./~/photo-sphere-viewer/dist/photo-sphere-viewer.js
> Module not found: 'D.js' in /home/ghy/WebstormProjects/mia-map/node_modules/photo-sphere-viewer/dist
> 
>  @ ./~/photo-sphere-viewer/dist/photo-sphere-viewer.js 9:4-55

Can anyone help me spot what is wrong?

PS. I think following line is causing issue (inside photo-sphere-viewer.js):

  ```
if (typeof define === 'function' && define.amd) {
    define(['three', 'D.js', 'uevent', 'doT'], factory);
  }
```
but I am even surprised why it enters inside this if as I didn't know I had require.js installed.

PPS. I have a react application created by create-react-app

**Comment by topherbuckley** [comment]
Not familiar with React, and not quite sure of the import syntax you are using, but the error is pointing to the fact that D.js is not found so my first guess would be that you don't have that properly installed. 

Did you install D.js and the other dependencies listed on the README with npm as well?

**Comment by psyke089** [comment]
I'm having the same issue.

All dependencies are installed. It occurs using import, as well as require syntax.

Could the problem be the package names in the line mentioned by @tsotneguti ?

Changing  'D.js' and 'doT' to 'd.js' and 'dot', as in line 12, seems to resolve the issue.

**Comment by remicmacs** [comment]
Hello @psyke089. 
Could you show how you solved this issue please ?

Cause I'm having trouble using this package with React and npm.
I'm having : 
`Module not found: "~\dev\test-360-component\node_modules\doT\doT.js" does not match the corresponding path on disk "dot"` in the terminal. 
And yet at line 12 in photo-sphere-viewer.js : 
`module.exports = factory(require('three'), require('d.js'), require('uevent'), require('dot'));`

**Comment by simonmeusel** [comment]
Could it be, that the package doesn't register any main file in the package.json, so no starting point is set!

**Comment by speich** [comment]
The problem is the wrong module name. The AMD module definition states that

> Module identifiers may not have file-name extensions like ".js".

see https://github.com/amdjs/amdjs-api/wiki/AMD
