### ISSUE TITLE
iOS Fullscreen problem

### ISSUE THREAD

**Issue by matis4work** [mistic100/Photo-Sphere-Viewer#1302]
### Describe the bug

I know that handling of fullscreen in iOS's Safari is [already implemented here](https://github.com/mistic100/Photo-Sphere-Viewer/blob/3ec9eab030a459528facee5ebd9a558b9e4e537d/packages/core/src/utils/browser.ts#L131), but from my tests it's not working properly, at least in the newest iOS version.

### Online demo URL
https://photo-sphere-viewer.js.org/demos/basic/0-config.html

### Photo Sphere Viewer version
5.7.3

### OS & browser
iOS - Version 17.4.1

**Comment by mistic100** [comment]
Please use the search bar

#860 #985
