### ISSUE TITLE
[Microsoft Edge] version: 92.0.902.67,psv.ts:441 PhotoSphereViewer: stylesheet "@photo-sphere-viewer/core/index.css" is not loaded

### ISSUE THREAD

**Issue by hrkcloud** [mistic100/Photo-Sphere-Viewer#1306]
### Describe the bug

[Microsoft Edge] version: 92.0.902.67
psv.ts:441 PhotoSphereViewer: stylesheet "@photo-sphere-viewer/core/index.css" is not loaded
PhotoSphereViewer: stylesheet "@photo-sphere-viewer/markers-plugin/index.css" is not loaded

### Photo Sphere Viewer version

5.7.3

### OS & browser

windows,[Microsoft Edge] version: 92.0.902.67

**Comment by mistic100** [comment]
posting a single error line is not a proper bug report !

you need to add your complete source code and/or a demo
