### ISSUE TITLE
Issue with displaying panoramas using EquirectangularTilesAdapter in PhotosphereView

### ISSUE THREAD

**Issue by luisjm1992** [mistic100/Photo-Sphere-Viewer#1308]
### Describe the bug

I'm trying to display a panoramic image from an Amazon S3 bucket via CloudFront using the EquirectangularTilesAdapter adapter in PhotosphereView. Here's the image I'm trying to load:

[This is image](https://dc3vyqf4n37w5.cloudfront.net/panoramas/imagen_1.webp)

```
const baseUrl = 'https://dc3vyqf4n37w5.cloudfront.net/panoramas/'

const viewer = new Viewer({
    container: 'viewer',
    adapter: EquirectangularTilesAdapter,
    panorama: {
        width: 12000,
        cols: 16,
        rows: 8,
        baseUrl:`${baseUrl}imagen_1.webp`,
        tileUrl: (col, row) => {
            const num = row * 16 + col + 1;
            return `${baseUrl}sphere-tiles/image_part_${('000' + num).slice(-3)}.jpg`;
        },

    }
});

viewer.addEventListener('click', ({ data }) => {
    console.log(`${data.rightclick ? 'right ' : ''}clicked at yaw: ${data.yaw} pitch: ${data.pitch}`);
});

```
When I try to check if the panorama configuration was successful, it appears like this:

I don't understand or can't seem to solve this. I appreciate your help.

### Online demo URL

https://codepen.io/panelessolares/pen/abrNvYW?editors=1010

### Photo Sphere Viewer version

5.7.4

### OS & browser

 Windows and Chrome

### Additional context

I'm working on a project to display panoramic images from my Amazon S3 bucket using CloudFront for distribution. To achieve this, I'm using a library called PhotosphereView along with the EquirectangularTilesAdapter adapter. The goal is to create an interactive viewer where users can explore these panoramic images.

The issue I'm facing is that when loading the viewer to see the panoramic image, it doesn't display correctly. Instead of seeing the complete and panoramic image, I see something different or incorrect in the viewer.

**Comment by mistic100** [comment]
Also using a large image as `base` kinda ruins the goal of the tiles adapter. The base image must be loaded as fast as possible.
