### ISSUE TITLE
Examples dont work

### ISSUE THREAD

**Issue by schroef** [mistic100/Photo-Sphere-Viewer#131]
I just downloaded this zip and wanted to check the example. They dont load or do anything locally is that correct?

In chrome inspector is says PhotoViewer is not defined, yet its a variable so i dont understand why this error shows. See line 111 in the index.htm

**Comment by mistic100** [comment]
You need to download the master branch, or build yourself the dev branch (see the readme).

And you also have to run `bower install ` (+ `npm install ` for the build).
