### ISSUE TITLE
Add support for web-xr

### ISSUE THREAD

**Issue by rats4final** [mistic100/Photo-Sphere-Viewer#1313]
### Describe the feature

I know this might be duplicate, but this library would much more complete if there was support for web xr, allowing us to use meta quest and other specially inside the virtual tour

### Alternatives you've considered

i have tried using the default fullscreen feature of the meta quest 2 while being inside the virtual tour using react photo sphere viewer but it looks a bit bugged and also you cannot click on the arrows anymore

**Comment by mistic100** [comment]
> I know this might be duplicate

Then search for existing issues before posting :-)

https://github.com/mistic100/Photo-Sphere-Viewer/issues/571
