### ISSUE TITLE
photo-sphere-viewer Using Equirectangular tiles adapter; After switching scenes, there will be some image slices of the shirt scene left behind

### ISSUE THREAD

**Issue by kuiLongWen** [mistic100/Photo-Sphere-Viewer#1316]
### Describe the bug

photo-sphere-viewer Using Equirectangular tiles adapter; After switching scenes, there will be some image slices of the shirt scene left behind

### Photo Sphere Viewer version

5.7.4

### OS & browser

win10 & chrome  124.0.6367.208

**Comment by mistic100** [comment]
Missing demo
