### ISSUE TITLE
Image Distortion

### ISSUE THREAD

**Issue by IceBlueFire** [mistic100/Photo-Sphere-Viewer#132]
I've tried a variety of panorama apps for the iPhone, but when i load them into the viewer, i get some image distortion that stretches the images in a weird way, however the images look fine while looking at them in the native apps.  Is there a setting that i'm messing up somewhere that is messing with this?

Edit: Example link removed.

**Comment by mistic100** [comment]
Are you referring to the the horizontal and vertical lines not being straight ? This is normal has how the sphere is drawn for performances.

Or the top and bottom being stretched ? It also occurs on desktop and this is because your panorama is not a sphere !

**Comment by mistic100** [comment]
If you want to use partial projections (like rectilinear) you must define the corresponding area using XMP tags, see my answer here #78 (comment)

**Comment by IceBlueFire** [comment]
Yeah, i'm referring to the cars looking super compact when you look straight on at them, but then stretching back out as you continue to spin around.  I'll take a look at that answer and give it a go, thanks!

**Comment by mistic100** [comment]
The best way is to fit your image in a 2:1 image.

If your source is 3000x500 (a standard horizontal panorama)
```
      {
          full_width: 3000
          full_height: 3000/2 = 1500
          cropped_width: 3000,
          cropped_height: 500,
          cropped_x: 0,
          cropped_y: (1500-500)/2 = 500
      }
```
