### ISSUE TITLE
[Virtual Tour Plugin] Marker click on mobile doesn't change picture (5.8.0-alpha.1)

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#1329]
### Describe the bug

Following #1163 we did a bit more testing, and on mobile, markers are not working as expected:

- The default marker is not clickable at all (click doesn't change picture), demo @ https://files.pavie.info/clients/panoramax/2024-06-17_PSV_arrows.html
- A simpler SVG image (`<img src="triangle.svg />`) is hardly clickable (click only works on certain angle, image "hitbox" seem very smaller compared to the image itself), demo @ https://files.pavie.info/clients/panoramax/2024-06-17_PSV_arrows_svg.html

This seem to be mobile/touch-specific, as I don't run into this issue on desktop (Linux + Firefox 127 / Chromium 126)

### Photo Sphere Viewer version

5.8.0-alpha.1

### Plugins loaded

VirtualTourPlugin

### OS & browser

Android + Chrome 118 / Firefox 125

**Comment by mistic100** [comment]
I forgot that the main viewer "swallows" all touch events and thus the native emulated click event is missing. Switched to PSV click event instead.
