### ISSUE TITLE
I have a question about gyroscope and mobile touch device.

### ISSUE THREAD

**Issue by nemohoon** [mistic100/Photo-Sphere-Viewer#133]
Photo Sphere Viewer : 3.2.3
ThreeJS : 85
browser versions : iOS 10 safari
my code : https://codepen.io/nemohoon/pen/RgVweM

Hi.
I do not speak English very well.
Please acknowledge this point.

Once the document is loaded.
On devices supporting gyroscope, gyroscope is enabled by default.
When i touch and move the screen in this state.
In the state of moving the device.
I want to work like the state of 'gyroscope: true’.

While using the gyroscope, touch the screen and move it. When you release your finger from the screen, it becomes a gyroscope again.
I want to make the user experience smoother.

**Comment by mistic100** [comment]
Sorry but i really don't understand what you mean.

**Comment by Strae** [comment]
I think he was meaning  something like

> for devices with gyroscope, it is possible to disable the auto-rotation when the user touch the screen and then re-enable after [i guess with a timeout?]?

If it is so, yes it is possible but there is no options to do that, you need to edit the source code

**Comment by nemohoon** [comment]
@mistic100 

1. Page loading - gyroscope enabled.
2. touchmove event - gyroscope disabled & Keep up positon & Control Sphere
3. touchend event - Keep up positon & gyroscope enabled

I want to make this step.

**Comment by mistic100** [comment]
Ok. There is already a pull request for this here https://github.com/mistic100/Photo-Sphere-Viewer/pull/105
It is not mergeable right now.

And there is this issue https://github.com/mistic100/Photo-Sphere-Viewer/issues/100 that needs to be resolved too.
