### ISSUE TITLE
could you switch the current panorama effect to a 3D model effect? 

### ISSUE THREAD

**Issue by jiechengyang** [mistic100/Photo-Sphere-Viewer#1330]
### Describe the feature

Hello Sir, could you switch the current panorama effect to a 3D model effect? Please refer to the following URL: https://stackblitz.com/edit/five-vue-js-demo?file=src%2Fcomponents%2FToggleFiveModeButton.vue
<img width="1408" alt="image" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/33148475/1843334d-95f6-4317-8600-e3e71521e59a">
<img width="1374" alt="image" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/33148475/092197d5-beb2-46b4-9327-beb2d1c2b195">

**Comment by mistic100** [comment]
No, this is not the goal of this library
