### ISSUE TITLE
Issue with Transition Animation using setPanorama in Photo Sphere Viewer

### ISSUE THREAD

**Issue by luisjm1992** [mistic100/Photo-Sphere-Viewer#1332]
### Describe your problem

I'm experiencing an issue with the transition animation when changing the panoramic image using the setPanorama method in Photo Sphere Viewer. The problem is that the loading logo appears in the center, and then the image changes without the smooth transition I expected.

```
const viewer = new Viewer({
    container: 'viewer',
    loadingImg: baseUrl,
    defaultYaw: '100deg',
    plugins: [
        MarkersPlugin,
        [VirtualTourPlugin, {
            positionMode: 'gps',
            renderMode: '3d',
            startNodeId: nodes[0].id,
            preload: true,
            arrowPosition: 'bottom',
            dataMode: 'client',
            nodes: nodes
        }]
    ]
});

viewer.setPanorama(panoramaUrl, {
    transition: {
        duration: 1000,
        loader: true,
    },
    speed: '20rpm',
    position: { yaw: 0, pitch: 0 },
    caption: 'The new caption'
})
.then(() => console.log('Update complete!'))
.catch((error) => console.error('Error loading panorama:', error));
```
I've verified that the image URL is correct and configured the animation and speed options according to the documentation. However, the loading logo appears, and then the image changes abruptly without a smooth transition.

someone provide an example of how to achieve a smooth transition when changing panoramic images using setPanorama in Photo Sphere Viewer?

Thank!

### Photo Sphere Viewer version

5.7.4

### Plugins loaded

VirtualTourPlugin MarkersPlugin

**Comment by mistic100** [comment]
If you are using the virtual tour plugin you should not use setPanorama API, you should use virtualTour.setCurrentNode

**Comment by luisjm1992** [comment]
Thank you very much, I'm going to implement it.

**Comment by luisjm1992** [comment]
> If you are using the virtual tour plugin you should not use setPanorama API, you should use virtualTour.setCurrentNode

Thank you very much, I'm going to implement it.
