### ISSUE TITLE
ios15 cant work

### ISSUE THREAD

**Issue by hothotsavage** [mistic100/Photo-Sphere-Viewer#1334]
### Describe the bug

use ios15 can't view v5 and v4 demos in https://photo-sphere-viewer.js.org.
it work just only by switching version to v3.
my device is iphone12

### Photo Sphere Viewer version

5.8.0

### OS & browser

ios15 safari

**Comment by mistic100** [comment]
I have no iOS device, if you want to help me fix the issue, please add screenshots and browser logs.

**Comment by develth** [comment]
I stumped upon that.
Error is thrown:

Unhandled Promise Rejection: ReferenceError: Can't find variable: OffscreenCanvas

**Comment by develth** [comment]
15.11.0 is working - there was no OffscreenCanvas in use. Maybe add a compatibility mode for those devices?
iOS 15.8. is sadly still in use and last Update was in March 2025
