### ISSUE TITLE
MarkerPlugin Hover events no longer firing after update to 5.8.1

### ISSUE THREAD

**Issue by AndyBaird** [mistic100/Photo-Sphere-Viewer#1340]
### Describe your problem

I am testing the updates on 5.8.1 and noticed the `enter-marker` events stopped firing everywhere. I am utilizing the  VirtualTourPlugin as well. Are we still supposed to utilize that method in the markersPlugin when using the virtualTourPlugin?

### Photo Sphere Viewer version

5.8.1

### Plugins loaded

markersPlugin, galleryPlugin, gyroscopePlugin, virtualTourPlugin

### Additional context

This no longer works after moving to 5.8.1:

      markersPlugin.addEventListener(
        "enter-marker",
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        //@ts-ignore
        ({ marker }) => {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
          const link = getLinkFromInternalMarker(marker);
          if (link) {
            setHoveredLink(link);
          }
        },
      );

**Comment by mistic100** [comment]
What di you mean "stopped firing everywhere" ? can you give a concrete example of expected behaviour (setup and demo using version 5.7.4 on stackblitz or other)

**Comment by AndyBaird** [comment]
Diagnosing it further, the problem does not appear to be the event listener itself, but the markersPlugin. I found that when updating to 5.8.1 the markers object inside of the markersPlugin is null:

**5.8.1 markersPlugin object:**

<img width="833" alt="image" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/11802239/40873aab-c12f-45e9-93f4-0fec91d737dc">

**5.7.4 markersPlugin object:**

<img width="829" alt="image" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/11802239/fd2d6398-bdf5-4db9-aa73-d579fdb1ded9">

**Comment by mistic100** [comment]
Yes because the virtual tour plugin does not use markers anymore as stated in the 5.8.0 changelog.

You might use events of the virtual tour plugin instead https://photo-sphere-viewer.js.org/api/modules/virtualtourplugin.events

**Comment by AndyBaird** [comment]
Understood, shifting to the `enter-arrow` events will work. I thought those events were still only applicable to the arrows in 3d mode and not markers. Perhaps that part of the guide can be updated for clarity. 
Thanks!

<img width="663" alt="image" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/11802239/6f484c42-9c24-4011-8905-71487f8445eb">

**Comment by mistic100** [comment]
Updated the doc to remove the outdated statement
