### ISSUE TITLE
Panorama stuck at initial view

### ISSUE THREAD

**Issue by f3k-freek** [mistic100/Photo-Sphere-Viewer#1344]
### Describe the bug

I'm not able to "move" the panorama on both my own deployment and the demos on https://photo-sphere-viewer.js.org/demos/

Neither dragging nor markersPlugin.gotoMarker() seems to work.
I've tested this on multiple macbooks in different browsers (brave, firefox, safari).

The markers do detect hovering.

### Online demo URL

https://photo-sphere-viewer.js.org/demos/basic/0-config.html

### Photo Sphere Viewer version

5.7.0

### OS & browser

MacOS Brave

**Comment by webmazz** [comment]
I think it's the fault of the three.js version.

When I changed `"three": "https://cdn.jsdelivr.net/npm/three/build/three.module.js",` to  `"three": "https://cdn.jsdelivr.net/npm/three@0.165.0/build/three.module.js",` everything started working again.
