### ISSUE TITLE
method of converting several panoramic image view coordinates to the equirectangular image coordinates

### ISSUE THREAD

**Issue by neurosynapse** [mistic100/Photo-Sphere-Viewer#1345]
### Describe your problem

Hello,

Is there any method with which you can convert point coordinates clicked in panoramic image view to equirectangular image coordinates? It would be nice if you could help me with this.

Best regards,
Roberts

### Photo Sphere Viewer version

5.8.1

**Comment by Rai-Rai** [comment]
Hi, check the data helper: https://photo-sphere-viewer.js.org/api/classes/core.datahelper

- [sphericalCoordsToTextureCoords](https://photo-sphere-viewer.js.org/api/classes/core.datahelper#sphericalCoordsToTextureCoords)
- [sphericalCoordsToVector3](https://photo-sphere-viewer.js.org/api/classes/core.datahelper#sphericalCoordsToVector3)
- [sphericalCoordsToViewerCoords](https://photo-sphere-viewer.js.org/api/classes/core.datahelper#sphericalCoordsToViewerCoords)
- [textureCoordsToSphericalCoords](https://photo-sphere-viewer.js.org/api/classes/core.datahelper#textureCoordsToSphericalCoords)
- [vector3ToSphericalCoords](https://photo-sphere-viewer.js.org/api/classes/core.datahelper#vector3ToSphericalCoords)
- [vector3ToViewerCoords](https://photo-sphere-viewer.js.org/api/classes/core.datahelper#vector3ToViewerCoords)
- [viewerCoordsToSphericalCoords](https://photo-sphere-viewer.js.org/api/classes/core.datahelper#viewerCoordsToSphericalCoords)
- [viewerCoordsToVector3](https://photo-sphere-viewer.js.org/api/classes/core.datahelper#viewerCoordsToVector3)

call it via `viewer.dataHelper.viewerCoordsToVector3(<params>)`
