### ISSUE TITLE
What methods can be used in place of updateMarker now that the virtual tour plugin does not use markers?

### ISSUE THREAD

**Issue by AndyBaird** [mistic100/Photo-Sphere-Viewer#1348]
### Describe your problem

In our usage we have allowed users to move markers in a virtual tour with a few "move" buttons that would call the `markersPlugin.updateMarker` method and save the updated `linkOffset`. Now that the virtual tour plugin does not use markers, none of that functionality will work. 

I am not seeing an alternative method in the virtualTourPlugin [API documentation](https://photo-sphere-viewer.js.org/api/types/virtualtourplugin.virtualtourlink) that would allow for these marker/arrows to be moved in real-time anymore. Does a [new method](https://photo-sphere-viewer.js.org/api/classes/virtualtourplugin.virtualtourplugin) need to be added or is there a way to do this that I am not understanding?

### Photo Sphere Viewer version

5.8.1

**Comment by mistic100** [comment]
If you are building an UI to create a virtual tour I would suggest to only use the markers plugin during the configuration phase, save, the various coordinates, then switch to the virtual tour plugin in production.

However you should be able to update the links by calling `setNodes`, this requires to overwrite all the nodes, but it should not be a problem.

Manually updating the generated markers was not intended.
