### ISSUE TITLE
Omnitone Spatial Audio Integration

### ISSUE THREAD

**Issue by topherbuckley** [mistic100/Photo-Sphere-Viewer#135]
My current hurdle with this is likely on the side of the omnitone package, but I'm trying to find a workaround for the time being. The problem is that I can't get the spherical image and the audio "sphere" or ambisonics file to line up right. 

For example, if I have an image of the beach, I want the sounds of the ocean to come from the same direction as the where they are shown on the spherical image. 

I tried playing around with the default_long option, but this doesn't remap anything it seems, just sets the default camera view matrix which is the same for both PSV and omnitone in this case. So I need a way to hardcode rotate the spherical image or the ambisonics audio file. (I opened an [issue](https://github.com/GoogleChrome/omnitone/issues/58) in the omnitone repo about doing this via the ambisonics file, but its just as easily doable via rotating the spherical image). 

I'm guessing this has something to do with rotating the spherical mesh. Is this possible to do with PSV? Or do you know of an image editor that can do this manually before putting them on the server? I couldn't find anything immediately in the PSV API or on google regarding the image editor. 

If nothing immediate comes to mind, I'll keep pushing for this on the omnitone side as I think that should be the long term goal.

**Comment by mistic100** [comment]
You can do it with any image editor if you have an eauirectangular image : cut the left part, move the right to the left, and paste the part you cut on the right.

**Comment by topherbuckley** [comment]
Yep, that is what I'm doing at the moment, though I was hoping for something a bit more manageable like rotate(45). Otherwise its a lot of hand calculations for each image as to how much to cut from each side and quite slow for anything past this demo of a single image. No big deal for the demo, but I'll have to get something working more fluidly with omnitone for this to apply to any image/audio. 

Thanks for the tip though.

**Comment by mistic100** [comment]
I thought it was the other way around : simpler to visually identify where to cut than doing the Marty to find the angle.

Anyway it's a feature that make sense, I just don't know how to make it clear it is not the same thing as "default_long"

**Comment by topherbuckley** [comment]
You are probably right for this single image case, but I will eventually need a way to do this more quickly. I'm guessing there is some photo/video editor out there that can work with spherical images and ambisonics files, but maybe not. 

Eventually I'd like to identify a point on the image (maybe using something like your markers functionality?) and then adjust the ambisonics rotation matrix to make a sound come from that point. So for my ocean photo example:

- Load the PSV

- Center the view on the shore where the waves are hitting

- Press a button to assign a marker to the center of the view

- Grab the location of the marker via the camera matrix or your getPosition() method

- Add a file picker dialog somewhere within the cloud popup details for the marker which can select a mono audio file

- I'm working on a non-GUI solution for using the Ambix plugins to create the necessary ambisonic file from the mono audio file and assign the proper location based on the marker location grabbed from getPosition or the camera matrix.

- Use the necessary methods from the omnitone API to assign the audio file to the marker location.  

- Voila, you now hear the ocean coming from the ocean. 

I can do this all by hand as I am doing now, but if this could all be done programmatically, we could have a nice soundscape designer app on our hands.

**Comment by topherbuckley** [comment]
Found a very useful tool for "rotating" the spherical images to align everything and just wanted to leave it in this thread for future reference. 

In GIMP use Layer-->Transform-->Offset with the "wrap around" edge behavior.

**Comment by topherbuckley** [comment]
Still a couple of kinks to work out, but [here](http://omnyacoustics.com/vr_main.html) is the work in progress:

In short, it is a building acoustics simulator called Omny VR which provides auralizations for different noise isolation scenarios coupled with various common noise sources.

**Comment by topherbuckley** [comment]
Updated a few things, but one bug I've stumbled upon only pops up in Firefox (54.0) and not in Chrome (Version 59.0.3071.109).

If you open the link from my previous post in both Chrome and Firefox you will notice running in Firefox is quite slow, especially at changing between rooms. In terms of PSV this means, the onClick() method would run corresponding to the button I setup with the navbar initalization. Below is the code for one button, but they are all the same other than the indicies for the rooms:

```javascript
{
id: 'room1',
title: 'Switch to Room 1',
className: 'room1',
content: '<img style="position: absolute; width: 20px" class="psv-button-svg button" viewBox="0 0 100 100" src="./src/images/room_icon1.svg"><div id="roomPopover"></div></svg>',
onClick: function() {
    viewer.setPanorama(panoramas[0]);
    room = 0;
    audioChange(room,noise);
    }
},
```

In the dev tools -->network I noticed that in Firefox, that when I change rooms for the first time (for each new room) the panorama image reloads from the server rather than using the one that should be in the cache when I pre-load them all. In Chrome, when switching between panoramas it uses the images from the cache as expected. 

Here is my preload method where panoramas is just an array with all the image file names. preloadNoises is just another similar method but for the audio files:
```javascript
function preloadPanos(panoramas, pano_index) {
  if (panoramas && panoramas.length > pano_index) {
    var img = new Image ();
    img.src = panoramas[pano_index];
    // async loading
    // img.onload = function() {
    //     preloadPanos(panoramas, pano_index + 1);
    // }
    preloadPanos(panoramas, pano_index + 1);
  }
  else{
    preloadNoises(noises, pano_index, noise_index);
  }
}
```

From what I can see it is either simply a problem with Firefox, or some incompatibility with the code inside of PSV.setPanorama() with Firefox. 

The reason I suspect it is something in PSV is that Firefox does just fine with pulling the audio files from the cache...its only problem is with pulling the images from the cache (Though it pulls them just fine after they've been pulled from the server a 2nd time via button presses). 

If you think it is something that could be fixed within PSV, I'll start a new issue, otherwise I'll submit a bug report to Mozilla is you don't think there is anything on your end. 

Let me know if you need any further code, but I haven't minified anything, so you should be able to see it all from the dev console.
