### ISSUE TITLE
Take an screen shot

### ISSUE THREAD

**Issue by Mohammadf4f12** [mistic100/Photo-Sphere-Viewer#1353]
### Describe your problem

A

### Photo Sphere Viewer version

5.8.0

### Additional context

Hello, good time. How can I take a screenshot of the current display that is being shown?

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/demos/advanced/screenshot.html

**Comment by Mohammadf4f12** [comment]
Thank you very much 🙏
