### ISSUE TITLE
360 images not working (also the demos in https://photo-sphere-viewer.js.org/

### ISSUE THREAD

**Issue by Louri3000** [mistic100/Photo-Sphere-Viewer#1354]
### Describe the bug

Hello, I'm sorry if this type of question is not posted here, but this is my first time using the forum.

Since yesterday none of the 360 ​​images work in rotation and only allow me to zoom. Does the same happen to anyone else?

(I have the same problem using the demos, not just in my server)

Thanks and best regards!
Jose.

### Online demo URL

https://photo-sphere-viewer.js.org/demos/basic/0-config.html

### Photo Sphere Viewer version

5.8.1

### OS & browser

Windows / Chrome

**Comment by mistic100** [comment]
https://github.com/mistic100/Photo-Sphere-Viewer/issues/1344
