### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1358]
### Describe the bug

Importmap isn’t suppored by Firefox and Safari. So I can't open tour on iPhone.

I have Web Inspector, so there is a screen:
![photo_2024-07-07_10-23-17](https://github.com/mistic100/Photo-Sphere-Viewer/assets/20244089/dac25cd0-47c6-4556-8b6c-48376eaa8e16)

URL - https://vi-tour.ru/s/smwtecgb/

Same problem was described here:
https://discourse.threejs.org/t/bug-importmap-isnt-suppored-by-firefox-and-safari/41716
https://stackoverflow.com/questions/71814384/in-safari-and-only-if-i-open-devtools-i-get-typeerror-module-specifier-does

How can I change block "<script type="importmap">" for working in any browser?

### Photo Sphere Viewer version

5.8.2

### OS & browser

IOS, Safari

**Comment by mistic100** [comment]
Use a bundler (vite, rollup, webpack, etc) to bundle your app, including dependencies into standard JS files.

Or try to use https://github.com/guybedford/es-module-shims

These solutiosn are already discussed in the links you provided and there is nothing more I can do.
