### ISSUE TITLE
Use apng 

### ISSUE THREAD

**Issue by Mohammadf4f12** [mistic100/Photo-Sphere-Viewer#1359]
### Describe your problem

Is there a way to use APNG images in an imageLayer instead of image? I tried everything, but the animation stops. I used videoLayer and the WebM format, but this format isn't well-supported by most browsers.

### Photo Sphere Viewer version

5.8.0

**Comment by mistic100** [comment]
That would require too much work for very limited use case. Convert you animation to a video file.

WebM **IS** supported by all browsers https://caniuse.com/webm (as long as youuse VP8 or VP9 video codec)

**Comment by Mohammadf4f12** [comment]
I used videoLayer and WebM, but nothing was displayed on an iPhone 11! Can you think of another way (besides using chroma key and green screen)?

**Comment by mistic100** [comment]
Indeed iOS 11 does not support it. What is the problem with chromaKey ? I don't see other solution.
