### ISSUE TITLE
Default Viewing Angle and VirtualTourPlugin

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1360]
### Describe your problem

I use Photo Sphere Viewer and VirtualTourPlugin for my tours (by the way - thank you for the excellent solution). 

I can set the viewing angle only for the first panorama with
```
defaultYaw
defaultPitch
```

But I want to set first view for each panorama. I need to set defaultYaw for each node. 

Is it possible?

### Photo Sphere Viewer version

5.8.2

**Comment by mistic100** [comment]
By default the viewer will keep the current orientation after clicking the link., implying that every panorama must have the same orientation.  
If this is not the case your should set `panoData.poseHeading` on each node to correct the orientation.

If however you don't want each panorama to have the same orientation, use `transitionOptions` global configuration poseHeading has a function, it can returns `rotateTo` (click on "See details" for code example)

**Comment by Rusachok** [comment]
Thanks!

**Comment by mistic100** [comment]
Please close the issue if the question is answered.
