### ISSUE TITLE
MarkersPlugin 可以支持标注后拖动吗？

### ISSUE THREAD

**Issue by guoshao99** [mistic100/Photo-Sphere-Viewer#1362]
### Describe the feature

在全景图上标注后，我想进行使用标注的移动，目前是如何实现有什么解决方案？

**Comment by guoshao99** [comment]
API documentation not found  ，https://photo-sphere-viewer.js.org/plugins/markers.html#configuration  The API documentation in this plugin does not have any fragrance related second speed functionality，Can you guide me where the API is？

**Comment by html580** [comment]
可以使用jqueryui drag来操作dom结点。我们已经实现了。

**Comment by guoshao99** [comment]
jqueryui drag，鼠标和标记点不在一个位置您是怎么实现的？

**Comment by guoshao99** [comment]
> 可以使用jqueryui drag来操作dom结点。我们已经实现了。
在使用jq的过程中鼠标按下，松开了，但是鼠标的焦点还是在标记上，并且还会继续拖动标记，请问这个是如何处理的。？

**Comment by guoshao99** [comment]
> 可以使用jqueryui drag来操作dom结点。我们已经实现了。

666
