### ISSUE TITLE
MapPlugin in VirtualTourPlugin

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1365]
### Describe your problem

I want to use MapPlugin with VirtualTourPlugin.
I set position, but it is not work

```
              [VirtualTourPlugin, {
                  positionMode: 'manual',
                  renderMode: '2d',
                  map: {
                      imageUrl: '/media/{{ plan_image }}',
                      static: true,
                      position: 'top left',

                  },
              }],
```

How can I do static map with "top left" position? Please help.

### Online demo URL

https://vi-tour.ru/s/qyjtbuht/?addmap=1

### Photo Sphere Viewer version

5.8.2

**Comment by mistic100** [comment]
Only the map image is configured on virtual-tour plugin, other settings are on the map (virtual-tour does not care of the position)

```js
              [MapPlugin, {
                      static: true,
                      position: 'top left',
              }],
              [VirtualTourPlugin, {
                  positionMode: 'manual',
                  renderMode: '2d',
                  map: {
                      imageUrl: '/media/{{ plan_image }}',
                  },
              }],
```

**Comment by Rusachok** [comment]
It is great!
And how can I do the following:
1. After maximizing plan I want to do it big, with zoom 100. And after minimizing - revert zoom to 40%.
2. Can I set the plan to the center of widget? Now the center is - point of current panorama.

**Comment by Rusachok** [comment]
OK!

And one more question.
When gallery is opened, I maximize plan. And the button for hiding the plan appears under the gallery. It cannot be clicked.
It would be great if, with an open gallery, the plan would be expanded taking into account the available area of the screen.

**Comment by Rusachok** [comment]
https://github.com/mistic100/Photo-Sphere-Viewer/issues/1369

**Comment by mistic100** [comment]
#1372
