### ISSUE TITLE
Hello, author How to support dragging icons to change coordinate positions after using MarkersPlugin annotations

### ISSUE THREAD

**Issue by guoshao99** [mistic100/Photo-Sphere-Viewer#1366]
### Describe your problem

Hello, author
How to support dragging icons to change coordinate positions after using MarkersPlugin annotations

### Photo Sphere Viewer version

5.8.2

### Additional context

Hello, author
How to support dragging icons to change coordinate positions after using MarkersPlugin annotations

**Comment by mistic100** [comment]
This is not possible with this library. It is a library to **view** things, not to edit.

You can listen to "click" events on the viewer to move markers where the user clicked, but you cannot make drag-and-drop finctionnality.

**Comment by guoshao99** [comment]
As you said, how should we obtain the coordinates required for marking the final mouse landing point by moving it with the mouse? How should this be converted

**Comment by mistic100** [comment]
The viewer "click" event has all the data you need, including projectes yaw+pitch

https://photo-sphere-viewer.js.org/guide/events.html#click-data-dblclick-data  
https://photo-sphere-viewer.js.org/api/classes/core.events.clickevent

**Comment by html580** [comment]
Uploading 111.mp4…

**Comment by html580** [comment]
my project use jqueryui draggable  is ok
