### ISSUE TITLE
New events for MapPlugin

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1369]
### Describe the feature

https://vi-tour.ru/s/qyjtbuht/
Using MapPlugin.
After maximizing plan I want to do it big, with zoom 100. And after minimizing - revert zoom to 40%.

It would be great, if you add an event to listen for widget maximize/minimize and a method to change to zoom level

**Comment by mistic100** [comment]
Example usage

```js
map.addEventListener('view-changed', ({ view }) => {
                if (view === 'maximized') {
                    map.setZoom(100);
                } else if (view === 'normal') {
                    map.setZoom(40);
                }
            });
```
