### ISSUE TITLE
Flickering in Safari (Mac OS 10.12.5)

### ISSUE THREAD

**Issue by dogaoz** [mistic100/Photo-Sphere-Viewer#137]
I tested in my website and in photo sphere viewer homepage. When you click, hold and drag, and release your finger, it stutters and flickers like it cannot decide between 2 points and renders two points constantly until the animation stops. It only happens in Safari. It doesn't happen in Chrome, Opera.

**Comment by mistic100** [comment]
I cannot debug this, I don't have access to a Mac

**Comment by mateioprea** [comment]
@mistic100 I can debug it

**Comment by Tulbix** [comment]
move_inertia: false;

**Comment by mistic100** [comment]
Yes of course, but it doesn't solve the problem, only disable the feature.
