### ISSUE TITLE
Showing the Gallery on phones

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1370]
### Describe your problem

I think showing Gallery with GalleryPlugin have to be different for desktop and mobile. 

For example, I would like to:
1. for desktop - show the gallery at all times (at start and after transitions) and have a button to turn it off and on.
2. for mobile - don't show gallery, only button to show it. May be some buttons for next and prev panoramas should be for mobile.

Now I turned gallery on at start, but this is not necessary for mobile.

I can show some example from another viewer.

![Clipboard_07-10-2024_01](https://github.com/mistic100/Photo-Sphere-Viewer/assets/20244089/b5f87218-90b4-48b1-95cd-fe54e70ca767)
![photo_2024-07-10_12-21-42](https://github.com/mistic100/Photo-Sphere-Viewer/assets/20244089/31483685-b614-44c5-bc73-225520b65f44)

### Online demo URL

https://vi-tour.ru/s/qyjtbuht/

### Photo Sphere Viewer version

5.8.2

**Comment by mistic100** [comment]
You should detect yourself if you are on mobile (either by screensize or tools like modernizr.js) and change the `visibleOnLoad` setting accordingly.

This is not by default because there are many ways and many philosophies to detect mobile phones.

**Comment by Rusachok** [comment]
Ok, I can do it for visibleOnLoad.
And what about something like alwaysVisible - for visibility after transition?

**Comment by mistic100** [comment]
I don't understand.

**Comment by Rusachok** [comment]
When I click on the next panorama, the gallery is hidden. I want it to always be visible to the desktop. Is some settings for it?

**Comment by mistic100** [comment]
Please take some time to read the doc...

https://photo-sphere-viewer.js.org/plugins/gallery.html#hideonclick

**Comment by Rusachok** [comment]
Ok! Thank you very much, there is no more questions.
