### ISSUE TITLE
3d arrows and Gallery

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1374]
### Describe the bug

When I use Gallery and 3d arrows to the next point, I have a problem. I can't click on arrow - see screen below.

![image](https://github.com/user-attachments/assets/8ed2b148-d9ef-4bf5-bad2-28b18d179520)

### Online demo URL

https://vi-tour.ru/s/qyjtbuht/

### Photo Sphere Viewer version

5.8.2

### OS & browser

Win10, Chrome

**Comment by mistic100** [comment]
What solution do you propose ?

**Comment by Rusachok** [comment]
The same as for collapsing plan button.
https://github.com/mistic100/Photo-Sphere-Viewer/issues/1372

I think, all arrows have to be above the gallery.

**Comment by mistic100** [comment]
I don't agree. The fix for #1372 was not to make toe plan/map above the gallery but to close the gallery was the map/plan is maximized.

This is not applicable here. Having the arrows above the gallery would be very odd.

**Comment by Rusachok** [comment]
>The fix for https://github.com/mistic100/Photo-Sphere-Viewer/issues/1372 was not to make the plan/map above the gallery but to hide the gallery when the map/plan is maximized.

It's a pity. I hope it would be a smaller size for map, when gallery is visible. 

So, there is a problem with 3d-arrows. Current usage is not comfortable. I can only change arrows to 2d. :(

**Comment by mistic100** [comment]
Add this to your stylesheet

```scss
.psv-virtual-tour-arrows {
  margin-bottom: 100px;
}
```

This is an abritrary fix I cannot really make generic but it should solve it for you.

---

Unless you have a more generic proposal, which I don't have.

**Comment by Rusachok** [comment]
I think it is necessary to support the **interaction** between the Gallery and the VirtualTour.
In the function of showing gallery, you need to add an upward shift of the arrows to the height of the previews. 
In the function of hiding gallery, you need to add a shift of the arrows back to the standard place. 
If the gallery is not active, then nothing will move. If there are no arrows, but there is a gallery, then nothing will break either.
On the phone, the gallery takes up the entire screen, so that the arrows are not visible when displaying the gallery. Their shift won't break anything.

**Comment by mistic100** [comment]
demo of interactions between map, gallery and virtual-tour UI elements

[screen-capture.webm](https://github.com/user-attachments/assets/a0aeebbc-747e-4dca-9eaf-59aacaeed5a9)

**Comment by Rusachok** [comment]
You're great! Thanks!
When are you planning to release 5.8.3?
