### ISSUE TITLE
Gallery on the phone

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1376]
### Describe the feature

I have already written about the Gallery display on the phone (https://github.com/mistic100/Photo-Sphere-Viewer/issues/1370). As a result, depending on the phone or desktop, I set the parameters:

* for my phone
```
visibleOnLoad = false;
hideOnClick = true;
```
* for desktop
```
visibleOnLoad = true;
hideOnClick = false;
```
It works great.
Now I would like the phone to have two small arrows for transitions between panoramas. I saw such an example in another viewer.

![image](https://github.com/user-attachments/assets/3172a816-2bab-43f0-91fd-c1378e361f45)

I want to do something like this:

![image](https://github.com/user-attachments/assets/20964895-5a18-430a-a57a-5bc9bc1396b8)

I would turn on such arrows in phone mode.

And one more suggestion. The gallery button is small and invisible to a new user. It would be great to be able to customize this button, make it bigger, or add text to it.

**Comment by mistic100** [comment]
You could add custom buttons to the navbar https://photo-sphere-viewer.js.org/guide/navbar.html#custom-buttons

I am sorry I am not willing to change the behavior of the gallery.

---

You can also use custom buttons to replace the default gallery button if it does not suit you.

**Comment by Rusachok** [comment]
It is not about "changing behavior of the gallery". 
I would like to add a parameter for displaying arrows to the existing behavior. And follow the arrows to the neighboring panoramas. 
The gallery on the phone takes up the entire screen. You can't keep it on all the time. And the arrows would help.
If you consider it acceptable.

**Comment by mistic100** [comment]
So it would not be a gallery anymore. As I said you can add custom buttons the the navbar.

**Comment by mistic100** [comment]
Just to clarify : adding an option is simple, maintaining an option in the long term is not. I am alone on this project, I don't have time to test every scenario for every release, so I keep the number of options low, especially when an alternative exists.
