### ISSUE TITLE
three.Quaternion is not a constructor error

### ISSUE THREAD

**Issue by bakermanbrian** [mistic100/Photo-Sphere-Viewer#1377]
### Describe the bug

I am trying to get this library to work in my react application and ran into the error "three.Quaternion is not a constructor error"

It seems this was an old issue that someone had a resolution for, but the resolution now no longer applies to the repo:
https://github.com/mistic100/Photo-Sphere-Viewer/issues?q=three.Quaternion+is+not+a+constructor

Is there an obvious workaround here?

### Photo Sphere Viewer version

5.8.3

### OS & browser

Mac/Chrome

**Comment by mistic100** [comment]
I will not be of any help for this. But here are a few tips :
- put breakpoint to figure out was the `three` variable actually contains, obviously the bundler is doing something wrong
- check that the bundler uses the right file for dependencies, both three and photo-shere-viewer are published as dual ESM+CJS package with correct entries in the package.json but perhaps the bundler is picking the "main" field where it should pick the "module" field
