### ISSUE TITLE
Use a Marker as a Link in VirtualTour

### ISSUE THREAD

**Issue by bakermanbrian** [mistic100/Photo-Sphere-Viewer#1378]
### Describe the feature

I like markers and I like the virtual tour transition functionality. However, I would like to replace the virtual tour arrows with circular makers. Additionally, I want to define the pitch and yaw of the markers. The end goal is the picture attached. Is this possible today?

<img width="705" alt="Screenshot 2024-07-17 at 8 26 54 PM" src="https://github.com/user-attachments/assets/f1761d80-bf78-44d9-aaf1-01393e6910a5">

**Comment by mistic100** [comment]
It is not possible to use markers for the virtual tour links.

---

Alternatively, set `renderMode` to `2d` and provide a custom element to `arrowStyle`

```js
arrowStyle: (link) => {
   const el = document.createElement('div');
   .....
   return el;
},
```

As of defining the pitch and yaw this is exactly what the "Manual mode" is for https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#usage
