### ISSUE TITLE
The name of the panorama in Vitour

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1380]
### Describe the feature

When there are a lot of panoramas on a tour, their names are often long. Moreover, in Russian, words are longer than English ones. 
What is displayed in the preview is poorly readable.

Is it possible to write the name of the displayed panorama entirely in this place? You can do this by parameter.

![image](https://github.com/user-attachments/assets/cf201473-7dfa-4ef2-ae99-1931e78f1210)
![image](https://github.com/user-attachments/assets/3a541ffd-bb19-4405-8493-1374fd17d442)

**Comment by mistic100** [comment]
This is what the caption was intended for, here you hardcoded it with a single value but you could define the caption for each gallery item, and the navbar will update.

I will not provide and option accoding to your mockup, this is somethiong you can easily do yourself by adding an element above the viewer and update it by listening to gallery/viewer events.

**Comment by Rusachok** [comment]
OK!
