### ISSUE TITLE
Getting poseHeading from Viewer

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1381]
### Describe your problem

We can get the current values of the yaw and pitch parameters from the viewer.
How do we get the current value of poseHeading?
This is very important for us. Maybe it is possible to calculate it somehow?

### Photo Sphere Viewer version

5.8.3

**Comment by mistic100** [comment]
poseHeading is not a variable, it is a property of the panorama, you should know the value because it is provided by you.

Thevalue you are looking for is probably a simple subtraction between `yaw` and the configured poseHeading

**Comment by Rusachok** [comment]
Thanks!
