### ISSUE TITLE
Incorrect selection processing

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1382]
### Describe the bug

I have a tour with a lot of panoramas, I often had to move the gallery to the right and left. Sometimes it turned out that a part of the screen was highlighted and the viewer broke after that. 
I was able to clearly fix how to repeat it.
Select the title and, with the mouse key pressed, continue to pull up on the viewer. I.e., I hold down the key, select and press only in the middle of the viewer. 
After that, dragging the panorama does not work. When clicked, it starts dragging the panorama without holding down the mouse button. And when pressed, it does nothing.
You need to ignore the possibility of highlighting on the viewer.

I hope you can repeat it. The video does not reflect exactly how the viewer behaves when it breaks down.

https://github.com/user-attachments/assets/96acc0d8-f203-49ad-b6ce-39b2aea4da8d

### Online demo URL

https://vi-tour.ru/s/eyclgqhj/

### Photo Sphere Viewer version

5.8.2

### OS & browser

Win10, Chrome

**Comment by Rusachok** [comment]
We had a similar problem. It is necessary to prohibit the selection of text in the container:
```
user-select: none;
```

**Comment by mistic100** [comment]
This was actually a problem with the markers container, not the navbar not the gallery

**Comment by Rusachok** [comment]
Are you sure? There are no markers on this tour.

**Comment by mistic100** [comment]
That's irrelevant, the markers plugin is loaded and the container is here.
