### ISSUE TITLE
Interaction between the Info Panel and the Gallery

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1383]
### Describe the bug

I would like to have interaction between the Info Panel and the Gallery.
Similar to how it is done in
https://github.com/mistic100/Photo-Sphere-Viewer/issues/1374

My gallery is open when loading and does not close when navigating.
When I click on info, the panel on the right opens, the gallery is hidden. But when I close the panel, the gallery does not appear again. The user must search for where they have gone.

### Online demo URL

https://vi-tour.ru/s/eyclgqhj/

### Photo Sphere Viewer version

5.8.2

### OS & browser

Win10, Chrome

**Comment by mistic100** [comment]
use events and methods

```js
viewer.addEventListerner('hide-panel', () => gallery.show());
```

**Comment by Rusachok** [comment]
Thanks!
It works:
```
viewer.addEventListener('hide-panel', ({ panelId }) => { virtualTour.gallery.show(); });
```
