### ISSUE TITLE
Plan plugin maximized 

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1385]
### Describe the bug

Since 5.8.3 when plan plugin is maximized the compass remains in the foreground and therefore covers the buttons of plan plugin in the upper left corner.

### Online demo URL

https://www.tadini.it/temp/panorama_boval.html

### Photo Sphere Viewer version

5.8.3

### Plugins loaded

plan compass

### OS & browser

win 11 - chrome 126

**Comment by mistic100** [comment]
Is this a real usecase ? The map and plan have all the features of the compass, why would you use both ?

**Comment by haldo98** [comment]
it was the behaviour before 5.8.3.
Never mind .. I will use an event.
