### ISSUE TITLE
Bug with Virtual tour on IPhone

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1387]
### Describe the bug

I have some bug, but don't know what is it.
On the iPhone, when you click on the transition on the arrow, the reaction is very slow.
At first, it seems that nothing is happening. And belatedly, a spinner appears. Below is a video from different iPhones.
It is important to navigate through a panorama that has not loaded before, because the second time the same panorama is clicked normally.

https://github.com/user-attachments/assets/b8f9bad8-f651-4580-b213-40ed7dd1fb3e

https://github.com/user-attachments/assets/03831589-2236-4447-bde0-4d69bdad3307

### Online demo URL

https://vi-tour.ru/s/eyclgqhj/

### Photo Sphere Viewer version

5.8.2

### OS & browser

Ios

**Comment by mistic100** [comment]
I have no iPhone to test, and I cannot reproduce on my Android.

I suggest you do some remote debug with Safari to check for errors and/or profiling the app.

**Comment by Rusachok** [comment]
There is no error in the console during the transition. But there is such a thing. It is unlikely to be related to the bug.

![image](https://github.com/user-attachments/assets/5b4b4ea3-4794-44e3-a242-e4004469869c)

**Comment by mistic100** [comment]
This might be fixed with version 5.9.0, please confirm and close the issue if it is the case.

**Comment by Rusachok** [comment]
Yes, it seems that no such problem is noticed anymore!

**Comment by mistic100** [comment]
Thanks you for testing
