### ISSUE TITLE
EquirectangularTilesAdapter update5.8.3 Cannot switch as a whole

### ISSUE THREAD

**Issue by html580** [mistic100/Photo-Sphere-Viewer#1394]
### Describe your problem

EquirectangularTilesAdapter update5.8.3 Cannot switch as a whole。
my project user 5.5.0 is prefect。
const loader = new THREE.ImageLoader();

	return new Promise((resolve, reject) => loader.load(pano.base, resolve, undefined, reject))
		.then((image) => {
			const canvas = document.createElement('canvas');
			canvas.width = image.width;
			canvas.height = image.height;
			const ctx = canvas.getContext('2d');
			ctx.drawImage(image, 0, 0);
			ctx.fillStyle = 'rgba(255, 255, 255, 0.01)';
			ctx.fillRect(0, 0, canvas.width, canvas.height);
			return canvas.toDataURL('image/jpg');
		})
		.then((baseUrl) => {
			return psv.value
				.setPanorama(
					{
						...pano.config,
						baseUrl: baseUrl,
					},
					{
						zoom: data.defaultZoomLvl,
						defaultYaw: data.yaw,
						defaultPitch: data.pitch,
						position: { yaw: pano.position.yaw, pitch: pano.position.pitch },
						touchmoveTwoFingers: true,
						mousewheelCtrlKey: true,
					}
				)
				.then(
					function (data) {
						initSceneMarker();
						psv.value.plugins.autorotate.config.startFromClosest = false;
						if (!props.isEdit && !state.isautoinit) {
							psv.value.plugins.autorotate.stop();
							psv.value.plugins.autorotate.start();
							psv.value.plugins.autorotate.setOptions({
								autostartDelay: 2000,
								autostartOnIdle: true,
							});
						}
					},
					function (data) {
						debugger;
					}
				);
		})
		.then(() => {
			psv.value.navbar.setCaption(pano.title);
			psv.value.setOption('minFov', pano.minFov || 30);
		});

### Photo Sphere Viewer version

5.8.3

**Comment by html580** [comment]
examples: https://www.kuqixiu.com/index/view/id/24  is now use 5.5.0
other question:when i change other pano. it turns start point . how to config to fade to jump.

**Comment by mistic100** [comment]
I don't understand your questions. What "Cannot switch as a whole" means ?

If you provide an example, please use a version which has the problem.

**Comment by html580** [comment]
change other Pano wait to long time to show。but 5.5.0 show fast。

**Comment by Rusachok** [comment]
> change other Pano wait to long time to show。but 5.5.0 show fast。

Do you have the same problem?
https://github.com/mistic100/Photo-Sphere-Viewer/issues/1395#issuecomment-2254437339
