### ISSUE TITLE
Spinner for preloaded panoramas

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1395]
### Describe your problem

The viewer has excellent functionality - preload. 
Compared to moving to another distant point, it immediately feels like the panorama is preloaded. 
But the question arises - why display the spinner if the new panorama has already been loaded. Why not make a soft transition. 
If you don't understand what I mean, I can record a video. 

The expected behavior is a soft transition. Here is an example of a viewer in which the tour is loaded first, and then the transitions between panoramas are just instantaneous.
https://gnessinka.ru/3d/tour.html

One panorama is transformed into another without an additional spinner. I would like to do the same. Is it possible?

### Online demo URL

https://vi-tour.ru/s/eyclgqhj/

### Photo Sphere Viewer version

5.8.2

**Comment by mistic100** [comment]
Because even though the image file is preloaded, there is still work to do (transform the jpeg to a texture and transfert it to the GPU).  
Other viewers may work "better" because they don't have the same architecture.

You can hide the loader with `transitionOptions` https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#transitionoptions

**Comment by mistic100** [comment]
Also in the example you linked, it uses a tiling system, so the overhead to load a new texture is much lower. This is possible in PSV with the EquirectangularTilesAdapter.

**Comment by Rusachok** [comment]
I switched to using Tiles.
Can you tell me what the usage error is?
Now only the first image is loaded using the basic panorama and Tiles loading. 
During transitions, I first see the spinner for a very short time, then pause, and then immediately the panorama is displayed in good quality. 

For some reason, viewer doesn't want to show a small panorama with a blur first.

https://vi-tour.ru/s/aojyhech/

**Comment by mistic100** [comment]
I works perfectly here, all fives images are loaded with tiles

**Comment by Rusachok** [comment]
https://github.com/user-attachments/assets/01a1f985-3ab1-4434-bc36-f148bb5ca615

Please take a look at the video.
The first panorama is loaded with a blur and tiles. But when I switch to the second panorama, I see "Loading" in the bottom line, nothing happens. And then the panorama is immediately displayed in high quality.

**Comment by Rusachok** [comment]
And on the big tour (54 panoramas), working with tiles sometimes leads to the browser (Chrome) hanging after transitions.

https://vi-tour.ru/s/mdkygphe/

**Comment by Rusachok** [comment]
And there is no problem when tiles are disabled.

**Comment by mistic100** [comment]
I don't know what to do to help you as I don't have the problem myself. Your big tour works perfectly, everything loads fast with initial blurred + tiles.

**Comment by Rusachok** [comment]
Maybe you can repeat it if you have more data. 
Chrome browser, updated to the latest version, win 10. The problem is observed on two different computers. 

I made a parameter to show the tour with and without tiles.
Without: https://vi-tour.ru/s/mdkygphe/
With tiles: https://vi-tour.ru/s/mdkygphe/?usetiles=1

Without tiles works perfectly. 
The tiles option works strangely. After each transition, the spinner is displayed, disappears quickly, then there is an impressive delay. And only then a new panorama is loaded.
While waiting, I want to click a second time.

https://github.com/user-attachments/assets/1be17434-260a-40e7-9e00-ea99e851d862

**Comment by mistic100** [comment]
I have the same setup and no problem. Don't need to repeat your problem, I saw the video, I understand it, but there is nothing I can do from my side.

**Comment by html580** [comment]
yes。the same problem。But 5.5.0 is ok。

**Comment by mistic100** [comment]
I experienced serious performance issues on my work computer which does not have a dedicated GPU. Though the behaviour is not exactly the same, I think it is the issue you have.

If you still experience issues with the future version 5.8.4 please open a new issue.

**Comment by Rusachok** [comment]
Thank you very much. 
Tiles are now working as expected. 
Nevertheless, I want to ask. Here are two tours - with and without tiles.
https://vi-tour.ru/s/mdkygphe/
https://vi-tour.ru/s/mdkygphe/?usetiles=1

The loading time of the panorama is essentially the same. Without tiles, the spinner spins a little longer, and with tiles, time is spent on displaying the blured image.
But after loading, there is no turbidity without tiles, and with tiles when turning, there is still loading. 
I don't understand why there is no gain from tiles. I asked several users which of these tours is more comfortable - they say that without tiles.

It's just a remark, I don't know if anything can be done about it.

**Comment by mistic100** [comment]
We don't have the same notion of "essentially the same". Without tiles the loader is displayed for half a second, with tiles it is barelly visible, some times is not even displayed, you could even totally disable it (I indicated how on my first answer).
