### ISSUE TITLE
Link to a specific panorama in Tour

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1396]
### Describe your problem

Is it possible to do the link to a specific panorama in Virtualtour?

For example.
There is tour
https://gnessinka.ru/3d/tour.html

And this is link to specific panorama
https://gnessinka.ru/3d/tour.html#node61

### Photo Sphere Viewer version

5.8.3

**Comment by Rusachok** [comment]
It is clear that I can process the parameter on the server and specify the first point when loading the viewer. But how do I get such a link?
I would like the user to be able to right-click on the preview in the gallery and select "Copy link to this panorama". 
Or something similar. 
That is, it is convenient for the user to get a link to a particular panorama. So that you can share it. 
So I want to show a friend exactly the baggage claim room on the tour, now I can only give a link to the tour and say that you need to click on such and such a photo in the gallery.

**Comment by mistic100** [comment]
This is some integration not related to PSV.

The Virtual Tour Plugin has a "setCurrentNode" method, up to you to call it when needed on query parameter change.

----

Has for right click on gallery items, you will have to do it yourself.

You can get the DOM element with `document.querySelector('.psv-gallery')` and setup your own "contextmenu" event handler (with [delegation](https://www.freecodecamp.org/news/event-delegation-javascript/) you have only one listener to add).
