### ISSUE TITLE
BUG: Tiles, Virtual Tour and poseHeading

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1397]
### Describe the bug

When I use Virtual Tour and Tales -- poseHeading doesn't work. 
So all transitions are inadequate.

The first video of the tour without tiles - all transitions are excellent, the look goes where it should. 
https://vi-tour.ru/s/mdkygphe/

The second video of the tiles tour - everything is not as it should be. I go to the baggage claim room, I should see the baggage belt, and the panorama is turned in the other direction.
https://vi-tour.ru/s/mdkygphe/?usetiles=1

Without tiles, works fine:
https://github.com/user-attachments/assets/cfcd0951-7a6d-4472-8f5f-cf5d1749ffb1

With tiles - it doesn't work well:
https://github.com/user-attachments/assets/251bb992-37c1-4eb2-a813-44e704ab1d60

### Photo Sphere Viewer version

5.8.2

### OS & browser

Chrome, Win10

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/guide/config.html#panodata

> Only the default [equirectangular](https://photo-sphere-viewer.js.org/guide/adapters/equirectangular.html) adapter and low-resolution panorama of [equirectangular-tiles](https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html) supports panoData, for other adapters you can only use [sphereCorrection](https://photo-sphere-viewer.js.org/guide/config.html#spherecorrection) if the tilt/roll/pan needs to be corrected.

**Comment by Rusachok** [comment]
If 
`panoData: { poseHeading: 180, },`
means the same 
`sphereCorrection: {pan: 180},`

You recommended using postHeading to align the direction of the panoramas (https://github.com/mistic100/Photo-Sphere-Viewer/issues/1360#issuecomment-2213413368). 
So, is there a more universal option for this sphereCorrection?

**Comment by mistic100** [comment]
I recommended using poseHeading when you was using the standard adapter.

poseHeading is applied on the texture (the pixels are shifted), and is usually read from XMP data.  
sphereCorrection was added later to fix cases where the XMP where false and for adapters which cannot support modifying the textures.

note: sphereCorrection is in radians, not in degrees

**Comment by Rusachok** [comment]
If I use different adapters, is it better to switch to `sphereCorrection` everywhere at once?
Did I understand correctly that sphereCorrection is a universal? It will solve the problem with shifting panoramas. 
I understand about radians, thank you.

One more question. You helped me figure out how to get postHeading from the current panorama position to fix it (https://github.com/mistic100/Photo-Sphere-Viewer/issues/1381#issuecomment-2239542897). 

How do I get `sphereCorrection`  in this case?

**Comment by mistic100** [comment]
Exactly the same.

Change `panoData: { poseHeading: 45 }` to `sphereCorrection: { pan: 45/180*Math.PI }`

**Comment by Rusachok** [comment]
Thanks!
