### ISSUE TITLE
New events

### ISSUE THREAD

**Issue by Rusachok** [mistic100/Photo-Sphere-Viewer#1402]
### Describe the feature

Hello!

I understand that PSV is a viewer, not an editor. But we want to implement marker dragging.
We found the following events in the documentation:
https://photo-sphere-viewer.js.org/guide/events.html#click-data-dblclick-data

We are missing the mouse movement event and the mouse key release event.

Is it possible to add them?

**Comment by mistic100** [comment]
```js
viewer.container.addEventListener('mousemove', (e) => {
  if (doingSomeEdit) {
    // do something
    e.stopPropagation(); // prevents PSV to move
  }
});
```

viewer coordinates are obtainable with :

```js
const boundingRect = viewer.container.getBoundingClientRect();

const viewerX = e.clientX - boundingRect.left;
const viewerY = e.clientY - boundingRect.top;

const { yaw, pitch } = viewer.dataHelper.viewerCoordsToSphericalCoords({ x: viewerX, y: viewerY });
```

do you really need something more ?

**Comment by Rusachok** [comment]
I need unclick.
User do click, move and unclick (key release).

Is it possible?

**Comment by mistic100** [comment]
the same as above but with 'mouseup'

perhapsp you should read some javascript tutorials :-)

**Comment by Rai-Rai** [comment]
Hi @Rusachok 
check this Issue (#229 : https://github.com/mistic100/Photo-Sphere-Viewer/issues/229)
It basically shows exactly what you want to do
