### ISSUE TITLE
Displaying less-than-360-degree panoramas

### ISSUE THREAD

**Issue by lscorcia** [mistic100/Photo-Sphere-Viewer#1403]
### Describe the bug

Hi, I am using Immich as photo storage solution and discovered that it uses PhotoSphereViewer internally to display panoramas.

Most of my panos cover less than 360 degrees horizontally (usually 180-270). When I display those in Google Photos, its viewer is able to display the picture respecting the original viewing angle (the missing part is rendered black). When I open one of those pictures in PSV instead it stretches the picture on the whole 360 deg field.

See for following the attached picture. You can load it in the online playground.
![IMG_20240625_075653181](https://github.com/user-attachments/assets/d0e5374c-ae95-40d3-a206-c1de50fede48)

Is this a missing metadata issue that somehow Google figures out, or is it a missing feature in PSV? (intentional or not)

### Photo Sphere Viewer version

5.9.0

### OS & browser

Win/Firefox

**Comment by lscorcia** [comment]
Sorry, just found out that PSV does actually support partial panos (found the demo called cropped panorama). I'll try to figure out why Immich doesn't show them right, possibly they strip necessary metadata.

**Comment by mistic100** [comment]
I just checked with Exif tool with `exiftool -xmp -b file.jpg > data.xmp` and the XMP data seems complete. So Immich is doing something wrong, which is surprising because last time I checked, people had problems with initial pose metadata not being loaded (this is fixed now), but partial panoramas worked fine. Perhaps they broke something in a recent release.

**Comment by mistic100** [comment]
(BTW there is something wrong with the Playground, it wrongly overloads cropping data)

**Comment by mistic100** [comment]
https://github.com/immich-app/immich/issues/10917
