### ISSUE TITLE
5.9.0 EquirectangularTilesAdapter display black

### ISSUE THREAD

**Issue by html580** [mistic100/Photo-Sphere-Viewer#1404]
### Describe the bug

5.9.0 EquirectangularTilesAdapter display black。

### Photo Sphere Viewer version

5.9.0

### Plugins loaded

https://www.kuqixiu.com/index/view/id/24

### OS & browser

Chrome

### Additional context

![image](https://github.com/user-attachments/assets/55f1db11-a9cf-46c7-a3e0-b6be8dff58b1)
![image](https://github.com/user-attachments/assets/eb145094-d196-45d1-8aa9-846862181495)
5.9.0 EquirectangularTilesAdapter display black。my old version5.5.0 is ok, baseUrl is config.

**Comment by mistic100** [comment]
Please provide a reduced example without all the bloat of you application, I am unable to debug your 10 javascript files.

But by inspecting the viewer I see that you do **NOT** provide baseUrl.

`document.querySelector('#diygwvr').photoSphereViewer.config.panorama.baseUrl` yields `undefined`

**Comment by mistic100** [comment]
![Capture d’écran du 2024-08-06 09-25-49](https://github.com/user-attachments/assets/f783985c-1339-41a5-8677-140e1d78bc3d)

At first you provide `${s}/base.jpg` and then you override it with a undefined value, so obvisouly it does not work.

**Comment by html580** [comment]
thanks 。my config error 。
other question when other pic not in view,when it animate in view,it has a little time to load tie。how to cofing faster load tie.

**Comment by mistic100** [comment]
This is not possible, only tiles in the view are loaded.

**Comment by html580** [comment]
> This is not possible, only tiles in the view are loaded.

krpano lib load tie fast.it show prefect. so i think you can improve better. 
https://krpano.com/releases/1.21/viewer/krpano.html?xml=examples/demotour-apartment/tour.xml

**Comment by mistic100** [comment]
Then use krpano... I can only do what I have time and the will to do. This is an open project maintained by a single person.

**Comment by html580** [comment]
> Then use krpano... I can only do what I have time and the will to do. This is an open project maintained by a single person.

thank you very much. We have been continuously using version 3.0 until now.Looking forward to your improvement.
