### ISSUE TITLE
Max zoom error

### ISSUE THREAD

**Issue by Nikolay206** [mistic100/Photo-Sphere-Viewer#141]
1) Open example http://photo-sphere-viewer.js.org/
2) Set max zoom 
3) click zoom in many times 

In result - I can not zoom out.

**Comment by mistic100** [comment]
I do not reproduce, what is your browser ? do you have an error in the console ?

**Comment by Nikolay206** [comment]
try click and move
https://drive.google.com/file/d/0BwAZk0drSwCXY3BxRjNlLTFrMjg/view  
browser chrome x64   59.0.3071.115 version




>Вторник, 25 июля 2017, 18:19 +03:00 от Damien Sorel <notifications@github.com>:
>
>I do not reproduce, what is your browser ? do you have an error in the console ?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением
Николай Коротков

**Comment by Nikolay206** [comment]
not fixed.
I reproduce this bug in your site:
https://drive.google.com/file/d/12iPorbMKtiz-cxGYB2CnBIdh8NY-11Y1/view

**Comment by Nikolay206** [comment]
look at 1m 5 s

**Comment by mistic100** [comment]
Fixed on dev doesn't mean published.
Look the milestone 3.2.5 is not ready.

**Comment by Nikolay206** [comment]
Very good. Thank you very much. I will wait this version
