### ISSUE TITLE
Plan plugin layer selector non-readable on windows OS

### ISSUE THREAD

**Issue by juanbrk** [mistic100/Photo-Sphere-Viewer#1410]
### Describe the bug

The plan plugin layer selector is showing options with white text on white background for Windows users, so it’s impossible to read unless hovering on the option.
![Screenshot 2024-08-16 at 12 14 57 PM](https://github.com/user-attachments/assets/cd484669-bff1-48fb-a02b-cafcfdb8c889)

### Photo Sphere Viewer version

5.8.3

### Plugins loaded

@photo-sphere-viewer/compass-plugin@5.8.3 ├── @photo-sphere-viewer/core@5.8.3 ├── @photo-sphere-viewer/equirectangular-tiles-adapter@5.8.3 ├── @photo-sphere-viewer/gallery-plugin@5.8.3 ├── @photo-sphere-viewer/markers-plugin@5.8.3  ├── @photo-sphere-viewer/visible-range-plugin@5.8.3

### OS & browser

Windows 11, Chrome

### Additional context

Tested on Windows 11 and customers complained about It happening on both Win10 and Win11 OS. On MacOs It works properly.

**Comment by mistic100** [comment]
On Windows 10, Chrome I don't have this result. The layers selectors itself is a native `<select>` without any styling. Did you check that it is not your own stylesheet which cascades into the viewer ?

**Comment by mistic100** [comment]
Any news ? I could add overrides to make sure the display is correct in every contexts, but I would need an extract of your stylesheet tot test.

**Comment by mistic100** [comment]
Sorry I don't have to lear yet another framework, if you can give the final real stylesheet without tailwind tools it would more useful.

**Comment by mistic100** [comment]
There are not form color definition here, so it cannot be the cause of the issue.

**Comment by mistic100** [comment]
Otherwise please provide a full demo on CodeSandbox, that's exactly for this kind of issues a demo is asked in the issue template.
