### ISSUE TITLE
Draw polygons and lines with hotspot markers

### ISSUE THREAD

**Issue by guoshao99** [mistic100/Photo-Sphere-Viewer#1414]
### Describe your problem

How are the polygons and polylines drawn using the marked points in the demo (with the help of third-party tools or within the Photo Sphere Viewer framework) and displayed on the panoramic image
New polygon marker和New polyline marker two
https://photo-sphere-viewer.js.org/playground.html

### Photo Sphere Viewer version

5.8.2

### Plugins loaded

Marker

**Comment by guoshao99** [comment]
https://geojson.readthedocs.io/en/latest/#

**Comment by guoshao99** [comment]
Is this tool used to draw polygons and polylines for creating panoramic images?
https://geojson.readthedocs.io/en/latest/#polygon

https://photo-sphere-viewer.js.org/playground.html

**Comment by Rai-Rai** [comment]
No external tool is used/needed to draw the polygon.
Showing polygon/polyline is a feature of PSV.

The Playground just reacts to the click on the panorama and adds the click coordinates to the poly* which is currently created.
See here: https://github.com/mistic100/Photo-Sphere-Viewer/blob/052c9458ffa1989efd824ecbc48ac8c71d0abd4e/docs/.vuepress/components/Playground.vue#L1176

**Comment by guoshao99** [comment]
If I have already implemented polygon marking, but I need to modify the marking of this polygon, can it support dragging polygon points for modification? I still need to implement it myself

**Comment by mistic100** [comment]
There is not possibility to do that in Photo Sphere Viewer. It is _possible_ because polygon markers are simple SVG elements but you will have to do it all by yourself, I will not provide help.

**Comment by guoshao99** [comment]
Although it is a simple SVG tag, can you provide more attributes? I think there should be many people using this as well
