### ISSUE TITLE
Using updateMarker in MarkerPlugin to modify the tooltip without re rendering the text of the data

### ISSUE THREAD

**Issue by guoshao99** [mistic100/Photo-Sphere-Viewer#1416]
### Describe the bug

Using updateMarker in MarkerPlugin to modify the tooltip without re rendering the text of the data
```js
export function setMarker(currMarker: Object) {
  const mk = {
    id: currMarker.elementId,
    position: {
      yaw: currMarker.yaw,
      pitch: currMarker.pitch,
    },
    // image: currMarker.markerWayValue,
    size: { width: currMarker.width, height: currMarker.height },
    anchor: 'center center',
    tooltip: {
      content: currMarker.title,
      position: 'top center',
    },
    // style: {
    //   backgroundColor: 'rgba(1, 0, 0, 0.5)',
    //   border: '1px solid rgb(250 100 0)'
    // },
    scale: {
      //最小缩放比例，最大缩放比例
      zoom: [currMarker.scale / 100, 1],
    },
    visible: currMarker.visible,
    data: {
      generated: true,
      mk: currMarker,
    },
  };

  if (currMarker.markerWay == MarkerWay.SYSTEM_ICON || currMarker.markerWay == MarkerWay.IMAGE) {
    mk.image = currMarker.markerWayValue;
  } else if (currMarker.markerWay == MarkerWay.TEXT) {
    mk.html = '<div>' + currMarker.markerWayValue + '</div>';
  } else if (currMarker.markerWay == MarkerWay.VIDEO) {
    mk.videoLayer = currMarker.markerWayValue || 'xgy.mp4';
  }


  return mk;
}

let markersPlugin = ref(null);
let mk = setMarker(currMarker);

markersPluginObj.value.updateMarker(mk);

```

either or

`markersPluginObj.value.updateMarker({id: 'aaa', 
tooltip: { 
  content: 'This is marker',
  position: 'bottom left',
}});`

### Photo Sphere Viewer version

5.9.0

### Plugins loaded

Marker

### OS & browser

google

**Comment by mistic100** [comment]
This is the last time I ask you this : please explain your problem better with complete sentences. What I am supposed to understand with just your code ?

I don't have time to loose to decipher.

**Comment by guoshao99** [comment]
The tooltip content for modifying tags by clicking on them is not updated in real-time. It can be viewed by printing on console. log (markers Plugin. value), but the value has already been modified
`markersPlugin.value.addEventListener('select-marker', ({ marker }) => {
      console.log(marker.id)
      markersPlugin.value.updateMarker({
        id: marker.id,
        tooltip: {
          content: new Date().getTime(),
          position: 'top center',
        },
      });
      //tooltip It has been modified
      console.log(markersPlugin.value)
    });`

**Comment by Rai-Rai** [comment]
I've implemented this usecase as well and there are absolutely no problems with this, works as expected.

**Comment by mistic100** [comment]
I indeed reproduce the problem, if the tooltip is curently renderer, it does not update immediately.
