### ISSUE TITLE
navigation dosent work in new documentation, refresh required

### ISSUE THREAD

**Issue by mostafa-kheibary** [mistic100/Photo-Sphere-Viewer#1417]
### Describe the bug

With the new documentation (its realy nice btw), the navigation for all pages are broken and it dosen't render the page when user navigate using hyperlinks
just the url is changed, and its need a refresh to navigation take place

### Online demo URL

https://photo-sphere-viewer.js.org/

### Photo Sphere Viewer version

5.9.0

### OS & browser

mac OS, Chrome 128 arm

**Comment by mistic100** [comment]
I don't have any issue accessing any part of the doc (Chrome and Firefox)

I this broken too ? https://vitepress.dev/

**Comment by mistic100** [comment]
I honnestly don't know what's going on. I will have to make a repro case and submit it to vitepress team.

**Comment by mostafa-kheibary** [comment]
Please check out this issue. 

I couldn't find the solution but I think it's helpful.

https://github.com/vuejs/vitepress/discussions/1812

**Comment by mistic100** [comment]
The problem is fixed
