### ISSUE TITLE
PlanPlugin implementation | CompassPlugin version update causes polyline projections to not be visible on compass.

### ISSUE THREAD

**Issue by juanbrk** [mistic100/Photo-Sphere-Viewer#1419]
### Describe the bug

<img width="1234" alt="image" src="https://github.com/user-attachments/assets/fee3612f-446f-43a4-96e1-575fe23654b4">

After implementing `PlanPlugin` on the viewer, polyline projections have disappeared from the `CompassPlugin`, leaving only Hotspot projections visible. This issue arose after updating the @photo-sphere-viewer/compass-plugin version from 5.7.0 to 5.8.3, suggesting that the problem may be related either to the implementation of the `PlanPlugin` or the `CompassPlugin` version update. No changes on how the markers are created or displayed had been made since. 

I traveled back in commit history to find out when the bug was introduced and It was indeed introduced after the initial `PlanPlugin` implementation. This is the snapshot of the changes to the `package.json` on that initial implementation:

<img width="1368" alt="image" src="https://github.com/user-attachments/assets/db3e70c3-2c9b-43cd-aad8-b18c430f1fbc">

I have since  upgraded all  `photo-sphere-viewer` modules to `5.9.0` and the bug was still there.  

to implementing

### Photo Sphere Viewer version

5.8.3

### Plugins loaded

@photo-sphere-viewer/compass-plugin@5.8.3 ├── @photo-sphere-viewer/core@5.8.3 ├── @photo-sphere-viewer/equirectangular-tiles-adapter@5.8.3 ├── @photo-sphere-viewer/gallery-plugin@5.8.3 ├── @photo-sphere-viewer/markers-plugin@5.8.3 ├── @photo-sphere-viewer/visible-range-plugin@5.8.3

### OS & browser

macOS Sonoma Version 14.0  Chrome

### Additional context

There are three types of projections on my project:
- Line
- Polygon
- Point

Point projections are implemented as `PlanPlugin` hotspots by using the `planPlugin.setOptions({hotspots})` method. Polyline projections are implemented by adding them directly to `leaflet` by using the following lines of code (Simplified):

```
const planPlugin = viewer.getPlugin<PlanPlugin>(PlanPlugin);
const leaflet = planPlugin.getLeaflet();
polygons.addTo(leaflet);
```

## Markers config
This is what my markers config looks like:

### Points

```
{
    "id": "3374165d-4246-4276-97fb-4674502772c4",
    "html": "\n      <div class=\"relative\">\n ...\n    ",
    "anchor": "bottom center",
    "className": "text-5xl font-bold",
    "style": {
        "color": "#4decf2",
        "opacity": "1"
    },
    "position": {
        "textureX": 6738,
        "textureY": 6381
    },
    "data": {
        "compass": "#4decf2",
        "type": "POINT",
        "isWaypoint": false,
        "assetId": "98f93af6-4359-492f-9161-ac0babd962b5",
        "isTemporary": false
    },
    "listContent": "POINT: 293822.06, 5062123.5, 21.42"
}
```

### Polylines

```
{
    "id": "a9542b18-bb51-4bc1-9c16-b55e1aa1dee2",
    "svgStyle": {
        "stroke": "#4df28c",
        "strokeLinecap": "round",
        "strokeLinejoin": "round",
        "strokeWidth": "4px",
        "strokeOpacity": "1"
    },
    "polylinePixels": [
        [
            20446,
            6631
        ],
        [
            21395,
            6916
        ]
    ],
    "data": {
        "compass": "#4df28c",
        "type": "LINE",
        "isWaypoint": false,
        "isTemporary": false,
    },
listContent: "LINE: (2 points), 8.72m"
}
```

**Comment by mistic100** [comment]
This has nothing to do with the plan plugin. It is broke here too https://photo-sphere-viewer.js.org/plugins/compass.html
