### ISSUE TITLE
Image incompatible

### ISSUE THREAD

**Issue by carstengrimm** [mistic100/Photo-Sphere-Viewer#142]
I have been creating several images with hugin or other panorama / 360° image applications to use them with this viewer, while my first shot was working fine. i tried and repeated every but can't seem to make it work with any other image file i have created. 

i searched around the web to find image dimension restrictions and while it seems the answer having 2:1 seemed most common, when cropping an image to that aspect ratio, there was no success either. 

I could load pretty much a few other sample images from the web which worked fine in this viewer, so i pretty much sum up that something in my workflow is not right to make it compatible.

is there any pixel/size/ratio best practices to make that work with PSV ?

**Comment by mistic100** [comment]
2:1 that's it, it's the ratio of an equirectangular projection.

I can't help you if you don't provide the image having problem and if you don't explain what is the problem. Is the viewer blank ? Is the image deformed ? etc

**Comment by carstengrimm** [comment]
the viewer will stay black, 
i am actually only changing files to see if it works...

many sample from the web worked, which were not 2:1 but obviously they were distorted...

https://drive.google.com/drive/folders/0B0R6G-JoX5MAN1YyNUxPQ2xkXzg?usp=sharing

here are some example which did leave a black screen.

**Comment by mistic100** [comment]
The 17248x4541 file is too big, you need to downsize it.

But it's not the reason the smaller file does not work. I re-compressed it (without changing the size) with XnConvert and it worked.
The only difference I can see between before and after the compression is a "PPP = 72 x 72" metadata in the original file (seen with XnView).

I cannot tell you why it is not working and it's not something I can fix anyway (the problem must be in the image loader of THREE.js).

I suggest you down size and re-compress your panoramas and you are all good.

**Comment by mistic100** [comment]
Sorry I made a mistake, I also deleted the XMP tag while compressing the image.

I think the real problem is here : you have weird character in the data block (first and last lines), try to clean them leaving only the <rdf:Description xmlns:GPano> block
