### ISSUE TITLE
Using markers to render links in VirtualTours

### ISSUE THREAD

**Issue by IAMOTZ** [mistic100/Photo-Sphere-Viewer#1420]
### Describe your problem

Hi 👋 

I'm trying to set up a virtual tour where the node links in the tour are rendered as markers or in a way that I can customize some of the standard properties that a marker offers e.g rotation, scale, opacity e.t.c

I saw that in v4, there was a [markerStyle](https://photo-sphere-viewer-4.netlify.app/plugins/plugin-virtual-tour.html#markerstyle-markers-mode-only) option that allowed for this, but I've been unable to find a similar option in v5 so far. The links are rendered in '2d', so [arrowStyle](https://photo-sphere-viewer.js.org/plugins/virtual-tour.html#arrowstyle-3d-mode-only) doesn't help either. Is there any way to achieve this kind of link customization v5? 

Thanks.

### Online demo URL

https://codesandbox.io/p/sandbox/k3rwcz

### Photo Sphere Viewer version

5.9.0

### Plugins loaded

VirtualTourPlugin, Markers, AutorotatePlugin, GalleryPlugin

**Comment by mistic100** [comment]
There is an error in the doc, `arrowStyle` is usable in both 2d and 3d, so you can use a custom element and entirely customize the display.

It is not possible to uses markers.

**Comment by IAMOTZ** [comment]
Thanks for the swift response! 

I'll try the `arrowStyle`. 

I can also open a PR to fix that part of the docs.

**Comment by IAMOTZ** [comment]
I was able to use `arrowStyle` to render custom images/icons in 2d mode for my virtual tour 🎉 

I opened PR here to fix the docs about `arrowStyle` applicable in both 2d & 3d mode: https://github.com/mistic100/Photo-Sphere-Viewer/pull/1421

Will close this issue now.
