### ISSUE TITLE
Download with markers

### ISSUE THREAD

**Issue by JStuve** [mistic100/Photo-Sphere-Viewer#1422]
### Describe the feature

Hello! Any discussion on supporting the ability to download images along with the Markers plugin?

 I have a great use case for needing to export images with markers and showing sphere photos on another application.

**Comment by mistic100** [comment]
This is not possible has markers are not part of the canvas. You can use other tools like https://www.npmjs.com/package/html-to-image (you will propably have to call inside the render loop like the download example for it to have access to the canvas data).
