### ISSUE TITLE
360° 预览全景图片 0°位置的直线会加载成波浪线

### ISSUE THREAD

**Issue by liuhq0826** [mistic100/Photo-Sphere-Viewer#1425]
### Describe your problem

我测试了v4版本和v5版本都会有这种问题，用桌面端的软件就不会产生这种问题。
同一张图片实际效果：
![实际效果](https://github.com/user-attachments/assets/e4bc1454-4111-4616-bec8-9ea6dbb558d5)

用photo-sphere-viewer效果：
![viewer效果](https://github.com/user-attachments/assets/5d9be7ef-41c4-4bc0-a53a-68a7f9a572e2)

我使用的都是默认参数，未进行自定义设置，是需要进行怎么样的设置吗？
请指导，谢谢！

源文件：
https://pan.baidu.com/s/18rF43627x_Qxs7OMudMoXw?pwd=bq27
[https://pan.baidu.com/s/18rF43627x_Qxs7OMudMoXw?pwd=bq27](下载文件)

### Photo Sphere Viewer version

other

**Comment by mistic100** [comment]
I don't speak chineese.

read https://github.com/mistic100/Photo-Sphere-Viewer/issues/699

**Comment by liuhq0826** [comment]
> I don't speak chineese.
> 
> read #699

Thanks, I Know.
