### ISSUE TITLE
PanoData CroppedHeight Support in Equirectangular Video

### ISSUE THREAD

**Issue by alexhelms** [mistic100/Photo-Sphere-Viewer#1426]
### Describe the feature

I have equirectangular videos that are 360 degrees by 180 degrees from an allsky camera -- a single fisheye lens looking at the sky. For a single frame, I am using the following:

```
await viewer.setPanorama(url, {
    panoData: {
        fullWidth: width,
        fullHeight: height,
        croppedWidth: width,
        croppedHeight: height / 2
    }
});
```

But when I try this using the `EquirectangularVideoAdapter` it doesn't work. 

```
videoViewer.setPanorama({ source: url }, {
    panoData: {
        fullWidth: width,
        fullHeight: height,
        croppedWidth: width,
        croppedHeight: height / 2
    }
});
```

I've tracked it down to the code below:

https://github.com/mistic100/Photo-Sphere-Viewer/blob/5bb2e4e504470b970492cece111136ff338b010a/packages/equirectangular-video-adapter/src/EquirectangularVideoAdapter.ts#L71

It seems it is just using the html video element's dimensions and not my values from `panoData`.

Is it possible to use my values or is this a limitation of video playback?

Thanks!

### Alternatives you've considered

I can use ffmpeg to pad the video with a large black bar doubling the height of the video. This compresses well so it doesnt add much if any size to the video files.

**Comment by mistic100** [comment]
I don't think it is possible, the panoData are applied by resizing the panorama in an canvas, I don't think this can be done at 30/60 fps

It would be much better if you completed it yourself with black (shouldn't increase the file too much as it compress very well).

**Comment by mistic100** [comment]
Ideally the panoData would be applied sollelly with altering the UV mapping of the sphere mesh, this is totally possible but alot of headache.

**Comment by mistic100** [comment]
Ok I just realized I can use the phiStart, phiLength, thetaStart and thetaLength parameters of the SphereGeometry to generate a partial sphere, and be able to display partial panoramas without having the generate the full size texture.

This would provide a interesting performance improvement and also allow to use partial videos.

@PanierAvide I guess this change could interest you for your usage

**Comment by mistic100** [comment]
You may want to test version 5.11.0-beta.1

There is an example here https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/examples/misc-equirectangular-video-cropped.html#L36
