### ISSUE TITLE
Photo Sphere Viewer in modal pop-up

### ISSUE THREAD

**Issue by shobhitvaish** [mistic100/Photo-Sphere-Viewer#144]
I am trying to use Photo Sphere Viewer in modal pop-up and everything works fine excepts I am not able to move image horizontally with mouse. Is that an known issue or I am missing some configuration?

I am using code from here: https://codepen.io/bramus/pen/yeWJwN . It is just loaded in modal

**Comment by shobhitvaish** [comment]
It works now. I was calling javascript at wrong time.

**Comment by runtim** [comment]
@shobhitvaish do you have an example of the modal? I'm interested in this.
Thanks!
