### ISSUE TITLE
Listen to mouse move event to track Its position on the viewer

### ISSUE THREAD

**Issue by juanbrk** [mistic100/Photo-Sphere-Viewer#1442]
### Describe the feature

A `mousemove` event could be introduced to provide access to the current mouse coordinates in the panorama image, enabling developers to implement features such as a temporary trace when drawing markers by being able to access the cursor's current position. 

### Additional context

Currently, the library doesn't support a `mousemove` event listener for tracking cursor movements on the viewer. This limitation makes it impossible to dynamically display a trace between the last measured point and the current mouse position while drawing polyline markers.

**Comment by mistic100** [comment]
You can just add your ownlistener to the container and use this https://github.com/mistic100/Photo-Sphere-Viewer/issues/1439
