### ISSUE TITLE
Implementing Image Editing Features 

### ISSUE THREAD

**Issue by enrique138** [mistic100/Photo-Sphere-Viewer#1444]
### Describe your problem

Hi @mistic100, I am trying to add some editing features to my Photo Sphere Viewer canvas image, such as drawing on the image, adding custom shapes, resizing, and dragging and dropping elements by selecting and moving them with the mouse. Additionally, I want to blur specific areas of the image. After editing, I want to save the changes so that they are visible the next time I load the image.
 
I haven't found a direct way to achieve this, but I am attempting to use Fabric.js. My approach involves opening the image in a Fabric canvas, where I handle tasks like drawing, adding shapes, resizing, and blurring. I then attempt to add these modifications to the 360-degree view by calculating and converting the coordinates. However, I'm still facing challenges. Through my research, I've found that Three.js might allow for editing 3D images, but I haven’t been able to get it to work.
 
I want to integrate these features into my 360-degree Photo Sphere Viewer. Is there anyone who can help me achieve direct image editing (drawing, blurring, adding custom shapes, resizing, and drag-and-drop functionality)? Thanks!
 
What do you think of this? 
 

### Photo Sphere Viewer version

5.10.1

**Comment by mistic100** [comment]
That a lot a features... I am sorry but I won't be able to help you. I am not even sure what you want is applicable a 3d environment.

PSV is and will always be a viewer, nothing more.

Good luck.
