### ISSUE TITLE
getMarker -ERROR

### ISSUE THREAD

**Issue by mnaib** [mistic100/Photo-Sphere-Viewer#1446]
### Describe the feature

everytime getMarker method return ERROR
 getMarker(markerId: string | MarkerConfig): Marker {
        const id = typeof markerId === 'object' ? markerId.id : markerId;
        if (!this.markers[id]) {
            throw new PSVError(`cannot find marker "${id}"`);
        }
        return this.markers[id];
    }
is it possible to replace the error with a null value?

**Comment by mistic100** [comment]
No, if you know you can call "getMarker" with an invalid id, use a try/catch block.
