### ISSUE TITLE
A few small problems

### ISSUE THREAD

**Issue by vincnetdu** [mistic100/Photo-Sphere-Viewer#145]
1.If you reload in the size-updated event, you need to manually clear div, otherwise multiple copies will be generated.

2.The cubemap.htm example cannot be tested. Can you put the JS file you use in your package? What I can find is not suitable for this example.

3.Gyroscope successfully added, but how do you make a virtual-reality?

The case of using JeremyHeleine/Photo-Sphere-Viewer:
Https://www.ykipa.com/www/vr.html
The case of using mistic100/Photo-Sphere-Viewer:
Https://www.ykipa.com/www/vr2.html

**Comment by mistic100** [comment]
1. What means "reload" ? provide an example

2. Why ? What problem do you encounter ? I have absolutely no problem testing it

3. #122

**Comment by vincnetdu** [comment]
Cubemap. HTM example can you pack an email and give it to me? Email 593106@qq.com, thank you!

**Comment by mistic100** [comment]
No I cannot.

The example folder contains everything you need. Didn't you forghet to run "bower install" in the root ?

**Comment by vincnetdu** [comment]
2.The cubemap.htm example cannot be tested. Can you put the JS file you use in your package? What I can find is not suitable for this example.

error msg:
Uncaught TypeError: a.MultiMaterial is not a constructor
    at e._createCubemap (photo-sphere-viewer.min.js:7)
    at e._createScene (photo-sphere-viewer.min.js:7)
    at e._setTexture (photo-sphere-viewer.min.js:7)
    at photo-sphere-viewer.min.js:7
    at D.min.js:2
    at i (D.min.js:2)
    at D.min.js:2
    at MessagePort.t.port1.onmessage (D.min.js:2)

e._createCubemap | @ | photo-sphere-viewer.min.js:7
-- | -- | --
  | e._createScene | @ | photo-sphere-viewer.min.js:7
  | e._setTexture | @ | photo-sphere-viewer.min.js:7
  | (anonymous) | @ | photo-sphere-viewer.min.js:7
  | (anonymous) | @ | D.min.js:2
  | i | @ | D.min.js:2
  | (anonymous) | @ | D.min.js:2
  | t.port1.onmessage | @ | D.min.js:2

**Comment by mistic100** [comment]
Ok I will make it clear : what I say "I have no problem using it" I means that there is nothing more than the example folder. I am not stupid enough to make an example which require additional JS files I do not provide.

Now you pasted the actual error, I am able to help.
MultiMaterial was removed in r85 https://github.com/mrdoob/three.js/issues/10931 (that's the problem of  unfinished APIs).
I will update my code accordingly. If you need it immediately you can use Three.js versions prior to r85 (r84 is not affected).

**Comment by vincnetdu** [comment]
Merci de votre aide, R84 version est normal.
