### ISSUE TITLE
Ignore keyboard shortcuts if "Alt" key is pressed

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#1451]
### Describe the bug

Original use case : be able to go forward/backward in browser history, using standard "Alt + LeftArrow" or "Alt + RightArrow" keyboard shortcut.

If I have a Viewer with `keyboard: always` option enabled, Left and Right Arrows are used for moving around the view. Pressing Alt key at the same time should avoid the camera move, and let browser do its thing. As now, viewer still moves around and browser doesn't do anything.

[A special behaviour already exist for the Ctrl key](https://github.com/mistic100/Photo-Sphere-Viewer/blob/b211023040236b444e10537758b1c84c7a0e61c4/packages/core/src/services/EventsHandler.ts#L88), so I'm wondering if similar thing could be done for Alt key. If pressed, no basic key press would have effect, and keypress event goes up to browser.

### Photo Sphere Viewer version

5.10.1

### Plugins loaded

None

### OS & browser

Linux, Firefox (but I guess it happens everywhere)

### Additional context

[Issue originating from Panoramax Web Viewer](https://gitlab.com/panoramax/clients/web-viewer/-/issues/161), where we wanted to be able to go forward/backward in history to go to previous shown image. I tried to work around PSV to not call PSV roll function if Alt is pressed. But at some point the keyboard event is intercepted and native browser forward/backward is never called.

Parts of code which almost work :sweat_smile: 

```js
		const rollNoAlt = (action, opts) => (e => {
			console.log("roll", e);
			if(!this._altPressed) {
				console.log("no alt");
				this.psv.dynamics.position.roll(opts);
				this.psv.eventsHandler.keyHandler.down(action);
			}
		});
		try {
			this.psv = new Photo(this, this.psvContainer, {
				transitionDuration: this._options.transition,
				shouldGoFast: this._psvShouldGoFast.bind(this),
				keyboard: "always",
				keyboardActions: {
					...PSDefaults.keyboardActions,
					"8": rollNoAlt("ROTATE_UP", { pitch: false }),
					"2": rollNoAlt("ROTATE_DOWN", { pitch: true }),
					"6": rollNoAlt("ROTATE_RIGHT", { yaw: false }),
					"4": rollNoAlt("ROTATE_LEFT", { yaw: true }),
					"ArrowUp": rollNoAlt("ROTATE_UP", { pitch: false }),
					"ArrowDown": rollNoAlt("ROTATE_DOWN", { pitch: true }),
					"ArrowRight": rollNoAlt("ROTATE_RIGHT", { yaw: false }),
					"ArrowLeft": rollNoAlt("ROTATE_LEFT", { yaw: true }),
...
```

As it also happens on a classic, basic PSV viewer (if keyboard=always), I guess it makes sense to make this Alt behaviour handled mainstream.

**Comment by mistic100** [comment]
Going further, I think the default actions should be totally ignored if any modifier key is pressed, as in its current state `keyboardActions` keys cannot specify a mofifier.

Additionally I would add the original event to the custom callback parameters.

```ts
'ArrowUp': 'ROTATE_UP', // will move the view only and only if ArrowUp alone is pressed

'ArrowUp': (viewer, evt) => // will be called in ArrowUp is pressed with or without modifier, but the modifiers are accessible in the "evt"
```

**Comment by PanierAvide** [comment]
That was fast, thanks for your efficiency as always :grin:
