### ISSUE TITLE
VirtualTourPlugin real-time update

### ISSUE THREAD

**Issue by Zambiorix** [mistic100/Photo-Sphere-Viewer#1460]
### Describe your problem

Is there a way to update a node / link for the VirtualTourPlugin in real-time without setting all nodes with setNodes?
I'm developing a tour editor for a custom project and I need a way to change the arrow location (and other options) in real time.

Thanks for your help

Cheers
Gerd

### Photo Sphere Viewer version

5.11.0

### Plugins loaded

VirtualTourPlugin

**Comment by mistic100** [comment]
Use the server side mode, even if your `setNode` method does not make an actual HTTP request and call `setCurrentNode(xxx, { forceUpdate: true })`

**Comment by Zambiorix** [comment]
I implemented server side mode where `getMode` fetches the correct node from a map. That works fine.
But updating the link position and then calling `setCurrentNode` with `forceUpdate: true` does not work.

```
function test () {

    const node = tour.getCurrentNode()

    console.log(`--> test : ${node.id}`)

    tour.setCurrentNode(node.id, { forceUpdate: true }).then(() => {}).catch(() => {})
}
```

```
            plugins: [[VirtualTourPlugin, {

                dataMode: 'server',

                getNode: (nodeId) => new Promise((resolve, reject) => {

                    console.log(`--> getNode : ${nodeId}`)

                    if (nodes.available) {

                        switch (nodeId) {

                        case nodes.source.id:

                            resolve(nodes.source)

                            break

                        case nodes.target.id:

                            resolve(nodes.target)

                            break

                        default:

                            reject()
                        }

                    } else {

                        reject()
                    }
                }),
```

`test` is called on a button click, but subsequently `getNode` is not called.
Clicking on the arrow in the viewer does change the node and `getNode` is called as expected.
It seems like `forceUpdate` is not working .. not sure what is wrong, any idea?

Thanks!

**Comment by mistic100** [comment]
It does seem to work https://codesandbox.io/p/sandbox/dark-wood-28xg7x (here a random value between -0.5 and 0.5 is added to the "yaw" of each link of the current node)

**Comment by Zambiorix** [comment]
My mistake, I mentioned I had 5.11.0 installed ... it was 5.10.1 (where it didn't work).
As soon as I moved to 5.11, all is functioning as intended.

Thank you for your help.

**Comment by Zambiorix** [comment]
Although, it technically works, it does not solve my problem. I am working on a Tour editor where I can change the position of an arrow with sliders in real time. The `setCurrentNode` reloads the entire node and that is too much overhead when only the position of the arrow is changed. Not sure how I'm going to solve that

**Comment by mistic100** [comment]
Did you consider using the Markers Plugin instead when it "dev mode" ? This would allow to update the positions without reload.

**Comment by Zambiorix** [comment]
I was thinking about it just now :-) .. The arrow in a tourviewer is a marker? I was about to check your code if I needed something custom to render the arrow/marker in 3d.

The way I develop my editor now is to have a dialog to edit a link between 2 panoramas where I show a tourviewer with just 2 nodes (source & target). I can go back and forth between the 2 and ajust various setting (with sliders and what not).

So I can replace the tourviewer with a regular panorama viewer and mimic tourviewer behavior? And use a marker for the arrow? Do I need specific rendering code to make it look exactely like the tourviewer? Or can I use markers our of the box?

**Comment by mistic100** [comment]
Virtual Tour arrows are not markers. Unfortunately I think you will never be able to match the rendering behaviour ouf tour arrows with markers. You can approach it with `elementLayer` markers but it will not be one-to-one.

**Comment by mistic100** [comment]
Please tests this branch https://github.com/mistic100/Photo-Sphere-Viewer/tree/virtual-tour-update ([dev instructions](https://photo-sphere-viewer.js.org/guide/development.html) here)

There is a new "updateNode" which allows to update all properties of a node (client mode only).

```js
virtualTour.updateNode({
  id: '...',
  links: newLinks
});
```

I didn't tested all cases yet.

**Comment by Zambiorix** [comment]
Not sure how to install a plugin in my project from a specific branch ...
I have been searching on internet on how to do that, but no luck so far.
I'm using yarn. 

Any pointers?

**Comment by mistic100** [comment]
Use yarn link

**Comment by Zambiorix** [comment]
Works like a charm!

Thanks :-)

**Comment by Zambiorix** [comment]
Small bug:
If the tooltip is visible and the link/arrow position is updated, the tooltip does not move with it and never disappears. Hovering over the arrow show a new tooltip .. and this goes on with every move and hover.
Maybe a `updateNode` should first hide a visible tooltip?

**Comment by Zambiorix** [comment]
I should add that I have the following setup:

To edit a link, I try to keep it in the centre of the viewer when the user looks around. This is done by listening to the viewer's `position-updated` event and updating that position to the link and calling `updateNode`.

The arrow now stays perfectly in the centre, but many tooltips are generated when the mouse pointer hovers the link arrow. They are never destroyed.

As an additional feature, it would be greate to have an updateable `tooltipsDisabled` option on tour and node level and a `tooltipDisabled` on link level. And/or a global `tooltipsDisabled` option on viewer level.

**Comment by mistic100** [comment]
added a global `showLinkTooltip`, also if `getLinkTooltip` returns null for a particular link, it will not be displayed
