### ISSUE TITLE
[VirtualTourPlugin] strange arrow behavior when setting custom image and className

### ISSUE THREAD

**Issue by Zambiorix** [mistic100/Photo-Sphere-Viewer#1463]
### Describe the bug

I want to change the default link arrow in VirtualTourPlugin and add a custom animation class.

The image shows correctly but when I set the animation class, the arrow immediately moves to the top left corner of the viewer and stays there. The animation (in my case persistent rotation) works fine.

I'm not sure if this is a bug, or if I need to adjust my class...

```
arrowStyle: {
    image: linkSvg,
    className: 'my-arrow',
    size: {
        width: SIZE_DEFAULT,
        height: SIZE_DEFAULT,
    },
},
```

```
@keyframes rotate {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

.my-arrow {
    animation: rotate 10s infinite linear;
}
```

### Photo Sphere Viewer version

5.11.0

### Plugins loaded

VirtualTourPlugin

### OS & browser

macOS + Firefox

**Comment by Zambiorix** [comment]
This is in 2d mode

**Comment by mistic100** [comment]
You cannot override the "transform" property of the arrow itself, it used by the ThreeJS CSSRenderer.

You can however still the inner elements as you wish.

**Comment by Zambiorix** [comment]
By using `element` instead of `image`? I'll try that...

Thanks

**Comment by Zambiorix** [comment]
Yup, that works
Thanks!

**Comment by AndyBaird** [comment]
I have a similar problem where I am trying to apply transformations but cannot because ThreeJS uses them. I found a work around by applying transformations to the child element (SVG). I was hoping the library could be updated to do this, meaning instead of applying transformations as inline styles to the button, it would just apply transformations to the child element.
