### ISSUE TITLE
Issue with Photo Quality on Mobile Devices

### ISSUE THREAD

**Issue by Alex1120001** [mistic100/Photo-Sphere-Viewer#1470]
### Describe the bug

I'm experiencing a problem with the quality of photos when using the Photo Sphere Viewer library on mobile devices. While the images appear sharp and clear on desktop, they become blurry when zooming in on mobile devices.

### Online demo URL

https://671badc8a548b247d0ac333c--glowing-hotteok-063747.netlify.app/

### Photo Sphere Viewer version

5.11.0

### OS & browser

mobile device (safari, chrome)

### Additional context

The first screenshot was taken from a computer in developer mode on an iPhone 14. The second one was taken from an Android phone.

<img width="336" alt="Screen Shot 2024-10-25 at 19 37 08" src="https://github.com/user-attachments/assets/002a1339-b791-4fcb-877a-0b22f901d82c">

![photo_2024-10-25_19-36-53](https://github.com/user-attachments/assets/8aad2ec9-902c-4109-8ca9-09f1fc3aaa29)

**Comment by mistic100** [comment]
This has been answered multiple times : mobile browsers can only use textyres up to 4096px so the image is downscaled.

You can use this https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html

**Comment by Alex1120001** [comment]
will this fix the quality issue on mobile devices?
