### ISSUE TITLE
[VirtualTourPlugin] updateNode function throws typeError 'gps is undefined'

### ISSUE THREAD

**Issue by Hafdoune** [mistic100/Photo-Sphere-Viewer#1471]
### Describe the bug

virtualTourPlugin.updateNode({
        id: '1',
        panorama: baseUrl + 'tour/key-biscayne-7.jpg',
        thumbnail: baseUrl + 'tour/key-biscayne-7-thumb.jpg',
        name: 'Seven',
        caption: `[7] ${caption}`,
        links: [{ nodeId: '6' }],
        gps: [-80.15707, 25.6665, 3],
        sphereCorrection: { pan: '110deg', pitch: -3 },
    });
![image](https://github.com/user-attachments/assets/7ed1d4ff-1296-44b3-9176-b7a81824081e)

### Photo Sphere Viewer version

5.11.1

### OS & browser

Firefox

**Comment by mistic100** [comment]
Ok this happens because the "gps" value of the linked node is not correctly copied from node `6`.

In the mean time you can redeclare it :

```js
...
links: [{ nodeId: '6', gps: [lat, long] }],
...
```
