### ISSUE TITLE
在部分低版本浏览器下，使用Photo-Sphere-Viewer@4版本播放360度全景图片，图库中有六张图片，加载很慢等待时间长，而且还有报错。

### ISSUE THREAD

**Issue by 15132801861** [mistic100/Photo-Sphere-Viewer#1474]
### Describe the bug

在部分低版本浏览器下，使用Photo-Sphere-Viewer@4版本播放360度全景图片，图库中有六张图片，加载很慢等待时间长，而且还有报错。
![微信截图_20241028141551](https://github.com/user-attachments/assets/a7678321-4182-41d1-96dd-3fc25182483f)

<img width="529" alt="Snipaste_2024-10-28_14-13-06" src="https://github.com/user-attachments/assets/6ab5a6aa-b934-49f0-80a5-7b564eb56c05">

### Photo Sphere Viewer version

other

### OS & browser

低版本谷歌浏览器，或者是低版本统信浏览器（政府使用的低版本浏览器）

**Comment by mistic100** [comment]
Please speak english.

**Comment by 15132801861** [comment]
这个错您知道是啥意思吗？

**Comment by 15132801861** [comment]
On Google 122 and above versions, loading six images is too slow, but this error will not occur
Is there any way to optimize the loading speed of images and avoid errors? I hope you can give me some advice on whether 5.11.0 will have this problem
