### ISSUE TITLE
In some lower version browsers, use Photo-Sphere-Viewer@4 The version plays 360 degree panoramic images, but there are six images in the gallery. The loading is slow and the waiting time is long, and there are also errors.

### ISSUE THREAD

**Issue by 15132801861** [mistic100/Photo-Sphere-Viewer#1475]
### Describe the bug

<img width="529" alt="Snipaste_2024-10-28_14-13-06" src="https://github.com/user-attachments/assets/81c7bb77-dd8a-44b1-b9e0-59af07f602c2">
<img width="366" alt="Snipaste_2024-10-28_14-21-14" src="https://github.com/user-attachments/assets/4544cfbd-ef14-4e5d-be47-f08368662c7e">

### Photo Sphere Viewer version

other

### OS & browser

Low version Google Chrome, or low version Tongxin Browser (a low version browser used by the government)

### Additional context

In some lower version browsers, use Photo-Sphere-Viewer@4 The version plays 360 degree panoramic images, but there are six images in the gallery. The loading is slow and the waiting time is long, and there are also errors.

On Google 122 and above versions, loading six images is too slow, but this error will not occur
Is there any way to optimize the loading speed of images and avoid errors? I hope you can give me some advice on whether 5.11.0 will have this problem

**Comment by 15132801861** [comment]
please help me,thank you !!!

**Comment by mistic100** [comment]
- PSV 4 is not supported anymore
- only recents browsers versions are supported, and especially **NOT** the variety of chineese browsers
- if you have performance issues the only solution is to downscale your images

good luck, I cannot help you more

**Comment by 15132801861** [comment]
What does PSV 4 mean

**Comment by mistic100** [comment]
Photo-Sphere-Viewer@4

**Comment by 15132801861** [comment]
Photo-Sphere-Viewer@5.11.1 Does it support lower version browsers
