### ISSUE TITLE
how can i cover tripod cap in panorama

### ISSUE THREAD

**Issue by HungFpoly** [mistic100/Photo-Sphere-Viewer#1476]
### Describe your problem

![image_2024_10_28T02_58_41_304Z](https://github.com/user-attachments/assets/310d7c6c-19cf-402c-8a61-e3658f6e26ae)
I want to cover it like this

### Photo Sphere Viewer version

5.11.1

**Comment by mistic100** [comment]
Edit you image with a photo editing tool, this is not the goal of a viewer to alter the image.
