### ISSUE TITLE
Is there a method that is triggered when the user clicks the side panel, such as clicking the fullscreen button?

### ISSUE THREAD

**Issue by KKJava1** [mistic100/Photo-Sphere-Viewer#1479]
### Describe your problem

I need a callback method that is triggered after clicking the fullscreen button, or a callback method when clicking the side panel.

### Photo Sphere Viewer version

5.11.1

### Additional context

Is there a method that is triggered when the user clicks the side panel, such as clicking the fullscreen button?

**Comment by mistic100** [comment]
There are no specific events but you can subscribe yourself.

```js
document.querySelector('.psv-panel').addEventListener('click', () => {
 ....
});

document.querySelector('.psv-fullscreen-button').addEventListener('click', () => {
 ....
});
```
