### ISSUE TITLE
Gallery plugin default message when no items available

### ISSUE THREAD

**Issue by juanbrk** [mistic100/Photo-Sphere-Viewer#1481]
### Describe the feature

Given that GalleryPlugin Adds a gallery on the bottom of the viewer to navigate between multiple panoramas. It would be nice to provide a message to the user when there are no panoramas available to choose, avoiding displaying an empty gallery that can confuse Him.

**Comment by mistic100** [comment]
I detected this "problem" when implementing integration tests.

In the next version both the gallery and the button are hidden if the config is empty.

https://github.com/mistic100/Photo-Sphere-Viewer/blob/377d616da89e1239044cdf742218ff5d67aa86d8/cypress/e2e/plugins/gallery.cy.ts#L154-L160
