### ISSUE TITLE
The issue is with loading tiles.

### ISSUE THREAD

**Issue by Mohammadf4f12** [mistic100/Photo-Sphere-Viewer#1482]
### Describe the bug

Sometimes, in the panorama, images from another panorama are displayed!

### Photo Sphere Viewer version

5.8.3

### OS & browser

All mobile browsers

### Additional context

![IMG_۲۰۲۴۱۱۱۱_۱۲۵۶۱۸](https://github.com/user-attachments/assets/6af055df-be5c-4165-827e-bbb3f8f68a8c)

**Comment by mistic100** [comment]
Cannot help without a proper demo.

**Comment by Mohammadf4f12** [comment]
Hi,
Hope you're having a great day.

I’ve created the demo and sent you the link.
I’ve also attached a video to show you the issue.

As you can see, the tiles occasionally encounter problems.
I’ve checked everything, and the issue is not related to the internet connection as the images download without any problems. The issue is with the library.
(In image 5, for example, the images didn’t display correctly, but after switching between image 4 and image 5 once, the issue was resolved.)

At the end of the video, to ensure the problem isn’t network-related and that the images are indeed downloaded, I opened the undownloaded images to check if they could fix the broken tile. As you noticed, none of those images corresponded to the broken tile.

As a final note, I’d like to mention that this issue occurs much more frequently on mobile devices.
I’ve tested it on both Android and iOS, and the problem persists on both platforms.



Demo: 
https://codepen.io/Y7uby7km/pen/QWePVOq?editors=0010

Video:
https://drive.google.com/file/d/16AfSq_F4lc5QGYpcK2fdkTf2NnZPabfm/view?usp=drivesdk

**Comment by mistic100** [comment]
Allright, I can only reproduce it 10% of the time when quickly and erraticaly moving the camera just after changing the current panorama. In a normal operation : clicking an item in the gallery, wait 1-2 seconds for the image to load, then moving the camera, it never happens.

So I don't think I will take time to debug this. If it was reproducible 100% of the time why not, but here it seems to be a very rare edge case only found by QA testers :-)

**Comment by mistic100** [comment]
Also did you try to update the lib ? There was a lot of performance related changes in version 5.11

**Comment by Mohammadf4f12** [comment]
I have used the latest version of the library in the demo.  Also, this problem occurs much more in mobile.  When using the virtual tour, the user usually moves between images very quickly with markers.  As a result, the library creates many logs for the virtual tour


Video:

https://drive.google.com/file/d/16C6N3FUPj5FXFpn5zt3hPJZwQPiLHRAe/view?usp=drivesdk
