### ISSUE TITLE
Emit `baselayerchange` Event on layer changes via layer selector

### ISSUE THREAD

**Issue by juanbrk** [mistic100/Photo-Sphere-Viewer#1493]
### Describe the feature

Currently, the `PlanPlugin` does not emit a `baselayerchange` event when users switch layers. This makes it challenging to respond to layer changes programmatically, such as adjusting the map view to ensure the selected layer is immediately visible.

Adding support for the `baselayerchange` event (or a similar custom event) would allow developers to listen for layer selection changes and trigger appropriate actions (e.g., auto-zooming or fitting bounds).

### Alternatives you've considered

I've tried [listening to the](https://stackoverflow.com/a/18656792/8840456) `baselayerchange` event when the plan plugin is ready, but didn't get any luck.  I also [tried listening to the](https://stackoverflow.com/a/25567366/8840456) `overlayadd` map event with no luck. 

### Additional context

Currently, when switching layers to a secured basemap layer I need to zoom out or move the map around before I get the layer rendered visible on the map. I understand this is what I need to do but the users don't know about that and complain that the map is not visible. 

If only I could listen to `baselayerchange` event, I could add a zoom transition to trigger the rendering of the map  an automatically.

**Comment by mistic100** [comment]
Again : please provide a demo. 

`baselayerchange` is a Leaflet event, so it is emitted by the Map instance, not by the PlanPlugin instance.

**Comment by mistic100** [comment]
[It would probably](https://photo-sphere-viewer.js.org/api/classes/PlanPlugin.PlanPlugin.html#getLeaflet)

```js
viewer.getPlugin('plan').getLeaflet().on('baselayerchange', (e) => {
  console.log(e);
});
```

**Comment by mistic100** [comment]
Si I made a demo https://codesandbox.io/p/sandbox/icy-bird-vwqlz4

And you just have to use "layeradd" event instead.

Because as the docs says https://leafletjs.com/reference.html#map-baselayerchange the "baselayerchange" event is only called by the Leaflet Layers control, which is not what is used by my plugin.
