### ISSUE TITLE
How do I refresh the current scene after using this method? Instead of destroying it

### ISSUE THREAD

**Issue by guoshao99** [mistic100/Photo-Sphere-Viewer#1495]
### Describe your problem

How do I refresh the current scene after using this method? Instead of destroying it
viewer.setOptions({
    fisheye: true,
minFov: 180,
minFov: 1
});
![1732513243582](https://github.com/user-attachments/assets/2b251be2-7da6-4016-80cb-dad9393e9164)

### Photo Sphere Viewer version

5.11.0

**Comment by mistic100** [comment]
I don't understand the question
