### ISSUE TITLE
Hot spot tag dragging issue

### ISSUE THREAD

**Issue by guoshao99** [mistic100/Photo-Sphere-Viewer#1498]
### Describe your problem

I am unable to move annotations when using Layers markers for hotspot annotation, but it is possible to move annotations using images or HTML. Why is this? I used the drag tool, which is jQuery's draggable tool
This question has been bothering me for a long time

### Photo Sphere Viewer version

5.11.1

**Comment by mistic100** [comment]
Layer markers are part of the ThreeJS scene, they are OpenGL object and virtually innexistant for the browser. You will never be able to drag-n-drop them with a library like JQuery draggable.

**Comment by guoshao99** [comment]
Can't the elementLayer be dragged?

**Comment by guoshao99** [comment]
I can't drag him because I don't have an ID
