### ISSUE TITLE
Fix tilt?

### ISSUE THREAD

**Issue by vietquocnguyen** [mistic100/Photo-Sphere-Viewer#150]
If a 360 image has been taken at an angle and I would like to tilt it to fix it. Not in the JPEG but in the viewer, is that possible?

I was looking at viewer.camera.rotateX Y and Z but I didn't quite understand it. Thank you!

**Comment by mistic100** [comment]
Can you confirm you actually talk about the roll (angle of the horizon) ? 
![](http://answers.unity3d.com/storage/temp/85429-pan-tilt-roll1.png)

**Comment by vietquocnguyen** [comment]
That is correct @mistic100. Thank you!

**Comment by vietquocnguyen** [comment]
@mistic100 Thank you! I saw in the commit you added the panorama_roll option which accepts a radian. Is this only Roll or does your commit handle tilt as well?

**Comment by mistic100** [comment]
No it's only roll, what you message saif before you edited it (there is no notification for editions).
If you want more, create a new issue, or submit a pull-request, it's very simple.

**Comment by mistic100** [comment]
In version 3.2.5 "panorama_roll" will be replaced by "sphere_correction.roll" and added "tilt" and "pan"
