### ISSUE TITLE
Is this the right email for support ?

### ISSUE THREAD

**Issue by Mohammadf4f12** [mistic100/Photo-Sphere-Viewer#1505]
### Describe your problem

Hello Damien,

I hope you're doing well.

I sent an email yesterday to \<removed> regarding an issue with Photo-Sphere-Viewer. Since this is quite urgent for me, I wanted to confirm if this email address is still active or if there’s a better way to reach you.

Thank you for your time and support. I appreciate your help.

Best regards,
Mohammad

### Photo Sphere Viewer version

5.11.1

**Comment by mistic100** [comment]
I do not do any private support. This is a free and Open Source project, any request will be on Github only.
