### ISSUE TITLE
I am unable to drag when using videoLayer and imageLayer

### ISSUE THREAD

**Issue by guoshao99** [mistic100/Photo-Sphere-Viewer#1509]
### Describe your problem

I need these two 3D markers for marking points, but I cannot drag them. I can drag other 2D markers because they have an ID attribute. When can we support the dragging function of imageLayer and videoLayer markers, or can we provide more elements for us to drag this marker

### Photo Sphere Viewer version

5.11.0

**Comment by mistic100** [comment]
I already answered to this question, twice.

THIS IS NOT POSSIBLE.

If you continue openning the same issue I will block you. Have a nice day.

**Comment by mistic100** [comment]
You can subscribe to #1499 to be notified of evolutions. But DO NOT ASK "when will it be available". This is NOT planned.
