### ISSUE TITLE
If there is an image switching effect, just like the PPT slide page?

### ISSUE THREAD

**Issue by zhangf1987** [mistic100/Photo-Sphere-Viewer#151]
## Issues guidelines

- **Indicate your Photo-Sphere-Viewer, ThreeJS and web browser versions**
- Please search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

**Comment by zhangf1987** [comment]
I want to make a simple photo gallery similar to the Google street view

**Comment by zhangf1987** [comment]
Is a picture of the interior layout of a house

**Comment by zhangf1987** [comment]
Need image to switch special effects to achieve the effect of roaming in the room

**Comment by mistic100** [comment]
I suggest you take a look at https://github.com/mistic100/Photo-Sphere-Tour

**warning** : it is in very early stage of developement, and do not have time for it. There is no documentation (only an example) and I will not provide support for it.

Also I am not sure it is still compatible with the latest version of PSV, (PST is 2 years old).

Hope this helps.

**Comment by mistic100** [comment]
And you also can do it manually by calling the `setPanorama` method http://photo-sphere-viewer.js.org/api/PhotoSphereViewer.html#setPanorama (this is what PST does)
