### ISSUE TITLE
Get the position in yaw/pitch of a GPS link to use in rotate(position) method

### ISSUE THREAD

**Issue by AndyBaird** [mistic100/Photo-Sphere-Viewer#1518]
### Describe your problem

End goal: a button that someone can click which will rotate the viewer to a virtual tour link that is GPS based.
Problem: the link data only has the GPS coordinates which cannot be used in the rotate method.

Is there a method that can be used to achieve this that I am not seeing? Or is there a way to retrieve the computed position data for a GPS link?

### Photo Sphere Viewer version

5.11.2

### Plugins loaded

VirtualTourPlugin

**Comment by mistic100** [comment]
This method exists as it is used to rotate the viewer when navigating to a node, I can make it public.

If you are in an hurry the private method is `__getLinkPosition(currentNode, targetLink)`, will require a `// @ts-ignore` command ig your are using TypeScript.

**Comment by AndyBaird** [comment]
Awesome, exposing that would be very helpful. Thanks

**Comment by mistic100** [comment]
Please to do not close issue that are not solved. Using a private method is only temporary.
