### ISSUE TITLE
Updating from 5.11.1 to 5.11.3 is breaking the VirtualTourPlugin import

### ISSUE THREAD

**Issue by AndyBaird** [mistic100/Photo-Sphere-Viewer#1519]
### Describe the bug

I tried upgrading from 5.11.1 to 5.11.3 and I get the error `Module not found: Default condition should be last one` for the VirtualTourPlugin. Downgrading to 5.11.1 immediately resolves the issue

<img width="930" alt="image" src="https://github.com/user-attachments/assets/f0d79610-d601-490c-8aee-1b02ac57c9f4" />

### Photo Sphere Viewer version

5.11.3

### Plugins loaded

virtual-tour-plugin

### OS & browser

MacOS Chrome

**Comment by mistic100** [comment]
Is this for real ? https://stackoverflow.com/a/76127619

Since when to order of items **in a map** has any meaning ? I hate NodeJS architecture.
