### ISSUE TITLE
Invalid Panodata - equirectangular Tiles

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#1520]
### Describe the bug

Since 5.11 (with 5.10.1 the warning is not present) when loading an equirectangular tiles pano there's this warning:

`PhotoSphereViewer: Invalid panoData, croppedWidth/croppedHeight is not coherent with the loaded image.
        panoData: 18814x9407, image: 4000x2000`

the rendering of the pano is perfect and the proportion of the image is actually 2:1

I have another equirectangular tiles pano with the dimension of the panodata 16000x8000 and baseUrl image 4000x2000 and the warning is not shown.`

### Online demo URL

https://www.tadini.it/temp/comagna/ps_comagna.html

### Photo Sphere Viewer version

5.11.4

### OS & browser

win 11 - chrome 131

**Comment by mistic100** [comment]
This is because your base image https://www.tadini.it/temp/comagna/PS_Comagna.jpg still has embedded XMP metadata with the original dimensions.

Either remove or update the XMP data when resize the base image to hide the warning.

**Comment by mistic100** [comment]
Can I ask what gear/software you use the capture your panoramas ? They always are really nice !

Do you have a gallery somewhere ?

**Comment by haldo98** [comment]
> Can I ask what gear/software you use the capture your panoramas ? They always are really nice !
> 
> Do you have a gallery somewhere ?

Well, I changed my equipment over time. When I was younger and stronger :-) I always carried my reflex. But hiking with that weight was tough.

Nowadays smartphones are very good for the simple task of taking photos without zoom. I always use a smartphone with a very good sensor (about 50 megapixels and I think that Sony sensor are very good for landscape pictures) and I use the Google Pixel camera app. There are porting for almost any smartphone. 
That app allows you to take photos in RAW with the highest quality. Each photo is 25-40 MB each. 
For the panorama I take 15-16 photos in portrait mode with the main sensor (without wide angle).

For two years I have also been using a drone to take spherical photos. The drone I use when hiking in the mountains is a DJI Mini 2 with a 4k camera.
It's lightweight and very manoeuvrable and reliable.

There's an automatic procedure for spherical photos that also shoots in RAW, but sometimes I prefer to shoot in manual with 3 pics in bracketing, if the wind is not so strong. This way I also have HDR Panoramas.

Once I have all the RAW files (drone ones or not) I stitch them in an equirectangular panorama with the PTGUI software. 

The drone does not capture the zenithal part so I have to create it via software vith Affinity Studio.

I save the panoramas in 16bit TIFF files for the maximum quality and then vith Adobe Lightroom I make some small corrections and color adjustments before creating the jpg file to use with PSV.

I have an HTML-only webpage just for fun: https://www.tadini.it/panorama

And Thanks to you for your work with PSV
