### ISSUE TITLE
Embedding on remote websites

### ISSUE THREAD

**Issue by runtim** [mistic100/Photo-Sphere-Viewer#153]
What would be the best implementation of embedding this on remote websites?
I'm not concerned about CORS (Cross Origin Resource Sharing) because we can control Access-Control-Allow-Origin on our server.

**Comment by mistic100** [comment]
What exactly is your question ? Put your (remote or not) url in `panorama`  and that's it.

**Comment by runtim** [comment]
Is there an easy way to create a widget for sharing on other websites?

**Comment by mistic100** [comment]
This is just a library.... nothing more nothing less.
You probably need an iframe, but I cannot help yoy for that.
