### ISSUE TITLE
psv-panel (for tooltip content) width

### ISSUE THREAD

**Issue by carstengrimm** [mistic100/Photo-Sphere-Viewer#158]
I am not having an issue, but i have been wondering where i can change the default width for the content box after clicking on a tooltip. 

i have been looking thoughout the css and sphere.js file and most of the time each class / selector giving me 100% width, so i haven't been able to figure out what value to chance by now.

for example when clicking the tooltip, i want the window to fill up to 50% of the desktop screen with to provide a bigger view for informations and additional images which i am writing in the content section for each tooltip.

can you help me out pinpointing where to change?

**Comment by mistic100** [comment]
CSS property "max-width" of .psv-tooltip defined here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/scss/_vars.scss#L51

**Comment by carstengrimm** [comment]
psv-tooltip is for the tooltip hover title itself,...

i am looking for the default width of the content section... probably something with .psv-panel

another question of mine was, if it's possible to show the marker list by default.

**Comment by mistic100** [comment]
Then it's line 51, same propety https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/scss/_vars.scss#L51

**Comment by carstengrimm** [comment]
Thanks, that works... To get default call of the markers list i have used.

  viewer.on('ready', function() {
  viewer.showMarkersList();
