### ISSUE TITLE
Always show tooltip (as hovered)

### ISSUE THREAD

**Issue by carstengrimm** [mistic100/Photo-Sphere-Viewer#159]
I'd like to show tooltip titles (same as when hovering) for all available markers. to make visitors already see each point marker with their title before even hovering.

I have been checking out the css file for psv-marker and played with opacity and other values to turn marker titles visible, but it hasn't worked out so far.

**Comment by mistic100** [comment]
Problem is the tooltip is a singleton, only one instance can exists at a time.
It's very unlikely I make this change.
