### ISSUE TITLE
Cannot load image with Anonymous Authentication in IIS Virtual Directory

### ISSUE THREAD

**Issue by srikanth0526** [mistic100/Photo-Sphere-Viewer#164]
Hi Mist,

Hope you are doing good. 

First of all, appreciated for creating and sharing the photosphere image viewer. I am using the Photosphere JS library in our application (ESRI – Portal/Web app builder) and just downloaded the JS full version 3.2.3 code from the below URL. 

Url: http://photo-sphere-viewer.js.org/

I am getting the error message “Cannot load the image” while loading the image residing in the IIS Virtual directory which is Windows Authenticated VD. 
Ex-URL: https://server-name:port/virtualdirectory/images 

Interestingly, I can able to access the image if the Virtual Directory is enabled with anonymous authentication. However, Anonymous authentication is disabled in the server for security reasons. I already raised an issue in the GitHub repository with the username srikanth0526 for the Photosphere viewer. 

It would be helpful if you respond to the issue as soon as possible.

Here are the details:
1. Photosphere Viewer 3.2.3 and Internet Explorer 11
2. cors_anonymous option found in the sample Photosphere viewer version but not in the v3.2.3
3. Exception details in the Photosphere onerror event, the only thing I found Photosphere object is accessing the image with crossOrigin: anonymous which shouldn’t in our case. 
4. Getting 401 Unauthorised error message in the Developer tools console.

**Comment by mistic100** [comment]
Hello,

first of all I am not Jeremy, I am mistic100, it's written on the header.  
The library of Jeremy is here https://github.com/JeremyHeleine/Photo-Sphere-Viewer  
**But** if you downloaded the lib from photo-sphere-viewer.js.org your are using my fork.

---

Now for your problem, I have absolutely no knownledge to configure IIS, I cannot help you.

**Comment by srikanth0526** [comment]
Sorry about that..

I need a solution to overcome the problem with the IIS.

Cheers,
Srikanth Dasari

**Comment by srikanth0526** [comment]
Hi Mist,

Found the root cause on loading the image.. you are using anonymous for the crossorigin attribute to access the image. However, I used user-credentials attribute in the Three.js file and unexpected behavior with the panorama... 
Please guide me on this to close the requirement.
Attaching the image for your reference.
![image](https://user-images.githubusercontent.com/5968148/34185829-4e7a411c-e4ed-11e7-9380-8da3d622edc8.png)

Cheers,
Srikanth Dasari

**Comment by srikanth0526** [comment]
Hi Mist,

Using use-credentials property for the crossOrigin attribute resolved the issue.

Cheers,
Srikanth Dasari
