### ISSUE TITLE
After "yarn install" PSV is not working. (3.2.4 issue?)

### ISSUE THREAD

**Issue by R1cro** [mistic100/Photo-Sphere-Viewer#166]
Hello there.

2 month ago I add this feature into my project and it worked as well. But some days ago team mates moved a new project version and completed "yarn install"...and that thing broke PSV...

![screen shot 2018-01-17 at 2 47 48 pm](https://user-images.githubusercontent.com/14110743/35041551-31239266-fb96-11e7-9d72-a9967ef3fd60.png)

I think, something wrong with **doT.js**.

So, the stable version  (**3.2.3**) looks like this:

<img width="221" alt="screen shot 2018-01-17 at 14 54 59" src="https://user-images.githubusercontent.com/14110743/35041707-be3cb434-fb96-11e7-8bae-3c4d32e31987.png">

Its working as expected.

The "broken" version  (3.2.4) did't move **doT.js** into components (and assets too) and **d.js** generated outside lib.js, but  it should generated inside this lib ...

Looks like the path problems? I'm confused. PSV version changed from 3.2.3 to 3.2.4 and totally stop to work with the same code...

![screen shot 2018-01-17 at 3 13 13 pm](https://user-images.githubusercontent.com/14110743/35042276-016672d4-fb99-11e7-83bd-b2324b492fed.png)

About the code:

**gulp/misc-compiler.js:**

```
// Photo Sphere Viewer dependencies
"node_modules/uevent/uevent.min.js": "/components/uevent",
"node_modules/three/build/three.min.js": "/components/three",
"node_modules/dot/doT.js": "/components/doT",


gulp.task("component:copy", function() {
    var streams = _.map(componentsToCopy, function(dest, src) {
        return gulp.src(src)
            .pipe(plumber())
            .pipe(gulp.dest(fSettings.outputPath + dest));
    });

    return merge(streams).pipe(plumber());
});
```

**gulp/javascript-compiler.js:**

```
"lib.js": [
        ...
        "node_modules/d.js/lib/D.min.js"
]


```

I'm using **requirejs**:

```
requirejs.config({
        // This is where our modules are located
        baseUrl: window.FL_CONFIG.assetPath,

        // This is the amount of time to wait before throwing a timeout exception
        waitSeconds: 15,

        // This supports shorter path names when actually requiring a module
        paths: {
            "three":    "components/three/three.min",
            'uevent':   "components/uevent/uevent.min",
            'doT':      "components/doT/doT",
        },

```

And all this code works as expected... 

What is going on? What changed in PSV?

package.json -> "photo-sphere-viewer": "~3.2.4" and nothing more.

**Comment by R1cro** [comment]
Okay, I figured out with doT.js (moved him into assets folder from components) and now I got this:

```
Script Error: require null undefined TypeError: D is not a function
    at Function.PhotoSphereViewer._loadSystem...
```

```
/**
 * @summary Inits the global SYSTEM var with generic support information
 * @private
 */
PhotoSphereViewer._loadSystem = function() {
  var S = PhotoSphereViewer.SYSTEM;
  S.loaded = true;
  S.pixelRatio = window.devicePixelRatio || 1;
  S.isWebGLSupported = PSVUtils.isWebGLSupported();
  S.isCanvasSupported = PSVUtils.isCanvasSupported();
  S.maxTextureWidth = S.isWebGLSupported ? PSVUtils.getMaxTextureWidth() : 4096;
  S.mouseWheelEvent = PSVUtils.mouseWheelEvent();
  S.fullscreenEvent = PSVUtils.fullscreenEvent();
  **S.deviceOrientationSupported = D();** <<<< Here
```

Looks like its **D.js**...

**Comment by R1cro** [comment]
After my little investigation, I found this: https://github.com/mistic100/Photo-Sphere-Viewer/commit/798912cf3f31a5b87f78efadd65c8016d29ac618

Well. Any ideas hot I can correctly add this libs with 3.2.4?

**Comment by mistic100** [comment]
Sorry but I cannot help you. It is not related to PSV itself as it requires modules whith their correct name regarding NPM. And I absolutely do not know RequireJS.

You must have a way to override modules names/paths (this `path` option in requirejs conf is a good candidate).
