### ISSUE TITLE
Image washed out on Safari/Mac

### ISSUE THREAD

**Issue by EricDu** [mistic100/Photo-Sphere-Viewer#171]
The image is very washed out (almost white) on the demo site (http://photo-sphere-viewer.js.org/) with Safari on Mac

Adding CSS style "background:#000;" to _.psv-canvas-container_ fixes the problem on Safari. Not sure if that change would have any impact on other browsers.

Mac Pro 5,1, Mac OS 10.12.6, Safari 11.0.3, NVIDIA Web Driver

**Comment by mistic100** [comment]
Screenshot ?

**Comment by EricDu** [comment]
Sorry. Didn't see the request for screenshot until today. As you can see, the blending mode Safari uses (screen mode?) makes it washed out.

You can either darken the container (as shown below) or set the background-color of the canvas itself (canvas.psv-canvas) to black (which would preserve the loading background pattern). Changing background-blend-mode has no effect.

Default (pattern background)
![screen shot 2018-03-25 at 10 11 25 am](https://user-images.githubusercontent.com/3483810/37876084-b166fa54-3015-11e8-996e-a11842f10b53.png)

Light gray background
![screen shot 2018-03-25 at 10 14 23 am](https://user-images.githubusercontent.com/3483810/37876081-b13fc40c-3015-11e8-90ed-66e3320df8d4.png)

Color background
![screen shot 2018-03-25 at 10 12 50 am](https://user-images.githubusercontent.com/3483810/37876083-b1582ace-3015-11e8-8a92-20bb5792bc49.png)

Black background
![screen shot 2018-03-25 at 10 13 11 am](https://user-images.githubusercontent.com/3483810/37876082-b14d584c-3015-11e8-9a66-5b412c5626b8.png)

**Comment by mistic100** [comment]
I don't like this solution.

Can you try to add `{alpha: true}` in the `new THREE.WebGLRenderer()` ?
https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/dist/photo-sphere-viewer.js#L978

Relevant discussion : https://github.com/mrdoob/three.js/issues/9685

**Comment by mistic100** [comment]
Closing, feel free to create a new issue
