### ISSUE TITLE
Multiple spheres?

### ISSUE THREAD

**Issue by kaludjer** [mistic100/Photo-Sphere-Viewer#175]
Is it possible to initialize multiple Spheres? With multiple containers ofc.

**Comment by mistic100** [comment]
did you try ?

**Comment by kaludjer** [comment]
Problem is because container value can be only element or ID. I changed it to allow classes and it's ok now. Thanks anyway.

**Comment by mistic100** [comment]
So you mean you want the same sphere on multiple containers ? Clearly I will not support it.

**Comment by mistic100** [comment]
And if your only

**Comment by kaludjer** [comment]
Not same sphere, I made it gallery-like. You have for example 5 items with 5 different spheres but configuration has to be same.

**Comment by mistic100** [comment]
ok, so why did you need to modify the library ?

Here using lodash extend and querySelector
```js
PhotoSphereViewer(_.extend({
  panorama: 'image-1.jpg', 
  container: document.querySelector('.container-1')
}, defaultConfig);
```

---

Anyway I strongly advise **against** initializing multiple viewers at once, you will get awfully slow page by doing this.

Prefer having only one viewer and use the `setPanorama`  method to switch between images.

**Comment by kaludjer** [comment]
Nice, tnx.
