### ISSUE TITLE
double/duplicate download of panorama images

### ISSUE THREAD

**Issue by Nightreaver** [mistic100/Photo-Sphere-Viewer#177]
I recently installed photo sphere viewer v3.2.4 with corresponding requirements:
```
    "three.js": ">= 0.85.0",
    "D.js": "~0.7.3",
    "uevent": "~1.0.0",
    "doT": ">=1.0.3"
```

Then I tried to load a spherical panorama of about 50MB, after some waiting time, I noticed that loading takes longer than expected. So I checked the Chrome developer tools, Network section
![image](https://user-images.githubusercontent.com/3270156/36411418-dde1d292-1658-11e8-8647-b69c9d607831.png)

As you can see, the `PANO0001.jpg` file is fully loaded two times.   
First by `photo-sphere-viewer.js` as **xhr** and secondly from `three.js` as **jpg** to finally display the image.

Even though it doesn't matter much for personal computers... it might matter more for mobile devices and is kind of a hassle for people with low internet connection speed / data volume (they still exist, my parents for example have 6mbit internet connection at home)

Used: Chrome Version 61.0.3163.100 (Official Build) (32-bit)

And the code I used  
```javascript
<script>
  var PSV = PhotoSphereViewer({
    container: 'photoshpere',
    panorama: './PANO0001.jpg',
    loading_img: './photosphere-logo.gif',
    caption: '...',
    default_fov: 80,
    default_lat: -0.3,
    anim_speed: '1rpm',  
  });
</script>
```

Is this something that can be fixed?

**Comment by mistic100** [comment]
Multiple solutions :

- Re-enable `cache_texture` , I disabled it by default because it caused a lot of trouble (the doc is outdated, the default is `0`)
- Disable `usexmpdata` if your panorama is not cropped
- Manually provide `pano_data` if the panorama is cropped

And BI think a 50MB image is overkill, it will be downsized anyway according to the max supported texture size which range from 4096 to 16384 depending on the system.

**Comment by Nightreaver** [comment]
Thanks for the answer.
what does cropped mean in is context?

**Comment by mistic100** [comment]
http://360rumors.com/2016/06/technique-how-to-make-partia.html

**Comment by Nightreaver** [comment]
thank you, i disabled `usexmpdata` an it workes with "single download"
I will reconsider changing the size, but its just 17k*6k so might be okay for 16384, will do some tests though
