### ISSUE TITLE
How to use Marker polyline or path in svg

### ISSUE THREAD

**Issue by greatevil84** [mistic100/Photo-Sphere-Viewer#178]
## Issues guidelines

- **Indicate your Photo-Sphere-Viewer, ThreeJS and web browser versions**
- Please search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

**Comment by mistic100** [comment]
Give more detail of your problem or I close this issue.

I am sure there are enough info by reading the doc and the example
"Show source" on this page http://photo-sphere-viewer.js.org/markers.html

**Comment by greatevil84** [comment]
var addMarkerPolyline = (myRads) => {
    var id = '#' + Math.random();
    var arrays = [];
    var arrayPoints = [];
    var pathStr = "";
    
    myRads.forEach((rad,index) => {
        let PSVUtils = PhotoSphereViewer.Utils;
        arrays.push([rad.radLon, rad.radLat]);
        latitude = PSVUtils.parseAngle(rad.radLat);
        longitude = PSVUtils.bound(PSVUtils.parseAngle(rad.radLon, -Math.PI), -PSVUtils.HalfPI, PSVUtils.HalfPI);
        var myVector3 = myPSV.sphericalCoordsToVector3({latitude,longitude});
        var myPoint = myPSV.vector3ToViewerCoords(myVector3);
        arrayPoints.push(myPoint);
        //arrayPoints.push(myPSV.sphericalCoordsToTextureCoords({latitude:rad.radLat,longitude:rad.radLon}));
        
    });
    arrayPoints.forEach((point,index)=>{
        if(index==0){
            pathStr += "M"+point.x+" "+point.y+"";
        }else{
            pathStr += " L"+point.x+" "+point.y+"";
        }
    });

    console.log({myRads,arrays,arrayPoints,pathStr});

    //show in polygon is okay
    myPSV.addMarker({
        id: id,

        polygon_rad: arrays,
       svgStyle: {
        fill: 'rgba(200, 0, 0, 0.2)',
        stroke: 'rgba(200, 0, 50, 0.8)',
        'stroke-width': '2px'
      },
        tooltip: {
            content: 'A dynamic polygon marker ' + id,
            position: 'right bottom'
        }
    })

    //but in path svg is problem, class don't create 'psv-marker--visible'
    myPSV.addMarker({
        id: id+"2",
        path:pathStr,
       svgStyle: {
        stroke: 'rgba(200, 0, 50, 0.8)',
        'stroke-width': '3',
        fill:"none"
      },
      tooltip: {
        content: 'A dynamic polyline marker ' + id,
        position: 'right bottom'
    },
      //className:"psv-marker--visible",
        visible:true
    })
};

**Comment by mistic100** [comment]
What I am supposed to do with this block of code ?
Did you read my issue guidelines ? I won't answer anymore if you don't follow them.

**Comment by greatevil84** [comment]
I have read your guidelines in marker but i have a question in if i want to show polylines or lines in photo sphere view how can i do that? because it have no sample how to do it. Thanks for reply

**Comment by mistic100** [comment]
You really need to clarify your question :

1. Do you want a static line attached to a point of the sphere ? Then you the **path** marker

2. Do you want to display one or multiple lines following the perspective of the sphere (like the polygon does) ? Then this feature does not exist.

**Comment by greatevil84** [comment]
I already have the solution by this issue by changing the code using **path** marker. So this issue can be closed. Thanks for your reply. this issue can be close

**Comment by mistic100** [comment]
Anyway I added "polyline_rad" and "polyline_px" markers on the `dev` branch

**Comment by greatevil84** [comment]
That great help man. Thank you very much
