### ISSUE TITLE
Sometimes the sphere turns black (and sometimes blue) after refreshing

### ISSUE THREAD

**Issue by mariommoreno** [mistic100/Photo-Sphere-Viewer#18]
Using Firefox 44.0.2. 
Markers remains visible and functional.

**Comment by mistic100** [comment]
What is "refreshing" ?

I'm also using FF without issue, please setup an online example.

**Comment by mariommoreno** [comment]
I was just running the demo.
By refresh I mean pressing F5 or Ctrl+F5.
I mean, the same sphere that worked before, then stops running.

I've read it's a common WebGL problem (I remember something similar running a 360Video demo from Theta S Camera). But I was visiting other sphere solution (paid ones...) that where running while this one was still black.. or blue.

Don't think I'm criticizing. I really want to use your code. I think that covers a BIG gap in photosphere need for customizable solutions.

**Comment by mistic100** [comment]
Problem is that I'm absolutely not expert in Three.js and WebGL, so I'll need external help if there are problems.

**Comment by mariommoreno** [comment]
Neither a three.js or even js expert, sorry.

Not sure if the warning is important.
It can be avoided adding this to the texture:
`texture.minFilter = THREE.LinearFilter;`

I also added:
    `texture.generateMipmaps = false;`
Because mipmaps are used only when objects are far or little and it's not the case.

But the black/blue happens anyway.

One curious thing is when your sphere crashes to black, also the Theta360 sphere turns black. And only when I close your sphere, the other viewer can recover. So it looks like a memory related issue that affect other Three.js instances. Maybe something related to the buffer? I don't know...

**Comment by mistic100** [comment]
This actually happens when the WebGL process crash, because it's shared accross de whole system.

There is nothing proving or not it's related to memory.

(You can experience this behavious on https://www.shadertoy.com for example).

**Comment by mariommoreno** [comment]
Ok... It has more sense :)
