### ISSUE TITLE
How to let container rotate 90° ?

### ISSUE THREAD

**Issue by Realybig** [mistic100/Photo-Sphere-Viewer#180]
i want to container rotate 90° ,i use  CSS3 transform: rotate(90deg) but i found when mouse move not right T_T , what should I do?
![image](https://user-images.githubusercontent.com/10878451/36774250-34f485f8-1c98-11e8-9b30-0a8d2d551844.png)

**Comment by mistic100** [comment]
Sorry I highly doubt it is possible and for such a rare usecase I won't spend time on it.
