### ISSUE TITLE
clearPanoramaCache() behaviour changed

### ISSUE THREAD

**Issue by TheoHarbers** [mistic100/Photo-Sphere-Viewer#181]
Using latest distribution from: http://photo-sphere-viewer.js.org/dist
Remark: DeviceOrientationControls.js has gone missing from the distribution !!!!

Since yesterday Photo-Sphere-Viewer stopped working because of failing clearPanoramaCache()

	 panoPlayer = new PhotoSphereViewer({
					container: 'photosphere',
					navbar: 'gyroscope autorotate zoom caption fullscreen',
					fisheye: false,
					mousewheel: true,
					gyroscope: true,
					move_speed: 4,
					size: {	height: 400 },
					autoload: false
				});

		panoPlaying.setPanorama("mypano");

/// later on trying to clear the cache
               panoPlayer.clearPanoramaCache();

Chrome reports following error and the viewer stops working:

photo-sphere-viewer.min.js:7 Uncaught b {message: "Cannot clear cache, cache_texture is disabled", stack: "PSVError: Cannot clear cache, cache_texture is dis…n.com/bootstrap/3.3.7/js/bootstrap.min.js:7:1230)"}
message:
"Cannot clear cache, cache_texture is disabled"
stack

"PSVError: Cannot clear cache, cache_texture is disabled↵    at n.clearPanoramaCache (http://photo-sphere-viewer.js.org/dist/Photo-Sphere-Viewer/dist/photo-sphere-viewer.min.js:7:32330)↵    at HTMLAnchorElement.<anonymous>↵    at HTMLAnchorElement.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:3:10315)↵    at HTMLAnchorElement.q.handle (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:3:8342)↵    at Object.trigger (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:4:5808)↵    at HTMLAnchorElement.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:4:6318)↵    at Function.each (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:2815)↵    at r.fn.init.each (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:2:1003)↵    at r.fn.init.trigger (https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js:4:6294)↵    at c.show (https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js:7:1230)"
__proto__
:
Error

**Comment by mistic100** [comment]
As stated in the changelog, I disabled the cache by default, you need to configure it if you want (`cache_texture` option).

---

You should not use the files from the demo website ! Get them from a CDN or NPM
