### ISSUE TITLE
postinstall script cannot be executed in 3.0.0-snapshot

### ISSUE THREAD

**Issue by elboletaire** [mistic100/Photo-Sphere-Viewer#182]
With Photo-Sphere-Viewer 3.0.0-snapshot the `postinstall` script cannot be properly executed, at least under CI environment:

- Under CI environments, the used user usually is `root`, so the `bower install` fails, because doesn't allow root.
- After changing my docker CI image to not run as root, the error is `ENOENT No bower.json present`.
- Given this case, where you are adding major changes, you should not use a minor version, but a major one (4.0.0 instead of 3.3.0).

In my case, the 3.2.4 version was working well, so I'm gonna fix the version to avoid this issues.

**Comment by mistic100** [comment]
I always forgot that "postinstall" is executed when the package is installed (!!) and not only when it's dependencies are locally installed.
It's a pity there is still no way to distinguish these two cases.

I'll publish 3.3.1 during the day.

**Comment by elboletaire** [comment]
Thanks @mistic100 😃
