### ISSUE TITLE
Scrolling content of marker on mobile doesn't happen and hint for solution

### ISSUE THREAD

**Issue by axel20000** [mistic100/Photo-Sphere-Viewer#183]
I'm testing your demo at http://photo-sphere-viewer.js.org/markers.html with my mobile phone on Chrome and also on desktop Chrome with developer tools set for mobile phone. 

In both cases I notice a behavior. When you click on the blue marker to show the "HTML Ipsum Presents" text and a google map, it is not possible to scroll the content of the marker. The curious thing is that when you tap and move on the google map, you can scroll the content of the marker. I also tried this with a copy of your demo taking out the google map but I still couldn't scroll the content. I also tried changing css on psv-panel-content's overflow from auto to scroll but nothing changed. Actually I played a lot with overflow and position of elements to make some difference but I didn't make it.

Actually I think whatever the google map iframe does is what should be done on psv-panel-content to achieve scroll on mobile. I don't know if it's something about CSS or javascript in the google map, for example something about tap/touch events. This google map expects two fingers when tapping and when using one finger it looks like it lets the movement to propagate away from the iframe which lets psv-panel-content receive the touch movement and then scroll happens.

May be it's something simple to make this behavior work but I'm out of ideas.

**Comment by mistic100** [comment]
#119
didn't had time to test
