### ISSUE TITLE
Pointer lock with Photo Sphere Viewer

### ISSUE THREAD

**Issue by ZhuJo** [mistic100/Photo-Sphere-Viewer#184]
I would like to ask whether it's possible to use some kind of Pointer lock with Photo Sphere Viewer.

That means user would just have to hover around the panorama without holding the button to rotate panorama.

**Comment by mistic100** [comment]
how to you imagine the configuration ? a single point [longitude, latitude] which will follow the cursor ? (that implies the use won't be able to do a full rotation)

**Comment by ZhuJo** [comment]
yeah, something like that. Can check videojs-panorama, it works like that. Obviously it should allow the user to leave the area with cursor. 

Actually I want Photo Sphere as an fallback for video panorama as Safari in macOS High Sierra 10.13.3 is unusable regarding video mapped on WebGL sphere (no video or stroboscopic blinking)

**Comment by mistic100** [comment]
I don't see any pointer lock in the demo...

**Comment by ZhuJo** [comment]
It's not in the demo on page, but it's default.

Check options. https://github.com/yanwsh/videojs-panorama

**Comment by mistic100** [comment]
I set `clickAndDrag: false` and either I am dumb either it's just not working, the view is only facing the south pole and I can't turn around.

Not really helping to understand the behaviour you want.

**Comment by mistic100** [comment]
Okay it only works in fullscreen !!!

If we see the same thing, it's not a "pointer lock" at all.

It's certainly doable.

**Comment by ZhuJo** [comment]
rotation simply follows mouse cursor on movement within certain threshold.

Thanks for info.

**Comment by mistic100** [comment]
Well I won't say it "follows" the cursor as the X axis is inverted :-)
