### ISSUE TITLE
Reset default view 

### ISSUE THREAD

**Issue by NoAtaraxie** [mistic100/Photo-Sphere-Viewer#185]
Hello all, 

I just want to know how to clean panorama. 

I tried to do {panorama: ' '} but it generate an error.  
And i do not want destroy the PSV object. 

There is any solution to this ? 

Thanks 

Regards,

**Comment by mistic100** [comment]
Hello

this is not possible and I don't really get the point.
If you temporary don't need the viewer you should destroy it in order the free the resources used by the WebGl context.

**Comment by NoAtaraxie** [comment]
Hello,

Of course, you are right. I  was so focused on my goal and did not see that what I wanted was stupid.
Tanks, 

Good library, good job and good luck.
