### ISSUE TITLE
Chrome HTML Canvas rendering broken with version 3.3.0+

### ISSUE THREAD

**Issue by rabelloo** [mistic100/Photo-Sphere-Viewer#186]
#### Versions
- **Photo-Sphere-Viewer:** 3.3.1
- **ThreeJS:** 0.91.0 (actually coming from Photo-Sphere-Viewer dependencies which is >= 0.70.0)
- **Chrome:** Version 64.0.3282.186 (Official Build) (64-bit)

Included files on build (in order):
- node_modules/three/build/three.js
- node_modules/three/examples/js/renderers/CanvasRenderer.js
- node_modules/three/examples/js/renderers/Projector.js
- node_modules/three/examples/js/Gyroscope.js
- node_modules/dot/doT.js
- node_modules/uevent/uevent.js
- node_modules/d.js/lib/D.js
- node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js

### Issue
**All I get with this setup is a black screen where the image should be and no error**

IE can render it just fine.

We use the library in an enterprise environment where WebGL is disabled, so I assume all rendering is done using HTML Canvas.

For every render I get a console.log with message "THREE.CanvasRenderer 91".

We are using equirectangular panoramas taken with Ricoh Thetas.

It still works fine on version ~3.2.4

Haven't had time to take a look at the source code yet.
For the time being we are locking our package.json version to ~3.2.4

I would appreciate any help on the issue

PS: I have the same issue on the homepage's panorama: http://photo-sphere-viewer.js.org/
Except it logs "THREE.CanvasRenderer 89", so I'm assuming ThreeJS version 0.89.0 is being used instead

**Comment by mistic100** [comment]
Thank you, I release 3.3.2
