### ISSUE TITLE
How to make the machine move around 怎样使像机前后左右移动

### ISSUE THREAD

**Issue by hongtctc** [mistic100/Photo-Sphere-Viewer#187]
It feels like in the real scene that you can move freely and then dynamically load more real pictures on the server.

感觉自己真的是在实景里一样，可以自由的走动，然后可以动态的到服务器加载更多的实景图片。

**Comment by mistic100** [comment]
I am sorry but your automatic translation does not make sense. If you can't speak English I cannot help you.
