### ISSUE TITLE
Cache Panorama before setPanorama

### ISSUE THREAD

**Issue by pmsfc** [mistic100/Photo-Sphere-Viewer#190]
## Panorama Cache

I am trying to cache a item before **setPanorama**, i see that is possible to **getPanoramaCache** and **clearPanoramaCache**.

Is this possible now?  Or will it be a possible new feature?

Regards

**Comment by mistic100** [comment]
http://photo-sphere-viewer.js.org/api/PhotoSphereViewer.html#preloadPanorama
