### ISSUE TITLE
Support cylinder panoramic preview

### ISSUE THREAD

**Issue by bigfacewo** [mistic100/Photo-Sphere-Viewer#199]
thanks a lot.

**Comment by mistic100** [comment]
Please ellaborate

**Comment by wukaikailive** [comment]
Hi!

If i just have a normal picture(not for the sphere), but if I use the panorama of the cylinder,the picture will become a cylinder's map,the preview will be the same as the sphere, which can be moved and rotated.

Then,the bottom and top of the cylinder can be set up with text or other pictures.

I looked for a long time and found that they were all spherical panorama. I wanted to make one myself, but I needed to learn three.js first. that's a big challenge for me.

emm..I hope you can understand what I mean.

**Comment by mistic100** [comment]
Not really... it's very confuse.

Why don't you use something like https://github.com/peachananr/panorama_viewer ?

**Comment by wukaikailive** [comment]
Yes, I also saw this, but this didn't have the 3D preview effect.

**Comment by wukaikailive** [comment]
In your library, the picture is used as the map of the ball, and the camera is inside the ball. I'm talking about the picture as a map of the cylinder, and the camera inside the cylinder.

**Comment by wukaikailive** [comment]
You can see this [example](https://s.wcd.im/index.jsp?id=15190Zqb&flyerAid=15190&loading=1&chl=).

**Comment by mistic100** [comment]
But, that's ugly ! The image is completely deformed when panning up and down, it made me sick in seconds.

Anyway, this library is for complete spheres, you can use the crop support as explained here https://photo-sphere-viewer.js.org/crop.html but that's all.

**Comment by wukaikailive** [comment]
Yes,I know the cropped panorama feature.
Anyway,Thanks!
