### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by s427** [mistic100/Photo-Sphere-Viewer#2]
When viewing the documentation page (http://mistic100.github.io/Photo-Sphere-Viewer/) with Internet Explorer 11 (Windows 8.1), the photosphere viewer gets stuck. The loading animation works normally, and then the navigation bar appears, but nothing else. (Screenshot below)

In the console, there's the following error message:
> THREE.CanvasRenderer has been moved to /examples/js/renderers/CanvasRenderer.js

I've had the same behavior happening on personal tests (also IE11; works fine with Firefox or Chrome).
Hope this helps.

![psv-ie11](https://cloud.githubusercontent.com/assets/2195471/7431852/f2a9c7ca-f022-11e4-9662-ab83ef48cf01.png)

**Comment by mistic100** [comment]
can you try including https://github.com/mrdoob/three.js/blob/master/examples/js/renderers/CanvasRenderer.js ?
if it works I'll add a note on the doc saying to include the renderer in addition to core three.js

**Comment by s427** [comment]
OK, I included the file, which caused a brand new error to appear:

> THREE.Projector has been moved to /examples/js/renderers/Projector.js.

So I also included this file, and now it's working. :-)

**Comment by mistic100** [comment]
Thank you
