### ISSUE TITLE
How can I destroy instance? (Only question)

### ISSUE THREAD

**Issue by jobsboris27** [mistic100/Photo-Sphere-Viewer#201]
I'm using it inside angular application, inside modal component.
That component can be showed/destroed, and i need to create/destroy PhotoSphereViewer instance, but i don't understand aboun "right way" of destroying instance of PhotoSphereViewer.

**Comment by mistic100** [comment]
```js
viewer.destroy();
```

It's in the doc https://photo-sphere-viewer.js.org/api/PhotoSphereViewer.html#destroy
