### ISSUE TITLE
2D XY to texture coordinates XY

### ISSUE THREAD

**Issue by pajamabob** [mistic100/Photo-Sphere-Viewer#204]
I have a panoramic image that is 4000 pixels wide X 1765 pixels high.  I have a point on that 2D image that is at x = 2500 y = 1600.  I want to programmatically add a marker at the point.

Is there a function or a formula for converting the 2D X/Y position into X/Y texture coordinates when projected on a sphere in the Photo Sphere Viewer?

**Comment by mistic100** [comment]
There is no conversion to do, it's the same thing. x and y are in pixels on the image and longitude and longitude are in radians on the sphere.
