### ISSUE TITLE
wrong case in AMD define

### ISSUE THREAD

**Issue by speich** [mistic100/Photo-Sphere-Viewer#205]
version 3.3.3

The D.js dependency is defined as "d.js", but module is defined/exported as "D.js".
 See https://github.com/malko/D.js/blob/5217f4c04a047b3695ab51751c0bf8666317aa10/lib/D.js#L434
versus
https://github.com/mistic100/Photo-Sphere-Viewer/blob/4006db12531ab78ebc2e182297421bb656077713/src/js/.wrapper.js#L3

**Comment by mistic100** [comment]
I didn't work either with a capital D when using Webpack.
https://github.com/mistic100/Photo-Sphere-Viewer/issues/130

As its seems loaders and bundlers have unconsistent behaviours I won't change anything.
You will have to configure the particular bundler/loader to aliad the dependency.

**Comment by speich** [comment]
The problem is, that "D.js" is not a valid AMD module name. I opened issue https://github.com/malko/D.js/issues/21 accordingly.
