### ISSUE TITLE
gyroscope:true not working in v.3.3 

### ISSUE THREAD

**Issue by jiimmysu** [mistic100/Photo-Sphere-Viewer#208]
Hello,

I got an issue about "gyroscope" option in version 3.3.
I already included DeviceOrientationControls.js on page, but there are some problems below, Do I miss something?
- I set gyroscope:true,  but the viewer doesn't move when I moving my phone. 
- The result of isGyroscopeEnabled() is always false.
- PSV1.toggleDeviceOrientation() is not a function. 

## example code
- simple example https://jsbin.com/sunahoyaqu/edit?output
- The other person I found on google, he got the same problem like me recently. https://segmentfault.com/q/1010000015426170

## browser:
- iOS 11.4/ Safari 
- Android 8.0 / Chrome 67.0.3396.87

**Comment by mistic100** [comment]
if you don't add the "gyroscope" in the navbar, the user won't be able to enable the control, it does not start by itself

and the method is not "toggleDeviceOrientation" but "toggleGyroscopeControl" as detailed in the doc https://photo-sphere-viewer.js.org/api/PhotoSphereViewer.html#methods

**Comment by rishisharma08** [comment]
i am going through the same issue, i added `gyroscope: true` in the options, and 
`psv.toggleGyroscopeControl()` in the ready callback. yet i dont see it working. 
i keep getting the warning `PhotoSphereViewer: gyroscope not available`
I am trying this out on my desktop browser with iphoneX emulation and orientation sensors enabled. 
Typing `'DeviceOrientationEvent' in window` in the console returns `true` but still failing.

seems to be failing on a 2 second timeout inside the **PSVUtils.isDeviceOrientationSupported**
`    setTimeout(function() {
      if (defer.promise.isPending()) {
        listener(null);
      }
    }, 2000);`

**Comment by rishisharma08** [comment]
so i tried one more thing just now: 
i kept moving my device orientation emulator while the page loaded so that the **listener** callback would be called, and the `defer.resolve();` will get called. to check the orientation support, you add a listener and then wait for an event to be fired for 2 seconds. if nothing fired, you `defer.reject()`.

so seems like it worked that way (kinda hacked around it).
