### ISSUE TITLE
VR mode does not work on iPhone

### ISSUE THREAD

**Issue by xvlm** [mistic100/Photo-Sphere-Viewer#209]
V3.4.0
No change after clicking on the VR icon.
But it works on Android.

**Comment by mistic100** [comment]
If you can try to debug and submit a fix, please do.
I don't have access to an iPhone.

**Comment by Blindmikey** [comment]
Just adding some detail - console error thrown when clicking to utilize vr on iphone:

```TypeError: undefined is not an object (evaluating '(t.requestFullscreen||t.mozRequestFullScreen||t.webkitRequestFullscreen||t.msRequestFullscreen).call')```

**Comment by Blindmikey** [comment]
Some further sleuthing shows that mobile iOS doesn't support the fullScreen API.
https://caniuse.com/#feat=fullscreen

A potential solution might be the old .webkitEnterFullscreen() method, though a preliminary addition of that function in the following list did not immediately solve the problem. 

```(t.requestFullscreen||t.mozRequestFullScreen||t.webkitRequestFullscreen||t.msRequestFullscreen||t.webkitEnterFullscreen).call```
