### ISSUE TITLE
re-render possible

### ISSUE THREAD

**Issue by umxr** [mistic100/Photo-Sphere-Viewer#210]
Hi i was just wondering whether or not it was possible to force a re render of the current instance of the photo viewer. ive looked through the documentation and i cant seem to find one, Unless ive missed it

**Comment by mistic100** [comment]
@pajamabob this method is deprecated, one must call [`needsUpdate()`](https://photo-sphere-viewer.js.org/api/PhotoSphereViewer.html#needsUpdate) instead

@umxr Why do you need to perform a render ?

**Comment by umxr** [comment]
@mistic100 id like to update the image once the user clicks a certain marker. i feel like this is possible but the way im going about it is incorrect

**Comment by mistic100** [comment]
You do not need a render for that, a render is exclusively for the WebGL view, the markers are not in the WebGL view.

To update a marker you need the `updateMarker` method, with at meast its `id` and the property you want to change (here the `image` I guess).

---

General rule : when you need something on a library you don't master, start by explaining what you want to do, not what you think is the solution :-)

**Comment by umxr** [comment]
I dont think i explained it properly, But here goes :)

So, when a user initially loads on the page, theyll be a panoramic image the user can enjoy. to the left and right of them. i will place a marker, when a user clicks on either, It will change the panorama prop to show the correct image.

**Comment by mistic100** [comment]
The you need https://photo-sphere-viewer.js.org/api/PhotoSphereViewer.html#setPanorama or https://photo-sphere-viewer.js.org/api/PhotoSphereViewer.html#animate
