### ISSUE TITLE
Adding content to panel when addMarker is clicked

### ISSUE THREAD

**Issue by mavenandy** [mistic100/Photo-Sphere-Viewer#211]
Hello,

Like the title says I was wondering if there is a functionality already set in place that adds content to the content panel when a new point is selected or (onclick addMarker). 

Here's how I currently have is structured:

https://jsfiddle.net/ng8m9yuz/1/

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/api/module-components.PSVPanel.html#showPanel


```js
viewer.showPanel(fullContent); // you have to keep fullContent updated somewhere in your app
```

**Comment by mavenandy** [comment]
Thanks! This helped me look at the functionality different.

I ended up putting showPanel(); outside of the addMarker(); method, then I pulled the content with a getElementById(); method.

> PSV.on('click', function(e) {
      PSV.addMarker({
        id: '#' + Math.random(), etc...
        }
      });
      PSV.showPanel( document.getElementById('edit-tag').innerHTML ); 
    });
