### ISSUE TITLE
IE11/Edge - image load fails on certain machines/versions of Windows

### ISSUE THREAD

**Issue by bigwigal** [mistic100/Photo-Sphere-Viewer#213]
This one is down to `image.crossOrigin` always being set to 'anonymous' regardless of it's origin. I don't know why but when ran on our servers it causes the image load to be aborted in <1ms. I found [this article](https://medium.com/@albertogasparin/manipulating-cross-origin-images-with-html-canvas-1e3e8780964c) and added the following line before calling the loader:

`loader.setCrossOrigin((/^([\w]+\:)?\/\//.test(panorama) && panorama.indexOf(location.host) === -1) ? 'anonymous' : 'use-credentials');`

Seems to have sorted the problem. This fix is probably better made in the three.js code but I thought you would want to hear about it and make your own mind up. Thanks again.

**Comment by mistic100** [comment]
If you use the last version there is the "with_credentials" option

**Comment by mistic100** [comment]
https://github.com/mistic100/Photo-Sphere-Viewer/commit/4006db12531ab78ebc2e182297421bb656077713

**Comment by bigwigal** [comment]
Wow, that was quick. Sorry, completely missed that! Will do, thanks!
