### ISSUE TITLE
[Feature] Keyboard controls.

### ISSUE THREAD

**Issue by b3none** [mistic100/Photo-Sphere-Viewer#216]
It'd be nice if we could add super simple keyboard controls.

**Comment by mistic100** [comment]
Please be more specific.
There already are keyboard controls enabled by default with the "keyboard" option https://photo-sphere-viewer.js.org/#options

**Comment by b3none** [comment]
This is what I meant @mistic100.

**Comment by mistic100** [comment]
@b3none You will be able to provide your own keyboard events :

```js
PhotoSphereViewer({
  keyboard: {
    'w': 'rotateLatitudeUp',
    's': 'rotateLatitudeDown',
    'd': 'rotateLongitudeRight',
    'a': 'rotateLongitudeLeft',
  }
})
```
