### ISSUE TITLE
How to disable scroll on mobile

### ISSUE THREAD

**Issue by Maadtin** [mistic100/Photo-Sphere-Viewer#219]
Please how to disable mousewheel scroll on mobile, It only works on browser

**Comment by mistic100** [comment]
I'm sorry but your sentence makes no sense. If it does not work on mobiles (obviously) why do you want to disable it ?

**Comment by mistic100** [comment]
I understand, but in that case how would you navigate in the photo ?

**Comment by Maadtin** [comment]
with the zoom in and out ? If It works on desktop why not on mobile? :s

**Comment by Maadtin** [comment]
I see your point, okay then I'll figure out a solution to this myself. thanks..

**Comment by mistic100** [comment]
@Maadtin I would very glad if you can give it a try on the dev branch.
You need to build the lib (explained in the readme) and use the new "touchmove_two_fingers: true" option.

It should not block page interactions with single touch and require two touches to navigate.
