### ISSUE TITLE
Full screen display issues in Safari (Mac/iPad)

### ISSUE THREAD

**Issue by bigwigal** [mistic100/Photo-Sphere-Viewer#231]
When entering full screen mode the element moves to the top left of the screen but fails to resize to fill it. The full screen icon is actually missing on the iPad I have but the resize issue has been observed on another iPad. I've also checked the example on your main documentation and both issues can be seen.

Versions:
Photo-sphere-viewer 3.4.0
Three.JS 0.94.0
Safari (Mac OS 10.11.6) 11.1.2
Safari (iOS 12.0.1) latest

**Comment by mistic100** [comment]
Fullscreen is not supported on iOS https://caniuse.com/#feat=fullscreen  
That why the button his hidden and you have issues if you manually call the method.

**Comment by bigwigal** [comment]
Thanks, Damien. I didn't check iOS support. The button is shown in the latest version though (12.0.1) so I'm assuming it is supported now? I haven't called the API manually, the resize issue is present when the button is visible on both Mac OS X and the latest iOS. Thanks again.

**Comment by mistic100** [comment]
Ok it seems they added fullscreen support on iOS for iPad only.

I keep this issue opened but I cannot do anything.

**Comment by gvdhorst** [comment]
I have the same issue in Google Chrome when setting the browser to full screen mode (F11) before entering the photo sphere viewer's full screen mode.

Tested in Windows 10 and Gnome 3 with the same result.

**Comment by mistic100** [comment]
There is an emulated fullscreen since version 4.
Feel free to open a new issue if needed.
