### ISSUE TITLE
Way of enabling gyroscope

### ISSUE THREAD

**Issue by kaadash** [mistic100/Photo-Sphere-Viewer#233]
Hello!
Firstly thank you for great library. I have problem with way of activating gyroscope. It is hard to extend THREE js object when it is imported using ES6 modules. Is there any reason why it is done this way? I can help to change this but I need to know if you think it is good approach?

**Comment by mistic100** [comment]
Hi,
I don't understand what you want. What is the problem you have ? *What* is "done the way" ?

**Comment by kaadash** [comment]
Is it true that to enable gyroscope we need to extend THREE js object with DeviceOrientationControls field, am I right? Let say that we are using es6 modules and we are importing PhotoSphereViewer:
```import PhotoSphereViewer from 'photo-sphere-viewer';```
Then we are importing three js as we want to extend this:
```import * as THREE from 'three';```
and we want to extend `THREE.DeviceOrientationControls = ....`;
but we cannot extend three js this way as es6 modules behaviour is read-only and we cannot extend three js with DeviceOrientationControls 

and I don't know how to deal with it in this case

**Comment by mistic100** [comment]
DeviceOrientationControls is already declaring itself on the THREE global variable.
https://github.com/mrdoob/three.js/blob/master/examples/js/controls/DeviceOrientationControls.js

I cannot guide you about how to implement this file in a module oriented architecture.
Clearly the THREE examples files are not ready for Webpack and other fancy bundlers, you will probably have to copy and modify it.
