### ISSUE TITLE
Linking another panorama with a marker

### ISSUE THREAD

**Issue by ai-tushar** [mistic100/Photo-Sphere-Viewer#234]
First of all thanks a lot Damien and Jeremy for this wonder piece of library. it great work.
i am trying to use it in my web application.
however i was wondering if there is any functionality available,
1.  to link another panorama to a marker, so clicking on it can move to that panorama with a zoom in animation. 
2. i cant figure out a way to zoom to the max level with a nice animation affect, so it can be smoothly zoomed in.

Thank you in advance.

**Comment by mistic100** [comment]
1.

```js
PSV.on('select-marker', (marker) => {
  if (marker.id === 'goto-pano') {
    PSV.setPanorama('new-pano.jpg', null, true);
  }
});
```

2. There is no build in animation for zoom, you can do it yourself with the animation helper

```js
PhotoSphereViewer.Utils.animation({
  properties: {
    zoom: {start: PSV.getZoomLevel(), end: 100}
  },
  duration: 2000,
  easing: 'inOutQuad',
  onTick: (properties) => {
    PSV.zoom(properties.zoom);
  }
});
```

**Comment by ai-tushar** [comment]
Thank You so much. really helpful :-)

**Comment by mrAceT** [comment]
I think this is exactly what I need, but I cant get the zoom-animation to work?

I get this error:
```
Uncaught TypeError: Cannot read property 'transition' of null
    at Viewer.setPanorama (Viewer.js:454)
    at MarkersPlugin.<anonymous> (test.html:215)
    at MarkersPlugin.trigger (EventEmitter.js:140)
    at MarkersPlugin.__onClick (index.js:936)
    at MarkersPlugin.handleEvent (index.js:215)
    at Viewer.trigger (EventEmitter.js:137)
    at EventsHandler.__click (EventsHandler.js:569)
    at EventsHandler.__stopMove (EventsHandler.js:473)
    at EventsHandler.__onMouseUp (EventsHandler.js:246)
    at EventsHandler.handleEvent (EventsHandler.js:128)
```

I'dd also like to alter the the latitude & longitude (variables in an object where I set the difference)

**Comment by mistic100** [comment]
@mrAceT this is from 2018, check the new API documentation.
Also please do not bumb closed issues.
