### ISSUE TITLE
gyroscope and stereo button, VR, marker dragging, panel width and tooltip

### ISSUE THREAD

**Issue by ai-tushar** [mistic100/Photo-Sphere-Viewer#235]
Hi again,
the more i am digging into this the more i am amazed. really a great piece of work man.
however, 
1. in my initialization i am declaring navbar array as this,
 ```
 navbar: [
    'autorotate', 'zoom', 'download', 'markers', 'gyroscope', 'stereo', 'fullscreen'
]
```
but i dont see any buttons for gyroscope and stereo buttons showing into the navbar
2. how to enable a VR button in nabar ? or should i do it with a manual button ?
3. is there any dragging feature available for markers to change its position ?
4. can i define the panel width ?
5. is it possible to add any call to action button below marker on hover ? i checked that i can add link/buttons in tooltip but it hides immedietly after hoverout from marker. is it possible to keep the tooltip when cursor is on marker or on tooltil itsef ?

thank you so much in advance for your time. :-)

**Comment by mistic100** [comment]
1 & 2. the buttons are enabled only if you have the necessary modules (DeviceOrientationControl and StereoEffect) and on a device with gyroscope support, it can't be tested on desktop

3. No #229 

4. you can do it in CSS

5. use "over-marker" event https://photo-sphere-viewer.js.org/api/module-components.PSVHUD.html#.event:over-marker

**Comment by ai-tushar** [comment]
Thank you very much Damien for all the answers. 
i will test point 1,2 and let you know if i face any problem.

one more thing i remember, is there any compass feature available ? so that we can know which direction we are looking in a panorama

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/api/PhotoSphereViewer.html#.event:position-updated

and use this to create your own display
