### ISSUE TITLE
360 Degree Panoramic? Ghost ?

### ISSUE THREAD

**Issue by rodvay** [mistic100/Photo-Sphere-Viewer#237]
Hello
Very good ghost platform

im need added projets 360 degree panoramic photo

this feature is available ? ghost platform
Thank you

**Comment by mistic100** [comment]
What ? I don't understand anything.

Sent from MailDroid

-----Original Message-----

**Comment by rodvay** [comment]
Sry
does it work ghost.org ( Ghost Platfom )

**Comment by mistic100** [comment]
Ask them

Sent from MailDroid

-----Original Message-----

**Comment by rodvay** [comment]
Ok thank you
