### ISSUE TITLE
自动上传图片预览vr全景，当图片的尺寸为5.8MB的情况下，无法正常预览；文档没看到限制图片尺寸的参数，怎么解决这个问题。

### ISSUE THREAD

**Issue by miean93** [mistic100/Photo-Sphere-Viewer#239]
## Issues guidelines

- **Indicate your Photo-Sphere-Viewer, ThreeJS and web browser versions**
- Please search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

**Comment by mistic100** [comment]
Sorry I don't speak Chinese

Sent from MailDroid

-----Original Message-----
