### ISSUE TITLE
Recover from missing image

### ISSUE THREAD

**Issue by pajamabob** [mistic100/Photo-Sphere-Viewer#241]
When attempting to load an image that does not exist at the path passed to the viewer, it throws an error:

Uncaught PSVError {message: "Cannot load image", stack: "PSVError: Cannot load image↵"}

This makes perfect sense.  

Trying to then pass a valid image path to the viewer results in additional errors:

Uncaught PSVError {message: "Loading already in progress", stack: "PSVError: Loading already in progress↵}

Is there a way to "Reset" the viewer after a failed loading attempt?

Thanks in advance for you time and consideration...

**Comment by mistic100** [comment]
Currently teh viewer DOM is completely destroyed on loading error.
I'll plan this for 4.0.0 which already has a better error management.
