### ISSUE TITLE
Improve heavy pano loading by slice it to many pieces

### ISSUE THREAD

**Issue by mnking** [mistic100/Photo-Sphere-Viewer#243]
## Improve heavy pano loading by slice it to many pieces

- My pano image has 5mb of size, it very slow to load in the first time
- How to improve speed by slice it to many pieces and load it async

**Comment by mistic100** [comment]
The current state of the code is absolutely not ready for this. I cannot tell I will ever do it.

**Comment by cyruscuenca** [comment]
Try tweaking the compression for your image, and then load it into a CDN. That's what I did, and now my panoramas load pretty fast.

You could also pre load the whole panorama on an SPA in the background if you really want the panorama appear instantly.

You should probably close this issue

**Comment by mistic100** [comment]
I don't think so. current implementation is limited by the canvas resolution of the browser #363 whatever is the filesize.

Having multiple slices would allow much higher resolution.

**Comment by mistic100** [comment]
So I have a working code on the `adapters` branch but is has very poor performances.  
It works well for a 6000x3000 panorama with 375x375 tiles (16 columns and 8 rows) but is very slow with a 16384x8192 panorama with 512x512 tiles (theorical limit for the canvas buffers I use).

I think the performance issue is when the updated buffers needs to be uploaded to the GPU.  
I hoped to be able to render highres panoramas with multiple levels of tiling but the approach is just not adapted.

On a side node I found this paid solution with tremedous performances !
https://krpano.com/examples/?multires

**Comment by mistic100** [comment]
I made a new implementation using custom UV mapings (still on the `adapters` branch) and it has excellent performances.
Tested with the same 16384x8192 panorama using 256x256 tiles (2048 tiles in total).
