### ISSUE TITLE
viewer does not resize after parent div width changes

### ISSUE THREAD

**Issue by ai-tushar** [mistic100/Photo-Sphere-Viewer#244]
Hi there,
i have encountered an issue regarding size,
in my webpage, i have a feature to dynamically change the width of the viewer parent div. so when the page loads the viewer will be full screen, and clicking on a button will make the viewer parent div half width of the screen. problem is when parent div became half of the screen, the pano viewer still stays the fill width of the screen.
i have tried the followings after updating the widht of parent div,
`$(window).trigger('resize');` doesnt work.
tried `panoObject.render();` doesnt work.
tried `panoObject.resize({width: 675, height: 500});` doesnt work.

only thing works here is `window.dispatchEvent(new Event('resize'));` which resizes the viewer.
but unfortunately i cannot use it, as it create problems with some other element in my page.

can you suggest me any other way i can resize the viewer ?

Thanks in advance.

**Comment by mistic100** [comment]
Hello,

call the "private" method `_onResize`  
on the next major version this method will be public and documented (and renamed `autoSize`)

**Comment by ai-tushar** [comment]
thank you a quick response.
tried `panoObject._onResize();` but not working.

**Comment by mistic100** [comment]
You will need to setup a demo fo the problem, as asked in the issues guidelines :-)

**Comment by ai-tushar** [comment]
hopelessly i was just trying everything that came to my mind, and suddenly one solution worked,
viewer resize metho worked like this,
```
panorama[element_id].resize({
        width: '300px',
        height: '200px'
 });
```

where 300 and 200 will be relpace with the realtime window heigh and width.

thanks for your quick responses and kind helps Damien. 
will be waiting for the new major version with more features.
