### ISSUE TITLE
Can't initialize?

### ISSUE THREAD

**Issue by romtim** [mistic100/Photo-Sphere-Viewer#247]
I am trying to get it to work, but there are a lot of dependencies and after calling them all in a seemingly correct way, the chrome console shows me no errors and yet it doesn't load the photo sphere correctly.

It fills the div in some way, but its still invisible on the page, and if I remove the display:none's, whats left is just a static image.

http://www.timochenko.com/test-photosphere/

This is the list of files that I'm calling on the page
`		wp_enqueue_style( 'vr-style', '/wp-content/themes/Divi-Child/css/photo-sphere-viewer.min.css' );
		wp_enqueue_script( 'vr-script-1', '/wp-content/themes/Divi-Child/js/three.js', array('jquery') );
		wp_enqueue_script( 'vr-script-2', '/wp-content/themes/Divi-Child/js/doT.min.js', array('jquery') );
		wp_enqueue_script( 'vr-script-3', '/wp-content/themes/Divi-Child/js/uevent.min.js', array('jquery') );
		wp_enqueue_script( 'vr-script-4', '/wp-content/themes/Divi-Child/js/D.min.js', array('jquery') );
		wp_enqueue_script( 'vr-script-5', '/wp-content/themes/Divi-Child/js/photo-sphere-viewer.min.js', array('jquery') );
		wp_enqueue_script( 'vr-script-6', '/wp-content/themes/Divi-Child/js/photosphere-custom.js', array('jquery') );`

**Comment by mistic100** [comment]
You didn't gave any size nor to the container nor the viewer itself, hence the 0px height.

You can either give an height in CSS to the #viewer div or use the "size" option https://photo-sphere-viewer.js.org/#options

**Comment by romtim** [comment]
Thank you, that did it.
