### ISSUE TITLE
Add a remark in the getting started docs section that it's needed to set a height on container or config

### ISSUE THREAD

**Issue by wimhendrikx** [mistic100/Photo-Sphere-Viewer#248]
Afterwards it's obvious that you need to set a height but some can think that the plugin reads the height from the image. By adding a small remark in de "Getting started" docs you can prevent people forgetting this and getting things working faster.

**Comment by mistic100** [comment]
It would make no sense to read the size from the source image... I don't want a 6000*3000 pixels viewer.
Feel free to propose a change to the gh-pages branch, preferably in the "Let's go" example itself.

**Comment by wimhendrikx** [comment]
You could calculate the scale and with that also the height but that would take it too far. It's better this way. I've created a pull request for an extra notice in the docs.

**Comment by mistic100** [comment]
Done
