### ISSUE TITLE
Display issues when detached from the DOM

### ISSUE THREAD

**Issue by bigwigal** [mistic100/Photo-Sphere-Viewer#249]
I've noticed some issues when the viewer is detached from the DOM. I learnt a while back that it was necessary for the target container to be in the DOM, prior to initialisation, for the the panorama to render correctly. However, I've just noticed an issue when a viewer is detached from the DOM, post initialisation, and request fullscreen is called on another element. This results in the panorama of the detached viewer not rendering correctly when it is reattached to the DOM.  I'm assuming that something is happening in response to the fullscreen event. An 'i' button is displayed in the control bar, in both cases, but no message is shown when it is pressed, and resizing the window/opening the developer tools etc. will result in the image being rendered.

A little background... I work for a distance learning university and am using multiple viewers alongside Leaftlet to produce a set of learning materials, packaged up as virtual fieldwork. It all works really well together, and I'm very impressed with both libraries. I realise this is a bit of an edge case though and there are probably good reasons for the viewer needing to be in the DOM during initialisation but it would be good to get a fix for the fullscreen issue, if possible. I'm yet to try calling resize via the API, hopefully that will provide a workaround in the meantime. Thanks again for the library and for your continued support.

**UPDATE:** calling resize does sort the issue. It seems that the width/height on the canvas element are set to zero in both cases mentioned above, and calling getSize at that point returns zero width/height. I've worked around by getting the computed style of the container and passing those values to resize. I'm assuming that it's getComputedStyle that leads to zero values when detached from the DOM.

**Comment by mistic100** [comment]
I will not investigate this issue further. I consider if you need to remove the viewer the DOM you should destroy it.
