### ISSUE TITLE
PSV.rotate not functioning if startGyroscopeControl

### ISSUE THREAD

**Issue by insub** [mistic100/Photo-Sphere-Viewer#250]
Photo-Sphere-Viewer : 3.4.1
Threejs : 0.99.0
Browser: iOS Safari

In fact, what I need to achieve is to set a position when the gyroscope starts up.
Like this issue:
#100 
But unfortunately, PSV.doControls.updateAlphaOffsetAngle method seems to have been Discard

So i try this:
```
PSV.startGyroscopeControl();
PSV.rotate({
   longitude: 2.95,
   latitude: -0.1
 })

```
But still not work.
Any idea?

**Comment by mistic100** [comment]
The rotate method is disabled when the gyroscope is enabled to avoid issues while computing camera direction.

You could try to update `PSV.prop.gyro_alpha_offset` on the `gyroscope-updated` event (not directly after gyro control start) but I don't know what will happen.

**Comment by insub** [comment]
Thank～
It seems that it is more efficient to modify the panorama to fit the initial position of the gyroscope.

**Comment by mistic100** [comment]
What do you mean ? There is no initial position of the gyroscope, it all depends in what direction is your phone when you enable it.

Did you checked the `sphere_correction` option ?

**Comment by mistic100** [comment]
And it should already auto-correct itself to the current view direction.
https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/js/PhotoSphereViewer.public.js#L325-L331
