### ISSUE TITLE
Mouse Wheel not disabled

### ISSUE THREAD

**Issue by JrDabhi** [mistic100/Photo-Sphere-Viewer#261]
**Photo Sphere Viewer: 2.9, ThreeJS: Version 2.3 and web browser Chrome: Version 71.0.3578.98 **
I have used this version of Library:
Add this options:
var viewer = new PhotoSphereViewer({
    container: 'paronoma_image',
    panorama: 'images/media/smart-viewing-video.jpg',
	loading_img: 'images/loader.gif',
	time_anim: false,
	navbar: true,
	touchmove_two_fingers: true,
	mousewheel: false,
	mousemove: false,
	mousewheel_factor: 0,
	autoload: false,
	navbar_style: {
		backgroundColor: 'transparent'
	}
  });

- Mouse wheel false not working for me can you please help me for this thanks

And also i tired latest version of library 3.5.0 but is getting error 
-> Uncaught TypeError: Cannot read property 'mixin' of undefined

**Comment by mistic100** [comment]
Could you provide a demo ?

----

If you get "Cannot read property 'mixin' of undefined" then you forgot to include uEvent in your page

**Comment by mistic100** [comment]
I cannot reproduce on 3.5.0
