### ISSUE TITLE
panorama-load-progress only trigger on progress 100%

### ISSUE THREAD

**Issue by insub** [mistic100/Photo-Sphere-Viewer#262]
Photo Sphere Viewer Version :  3.4.1

my code:
`PSV.on('panorama-load-progress', function(panorama, progress) {
     console.log("progress", panorama, progress)
  });`

I try to execute in the case of an analog 3G network, there is always only one console logs：
“./some.jpg 100”

**Comment by mistic100** [comment]
The load progress event only works when the browser is actually able to compute the download progression (when the server provide the Content-Length header)
https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/lengthComputable

**Comment by nushydude** [comment]
I know this is closed, but I also experience this. My files are coming from Google Cloud Storage, and this is what I see in for the response headers in the Network tab in Chrome dev tools.

![content-length](https://user-images.githubusercontent.com/12478046/78899635-020a7680-7ab9-11ea-93f1-08239cccefc8.jpg)

**Comment by mistic100** [comment]
In any case I do not manage this part of the code, it is directly hooked to XMLHttpRequest. If XHR says the length is not computable there is nothing I can do.
