### ISSUE TITLE
I can't run a simple example of photo-sphere-viewer@4.0.0-alpha.1

### ISSUE THREAD

**Issue by SaulBurgos** [mistic100/Photo-Sphere-Viewer#265]
I am trying to run a simple example of the new version but I am getting the following errors

https://imgur.com/a/x7iGVBw

I have executed this command:   npm install photo-sphere-viewer@4.0.0-alpha.1

Did I miss a dependency ?  Here is my code:

````<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Document</title>
	<link rel="node_modules/photo-sphere-viewer/dist/photo-sphere-viewer/photo-sphere-viewer.min.css" href="styles.css">	
	<script src="node_modules/three/build/three.min.js"></script>	
	<script src="node_modules/uevent/uevent.min.js"></script>	
	<script src="node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.min.js"></script>	
</head>
<body>	
	<div id="viewer"></div>
	<style>
	#viewer {
		height: 400px;
		width: 540px;
		margin: 0 auto;
	}
	</style>

	<script>
		const viewer = new PhotoSphereViewer({
			container: document.querySelector('#viewer'),
			panorama: '360.jpg'
		});
	</script>
</body>
</html>

**Comment by mistic100** [comment]
your CSS link is completely false

you need
```html
<link rel="stylesheet" href="node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.min.css">	
	```

**Comment by SaulBurgos** [comment]
Thanks for the reply, But I think the problem is not about CSS.  I have created a glitch project to show you the problem, please see the developer console the error.

https://sphereviewer.glitch.me/

here the code:

https://glitch.com/~sphereviewer

**Comment by mistic100** [comment]
I just tried your example, it works perfectly if you use a **correct link** for the CSS stylesheet

```html
<link rel="stylesheet" href="photo-sphere-viewer.min.css">	
```

**Comment by mistic100** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

**Comment by SaulBurgos** [comment]
Ohhhh oooohhhh   (╥_╥)    

(ᴗ_ ᴗ。) Sorry I didn't notice the attribute...  thanks for your patience (◍•﹏•)
