### ISSUE TITLE
Caption hidden by default when using setCaption

### ISSUE THREAD

**Issue by Biboba** [mistic100/Photo-Sphere-Viewer#266]
When using setCaption function, it is hidden behind a button though there is plenty of space available:
https://jsfiddle.net/as9c3rwv/

You need to resize the window so that it appears.

But it works on v4 alpha:
https://jsfiddle.net/as9c3rwv/1/

Photo-Sphere-Viewer version: 3.5.0
Three version: 0.97.0
Browser : Chrome Version 71.0.3578.98 (Build officiel) (64 bits)

**Comment by mistic100** [comment]
Actually you shouldn't make call to the API until the viewer is ready

```js
PSV.on('ready', () => {
  PSV.setCaption('Small Caption')
});
```

And if you want to set the caption at startup, use the constructor option.

I won't try to backport the v4 code.

**Comment by Biboba** [comment]
@mistic100 Thanks !
