### ISSUE TITLE
autorotateStartup property does not exist in 4.0.0-alpha.2

### ISSUE THREAD

**Issue by Biboba** [mistic100/Photo-Sphere-Viewer#267]
Photo-Sphere-Viewer version: 4.0.0-alpha.2
Three version: 0.97.0
Browser : Chrome Version 71.0.3578.98 (Build officiel) (64 bits)

autorotateStartup is mentionned is the documentation but it actually does not exist:
https://github.com/mistic100/Photo-Sphere-Viewer/blob/160c89c9dc816cd2081dd7893dca41d21defbce4/v4/index.html#L310

**Comment by mistic100** [comment]
Thank you it's changed.
