### ISSUE TITLE
Pan, tilt, roll issues

### ISSUE THREAD

**Issue by gocebo** [mistic100/Photo-Sphere-Viewer#268]
Photo Sphere Viewer 3.5.1
ThreeJS 99

Although #263 fixed most of the pan, tilt, roll issues, it seems that they are not completely fixed. For example the following image http://www.androidblip.com/download/test.jpg is properly displayed in the Theta viewer and others, but PSV still does not display it properly when setting the correct pan/heading, pitch/tilt and roll sphere corrections.

Here is the raw XMP data:
`
<x:xmpmeta xmlns:x="adobe:ns:meta/" xmptk="RICOH THETA S Ver1.11">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about="" xmlns:GPano="http://ns.google.com/photos/1.0/panorama/">
      <GPano:ProjectionType>equirectangular</GPano:ProjectionType>
      <GPano:UsePanoramaViewer>True</GPano:UsePanoramaViewer>
      <GPano:CroppedAreaImageWidthPixels>5376</GPano:CroppedAreaImageWidthPixels>
      <GPano:CroppedAreaImageHeightPixels>2688</GPano:CroppedAreaImageHeightPixels>
      <GPano:FullPanoWidthPixels>5376</GPano:FullPanoWidthPixels>
      <GPano:FullPanoHeightPixels>2688</GPano:FullPanoHeightPixels>
      <GPano:CroppedAreaLeftPixels>0</GPano:CroppedAreaLeftPixels>
      <GPano:CroppedAreaTopPixels>0</GPano:CroppedAreaTopPixels>
      <GPano:PoseHeadingDegrees>225.0</GPano:PoseHeadingDegrees>
      <GPano:PosePitchDegrees>17.0</GPano:PosePitchDegrees>
      <GPano:PoseRollDegrees>-121.0</GPano:PoseRollDegrees>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
`

Here is a copy of the same image but straightened http://www.androidblip.com/download/test_xmp_e.jpg as a reference how the end result should look like.

**Comment by mistic100** [comment]
I didn't mentioned that the Pose* fields currently are not read from the XMP, for now you need to configure the sphere_correction yourself.

And it works perfectly with the following values :
```js
  tilt: '17deg',
  roll: '-121deg',
  pan: '225deg',
```

**Comment by gocebo** [comment]
The sphere_correction is set manually. Here is a side by side example http://recordit.co/1ECSw19XWU
The first image is the un-straightened raw image (http://www.androidblip.com/download/test.jpg) second one is straightened (http://www.androidblip.com/download/test_xmp_e.jpg). There is a visible difference in how they are displayed. I can upload the test if you like.

**Comment by mistic100** [comment]
I cannot improve it, PhotoSphereViewer passes the provided values directly to the ThreeJS object which I trust to do the correct Euler angles computation.

Are you sure you give the correct values to the sphere_correction ? Because I don't get the same result at all, on my test page the horizon is almost straight.

**Comment by mistic100** [comment]
There is something wrong with 3.5.1 which has been fixed in 4.0.0-alpha.2, I don't know what.

**Comment by gocebo** [comment]
OK will wait for the 4.0.0 official release. Please, make sure you fix the max allowed angles in that one too.  Tried it and it looks like it is producing similar results as pre v3.5.1.

**Comment by mistic100** [comment]
Don't worry it is https://github.com/mistic100/Photo-Sphere-Viewer/commit/bae8c8459c53f39f44fe4736cf961ec56ec96b36
