### ISSUE TITLE
Misc evolutions

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#27]
(most from JeremyHeleine work)
 - [x] allow degrees for latitudes and longitudes
 - [x] viewable longitude range (min & max)
 - [x] public methods for interesting properties
 - [x] panorama size parameter as an XMP fallback
 - [x] add methods to hide the navbar
 - [x] ~~automatically hide the navbar when autorotate/gyroscope~~
 - [x] user move speeds depends on viewer size and zoom
 - [x] load all components in constructor, making all public methods available at init
 - [x] use https://github.com/mistic100/uEvent
 - [x] allow multiple CSS classes for custom buttons and markers
 - [x] get references to buttons
 - [x] method to disable button
 - [x] `updateMarker`  should not alter the input object

**Comment by marcin1337** [comment]
How about marker actions?
meaning if a user clicks a certain marker type he can 

- Open a new tab with URL
- Go to a predefined Scene
- Call a clicked event

**Comment by mistic100** [comment]
It's already possible with the "select-marker" event

**Comment by marcin1337** [comment]
oh ok, do you need any help in these tasks? I would be happy to offer support
