### ISSUE TITLE
hide gridlines in Canvas  mode

### ISSUE THREAD

**Issue by chn121** [mistic100/Photo-Sphere-Viewer#270]
## hide gridlines in Canvas  mode
its shows many gridline when display a panorama jpg in Canvas mode，but display right in webgl mode 。
how to hide the gridline ？
![default](https://user-images.githubusercontent.com/33249837/51718129-d9968800-207e-11e9-93ec-ed1f24d28ef7.png)

**Comment by mistic100** [comment]
You cannot, the CanvasRenderer has been deprecated by ThreeJS and the overdraw option I used to fix this issue completely removed.
