### ISSUE TITLE
PhotoSphereViewer 3.5.1 incompatible with uEvent 2.0

### ISSUE THREAD

**Issue by SudoHenk** [mistic100/Photo-Sphere-Viewer#274]
Installed 3.5.1 of the Photo-Sphere-Viewer in combination of the latest three.js, doT and uEvent (2.0.0) libraries. Tried to load photosphere: OK, but once the auto rotate kicks in, the view rotates down and you cannot normally pan around anymore. I've tried to debug through the code, and found out that the longitude in the auto rotate function results in NaN, which I think causes this unexpected behaviour. I did not see any exception coming by.

Once I've downgraded to uEvent 1.0.0 the problem did not occur anymore.

**Comment by mistic100** [comment]
Yes, that's why the dependency is "~1.0.0" is the package.json :-)

Next major version will use uEvent 2
