### ISSUE TITLE
GPS Lat Long as Marker in Photosphere

### ISSUE THREAD

**Issue by universalmercator** [mistic100/Photo-Sphere-Viewer#275]
Can I display GPS locations (WGS84 lat-long in decimal degrees) on photosphere viewer as a marker?? 

These locations are signboards on the road collected with accurate GPS surveys.
 
The source panoramic images were acquired with accurate surveys and geotagged with GPS locations (WGS84 lat-long).
 
Am using version 3.5.1 of https://photo-sphere-viewer.js.org/.  

I was under the impression three.js support this but not sure.
 
Any help or ideas much appreciated. Thanks.

**Comment by mistic100** [comment]
PhotoSphereViewer has no concept of GPS coodinates.
any "longitude" and "latitude" found everywhere in the docs are strictly related to the ThreeJS sphere holding the texture.

(long=0, lat=0) and (long=360, lat=0) are equals and in the center of source image, directly in front of the 
camera on init  
positive lattitudes are up, and positive longitudes are on the right.

Nothing more.

**Comment by mrAceT** [comment]
Is there any update / workaround to this topic now?
