### ISSUE TITLE
fisheye - not good-looking fisheye view - how to minimize it?

### ISSUE THREAD

**Issue by marcinzmyslowski** [mistic100/Photo-Sphere-Viewer#277]
- Firefox & Chrome and I suppose all other web browsers
- my code:
<script>
  var PSV = new PhotoSphereViewer({
    panorama: "http://www.kolekcja.zmyslowski.pl/zdjeciagooglepicasa/o118736.jpg",
    container: 'photosphere',
    caption: "2019-03-31 - lot dronem na cmentarzem w Osielsku na ul Lawendowej 10 - panorama sferyczna 2 - Marcin Zmyslowski",
    loading_img: "https://photo-sphere-viewer.js.org/assets/photosphere-logo.gif",
    navbar: 'autorotate zoom download caption fullscreen',
    default_fov: 70,
    default_lat: 0.3, 
    mousewheel: false,
	fisheye: 0,
    touchmove_two_fingers: true,
    size: {
      height: 800
    }
  });
</script>

Question:
How to eliminate not good-looking fisheye view from my 360 panorama photo?
Here is a link:
http://www.kolekcja.zmyslowski.pl/index.php?id_page=otworz&nazwa_galerii=2019-03-31+-+lot+dronem+na+cmentarzem+w+Osielsku+na+ul+Lawendowej+10+-+panorama+sferyczna+2&widok=pojedyncze

Is it possible with your API or how to minimize this fisheye effect? This drone photo is not fisheye, so I don`t know why it presents as fisheye.
Maybe it is possible to present this photo as it is, I mean without curved horizon.

Kindest regards
Marcin

**Comment by mistic100** [comment]
The horizon must be in the center of the image, your's is not http://www.kolekcja.zmyslowski.pl/zdjeciagooglepicasa/o118736.jpg

You must manually edit it with a photo manipulation software, PhotoSphereViewer cannot correct this.

**Comment by mistic100** [comment]
It looks like your photo has been cropped on the top, equirectangular images must have 2:1 ratio, you can add white on the top to do so.

**Comment by mistic100** [comment]
You can also provided cropping data, it looks good with a 900px top offset (but it's filled with black).
Use this page to test it out https://photo-sphere-viewer.js.org/crop.html
