### ISSUE TITLE
I don't know how to deploy this script

### ISSUE THREAD

**Issue by TomHsiung** [mistic100/Photo-Sphere-Viewer#278]
Hello,

The information about how to use this script is two simple for non-coders. Can you share how to deploy this script to the web server?

I even don't know what files should I upload to my web server.

Regards,

Tom

**Comment by mistic100** [comment]
Hello,

I cannot help you, there are innumerable ways to install and use any JS library to a server and I don't have time to assist you from scratch.

The files you need are the dependencies listed on the documentation and the two minified files https://github.com/mistic100/Photo-Sphere-Viewer/tree/master/dist

It might be a good idea to read the example too https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/example/equirectangular.html
