### ISSUE TITLE
Several panorams on one page

### ISSUE THREAD

**Issue by Stigie** [mistic100/Photo-Sphere-Viewer#282]
I trying to add several viewer on one page, they show on page, but correctly work only one. Example: https://test.ilyaeliseev.ru/proekty-domov/panoram360

**Comment by mistic100** [comment]
None of your viewers are working, both have the same issue and cannot be moved.

Please create a minimal reproduction on another page. (with only one viewer).

**Comment by mistic100** [comment]
BTW if you are displaying viewers like that you should set `mousewheel: false` in order to not block the scrolling in the page.

**Comment by Stigie** [comment]
@mistic100 
> None of your viewers are working, both have the same issue and cannot be moved.
> 
> Please create a minimal reproduction on another page. (with only one viewer).

Example with only viewer: http://web-flagman.ru/photo-sphere-viewer/

**Comment by mistic100** [comment]
Can you not use minified JS files ? I cannot debug

**Comment by mistic100** [comment]
BTW I cannot reproduce on my machine, I created a simple page with the same photos and same layout and it's working perfectly.
Hence the need to debug directly on your page.

**Comment by Stigie** [comment]
@mistic100 I added not minified JS file. What libraries and what version do you use?

**Comment by mistic100** [comment]
Your problem is your version of uEvent, you are using version 2 but it's not compatible
https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/package.json#L20

**Comment by Stigie** [comment]
Thanks!
