### ISSUE TITLE
add fixed text inside the polygon mark

### ISSUE THREAD

**Issue by yoyomule** [mistic100/Photo-Sphere-Viewer#287]
Thank you very much for your project. We are actively testing and it feels great. There are a few feature suggestions and I hope to be useful for your continued development.
1. After adding the polygon mark, I hope to add the fixed display text inside the area, so that it is easy to know what the area is, and the text size is expected to be able to be adjusted.
2. Is it supported to play panoramic video? In addition, can you add a model supports inside, such as obj, gltf format.
Thanks.
![text](https://user-images.githubusercontent.com/10000818/56879101-ccc46e80-6a89-11e9-983e-748afcfb754e.png)

**Comment by solo114114** [comment]
This idea is good, I hope to achieve it.

**Comment by mistic100** [comment]
You can compute the centroid of your polygon and add a text marker at said position. I won't add a feature as you described it.

----

Video support is WIP https://github.com/mistic100/Photo-Sphere-Viewer/issues/128 I cannot tell you when it will be done.

----

There won't be any support for 3D models, this is clearly not the goal of this lib.
