### ISSUE TITLE
setParanoma function missing

### ISSUE THREAD

**Issue by nichthinkof30** [mistic100/Photo-Sphere-Viewer#29]
Hi, as I saw in the example, there is an implementation of setParanoma, however, when I tried to implement, this method is missing..

PSV.setPanorama()

Do we need to include any specific js to get this?

Thanks! @mistic100

**Comment by mistic100** [comment]
Run «grunt» command, the development version is bit builded

**Comment by nichthinkof30** [comment]
Thanks @mistic100, I just found out, there are two different versions, 3.2 and 3.1, everything works fine on 3.1 except setPanorama ..After I changed to 3.2 version, it did display the image, but it don't show my markers anymore and the loading image also seems goes wrong..any idea?

**Comment by mistic100** [comment]
It's a dev version, still work in progress.

**Comment by nichthinkof30** [comment]
I see, from current version 3.1, if I want to replicate the similar functionality of setPanorama(), I need to use destroy ?
