### ISSUE TITLE
A tour system 

### ISSUE THREAD

**Issue by micker** [mistic100/Photo-Sphere-Viewer#290]
hello its possible to create a tour system ? to jump to an other panorama like enter in house ?
regards

**Comment by mistic100** [comment]
Use markers to create clickable zones and call "setPanorama" to change the image. 

I have an early WIP with advanced options here https://github.com/mistic100/Photo-Sphere-Tour
but it is absolutely not finished.

**Comment by micker** [comment]
ok for now its not usuable ..

**Comment by mistic100** [comment]
But as I said you can do it yourself, there is nothing complex if you read carefully the doc and the example file.

**Comment by micker** [comment]
yes i will try ... after find how to install it lol doesn't have any experience with npm on windows ...
