### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by micker** [mistic100/Photo-Sphere-Viewer#291]
hello sorry for this light newbe question but i don't understand why when i use example files that doesn't work .... you zip seams isn't complet ...
can you explain more ?
reagrds

**Comment by mistic100** [comment]
you need to install NPM and run "npm install" in the folder to get dependencies

easy to spot if you open the browser console and see a bunch of 404 errors on "node_modules" files

**Comment by micker** [comment]
ok i will try to find ressource for windows dev ...
regards

**Comment by micker** [comment]
no way to have a small package with only file for testing i try to deploy simply in web site ?

**Comment by mistic100** [comment]
no

the fact is, in 2019, if you don't know how to use NPM, you are closing yourself a lot of gates  
and also I don't want to do this work for you :-)

**Comment by mistic100** [comment]
and also what's the big deal ? you just have to install Node from official website, it comes fully configured with NPM in the path an ready to use.

**Comment by micker** [comment]
yes yes my first try is incomplete ... need more work lol
