### ISSUE TITLE
Lite version

### ISSUE THREAD

**Issue by ds-car-3d** [mistic100/Photo-Sphere-Viewer#292]
The features I need are sometimes very simple, such as a simple panorama display, but PhotoSphereViewer looks bloated. Is it possible to post a streamlined version, I think someone needs it. Discard all dependencies or they are optional.

**Comment by mistic100** [comment]
The only big dependency is three js and it's not optional.

I will not provide a "lite" version. (Whatever this means because the extra features do not represent the biggest part of the code)
