### ISSUE TITLE
How best to determine when a new sphere is loaded?

### ISSUE THREAD

**Issue by mycobiont** [mistic100/Photo-Sphere-Viewer#293]
I have code to jump from one photosphere to another, which uses setPanorama() to load the next sphere.  I also have some code to overlay some information with addMarker() and to rotate the new sphere in a different direction with animate().  The problem is that setPanorama() runs a promise that downloads the new photosphere file - if that file is slow to download, it is visually clear that the new markers get drawn onto the old photo and then the rotation animation runs.  I would like to delay those until after the new file is fully downloaded and rendered.  

While I would think that the PSV.on('ready', __) event would be the way to detect when the new photosphere download and rendering is completed, it appears that this is not the case.  I find that 'ready' fires well before the new file is downloaded (promise complete).

Any recommendations on a property I can watch for, or some other solution?

Thanks!   --- using PSV v3.5.1, Three v97

**Comment by mycobiont** [comment]
I think I hacked my way through this issue.  Apparently 'ready' is only triggered when the PSV framework has loaded.  If one uses setPanorama(), 'ready' is not triggered again.  However, 'panorama-loaded' is triggered (after the new image is in the viewer).  Just what I wanted!

**Comment by mistic100** [comment]
As you said "setPanorama" returns a promise. Why not subscribing to this promise ?

It's is the same as the "panorama-loaded" event. Use the solution that most suits you.
