### ISSUE TITLE
PSV not rendering on Chrome until changing zoom of browser

### ISSUE THREAD

**Issue by kylclrk** [mistic100/Photo-Sphere-Viewer#297]
**Versions:**
Photo-Sphere-Viewer@3.5.1
ThreeJS@0.105.2
Chrome@74.0.3729.169

I was having trouble with this and couldn't figure out why the example code wasn't working. After trying it in Edge, it finally worked. When I went back to chrome, I decided to change the browser zoom (was on default 100%). After adjusting the zoom of the browser, PSV rendered the image. I then reset back to the default zoom of 100% and it was still rendering. 

I tried adding my code to Plunker and JSFiddle, but I'm not sure how to replicate my babel/webpack configuration on there. 

Here's my code:

**index.js**
~~~~
import PhotoSphereViewer from 'photo-sphere-viewer';
import photospherecss from 'photo-sphere-viewer/dist/photo-sphere-viewer.min.css';

document.addEventListener('DOMContentLoaded', e => {
    const view = document.querySelector('#viewer');
    new PhotoSphereViewer({
        container: view,
        // panorama: '/public/img/photospheres/PANO_QC.jpg',
        panorama: 'https://raw.githubusercontent.com/mistic100/Photo-Sphere-Viewer/master/example/Bryce-Canyon-National-Park-Mark-Doliner.jpg',
        size: {
            width:500,height:300
        }
    });
});
~~~~

**index.html**
~~~~
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PSV</title>
</head>
<body>
<div id="viewer"></div>
</body>
</html>
~~~~

**package.json**
~~~~
{
...
  "scripts": {
    "build": "webpack --config webpack/webpack.config.prod.js  --colors",
    "start": "webpack-dev-server --open --config webpack/webpack.config.dev.js"
  },
  
...

  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/preset-env": "^7.4.2",
    "babel-loader": "^8.0.5",
    "clean-webpack-plugin": "^2.0.2",
    "copy-webpack-plugin": "^5.0.3",
    "css-loader": "^2.1.1",
    "eslint": "^5.16.0",
    "eslint-loader": "^2.1.2",
    "file-loader": "^3.0.1",
    "html-webpack-plugin": "^4.0.0-beta.5",
    "mini-css-extract-plugin": "^0.6.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.2.1",
    "webpack-merge": "^4.2.1"
  },
  "dependencies": {
    "@babel/polyfill": "^7.4.0",
    "core-js": "^3.0.1",
    "dot": "^1.1.2",
    "photo-sphere-viewer": "^3.5.1",
    "promise-polyfill": "^8.1.0",
    "three": "^0.105.2",
    "uevent": "^2.0.0"
  }
}
~~~~

I hope this is enough information to go off of. Sorry about not having a JSFiddle or Plunker.

**Comment by kylclrk** [comment]
I tried with and without the 'DOMContentLoaded' event. Didn't make a difference. Also tried with local image. Still same effect.

**Comment by kylclrk** [comment]
Another quick note: the example PSV on your website works with no issues in my browser.

**Comment by kylclrk** [comment]
In the dependencies on the website, you list Three JS + example files. Having the npm module installed should be good enough to meet that requirement, correct?

I only ask because I'm thinking this might be a Three JS problem.

**Comment by mistic100** [comment]
To create a codepen/jsfiddle you have to add the JS and CSS files in the ressources from a CDN (jsDelivr for example) and write you code as you currently do. There is not webpack involved.

---

Has explained in the doc you need to add some ThreeJS examples files depending on your needs, those are NOT included in the main module.

---

If you cannot provided a reproductible example and you do not encounter the issue on the demo, I don't know what I can do for you...

**Comment by SLMNBJ** [comment]
I'm having a similar problem with webpack and dynamic import. PSV render the image only when I resize the window.

**Comment by SLMNBJ** [comment]
Using requirejs to import files from cdn works correctly.
