### ISSUE TITLE
Not working on iPad/iOS 8 and Safari 8/Chrome

### ISSUE THREAD

**Issue by enlewof** [mistic100/Photo-Sphere-Viewer#3]
Hi,

iOS isn't loading the photo sphere correctly.  I think these warnings I found on the Safari Web Inspector might have something to do with it.

[Warning] WebGL: INVALID_VALUE: texImage2D: no canvas (three.min.js, line 522)
[Warning] WebGL: INVALID_OPERATION: generateMipmap: level 0 not power of 2 or not all the same size (three.min.js, line 522)

Let me know if you need more info.

**Comment by mistic100** [comment]
can you replace the body of this function by `return false` and give it a try https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/dist/photo-sphere-viewer.js#L1269-L1270

It just an hint, I don't have any Apple product so if there is a solution someone else will have to find it.

**Comment by RamonSmit** [comment]
I will take a look on this one.

**Comment by jeffreyvandenbossche** [comment]
Have anybody found a solution for this problem ?

**Comment by ragcsalo** [comment]
Finger scrolling and zooming not working on iOS8 (iPhone 5C). Any ideas why?
