### ISSUE TITLE
goToMarker bug

### ISSUE THREAD

**Issue by Kevinveneman** [mistic100/Photo-Sphere-Viewer#302]
There is an issue in the goToMarker function.

When i run the function for 'marker_1' the viewer rotates to the position of the marker. When i run the function again, without changing something to the viewer, it results in an error. 

Error message: PSVAnimation.resolve is not a function

It has something to do with this part.

```
// if no animation needed
  if (!duration) {
    if (positionProvided) {
      this.rotate(options);
    }
    if (zoomProvided) {
      this.zoom(options.zoom);
    }

    return PSVAnimation.resolve();
  }
```

**Comment by DaveGold** [comment]
I have it also. I have prevented it by not navigating to same position twice.

**Comment by DaveGold** [comment]
Added a PR https://github.com/mistic100/Photo-Sphere-Viewer/pull/322 to fix this issue. It seems it was trying to return a promise resolve from undefined object

**Comment by mistic100** [comment]
This is resolved in Photo Sphere Viewer 4
