### ISSUE TITLE
Black overlay before rendering the image

### ISSUE THREAD

**Issue by adamolkin** [mistic100/Photo-Sphere-Viewer#303]
** Using PSV 3.5.1**
There is a brief black overlay just before the rendering of the image. You can see it directly from the viewer in your example [https://photo-sphere-viewer.js.org/ ](https://photo-sphere-viewer.js.org/ ). It can be an aesthetic problem for some. Where does it come from and is it possible to remove it? I noted this wasn't occurring in my previous 3.2.4 version. Thanks

**Comment by mistic100** [comment]
Yes I see it, it's possible the scene is renderer without texture for one frame (because of the new render manager introduced in 3.4.0)

**Comment by mistic100** [comment]
Will be fixed in Photo Shere Viewer 4
