### ISSUE TITLE
Cannot make the Cubemap feature work at all.

### ISSUE THREAD

**Issue by adamolkin** [mistic100/Photo-Sphere-Viewer#310]
**Photosphere version 3.5.1**

I tried my best but can't make the cubemap working. Did the build with several releases to be sure but still cannot be able to get a result on the example cubemap.html

You can find here the JS fiddle : https://jsfiddle.net/Lmzxf81y/9/

But I precise that the I did also the build on local following the `npm install`directions on the `readme.md` and get the same result whereas the equirectangular.html example works perfectly.

What am I missing?

**Comment by adamolkin** [comment]
Up :)

**Comment by laoruiwen** [comment]
+1

**Comment by mistic100** [comment]
This is a problem with THREE.js above version 97  
with 97 it works https://jsfiddle.net/mistic100/0ghqy9s4/3/

It will be fixed in Photo Sphere Viewer 4

**Comment by mistic100** [comment]
I backported the fix in version 3.6.0 which should support newer versions of THREE.js
