### ISSUE TITLE
.destroy() error: this.parent.removeChild is not a function

### ISSUE THREAD

**Issue by MasonChinkin** [mistic100/Photo-Sphere-Viewer#313]
Hi, in version `3.5.1` I'm getting the error below when calling `.destroy()`. I have tried using `new` and not. I have tried using the `parent` option and not. Any ideas? I'm using the React pattern I found here: https://stackoverflow.com/questions/56298812/photo-sphere-viewer-on-react-pure-javascript

<img width="470" alt="Screen Shot 2019-09-09 at 4 34 37 PM" src="https://user-images.githubusercontent.com/32528966/64573353-e327e400-d31f-11e9-9002-75e8ad41144d.png">

My code
```javascript
import React from 'react';
import PhotoSphereViewer from 'photo-sphere-viewer';
import 'photo-sphere-viewer/dist/photo-sphere-viewer.min.css';

export default class Photo360 extends React.Component {
  constructor(props) {
    super(props);

    this.sphereDiv = element => {
      this.photoSphereViewer = element;
    };

    this.sphereDiv.appendChild = (elem) => {
      this.subDiv.appendChild(elem);
    };
  }

  componentDidMount() {
    this.viewer = PhotoSphereViewer({
      parent: this,
      container: this.sphereDiv,
      panorama: this.props.src,
      navbar: [
          'autorotate',
          'zoom',
          'fullscreen'
      ],
      min_fov: '25',
      max_fov: '90',
      default_fov: '45'
    });
  }

  componentWillUnmount() {
    this.viewer.destroy();
  }

  render() {
    return (
      <div className='photo360-wrapper' ref={this.sphereDiv} >
        <div className='photo360' ref={node => { this.subDiv = node; }}/>
      </div>
    );
  }
```

**Comment by mistic100** [comment]
`parent` is supposed to be an HTML Element, not a React Component

I don't know React but in Angular you would inject ElementRef et use `this.elementRef.nativeElement`

**Comment by mistic100** [comment]
you must use `this.photoSphereViewer` (HTML Element) as container, not `this.sphereDiv` (Ref callback)

**Comment by mistic100** [comment]
and `parent` is not a supported option

**Comment by MasonChinkin** [comment]
Thank you! As you said, I needed the HTML element that `this.photoSphereViewer` was held in. My working `componentWillUnmount()` is

```Javascript
componentWillUnmount() {
    this.viewer.parent = this.photoSphereViewer.firstChild;
    this.viewer.destroy();
  }
```
