### ISSUE TITLE
Smallest html code to run Photo Sphere Viewer V4

### ISSUE THREAD

**Issue by lamazze** [mistic100/Photo-Sphere-Viewer#316]
Hello,

I'm trying to create the simpliest working example html code using Photo-Sphere-Viewer.
I don't use any development tool, just Notepad++.
I'll describe the step I've followed as explained in the v4 page:
- Download latest Photo-Sphere-Viewer (4.0.0-alpha.2)
- Download latest Three (0.108.0)
- Download latest uEvent (2.0.0)
- Download latest NoSleep (0.9.0)
- Download all files linked in the v4 page (CanvasRenderer.js, Projector.js, DeviceOrientationControls.js, StereoEffect.js)
- In the html source I load Three, uEvent, NoSleep, the examples from Three then Photo-Sphere-Viewer in that order.
The rest of the code is taken from the example from the v4 page.

You can test the page here: https://www.be-smartr.com/test/

It loads fine for me (Windows 10 + latest Firefox, Samsung S8 + Samsung browser). However, I see these errors in the console (sorry it's in french for the first one):

- L’utilisation du capteur d’orientation n’est plus permise. photo-sphere-viewer.min.js:7:11531
- THREE.Material: .overdraw has been removed. three.min.js:949:503
- THREE.MeshBasicMaterial: 'overdraw' is not a property of this material. three.min.js:482:172

Maybe related or not: once I click on the full screen button, the viewer turn blank. And the viewer seems to be dead.
Maybe related or not: on my S8, I don't have gyroscope support.

I've tried to be as precise as possible but don't hesitate to request more information if needed.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PhotoSphereViewer</title>
  <link rel="stylesheet" href="dist/photo-sphere-viewer.min.css">
</head>
<body>

<div id="viewer"></div>

<script src="dist/three.min.js"></script>
<script src="dist/browser.js"></script>
<script src="dist/NoSleep.min.js"></script>
<script src="dist/DeviceOrientationControls.js"></script>
<script src="dist/StereoEffect.js"></script>
<script src="dist/CanvasRenderer.js"></script>
<script src="dist/Projector.js"></script>
<script src="dist/photo-sphere-viewer.min.js"></script>

<style>
  #viewer {
    width: 95vw;
    height: 95vh;
  }
</style>
<script>
  const viewer = new PhotoSphereViewer({
    container: document.querySelector('#viewer'),
    panorama: '351ee7c366e7_equirectangular_16384.jpg'
  });
</script>

</body>
</html>
```

Any help would be appreciated.

BR,

lamazze

**Comment by mistic100** [comment]
None of these warnings are relevant :
- deviceorientation is deprecated by Mozilla but not removed because there are no viable alternatives https://www.fxsitecompat.dev/en-CA/docs/2018/various-device-sensor-apis-are-now-deprecated/
- THREE overdraw is deprecated but I keep it for people using old versions of THREE

----

For your fullscreen issue I don't know what is appenning, I woulnd't be able to debug it for now.

**Comment by lamazze** [comment]
Thank you Damien.
I've found out the origin of the problem.

In the equirectangular example html (found here: https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/example/equirectangular.html), instead of loading uevent.js it loads browser.js. That caused the update problem.

For the gyroscope problem, I've found out you have to enable it once the viewer is loaded.
