### ISSUE TITLE
how to display images from Insta360 Air ?

### ISSUE THREAD

**Issue by alansaviolobo** [mistic100/Photo-Sphere-Viewer#318]
I have an  [insta360 Air](https://www.insta360.com/product/insta360-air/) and I get images like the type I have attached to this issue. The images are originally in the .insp format.

I was wondering what steps I have to take to get those to display correctly in Photo-sphere-Viewer
Currently, If I just convert it to .jpg and use it in the viewer, the top and bottom show a black void and the borders are also evident.

![IMG_20191011_131102_021](https://user-images.githubusercontent.com/1202289/67064043-8cb38e00-f186-11e9-89d9-17444c49fc19.jpg)

**Comment by mistic100** [comment]
You need to convert them to equirectangular projection or to a cubemap, the only formats supported by PSV.

This is what an equirectangular image looks like 
![](https://photo-sphere-viewer.js.org/assets/Bryce-Canyon-National-Park-Mark-Doliner.jpg)

I don't know how to do it.

**Comment by alansaviolobo** [comment]
Thanks for your inputs.
Can you tell me what my image is called ? I cant find the name of that and hence unable to figure out how to convert it.

**Comment by mistic100** [comment]
I don't know sorry.
