### ISSUE TITLE
D is not a function

### ISSUE THREAD

**Issue by jdbuild** [mistic100/Photo-Sphere-Viewer#32]
When including three.js and trying to run the basic example provided i get the following error in Firefox and Chrome Debug TypeError: D is not a function (photo-sphere-viewer.js:2255)
Uncaught TypeError:  D is not a function
	S.deviceOrientationSupported = D();

The only includes in the example/index.html look like this 
  <link rel="stylesheet" href="../dist/photo-sphere-viewer.css">
  <script src="../threejs/three.min.js"></script>
  <script src="../dist/photo-sphere-viewer.js"></script>

Any suggestions much appreciated, best Jakob

**Comment by mistic100** [comment]
Run "bower install" or manually get https://github.com/malko/D.js
