### ISSUE TITLE
Any chance to include it in a Bootstrap TABS?

### ISSUE THREAD

**Issue by jmartinvamos** [mistic100/Photo-Sphere-Viewer#321]
I want to include this 360º photo sphere inside a bootstrap TAB, But it seems that the photosphere div does not load if the tab is not active.

**Comment by mistic100** [comment]
Please provide a demo of your problem.

**Comment by jmartinvamos** [comment]
Hi!!! I've got the problem here: http://www3.vamos.es/fiat-ibiza/

If you scroll to the 360º tabs, the second one is the container of the photosphere canvas, if you resize your browser it will show up.

Thanks

**Comment by mistic100** [comment]
The viewer cannot init when hidden because hidden elements have no size.

You must call `viewer._onResize()` once the tab is visible.

**Comment by jmartinvamos** [comment]
@mistic100 thanks for your quick reply, my javascript skills are poor, where do I have to include the:
viewer._onResize()
???

Thanks, I appreciate your help.

**Comment by mistic100** [comment]
Once the second tab is displayed, I don't how your page is done so I cannot tell you.

**Comment by jmartinvamos** [comment]
Do you have an example of how things must be done?

I have bootstrap tabs but I don´t know if viewer._onResize() must be place in the photospher javascript or in the tab javascript:

My code:


								<ul class="nav nav-tabs" role="tablist">
									<li role="presentation" class="active"><a href="#360ext" aria-controls="360ext" role="tab" data-toggle="tab">Vista 360º Exterior</a></li>
									<li role="presentation"><a href="#360int" aria-controls="360int" role="tab" data-toggle="tab">Vista 360º Interior</a></li>
								</ul>
							
								
								<div class="tab-content">
								  <div role="tabpanel" class="tab-pane fade in active" id="360ext">
										<?php the_field ('shortcode_exterior'); ?>
								  </div>
								  <div role="tabpanel" class="tab-pane fade" id="360int">
										<div id="photosphere"></div>
								  </div>
								</div>

Thanks

**Comment by mistic100** [comment]
No I don't have and example, sorry I cannot help you to integrate Bootstrap.

Check the doc about events https://getbootstrap.com/docs/4.0/components/navs/#events you need to listen the "shown.bs.tab" event and call PSV resize moethod from here.
