### ISSUE TITLE
No output 

### ISSUE THREAD

**Issue by jdbuild** [mistic100/Photo-Sphere-Viewer#33]
Probably a newb question but i installed dependencis with bowser and put all data on a LAMP environment (cross origin prevention). The output of example/index.htm only shows this [1] in Chrome an Firefox. No error / debug messages in console. Do you have any suggestions? if this causes inconvenience please close issue

best [1]
http://jdoppler.students.fhstp.ac.at/_projects/photosphere/example/

**Comment by mistic100** [comment]
Did you build the lib ?
"$ grunt"

**Comment by jdbuild** [comment]
No i just the prebuilt versions in /dist. I thought this would be fine. I will try to do that.

**Comment by mistic100** [comment]
The build files are for 3.1.0, the example file is for 3.2.0 snapshot (current code in master)

**Comment by jdbuild** [comment]
Thank you this can be closed.

**Comment by mistic100** [comment]
You can do it yourself :-)

**Comment by jdbuild** [comment]
Ok, i found the button now. I should read on github i guess. Think before post :) Thank you again.
