### ISSUE TITLE
Prevent from loading and viewing regular non-spherical image

### ISSUE THREAD

**Issue by avnermosh** [mistic100/Photo-Sphere-Viewer#333]
Hi,

Is there a way to detect regular image from spherical image, before loading and viewing the image in photo-sphere-viewer

Currently, if I replace the spherical [image](https://cdn.rawgit.com/mistic100/Photo-Sphere-Viewer/3.1.0/example/Bryce-Canyon-National-Park-Mark-Doliner.jpg) in [here](https://codepen.io/bramus/pen/yeWJwN)

with a regular [image](https://i.imgur.com/jpbgBC9.jpg) see [here](https://codepen.io/avnerm/pen/vYERvqK)
The regular image is shown distorted (as expected)

**Is there an option to detect that this is not a sperical image and alert the user that this image is not fit for this viewer?**

**Also, is there a way to load a local file, e.g. replace [this](https://cdn.rawgit.com/mistic100/Photo-Sphere-Viewer/3.1.0/example/Bryce-Canyon-National-Park-Mark-Doliner.jpg) image with a local copy file (that was downloaded properly with all the original metadata)
file:///home/user/mages/Bryce-Canyon-National-Park-Mark-Doliner.jpg ?**

Thanks,
Avi

----------------------

photo-sphere-viewer version 3.5.1
three.js version 112
Firefox 71.0 (64-bit)

**Comment by mistic100** [comment]
There no technical difference between an actual photosphere and a regular image, not even the ratio because cropping metadata can be added.

---

What do you mean "load a local file" ? What is your usecase ? If you are running a website and you want users to load their own images you need to use an `input [type=file]`, get the File object, load it in a canvas to get the image data, and give the base64 data as input to the viewer.

I will not explain further there are very good resources online explaining this.

**Comment by avnermosh** [comment]
> There no technical difference ...

I am referring to the exif tags that can identify the image as being fit to be rendered with.
For example, running the exiftool utility to the following example image, shows that it is has an equirectangular projection and thus fit for display using the photo-sphere-viewer.

```
exiftool 360_image_instas360Pro.jpg
...
Camera Model Name               : Insta360 Pro
Use Panorama Viewer             : True
Projection Type                 : equirectangular
```

A "regular" (with no projection) image will not have this field, and so the photo-sphere-viewer can possibly distinguish between "regular" and "non-regular" image and notify the user if the image is not fit to be displayed.

Thanks

**Comment by mistic100** [comment]
This is not always the case, the sphere I am sticking manually don't have this field.

I don't want to add such option in the lib. Its aim is to just be a viewer.

**Comment by avnermosh** [comment]
Ok, thanks for the information.
