### ISSUE TITLE
gyroscope not work?

### ISSUE THREAD

**Issue by im-zhangxi** [mistic100/Photo-Sphere-Viewer#335]
I use it in vue.
my code: 
index.html
`
    <script src="three.min.js"></script>
    <script src="DeviceOrientationControls.js"></script>
`
Component:

`
    import PhotoSphereViewer from 'photo-sphere-viewer'
    import 'photo-sphere-viewer/dist/photo-sphere-viewer.css'

    export default {
        name: 'three',
        data() {
            return {
                factoryLink: 'xx/common/48.png'
            }
        },
        methods: {
            initPhotoSphere() {
                let viewer = document.getElementById('viewer');
                let viewerHeight = parseFloat(getComputedStyle(viewer).height);
                let maxHeight = window.innerHeight;
                let height = parseFloat(maxHeight - viewerHeight) + 'px';
                let PSV = new PhotoSphereViewer({
                    container: document.getElementById('viewer'),
                    panorama: "xx/common/48.png",
                    size: {
                        width: '100%',
                        height: height
                    },
                    caption: '',
                    time_anim: false,
                    sphere_correction: {pan: 30.01, tilt: 0, roll: 0},
                    default_position: {long: 90, lat: 90},
                    default_fov: 179,     // 默认缩放值，在1-179之间
                    zoomRangeWidth: 1,
                    navbar: [
                        'autorotate',
                        'zoom',
                        'caption',
                        'gyroscope',
                        'fullscreen',
                    ],
                    //按钮提示
                    lang: {
                        autorotate: 'Automatic rotation',
                        zoom: 'Zoom',
                        zoomOut: 'Zoom out',
                        zoomIn: 'Zoom in',
                        fullscreen: 'Fullscreen',
                        gyroscope: 'Gyroscope'
                    },
                    theta_offset: 1000, // 旋转速度
                    fisheye: true,
                    //  启用陀螺仪
                    gyroscope: true,
                });
                PSV.on('ready', function () {
                    setTimeout(function () {
                        PSV.startGyroscopeControl();
                    }, 2000);
                });
            }
        },
        mounted() {
            // THREE.DeviceOrientationControls
            console.log(THREE)
            this.initPhotoSphere();
        },
`
![image](https://user-images.githubusercontent.com/18593080/72696156-2750ae00-3b76-11ea-9127-f5a496b77ec9.png)

For help.

**Comment by mistic100** [comment]
What does "not working" means ? What happens ? What is your device, browser, etc ?

(Is it so hard to fill a proper issue ...)

Sent from MailDroid

**Comment by im-zhangxi** [comment]
import DeviceOrientationControls of success

Available on Android phones. ios not work.

`
  import * as THREE from 'three';
    import dc from 'three-device-orientation';
    import PhotoSphereViewer from 'photo-sphere-viewer'
    import 'photo-sphere-viewer/dist/photo-sphere-viewer.css'

    export default {
        name: 'three',
        data() {
            return {
                factoryLink: 'https://iddd.oss-cn-shanghai.aliyuncs.com/common/48.png'
            }
        },
        methods: {
            initPhotoSphere() {
                let viewer = document.getElementById('viewer');
                let viewerHeight = parseFloat(getComputedStyle(viewer).height);
                let maxHeight = window.innerHeight;
                let height = parseFloat(maxHeight - viewerHeight) + 'px';
                let PSV = new PhotoSphereViewer({
                    container: document.getElementById('viewer'),
                    panorama: "https://iddd.oss-cn-shanghai.aliyuncs.com/common/48.png",
                    size: {
                        width: '100%',
                        height: height
                    },
                    caption: '',
                    time_anim: false,
                    sphere_correction: {pan: 30.01, tilt: 0, roll: 0},
                    default_position: {long: 90, lat: 90},
                    default_fov: 179,     // 默认缩放值，在1-179之间
                    zoomRangeWidth: 1,
                    navbar: [
                        'autorotate',
                        'zoom',
                        'caption',
                        'gyroscope',
                        'fullscreen',
                    ],
                    //按钮提示
                    lang: {
                        autorotate: 'Automatic rotation',
                        zoom: 'Zoom',
                        zoomOut: 'Zoom out',
                        zoomIn: 'Zoom in',
                        fullscreen: 'Fullscreen',
                        gyroscope: 'Gyroscope'
                    },
                    theta_offset: 1000, // 旋转速度
                    fisheye: true,
                    //  启用陀螺仪
                    gyroscope: true,
                });
                PSV.on('ready', function () {
                    setTimeout(function () {
                        PSV.startGyroscopeControl();
                    }, 1000);

                });
            }
        },
        mounted() {
            THREE.DeviceOrientationControls = dc;
            this.initPhotoSphere();
        },
        created() {
        }
    }
`

What should I do?

**Comment by im-zhangxi** [comment]
npm run start
example/equirectangular.html
gyroscope: true :   ipone 6  and  x  not working.  

 What should I do?

**Comment by mistic100** [comment]
again, what "not working" means ? are there errors in the debugger ?

**Comment by im-zhangxi** [comment]
@mistic100    
 Solved. Thank you.
 Apple gyroscope must be https
