### ISSUE TITLE
Image file loaded twice 

### ISSUE THREAD

**Issue by mnaib** [mistic100/Photo-Sphere-Viewer#338]
Photo Sphere Viewer 3.5.1

Image file loaded twicely

You can see it directly from the viewer in your example 
https://photo-sphere-viewer.js.org/markers.html
![image](https://user-images.githubusercontent.com/6978173/74072274-bcc9ba00-4a1f-11ea-8589-ad2ebe906b9d.png)

![image](https://user-images.githubusercontent.com/6978173/74071747-2b0d7d00-4a1e-11ea-910f-63733cb93238.png)

**Comment by mistic100** [comment]
It's is loaded twice to be able to grab XMP Data. In most case this does not mean two complete HTTP request, the browser uses it's cache.

You can turn of XMP loading with the `usexmpdata` option.
