### ISSUE TITLE
image is rendered upside down

### ISSUE THREAD

**Issue by doshu** [mistic100/Photo-Sphere-Viewer#34]
i have use the attached image. the image is rendered upside down and when the animation is finished, the image will turn. this behavior is repeated at every complete 360°

![ufficio4](https://cloud.githubusercontent.com/assets/2188454/14177670/b238188a-f757-11e5-8d62-5628d369f7d8.jpg)

**Comment by mistic100** [comment]
Rebuild the lib.
#33

**Comment by doshu** [comment]
rebuilding the library has not resolved the problem

**Comment by doshu** [comment]
Ok i found that the master is the 3.2.0 beta. i use the 3.1.0 branch and works
