### ISSUE TITLE
How to achieve the cube panorama?

### ISSUE THREAD

**Issue by lanyanan** [mistic100/Photo-Sphere-Viewer#343]
How to achieve the cube panorama? I used your cube sunbathing example, but there was a problem

**Comment by mistic100** [comment]
Huh ? And what was this problem ? What exactly did you try ?

**Comment by lanyanan** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PhotoSphereViewer - cubemap demo</title>

  <link rel="stylesheet" href="../dist/photo-sphere-viewer.min.css">

  <style>
    html, body {
      width: 100%;
      height: 100%;
      overflow: hidden;
      margin: 0;
      padding: 0;
    }

    #photosphere {
      width: 100%;
      height: 100%;
    }

    .psv-button.custom-button {
      font-size: 22px;
      line-height: 20px;
    }
  </style>
</head>
<body>

<div id="photosphere"></div>

		<script src="../node_modules/three/build/three.js"></script>
		<script src="../node_modules/promise-polyfill/dist/polyfill.js"></script>
		<script src="../node_modules/uevent/uevent.js"></script>
		<script src="../node_modules/dot/doT.js"></script>
		<script src="../node_modules/nosleep.js/dist/NoSleep.js"></script>
		<script src="../node_modules/three/examples/js/controls/DeviceOrientationControls.js"></script>
		<script src="../node_modules/three/examples/js/effects/StereoEffect.js"></script>
		<script src="../node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.min.js"></script>
		<script>
			var div = document.getElementById('photosphere');
			var PSV = new PhotoSphereViewer({
					panorama: {
						left  : '../img/left.jpg',
						front : '../img/front.jpg',
						right : '../img/right.jpg',
						back  : '../img/back.jpg',
						top   : '../img/top.jpg',
						bottom: '../img/bottom.jpg'
					},
					container: div,
					time_anim: 3000,
					navbar: true,
					default_long: Math.PI / 2,
					defaultZoomLvl:0,
					autorotateSpeed:'1rpm',
					moveSpeed:0.5,
					moveInertia:true,
					navbar_style: {
						backgroundColor: 'rgba(58, 67, 77, 0.7)'
					},
					navbar: [
      'autorotate', 'zoom', 'download', 'markers',
      {
        title: 'Change image',
        className: 'custom-button',
        content: '🔄',
        onClick: (function() {
          var i = 0;
          var loading = false;

          return function() {
            if (loading) {
              return;
            }

            i = 1 - i;
            loading = true;
            PSV.clearMarkers();

            PSV.setPanorama('../img/0011.jpg', {zoom: 50}, true)
              .then(function() {
                PSV.setCaption('浴室');
                loading = false;
              });
          }
        }())
      },
      {
        title  : 'Random position',
        className: 'custom-button',
        content: '🔀',
        onClick: function() {
          PSV.animate({
            longitude: (Math.random() - 0.5) * 2 * Math.PI,
            latitude: (Math.random() - 0.5) * 3 / 4 * Math.PI,
            zoom: Math.random() * 60 + 20
          }, 1500);
        }
      },
      'caption', 'gyroscope', 'stereo', 'fullscreen'
    ],
					markers: [
		{
      // html marker with custom style
      id: 'text',
      longitude: -1.2,
      latitude: -0.3,
      html: '去浴室看看<img width=32 height=32 src="../img/pin-blue.png"/>',
      anchor: 'bottom right',
      scale: [0.5, 1.5],
      style: {
        maxWidth: '100px',
        color: 'white',
        fontSize: '20px',
        fontFamily: 'Helvetica, sans-serif',
        textAlign: 'center'
			},
			data:{
				mark:1
			}
    },
  ]
				});

				PSV.on('select-marker', function(marker) {
					console.log(marker,'--')
						if (marker.data && marker.data.mark===1) {
								var loading = false;
								PSV.clearMarkers();
								if (loading) {
									return;
								}
								loading = true;
								PSV.setPanorama('../img/0011.jpg', {zoom: 50}, true)
								.then(function() {
									PSV.setCaption('浴室');
									loading = false;
								});
						}
					});
		</script>
	</body>

</html>

**Comment by lanyanan** [comment]
https://raw.githubusercontent.com/lanyanan/pic/master/WechatIMG142.png
This is the display effect. It seems that the display is not complete. I don't know if it's the reason for configuration

**Comment by lanyanan** [comment]
It's my camera's position is not set, right

**Comment by mistic100** [comment]
Please use markdown syntax when you post code in the issues https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

----

I don't know what is hapenning, your settings seems fine (beside the fact that you mix `camelCase` and `snake_case` syntax, if you use PSV 3 you must use `snake_case`).

Could you host your page somewhere ?

**Comment by mistic100** [comment]
This is the only one reference for PSV 3 : https://photo-sphere-viewer.js.org/#options

Do not blindly copy-paste the example (https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/example/equirectangular.html) which uses use PSV 4 release candidate.

**Comment by lanyanan** [comment]
Thank you. I haven't deployed online yet. I'm using the psv4 version. Can you give me an example of cube panorama? Can I use this example https://github.com/mistic100/photo-sphere-viewer/blob/3.5.0/example/cubemap.html

**Comment by lanyanan** [comment]
Will you report an error with this example https://github.com/mistic100/photo-sphere-viewer/blob/3.5.0/example/cubemap.html

**Comment by mistic100** [comment]
> I'm using the psv4 version. 

No you are not, PSV 4 constructor is `PhotoSphereViewer.Viewer`, not `PhotoSphereViewer`.

> Can I use this example https://github.com/mistic100/photo-sphere-viewer/blob/3.5.0/example/cubemap.html
of course you can.  
perhaps this might help by the way https://github.com/mistic100/Photo-Sphere-Viewer/issues/310#issuecomment-586620253

In absence of a reproductible scenario, I close this issue

**Comment by mistic100** [comment]
I was finally able to reproduce the issue. I just release version 3.6.0 which should support newer versions of THREE.js
