### ISSUE TITLE
Missing Three.js components: DeviceOrientationControls. Get them from three.js-examples package

### ISSUE THREAD

**Issue by lshfong** [mistic100/Photo-Sphere-Viewer#344]
## Issues guidelines

- **Indicate your Photo-Sphere-Viewer, ThreeJS and web browser versions**
- Please search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

**Comment by lshfong** [comment]
// eslint-disable-next-line no-unused-vars
import * as THREE from 'three'
import PhotoSphereViewer from 'photo-sphere-viewer'
import 'photo-sphere-viewer/dist/photo-sphere-viewer.css'
import 'nosleep'
// eslint-disable-next-line no-unused-vars
import DeviceOrientationControls from 'three/examples/js/controls/DeviceOrientationControls'
// eslint-disable-next-line no-unused-vars
import StereoEffect from 'three/examples/js/effects/StereoEffect'
=====================================================
An error：
DeviceOrientationControls.js?abac:8 Uncaught ReferenceError: THREE is not defined
    at eval (DeviceOrientationControls.js?abac:8)
    at Object../node_modules/three/examples/js/controls/DeviceOrientationControls.js (app.js:4247)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (selector.js?type=script&index=0!./src/page/index.vue:8)
    at Object../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/page/index.vue (app.js:1296)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at eval (index.vue?f97c:1)
    at Object../src/page/index.vue (app.js:4602)

**Comment by lshfong** [comment]
Photo Sphere Viewer 3.5.1

**Comment by mistic100** [comment]
Because how they are declared, THREE.js examples files cannot be import as-it in Webpack applications.

You can find more informations here https://github.com/mrdoob/three.js/issues/10328 and here https://github.com/mrdoob/three.js/issues/9562

I didn't dig enough to know what is the proper Webpack configuration. Anyway this is not related to Photo Sphere Viewer.
