### ISSUE TITLE
Does it work with 360/3D product images?

### ISSUE THREAD

**Issue by simplenotezy** [mistic100/Photo-Sphere-Viewer#351]
I am curios to know whether or not I can use this library to present 360 images like so: https://3d-experience.thejewelleryroom.com/brands/Ole%20Lynnggard/Shotting%20stars/OleLynggaardShotingStarsOpen/OleLynggaardShotingStarsOpen.html

**Comment by mistic100** [comment]
The library only displays equirectangular spheres and cubemaps
