### ISSUE TITLE
setPanorama() inside panorama-loaded event callback, gives error "PSVError: Loading already in progress"

### ISSUE THREAD

**Issue by ai-tushar** [mistic100/Photo-Sphere-Viewer#353]
Photo Sphere Viewer 3.4.1

Hello,
i am trying to reduce loading speed by loading a low quality pano image first, and then gradually loading the higher quality panorama image,
below is what i tried,
```js
    panorama.on('panorama-loaded', function () {

                console.log('panorama-loaded');
                console.log(panorama.config.panorama);
                console.log(element_id);
                if(panorama.config.panorama.indexOf('/thumbs') !== -1){
                    panorama.setPanorama(panorama.config.panorama.replace('/thumbs', '/1024s'));
                }
                else if(panorama.config.panorama.indexOf('/1024s') !== -1){
                    panorama.setPanorama(panorama.config.panorama.replace('/1024s', '/2048s'));
                }
                else if(panorama.config.panorama.indexOf('/2048s') !== -1){
                    panorama.setPanorama(panorama.config.panorama.replace('/2048s', '/4096s'));
                }
                else if(panorama.config.panorama.indexOf('/4096s') !== -1){
                    panorama.setPanorama(panorama.config.panorama.replace('/4096s', ''));
                }
    });
```

`panorama-loaded` is triggered when the pano completes loading. so after the loading completes, i try to load a higher resolution. but i am getting the error `PSVError: Loading already in progress`

if i call `setPanorama()` after an interval of 500 ms inside this callback, then it works. which is not a good solution.
another thing is, loading new pano in this way, shows the loader icon, so is their any way i can load the new panorama without showing the loader icon ?
there is a function `preloadPanorama()` but calling this function with panorama path, does not loads the image in browser.

can you please suggest me a solution ? or is there a better way to serve the purpose i am trying to reach ?

**Comment by mistic100** [comment]
using setTimeout (with a delay of 0) is the only solution because then is triggered from inside the Promise, and the mentionned error occurs when the Promise is still running.

setTimeout is **not** evil, it is perfectly fine to use to execute code on next browser tick.

---

You can disable the loader by configuring the `transition` (https://photo-sphere-viewer.js.org/#options), this does not affect the first loading.

---

`preloadPanorama` requires the configuration of `cache_texture`

**Comment by ai-tushar** [comment]
Thank you for you detailed answers. i have tried `setTimeout` with an interval 0. i am still getting the error, but before the second `setPanorama` call. for example my code looks like this now,

    panorama[element_id].on('panorama-loaded', function () {
                console.log(panorama[element_id].config.panorama);
                if(panorama[element_id].config.panorama.indexOf('/thumbs') !== -1){
                    console.log('inside '+1);
                    setTimeout(function(){
                        panorama[element_id].setPanorama(panorama[element_id].config.panorama.replace('/thumbs', '/1024s'));
                    }, 0);
                }
                else if(panorama[element_id].config.panorama.indexOf('/1024s') !== -1){
                    console.log('inside '+2);
                    setTimeout(function(){
                        panorama[element_id].setPanorama(panorama[element_id].config.panorama.replace('/1024s', '/2048s'));
                    }, 0);
                }
                else if(panorama[element_id].config.panorama.indexOf('/2048s') !== -1){
                    console.log('inside '+3);
                    setTimeout(function(){
                        panorama[element_id].setPanorama(panorama[element_id].config.panorama.replace('/2048s', '/4096s'));
                    }, 0);
                }
                else if(panorama[element_id].config.panorama.indexOf('/4096s') !== -1){
                    console.log('inside '+4);
                    setTimeout(function(){
                        panorama[element_id].setPanorama(panorama[element_id].config.panorama.replace('/4096s', ''));
                    }, 0);
                }
    });

now after loading the initial panorama, it triggers the setPanorama from first if condition. then when that panorama of 1024s folder is loaded, this event is triggered again, and now inside first `else if` when `setPanorama` is called again, the same error occures. so for the above call i get the output in console is this

    http://localhost/ps_ifp/uploads/floor/elements/360s/thumbs/element_360_218909245_1584892497.jpg
    inside 1
    http://localhost/ps_ifp/uploads/floor/elements/360s/1024s/element_360_218909245_1584892497.jpg
    inside 2
    uncaught exception: PSVError: Loading already in progress


is it possible to do any operation when the Promise fully completed ?

**Comment by mistic100** [comment]
remove your `panorama` option, this will disable the initial auto load

then immediately call `setPanorama` with the small image, it returns the Promise, it _should_ work if you load the next image when this Promise complete

**Comment by ai-tushar** [comment]
Thanks a lot for the trick. i have updated my code as you suggested. my new code is like below.

    let loadThumbPromise = panorama[element_id].setPanorama(file_url);
            loadThumbPromise.then(function(){
                console.log('1');
                file_url = file_url.replace('/thumbs', '/1024s');
                let load1024sPromise = panorama[element_id].setPanorama(file_url, false, false);
                load1024sPromise.then(function(){
                    console.log('2');
                    file_url = file_url.replace('/1024s', '/2048s');
                    let load2048sPromise = panorama[element_id].setPanorama(file_url, false, false);
                    load2048sPromise.then(function(){
                        console.log('3');
                        file_url = file_url.replace('/2048s', '/4096s');
                        let load4096sPromise = panorama[element_id].setPanorama(file_url, false, false);
                        load4096sPromise.then(function(){
                            console.log('4');
                            file_url = file_url.replace('/4096s', '');
                            let loadOrigPromise = panorama[element_id].setPanorama(file_url, false, false);
                            loadOrigPromise.then(function(){
                                console.log('final loaded');
                            });
                        });
                    });
                });
    });

So now i am able to load all the images of diff quality step by step.
but one problem remains, the loader still shows, as you can see i have passed 2nd and 3rd parameter to `setPanorama()` function as `false'  as i dont want to pass any additional config and disable the transition, but still shows the loader every time `setPanorama` is called.

also during the first init of `new PhotoSphereViewer()` i have also set the config as 

    transition: {
                    duration: 0,
                    loader: false
    }

but ignoring everything it still shows the loader.
i just want to show the loader first time, and then disable it. 
am i doing it wrong somehow?

**Comment by ai-tushar** [comment]
Hello again, i think there might be some improvement needed in the condition of showing loader inside `setPanorama()` function.
however for now i have solved this issue by adding a `hidden` class to the `psv-loader-container` explicitly. like this,
`$(panorama[element_id].loader.container).addClass('hidden');`
so in my css file,

    .panorama-wrapper .psv-container .psv-loader-container.hidden{
        display: none !important;
    }

so this overrides the dynamically changing `display ` property of `psv-loader-container` from inside the `setPanorama()` method. so it always stays `display: none;` untill i remove the hidden class.

Note: after i loaded my max resolution panorama, i removed the `hidden` class form the loader container. so i dont mess up with any other process related to this for futher operations.

so now this solves my issue, but if there is a better way to manage things, let me know please.

Thanks for your time and suggestions so far.

**Comment by mistic100** [comment]
In version 4 I moved all transition options to the "setPanorama" method, allowing full control of the behavior.
