### ISSUE TITLE
How to add second set marker to image?

### ISSUE THREAD

**Issue by Wintear91** [mistic100/Photo-Sphere-Viewer#354]
How do I add "second" set markers to the second image after calling PSV.setPanorama() function?
I have customized a marker to do the switching to 2nd panorama.

I realise the function markers: (function () {....} i try do if/else return var a/ var b but does'nt seems to work.

Anyone have examples? am doing a switch back and fourth layout.

```
PSV.on('select-marker', function (marker, click) {
        if (marker.data && marker.data.deletable) {
          if (click) {
            PSV.removeMarker(marker);
          }
          else {
            PSV.updateMarker({
              id: marker.id,
              image: 'assets/pin2.png'
            });
          }
        } else if (marker.data && marker.data.id === "go-ground-floor") {
          if (click) {
            i++;
            console.log(i);
            PSV.clearMarkers();
if(i > 1){
i = 0;
}
            PSV.setPanorama(panos[i].url, panos[i].target, true);
          }
        }
      });
```

**Comment by mistic100** [comment]
Use "addMarker" or "setMarkers"

Sent from MailDroid

-----Original Message-----

**Comment by mistic100** [comment]
> I realise the function markers: (function () {....} i try do if/else return var a/ var b but does'nt seems to work.

Of course, this is a self called function only used to encapsulate the markers initialisation in the demo, it is **not** re-evaluated

**Comment by Wintear91** [comment]
> > I realise the function markers: (function () {....} i try do if/else return var a/ var b but does'nt seems to work.
> 
> Of course, this is a self called function only used to encapsulate the markers initialisation in the demo, it is **not** re-evaluated

Any quick guides for me? kinda brain dead now need some guides or examples
Appreciated

**Comment by mistic100** [comment]
There is already an example in the file you are copying
https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/example/equirectangular.html#L408

**Comment by mistic100** [comment]
And there is the doc https://photo-sphere-viewer.js.org/api/module-components.PSVHUD.html#addMarker

By the way I absolutely hate spoon-feeding people, so I won't write your code for you. But I answer question when you have working or non working code.

**Comment by Wintear91** [comment]
> And there is the doc https://photo-sphere-viewer.js.org/api/module-components.PSVHUD.html#addMarker
> 
> By the way I absolutely hate spoon-feeding people, so I won't write your code for you. But I answer question when you have working or non working code.

I got it work thanks.
