### ISSUE TITLE
Disable overlay and show old panorama in the background when new panorama is being loaded

### ISSUE THREAD

**Issue by ai-tushar** [mistic100/Photo-Sphere-Viewer#356]
Hello,
when i call `setPanorama()` to load a higher resolution of the same panorama, immediately a white/ash colored overlay shows over the old image, how i can disable this overlay ?
because i want users to be able to interact with the old panorama continuously. so loading new panorama should not interrupt user interactions. 
(i am in discussion about disabling loader in a different question. so this question only focuses on the overlay disabling.)

**Comment by ai-tushar** [comment]
after doing some more digging, i found out that the PSVOverlay is not the problem actually.
problem is when we call `setPanorama()` it set `PSV canvas container (psv-canvas-container)` `opacity: 0`
and after the loading new panorama completes it set `opacity: 1`. it i see that it kind of a default behaviour. so to disable this i had to explicitly set the `opacity` to 1 always.
so what is did is ,

`$(panorama[element_id].canvas_container).addClass('opacity-one');`

and in my css,

    .panorama-wrapper .psv-container .psv-canvas-container.opacity-one{
        opacity: 1 !important;
    }

and after my loading completes i remove the class,
`$(panorama[element_id].canvas_container).removeClass('opacity-one');`
to not mess up with any other default operations after my purpose is served.

this solved my problem for now. but if there is any other better way, i will be glad to know.

note: i didnt removed the issue as it may help someone else. you can close it unless there is a better suggestion.

**Comment by mistic100** [comment]
In version 4 I removed the line hiding the canvas during loading
