### ISSUE TITLE
Install instruction enhancement

### ISSUE THREAD

**Issue by bpascoe** [mistic100/Photo-Sphere-Viewer#357]
This looks like the best library to use, but for those of us short on time, and who just want to do use a few features to get it working, the 5s install is failing when compared to other panorama viewer javascript options, which I'm about to switch to. This is really the one I want to use though, so I'm taking the trouble to put in an issue. So, the problem is this step: "Include all JS & CSS files in your page manually or with your favorite bundler and init the viewer."
This must sound obvious to you, and others who bash out js driven websites every day but I'm running into a lot of hiccups. There are quite a lot of .js files. Do you literally mean I should include them all, or just a few particular ones, like the one in /build or /dist or /dist for each of the dependencies? I tried mucking around with npm and packagers, but it's a lot just to plonk some .js in a folder and point to it. Can you maybe provide a stable minified file for everything that is needed? (I managed to find a minified three.min.js, but still can't sort out uEvent, and am getting errors if I directly include all the files under uevent). Then a code snippet with 3 or so <script src=""> elements would complete it and it really would be a 5s set up.
I realise this is as much because I should get up to speed on javascript package managers etc, but it would still help people like me out a great deal just to have that include snippet work out of the box. It seems a shame to turn people away from that one stumbling block at the beginning.
Thanks in advance. It looks awesome, and like it will do everything I might want it to do. The API doco looks clear and easy enough to follow.

**Comment by mistic100** [comment]
The example file has all necessary files included https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/example/equirectangular.html

I'll add a complete example on the new documentation.

**Comment by mistic100** [comment]
I won't provide a "stable minified file for everything that is needed" because it will make the NPM package bigger and THREE.js as a new version every second day.

**Comment by bpascoe** [comment]
Great! Thankyou!
