### ISSUE TITLE
uEvent 2.0.0 and PhotoSphereViewer 3.6.0 auto-rotate glitch 

### ISSUE THREAD

**Issue by philipperoubert** [mistic100/Photo-Sphere-Viewer#358]
Hello! First of all, thanks a lot for your great work.

I discovered a bug, not sure if it's me doing something wrong or not.

uEvent 2.0.0 and Photo Sphere Viewer 3.6.0 seem to not work together. If I enable the auto-rotate feature, the Sphere will glitch to one of the poles and won't move. This test was done in firefox 74.0.1, and was also reproduced in Chrome by a colleague.

The fix I found was to downgrade uEvent to 1.0.0 on [JsDelivr](https://www.jsdelivr.com/package/npm/uevent?version=1.0.0) which works just fine. I just assumed I'd have to download the latest version of uEvent, but perhaps not? In which case I think it would be useful to precise on the website which version to use...

Thank you! :)

**Comment by mistic100** [comment]
Hello

the compatible version is indicated in the package.json

PSV 4 being just around the corner I think it is enough for people sticking to the old versions.
