### ISSUE TITLE
missing marker id

### ISSUE THREAD

**Issue by 183055116** [mistic100/Photo-Sphere-Viewer#359]
I'm a beginner. When I change the image PSV. Setpanorama () after PSV. Clearmarkers (), the added markers appear missing marker ID. it turns out that marker ID exists. What's the problem here? Thank you!
![img](https://user-images.githubusercontent.com/37178044/78776806-05bfcf80-79cb-11ea-9517-fde25bc02c12.png)

**Comment by mistic100** [comment]
Please show your code

**Comment by 183055116** [comment]
> 请显示您的代码

![one](https://user-images.githubusercontent.com/37178044/78854674-81199380-7a54-11ea-9dd6-ca2306d4cab7.png)
![two](https://user-images.githubusercontent.com/37178044/78854688-88d93800-7a54-11ea-858f-87760baaa0d4.png)

Thank you very much for your guidance, This question has been bothering me for two days.

**Comment by 183055116** [comment]
@mistic100 thanks!!!

**Comment by 183055116** [comment]
@mistic100 I read your source code and have solved this problem. Thank you for helping me.
![two](https://user-images.githubusercontent.com/37178044/78855360-4284d880-7a56-11ea-9d94-b939543df725.png)

**Comment by 183055116** [comment]
> Please show your code

I read your source code and have solved this problem. Thank you for helping me.
