### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by TheWizz** [mistic100/Photo-Sphere-Viewer#360]
Looking through the v4 development branch, checked out today, I found this commend in the Viewer.js file:

_The memory used by the ThreeJS context is not totally cleared. This will be fixed as soon as possible._

Does this mean that a certain amount of memory is leaked every time a Viewer is created and then destroyed, or is this a "one time leak", that will not accumulate over time? The latter would not be a problem in our case, while the former likely would (long running session that may create and destoy man y vewers over time).

-JM

**Comment by mistic100** [comment]
That's an old comment. Someone pointed out that it is not possible to totally clean a three.js scene.
I have no idea if it is still the case

**Comment by TheWizz** [comment]
OK, thanks. I guess you then have no idea whether this was a "one time leak" or a potential leak for every new scene created. I assume I just have to try things out to see how it files.

-JM

**Comment by mistic100** [comment]
In theory the lib cannot do much more than https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/services/Renderer.js#L424

it loops through all objects and call `dispose` everytime it can
