### ISSUE TITLE
Passing in ready-made element instead of HTML code

### ISSUE THREAD

**Issue by TheWizz** [mistic100/Photo-Sphere-Viewer#361]
I'm looking into combining the sphere viewer with an existing application where there is already a mechanism to render interactive "widgets" as elements. However, those are generated programmatically, and then added to the DOM. When used with the sphere viewer I would like to add such elements as markers instead. Since the elements already come pre-made, I would like to add those "as is". But I see only the ability to add elements by passing in the HTML code. Would you  say it could be feasible to provide ready-made elements instead of HTML source code, and then make those work as markers in the same way?

I can see in the __updateNormal() function that all it does is

`this.$el.innerHTML = this.config.html`

Perhaps it could be just as easy to use a passed-in element instead of this.$el (or as a child of $el). If you see no conceptual problem with that, I'd be happy to pursue this further on my own. I just wanted to check up front so I don't waste my time on something that has no chance of working.

-JM

**Comment by mistic100** [comment]
No this can't be done. Markers element have to be fully owned by the viewer and children of the `.psv-hud` element.

The only solution is the "clone" youf elements by getting their `innerHTML` and use it as the `html` marker property.

**Comment by TheWizz** [comment]
Making them "fully owned by the viewer" isn't a problem for me. Those elements are produced by JS code, but not yet attached anywhere else in the DOM. So they're fresh and "virgin" in that sense. So why would I need to clone them before attaching them to the viewer?

-JM

**Comment by mistic100** [comment]
What is the issue on your side to get the innerHTML of said elements ?

**Comment by TheWizz** [comment]
Some of those elements may already have event handlers and such attached, which would be lost if I serialize back to HTML and re-surrect from there. So I do need to use those elements "as is", and see no obvious reason why I shouldn't be able to. But perhaps I'm overlooking something.

-JM

**Comment by mistic100** [comment]
Stability and maintenability. Adding such feature :
1. will impose I am very careful when making internal changes
2. has 100% chance someone will try to attach an element already attached in the DOM and break its app (generating support for me)
3. has unpredictable behavior because the viewer attach it's own event handlers to the markers

My decision is final. Thank your for understanding and good luck.

**Comment by TheWizz** [comment]
Thanks for your comments. I fully understand. 

I'll take a stab at it within my app to see how far I can get with my approach. If nothing else, I'll learn a lot more about your excellent sphere viewer as well as three.js in the process ;-).

-JM
