### ISSUE TITLE
Is there a way to work with flat images too?

### ISSUE THREAD

**Issue by stranger-games** [mistic100/Photo-Sphere-Viewer#365]
Hi

I have been using this library successfully with 360 images and hotspots. The client now wants the same functionality with flat images. I think the only way is to do a switch between this library when the image is 360 and another library when the image is flat.

But just wanted to make sure that photo-sphere-viewer can't work with flat images before I bite the bullet with a new library.

Thanks for advance.

**Comment by mistic100** [comment]
No it can't
#200

**Comment by pajamabob** [comment]
Send me an email pajamabob@gmail.com.  I have some work I have been doing to support flat images.
