### ISSUE TITLE
use version 4.0.1, Mobile click or touch event is invalid

### ISSUE THREAD

**Issue by freedom2012** [mistic100/Photo-Sphere-Viewer#366]
Hello,i use version 4.0.1, mobile click or touch event is invalid.Can you help me see why

**Comment by mistic100** [comment]
What do you mean ? Please respect the issue guidelines.

Sent from MailDroid

-----Original Message-----

**Comment by freedom2012** [comment]
use mobile,when the panel open,i can not click the element in the panel.like the marker list.
