### ISSUE TITLE
how use MarkersPlugin in photo-sphere-viewer4.0.1

### ISSUE THREAD

**Issue by w8w8w8** [mistic100/Photo-Sphere-Viewer#368]
my  project is angular9.0  some code like this :

import * as THREE from 'three';
import { Viewer, PhotoSphereViewer, MarkersPlugin } from 'photo-sphere-viewer';

public ngOnInit(): void {
    const viewer = new Viewer({
        container: document.querySelector('#viewer'),
        panorama: 'assets/images/1.jpg',

        plugins: [
          /************ MarkersPlugin************/
          [MarkersPlugin, {
            markers: [ 
              {
                id: 'newmarker2',
                longitude: '45deg',
                latitude: '0deg',
                image: 'assets/images/pin-blue.png',
              },
            ],
          }],

        ],
    });

    /****  */
    const markersPlugin = viewer.getPlugin(MarkersPlugin);
    
    console.log(markersPlugin);

  }

the "markersPlugin " is undefined  .

**Comment by mistic100** [comment]
Import MarkersPlugin from photo-sphere-viewer/dist/plugins/markers;

This is indicated on top of the plugin page.
Note : it is a defaults export, no mustaches

Sent from MailDroid

-----Original Message-----

**Comment by w8w8w8** [comment]
@mistic100 thanks for your replay.

I am a junior coder ,  and I write this code:

`import { Viewer, PhotoSphereViewer } from 'photo-sphere-viewer';
import {MarkersPlugin} from 'photo-sphere-viewer/dist/plugins/markers';

public ngOnInit(): void {
const viewer = new Viewer({
container: document.querySelector('#viewer'),
panorama: 'assets/images/1.jpg',

    plugins: [
      /************ MarkersPlugin************/
      [MarkersPlugin, {
        markers: [ 
          {
            id: 'newmarker2',
            longitude: '45deg',
            latitude: '0deg',
            image: 'assets/images/pin-blue.png',
          },
        ],
      }],

    ],
});


/****  */
const markersPlugin = viewer.getPlugin(MarkersPlugin);

console.log(markersPlugin);
}`

but it does not work .  how to write the code ?
 thanks again

**Comment by mistic100** [comment]
As a junior developper do not say "it does no work", explain what is not working.

As I said it is a default export so you must not use mustaches in the import
```
import MarkersPlugin from 'photo-sphere-viewer/dist/plugins/markers';
```

**Comment by w8w8w8** [comment]
@mistic100 hi, my english so poor, i can not understand 'you must not use mustaches in the import'.
could you write an example for me ?

my code like this:


import { Viewer, MarkersPlugin } from 'photo-sphere-viewer';
init() {
const viewer2 = new Viewer({
        container: document.querySelector('#viewer'),
        panorama: 'assets/images/Bryce-Canyon-National-Park-Mark-Doliner.jpg',
        defaultZoomLvl:50,
        plugins: [
          [MarkersPlugin, {
            markers: [ 
              {
                id: 'new-marker',
                longitude: '45deg',
                latitude: '0deg',
                image: 'assets/images/pin-red.png',
              },
            ],
          }], 
        ],
    });
}

but the MarkersPlugin not work

thank you again!

**Comment by mistic100** [comment]
I wrote an example in my previous message !

Sent from MailDroid

-----Original Message-----

**Comment by w8w8w8** [comment]
@mistic100  i will try it again, thank you.
