### ISSUE TITLE
Cancel panorama loading

### ISSUE THREAD

**Issue by gvdhorst** [mistic100/Photo-Sphere-Viewer#369]
Tested on version 4.0.1

Calling viewer.setPanorama() throws an error when a panorama is already loading (as described in the API documentation).
When a user selects a panorama to load but then changes his mind and wants to load a different panorama instead, he has no choice but to wait for the first (undesirable) panorama to load until the second can be loaded.

Because it can take quite some time for a panorama to load it would be useful if the loading process can be cancelled.
Ideally calling viewer.setPanorama() when a panorama is already being loaded would cancel the old loading process and start a new loading process.

**Comment by mistic100** [comment]
@gvdhorst it would be cool if your are able to test it before release

**Comment by gvdhorst** [comment]
Tested on Chromium Version 81.0.4044.122 (Official Build) Arch Linux (64-bit)

This works for me, but viewer.setPanorama() does **throw** a `ProgressEvent` with `.type` "abort" when the loading got interrupted by a second call to setPanorama() before the first was completed.

The `ProgressEvent` makes sense to me, but I didn't expect it to be thrown as an error since it is the desired behavior.
I would instead expect to be able to handle the abort event in `.then()` or as `.on('abort', ...)`

This is my workaround:
```
viewer
.setPanorama(url)
.catch((err) => {
      if (err.type === 'abort') {
          // loading was canceled - this is fine, do nothing.
      } else {
          throw err;
      }
}
```

**Comment by mistic100** [comment]
The problem is other parts of the library (mainly plugins) expect the Promise to be resolved when the panorama has actually been loaded, so it left me no other choice to reject the Promise for all other cases.
