### ISSUE TITLE
[feature request] Implement a smooth scrolling

### ISSUE THREAD

**Issue by wujekbogdan** [mistic100/Photo-Sphere-Viewer#37]
Hi,

Is there any chance to implement smooths scrolling (e.g. like [Panellum](https://pannellum.org/) has)?

I tried to implement it on my own using the `position-updated` callback and the `.animate()`method, but `position-updated` returns only the new values. If the previous values (the initial position before drag started) were passed to the `position-updated` callback it would be much easier to do such things.

btw, it would be great [if the `.animate()` method supported easing](https://github.com/mistic100/Photo-Sphere-Viewer/issues/38).

**Comment by mistic100** [comment]
You mean the slow down animation once the user release the mouse ? It's already implemented for next version.

**Comment by wujekbogdan** [comment]
Yes. Exactly.

**Comment by mistic100** [comment]
I honnestly don't see the interest. I am against making everything configurable, it confuses people for nothing. If there are better timings we can change the code but I don't want to add a parameter for that.
