### ISSUE TITLE
Viewer "Screenshot"

### ISSUE THREAD

**Issue by pajamabob** [mistic100/Photo-Sphere-Viewer#371]
I know I can download the image being displayed in the viewer.  However, is there a way to get a “screenshot” of what is displayed in the viewer, including markers?  

Any help would be much appreciated.

**Comment by mistic100** [comment]
As markers are not in the canvas it can get tricky.  
I suggest you use https://www.npmjs.com/package/html-to-image to export the whole viewer container.

You might need to hide the navbar first
```
viewer.navbar.hide(); // if using version 4

viewer.hideNavbar(); // if using version 3
```

**Comment by pajamabob** [comment]
Thank you!

I am still working with version 3.  To make your suggestion work, I had to
call the new renderer like this:

new THREE.CanvasRenderer(

*{                    preserveDrawingBuffer: true                }*);

With that one change, and the library you suggested, all woks as I had
hoped...


Thank you again...

Regards,
Bob Fahlin

**Comment by mistic100** [comment]
cool

FYI CanvasRenderer is not supported anymore by THREE.js

**Comment by mistic100** [comment]
Also this might be useful https://stackoverflow.com/questions/30628064/how-to-toggle-preservedrawingbuffer-in-three-js

You can force a render by calling the `render` method.
This way you don't have to modify the library.

**Comment by pajamabob** [comment]
Perfect, thank you so much...

Regards,
Bob Fahlin
