### ISSUE TITLE
'camera' property of 'renderer' is null, when I'm adding next markers

### ISSUE THREAD

**Issue by RaGreen** [mistic100/Photo-Sphere-Viewer#375]
Photo-Sphere-Viewer: 4.0.2
three: 0.116.1
Browser: Google Chrome 81.0.4044.129

I started rewritting React code from 3.x to 4.x version of Photo-Sphere-Viewer. I load Viewer and plugings:
```
import { Viewer } from 'photo-sphere-viewer';
import * as GyroscopePlugin from 'photo-sphere-viewer/dist/plugins/gyroscope';
import * as MarkersPlugin from 'photo-sphere-viewer/dist/plugins/markers';
```
then in useEffect() hook I create viewer with marker:
```
     const tempViewer = new Viewer({
            container: 'viewer',
            loadingImg: '/assets/img/photosphere.gif',
            caption: 'Zdjęcie 360',
            panorama: '/assets/360/photo.jpg',
            navbar: [
                'autorotate',
                'zoom',
                'caption',
                'fullscreen'
            ],
            autorotateDelay: false,
            sphereCorrection: {
                pan: 0,
                tilt: 90
                roll: 0
            },
            plugins: [
                GyroscopePlugin,
                [ MarkersPlugin, {
                    markers: [
                        {
                            id: 'nordic',
                            x: 3563,
                            y: 1239,
                            circle: 20,
                            tooltip: 'Tower',
                            svgStyle: {
                                fill: 'blue'
                            }
                        }
                    ]
                }]
            ]
        });
```
When I want to add next marker I get plugin:
`const markersPlugin = tempViewer.getPlugin('markers');`
and I try to add next marker:
```
markersPlugin.addMarker({
    id: 'image2',
    longitude: 5.59,
    latitude: -0.12,
    width: 300,
    height: 200,
    anchor: 'bottom center',
    image: '/assets/img/bridge.jpg',
    tooltip: 'Bridge'
});
```
but operations failes due to this error:
![image](https://user-images.githubusercontent.com/1823017/81075980-5d2e5e00-8eeb-11ea-983a-015e97f993a0.png)
I debugged DataHelper.js and `this.psv.renderer` contains property `camera`, but it's null when I try access this. Any suggestions?

**Comment by RaGreen** [comment]
![image](https://user-images.githubusercontent.com/1823017/81077646-8a7c0b80-8eed-11ea-9f4a-306ca474b1ab.png)
console.log:
1. `this.psv.renderer`
2. `this.psv.renderer.camera`
3. `this.psv.renderer.camera == null`

**Comment by mistic100** [comment]
instead of setTimeout try `viewer.once('ready')`
https://photo-sphere-viewer.js.org/guide/methods.html#presentation

**Comment by RaGreen** [comment]
Yep, sorry, my fault. I should have checked if there is a method for this.
