### ISSUE TITLE
'stereo-updated' event not fired

### ISSUE THREAD

**Issue by pmarfany** [mistic100/Photo-Sphere-Viewer#377]
Hi!

I'm updating my code to use the new **4.0.2** release of this library and the 'stereo-updated' event is not firing.

I have included the 'GyroscopePlugin' and StereoPlugin' and when I click on the VR button, everything works fine except for 'stereo-updated' event, which is not fired.
I'm also subscribed to the 'ready' and 'fullscreen-updated' events and these two work perfectly.

```javascript
import { Viewer as PhotoSphereViewer } from 'photo-sphere-viewer';
import GyroscopePlugin from 'photo-sphere-viewer/dist/plugins/gyroscope'
import StereoPlugin from 'photo-sphere-viewer/dist/plugins/stereo'
import 'photo-sphere-viewer/dist/photo-sphere-viewer.css';

var viewer = PhotoSphereViewer({
  container    : 'photosphere',
  panorama     : 'panorama-url',
  plugins      : [GyroscopePlugin, StereoPlugin],
  navbar       : ['stereo', 'gyroscope', 'fullscreen'],
});

viewer.on('stereo-updated', () => {
  console.log('Stereo updated');
});

viewer.on('fullscreen-updated', () => {
  console.log('Fullscreen updated');
});
```

Has this event been removed? If not, can you have a look into it?

Thanks!

**Comment by mistic100** [comment]
The event is part of the plugin

```
viewer.getPlugin(StereoPlugin).on('stereo-updated')
```

https://photo-sphere-viewer.js.org/plugins/#using-a-plugin

**Comment by pmarfany** [comment]
Sorry @mistic100, I missed that part in the docs! 😅.

I have made the modifications but its not working either.
After looking a little bit at the code I found the lines where the event is triggered, and I see it's being called as <StereoPlugin.EVENTS.**STEREO_UPATED**>:

https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/plugins/stereo/index.js#L167
https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/plugins/stereo/index.js#L201

Could that be a typo?

**Comment by mistic100** [comment]
it's a variable...
defined here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/plugins/stereo/index.js#L53

**Comment by mistic100** [comment]
Sorry I see what you meant. I'll fix it
