### ISSUE TITLE
PSV.setPanorama cause THREE.WebGLRenderer: Context Lost.

### ISSUE THREAD

**Issue by Warlock1994** [mistic100/Photo-Sphere-Viewer#379]
When I use it multiple times, it may happen，then  the whole page is stuck.Is it wrong with me?
![image](https://user-images.githubusercontent.com/21231664/81663420-418a0100-9471-11ea-9f78-05cdcd7322fd.png)

**Comment by mistic100** [comment]
I cannot reproduce the problem.

**Comment by licethbarandica** [comment]
Could you fix the issue?
