### ISSUE TITLE
[feature request] add easing parameter to the animate() method.

### ISSUE THREAD

**Issue by wujekbogdan** [mistic100/Photo-Sphere-Viewer#38]
It would be great if there were additional `easing` parameter for the `.animate()` method. It would make animations much smoother.

**Comment by mistic100** [comment]
Next version always use "inOutSine" easing https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/src/js/PhotoSphereViewer.public.js#L406
This could be configurable (but I'm not sure it's really usefull now it's never linear)

**Comment by wujekbogdan** [comment]
Great. if `inOutSine` wasn't hard-coded it would be even better.

**Comment by mistic100** [comment]
Same answer as #37
