### ISSUE TITLE
Big files not working on Firefox

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#383]
seen at #380

supposedly the internal resize to respect WebGL texture max size is not working.

**Comment by sp00x** [comment]
A short comment: I noticed that if I try the image I was using in #380 in your playground page - https://photo-sphere-viewer.js.org/guide/cropped-panorama.html#manually - it works fine as long as I don't set any "Cropped Y" values, so I assume it might be related to the processing that is being done there + the potential image size issue.

**Comment by mistic100** [comment]
So the problem is with the area of the canvas, it cannot exceed ~124 978 050 pixels (found empirically).

The current code tries to create a canvas of 16384 (max WebGl texture size) x 8192 = 137 904 128 pixels.

So because the browser does not provide this info, and the creation of the canvas does not fail (damn !!!!!) I'll have to include a test of the maximum supported area at startup.

**Comment by mistic100** [comment]
And as textures sizes must be a power of to it will be scalled down to 8192 x 4096.

In such cases it is better to not using cropping data and include a black bar in the source image, as the WebGL driver is able to display 16384 x 8192 textures.
