### ISSUE TITLE
multiresolution feature ?

### ISSUE THREAD

**Issue by mnaib** [mistic100/Photo-Sphere-Viewer#384]
we are very grateful to You for this project
Very nice  hotspot types ,styles and plugins.
Do your planned add   multiresolution feature  as Standard options  and tools for converting   panorama into   multiresolution format

**Comment by mistic100** [comment]
Like that ? https://photo-sphere-viewer.js.org/plugins/plugin-resolution.html
**note** : is not released yet

**Comment by mnaib** [comment]
multiple resolution feature speeds up loading pano using  image  tiles .  Visible tiles must be loaded first.  setPanorama method loads the entire panorama.

**Comment by mistic100** [comment]
#243
