### ISSUE TITLE
prompt position deviated from object

### ISSUE THREAD

**Issue by tashiwo** [mistic100/Photo-Sphere-Viewer#385]
![image](https://user-images.githubusercontent.com/49508459/82296902-7e5f7600-99e4-11ea-97c7-5316d692b182.png)
 
 
 markers.addMarker({

          id: 'polygon1' + Math.random(),
          content: 'polygon1',
          polygonRad: [[0.4693490176750515, -0.5829017557287455], [0.3247446259019577, -0.29101883823728514], [6.072435720649082, -0.2977128376177518], [6.000252106287911, -0.6116399392407947]],
          svgStyle: { fill: "rgba(200, 0, 0, 0.2)", stroke: "rgba(200, 0, 50, 0.8)", strokeWidth: "2px" },
          tooltip: {
            content: 'This is a mountain',
            position: 'bottom center',
          },
        });

**Comment by mistic100** [comment]
Provide a live demo

**Comment by mistic100** [comment]
Probably similar to #388 your are missing the stylesheet of the markers plugin
