### ISSUE TITLE
i make a marker and when i change angle of view，markers can't  stick

### ISSUE THREAD

**Issue by seventhcode** [mistic100/Photo-Sphere-Viewer#386]
i make a marker and when i change angle of view，markers can't  stick
![微信图片_20200520142314](https://user-images.githubusercontent.com/43659713/82412408-2ee17e80-9aa6-11ea-9b20-91b17e3b230b.png)
![微信图片_20200520142351](https://user-images.githubusercontent.com/43659713/82412422-330d9c00-9aa6-11ea-86fb-4a3e869dcfda.png)

**Comment by mistic100** [comment]
Is this a "rect" marker ? If this this is totally normal, markers are drawn above the view.

If you want to outline the window you must use "polygonRad" or "polygonPx" as in the example 
https://photo-sphere-viewer.js.org/plugins/plugin-markers.html#example (the red blob on the rock)

**Comment by seventhcode** [comment]
@mistic100 
thanks,is there some api for change camera position?i am so sorry i can't find them

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/guide/methods.html#rotate-position

**Comment by seventhcode** [comment]
i want to use image marker and altered by the angle of view,how can i do that ? @mistic100

**Comment by mistic100** [comment]
It is not possible. And I will not and this functionality, sorry.

Sent from MailDroid

-----Original Message-----
