### ISSUE TITLE
Stereo Plugin has wrong gyroscope import path

### ISSUE THREAD

**Issue by paglias** [mistic100/Photo-Sphere-Viewer#389]
## Issues guidelines

- Photo-Sphere-Viewer 4.0.4, three.js 0.116.1 

I'm sorry for the lack of a jsfiddle example but this seems to be a build problem.

The published NPM package in `/dist/plugins/stereo.js` requires `photo-sphere-viewer/plugins/gyroscope` but the path should be `photo-sphere-viewer/dist/plugins/gyroscope`.

This way webpack doesn't find it and an error is thrown:

```
import { Viewer } from "photo-sphere-viewer";
import GyroscopePlugin from "photo-sphere-viewer/dist/plugins/gyroscope";
import StereoPlugin from "photo-sphere-viewer/dist/plugins/stereo";

    const viewer = new Viewer({
      plugins: [GyroscopePlugin, StereoPlugin],
      container: document.querySelector("#viewer"),
      panorama: initialImage.path,
      caption: initialImage.caption,
    });
```

```
This dependency was not found:

* photo-sphere-viewer/plugins/gyroscope in ./node_modules/photo-sphere-viewer/dist/plugins/stereo.js

To install it, you can run: npm install --save photo-sphere-viewer/plugins/gyroscope
```

**Comment by mistic100** [comment]
Thank you, the latest version should fix the problem.
