### ISSUE TITLE
example picture flips upside down halfway through 360

### ISSUE THREAD

**Issue by kaosbeat** [mistic100/Photo-Sphere-Viewer#39]
When I use the default included picture, with the example configuration, (or my own) in the most simple implementation the picture flips upside down halfway through the 360. Both in Chrome and safari.

I don't get any javascript feedback in the console, seems errorfree

any ideas?

Thanks

**Comment by mistic100** [comment]
#34

**Comment by kaosbeat** [comment]
afraid building the file does not solve it.
after succesfully building

I included the new files (both js/css) as described in [this](https://gist.github.com/kaosbeat/f3ba32ed7892a599cdbcd68ab7bf1d79)  gist
this seems to be the simplest possible implementation to me, I get:

`photo-sphere-viewer.new.js:251 Uncaught TypeError: Cannot read property 'mixin' of undefined`

in the console

am I on the right branch? in #34 there is a [mention](https://github.com/mistic100/Photo-Sphere-Viewer/issues/34#issuecomment-203970202) of branch 3.2 but I can only find the master

```
$ git branch
  gh-pages
* master
```
 


any ideas?

**Comment by mistic100** [comment]
#36 :-)

**Comment by mistic100** [comment]
mising uevent

**Comment by mistic100** [comment]
There is no mention of a "branch 3.2", he said that "master" IS "3.2 snapshot".
and there is not "branch 3.1" either, it's a tagger release https://github.com/mistic100/Photo-Sphere-Viewer/releases (which, again, you should use)

**Comment by kaosbeat** [comment]
oh I see a pattern here :)
I was missing doT.js as well, but now everything works!

thanks!

**Comment by mistic100** [comment]
After the next release I'll consider creating  a "dev" branch because too many people get confused by master not being a stable branch (which is understandable)
