### ISSUE TITLE
Two fingers overlay is not always hidden on touch end

### ISSUE THREAD

**Issue by smcyr** [mistic100/Photo-Sphere-Viewer#391]
On mobile, with `touchmoveTwoFingers` enabled, the overlay "Use two fingers to navigate" isn't always hidden on touch end. 

Here is a pull request with a fix:
https://github.com/mistic100/Photo-Sphere-Viewer/pull/390
It seems that `this.prop.longtouchTimeout` is sometimes undefined, so I moved the code to hide the overlay outside of the condition.

I am on version 4.0.4 and latest chrome version.

**Comment by mistic100** [comment]
Thank you
