### ISSUE TITLE
Is it available on vue? Tried all afternoon without success

### ISSUE THREAD

**Issue by YYJavaGit** [mistic100/Photo-Sphere-Viewer#392]
Is it available on vue? Tried all afternoon without success，

```
<template>
    <div :style="pageStyle" id="app">
<!--        <page :pageStyle="pageStyle" :onLoad="onLoad"></page>-->
        <div id="div"></div>
    </div>
</template>

<script>
    import page from "./pages/page";
    import website from '@/config/website'
    import {getStore, setStore} from "../../utils/store";
    import { Viewer as PhotoSphereViewer} from 'photo-sphere-viewer';

    export default {
        name: "index",
        components: {page},
        data() {
            return {
                pageStyle: {
                    color: ''
                },
                div: 'div'
            };
        },
        created() {
            let sss = {
                container: document.querySelector('#div'),
                panorama: 'http://10.10.10.129:1888/ftp/lgzhkj/sideroom/index.jpg'
            }
            let viewer = PhotoSphereViewer(sss);
        },
        methods: {
            onLoad() {
                let store = getStore({name: 'style'});
                if (!store) {
                    setStore({
                        name: 'style',
                        content: {style: website.style.default.style}
                    });
                    this.pageStyle = website.style.default.style;
                } else {
                    this.pageStyle = store.style;
                }
            }
        }
    };
</script>

<style>
</style>
``` 
My code
![image](https://user-images.githubusercontent.com/50813117/83002761-01657980-a040-11ea-8ab9-cedafb88f8c3.png)
Error

**Comment by mistic100** [comment]
The documentation uses vuepress, and this component in particular uses the Viewer 
https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/docs/.vuepress/components/CropPlayground.vue

Now I don't really know vue, and your error says nothing about what is happening, that I cannot debug for you.

----

BTW you are missing the "new" keyword when instanciating the viewer

**Comment by YYJavaGit** [comment]
thank you




On 05/27/2020 19:08, Damien Sorel wrote:

The documentation uses vuepress, and this component in particular uses the Viewer
https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/docs/.vuepress/components/CropPlayground.vue

Now I don't really know vue, and your error says nothing about what is happening, that I cannot debug for you.

BTW you are missing the "new" keyword when instanciating the viewer
