### ISSUE TITLE
Can only load image from url link and not in file system

### ISSUE THREAD

**Issue by martinodonnell** [mistic100/Photo-Sphere-Viewer#396]
Versions
```
   Photo-Sphere-Viewer: 3.3.3
   three.js: unknown but downloaded from website
   web browser: Chrome 83.0.4103.61
```

I am trying to load the panoramas from my folders instead of having to go to the internet to fetch them. I have used the code below and it works for online files. I have the code in my repo at https://github.com/martinodonnell/escape-room/blob/master/index.html. Code is at line 142

```
<script>
var PSV = new PhotoSphereViewer({
        container: "viewer",
        panorama:   "https://upload.wikimedia.org/wikipedia/commons/f/f0/Colonia_Ulpia_Traiana_-_Rekonstruktion_r%C3%B6mischer_Schiffe-0010560.jpg",

        caption: "Parc national du Mercantour <b>&copy; Damien Sorel</b>",
        time_anim: false,
        anim_speed: "-2rpm",
        default_fov: 50,
      });
 </script>
```

When I download the file and change it to ` rooms/Colonia_Ulpia_Traiana_-_Rekonstruktion_r%C3%B6mischer_Schiffe-0010560.jpg` I get an unable to load image error. This occurs with any image from other examples I have looked at.

**Comment by mistic100** [comment]
Are you using a local server ? If not you need to use the file protocol.

If that does not work you must use a local server. It might be blocked for security reasons.

Sent from MailDroid

-----Original Message-----

**Comment by martinodonnell** [comment]
Your right @mistic100. I need to use a local server
