### ISSUE TITLE
Upside down image

### ISSUE THREAD

**Issue by siccovansas** [mistic100/Photo-Sphere-Viewer#398]
Versions:
- Photo Sphere Viewer: 3.5.1
- three.js: can't find it, but it is [this file](https://github.com/nextcloud/files_photospheres/blob/master/js/three.min.js)
- Firefox 76.0.1 and Firefox for Android 68.8.1

Some of my images are shown upside down when I view them using Photo Sphere Viewer as implemented in [Nextcloud's 'Photo Sphere Viewer' app](https://apps.nextcloud.com/apps/files_photospheres). It appears to me to be related to the classic problem of smartphones storing images in a wrong rotation based on the orientation of the phone when capturing the image, and then saving that info in the EXIF, but then some programs don't correct for this when viewing the image.

I asked the maintainer of that app for support and he checked if version 4 of photo-sphere-viewer.js solves this problem, but [he ran into this issue](https://github.com/nextcloud/files_photospheres/issues/49):

```
psv.js:11 PhotoSphereViewer: invalid XMP data

three.min.js:131 WebGL: INVALID_VALUE: texImage2D: bad image data
[.WebGL-0x3c3319f0e300]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

So my main question is, can photo-sphere-viewer.js render [this image](https://we.tl/t-4gmfXk2ovp) correctly orientated (either in version 3 or 4), or is this a featured that is not (yet) implemented? (the linked image is larger than GitHub's 10MB attachment limit, so I needed to use an external service)

In any case, thanks for this awesome library!

**Comment by mistic100** [comment]
I don't see any reason why it would be upside down. Nor any metadata that could be used to fix it. If this is because the JPEG data are somehow messed up I cannot do anything.

---

regarding the XMP error, PSV does not check for the "ProjectionType" property, however the CroppedAreaTopPixels value is not valid, it should not be negative.

----

IMHO your image covers such a small portion of the sphere it is not worth displaying it in PSV.

**Comment by siccovansas** [comment]
Thanks for your reply. The image is indeed small for PSV, but was just to point out my problem. If you see no issues with it the I guess version 4 fixes it. Thanks!

**Comment by siccovansas** [comment]
Aah, I misunderstood then. Still it is good to know that my image seems to differ from other images and that causes the issue. Thanks!
