### ISSUE TITLE
Straight lines appear wavy

### ISSUE THREAD

**Issue by mridge-immt** [mistic100/Photo-Sphere-Viewer#40]
Hi,

I've found in a number of different panoramas that the scene looks as if you're viewing it underwater. The majority of straight lines in the image appear wavy, eg:

![wavy-lines](https://cloud.githubusercontent.com/assets/16929625/14729173/df132ed6-086d-11e6-8307-cfc05fff81cb.png)

This isn't as noticeable near the equator, but the further you get from it the more prominent the effect becomes.

Increasing the number of length and width segments in the scene's sphere geometry from 32 to 64 seemed to do the trick. There does still appear to be some straight line waviness but its nowhere near as obvious.

![fewer-wavy-lines](https://cloud.githubusercontent.com/assets/16929625/14729258/b627b4dc-086e-11e6-8c7c-195d935ad676.png)

**Comment by mistic100** [comment]
The result is indeed better, but I'm concerned off possible performances drop.
I'll set it as a parameter (64 by default).
