### ISSUE TITLE
How to use photo-sphere-viewer plugins in vue project

### ISSUE THREAD

**Issue by zhangqwh** [mistic100/Photo-Sphere-Viewer#403]
Hello Dear
  
Thank you! I have found answer in issue #368. Thank you all the same.

  I used the photo-sphere-viewer 4.0.5 version in vue project.
  Now I have met a strange problem.
  I used like this completely copying from guide .
html is as below:
```
<div id="viewer"></div>
```
js part is as:
```
import * as PSV from 'photo-sphere-viewer';
import 'photo-sphere-viewer/dist/photo-sphere-viewer.css';

export default {
  mounted() {
    this.initPhotoSphere();
  },
  methods: {
    initPhotoSphere() {
      const viewer = new PSV.Viewer({
        container: document.getElementById('viewer'),
        // panorama: this.factoryLink,
        panorama: 'https://photo-sphere-viewer.js.org/assets/sphere.jpg',
        size: {
          width: '100%',
          height: screen.availHeight,
        },
        loadingImg: 'https://photo-sphere-viewer.js.org/assets/photosphere-logo.gif',
        caption: '街景图',
        defaultLat: 0.3,
        plugins: [
          [PSV.MarkersPlugin, {
            markers: [ 
              {
                id: 'new-marker',
                longitude: '45deg',
                latitude: '0deg',
                image: 'https://photo-sphere-viewer.js.org/assets/pin-red.png',
              },
            ],
          }] 
        ],
      });
      console.log(viewer);
    }
  }
}
```

But in my last console.log, I can not find the plugins in viewer.

I trace in the photo-sphere-view source code. I print 'plugins' in 'photo-sphere-viewer.js' line 3200, I got a result of 
```
 [undefined, {markers: Array(1)}]
```
I think maybe the undefined in the 0 index cause the problem. But I don't know why it will add the undefined in the first.
Then I changed to other plugins, the problem is the same. 
Hoping for your professional explanations.
Thank you for your help!

**Comment by mistic100** [comment]
Read the guide again, particularly the page about using plugins, and the first sentence of each plugin.

You are not importing from the right file.

Sent from MailDroid

-----Original Message-----

**Comment by mistic100** [comment]
```
import { Viewer } from 'photo-sphere-viewer';
import MarkersPlugin from 'photo-sphere-viewer/dist/plugins/markers';
```

**Comment by zhangqwh** [comment]
Yes. You are right.
I am not rightly import the plugins here. Thank you very much.

**Comment by JuxhinB** [comment]
> ```
> import { Viewer } from 'photo-sphere-viewer';
> import MarkersPlugin from 'photo-sphere-viewer/dist/plugins/markers';
> 
> import 'photo-sphere-viewer/dist/photo-sphere-viewer.css';
> import 'photo-sphere-viewer/dist/plugins/markers.css';
> ```

still its confusing, your reply maybe should be included in the docs ;)

**Comment by gleatherman** [comment]
agreed, the Plugins intro page for ES includes still shows mustaches in the import line, which is not what @mistic100 comment above defines

**Comment by mistic100** [comment]
In two years things changed. The documentation is correct.
