### ISSUE TITLE
Building with Angular 9

### ISSUE THREAD

**Issue by DaveGold** [mistic100/Photo-Sphere-Viewer#407]
## Issues guidelines

With latest Angular 9 and PhotoSphereViewer 4.0.5 I get the following error while building:

An unhandled exception occurred: Script file node_modules/uevent/uevent.min.js does not exist.

I don't know why it is looking for this file.. in most of the code browser.js from uevent is used.

Anyone any idea how to fix this?

**Comment by mistic100** [comment]
Check that you didn't overloaded the resolved version of uevent, this file existed in version 1 but not in version 2.

Beside that I cannot help you. It is certainly not a problem with PSV nor uevent which both have correct dependencies and package definition

**Comment by DaveGold** [comment]
I found the problem. it was defined in the angular.json as script to include in build
