### ISSUE TITLE
Display Angle of View from Photo Sphere Viewer Position

### ISSUE THREAD

**Issue by CalebM1987** [mistic100/Photo-Sphere-Viewer#409]
- **Indicate your Photo-Sphere-Viewer, three.js and web browser versions**
Photo-Shere-Viewer - version `4.0.5`
Three.js - version `0.106.2`
Browser - Google Chrome Version 83.0.4103.106 (Official Build) (64-bit)

Not an issue, but a question. We are attempting to display panoramic images within a map context by using the GPS info obtained by each image's EXIF data.  As part of this, we want to display the angle of view as the user moves around the x-axis in the PSV (`PSV.Poisition.longitude`) in degrees (0 or 360 is `North`, 180 is `South`, 270 is `West` and 90 being `East`).

My initial attempt at this seemed promising, as I thought I would start with the `GPSImgDirection` attribute from the GPS metadata, [convert the radians to degrees](https://www.rapidtables.com/convert/number/radians-to-degrees.html) from the viewer position's `longitude` value (Relative Bearing), and add that to the original image bearing:

`GPSImgDirection + Math.round(PSV.Viewer.prop.position.longitude * 57.2958)`

In a sample project of 152 images, this seems to work half of the time.  This makes me wonder if it is an error due to the sensors or more likely there is a better way to calculate this value.  I tried to look through the documentation and even some of the source code to see if there is any "real world angle" being calculated anywhere, but couldn't find anything.  I also tried to research the `GPSImgDirection` of exif data in panoramic to see if that denotes where the panorama started or if it is the center of the photo (my code is assuming center) but also came up empty.  Has anyone had any success doing this?

![image](https://user-images.githubusercontent.com/6826046/85314328-f6efa180-b47e-11ea-9c4e-6db986585934.png)

I have put together a little [JS Fiddle](https://jsfiddle.net/calebma/t0fczhwn/114/) that shows what I have tried so far.  It contains an array (named `images`) of 6 panoramic photos where the first three seem to be fairly accurate (denoted by the `seemsLegit` property in the JSON) while the last 3 images seem to be off by as much as 180 degrees.  This is using [Vue.js](https://vuejs.org/) and I am updating the Relative Bearing from the `PSV.Position.longitude` value from the `position-updated` event.  The image's exif data can be viewed by clicking on the table button on the `PSV.navbar`.

Fiddle Link:
[https://jsfiddle.net/calebma/t0fczhwn/114/](https://jsfiddle.net/calebma/t0fczhwn/114/)

**Comment by mistic100** [comment]
I don't know what I can asnwer to this....

If your code is working for most images you obviously have a problem in your data. There is no "random" in the library.
The three "no legit" images also have a strong tilt.

**Comment by CalebM1987** [comment]
It certainly could be an issue with the data collection, as half of the images seem to be way off.  However, some images that are off do **not** seem to have any tilt at all which in retrospect I should have included one of those samples in the fiddle.

Feel free to close this if you think it is purely a data issue.  I never assumed it was an issue with the library, what my long winded question boiled down to was "is this how you would calculate the viewer angle?".  If the answer is yes, then I'll just roll with what I have and put a disclaimer that some issues with the GPS collection can cause distortion in the map view angle.  Thanks for the quick response.

**Comment by mistic100** [comment]
Yes I don't know how it could be done better : orientation of the image (gps data) + viewer longitude = viewed orientation

BTW you should use `Math.PI / 180` instead of an hardcoded value, but it won't fix your issue.

**Comment by CalebM1987** [comment]
Thanks, will do.
