### ISSUE TITLE
The same image is loaded twice

### ISSUE THREAD

**Issue by jeenoshibu** [mistic100/Photo-Sphere-Viewer#416]
Version
THREE.WebGLRenderer 102
Photo Sphere Viewer 3.5.1

The same image is loaded twice when ever we initialize the photospere.

 Below is the code we used
`PSV = new PhotoSphereViewer({
                container: 'photosphere',
                panorama: 'https://photo-sphere-viewer.js.org/assets/sphere.jpg',
                time_anim: 10,
                cors_anonymous: true,
                navbar: [
                    'autorotate',
                    'fullscreen',
                    'markers'
                ],
                default_long: 0.3,
                defaultLat: 0.3,
                loading_img: '~/Content/assets/photosphere-logo.gif',
                anim_speed: '1rpm'
            });`

**Comment by mistic100** [comment]
This has ben fixed in version 4
