### ISSUE TITLE
Render Black

### ISSUE THREAD

**Issue by Davidx7** [mistic100/Photo-Sphere-Viewer#42]
New version doesn't work. 
It's all black when loaded, even the git example. 

Version from 3,4 days ago working fine. 

UPDATE:
I don't have any errors or warning to report. Everything is the same as usual, except the image is not at all rendered, all is black

**Comment by Davidx7** [comment]
Fixed. My fault

**Comment by mistic100** [comment]
Please elaborate for other people :-)

**Comment by Davidx7** [comment]
If the 360 starts as black and does not provide any error, go here `https://github.com/mrdoob/three.js/tree/master/examples` and take these modules `PSVError: Missing Three.js components: EffectComposer, RenderPass, ShaderPass, MaskPass, CopyShader. Get them from threejs-examples package.`

Sometimes the error doesn't appear. 

Also, careful with the `grunt` builder, as it needs `Ruby` installed to work (which is not comfortable at all) or else it generates a empty `.css` file and the plugin fails silently, again.

**Comment by mistic100** [comment]
Installing Ruby is a very little drawback for having the power of SASS :-)
And most people don't have to build the lib.
