### ISSUE TITLE
Multi resolution triggered by zoomlevel

### ISSUE THREAD

**Issue by mrAceT** [mistic100/Photo-Sphere-Viewer#420]
I have searched the documentation, but could not find the possibility to load a higher resolution image on passing a certain zoom level, do I need to play around with that plugin? Or is it there somewhere?

**Comment by mistic100** [comment]
Currently the viewer can only load one single texture for the whole sphere, and it's resolution is limited by the browser.

If https://github.com/mistic100/Photo-Sphere-Viewer/issues/243 is one day implemented it could be enhanced to have multiple resolutions for each tiles.

**Comment by mrAceT** [comment]
Yes and no. The viewer already supports 6 tile cubic sphere photo's that is more then large enough for me. What I am hoping to accomplish is that there is a basic (lower quality) image and that I can change (read: increase the resolution/quality) of the image when the visitor starts to zoom in. That seems to be an option looking at the "resolution plugin".. ar that it could be enhanced to do that..

**Comment by mrAceT** [comment]
As my first dive into the PSV code, I couldn't find a "on zoom change" event, so I had to use an interval, but is does work!

For those who might search a similar solution:

` var PSV = new PhotoSphereViewer.Viewer({
    container      : 'photosphere',
    panorama       : 'sphere_small.jpg',//'sphere.jpg',
    caption        : 'Parc national du Mercantour <b>&copy; Damien Sorel</b>',
    loadingImg     : 'assets/photosphere-logo.gif',
    defaultZoomLvl : 10,
  });
  setInterval(function () {
    console.log(PSV.getZoomLevel()+' '+PSV.PanoData);
    if (PSV.getZoomLevel() > 30
     && PSV.config.panorama != 'sphere.jpg' ) {
      PSV.setPanorama('sphere.jpg',{showLoader:false});
    }
  },500); `

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/guide/events.html#zoom-updated-level

**Comment by mrAceT** [comment]
great!
Updated my little piece of code to:

  PSV.on('zoom-updated', (e,ZoomLevel) => {
    console.log(ZoomLevel+' '+PSV.config.panorama);
    if (ZoomLevel >= 15
     && PSV.config.panorama.indexOf('_small.jpg') > 0 ) {
      PSV.setPanorama('cave1.jpg',{transition:3000,
                                    showLoader:false});
    }
  });

**Comment by mistic100** [comment]
I close this issue in favor of #773 and/or the existing resolution plugin.

I don't think loading huge files on zoom event is a good approach (and rather limited especially on mobile where the max texture size is 4096px)
