### ISSUE TITLE
Rotate some faces in a cubemap

### ISSUE THREAD

**Issue by saeedzr** [mistic100/Photo-Sphere-Viewer#422]
I didn't find any options to rotate single faces in a cubemap. The top and bottom faces of my cubemap images need 180 degree rotation to match the other faces. Is there any way to specify that?

**Comment by mrAceT** [comment]
wouldn't it be the simplest solution, to simply rotate the images in question?

(I expect that PSV adheres to the standards)

**Comment by mistic100** [comment]
No there is no option for that, your images must match the expected orientation.

Sent from MailDroid

-----Original Message-----

**Comment by saeedzr** [comment]
> wouldn't it be the simplest solution, to simply rotate the images in question?
> 
> (I expect that PSV adheres to the standards)

Yes but that was not my question!
We are using pure three.js now and there is support for that, I was wondering if I am missing some part of the documentation. I would've liked to skip this "simple" solution you mention to have a cleaner implementation!

> No there is no option for that, your images must match the expected orientation. Sent from MailDroid

Thanks for the reply, would be great to add it at some point, three.js supports that.
