### ISSUE TITLE
Trouble getting PSV to work on my live server (UTF8..)

### ISSUE THREAD

**Issue by mrAceT** [mistic100/Photo-Sphere-Viewer#425]
On my local test server I see this on line 56 of my markers.js:

`var λ1 = p1[0],`

On my live server I see:

`var Î»1 = p1[0],`

For more widely compatibility, could you rename those special characters to more UTF8 stuf?
like :
`var Lambda1 = p1[0],`

etc.. I could dig trough the code and do it manually, but that would make updating to a newer version more difficult..

PS: I wanted to share some "cool additions" which might be nice to include into a next version maybe, but I got stuck at publishing

**Comment by mistic100** [comment]
This character IS UTF8. If your server cannot handle it you will run into a lot of trouble (I can think of Angular which uses exotic variables too, but most certainly other libraries too).

The dev server used by "npm start" works perfectly.

Sent from MailDroid

-----Original Message-----

**Comment by mrAceT** [comment]
Haven't had any trouble up until now though!
Working on replacing that server ;)

For now I did a search / replace on:
λ -> Lambda
φ -> Phi

in: dist/photo-sphere-viewer.js
and: dist/plugins/markers.js

And everything works :)
