### ISSUE TITLE
Async loading of cubemap tiles

### ISSUE THREAD

**Issue by mrAceT** [mistic100/Photo-Sphere-Viewer#426]
When I look at the network tab in FireFox I get the distinct impression all 6 tiles are loaded immediately of a "cube 360 image set"

When one has a multitude of panorama images where one can click from one to the next, chances are quite good if there were an option to "lazy load" those six cubical images (only load the ones that are "in view") things would speed up quite a bit, not in the last place because 360 images tend to get quite big... Also bandwidth usage would reduce..

Could this be implemented?

**Comment by mistic100** [comment]
At default zoom level you will most likely have to load 5 files anyway, so it's **very** little optimization.

The real optimisation is to start from the tile in front of the user and load the rest asynchronously.

**Comment by mistic100** [comment]
I didn't made any change to the Cubemap adapter, but I did add a [Cubemap Tile adapter](https://photo-sphere-viewer.js.org/guide/adapters/cubemap-tiles.html)

The trick is it can be used with `nbTiles: 1` (it is buggy currently but I will fix it) thus effectively asynchrounously loading each face.

It is not released yet, this this issue will be notified once the version is published.
