### ISSUE TITLE
Enabling gyro does not resume camera from last position

### ISSUE THREAD

**Issue by nushydude** [mistic100/Photo-Sphere-Viewer#429]
Hi,

Version: 3.6.0.

This might not be a bug, but could be a feature request if already not supported by the library. 

When I enable gyroscope, it would always reset the camera to a default position. Doesn't matter which way I'm facing when I enable it, or where the camera was pointing before I enable it.

Seems to be this code [here](https://github.com/mistic100/Photo-Sphere-Viewer/blob/v3/src/js/PhotoSphereViewer.public.js#L336
) is supposed to "resume" the gyro orientation from the camera's last position,
 but it doesn't as per this [demo]( https://romantic-bose-baed03.netlify.app) (try on Chrome Android. iOS should be OK, but will have to grant permission and reload the page)

iOS Safari on iPad faces South box every time I enable gyro.
Chrome on Android faces West box every time I enable gyro. 
Before gyro is enabled, the camera faces North box at startup.

[This ](https://github.com/nushydude/photossphereviewer-gyro-test) is the repo for the above demo.
All the code is in [this file](https://github.com/nushydude/photossphereviewer-gyro-test/blob/master/src/App.js).

**Comment by mistic100** [comment]
Can you confirm it still does not work on v4 ?

The computation of alphaOffset changed : https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/plugins/gyroscope/index.js#L195

**Comment by nushydude** [comment]
Haven't been able to get the gyro plugin to work on v4. 
I think I have successfully specified the gyro plugin.
import: https://github.com/nushydude/photossphereviewer-gyro-test/blob/master/src/App.js#L7
specify in config: https://github.com/nushydude/photossphereviewer-gyro-test/blob/master/src/App.js#L52

But when I call getPlugin ([here](https://github.com/nushydude/photossphereviewer-gyro-test/blob/master/src/App.js#L184)), I get this.plugins is undefined error on this [line](https://github.com/mistic100/Photo-Sphere-Viewer/blob/04cb8edf0e754fd58f4023c52559fb8676f5df18/src/Viewer.js#L340).

I can't figure out what I'm doing wrong.

**Comment by mistic100** [comment]
IDK, it works on the examples

**Comment by nushydude** [comment]
I get the same error with this code.  

```
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.css"/>

  <style>
    /* the viewer container must have a defined size */
    #viewer {
      width: 100vw;
      height: 100vh;
    }

    #gyro {
      position: fixed;
      top: 30px;
      left: 30px;
      padding: 20px;
      z-index: 2;
    }
  </style>
</head>

<body>
  <div id="viewer">
    <button id="gyro">
      Toggle Gyro
    </button>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/three/build/three.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/uevent@2/browser.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/plugins/gyroscope.min.js"></script>
  <script>
    var viewer = new PhotoSphereViewer.Viewer({
      container: document.querySelector('#viewer'),
      panorama: './f4399f2b0b4bd8ba8406908b798add0b.jpg',
      navbar: ['autorotate'],
      defaultZoomLvl: 60,
      defaultLat: 0,
      defaultLong: 0,
      size: {
        width: window.innerWidth,
        height: window.innerHeight,
      },
      plugins: [
        PhotoSphereViewer.GyroscopePlugin,
      ],
    });

    var btn = document.querySelector('#gyro');

    if (btn) {
      btn.addEventListener('click', function onClick() {
        var gyro = new viewer.getPlugin(PhotoSphereViewer.GyroscopePlugin);

        if (!gyro) {
          console.log('gyro unavailable?');
        } else if (typeof gyro.isEnabled === 'function') {
          console.log('gyro.isEnabled():', gyro.isEnabled());
        } else {
          console.log('no isEnabled fn found?');
        }
      });
    }
  </script>
</body>
```

Error:
```Viewer.js:340 Uncaught TypeError: Cannot read property 'gyroscope' of undefined
    at new i.getPlugin (Viewer.js:340)
    at HTMLButtonElement.onClick (index.html:57)
```

Here's the link to the panorama file if you'd like to test yourself:
![f4399f2b0b4bd8ba8406908b798add0b](https://user-images.githubusercontent.com/12478046/88550921-94815680-d065-11ea-852e-93a49e69c2e0.jpg)

Could be a problem with the released dist files? I'll try our your examples directly from the repo tomorrow. It's late for me.

**Comment by mistic100** [comment]
```
var gyro = new viewer.getPlugin(PhotoSphereViewer.GyroscopePlugin);
```

why "new" ? this is your error.

-----

I tested on V4, the gyroscope does not keep the current position. I will fix it.

**Comment by nushydude** [comment]
> why "new" ? this is your error.
oh sorry, must have misunderstood the docs. my bad. 

>I tested on V4, the gyroscope does not keep the current position. I will fix it.
that's great! glad something useful came out of this discussion.

Just FYI, the main reason for all this is so that I can feed in compass data to orientate the camera in real-world when the gyro is active. Basically, when the user is facing North and the gyro is activated, he should be seeing the North box of my image. I know the compass is hardly accurate even when properly calibrated and only gives absolute heading in iOS Safari and Chrome (Chromium-based all?) via non-standard events, but this is the best option I have without the help of AR. 

So in this case, once you fix the position issue, I think what I would need to do is to `rotate` the camera first to where I want the camera to be facing using the data from the compass, and then turn on gyro? I wish it was possible to use the `rotate` method while the gyro is enabled as well. The behaviour would be like touch panning when the gyro is enabled (only rotates along the longitudinal axis).

**Comment by mistic100** [comment]
>  I wish it was possible to use the rotate method while the gyro is enabled as well.

You can

**Comment by nushydude** [comment]
> > I wish it was possible to use the rotate method while the gyro is enabled as well.
> 
> You can

That's great! It didn't work on v3.6. In v4.0.6 it's working perfectly. So I don't really have to wait for the 4.0.7!!!
