### ISSUE TITLE
`move_inertia` makes image "cut"

### ISSUE THREAD

**Issue by Davidx7** [mistic100/Photo-Sphere-Viewer#43]
When `move_inertia: true` is enabled, the image gets "cut" if you move it fast (this didn't happen before). I can't figure out why, but its easy to replicate. 

Just move fast right-left and the stop pressing and press again. 
Has weird behavior

**Comment by mistic100** [comment]
I don't understand anything.

**Comment by Davidx7** [comment]
The image flickers weirdly and randomly when doing what I described, if intertia is true

**Comment by mistic100** [comment]
No, definitely I can't reproduce with such little info. Record a video if you want.
And as you describe it, it does not seem to be the regular usage.
