### ISSUE TITLE
I try to add markers and not working. What i made bad?

### ISSUE THREAD

**Issue by Togarcia** [mistic100/Photo-Sphere-Viewer#434]
This is the code i have, is a exemples of our documentation y paste the code:

[Code.txt](https://github.com/mistic100/Photo-Sphere-Viewer/files/5022716/Code.txt)

I just try add marker on viewer when load page(thats not work), and after clicking on any point of image put another marker. When i click on picture and try to add new marker show the next error:

viewer.getPlugin(PhotoSphereViewer.MarkersPlugin) return null

*i think i have loaded markers plugin.
What i made bad?
Srry for my english.

**Comment by mistic100** [comment]
the plugin js file must be included **after** the main js file

I am sure you have an error in the console saying PhotoSphereViewer is undefined or something
