### ISSUE TITLE
Mouse move

### ISSUE THREAD

**Issue by Darq2016** [mistic100/Photo-Sphere-Viewer#44]
How can I move the image while it is still in autorotate mode (I mean, without having to click the rotate button first)?

**Comment by mistic100** [comment]
You can't. That's seems a little contradictory...

**Comment by Darq2016** [comment]
The previous version immediately stops the autorotate mode when mouse-pan begins. Cannot do that any more?

**Comment by mistic100** [comment]
Oh so automatically stopping the animation then.
For compatibility with the various animations and interactions I had to remove it.

**Comment by Darq2016** [comment]
Thanks!

**Comment by Darq2016** [comment]
Thanks for your help Damien. Sorry I waste your time with little stuff.
I want you to know that muy photo sphere viewer is working real nice now.
Thanks again.

**Comment by mistic100** [comment]
Good news :)

**Comment by mistic100** [comment]
I reopen this because it's indeed frustrating. Will try to find a way.
