### ISSUE TITLE
blurry on mobile vs desktop

### ISSUE THREAD

**Issue by tlamber** [mistic100/Photo-Sphere-Viewer#440]
It appears that when you load a 16k x 8k panorama it is quite pixelated on mobile vs desktop. 

Also, it appears that the zoom at 100% is quite limited vs the actual image level. 

Are there any solutions to these issues? 

Thank you!

**Comment by mistic100** [comment]
Do you have any example ? And screenshot ?

What does "mobile Vs desktop" mean ? Is it pixelated on desktop or on mobile ?

You need to be easy more detailed when you open such issues.

Sent from MailDroid

-----Original Message-----

**Comment by tlamber** [comment]
I apologize.  I will share a jsfiddle later today.  Thanks for your help Mistic!  You are an amazing person.

**Comment by tlamber** [comment]
I prepared a basic sample at http://prosperxr.com/panoblur

It's literally just the most basic pano viewer possible, with only a panorama and a container specified.   There is also a min and max fov specified.

When you zoom in on mobile it looks horrible.  When you zoom in on laptop or desktop it looks wonderful.  It's a ~16k image.  

Do you have any suggestions as to why it might have such incredible down resolution on mobile?

Below you will see two screenshots that show the issue.

This is desktop.  You will notice how all the text is readable.
![image](https://user-images.githubusercontent.com/5283570/92047115-205b6200-ed39-11ea-99c1-73e59cad9ffa.png)

This is mobile.  You will notice how all the text in the image is blury.
![image](https://user-images.githubusercontent.com/5283570/92047259-83e58f80-ed39-11ea-9aa5-8f78e775e2be.png)

**Comment by tlamber** [comment]
Also, just so you can see... it's just a standard implementation.  The min/maxFov have no impact on the blur / no blur issue.

Is it perhaps reducing the resolution for mobile?   It sort of makes it unusable with the resolution reduction.  Thanks for any help you can provide!!

var viewer = new PhotoSphereViewer.Viewer({
    container: document.querySelector('#viewer'),
    panorama: 'http://prosperxr.com/images/360/visitorcenter.jpg',
    navbar: 'autorotate zoom caption fullscreen',
    mousewheel: true,   
    minFov: 15,
    maxFov: 90,

});

**Comment by mistic100** [comment]
First thing to try is to add this meta to your <head>

```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

**Comment by mistic100** [comment]
off topic : how did you take the photo ? the quality is great

**Comment by mistic100** [comment]
Also the resolution is indeed reduced on mobile depending on the capabilities announced by the device, this is a hard limitation, it cannot be bypassed without #243

**Comment by tlamber** [comment]
Oh, thank you for your help!  I'll try a cube map :)

Ironically lowering the resolution from 20k to 8k increased mobile quality by about 2x.  It decreased desktop quality by about 2x as well.  Perhaps a parameter for "image for mobile" and "image for desktop" would be useful.  

We shot the panorama with a 5d mark iv and a 17-40mm lens set to 17mm.   16 images with a 30% overlap nodally captured and stitched with PTGui Pro using their masking option to remove stitch lines.  :)
