### ISSUE TITLE
When setParonama is outside the instance object, the paronama data changes but the scene is not re-rendered

### ISSUE THREAD

**Issue by qiqixyq** [mistic100/Photo-Sphere-Viewer#442]
const that = this
    var PSV = new Viewer({
      container: document.getElementById("viewer"),
      panorama: base64List[0],
      caption: '',
      navbar: [
        'autorotate',
        'zoom',
        'download',
        {
          title: '切换场景',
          className: 'custom-button',
          content: '🔄',
          onClick: (function ABC () {
            return function () {
              let A = that.state.base64List
              PSV.setPanorama(A[0], { longitude: 0, latitude: 0, zoom: 50 })
              .then();
            };
          }()),
        },
        'caption',
        'fullscreen',
      ],
      sphereCorrection: { roll: 0 },
    })
    let B = this.state.base64List
    debugger
    PSV.setPanorama(B[0], {zoom: 0}, true).then()
//The second PSV.setPanorama will run, B[0] data will also change paronama, but the scene will not change

**Comment by mistic100** [comment]
As said in the doc https://photo-sphere-viewer.js.org/guide/methods.html#presentation you must at least wait for ready event

Otherwise please setup a working demo
