### ISSUE TITLE
Black screen when rerender panorama

### ISSUE THREAD

**Issue by Ulgerd** [mistic100/Photo-Sphere-Viewer#443]
Hello! 

When I rerender panorama there is 50/50% chance, that it would be a black screen. 
There is no errors or anything. 
The only difference I found, that canvas height in 'psv-canvas-container' equals to 0.
<img width="455" alt="Снимок экрана 2020-09-10 в 15 28 30" src="https://user-images.githubusercontent.com/16854572/92732496-38f1fa80-f37f-11ea-969a-0424f4bdc4ac.png">

When I manually resize browser, it appears. So, I tried to rerender panorama when it's ready but it didn't work. 
Changing panorama with a new one via setPanorama didn't help as well. 

So, now I'm out of ideas why is this happening or how I can fix it.

**Comment by mistic100** [comment]
Demo ?
