### ISSUE TITLE
Future Support for default panel size

### ISSUE THREAD

**Issue by tlamber** [mistic100/Photo-Sphere-Viewer#444]
I was curious if you would be willing to add a parameter that allows users to adjust the default panel size?  Or if you could provide guidance on how to adjust this by altering the plugin itself?

We are hoping to make the side panel larger by default.  I have been trying to figure this out but am having some trouble.

Thanks Mistic!!

**Comment by mistic100** [comment]
Try this CSS after the main stylesheet :

```css
.psv-panel {
  width: 50vw;
}
```

however I will make an option for that

**Comment by tlamber** [comment]
The world is fortunate to have someone like you mistic!  Thanks for adding this feature.  

Setting width: 50vw; with .psv-panel wont work unfortunately as the css size is set inline via javascript which over-rides anything from a stylesheet.  It might with the !important declaration but then it would prevent the incredible panel resize functionality.

**Comment by mistic100** [comment]
Did you try ? It **does** work.
The initial width is pure CSS, the inline width is only applied when resizing.

**Comment by tlamber** [comment]
Oh, it does work!  I accidentally put the css in the wrong position, so the imported stylesheet overwrote my changes.

Yes, thank you mistic!  Thank you so much!
