### ISSUE TITLE
Cubemap breaks all circle markers

### ISSUE THREAD

**Issue by tlamber** [mistic100/Photo-Sphere-Viewer#445]
Hi Mistic,

I prepared a .jsfiddle so you could see.

 https://jsfiddle.net/hj7w15go/1/

If use a cubemap, you can not use circle markers.  I commented out a regular panorama so you could see that if you uses a regular panorama you can use circle markers.

**Comment by mistic100** [comment]
Hello

did you look at the console ?
> uncaught exception: PSVError: Unable to use texture coords with cubemap.

if you use longitude/latitude it works

**Comment by mistic100** [comment]
I added a note in the documentation
