### ISSUE TITLE
Feature Request - Different panorama image on mobile vs desktop

### ISSUE THREAD

**Issue by tlamber** [mistic100/Photo-Sphere-Viewer#447]
After much trial and error, I have found that a 13k image loaded as a cube map looks exponentially better than any other viewing options on mobile.

However, a 20k image loaded as a cube map looks better on desktop but exponentially worse on mobile.

Is there anyway we can load a different panorama on mobile vs desktop?

**Comment by mistic100** [comment]
There are many ways to detect mobile devices. Choose the one that suits you and switch your code accordingly.
I don't think this is the job of the library.
