### ISSUE TITLE
Change image

### ISSUE THREAD

**Issue by Darq2016** [mistic100/Photo-Sphere-Viewer#45]
How can I replace the "Change image" icon in the navbar with a text-link?

**Comment by mistic100** [comment]
Are you talking about the example page ? You just have the change the "content" and put anything you want here. Also use CSS  (with "className") if the size does not suit you.

**Comment by Darq2016** [comment]
I create a .custom-button class in css but it doesnt seems to do anything. What Im doing wrong?

**Comment by mistic100** [comment]
Come on ! without example I can't help you at all.

**Comment by Darq2016** [comment]
.custom-button{
  padding: 0,20px;
}

**Comment by mistic100** [comment]
..... a real example, something online

BTW your CSS is wrong, it's `padding: 0 20px;`
I don't want to be harsh but this is really basic, I have no time to teach CSS/JS to anyone.

**Comment by Darq2016** [comment]
Sorry. Will try this. Thanks a lot.
