### ISSUE TITLE
Focus issue for polygon marker

### ISSUE THREAD

**Issue by JuxhinB** [mistic100/Photo-Sphere-Viewer#450]
This is an issue I am facing in a project of mine.

The issue illustrated also in your demo.

https://jsfiddle.net/mistic100/kdpqLey2/

**Comment by mistic100** [comment]
@JuxhinB you didn't describe the problem

**Comment by JuxhinB** [comment]
After adding a polyline marker, going to the side list of markers, and click on the marker.....the issue is that PSV points to the opposite direction.

Check your fiddle for the red-ish area marker. if you go at the markers list and click on "A dynamic polygon marker" you can see what is happening. I don't believe that is the expected behavior or is it?

**Comment by mistic100** [comment]
ok understood

**Comment by mistic100** [comment]
the problem seems to be only when the polygon/polyline is crossing the origin (longitude=0). It's much complex than anticipated to fix it.

**Comment by mrAceT** [comment]
I had the same ting, I was testing something and wanted to draw a line in the full 360 degrees to mark the horizon.. I ended up doing it in two steps.. should have mentioned it here also.. sorry:

```
  // the horizon is drawn (for testing.. | could't get it in one line, bug? )
  GeoArchive.markers.addMarker({
            id        : 'Horizon1',
            polylineRad: [
              [Math.PI*0.0, 0],
              [Math.PI*0.5, 0],
              [Math.PI*1.0, 0],
            ],
            svgStyle  : {
              stroke        : 'rgba(255, 0, 0, 0.5)',
              strokeLinecap : 'round',
              strokeLinejoin: 'round',
              strokeWidth   : '1px',
            },
          });
  GeoArchive.markers.addMarker({
            id        : 'Horizon2',
            polylineRad: [
              [Math.PI*1.0, 0],
              [Math.PI*1.5, 0],
              [Math.PI*1.999999999, 0],
            ],
            svgStyle  : {
              stroke        : 'rgba(255, 0, 0, 0.5)',
              strokeLinecap : 'round',
              strokeLinejoin: 'round',
              strokeWidth   : '1px',
            },
          });
```

**Comment by mistic100** [comment]
@mrAceT this is not exactly the same problem. Your problem is that the viewer cannot determine how to re-project the vertex behind the camera, especially when they have the same effective coordinate (2PI=0) but are functionally different.

The `polygon-sky` in the example file is an extreme example of what my system can handle (it covers the whole sky).

(FYI there are some ugly maths here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/plugins/markers/index.js#L760-L780)
