### ISSUE TITLE
Use overlay image

### ISSUE THREAD

**Issue by indiboy** [mistic100/Photo-Sphere-Viewer#456]
change to base64 code merge？

**Comment by mistic100** [comment]
please reformulate your request, it makes not sense to me

**Comment by indiboy** [comment]
i means like MarkersPlugin,but is not add a Markers, is add other photo to canvas and merge [panorama] photo。
two photo merge one photo，360 view。two .png files merge one .png to canvas.

**Comment by indiboy** [comment]
![未命名-1](https://user-images.githubusercontent.com/5752024/97795668-ac0f4300-1c43-11eb-858a-64a90c7e5bf1.jpg)

**Comment by indiboy** [comment]
top pic is  [panorama] photo,add bottom pic into top pic ,merge and 360 views.

**Comment by indiboy** [comment]
![未命名-1](https://user-images.githubusercontent.com/5752024/97795726-afef9500-1c44-11eb-9ca4-81e312985a02.jpg)

![未命名-1](https://user-images.githubusercontent.com/5752024/97795725-a403d300-1c44-11eb-904d-501b91317ad2.png)

**Comment by mistic100** [comment]
Photo Sphere Viewer cannot use two images. But it is simple to do it yourself :

- create a canvas object
- draw the two images
- get the result with toDataURL
- call setPanorama directly with the base64 URL

Sent from MailDroid

-----Original Message-----

**Comment by indiboy** [comment]
thank you，i think this is a amazing function for users, user scene is more,do you want make a Plugin for this?
非常感谢您的回复。

**Comment by mrAceT** [comment]
Hmmm, this has the potential to create something to overlay an image inside a 360 image..

Back on my "figure it out list" ;)
