### ISSUE TITLE
PSV not displaying properly

### ISSUE THREAD

**Issue by ssoldy** [mistic100/Photo-Sphere-Viewer#458]
Hi i'm using photo-sphere-viewer@4.0.7 i was just trying to copy this example https://jsfiddle.net/mistic100/5r684etx/ but i see this
<img width="1440" alt="Screenshot 2020-11-06 at 15 49 47" src="https://user-images.githubusercontent.com/45917574/98379820-0a736180-2048-11eb-8aaf-02be6327765e.png">

i'm also using Angular 10 & have set a dimension for the viewer container, can't figure out what the problem might be

**Comment by mistic100** [comment]
did you included the stylesheet ?
https://photo-sphere-viewer.js.org/guide/#your-first-viewer
