### ISSUE TITLE
Photo-Sphere-Viewer 4: getPanoramaCache does not exist anymore

### ISSUE THREAD

**Issue by Biboba** [mistic100/Photo-Sphere-Viewer#459]
## Issues guidelines

- **Indicate your Photo-Sphere-Viewer, three.js and web browser versions**:
Photo-Sphere-Viewer: 4.0.7
Three.js: 0.120.1
Chrome: 86.0.4240.183

Hello,

Thanks for this very nice v4 update ! Much appreciated !

So I tried to migrate an application using v3 to v4 but I am currently facing an issue with cache management.
I understand from the documentation that you are now leveraging Three.js cache rather than your own implementation:
https://photo-sphere-viewer.js.org/guide/#your-first-viewer

I would like to be able to retrieve a panorama from the cache but I am currently unable to do so. Indeed, I used to use 'getPanoramaCache' method which following the documentation has been moved to the texture object:
https://photo-sphere-viewer.js.org/guide/migration-v3.html#moved-methods

But actually this method does not exist and I have the following error:
```
Uncaught TypeError: this.viewer.textureLoader.getPanoramaCache is not a function
```
I tried to manually access it using Three.js but if I import three on a side, it is not the same cache (and it is by default disabled) so I cannot access it.

Is it a method you forgot to migrate but did I miss anything ?

Thanks !

**Comment by mistic100** [comment]
if you do this there is not reason it is not the same cache

```js
import * as THREE from 'three';

THREE.Cache.get(panoUrl);
```

**Comment by Biboba** [comment]
Thanks for your quick reply.
I tried this but three was not found. Looking at 'node_modules' folder, I saw three installed as a dependency of your package and seems like it cannot be directly imported. So I had to install three as a side dependency and as a consequence the cache is not the same.

Just in case, I could do a PR if you want:
https://github.com/Biboba/Photo-Sphere-Viewer/commit/e7bb8b397e5ccc1f96e4f847eb827de3f7b1bcbf

Thanks !

**Comment by Biboba** [comment]
It is basically the same issue as described here:
https://stackoverflow.com/questions/9736514/require-dependency-of-another-dependency-in-node-modules

Maybe Three could be exposed as a Photo-Sphere-Viewer property ?

**Comment by Biboba** [comment]
But as mentionned on the stackoverflow, the following works
```
import * as THREE from 'photo-sphere-viewer/node_modules/three';
```
and you do have access to the cache.

**Comment by mistic100** [comment]
What is your package manager ? Transitive dependencies should hoisted (moved to the top level node_modules). Unless you depend on another package that uses a different versions of three.

Anyway it is not PSV job to handle such cases.

----

I am ok for the change your propose, but the method should  be at the bottom of the file after "preloadPanorama", and if you want to be complete, "clearPanoramaCache" is needed too (stating is clears the whole THREE cache)
