### ISSUE TITLE
Loading panorama after creating viewer instance

### ISSUE THREAD

**Issue by query-wow** [mistic100/Photo-Sphere-Viewer#460]
## Issues guidelines

Hi, first of all thank you for your plugin.
I'm currently trying to "lazy load" a panorama with markers, but the image is always grey. It works if i resize the window.

Example
https://imgur.com/a/lj0fb9u

Code:
https://gist.github.com/query-wow/1e17b4a25d98863ae9a35e35f701f6e8

Example of the code 

```js 
var manager = new PanoramaManager(document.getElementById('VTImage'));
if (media.waypoints.length)
{
      markers = manager.createHtmlMarkers(media, media.waypoints);
}

if (media.doorways.length)
{
	if ($.isArray(markers))
	{
		markers.push(manager.createHtmlMarkers(media, media.doorways));
	}
	else
	{
		markers = manager.createHtmlMarkers(media, media.doorways);
	}
}

manager.addPanorama(media.imageSrc, markers);
```

**Comment by mistic100** [comment]
Please put the demo online.

**Comment by query-wow** [comment]
Good morning, as requested an example of the behaviour https://jsfiddle.net/21jvL48p/2/

**Comment by mistic100** [comment]
You cannot initialize the viewer while it's container is hidden.

if you show #wrapper before initializing the viewer it works.

**Comment by query-wow** [comment]
Thank you for your time!
On a side note, is it possible to simulate a click on the canvas? i'm dragging and dropping markers into it and i'd like to know the lat and lon of where the user releases the mouse

**Comment by mistic100** [comment]
use `dataHelper.viewerCoordsToVector3` then `dataHelper.vector3ToSphericalCoords`
