### ISSUE TITLE
How to convert my own svg to Photo Sphere Viewer

### ISSUE THREAD

**Issue by benyuanzhang-Zhang** [mistic100/Photo-Sphere-Viewer#461]
## version
| name                | version       |
| ------------------- | ------------- |
| Photo-Sphere-Viewer | 4.0.7         |
| Google Chrome       | 86.0.4240.183 |

## issue
Hello guy,
	It's an honor to use your product. 
	I have a special request. I need to create a Svg myself and convert it to a 3D image. We can put it in PSV, but every time we move or change PSV, svg will recover.
	Do you have any good ideas?

**Comment by mistic100** [comment]
Do you have an example of input and expected result ?

Sent from MailDroid

-----Original Message-----

**Comment by benyuanzhang-Zhang** [comment]
Yes I have.  
  I did not expect your reply so quickly.
  Now I am on my way home, and I can only give it to you tomorrow. 
  I hope you can forgive me.  
  Thank you very much for your reply.

**Comment by benyuanzhang-Zhang** [comment]
> Do you have an example of input and expected result ? Sent from MailDroid
> […](#)
> -----Original Message----- From: Mingxin Zhang <notifications@github.com> To: mistic100/Photo-Sphere-Viewer <Photo-Sphere-Viewer@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Sent: mer., 11 nov. 2020 11:10 Subject: [mistic100/Photo-Sphere-Viewer] How to convert my own svg to Photo Sphere Viewer (#461) ## version | name | version | | ------------------- | ------------- | | Photo-Sphere-Viewer | 4.0.7 | | Google Chrome | 86.0.4240.183 | ## issue Hello guy, It's an honor to use your product. I have a special request. I need to create a Svg myself and convert it to a 3D image. We can put it in PSV, but every time we move or change PSV, svg will recover. Do you have any good ideas?
> -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #461

  for example
``` SVG
<polygon id="psv-marker-1605142838627" class="psv-marker psv-marker--svg psv-marker--has-tooltip psv-marker--visible" fill="rgba(255,0,0,0.3)" stroke="rgba(0, 0, 0, 0.8)" stroke-width="2px" points="607,277 942,407 694,601"></polygon>
```

``` JavaScript
[
  [0.039222284103776886, 0.10107006734248158],
  [0.453661573260569, -0.06268055651096693],
  [0.1591710673920942, -0.32285732768262365]
]
```
I have an array of coordinate points that I want to convert to the points attribute in PSV

**Comment by mistic100** [comment]
That does not answer my question, what does it look like and what is the expected result ?

**Comment by benyuanzhang-Zhang** [comment]
Thank you very much for your reply. I have solved the problem. 
Thank you again for your product. It's really powerful.

**Comment by mistic100** [comment]
Giving details and the solution would be helpful for other users...

**Comment by benyuanzhang-Zhang** [comment]
## Project requirements
  Use another plug-in([svg.js](https://github.com/svgdotjs/svg.js)) to draw svg onto PSV, and tt can be resized and moved.

## Problem
  Plug-ins can be used, but when dragging and moving the lens, the changed SVG will be restored

## Train of thought
  The relationship between coordinates and PSV, so ask a question

## Solved
  The solution was found by reading the source code and [official documentation](https://photo-sphere-viewer.js.org/api/psv.services.datahelper).

## code
```JavaScript
// val is svg points data
// viewer is PSV
function changeLevel(val) {
	const v3 = viewer.dataHelper.viewerCoordsToVector3(val)
	return viwer.dataHelper.vector3ToSphericalCoords(v3)
}
```
