### ISSUE TITLE
Grab the canvas content (for custom transitions)

### ISSUE THREAD

**Issue by mrAceT** [mistic100/Photo-Sphere-Viewer#462]
Hi,

I'm trying to create a cool transition function between images, but I am having trouble "grabbing" the current canvas.. the result is a black image, could you help me out maybee?

This is what I have now (the repositioning to -10px/-10px is for testing):

```
var container = 'photosphere';
var GAcanvas = $('#'+container).find('.psv-canvas-container').first().find('canvas').first();
GAcanvas.attr('id','GA'+container+'Canvas');
GAcanvas.after('<canvas id="GA'+container+'Transistion" width="'+GAcanvas.width()+'" height="'+GAcanvas.height()+'" class="psv-canvas" style="width: '+GAcanvas.width()+'px; height: '+GAcanvas.height()+'px;position:absolute;top:-10px;left:-10px;"></canvas>');
var sourceCanvas = document.getElementById('GA'+container+'Canvas');
var destinCanvas = document.getElementById('GA'+container+'Transistion').getContext('2d');
destinCanvas.drawImage(sourceCanvas, 0, 0);
```

**Comment by mistic100** [comment]
#193

**Comment by mrAceT** [comment]
Thank you for the tip, but I appear to be too unfamiliar with "THREE" to get it to work..
Could you give me an other tip?

Here is the unsatisfying result of me fiddling around for hours:
https://www.geoarchief.nl/psv/geoarchive_grab.html

PS: I know you have written me not to append to closed tickets, but I didn't want to clutter up your tickets.. Or would you rather have that I would start a new issue?

**Comment by mistic100** [comment]
The anwser is here https://github.com/mrdoob/three.js/issues/1472
the `preserveDrawingBuffer: true` needs to be added to the WebGL constructor

but because of the performance implications I don't want it to be in the library.
So I don't have any solution, but use a custom version of the lib.
