### ISSUE TITLE
Photo-Sphere-Viewer does not work on IE11

### ISSUE THREAD

**Issue by Biboba** [mistic100/Photo-Sphere-Viewer#463]
Photo-Sphere-Viewer 4.0.7 is broken on IE11 (with Promise polyfill included). 
When trying to initialize the viewer, the following error is logged:
```Object doesn't support property or method 'isNaN' ```

With the basic following code:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <title>Test</title>
        <style>
	  /* the viewer container must have a defined size */
	  #viewer {
		width: 100vw;
		height: 50vh;
	  }
        </style>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.css"/>
	<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/three/build/three.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/uevent@2/browser.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.js"></script>
  </head>

  <body>
    <div id="viewer"></div>
  </body>
  <script>
	  var viewer = new PhotoSphereViewer.Viewer({
		container: document.querySelector('#viewer'),
		panorama: 'https://photo-sphere-viewer.js.org/assets/sphere.jpg'
	  });
   </script>
</html>
```

I believe IE11 is supported, isn't it ?

I tested with IE11 version 11.2166.16299.0.

Thanks !

**Comment by mistic100** [comment]
caused by this line https://github.com/mistic100/Photo-Sphere-Viewer/blob/ffad99e87d5370b75e1a12c7d776739579518215/src/utils/psv.js#L199

use global isNaN instead

**Comment by Biboba** [comment]
Thanks for your reply.
Happy to read that you were able to identify the issue.
In the meantime, I managed to make it work on IE11 using [is-nan](https://www.npmjs.com/package/is-nan) polyfill.
