### ISSUE TITLE
Alter target for canvas (re)draw for creating transitions

### ISSUE THREAD

**Issue by mrAceT** [mistic100/Photo-Sphere-Viewer#464]
Since it is quite hard to copy the canvas content, I brainstormed an other possible way to go:

Is it possible to trigger a (re)draw event for the rendered image canvas and direct that (re)draw to an other canvas?

PS: I herby promise to share the results for the transition I have in mind, when I get it to work ;)

**Comment by mistic100** [comment]
Did you do some research ?
this for example ? https://stackoverflow.com/a/30647502/1207670
which explain what you were trying to in #462 does not work.

```
// force render, documented 
viewer.renderer.render();

// get image, standard THREE
viewer.renderer.renderer.domElement.toDataUrl();
```

**Comment by mrAceT** [comment]
Yes I did, but I'm too unfamiliar with THREE.js..

From your link, this part looks really promesing:
```
You don't need preserveDrawingBuffer: true to take a screenshot. What you need is to take the screenshot immediately after rendering. A screenshot is guaranteed to work as long as you take it after rendering but before exiting the current event.

So for example this will always work

renderer.render( scene, camera );
var screenshot = renderer.domElement.toDataURL();
```

If you could tell me..
`var PSV = new PhotoSphereViewer.Viewer({....});`
where
`PSV.renderer.renderer`
is the "renderer", but what do I use fo 'scene' and 'camera'?

PS: My apologies for my lack of knowledge in this area

**Comment by mistic100** [comment]
I posted exactly the code you needed....

**Comment by mrAceT** [comment]
"testgrab1" works now: https://www.geoarchief.nl/psv/geoarchive_grab.html

after doing this first:
`PSV.renderer.render();`

**Fantastic!**

Thanks :D
