### ISSUE TITLE
Photo-Sphere-Viewer V4: error when destroying widget

### ISSUE THREAD

**Issue by Biboba** [mistic100/Photo-Sphere-Viewer#465]
Using Photo-Sphere-Viewer v4.0.7, I noticed that the following error is logged when using [destroy](https://photo-sphere-viewer.js.org/api/psv.viewer#destroy) method:
```
THREE.Scene: .dispose() has been removed.
```

The issue is coming from the fowolling line when destroying the Scene:
https://github.com/mistic100/Photo-Sphere-Viewer/blob/8bfbc77d4b700dddd8b3d0507355346e354e6269/src/services/Renderer.js#L434

that triggers the following error from Three: 
https://github.com/mrdoob/three.js/blob/29d6058fbabded228f96ab66e5917e1f708c249d/src/Three.Legacy.js#L1483

Thanks !

**Comment by mistic100** [comment]
For the sake of simplicty my function tries to call "dispose" when the function exists. I think it is just bad design from THREE to keep the function but log and error. Hopefully they will completely remove it in a future version.
