### ISSUE TITLE
Provide typescript typings

### ISSUE THREAD

**Issue by Biboba** [mistic100/Photo-Sphere-Viewer#466]
Hello @mistic100,

Just a suggestion, but it would be nice to provide typescript [typings](https://github.com/DefinitelyTyped/DefinitelyTyped) for this library.

Thanks for listening !

**Comment by mistic100** [comment]
I added types on the `typings` branch, still have to test it on a real project (particularly for plugins)

**Comment by Sergiobop** [comment]
any chance this get merged? @mistic100 Thanks!

**Comment by mistic100** [comment]
No, it does not work yet
