### ISSUE TITLE
Catch position on mouse move

### ISSUE THREAD

**Issue by mrAceT** [mistic100/Photo-Sphere-Viewer#467]
I have searched the documentation and the issues here, but could not find it..

Is it possible to "catch" a "mousemove" event? Or in an other way catch the data.lat/lon of the mouse position on demand?

Something similar to:
`PSV.on('click', function (e, data) { ... });`

But not on click, but on "mouse move"?
`PSV.on('mousemove', function (e, data) { ... });`

**Comment by mistic100** [comment]
something like that :

```js
PSV.container.addEventHandler('mousemove', (e) => {
  const pos = { x: e.offsetX, y: e.offsetY };
  const vector = PSV.dataHelper.viewerCoordsToVector3(pos);

  if (vector) {
    const sphericalCoords = PSV.dataHelper.vector3ToSphericalCoords(vector);
    const textureCoords = PSV.dataHelper.sphericalCoordsToTextureCoords(sphericalCoords);
  }
});
```

**Comment by mrAceT** [comment]
Thanks!

for a next visitor to this thread, the above code is "close", this code works:
`PSV.container.**addEventListener**('mousemove', (e) => {
  const pos = { x: e.offsetX, y: e.offsetY };
  const vector = PSV.dataHelper.viewerCoordsToVector3(pos);

  if (vector.**length**) {
    const sphericalCoords = PSV.dataHelper.vector3ToSphericalCoords(vector);
    const textureCoords = PSV.dataHelper.sphericalCoordsToTextureCoords(sphericalCoords);
  }

});`

**Comment by mistic100** [comment]
Yes of course it is addEventListener.
But I don't know what case you are covering with `vector.length` instead of `vector`, `viewerCoordsToVector3` does not returns empty vectors : https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/services/DataHelper.js#L140-L155

**Comment by mrAceT** [comment]
The if statement didn't become true for me, but the vector had length.. so that's why I did that

**Comment by mistic100** [comment]
`if (vector)` cannot be not true while `if (vector.length)` is true, just saying

**Comment by mrAceT** [comment]
I stand corrected, was fumbling around there a bit I guess ;)

PS: damn, you are fast answerer!
