### ISSUE TITLE
Does not work with IE 11

### ISSUE THREAD

**Issue by krudoy** [mistic100/Photo-Sphere-Viewer#47]
Freezes and not showing Navigation Bar when used with IE 11

**Comment by rarutu** [comment]
+1

**Comment by serge-nu** [comment]
+

**Comment by Super-Meng** [comment]
+1     and  in chrome  has Mesh line :(

**Comment by mistic100** [comment]
The mesh is only visible if you don't have webgl support, whatever browser you use. And there is nothing I can do for that.

**Comment by AdrienPoupa** [comment]
The navbar doesn't show because of the call to hide():

```
// load components
        if (this.config.navbar) {
            this.container.classList.add('psv-container--has-navbar');
            this.navbar = new PSVNavBar(this);
            this.navbar.hide();
        }
```

despite IE reading this code below:

```
// enable GUI after first render
        this.once('render', function() {
            if (this.config.navbar) {
                this.navbar.show();
            }
```

**Comment by caiodoneda** [comment]
Still freezing on IE11... Someone was able to get it working?

**Comment by larsvliet** [comment]
The problem seems to be that IE doesn't like the display property to be set to null.
Set the display to an empty value fixes the issue:
`
viewer.on('ready', function() {
    // Fix for IE
    viewer.navbar.container.style.display = '';
    viewer.hud.container.style.display = '';
});
`

**Comment by mistic100** [comment]
Thank you, I changed it, as well as some issues with SVG support
