### ISSUE TITLE
polygon marker

### ISSUE THREAD

**Issue by shtrudelsupport** [mistic100/Photo-Sphere-Viewer#470]
Hi,
First thank you for PSV.

I have few issues with PSV and one og then is polygon marker.

If I hard code the polygon marker like in the sample you present I get the following error:

**index.js:585 Error: <polyline> attribute points: Expected number, "NaN,NaN NaN,NaN …".**

Polygon markers code follows -
```
markersPlugin.addMarker(
                {
                    // polygon marker
                    id: 'polygon',
                    polylineRad: [
                        [6.2208, 0.0906],
                        [0.0443, 0.1028],
                        [0.2322, 0.0849],
                        [0.4531, 0.0387],
                        [0.5022, -0.0056],
                        [0.4587, -0.0396],
                        [0.2520, -0.0453],
                        [0.0434, -0.0575],
                        [6.1302, -0.0623],
                        [6.0094, -0.0169],
                        [6.0471, 0.0320],
                        [6.2208, 0.0906],
                    ],
                    svgStyle: {
                        fill: 'rgba(200, 0, 0, 0.2)',
                        stroke: 'rgba(200, 0, 50, 0.8)',
                        strokeWidth: '2px'
                    },
                    tooltip: {
                        content: 'A dynamic polygon marker',
                        position: 'right bottom'
                    }
                }
            );
```

Can you please explain what am I doing wrong ?

**Comment by shtrudelsupport** [comment]
Hi again,

Also in your website at [https://photo-sphere-viewer.js.org/plugins/plugin-markers.html#example](url) the console show the same error...

**Comment by mistic100** [comment]
please provide a complete stack trace using **non minified** code (with just you error I cannot where the error is from)  
or an online demo

**Comment by shtrudelsupport** [comment]
function reloadMarkers() {
            markersPlugin.addMarker(
                {
                    // polygon marker
                    id: 'polygon',
                    polylineRad: [
                        [6.2208, 0.0906],
                        [0.0443, 0.1028],
                        [0.2322, 0.0849],
                        [0.4531, 0.0387],
                        [0.5022, -0.0056],
                        [0.4587, -0.0396],
                        [0.2520, -0.0453],
                        [0.0434, -0.0575],
                        [6.1302, -0.0623],
                        [6.0094, -0.0169],
                        [6.0471, 0.0320],
                        [6.2208, 0.0906]
                    ],
                    svgStyle: {
                        fill: 'rgba(200, 0, 0, 0.2)',
                        stroke: 'rgba(200, 0, 50, 0.8)',
                        strokeWidth: '2px'
                    },
                    tooltip: {
                        content: 'A dynamic polygon marker',
                        position: 'right bottom'
                    }
                }
            );

            
        }

**Comment by shtrudelsupport** [comment]
Is there a sample for adding a polygon marker programmatically ??

**Comment by mistic100** [comment]
https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/example/plugin-markers.html#L381

but you didn't answer my question, without the stack trace of the error I cannot help

**Comment by shtrudelsupport** [comment]
Thanks for the sample.

Stack trace follows -

![image](https://user-images.githubusercontent.com/1938290/101069404-9ffc0580-35a2-11eb-92a4-68dec0399a44.png)

**Comment by mistic100** [comment]
that's the stack trace of your call, not of the error.

If you want further help, provided an online demo of the issue

**Comment by shtrudelsupport** [comment]
![image](https://user-images.githubusercontent.com/1938290/101075075-341d9b00-35aa-11eb-8003-5b819b7177a9.png)

**Comment by shtrudelsupport** [comment]
I created a demo on my machine that reproduce the error. 

Don't know why when running it on [jsFiddle ](https://jsfiddle.net/s80qaLuy/2/)it does not initialize the viewer right ...

**Comment by mistic100** [comment]
What should I see ?

on the fiddle you posted the viewer is well initialized and the polygon marker is indeed visible.

So I am still struggling to understand your problem.

![Capture](https://user-images.githubusercontent.com/41597/101087909-31737380-35b3-11eb-83a3-d09a43eea55e.PNG)

**Comment by shtrudelsupport** [comment]
WEIRD...

The following code produce the error I mentioned earlier.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>

    <style type="text/css">
        #stage {
            width: 50vw;
            height: 50vh;
            border: 1px solid #808080;
        }
    </style>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4.0.7/dist/photo-sphere-viewer.min.css" />

 

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4.0.7/dist/plugins/markers.min.css" />


    <script src="script/jquery-3.4.1.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/three/build/three.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uevent@2/browser.min.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4.0.7/dist/photo-sphere-viewer.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4.0.7/dist/plugins/markers.min.js"></script>

    <script src="script/const.js"></script>
    <script src="script/const2.js"></script>
    <script src="script/folder.js"></script>
    <script type="text/javascript">

        function reloadMarkers() {
            markersPlugin.clearMarkers();


            markersPlugin.addMarker(
                {
                    // polygon marker
                    id: 'polygon',
                    polylineRad: [
                        [6.2208, 0.0906],
                        [0.0443, 0.1028],
                        [0.2322, 0.0849],
                        [0.4531, 0.0387],
                        [0.5022, -0.0056],
                        [0.4587, -0.0396],
                        [0.2520, -0.0453],
                        [0.0434, -0.0575],
                        [6.1302, -0.0623],
                        [6.0094, -0.0169],
                        [6.0471, 0.0320],
                        [6.2208, 0.0906]
                    ],
                    svgStyle: {
                        fill: 'rgba(200, 0, 0, 0.2)',
                        stroke: 'rgba(200, 0, 50, 0.8)',
                        strokeWidth: '2px'
                    },
                    tooltip: {
                        content: 'A dynamic polygon marker',
                        position: 'right bottom'
                    }
                }
            );
        }
        function handleViewer(_panorama) {
            
             $("#stage")
                .html("");

            photosphereviewer = new PhotoSphereViewer.Viewer({
                container: $("#stage")[0],
                panorama: _panorama,
                defaultLong: 0,
                defaultLat: 0,
                
                navbar: [
                    'autorotate',
                    'fullscreen',
                    'zoom'
                ], 
                plugins: [PhotoSphereViewer.MarkersPlugin]
            });

            


            photosphereviewer.on("panorama-loaded", function () {
                
                reloadMarkers();
            });

            markersPlugin = photosphereviewer.getPlugin(PhotoSphereViewer.MarkersPlugin);
          
        }

        $(function () {
            handleViewer("https://cdn1.matadornetwork.com/blogs/1/2006/11/360-panorama-matador-seo.jpg");
        });
    </script>
</head>
<body>
    <div id="stage"></div>
</body>
</html>
```

**Comment by mistic100** [comment]
Of the the problem is only present on Chrome and **not** in the the jsfiddle console.

It is because you add the markers too soon, use "ready" instead of "panorama-loaded".

**Comment by shtrudelsupport** [comment]
You are the best.

THANK YOU
