### ISSUE TITLE
Image seems distorted in wider viewers

### ISSUE THREAD

**Issue by vpzomtrrfrt** [mistic100/Photo-Sphere-Viewer#472]
Have modified the homepage demo to demonstrate the issue better: https://jsfiddle.net/90cpjh6y/
Especially when the aspect ratio of the viewer is rather wide, the objects on the edges of the screen feel larger than they should.

What's going on here? Is this expected behavior?

**Comment by mistic100** [comment]
This is normal, exactly the same things that happen when you open a game on an ultra wide monitor.

Increase the zoom level (`defaultZoomLvl`) if you want to mitigate it.
