### ISSUE TITLE
How can I change the "camera angle"

### ISSUE THREAD

**Issue by mrAceT** [mistic100/Photo-Sphere-Viewer#479]
I know it is possible to set a 'pan', 'tilt' and 'roll' via 'sphereCorrection'.

That way, that "starting view" changes, BUT that also alters te position op markers I set in the pano..

Is it possible to change/set the camera angle? via (relative) lat/lng?

(so just the 'viewing angle'.. not the rest)

**Comment by mistic100** [comment]
did you try the "rotate" method ?

**Comment by mrAceT** [comment]
Bingo, thank you!

(for the next one that finds this thread:)
```javascript
PSV.rotate({longitude:Math.PI*1, // range: 0 - 2xPi
            latitude:0           // range: -0.5xPi - 0.5xPi
           });

**Comment by mistic100** [comment]
BTW there are also `defaultLat` and `defaultLong`

https://photo-sphere-viewer.js.org/guide/config.html#standard-options
