### ISSUE TITLE
[improvement] Prefix all the SCSS variables in order to avoid conflicts.

### ISSUE THREAD

**Issue by wujekbogdan** [mistic100/Photo-Sphere-Viewer#48]
Hi,

Some variable names in the main SCSS file are too generic. For example `$main-background`.

Could you add a prefix to all the SCSS variables in order to avoid possible conflicts? For example, let's prefix all the variables with `$pss-`, so that `$main-background` becomes `$psv-main-background`.

PS
There's even a better solution - SASS maps. I've implemented such a solution in the [perfect-scrollbar](https://github.com/noraesae/perfect-scrollbar) library. Take a look at the example: https://github.com/noraesae/perfect-scrollbar/blob/master/src/css/themes.scss

Thanks!

**Comment by mistic100** [comment]
I don't like SASS maps because of the bloatware of the map-get method, I am waiting the time we will be able to use brackets syntax.
I'll go to prefixes.
