### ISSUE TITLE
Allow mouse wheel scroll with modifier only

### ISSUE THREAD

**Issue by HarrisonMylesG** [mistic100/Photo-Sphere-Viewer#487]
Feature Request:
Only zoom while holding modifier (command, control, etc.)
Benefit: allows easy, smooth zooming while being able to scroll on webpages

I was able to make this work by simply adding an event listener and an extra config param.

Version: 4.0.7

**Comment by mistic100** [comment]
Good idea, it would be the desktop version of `touchmoveTwoFingers`
