### ISSUE TITLE
Is there anyway to let viewer to go to one coner  in cubemap?

### ISSUE THREAD

**Issue by cityvoice** [mistic100/Photo-Sphere-Viewer#489]
For example, I'm now in a room ,I want to go from one corner to another coner , how to do?

**Comment by mistic100** [comment]
You cannot go from "one corner to another" in a cubemap.... the whole point of the cubemap is to have the camera at the center.

If you want to transition between two panorama use the `setPanorama` method. The method cannot be called when clicking on a marker (placed in a "corner" for example").

methods => https://photo-sphere-viewer.js.org/guide/methods.html  
markers => https://photo-sphere-viewer.js.org/plugins/plugin-markers.html

**Comment by cityvoice** [comment]
@mistic100 I see, thanks!
