### ISSUE TITLE
Polygon marker background image

### ISSUE THREAD

**Issue by shtrudelsupport** [mistic100/Photo-Sphere-Viewer#495]
Hi,

How can I center background image in polygon marker ?

**Comment by mistic100** [comment]
I don't know, that a thing I tried when first developing this feature, but there is no straight forward solution

**Comment by mistic100** [comment]
Actually found a very simple solution : instead of positionning the pattern applied to the polygon, the polygon is drawn arround it's center.

With such definition of the pattern 
```
<pattern id="image" x="960" y="540" width="1920" height="1080" patternUnits="userSpaceOnUse">
      <image href="test-sphere.jpg" x="0" y="0" width="1920" height="1080"/>
    </pattern>
```

https://user-images.githubusercontent.com/41597/107120971-1e6d7000-6890-11eb-98a9-c53d928c533d.mp4
