### ISSUE TITLE
How to open PSV panel from custom button

### ISSUE THREAD

**Issue by dunblanco** [mistic100/Photo-Sphere-Viewer#497]
Hi.

If someone can give me a hint to create a custom button, that (onclick) opens the lateral panel (psv_panel) to include a menu script that will let the user choose between the different stages available?

I mean when i click on Marker List button the PSV Panel (right) show the available markers, I'd like to do the same but showing a menu

I'm using now a left side div but i loose it on full screen mode.

![image](https://user-images.githubusercontent.com/29429507/106930745-2c978100-6716-11eb-85cc-18f9c1c08028.png)

Thanks a lot for your help in advance.

**Comment by mistic100** [comment]
Check the API documentation. The [Viewer](https://photo-sphere-viewer.js.org/api/psv.viewer) as a [panel](https://photo-sphere-viewer.js.org/api/psv.viewer#panel) property which has a [show](https://photo-sphere-viewer.js.org/api/psv.components.panel#show) method.

```js
viewer.panel.show({
  id: 'your-own-id',
  content: 'html of the content',
});

viewer.panel.hide('your-own-id'); // this allows to only hide if the panel stills shows your own content
```

**Comment by mistic100** [comment]
For you information there is an upcoming virtual tour plugin #491 you can test it on the [`tour` branch](https://github.com/mistic100/Photo-Sphere-Viewer/tree/tour)

**Comment by dunblanco** [comment]
Hi mistic.

honestly i don' get your hint, when you said id: 'your-own-id' ..... i have to create my own panel in my viewer?

If yes, I'm pretty sure that i dont know how to do it, sorry, thats why I'd like to show the content in the existing right panel (if possible).

I'm creating some custom buttons as follow:

var PSV = new PhotoSphereViewer.Viewer ({
    container : 'photosphere', panorama  : panos[i].url,  caption   : panos[i].desc,  defaultZoomLvl: 30,  
     navbar    : [
        {  id: 'menu', title    : 'Menu', className: 'custom-button', content  : '<i class="fas fa-bars"></i>', onClick: () => { w3_open("menu_lateral"); }  },
 {... others.....} ]

and then I'm managing the button action in the JS function.

I'm a beginer in JS by the way! So, if you can guide me a bit more, Thnaks.

**Comment by dunblanco** [comment]
> Check the API documentation. The [Viewer](https://photo-sphere-viewer.js.org/api/psv.viewer) has a [panel](https://photo-sphere-viewer.js.org/api/psv.viewer#panel) property which has a [show](https://photo-sphere-viewer.js.org/api/psv.components.panel#show) method.
> 
> ```js
> viewer.panel.show({
>   content: 'html of the content',
> });
> ```

**Comment by dunblanco** [comment]
Hi mistic100, i just close by accident, i mean the issue is closed and solved, but I'd like to thanks you for your help.

**Comment by mistic100** [comment]
de rien :)
