### ISSUE TITLE
start PSV in fullscreen

### ISSUE THREAD

**Issue by shtrudelsupport** [mistic100/Photo-Sphere-Viewer#498]
Hi there,

How can start PSV in full screen mode ?

Did not find this in documantation ...

**Comment by mistic100** [comment]
All methods and events are documented https://photo-sphere-viewer.js.org/api/psv.viewer

```js
viewer.once('ready', () => {
  viewer.enterFullscreen();
});
```

But doubt it will work because the browser will not allow to enter fullscreen without user interraction (ie clicking on a button).

**Comment by shtrudelsupport** [comment]
Couldn't find it in docs.

THANK YOU.

**Comment by shtrudelsupport** [comment]
Does not work for me.

Any idea what might be the reason **viewer.enterFullscreen()** not turning the viewer into full screen ?

**Comment by mistic100** [comment]
As I said earlier the browser does not allow to automatically enter full screen, this is **not** a problem with PSV.

If you open your dev console you will propably see error like this (translated from french).

> The fullscreen access request was denied because Element.requestFullScreen () was not called inside a user-generated event handler. 

There is nothing than can be done.
