### ISSUE TITLE
modal in full screen.

### ISSUE THREAD

**Issue by dunblanco** [mistic100/Photo-Sphere-Viewer#499]
Hi Mistic.

I'm using modal windows to show a "map" of the zone, but when I'm running in full screen mode, the modal do not work.

any hint?

From other side, I was thinking to show the map into PSV panel, but i need that panel width goes almost to full screen, in the isse #444 you mention how to do it modifying CSS, but, there is a way to do it dynamically using JS?

Thanks in advance.

Maybe i should open two issues?

**Comment by mistic100** [comment]
You really need to document yourself on what is "fullscreen" on the web.
Once again it is totally normal you cannot open a modal when an element is in fullscreen.

You should stop trying to use the fullscreen feature of PSV and tell your users to use F11 ( which pull to whole page in fullscreen, not only a single element).

**Comment by mistic100** [comment]
If you want to change the panel initial size only in certain situations, it is not possible, please open another issue.

**Comment by dunblanco** [comment]
Hi mystic, sorry for ask, i didn't knew the method used for you to get fullscreen. 

I found a way that "almost" work:

`<script>
/** GOES TO FULL SCREEN **/
function requestFullScreen(element) {
    // Supports most browsers and their versions.
    var requestMethod = element.requestFullScreen || element.webkitRequestFullScreen || element.mozRequestFullScreen || element.msRequestFullScreen;

    if (requestMethod) { // Native full screen.
        requestMethod.call(element);
    } else if (typeof window.ActiveXObject !== "undefined") { // Older IE.
        var wscript = new ActiveXObject("WScript.Shell");
        if (wscript !== null) {
            wscript.SendKeys("{F11}");
        }
    }
}

function gotofullscreen () { 
	var elem = document.body; // Make the body go full screen.
	requestFullScreen(elem);
}
</script>`

then in PSV (js+php)

`$icon_label = '<i class="fal fa-expand-wide"></i>';

echo "{
	id: 'labels_button',
	title    : 'Label Manager',
	className: 'custom-button',
	content  : '".$icon_label."',
	onClick: () => { gotofullscreen(); }
},";
`

the only issue, and that's why i said almost, is that on realod (to go to another scene) i loose F11 mode.

**Comment by mistic100** [comment]
In 2021 you really don't need to support ActiveX.

----

Why do you reaload the page when changing scene ? Call `setPanorama`, `setCaption`, `markers.setMarkers` etc

**Comment by mistic100** [comment]
If you want you can call the `PhotoSphereViewer.utils.requestFullscreen(document.body)`

it is the same cross-browsers code https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/utils/browser.js#L184

**Comment by dunblanco** [comment]
Why do you reload the page when changing scene ? Call setPanorama, setCaption, markers.setMarkers etc

I don't, I reload when changing of a set of scenes ..... to move into the scene to different positions i do like you said. But i could prepare the set of scenes and the avoid to realod..... reviewing my schema .... thank!

**Comment by mistic100** [comment]
Or make an AJAX call to your server to get the new configuration, avoiding to generate a potentially huge HTML page.

**Comment by mrAceT** [comment]
I use jquery for this:

```
// enter fullscreen:
$('body').fullscreen();
// exit fullscreen:
$.fullscreen.exit();
```

source of jquery plugin: https://github.com/private-face/jquery.fullscreen
