### ISSUE TITLE
Marker position compatibility between v3.6 and v4

### ISSUE THREAD

**Issue by ellesborough** [mistic100/Photo-Sphere-Viewer#501]
I have a solution working with v3.6.0, but when I use the same lat/lng for stored markers in V4, they seem to end up in a different place.

Is there a transform required to use previous markers with V4?

**Comment by mistic100** [comment]
None that I am aware of. Do you have an example ?

**Comment by ellesborough** [comment]
Hi, I created two test pages with the same photo sphere, and the same single marker
One is using v3.6.0 and the other v4.
You will see that the marker looks like it is 180deg out between them, or the photo sphere itself is the other way around.

http://www.soberton.hol.es/psv/psv-v3.html
http://www.soberton.hol.es/psv/psv-v4.html

I hope that is clear and you can see the issue.

Peter

**Comment by mistic100** [comment]
Obviously the image is rotated, the markers are in place.

The thing is your images has XMP data for pose heading (182°) which were not taken into account before 4.2.0.

If you don't want to use XMP data at all use `useXmpData: false`, you can also overwrite `panoData` to reset pose settings.

```
panoData: {
  poseHeading: 0,
  posePitch: 0,
  poseRoll: 0,
}
```

Or you can correct your markers the take the pose into account.

Mor info https://photo-sphere-viewer.js.org/guide/cropped-panorama.html

**Comment by ellesborough** [comment]
Thanks for the quick and accurate reply.
I found ignoring the xmpData distorts the image, but setting panoData.pose
values works a treat.
