### ISSUE TITLE
Markers Issue - Marker.js:383 Uncaught TypeError: photoSphereViewer.utils.isExtendedPosition is not a function

### ISSUE THREAD

**Issue by stevehaycock** [mistic100/Photo-Sphere-Viewer#505]
New to photosphere so please be gentle.

Followed the examples in the guide and managed to get them working and adjust them to suit my settings. However, now seeing the following error and I haven't adjusted anything. 

Markers visibility icon on the bottom bar is shown but there's no markers list icon. 

Any assistance would be appreciated.

Uncaught TypeError: photoSphereViewer.utils.isExtendedPosition is not a function
    at Marker.__updateNormal (Marker.js:383)
    at Marker.update (Marker.js:368)
    at new Marker (Marker.js:140)
    at MarkersPlugin.addMarker (index.js:304)
    at index.js:408
    at misc.js:170
    at Array.forEach (<anonymous>)
    at Object.k [as each] (misc.js:169)
    at MarkersPlugin.setMarkers (index.js:408)
    at o.<anonymous> (index.js:171)

`var viewer = new PhotoSphereViewer.Viewer({
    	container: document.querySelector('#viewer'),
    	panorama: imagenamelow,
    	loadingImg: '/assets/photosphere-logo.gif',
    	touchmoveTwoFingers: true,
    	mousewheelCtrlKey: false,
    	plugins : 	[
    				PhotoSphereViewer.SettingsPlugin,
    				[PhotoSphereViewer.MarkersPlugin, {
    					markers: [{
    						// image marker
    						id   		: 'image',
    						longitude	: '94deg',
    						latitude	: 0,
    						image       : 'assets/pin-blue_small.png',
    						width		: 32,
    						height		: 32,    					
    						anchor		: 'bottom center',
    						tooltip		: {
    							content	: 'Scan',
    							positon	: 'bottom center'
    						}
    					}]
    				}
    				],
    				[PhotoSphereViewer.ResolutionPlugin,
    				{
    					resolutions : [
    					{
    						id 			: 'low',
    						label		: 'Low',
    						panorama	: imagenamelow,
    					},
    					{
    						id  		: 'high',
    						label  		: 'High',
    						panorama 	: imagenamehigh,
    					},
    					]
    				}],
    				]
    			},
    	)`

**Comment by mistic100** [comment]
What versions of the libs are you using ?

**Comment by stevehaycock** [comment]
Lastest version, V4 and three 109.

Just tried again and not changed a thing and it's working.

**Comment by mistic100** [comment]
"4" is not a version. The last version is 4.2.0

I had a problem on jsfiddle because jsdelivr cached the old versions of the files. Solved by Ctrl+F5, you probably had a cache issue too.

**Comment by stevehaycock** [comment]
Sorry yes, 4.2.0.

Thank you
