### ISSUE TITLE
Keyboard event to move around image is works only in fullscreen mode. Is there any other way to trigger the move around while not in full screen?

### ISSUE THREAD

**Issue by rajith869** [mistic100/Photo-Sphere-Viewer#506]
## Issues guidelines

- **Indicate your Photo-Sphere-Viewer, three.js and web browser versions**
- Please search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

**Comment by mistic100** [comment]
You can call `viewer.startKeyboardControl()` the problem is it will brobably break the navigation on the rest of your page.

**Comment by rajith869** [comment]
thank you. @mistic100  It worked
