### ISSUE TITLE
Undefined prop issue

### ISSUE THREAD

**Issue by tingus** [mistic100/Photo-Sphere-Viewer#507]
I am using latest version version from NPM and using the bare essentialls to get this working according to the documentation.

Just importing this module you have a undefined prop. I will attach picture of my console log to see if this helps,
![Capture](https://user-images.githubusercontent.com/45846461/107509424-78c14600-6b9a-11eb-8829-861541908e8f.PNG)

**Comment by mistic100** [comment]
did you imported uevent ?

please post an online example, a stacktrace alone is not useful

**Comment by tingus** [comment]
> did you imported uevent ?
> 
> please post an online example, a stacktrace alone is not useful

`import React from 'react';

import { Viewer } from 'photo-sphere-viewer';

function InteractiveScene(props) {
    const sphereElementRef = React.useRef(null);
    let viewer = Viewer({
        panorama: 'https://s3-eu-west-1.amazonaws.com/cdn.example.co.uk/live/test-sphere.jpg',
        container: sphereElementRef.current
    });

    return(
        <div ref={sphereElementRef}></div>
    );
}

export default InteractiveScene;`
