### ISSUE TITLE
Is there any way to tab around the controls of 360 viewer controls like full screen, automatic rotation etc?

### ISSUE THREAD

**Issue by rajith869** [mistic100/Photo-Sphere-Viewer#508]
## Issues guidelines

- **Indicate your Photo-Sphere-Viewer, three.js and web browser versions**
- Please search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

**Comment by mistic100** [comment]
Please read and respect the issue guidelines

**Comment by rajith869** [comment]
Hi Damien,

I didn't really understood what you meant.

What I need is to switch between the controls of Photosphere using the tab
key in keyboard. I tried this in the demo site and the tab doesn't work.
That's why I raised this bug.

**Comment by mistic100** [comment]
Look at your first message, you left the inital "Issues guidelines", those are meant to be read and replaced by a complete description of your problem. The title must only contain a short description of your issue.

----

I don't plan to had keyboard navigations on the controls.

**Comment by rajith869** [comment]
@mistic100 thank you for your reply. I actually doesn't know how to post bugs here. This were my second bug. Will try adding descriptions in next time.

It will be much appreciated, if we have the keyboard navigation on Photosphere Viewer controls. What I'm trying to do in my website is to access the them, with or without mouse. Except in the photosphere viewer, everywhere else is possible.

**Comment by mistic100** [comment]
Close in favor of #522
