### ISSUE TITLE
Feature request: filter markers in the list

### ISSUE THREAD

**Issue by mrAceT** [mistic100/Photo-Sphere-Viewer#509]
First of all I would like to thank you for so actively maintaining PSV and answering everybody here on github!

Second, if you find the time, could you make it possible to filter markers in the list?

I have bunch of markers to show where a next pano is, and markers where one can click for more information about that spot. I would like to only see the "more info markers", not the "here is anther pano markers".

(maybe add an option to add a class to a marker in the list?, then I could simply hide them via CSS?)

**Comment by mistic100** [comment]
This was already added on the `tour` branch
https://github.com/mistic100/Photo-Sphere-Viewer/blob/tour/docs/plugins/plugin-markers.md#hidelist

if the virtual tour is not finished for the next release, I will back-port this option

**Comment by mistic100** [comment]
Actually this option already exists, only the documentation is missing, you can already add `hideList: true` to your markers
