### ISSUE TITLE
[question] The difference between the Ricoh Theta and the Photo Sphere algorithm

### ISSUE THREAD

**Issue by wujekbogdan** [mistic100/Photo-Sphere-Viewer#51]
I use a [Ricoh Theta](https://theta360.com/pl/gallery/) device to take 360 pictures. They have a dedicated tool to display the pictures taken with their device. But the tool is very limited. The photos have to be hosted on the Ricoh servers and can be displayed only in an iframe. There's no way to customise it or to get rid of their branding. So I decided to create my own tool built on top of Photo Sphere Viewer.

I've noticed that Photo Sphere displays the panoramas in a different way than Ricoh Theta tool. I've created 2 samples:
- [Ricoh Theta](https://theta360.com/s/gPDK1uvOK2eO7VhzyPwalCiie)
- [Photo Sphere Viewer](https://dl.dropboxusercontent.com/u/3638687/panorama/ps/examples/index.htm)

As you can see the panorama displayed by Photo Sphere is distorted on the edges in a different way than the panorama displayed by the Ricoh application. Photo Sphere stretches the image on the edges when the Ricoh app "squeezes" the edges. The more you zoom out, the more noticeable it is.

I suppose that they use a different algorithm. Is there any chance to implement such an algorithm in Photo Sphere? Is it just a matter of changing some parameters or is it a bigger issue that requires a lot of effort?

**Comment by mistic100** [comment]
It will basically require to totally replace the renderer (based on ThreeJS perspective projection).

I also use photo from the Ricoh Theta, and I don't like at all their viewer, what the point if this extreme deformation ?

**Comment by wujekbogdan** [comment]
> I also use photo from the Ricoh Theta, and I don't like at all their viewer, what the point if this extreme deformation ?

Both solutions distort the images, but each does it in a different way. The biggest disadvantage of the ThreeJS perspective projection is that the edges are stretched so that human faces look terrible on the edges. 

IMO Ricoh solution is better for indoor panoramas, Photo Sphere algorithm is better for landscapes.

> It will basically require to totally replace the renderer (based on ThreeJS perspective projection).
So it sounds like a big deal, not just changing the parameters.

**Comment by mistic100** [comment]
Correction of what I said : it would require to replace the camera used, and only the camera, everything else is fine. If you know an implementation of THREE.Camera that achieve this display, I'll be pleased to integrate it.

**Comment by mistic100** [comment]
I found this example http://threejs.org/examples/canvas_geometry_panorama_fisheye.html
The behaviour with extreme FOV is not the same but otherwise it's very similar.

I'll investigate when I get time.

**Comment by wujekbogdan** [comment]
Thanks for taking your time to investigate this issue! I really appreciate it.

**Comment by mistic100** [comment]
Finally it was only a mater of configuration. You can enable it with the new "fisheye" option.
Unfortunately it's absolutely not compatible with the markers (for now, I guess all computations must be redone with this new parameter).

**Comment by wujekbogdan** [comment]
Awesome! Thanks.
