### ISSUE TITLE
Cannot read property 'matrixWorldInverse' of null three.min.ls

### ISSUE THREAD

**Issue by stevehaycock** [mistic100/Photo-Sphere-Viewer#510]
Photo Sphere Version 4.2.0
Three version 125

Hi,

getting the following error when using addMarkers. Have tried changing the location from lat/long to x/y. Any assistance would be appreciated. 

three.min.js:2 Uncaught TypeError: Cannot read property 'matrixWorldInverse' of null
    at t.e.project (three.min.js:2)
    at DataHelper.vector3ToViewerCoords (DataHelper.js:165)
    at MarkersPlugin.__getMarkerPosition (index.js:700)
    at index.js:596
    at misc.js:170
    at Array.forEach (<anonymous>)
    at Object.each (misc.js:169)
    at MarkersPlugin.renderMarkers (index.js:573)
    at MarkersPlugin.addMarker (index.js:316)
    at panoviewer.html?s=G01a_G02_Storage-Plantroom_TyMen_000:129

My code,

```js
markersPlugin.addMarker({
            id: 'new marker',
            latitude: '10deg',
            longitude: 0,
            circle: 10,                  
        });
```
Both of the following appear above the above addMarkers method

```js
var viewer = new PhotoSphereViewer.Viewer({
    	container: 'viewer',
    	panorama: imagenamelow,
    	loadingImg: '/assets/photosphere-logo.gif',
    	touchmoveTwoFingers: true,
    	mousewheelCtrlKey: false,
        caption: imagenamearray[1],
    	plugins : 	[PhotoSphereViewer.SettingsPlugin,
                    [PhotoSphereViewer.MarkersPlugin],
                    [PhotoSphereViewer.ResolutionPlugin,
    				{
    					resolutions : [
    					{
    						id 			: 'low',
    						label		: 'Low',
    						panorama	: imagenamelow,
    					},
    					{
    						id  		: 'high',
    						label  		: 'High',
    						panorama 	: imagenamehigh,
    					},
    					]
    				}],
    				]
    			},
    	)

    var markersPlugin = viewer.getPlugin(PhotoSphereViewer.MarkersPlugin);
```

**Comment by mistic100** [comment]
Please read this to post correctly formatted code blocs https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

----

To you call "addMarkers" immediately after init ? If yes you must wait for "ready" event.  
explained here https://photo-sphere-viewer.js.org/guide/methods.html#presentation

```js
viewer.once('ready', () => {
  // addMaker
});
```


or define the markers in the plugin configuration like in the example https://photo-sphere-viewer.js.org/plugins/plugin-markers.html#usage

**Comment by stevehaycock** [comment]
Brilliant thank you.
