### ISSUE TITLE
Marker pointer-events

### ISSUE THREAD

**Issue by shtrudelsupport** [mistic100/Photo-Sphere-Viewer#511]
Hi,

Is it possible to set a marker as transparent to mouse click using CSS pointer-events: none ?

**Comment by mistic100** [comment]
You can add a CSS class to the marker or directly configure inline style  
https://photo-sphere-viewer.js.org/plugins/plugin-markers.html#markers-options

**Comment by shtrudelsupport** [comment]
I have a polygon marker with onClick event that works fine. 

I have added an image marker on top of the polygon marker with the following CSS -

.noMouseResponseClass {
            pointer-events: none;
        }

I expected that when click the image marker the click will trigger the polygon onClick event, instead when I click the image marker nothing happens....

**Comment by mistic100** [comment]
Care to post a demo ?  
What do you mean by "polygon marker with onClick event" ?  

I just tested on the "examples/plugin-marker.html" example, if I disable pointer events on the red pin above the red polygon, the event `select-marker` works just fine when I click on the pin.

**Comment by shtrudelsupport** [comment]
Suddenly its working....

Excuse me for disruppting
