### ISSUE TITLE
Problem with vertical distortion of panos on google chrome for android when portrait

### ISSUE THREAD

**Issue by LordGreeny** [mistic100/Photo-Sphere-Viewer#512]
When viewing a panorama in portrait mode on google chrome on an android phone the image is stretched vertically when is more than 50% of the screen height.  There is no distortion when viewed in landscape mode, or when using a different browser (tested with firefox).

If there are markers (only tested with polygon markers) then they remain where they should be, which means they don't line up with where they look like they should be (there are none in the below examples though).

The below fiddle and hosted version are of the same code (the 'Your first viewer' code from the getting started guide), so that you can see the issue.

https://jsfiddle.net/Leoh3yt7/

https://lucmaps.co.uk/Distort/

PSV v4.2.0 
Google Chrome for Android Phones 88.0.4324.152 - tested on S10 and S11.

**Comment by mistic100** [comment]
@LordGreeny I was able to reproduce the problem when removing the following metadata from the examples :

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

This is the minimal configuration when designing pages for mobile.

Please add it to your page a test again. And close this issue if it works.

**Comment by mistic100** [comment]
just updated the documentation https://photo-sphere-viewer.js.org/guide/#your-first-viewer
