### ISSUE TITLE
How to rotate with longitude and latitude ?

### ISSUE THREAD

**Issue by issimissimo** [mistic100/Photo-Sphere-Viewer#513]
Hello,
I should syncronize two applications ("server", "client") , so that when the "server" rotate the view the "client" do the same view rotation.

I can get from the "server" the the "longitude" and "latitude" params of the view, through
`viewer.on('position-updated', (e, position) => {
            const lat = position.latitude;
            const lon = position.longitude;
            SendToClient(lat, lon);
        });`

So I can send to the client this function:
`GetFromServer(lat,lon){
 viewer.rotate({
                x: lon,
                y: lat,
            });
}`

But it does not work, the rotationis totally wrong.
In your documentation you generally say that "viewer.rotate" method can also use longitude and latitude, but how?

Many thanks!

**Comment by issimissimo** [comment]
solved!

**Comment by mistic100** [comment]
For those having the same need, the documentation explains how "position" can be provided  
https://photo-sphere-viewer.js.org/guide/config.html#standard-options (second green block)
