### ISSUE TITLE
MarkersPlugin: I can't add new markers

### ISSUE THREAD

**Issue by issimissimo** [mistic100/Photo-Sphere-Viewer#514]
Hello,
I'm trying to create a marker by code,
when I call "markersPlugin.addMarker({...."  I get this error:
[http://issimissimo.com/Cattura.JPG](url)
Uncaught TypeError: Cannot read property 'matrixWorldInverse' of null

This my very simple code:

var viewer = new PhotoSphereViewer.Viewer({
            navbar: [
                'zoom',
            ],
            container: document.querySelector('#viewer'),
            panorama: '01.jpg',

            plugins: [
                [PhotoSphereViewer.MarkersPlugin, {
                    markers: [
                        {
                            id: 'new-marker',
                            longitude: '45deg',
                            latitude: '0deg',
                            image: 'pin-red.png',
                            width: 32,
                            height: 32,
                        },
                    ],
                }],
            ],
        });

        const markersPlugin = viewer.getPlugin(PhotoSphereViewer.MarkersPlugin);
        
        markersPlugin.addMarker({
            id: 'new-marker',
            longitude: '10deg',
            latitude: '0deg',
            image: 'pin-red.png',
            width: 32,
            height: 32,
        });

**Comment by mistic100** [comment]
Please search issues #510

**Comment by issimissimo** [comment]
Many thanks!
