### ISSUE TITLE
How to show/hide navbar

### ISSUE THREAD

**Issue by issimissimo** [mistic100/Photo-Sphere-Viewer#515]
Hello,
fist of all many thanks and congratulations for your outstanding library, we are enjoing every single aspect of it.

We would have 2 questions:
1 - Would it be possible to show/hide the navbar by code?
2 - if the navbar is not visible, would it be possible to hide the semi transparent black ribbon on the bottom?

Again, many thanks!

**Comment by mistic100** [comment]
```
viewer.navbar.hide();
```

this is fully documented https://photo-sphere-viewer.js.org/api/

**Comment by issimissimo** [comment]
many thanks!
