### ISSUE TITLE
How to change cursor on over marker

### ISSUE THREAD

**Issue by issimissimo** [mistic100/Photo-Sphere-Viewer#516]
Hello,
we'd like to change to cursor when is over a marker.
Unfortunately this does not work:

markersPlugin.on('over-marker', (e, marker) => {
                document.getElementById("viewer").style.cursor = "pointer";
            });

How can be done?
Many thanks!

**Comment by mistic100** [comment]
use `style` when declaring the marker

```
style: {
  cursor: 'pointer',
}
```

https://photo-sphere-viewer.js.org/plugins/plugin-markers.html#markers-options

**Comment by issimissimo** [comment]
wonderful!
Many thanks!
