### ISSUE TITLE
A grid of sphere segments visible in every browser

### ISSUE THREAD

**Issue by e-anka** [mistic100/Photo-Sphere-Viewer#52]
I'm not sure if this is an issue or a request, but it would be great if one was able to render the photo without the grid of those thin lines, showing sphere segments. On Jeremy Heleine's viewer the grid doesn't show up (but his viewer doesn't support markers), so I think it's possible. Or is it just me, and it's just an option that should be switched on / off?

**Comment by mistic100** [comment]
The grid is only visible when using Canvas rendering, if you enable webgl it won't show up.

**Comment by e-anka** [comment]
Thank you for explaining this, I thought I am missing something!
