### ISSUE TITLE
[Issue] Problem with HUGE viewer and icons.

### ISSUE THREAD

**Issue by EvilTeliportist** [mistic100/Photo-Sphere-Viewer#521]
- **Indicate your Photo-Sphere-Viewer, three.js and web browser versions**
  - Using most recent release of PSV and ThreeJS, tested on Chrome (88.0.4324.190 Official 64-bit).

So I'm trying to configure this to show images hosted on my Django site. I copied the template code directly into my Django template,  like this.
```
<div id="viewer"></div>

<style>
  /* the viewer container must have a defined size */
  #viewer {
    width: 100vw;
    height: 50vh;
  }
</style>

<script>
  var viewer = new PhotoSphereViewer.Viewer({
    container: document.querySelector('#viewer'),
    panorama: '{{ MEDIA_URL }}{{ images }}' <-- This fills in the URL from Django and works correctly.
  });
</script>
```

The issue is that once I go to this page, everything is blown completely out of proportion. I imagine that there's a CSS issue going on? I'll put some image links below. However, when I go fullscreen via the icon, everything is totally fine. Exiting fullscreen brings me back to the page, with the image loaded, but completely zoomed in to the point where the page is around 6000px wide. It's just the nested element I guess that's having issues? To clarify, there is **no other CSS being imported into the page**. I made sure of this just so that I could isolate the issue as much as possible. There are also no additional scripts being used save for jQuery. The image that I'm trying to display is [this](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.alamy.com%2F360-degree-panoramic-view-of-spherical-360-degree-equirectangular-panorama-of-funchal-marina-marina-do-funchal-madeira-image224712093.html&psig=AOvVaw23VCWkIwb44aLpLm7_kBI0&ust=1614646863194000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJCKy7vyje8CFQAAAAAdAAAAABAD) one, but I have also tested with others.

[Screenshots](https://imgur.com/a/wybOcwC)

**Comment by mistic100** [comment]
You just didn't imported the stylesheet of photo sphere viewer. Check the documentation.
