### ISSUE TITLE
Drag and rotate has issue when more than one 360 images are loaded

### ISSUE THREAD

**Issue by rajith869** [mistic100/Photo-Sphere-Viewer#523]
We have added markers on Photosphere viewer, to link to other 360 images. So on-clicking the marker, we are showing another image on a popup div. But when we drag and rotate the image in pop-up, the parent 360 also rotates the same way along with one in Pop-up. Both 360 were loaded on different containers

So is there any way to differentiate the drag event on each element.

**Comment by mistic100** [comment]
Please provide a demo.

**Comment by rajith869** [comment]
https://user-images.githubusercontent.com/62422080/109943142-e1639480-7cfa-11eb-8fff-c5dd1c1d2ac4.mp4

**Comment by mistic100** [comment]
Wouls you consider calling `setPanorama` method instead of creating a new viewer ?

**Comment by rajith869** [comment]
setPanorama is not possible in this case. We need 2 photosphere viewers in a single page. So clicking on markers from primary photosphere viewer, we were creating another photosphere viewer and then showing that one as a pop-up

**Comment by rajith869** [comment]
https://app.togotiki.com/channel/Jeeno/media/Master%20Bedroom%20-%205

Please check this URL. This is how we use photosphere

**Comment by mistic100** [comment]
There is nothing here, says "No preview available."

**Comment by rajith869** [comment]
Ohh shoot, that was my mistake. Could you please check now

**Comment by mistic100** [comment]
The problem is you instanciate the new viewer **inside** the first one (it's inside the markers container ?)

Create it at the same level (inside your #dvImage360Container) and you won't have any problem I think.

**Comment by mistic100** [comment]
Not really, you can exit fullscreen of the first viewer but the browser wont allow you to enter fullscreen of second one because it will be asynchronous.

Best shot is to no use the fullscreen option of PSV but add a custom button to put the whole #dvImage360Container in fullscreen.

**Comment by mistic100** [comment]
you can use `PhotoSphereViewer.utils.requestFullscreen` for that, it is cross browser compatible.

https://photo-sphere-viewer.js.org/api/psv.utils#.requestFullscreen

**Comment by jeenoshibu** [comment]
Is there a way to override the fullscreen button to run the above code?

Or is there a way to add a custom button inside the photosphere viewer to run the above code?

**Comment by rajith869** [comment]
Yes we can add custom buttons inside photosphere viewer.

navbar: [
                'autorotate',
                'markersList',
                {
                    id: 'my-button',
                    content: '<i class="fa s fa-expand"></i>',
                    title: 'Fullscreen',
                    className: 'custom-button',
                    onClick: () => {
                        PhotoSphereViewer.utils.requestFullscreen(document.getElementById("## Element id ##"))
                    }
                }
            ],

**Comment by jeenoshibu** [comment]
Yes, that will work thank you
