### ISSUE TITLE
How to show icon in place of text for custom button ?

### ISSUE THREAD

**Issue by issimissimo** [mistic100/Photo-Sphere-Viewer#524]
Hello, 
how to show icon in place of text for custom button ?
In the guide I can't see any option for the icon.
There's only "content" option, but it show only a string (and I'd like to hide the string and show only the icon).
Many thanks!

**Comment by mistic100** [comment]
You can put an SVG in the `content` property (in fact any HTML is valid, even img tags)

**Comment by issimissimo** [comment]
Many thanks!!
