### ISSUE TITLE
Partially restore 'old' sphereCorrection behaviour (prior to 4.2.0)

### ISSUE THREAD

**Issue by nickw1** [mistic100/Photo-Sphere-Viewer#527]
Hi,

I am developing an application which makes use of PSV and am coming across some problems getting it to work as intended in 4.2.0.

A bit of explanation: I load heading, pitch and roll from a server-side API rather than from the XMP data directly. The application allows users to correct heading, pitch and roll data via a web-based interface if the XMP data is inaccurate (which it frequently is), so the XMP data is sourced from a server-side API rather than directly from the image.

I  *can* get it to work if I set `useXmpData` to `false`. However ideally I do not want to completely turn off loading *all* data from XMP - just the heading, pitch and roll.

The alternative approach of setting the `panoData` option does not work fully for my use-case. The application allows users to correct the heading, pitch and roll through controls in a web interface. See the screenshot below. The yellow line represents the route of a sequence of panos taken along the path, and the markers represent the pano positions themselves. You can see that the route is offset slightly from its real position, which is along the visible path. Note how the interface allows the user to change the heading, pitch and roll; pressing the buttons should move the panorama relative to the markers *without reloading the panorama*.

This works as intended on <4.2 or when `useXmpData` is false. It works by calling `Viewer.setOption()` with `sphereCorrection` set to the new, corrected,  heading (pan), tilt (pitch) and roll values when the user presses the pan, tilt and roll correction controls shown on the screenshot below.

*However* if I try the same thing with `panoData` rather than `sphereCorrection`: I cannot use `setOption()` with `panoData`, I have to re-load the panorama, which is slow and does not lead to the desired effect of changing the panorama rotation relative to the overlaid markers.

Therefore, is it possible to restore part of the pre-4.2 functionality where sphereCorrection can be changed even if it was found in the XMP data? Or, alternatively, a refinement of the `useXmpData` option where you can set it to ignore heading, pitch and roll but use the other XMP data.

Of course, there may be a solution to what I want to achieve without doing this, but after experimentation I have not found a way. Many apologies if so and  please let me know!
![rotationcontrols](https://user-images.githubusercontent.com/585388/110150460-f702b800-7de7-11eb-8a44-b5fb7d9d004b.png)

**Comment by mistic100** [comment]
Would it make sense to apply XMP pose AND sphereCorrection together ? 
(witch means actually implement this line https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/services/Renderer.js#L223)

**Comment by mistic100** [comment]
The problem I have is the `sphereCorrection` was wrongly applied from the begining. Currently the angles are applied in this order : `roll, pan, tilt` but I feel it more natural to be `pan, tilt, roll`.

And it make even less sense when combining XMP pose (applied in pan, tilt, roll order) and sphereCorrection.

So should I change the way sphereCorrection is applied (with or without XMP) and introduce a new breaking change. Or apply it diffrently when there are XMP pose data ? (makes no sense).

**Comment by nickw1** [comment]
@mistic100 would you need to introduce a breaking change or could it all just be done internally without breaking the API? (I don't know, just asking.)

 For my use case it would make sense to have the 'inherent' XMP data plus a `sphereCorrection`. The inherent data could be sourced from the pano's XMP and the `sphereCorrection` could potentially be sourced from elsewhere, such as a server API.

So when the pano is first loaded the inherent XMP data is used, then the `sphereCorrection` could be adjusted with `setOption()` as was possible with <4.2.

**Comment by mistic100** [comment]
I would be grateful if you could test the `pose-correction` branch on your application.

You will have to set `sphereCorrectionReorder: true` to be future-proof.

**Comment by nickw1** [comment]
@mistic100 ok will do.

**Comment by nickw1** [comment]
@mistic100 it appears to be working - but - are there any recent changes that might stop the `select-marker` event being fired in certain circumstances? Any z-index related changes for instance? I find that I can no longer navigate to a panorama by clicking on it on this branch, whereas I could with 4.2.0 and earlier.

I am getting tooltips when I roll over the markers, but the `select-marker` event never seems to be fired.

**Comment by nickw1** [comment]
@mistic100 to add to that: this has definitely happened with this latest commit. If I use the immediate previous commit, the `select-marker` event is fired as expected.

**Comment by mistic100** [comment]
Good catch, it was missing a `recursive` option on the raycaster
