### ISSUE TITLE
Fullscreen problem

### ISSUE THREAD

**Issue by ragcsalo** [mistic100/Photo-Sphere-Viewer#53]
When opened in an IFRAME, the fullscreen mode is applied to the parent window, and not the actual photosphere image. Could you please check it, and fix if possible? :-)

**Comment by mistic100** [comment]
I do not reproduce. Aren't you missing all the necessary attributes ?
```
allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" oallowfullscreen="true" msallowfullscreen="true"
```

if not, setup an online example.

**Comment by ragcsalo** [comment]
Thanks for the quick reply!! Yes, I have all those attributes...
Test page: http://studio360.hu/index2.php
Look for the text "Demó fotó", the iframe is under that text. When I click the fullscreen icon, the main webpage goes fullscreen instead of the content of the iframe... Obviously I'm missing something... but what? :-)

**Comment by mistic100** [comment]
Of it works only on Firefox. I'll as on stackoverflow about Chrome but I'm not really confident.

Why are you using an iframe anyway ? IMHO it's completely useless.

PS: you should disable user interactions (mousemove option) on the header panorama, it's incompatible with your automatic "tour"

**Comment by ragcsalo** [comment]
I'd like to write a panorama viewer "API" that accepts an URL, and displays the panorama in the maximum available size... Thanks for the tip about mouse interactions though! :-)
I've tested video players from an iframe, and fullscreen works well. I don't know what's different with your photosphere viewer...

**Comment by mistic100** [comment]
If you don't tell which players I can't find either...

**Comment by ragcsalo** [comment]
Ohh... now I see that embedded Facebook video has the same problem when entering fullscreen mode. So it must be something with my webpage. Sorry for the false alarm! I'll now investigate my code, hopefully I'll find the problem. I'll post the solution afterwards... Thanks again!!

**Comment by mistic100** [comment]
Yes I confirm, I didn't test very well, a empty page with just the iframe also works on chrome.

**Comment by ragcsalo** [comment]
Solved: the problem was that I was using animate.css, which caused a fullscreen bug in Chrome. More details and solution here: http://stackoverflow.com/questions/32323499/full-screen-video-issue-when-using-animate-css-in-chrome
