### ISSUE TITLE
Markers appears in DOM but not showing up

### ISSUE THREAD

**Issue by jsruinedmylife** [mistic100/Photo-Sphere-Viewer#531]
- Vue 2.6.11
- Photo-Sphere-Viewer 4.2.1
- Chrome 89.0.4389.90 (64bit)

I'm trying to display a simple circle marker from docs example in my simple Vue app, no additional CSS:
```
{
  // circle marker
  id: 'livingRoom',
  circle: 200,
  x: 2500,
  y: 1000,
  tooltip: 'A circle marker'
}
```

As you can see below circle is injected into DOM:
![image](https://user-images.githubusercontent.com/32492739/112719931-db2c9680-8efb-11eb-905e-802a7232e285.png)

but to make it visible I have to add `overflow: visible;` to `.psv-markers-svg-container` and remove `.psv-canvas-container` element or add `position: absolute; z-index: 11111;` to `.psv-markers` and `overflow: visible;` to `.psv-markers-svg-container`

**Comment by mistic100** [comment]
Did you included the CSS files ? (both css files https://photo-sphere-viewer.js.org/plugins/plugin-markers.html)

**Comment by jsruinedmylife** [comment]
Ahh, only the main one, now working as expected, thanks for quick response!
