### ISSUE TITLE
MacOS - Camera rotation bug during fast and short mouse movements

### ISSUE THREAD

**Issue by jsruinedmylife** [mistic100/Photo-Sphere-Viewer#533]
![image](https://user-images.githubusercontent.com/32492739/113143898-f7e30a00-922c-11eb-8cd0-99f8f799f80e.png)
![image](https://user-images.githubusercontent.com/32492739/113143928-ffa2ae80-922c-11eb-88a0-f868c9c114c8.png)

You can see it on video: https://gyazo.com/cc105564e1a120e3b1628615ed26d7cc

It happens also on Safari and Firefox

**Comment by mistic100** [comment]
I don't experience that on Windows or Linux, not having a Mac I couldn't help.

**Comment by mistic100** [comment]
I don't see any problem either on Browserstack.

**Comment by mikepianka** [comment]
Was this the same issue that was fixed in https://github.com/mistic100/Photo-Sphere-Viewer/commit/3bdb207ba09d282339f62bc40099dcfd242d665a? The video is no longer available but it sounds like it could have been similar.
