### ISSUE TITLE
Is there any way to get around of delay between `setPanorama()` call and panorama update in DOM? 

### ISSUE THREAD

**Issue by jsruinedmylife** [mistic100/Photo-Sphere-Viewer#536]
I need to get rid of visible loader for 50-100ms when switching panoramas, any advice on that?

**Comment by mistic100** [comment]
What DOM update are you talking about exactly ? setPanoramadoes an HTTP request, how can it be done without delay ?

The method already returns a Promise resolved when the new panorama is loaded and displayed.

**Comment by jsruinedmylife** [comment]
Yeah, I want to preload all panoramas at once and then just display them from memory, with no HTTP request.

**Comment by mistic100** [comment]
then just set the option to hide the loader  
it will **never** be totally synchronous

**Comment by jsruinedmylife** [comment]
So PSV have to create new blob from image each time it is being displayed? There is no way I can display multiple times already created blob that is stored in variable? Why is it just like that?

**Comment by mistic100** [comment]
Sorry I have not the energy to explain all the internals and how THREE handles it's own cache (because PSV totally relies and THREE Cache for the preload).

**Comment by jsruinedmylife** [comment]
Nevermind, all I had to do is add cache variable to Viewer.js file (and of course use it at the beginning of setPanorama method) and now I'm getting new panorama displayed instantly after setPanorama() function is called with no HTTP request and with no delay.
