### ISSUE TITLE
https://photo-sphere-viewer.js.org/playground.html as an app?

### ISSUE THREAD

**Issue by Thatoo** [mistic100/Photo-Sphere-Viewer#537]
Would it be possible to self host exactly https://photo-sphere-viewer.js.org/playground.html to be able to use it being disconnected from internet?
Could it be a firefox extension? a webapp? anything that can be used easily on a linux OS like ubuntu...
Right now, if I download Photo-Sphere-Viewer-4.2.1.zip, I can't find any playground.html to open...
It's been an hour I'm looking for a free software photo sphere viewer on linux but I can't find any software doing so. It looks like it has to go throw the web with the help of your work for example. But I couldn't find how to do so.
Photo-Sphere-Viewer's Playground is awesome. It just need to be able to be used as a standalone "app/plugin..." to be very handy for people (and without the need of an internet connexion).

**Comment by mistic100** [comment]
It is a vue.js component, the source is here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/docs/.vuepress/components/Playground.vue

You can totally create your own vue application using this code. But I will not provide any support for that.

**Comment by Thatoo** [comment]
Thank you for trying to help but I didn't understand.
I understand you don't want to do this job but if you could let the issue open, maybe someone could read it and help.

**Comment by Thatoo** [comment]
I understand... but I feel sad, I'm actually surprised not to be able to find anything on linux that do what playground does on a webpage and I don't know how to get help.
Thanks anyway. And again, good job.
