### ISSUE TITLE
Broken demo in the /example directory

### ISSUE THREAD

**Issue by wujekbogdan** [mistic100/Photo-Sphere-Viewer#54]
The example in the `/example` directory is broken, there's a `D.min.js:2 Uncaught TypeError: Cannot create property 'deletable' on string 'pin.png'` error in the JS console.

**Comment by mistic100** [comment]
Run `grunt`
Also: https://github.com/mistic100/Photo-Sphere-Viewer/issues/39#issuecomment-213311261

**Comment by wujekbogdan** [comment]
ups. sorry. works like a charm.
