### ISSUE TITLE
[Feature request] Prevent touch panning/rotation when gyro is enabled

### ISSUE THREAD

**Issue by nushydude** [mistic100/Photo-Sphere-Viewer#540]
I couldn't find this in docs, so apologies if this is already available.

Is it possible to prevent touch panning/manual rotation while the gyro plugin is enabled?

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/plugins/plugin-gyroscope.html#configuration

```js
plugins: [
  [ GyroscopePlugin, { touchmove: false }]
]
``

**Comment by nushydude** [comment]
Silly me. Thanks a bunch.
