### ISSUE TITLE
How to get a rotation (bearing?) value?

### ISSUE THREAD

**Issue by lotrmj** [mistic100/Photo-Sphere-Viewer#545]
Hi! I am very sorry if it's a wrong place to ask that question, but I have a need to get a bearing of the view. Is there such a possibility? Something similar to mapillary's "bearingchanged" event: https://mapillary.github.io/mapillary-js/classes/viewer.html#bearingchanged

I use Photo-Sphere-Viewer next to a map. It's very desirable to show panorama's rotation angle symbol on the map. 

I tried using something like this, but I don't know what to do with that position:

> this.pSViewer.on("render", function(){
> 	var pos = this.pSViewer.getPosition();
> });

**Comment by mistic100** [comment]
Hello

there is not "bearing" in Photo Sphere Viewer, in the sense that it is absolutely not related to a any global positionning.

`getPosition` returns the position of the camera inside the sphere, nothing more. `latitude` is left/right and `longitude` is top/bottom. It is not related to GPS at all.

When the viewer scene is constructed, the center of the panorama image is placed at longitude=0, latitude=0
So if you want to know the "global" bearing, you need to know what was the orientation of the camera when the photo was took.

For example if your camera orientation was 60deg, and the viewer position#longitude is 20deg, then the bearing is 80deg.

------

to get the position I recommend

```js
viewer.on('position-updated', (e, position) => {
  // position.longitude
  // position.latitude
});
```

As the documentation says, `render` is called **a lot**.
