### ISSUE TITLE
preload Panorama issue

### ISSUE THREAD

**Issue by Victorfy1214** [mistic100/Photo-Sphere-Viewer#548]
when I call _viewer.textureLoader.preloadPanorama("img1_url")_ in advance and call the method _viewer.setPanorama("img1_url")_ after , I noticed that the devTools shows twice http requests with samiliar request time. just wonder can it be possible that the _setPanorama_ method reuses the cache that requested by the _preloadPanorama_ method.

![image](https://user-images.githubusercontent.com/36722161/121283209-543d6680-c90d-11eb-8a07-2ba89b81dfa0.png)

**Comment by mistic100** [comment]
first are you sure you wait for the preload to complete before calling setPanorama ?

that being said, Photo Sphere Viewer is entirely based on THREE Cache for the preload, that means the http request is cached but not the subsequent transformations to text (for XMP parsing) and blob (for rendering), and what you highlight on your screen is the loading of the blob, it is not an http request.

**Comment by mistic100** [comment]
what you see is probably the creation of the image here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/services/TextureLoader.js#L115

the result of `loadFile` is cached (by THREE) but not `loadImage` 

already discussed here #536

**Comment by Victorfy1214** [comment]
> what you see is probably the creation of the image here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/services/TextureLoader.js#L115
> 
> the result of `loadFile` is cached (by THREE) but not `loadImage`
> 
> already discussed here #536

Thank you for your patiance and detail reply，I now understand how it works. Besides,this project is really helpful. Thanks again
