### ISSUE TITLE
Markers dancing around

### ISSUE THREAD

**Issue by ndsmyter** [mistic100/Photo-Sphere-Viewer#549]
I am using the latest version of the NPM package photo-sphere-viewer (version 4.2.1). I placed several markers on the image with a specific location using latitude and longitude coordinates. I can also see the markers. But whenever I start moving the markers start moving in some weird directions (going up and down, left right etc), but not in line with the movement of th images

Whatch the images below to see how the markers "Compostvat" en "Terras links" move around eachother. The locations of the 2 markers are fixed and not changed between the images. The markers also move differently than the movement of the picutre.
![image0_200](https://user-images.githubusercontent.com/648669/121812464-1ff8db80-cc68-11eb-8040-adff06829a1a.jpg) | ![image1_200](https://user-images.githubusercontent.com/648669/121812467-225b3580-cc68-11eb-8440-5142016c9000.jpg) | ![image2_200](https://user-images.githubusercontent.com/648669/121812469-22f3cc00-cc68-11eb-8f75-05bb40f66dbe.jpg) | ![image3_200](https://user-images.githubusercontent.com/648669/121812468-22f3cc00-cc68-11eb-8b4c-d278ec04bfef.jpg)

**Comment by mistic100** [comment]
Please provide an online demo.

Another user had this issues when overriding the "position" CSS property (it has to stay "absolute")

**Comment by ndsmyter** [comment]
CSS wasn't altered, so that can't be the issue.

Not going to create a completely new online demo for this. That's why I added screenshots.

**Comment by mistic100** [comment]
And i cannot help just from screenshots.

you can fork the Marks demo https://jsfiddle.net/mistic100/kdpqLey2/
