### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by xiaopolan** [mistic100/Photo-Sphere-Viewer#551]
## Issues guidelines
![image](https://user-images.githubusercontent.com/49058272/122378140-46848280-cf98-11eb-9dbd-d96a7d13de8c.png)

- **Indicate your Photo-Sphere-Viewer, three.js and web browser versions**
- Please search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

**Comment by xiaopolan** [comment]
Please tell me the solution

**Comment by cnsyear** [comment]
@xiaopolan 我也遇到这这个问题  可以把图片转成base64就能显示了 。。  不知道你是怎么解决的 请教
