### ISSUE TITLE
The compiled plugin in the /dist directory is out of date

### ISSUE THREAD

**Issue by wujekbogdan** [mistic100/Photo-Sphere-Viewer#56]
the compiled plugin in the `/dist` directory is out of date. It doesn't contain the latest changes and fixes (for example the fisheye feature and the fixed loader animation).

**Comment by mistic100** [comment]
I know, this is how i work.

**Comment by wujekbogdan** [comment]
I see. So the `/dist` directory contains the stable version, and `/src` contains the development version. And you compile the `/dist` when you decide that the development version is stable enough?. Am I right?

**Comment by mistic100** [comment]
Exactly,  after the next iteration development will be done in a "dev" branch
