### ISSUE TITLE
Memorize marker coordonate in .xml file

### ISSUE THREAD

**Issue by fran6t** [mistic100/Photo-Sphere-Viewer#561]
I've buy a DJI drone and i make many sphere, photo-sphere-viewer work very well to publish. 
I want place marker to comment or show particularity but placing marker precisly is difficult for me. 
I have add console.log like this in example/plugin-makers.html
```js
var markers = PSV.getPlugin(PhotoSphereViewer.MarkersPlugin);

  PSV.on('click', function (e, data) {
    if (!data.rightclick) {
      markers.addMarker({
        id       : '#' + Math.random(),
        tooltip  : 'Generated marker',
        longitude: data.longitude,
        latitude : data.latitude,
        image    : 'example/assets/pin-red.png',
        width    : 32,
        height   : 32,
        anchor   : 'bottom center',
        data     : {
          deletable: true,
        },
      });
      console.log('latitude:',data.latitude,'longitude:',data.longitude);
    }
  });
``` 

After read latitude and longitude in console.log i add this value in add  marker
```js
a.push({
            id       : 'Titou',
            tooltip  : {
              content : 'Titou',
              position: 'bottom right',
            },
            //content  : document.getElementById('pin-content').innerHTML,
            latitude: -0.02060821814840952, 
            longitude: 5.620305116370929,
            image    : 'example/assets/pin-blue.png',
            width    : 32,
            height   : 32,
            anchor   : 'bottom center',
          });
``` 

I refresh my page, marker is viewed but isn't at the good place.

Actualy with a form, i generate a .xml with the same name of my .jpg sphère with information id, content, latitude, longitude it work fine but latitude and longitude is manualy find by many test (not with console.log)
Why console.log longitude latitude when markers.addMarker is called don't match with same longitude latitude ine a.push is there a way to make this please ?

Sorry for my very bad english
Many thank's for your work and sharing

**Comment by mistic100** [comment]
I edited your message to have proper code blocks  
see https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by mistic100** [comment]
Vous pouvez écrire en Français si vous voulez.

**Comment by fran6t** [comment]
Désolé, pour la mise en page. 
Alors je ne comprends pas je m’y suis remis et maintenant les coordonnées que je relève via console.log correspondent bien au marqueur que j'ajoute je vais donc pouvoir poursuivre mon petit système. 
En gros ce que je prévois de faire c’est que pour chaque fichier .jpg correspondant à une photo sphère proposer un formulaire qui permettra de générer un fichier .xml de la photo comprenant (titre, les coordonnées, graphique du marqueur et une légende).
Encore merci de m'avoir lu.
Pas de soucis pour supprimer cette issue je suis vraiment désolé

**Comment by mistic100** [comment]
Si le problème persistait j'aurais demandé de mettre en ligne une démo.  
Mais si c'est résolu je ferme :-)

**Comment by fran6t** [comment]
Bonjour, voici ce que j'ai commis avec bien du mal car je ne maitrise pas le javascript. 
Grace à votre travail et à celui d'un autre developpeur chez qui j'ai récupéré l'explorateur de fichier je suis arrivé a mes fins pour un usage familale et perso. 

Je voulais un système me permettant de voir les sphères prises et que je vais continuer à prendre avec un petit drone.

J'ai mis en dépot github ici https://github.com/fran6t/PanoDrone il y a une petit demo ici http://www.wse.fr/PanoDrone/
Pour voir le formulaire il suffit de visualiser une sphère puis de modifier l'url pano.php en pano-xml.php l'idéale aurait été que je place le formulaire de la même façon que l'apparition d'une innerHtml quand on clique sur un marqueur. 

J'ai tenté de placer le formulaire dans un innerHTML mais après c'est trop compliqué et pas recommandé de ce que j'ai vu d'acceder ou modifier les valeurs dans le formulaire et de plus elle ne sont pas persistante quand le innerHtml se cache le formulaire revient vide.

Si je peux encore abuser de votre gentillesse il y a un truc tout bête pour vous certainement, mais que je n'arrive pas à faire à savoir récuperer les logitudes et latitudes d'un marqueur déjà présent. 

Autant cela fonctionne lors de la création d'un marqueur 
```
PSV.on('click', function (e, data) {
    if (!data.rightclick) {
      markers.addMarker({
        id       : '#' + Math.random(),
        tooltip  : 'Generated marker',
        longitude: data.longitude,
        latitude : data.latitude,
        image    : 'example/assets/pin-red.png',
        width    : 32,
        height   : 32,
        anchor   : 'bottom center',
        data     : {
          deletable: true,
        },
      });
      console.log('latitude:',data.latitude,'longitude:',data.longitude);
      document.getElementById('latitudetmp').value = "<latitude>" + data.latitude + "</latitude><longitude>" + data.longitude + "</longitude>"
    }
  });
```
Autant alors que data est présent je n'ai pas de valeur autre que null dans la fonction de l'ajout d'un marqueur console.log ne me renvoi que null
```
markers.on('select-marker', function (e, marker, data) {
    console.log('select', marker.id);
    console.log('latitude:',data.latitude,'longitude:',data.longitude);
    if (marker.data && marker.data.deletable) {
      if (data.dblclick) {
        markers.removeMarker(marker);
      }
      else if (data.rightclick) {
        markers.updateMarker({
          id   : marker.id,
          image: 'example/assets/pin-blue.png',
        });
      }
    }
  });
```

Encore merci pour votre temps et le travail énorme fourni.

**Comment by mistic100** [comment]
Le paramètre `data` de `select-marker` ne contient pas du tout les data du marqueur, ce sont des métadonnées de l’événement (double clique, clique droit)  
cf https://photo-sphere-viewer.js.org/api/psv.plugins.markersplugin#.event:select-marker

les coordinnées du marqueur sont tous simplement dans dans `marker.position` (donnée calculée et nettoyée) et `marker.config` (données brute fournie à `addMarker`)

**Comment by fran6t** [comment]
Génial trop content de votre réponse, je vais pouvoir avancer.
J'abandonne l'idée de mettre les infos dans un fichier .xml, cela me plaisait bien car les infos étaient accessibles par n'importe quel éditeur de texte et très indépendant.
Vu qu'il me faudra toujours un mini serveur web avec php je m'oriente vers le stockage des marqueurs dans une bdd sqlite cela va me simplifier la tache, car pour avoir un formulaire construit a partir d'un fichier .xml avec la description pouvant contenir du html et le nombre de marqueurs non definis à l'avance  j'en arrive a une usine à gaz
Encore merci
