### ISSUE TITLE
Automatic FullScreen

### ISSUE THREAD

**Issue by Toledo95** [mistic100/Photo-Sphere-Viewer#57]
Hello everyone!
i want to put on FullScreen when the page is fully loaded but i can't 

> Failed to execute 'requestFullScreen' on 'Element': API can only be initiated by a user gesture.

what can i do to solve this?

sorry for the bad english

**Comment by mistic100** [comment]
You can't. That's a security in all browsers (like automatically opening popups, etc.)

**Comment by mistic100** [comment]
More info if you care https://fullscreen.spec.whatwg.org/#dom-element-requestfullscreen
see second requirement of point 4, the same authorization as for popups is applied

**Comment by Toledo95** [comment]
Thanks! very helpful.
