### ISSUE TITLE
Does not load with slideshow

### ISSUE THREAD

**Issue by vrestatetest** [mistic100/Photo-Sphere-Viewer#572]
I'm using the photosphere viewer in conjunction with a slideshow on my webpage and when I switch to another slide, the 360 view does not load. 

![psv issue](https://user-images.githubusercontent.com/88336961/131921040-6125fb0f-2612-448b-b76d-8453aea176b2.PNG)

```html
<script>
var slideIndex = 0;
showSlides();

function showSlides() {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";  
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}    
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 2000); // Change image every 2 seconds
}
```

**Comment by mistic100** [comment]
Please provide an online demo.

Most likely you initialize the viewer when it is hidden. This is not possible, theviewer container must be visible for THREE.js to know it's size and initialize the renderer.

You should only initialize the viewer when the slide is totally visible, and you will gain in performance.

**Comment by vrestatetest** [comment]
Ohh ok, I figured it out, thanks!
