### ISSUE TITLE
Open sphere directly centered on a marker

### ISSUE THREAD

**Issue by fran6t** [mistic100/Photo-Sphere-Viewer#573]
Hello,
by default sphere is open centered with defaultLong and defaultLat 0
I read Longitude and latitude of marker i wan't open on center and it work fine when i call PhotoSphereViewer like this.

```
const PSV = new PhotoSphereViewer.Viewer({
    container : 'photosphere',
    panorama   : 'mapshere.jpg',
    caption    : 'Soulac sur mer',
    loadingImg: 'example/assets/photosphere-logo.gif',
    defaultLat : '-0.5778782344161386',
    defaultLong: '2.0146886239008666',

```
 
i detect when sphere is ready, but i don't know how implement method Plugin.gotoMarker

Bonjour,
Ayant repéré la Latitude et Longitude d'un marqueur, il est possible d'ouvrir la sphère en passant defaultLat et defaultLong grand merci d'avoir implémenté cela. 

J'ai ajouté l'interception de l'evenement ready à l'appel de la sphère, mais je n'arrive pas a implémenter l'appel à la methode gottoMarker du plugin marker 

Ci-dessous mon code qui ne fonctionne pas  

```
<script>
  const PSV = new PhotoSphereViewer.Viewer({
    container : 'photosphere',
    panorama   : '<?php echo $quelfic; ?>',
    caption    : '<?php echo addslashes($titre); ?>',
    loadingImg: 'example/assets/photosphere-logo.gif',
    navbar    : [
      'autorotate', 'zoom', 'download', 'markers', 'markersList',
      {
        content  : '💬',
        title    : 'Show all tooltips',
        className: 'custom-button',
        onClick  : function () {
          markers.toggleAllTooltips();
        }
      },
      'caption', 'gyroscope', 'stereo', 'fullscreen',
    ],
    plugins   : [
      PhotoSphereViewer.GyroscopePlugin,
      PhotoSphereViewer.StereoPlugin,
      [PhotoSphereViewer.MarkersPlugin, {
        markers: (function () {
          var a = [];
          <?php echo $jmarqueur; ?> 
          return a;
        }())
      }]
    ]
  });
  var markers = PSV.getPlugin(PhotoSphereViewer.MarkersPlugin);
  
  PSV.on('dblclick', function (e, data) {
    history.back();
  });

  PSV.on('ready', function (e, data) {
   alert('sphere chargee');
    markers.gotoMarker('Marker2', 1500);
  });
</script>

```

D'avance merci pour tout aiguillage ou solution

**Comment by mistic100** [comment]
que veut dire "ne fonctionne pas" ? que ce passe-t-il ? y'a-t-il une erreur dans al console ? peut-on voir ça en ligne ?

**Comment by fran6t** [comment]
Merci de prendre du temps d'après ce que je comprend Marker2 n'est pas trouvé, l'url pas très friendly avec les marqueurs qui fonctionnent est celle-ci
https://d.wse.fr/ExhibMyDrone/PanoDrone/pano.php?p=Spheres%2FAquitaine%2FPhoto_6554212_DJI_612_pano_43110764_0_2021725104316_photo_pano.jpg

La page qui fait l'erreur ou je tente de centrer sur le marqueur ayant l'id Marker2 est celle-ci : 
https://d.wse.fr/ExhibMyDrone/PanoDrone/test.html

Entre les deux pages j'ai juste ajouté ces trois lignes l'evenement ready est bien intercepté je le vois par le alert, dès le click sur ok, markers.gotToMarker('Marker2',1500); indique ne pas trouvé Marker2

```
PSV.on('ready', function (e, data) {
   alert('sphere chargee');
    markers.gotoMarker('Marker2', 1500);
  });

```

**Comment by mistic100** [comment]
Probablement une histoire d'ordonnancement parce que le plugin initialise les marqueurs sur l'event "ready" lui aussi.

**Solution 1**: ne pas fournir les marqueurs à l'init :

```js
PSV.once('ready', () => {
   markers.setMarkers(markers);
   markers.gotoMarker('Marker2');
});
```

**Solution 2**: utiliser setTimeout

```js
PSV.once('ready', () => {
   setTimeout(() => {
     markers.gotoMarker('Marker2');
   });
});
```

**Comment by fran6t** [comment]
Grand merci pour cette aide precieuse. 
https://d.wse.fr/ExhibMyDrone/PanoDrone/test.html

J'ai implémentée la deuxième solution qui fait presque le job, je veux dire par là que oui il y a bien un mouvement qui s'effectue mais pas comme lors du clique sur un marqueur dans le volet de droite, le marqueur n'est pas au centre et la vitesse et plus lente

Je pense que c'est une histoire d'animation et de paramètres de gotoMarker, faut que je trouve ces paramètres j'ai quand même un doute sur l'histoire du centrage

**Comment by mistic100** [comment]
moi je le vois centré

la tempo lors du click dans la liste est de 1000ms 
https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/plugins/markers/index.js#L581

vu que vous n'avez pas mis de paramètre ça utilise la vitesse de base de `autorotateSpeed` qui est de 2 tours par minute

**Comment by fran6t** [comment]
Pffffffffffffff je suis un boulet, oui il est centré je pensais que Marker2 était le batiment bientôt démoli, mais c'est bien le camping car. 
Grand grand merci pout tout, j'ai eu toute mes réponses et vraiment merci car souvent je croise des auteurs qui vous force à découvrir les choses par soit-même c'est vrai que c'est utile bien souvent pour apprendre mais du coup là où pour un spècialiste c'est quelques minutes cela peut être des heures pour le novice. Merci et encore merci pour votre disponibilité. Cela va me permettre de passer un peu plus de temps sur l'assemblage des sphères, je croyais que des sphères 4K étaient impossibles à faire avec le drone DJI mini air 2 et finalement en activant l'option prise de vue jpg + raw nous obtenons bien des prises de vues raw au format 4k il faut ensuite les traiter.
