### ISSUE TITLE
Is it possible to add support for 3D models through plugins?

### ISSUE THREAD

**Issue by Avatarchik** [mistic100/Photo-Sphere-Viewer#574]

**Comment by mistic100** [comment]
You can do anything with plugins https://photo-sphere-viewer.js.org/plugins/writing-a-plugin.html

You will have to be more specific in your request.

**Comment by Avatarchik** [comment]
I would like to add a 3d model to the panorama and put it in a specific place

**Comment by mistic100** [comment]
Within a plugin you have access to the THREE.js scene and can do whatever THREE.js allows.

For example in this plugin I add 3D arrows to the scene 
https://github.com/mistic100/Photo-Sphere-Viewer/blob/tour/src/plugins/virtual-tour/index.js#L267-L283  
https://github.com/mistic100/Photo-Sphere-Viewer/blob/tour/src/plugins/virtual-tour/index.js#L500-L515

However I will not provide help for such usage. You will have to learn THREE.js yourself.  
All i can say is that the panorama is displayed on a sphere of radius 10 and both the sphere and the camera are at the origin (0,0,0) of the scene.

**Comment by Avatarchik** [comment]
Thanks!
