### ISSUE TITLE
Preparing the panorama start with tile_0000.jpg not with tile_0001.jpg

### ISSUE THREAD

**Issue by fran6t** [mistic100/Photo-Sphere-Viewer#577]
Bonjour, j'essaie de faire fonctionner le système de tuile pour les panoramas haute définition. 
Voici mon petit retour d'expèrience

Pour cela j'ai regardé le guide https://photo-sphere-viewer.js.org/guide/adapters/tiles.html#example
Il est donné l'exemple de la commande 
````
magick panorama.jpg -crop 375x375 tile_%04d.jpg
````
Sur ma config pas de commande magick (ubuntu 20.04) c'est convert et je pense qu'il en est de même sur tous les linux
J'arrive à un résultat uniquement si je fournis un rapport 1/2 entre les row et col 
Si je respecte pas cela j'ai juste un message dans la console et le grand picto point d'exclamation avec 
The panorama can't be loaded
````
Object { message: "Panorama cols and rows must be powers of 2...
````
J'ai donc ramené la taille de mon panorama à un rapport 1/2 soit 16000x8000 pour qu'il s'affiche non déformé puis j'ai fais ma decoupe en gardant là aussi un rapport 1/2 avec les row et col
````
convert panorama.jpg -crop 1000x1000 tile_%04d.jpg
````
J'ai donc obtenu 128 fichiers le premier étant tile_0000.jpg le dernier tile_0127.jpg la numération est incorrecte il aurait fallu que cela commence avec tile_0001.jpg

J'ai donc à minima trois façon d'essayer régler le problème. 

1/ Modifier la commande convert pour qu'elle commence avec tile_0001.jpg (pour l'instant je n'ai pas trouvé comment faire)
2/ Faire un petit script qui renome tile_0127.jpg en tile_0128.jpg et ainsi de suite jusqu'à tile_0000.jpg en tile_0001.jpg 
3/ Modifier le script en exemple 

Par ailleurs mes premiers tests je les ai faits en dérivant l'exemple donné, car je n'arrive pas a me procurer 
/dist/adapters/equirectangular-tiles.js

La commande
````
npm install photo-sphere-viewer 
````

crée bien bien un repertoire dist mais sans adapters

Mon premier test est visible ici http://www.wse.fr/help/sphere-tile/tile-test.php comme il manque la tuile 128 il y a un trou forcément. 
 
En récapitulation :
- problème de séquençage qui démarre à 0 avec file_0000.jpg
- problème avec equirectangular-tiles.js que je n'arrive pas à avoir "officiellement"

Et question supplémentaire, les tuiles sont-elles compatibles avec les marker ?

Merci

**Comment by mistic100** [comment]
La numérotation des tuiles est à votre discrétion, il suffit de modifer la fonctio `tileUrl` en conséquence. La documentation par exemple utilise `return `tile_${col}x${row}.jpg`;`. Et si vous utilisez l'exemple du dépot il suffit de faire `+1` sur la variable `num`.

L'adaptateur n'est pas disponible dans le paquet car ce n'est pas encore livré.

**Comment by mistic100** [comment]
> Et question supplémentaire, les tuiles sont-elles compatibles avec les marker ?

dans quel sens ? les markers étant positionné en longitude/latitude ils sont indépendants de système d'affichage de la photo. Je crois même qu'il est possible d'utilise les "coordonnées de de texture" temps que ça fait référence à l'image complète (16000x8000 dans votre cas)

**Comment by fran6t** [comment]
Merci encore une fois, cela répond entiérement à toutes mes interrogations.
Pour les markers c'est à cause de mon très faible niveau javascript, 
je vois dans l'exemple des tuiles que la fonction generateBaseUrl utilise un loader qui après utilise l'objet PhotoSphereViewer

Pour utiliser les markers pour mon niveau et avec l'aide formidable de vos exemples je vois bien que l'on crée PSV qui ensuite permet d'être enrichi par var markers = PSV.getPlugin...

Du coup et c'était là l'objet de ma question, et où vous m'avez rassuré 

C'est simplement que c'est moi qui ne vois pas trop comment est remplacé le PSV puisque c'est la fonction generateBaseUrl qui fait le new PhotoSphereViewer et que du coup j'avais peur d'une incompatibilité faisant que ce serait soit les tuiles soit les markers mais pas les deux.

**Comment by mistic100** [comment]
Comme le dit le commentaire c'est juste pour le démo, un utilisateur standard ne l'utilisera pas comme ça mais comme sur la documentation.

Sent from MailDroid

-----Original Message-----
