### ISSUE TITLE
Loading GIF Hangs

### ISSUE THREAD

**Issue by a2hill** [mistic100/Photo-Sphere-Viewer#59]
The loading gif will hang if `PSV.setPanorama` is called while the viewer is in the process of loading a panorama. The bug occurs at lines [1445-1461 in the `_loadTexture` callback](https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/dist/photo-sphere-viewer.js#L1445-L1461).  
  
Say we have to panos, pano1 and pano2. If we call`setPanorama(pano1)` and then call `setPanorama(pano2)` before pano1 finishes loading the viewer will show pano2 but the loading gif will never be cleared off the screen.  
  
This happens because the once pano1 finished loading it's callback sets `self.loader = null` while pano2 is still loading. Therefore when pano2's callback evaluates the if statement at line 1448 `self.loader.destroy()` is never called.

**Comment by mistic100** [comment]
I'd say it's up to the user to not do a mess and wait for the loading to be complete before changing the image again (all necessary events exists to do so).

It would require a lot a bloat code to be able to cancel the load and ensure everything is coherent.

**Comment by mistic100** [comment]
Simplest guard: throw an error if calling setPanorama while another load is pending

**Comment by a2hill** [comment]
I don't think it's worth a bloated fix to prevent users from trying to do things they shouldn't. But at the same time it was a rather weird bug to track down and it might be worth throwing something in the docs. An error would also be great.
