### ISSUE TITLE
VirtualTourPlugin is not available on NPM

### ISSUE THREAD

**Issue by xukang0222** [mistic100/Photo-Sphere-Viewer#590]
Hello, I want to use VirtualTourPlugin plug-in in NPM, but the latest version is not available, I hope you can update, thank you

![image](https://user-images.githubusercontent.com/47876647/139211008-c964905a-9b3a-48f6-8a63-25936f137043.png)

**Comment by mistic100** [comment]
version 4.4.0 was released
