### ISSUE TITLE
Is there a way to get an updated marker viewerX / viewerY in over-marker event handler?

### ISSUE THREAD

**Issue by zach-luman** [mistic100/Photo-Sphere-Viewer#594]
- My dev env
photo-sphere-viewer@4.3.0
three@0.133.1
google chrome v95.0.4638.54

I want to get the marker's current position (viewerX & Y) within the view container on it's mouse over event handler.

`markersPlugin.on('over-marker', (e, marker) => {
  console.log(marker.data.viewX);
  console.log(marker.data.viewY);
});`

While dragging & spinning the viewer, the marker is also moving in the screen.
However, when I put a cursor over the marker the above console.log outputs the marker's original position of when it was created.
How can I get the current position of the marker in the parent container?

**Comment by mistic100** [comment]
```js
const markerViewerPosition = viewer.dataHelper. sphericalCoordsToViewerCoords(marker.props.position);
```

**Comment by zach-luman** [comment]
Great, thanks!
