### ISSUE TITLE
Problem with Transitions and setPanorama

### ISSUE THREAD

**Issue by jackrugile** [mistic100/Photo-Sphere-Viewer#60]
I'm having two problems with transition feature on the `setPanorama()` method.

---

The first is that even when I set a duration to something like 1500, the next image snaps in immediately. The following demo switches the image after 4 seconds, and it is abrupt, not transitioned.

[View Demo](http://jackrugile.com/360-1/)
[View Source](https://gist.github.com/jackrugile/ace0de8c4f885a2697f63375436c7d46)

---

The second problem is that when I set the blur option to true for transitions, I get the following errors:

- `D.min.js:2 Uncaught TypeError: renderer.getSize is not a function`
- `D.min.js:2 Uncaught TypeError: Cannot set property 'enabled' of undefined`

I added the necessary Three.js dependencies.

[View Demo](http://jackrugile.com/360-2/)
[View Source](https://gist.github.com/jackrugile/5c8db1b749d1b8438f4385d919f6c716)

---

Any ideas what might be causing these problems? I'd be happy just to get the timed transition to work, even without the blur.

Is there a working demo of the transition somewhere?

**Comment by mistic100** [comment]
Yes there is a demo, in the "example" directory.

----

Please try with the dependencies from https://github.com/bodylabs/threejs-examples and tell me if it works better

**Comment by jackrugile** [comment]
Yeah, using the resources from that repo seemed to fix the problem. Thanks!

**Comment by mistic100** [comment]
Leave open, it must be compatible with the most recent version too.

**Comment by mistic100** [comment]
I tried with the examples files from r79 and cannot reproduce.

**Comment by mistic100** [comment]
Still working with latest examples files from https://github.com/mrdoob/three.js and https://github.com/mistic100/three.js-examples
