### ISSUE TITLE
Bring back the panorama-load-progress event

### ISSUE THREAD

**Issue by gocebo** [mistic100/Photo-Sphere-Viewer#602]
In v3 there was a very convenient event `panorama-load-progress` but in v4 it has been removed. Can you please bring it back?

**Comment by mistic100** [comment]
I'll see want I can do (and why I removed it)

**Comment by mistic100** [comment]
So I added "load-progress" which is in fact tied to the visual progress bar itself. Much easier to implement than the previous event that depended on the visualisation mode (equirectangular or cubemap)
