### ISSUE TITLE
Use transitions between panoramas 

### ISSUE THREAD

**Issue by gianemi2** [mistic100/Photo-Sphere-Viewer#604]
Hi mistic100, 
is it possible to use transitions as it was on Photo-Sphere-Viewer 3.0? 

I didn't find anything about transitions on documentation.

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/guide/methods.html#setpanorama-panorama-options-promise

**Comment by gianemi2** [comment]
Thank you mistic100, I thought something like Google Maps where the transition is something like [this](https://media.giphy.com/media/MDgyxn4fk0Tn5VgeXn/giphy-downsized-large.gif). 
Do you think is possible to do this? 

Thanks

**Comment by mistic100** [comment]
This is possible on Google Maps because it is not a single image but multiple images with 3D informations and a lot of engineering. Won't happen in PSV.

**Comment by Avatarchik** [comment]
Hi! Here is the information on how krpano implements it fashionably, https://krpano.com/forum/wbb/index.php?page=Thread&postID=79218
