### ISSUE TITLE
[VirtualTour] Can I change the link marker to any image?

### ISSUE THREAD

**Issue by kokeman** [mistic100/Photo-Sphere-Viewer#606]
I want change the link marker to my png image.

I try
```js
  var viewer = new PhotoSphereViewer.Viewer({
    container: document.querySelector('#viewer'),
    navbar: [
      'zoom',
      'move',
      'fullscreen',
      'caption',
    ],
    defaultLong: 1.5638934539917608,
    plugins    : [
      PhotoSphereViewer.MarkersPlugin,
      [PhotoSphereViewer.VirtualTourPlugin, {
        renderMode : 'markers',
        markerStyle: {
          longitude: 1.614518979150625,
          latitude: -0.45801860285781215,
          image: 'my_png_path',
          width: 30,
          height: 30,
        }
      }]
    ],
  });

```

But i got this error

```
multiple marker content, either image, html, polyg… polylineRad, square, rect, circle, ellipse, path
```

according [this document](https://photo-sphere-viewer.js.org/plugins/plugin-virtual-tour.html#configuration), ```markerStyle```  have html as default, so I can't set image ?

Sorry, I have one more thing to ask.
Can I change the position of the 3D arrow to the position obtained by clicking?
I changed this [exmaple](https://jsfiddle.net/wvhndeor/15/) 's latitude and longitude (l39), but not working.

**Comment by mistic100** [comment]
regarding the marker style this is a bug

----

for you other question I don't understand

**Comment by mistic100** [comment]
A simple fix I made it possible to use this configuration

```js
markerStyle: {
  html : null,
  image: 'path/to/image.png',
}
```
