### ISSUE TITLE
[Marker] Unnatural size change of marker by changing the viewpoint

### ISSUE THREAD

**Issue by kokeman** [mistic100/Photo-Sphere-Viewer#607]
[This](https://jsfiddle.net/Lmk15dbq/8/) is the demo.

The size of the camera marker changes when I move the viewpoint left or right.
When the camera is centered, it becomes larger, and when it is farther away, it becomes smaller, which is unnatural I think.
Is it possible to make it behave as if it were in that location?
Is this because Maker is displaying it separately from the rendering of Three.js?

**Comment by mrAceT** [comment]
I'm sure it can be done..

The image you use is wrapped around a sphere where you are standing in the exact center of it, that is what Three.js does for you. Your marker is "simply an image" placed in a lat/lon position relative to the viewpoint (that center). Nothing more, nothing less.

I think you would need to dive into this:
https://github.com/mistic100/Photo-Sphere-Viewer/issues/427

You would need to calculate/state the distance from your viewpoint to the point of your "camera marker".. take a height and do the calculations.. and then convert that to the size of your image..

**Comment by mrAceT** [comment]
Just clicked that link.. it's a bit old code.. I didn't do the "big calculations" I played around with the zoomlevel and the scale of the marker, to a degree I could live with, as a bases take a peak at:

```
// resize the markers height relative to the height of the pane
   PSV.on('size-updated', function (e, data) {
   for (var i in GeoArchive.markers.markers) {
   var b = GeoArchive.markers.markers[i].data.GA;
   //var factor     = 0.200;//*(Math.pow(1.2,1+PSV.getZoomLevel()/14));
   //console.log(PSV.getZoomLevel()+' '+factor+' '+PSV.config.panorama);
   GeoArchive.markers.updateMarker({
   id   : GeoArchive.markers.markers[i].id,
   scale      : [b[6]*(PSV.dataHelper.prop.size.height/1000)*0.5,
   b[6]*(PSV.dataHelper.prop.size.height/1000)*1.5],
   });
   }
   });
  
```

**Comment by mistic100** [comment]
@kokeman You can easily change the marker size depending on viewer position using the "scale" option as a function  
Demo : https://jsfiddle.net/oL2tagbr/1/

1. save the current position (because currently not provided to the "scale" function)

```js
let position;
viewer.on('position-updated', (e, pos) => {
  position = pos;
});
```

2. Use some math the change the scale depending on the position difference

```js
scale: (zoomLevel) => {
  const basescale = 0.5 + (1 - 0.5) * PhotoSphereViewer.CONSTANTS.EASINGS.inQuad(zoomLevel / 100);
  if (!position) {
    return basescale;
  }

  // 0 = longitude of the marker
  const dLong = Math.abs(PhotoSphereViewer.utils.getShortestArc(0, position.longitude));
  return basescale + dLong / 4;
}
```

here basescale uses the same formula when "scale" is an array : https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/plugins/markers/Marker.js#L227

**Comment by mistic100** [comment]
Please tell me if this make sense in your use case, I could clean it up and add this option for everyone

**Comment by mistic100** [comment]
@mrAceT I don't understand why the marker size should change when the viewer size change... at least I don't think it is what OP is asking for

**Comment by mrAceT** [comment]
> Is it possible to make it behave as if it were in that location?

This means that when one zooms in the image needs to become bigger (and smaller zooming out) This would give the effect of the image being part of it's surroundings

**Comment by mistic100** [comment]
So I implemented a way to define the scale depending on the longitude offset. Extract from the documentation :

#### `scale`
- type: `double[] | { zoom: double[], longitude: [] }`
- default: no scalling

Configures the scale of the marker depending on the zoom level and/or the longitude offset. This aims to give a natural feeling to the size of the marker as the users zooms and moves.
_(This option is ignored for polygons and polylines)_

Scales depending on zoom level, the array contains `[scale at minimum zoom, scale at maximum zoom]` :
```js
scale: {
  // the marker is twice smaller on the minimum zoom level
  zoom: [0.5, 1]
}

// same thing
scale: [0.5, 1]
```

Scales depending on position, the array contains `[scale on center, scale on the side]` :
```js
scale: {
  // the marker is twice bigger when on the side of the screen
  longitude: [1, 2]
}
```

Of course the two configurations can be combined :
```js
scale: {
  zoom: [0.5, 1],
  longitude: [1, 1.5]
}
```
