### ISSUE TITLE
[Feature] Overview of Nodes in Virtual Tour Plugin

### ISSUE THREAD

**Issue by Skayo** [mistic100/Photo-Sphere-Viewer#609]
I think it would be really nice to have a little overview of all nodes in the virtual tour, where you can see all nodes and switch to them.

[Here's an example from theasys](https://www.theasys.io/samples/)
(just clicked the button in the center at the bottom of the panorama)
![Example](https://user-images.githubusercontent.com/10259118/146820703-4e47cb90-90a1-4f82-b916-40860d84a7a2.png)

It could be located above/below the navbar and maybe get hidden when clicking a button in the navbar.
For my app I've implemented such a feature myself, but it think it would be a nice addition to the actual plugin!
In server mode you could display the preloaded ones only, or disable it completely?

Let me know what you think!

P.S.: Do you have a donation link?

**Comment by mistic100** [comment]
If something it will be in the side panel lik the list of markers https://photo-sphere-viewer.js.org/plugins/plugin-markers.html#example

Don't need to create another UI element.

**Comment by mistic100** [comment]
@Skayo what do you think of this ?
![Screenshot 2021-12-24 at 19-14-41 PhotoSphereViewer - virtual tour demo](https://user-images.githubusercontent.com/41597/147368407-55a63f93-7f5e-4718-b558-d8d42051110f.png)

**Comment by Skayo** [comment]
@mistic100 oh I didn't think you're working on this! Looks good!
