### ISSUE TITLE
[Feature] Map for Virtual Tour

### ISSUE THREAD

**Issue by Skayo** [mistic100/Photo-Sphere-Viewer#610]
I think, a map would be a really nice addition to the virtual tour.
It could be a combination between the compass plugin and the virtual tour plugin, where you can see the nodes on the map and switch to them directly, and similar to the compass plugin you could see your current orientation on the map.

[theasys](https://www.theasys.io) has a map feature, but it's a little bit weird and I'm trying to switch to your awesome library instead (thank you btw!). 
So here's an example on how it looks on theasys:
![Example](https://user-images.githubusercontent.com/10259118/146823344-996b6fce-0bc3-4bff-8e5d-eac82fa40ce0.png)

You could display it in a panel and for the position of the map icons you could use the GPS position and maybe allow providing a `mapPosition` for the node, which just refers to the position on the image itself.

Let me know what you think!

P.S.: Do you have a donation link?

**Comment by mistic100** [comment]
I think it becomes too mush specific to be implemented in this package. This would require a LOT of additional configuration to correctly geopositionate the floor map.

I think you have all the necessary tools to make it yourself :
- custom buttons https://photo-sphere-viewer.js.org/guide/navbar.html#custom-buttons
- use the panel https://photo-sphere-viewer.js.org/guide/components/panel.html#example
