### ISSUE TITLE
doc: markers GUI

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#613]
Similar to the playground (or directly in the playground) add an interface to create, import and export markers.

**Comment by zatakiya** [comment]
Documentation on [this](https://photo-sphere-viewer.js.org/plugins/markers.html) page says You can try markers live in [the playground](https://photo-sphere-viewer.js.org/playground.html),  but markers tab in playground shows Coming Soon message. 

Any ETA for that feature?

**Comment by mistic100** [comment]
Nope, I didn't re-coded it when changing the documentation framework and I don't think I will.

**Comment by mistic100** [comment]
The culprit message and tab has been removed.
