### ISSUE TITLE
VirtualTourPlugin  question

### ISSUE THREAD

**Issue by wangsen423** [mistic100/Photo-Sphere-Viewer#617]
Virtualtourplugin, about the arrow display, I wrote in the Vue project according to the example, which is different from the demo. What is the reason
![66659bb903826187c1914732ebb13a4](https://user-images.githubusercontent.com/22238381/149495954-9244768a-a3c1-48d4-adeb-121c9f398879.png)
![1642153769(1)](https://user-images.githubusercontent.com/22238381/149495964-cc21b652-d5ba-4529-a708-10629d9f1ed4.jpg)

**Comment by mistic100** [comment]
This is the `renderMode` option https://photo-sphere-viewer.js.org/plugins/plugin-virtual-tour.html#configuration
