### ISSUE TITLE
toggle custom button

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#618]
Hi, I'm a newbie and maybe I'm saying something dumb....

i'd like to use fisheye rendering depending on toggling or not a button in the navbar.

Is there a way to toggle fisheye option with a custom button?

Thanks.

**Comment by mistic100** [comment]
Yes

add a custom button to you navbar https://photo-sphere-viewer.js.org/guide/navbar.html#custom-buttons  
and use the "setOption" method https://photo-sphere-viewer.js.org/guide/methods.html#setoption-option-value

Alternatively you could use the settings plugin https://photo-sphere-viewer.js.org/plugins/plugin-settings.html

**Comment by haldo98** [comment]
thank You. works perfectly, but only one way.
clicking the button enables the fisheye option. If I click again nothing happens... (obviously... it's a "onClick")

is there a way to have a button toggling on/off some function?

Thanks again

**Comment by mistic100** [comment]
you must track yourself the state of the option using a variable

**Comment by haldo98** [comment]
as I said ...i'm  a newbie and I don't know where to put the let

I solved with two button ... fisheye on and fisheye off

but the fisheye effect only applies after a slight movement of the image and not immediately. Is a documented behaviour?

Thank You

**Comment by mistic100** [comment]
> as I said ...i'm a newbie and I don't know where to put the let

perhaps it is time to take some online course :) https://js-tutorials.info/variable-scope-in-javascript/  
put it anywere in your code, for example just before creating the viewer.

> but the fisheye effect only applies after a slight movement of the image and not immediately. Is a documented behaviour?

I'll take a look, I think I know why this is the case.

**Comment by haldo98** [comment]
> put somewhere in your code where it is accessible to "onClick", for example just before creating the viewer.

:))))     works like a charm now....  thank You!!!!!!!!!!!!!!!!!!

**Comment by mistic100** [comment]
@haldo98 just wanted to thank you for all your recent bug reports. Almost everything in [version 4.4.3](https://github.com/mistic100/Photo-Sphere-Viewer/releases/tag/4.4.3) comes from your findings.

**Comment by haldo98** [comment]
Thanks to you and your great work.....
