### ISSUE TITLE
Compass Plugin

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#619]
I use the compass plugin and I managed to set the real north of the image with the panodata - poseheading setting.
How can I start the PSV in a different position than the north (example south - 180 degrees) ?

And when using compass plugin and fisheye strange behaviour happens...   when clicking on the hotspot on the compass and then clicking the fisheye button the image goes to zenit.

check my test page:

https://www.tadini.it/photosphere/test/P.htm
sorry for the ugly image   :)

Thank You.

**Comment by mistic100** [comment]
> I use the compass plugin and I managed to set the real north of the image with the panodata - poseheading setting. How can I start the PSV in a different position than the north (example south - 180 degrees) ?

https://photo-sphere-viewer.js.org/guide/config.html#defaultlong

> And when using compass plugin and fisheye strange behaviour happens... when clicking on the hotspot on the compass and then clicking the fisheye button the image goes to zenit.

Weird

**Comment by haldo98** [comment]
> > I use the compass plugin and I managed to set the real north of the image with the panodata - poseheading setting. How can I start the PSV in a different position than the north (example south - 180 degrees) ?
> 
> https://photo-sphere-viewer.js.org/guide/config.html#defaultlong

Thank You.... I saw that and used it but did not work the first time. I was using the wrong parameter. Now it works.
Thank You.

**Comment by haldo98** [comment]
strange.... the page we were talking about this morning....

https://www.tadini.it/photosphere/test/PS_.htm

about the double declaration of the plugin array....  I fixed it and it showed correctly both compass and markers...

but now with 4.4.3 the compass disappeared... 

and in this page...    https://www.tadini.it/photosphere/test/Panorama_bregagno.htm   we were talking yesterday

the panorama with 4.4.3  won't load.  In this page there was three plugin compass, marker and virtual tour


Thank You

**Comment by mistic100** [comment]
That's because jsdelivr takes time to propagate the new version, wait a few more hours

once this file indicates "Photo Sphere Viewer 4.4.3" instead of "4.4.2" it will work https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.js

**Comment by haldo98** [comment]
Aw.. thank You. I did not know.
