### ISSUE TITLE
Feature Request: panorama-updated Event

### ISSUE THREAD

**Issue by jackrugile** [mistic100/Photo-Sphere-Viewer#62]
When using the `setPanorama()` method to change the panorama image, it would be nice to have an event that fires when the loading process is complete. This can sometimes take 1-3 seconds to complete, which is kind of a long time in UI world.

**Comment by mistic100** [comment]
`setPanorama` already returns a promise.

```js
viewer.setPanorama('path')
  .then(function() {
    alert('done');
  });
```
