### ISSUE TITLE
android issues

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#620]
https://www.tadini.it/photosphere/test/panorama_B.htm

https://www.tadini.it/photosphere/test/panorama_G.htm

with the latest release of chrome browser and android 11 on my xiaomi 11 the two pages linked before has strange issues.

- if right after the complete charging of the page I click on the dots on the right of the panel... the dots disappear. and appears the autorotate icon.
If I wait.... like ten seconds.... and then hit the dots .. it opens the setting panel correctly.   But in the panel the names of "content" and "title" of the custom button overlaps each other.

Is it normal than on the right there is no white border? (like on top, bottom and left)

now another issue on PC and chrome or other browser:
- if i hit twice the left or right icon the home icon (custom button) is selected and became blue.

- Is there a problem if I declare the use of .css and scripts even if I'm not using them?  (for the moment)

Like virtual tour css and js but there is no usage of the virtual tour in the script.

Thank you !!!

**Comment by mistic100** [comment]
> if right after the complete charging of the page I click on the dots on the right of the panel... the dots disappear. and appears the autorotate icon.

this is expected and due to the lazy detection of touch screen support.

> If I wait.... like ten seconds.... and then hit the dots .. it opens the setting panel correctly. But in the panel the names of "content" and "title" of the custom button overlaps each other.

please provide a screenshot of this overlap

> Is it normal than on the right there is no white border? (like on top, bottom and left)

these are the margins of your page (default browser margins), nothing to do with PSV

> if i hit twice the left or right icon the home icon (custom button) is selected and became blue.

this is also default browser behavior, try it on any text

> Is there a problem if I declare the use of .css and scripts even if I'm not using them? (for the moment)

no problem

**Comment by haldo98** [comment]
![Screenshot_2022-01-18-16-46-48-497_com android chrome](https://user-images.githubusercontent.com/97630238/149977472-292aacb2-2ece-41dc-8c86-02f0bd8ad32f.jpg)


the third row....  image in attachment

Thank you for your patience...!!!!!

**Comment by mistic100** [comment]
This is because your "Peak finder" icon has text as `content` and not an icon this is not handled correctly by the menu. Right now I cannot think of a good solution.

**Comment by haldo98** [comment]
> This is because your "Peak finder" icon has text as `content` and not an icon, this is not handled correctly by the menu. Right now I cannot think of a good general solution.

I use now an image as icon and works correctly.... Thank You...

However I saw that if I empty cache and history on my android device the panorama page shows like this... with all the icons in the lower part, 

![Screenshot_2022-01-20-09-38-43-790_com android chrome](https://user-images.githubusercontent.com/97630238/150372132-fc73b425-d4e5-4341-9e71-2b784a01eaee.jpg)


If afterwards I reload the page the panorama shows as usual...

![Screenshot_2022-01-20-09-39-46-187_com android chrome](https://user-images.githubusercontent.com/97630238/150372305-39f0eb93-d37d-47e8-86a6-f2bcc66c803a.jpg)

Is it normal?


I also noticed that the compass is not tappable...  like clicking on the normal pc browser.

**Comment by mistic100** [comment]
> However I saw that if I empty cache and history on my android device the panorama page shows like this... with all the icons in the lower part,

I can't tell you deleted your test pages. 
You should **really** remove the page default margin, this probably messes up the size detection.

> I also noticed that the compass is not tappable

I'll check

**Comment by mistic100** [comment]
The panorama does not load.

Sent from MailDroid

-----Original Message-----

**Comment by mistic100** [comment]
So I don't see anything wrong, it works as expected. As I said the detection of touch screen is asynchronous, it requires to user to touch the screen at least once to be detected.

So at first the zoom and move buttons are shown because it it assumed to be a standard screen + mouse, and the left menu is visible because there is not enough room for the other buttons. Once you touch the screen, the zoom and move buttons are hidden, and the menu is expected because more space is available.

**Comment by mistic100** [comment]
The compass issue will be tracked here #624
