### ISSUE TITLE
Virtual Tour

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#622]
I managed to start implementing virtual tour with markers, connecting different panoramas.
Basically I want to use it to connect different mountain peaks panoramas.

I don't think that this could be done.... however.... It would be nice if somehow some parameter could be passed to the connected panorama.
Meaning: when from a peak I click on the marker placed on another peak it opens the connected panorama facing where I was coming (the peak I was before) and not the normal defaultLong parameter in the script.

Thank You.

**Comment by mistic100** [comment]
Acttually it does not apply the defaultLong and defaultLat when switching panoramas, it keep the same orientation. So as long as all your image are oriented the same, it should be fine.

On the demo the bearing is conserved when navigating https://photo-sphere-viewer.js.org/plugins/plugin-virtual-tour.html#example (this was done my epirically setting `panoData.poseHeading` for each node instead of modifying the files)

**Comment by mistic100** [comment]
Ok I re-read your message and you actually want to total reverse of that : face where you where. I don't think this will be possible, I also think this would be very confusing for the user.

**Comment by mistic100** [comment]
However I could add some usefull metadata on the `node-changed` event, this way you could call `rotate` or `animate` after the transition

**Comment by haldo98** [comment]
> Ok I re-read your message and you actually want the total reverse of that : face where you where. I don't think this will be possible, I also think this would be very confusing for the user.

never mind... it was just a thought




> However I could add some usefull metadata on the `node-changed` event, this way you could call `rotate` or `animate` after the transition

elegant solution....


Thank you for your patience.

**Comment by mistic100** [comment]
example usage once this is published

```js
  virtualTour.on('node-changed', (e, nodeId, data) => {
    if (data.fromLinkPosition) {
      viewer.animate({
        longitude: data.fromLinkPosition.longitude - Math.PI,
        latitude: data.fromLinkPosition.latitude,
        speed: 1000,
      });
    }
  });
```

**Comment by haldo98** [comment]
I tried to apply the new feature and it works. After the click and the change of the image it rotates to the point where it came from.

I noticed that just before clicking on the link there's a movement towards up and this up-position applies also to the new image.

Is there a way to apply defaultZoomLvl to the clicked image ?

Thank You
