### ISSUE TITLE
Virtual Tour - dummy question

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#623]
I'm a newbie so......

I managed to get the virtual tour links on my pano...

https://www.tadini.it/photosphere/test/panorama_bregagno.htm

but even if  i declare the "markers" render....    the pano shows as 3d
I guessed it was the panodata and I added to the node declaration... but If I do the pano shows correctly but the marker disappear....

Thank You.

**Comment by mistic100** [comment]
you should use HTML5 doctype, HTML 4 is just completely outdated https://www.geeksforgeeks.org/html-doctypes/

remove the initial "panorama" and "panoData", these are overridden by the plugin anyway (and this is why you get "Loading was aborted" error in the console)  
"panoData" must be defined on each node https://photo-sphere-viewer.js.org/plugins/plugin-virtual-tour.html#nodes-options

I finally I do see markers on your page....

**Comment by haldo98** [comment]
Yes....   works now....  

Thank You !!!!!!!!!

**Comment by haldo98** [comment]
but I have another question:

in the linked panorama the default view is towards north (poseheading value) 
I tried to add defaultLong and also defaultZoomLvl (the two panoramas has different settings) ... but it doesn't work.

can I open the linked pano with zoom level and longitude set differently?


and also If I add the compass plugin it works only for the first image....   should it be set in the nodes?

Thank You again for your patience.....

**Comment by mistic100** [comment]
> can I open the linked pano with zoom level and longitude set differently?

no, that's whay I answered in the other thread, the current viewer orientation is kept, only the poseHeading can be changed.

> and also If I add the compass plugin it works only for the first image

what do you mean ? it seems to work perfectly on your demo

**Comment by haldo98** [comment]
> > can I open the linked pano with zoom level and longitude set differently?
> 
> no, that's whay I answered in the other thread, the current viewer orientation is kept, only the poseHeading can be changed.

I guessed so....    but I asked just to be sure.

> 
> > and also If I add the compass plugin it works only for the first image
> 
> what do you mean ? it seems to work perfectly on your demo

Yes it works but the orientation messes up after the back and forth from one pano to other...

these are the two panos.. with the correct orientation....

https://www.tadini.it/photosphere/test/panorama_bregagno.htm

https://www.tadini.it/photosphere/test/panorama_legnoncino.htm

if from the previous one (bregagno) I go to the second.. (legnoncino) the north is different


Thank You,

**Comment by mistic100** [comment]
Ok that's much more clear. Please refrain to just say "it does not work" when encountering a bug, it is never useful.

**Comment by haldo98** [comment]
> Ok that's much more clear. Please refrain to just say "it does not work" when encountering a bug, it is never useful.

sorry....

**Comment by mistic100** [comment]
I tracked down the problem into the cross-fade animation not applying correctly the "panoData". Next version will fix it.
