### ISSUE TITLE
Virtual Tour config

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#625]
same link as before:

https://www.tadini.it/photosphere/test/panorama_bregagno.htm

I read the config page of the plugin and it seems that the listButton (in client data mode) and linksOnCompass (markers render mode)  are true by default ....so I should not declare them and they should compare on the page by themselves. I have client mode and markers mode....

But even if I declare them in the plugin the button and the links on compass won't show.

What I did wrong?

Thank You.

**Comment by mistic100** [comment]
`listButton` is not working because you overwrote the "navbar" definition, you need to add `'nodesList'` somewhere, I'll update the documentation about that.

`linksOnCompass` is not working because of the order of the plugins, CompassPlugin needs te be before VirtualTourPlugin

**Comment by mistic100** [comment]
There is room for improvement about the last point #626

**Comment by haldo98** [comment]
great!!!   everything as expected....   I guess that the cardinal point East West South North in the Normal compass are overwritten because it would be a mess of points.....

**Comment by mistic100** [comment]
You are right, the default `hotspots` of the compass plugin are totally removed by the virtual tour plugin. Do you have a need for it ?

**Comment by mistic100** [comment]
The buttons documentation has been updated  
here https://photo-sphere-viewer.js.org/guide/navbar.html#plugins-buttons  
and here https://photo-sphere-viewer.js.org/plugins/plugin-virtual-tour.html#listbutton

**Comment by haldo98** [comment]
>  Do you have a need for it ?

Not at all. It would be messy.
Thank You for your great work,...    and for your patience.
