### ISSUE TITLE
Marker Plugin Help 

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#628]
https://www.tadini.it/photosphere/test/PS_.htm

I managed to declare two markers  "c" and "g"

I want to trigger an event "window.location" on doubleclicking the marker...

```js
markersPlugin.on('select-marker', function(e, marker, data) {
  if (data.dblclick) {
    window.location=('https://www.corriere.com');
  }
});
markersPlugin.on('select-marker', function(e, marker, data) {
  if (data.dblclick) {
    window.location=('https://www.google.com');
  }
});
```

But I don't know how to differentiate the marker click....     :)   I tried else if but no effect.

I also have the generated marker on click (from your example on the marker page) 
I want to obtain the coordimnates from the generated marker and I saw the #594 
with the:

```js
const markerViewerPosition = viewer.dataHelper.sphericalCoordsToViewerCoords(marker.props.position);
```

if I interpreted correctly...  I tried but I don't get the result.

and In the page I have the compass plugin but it does not show. I remember what you said about the order of plugins and I switched the position between markers and compass plugin.  But what is at the first place disappear...  (markers or compass)

Thank You a lot...

**Comment by mistic100** [comment]
When posting code, use markdown formatting, see https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

----

> But I don't know how to differentiate the marker click.... :) I tried else if but no effect.

What do you want to differentiate ?   
Which marker was clicked ? you have the `marker` parameter for that, it has the original `id` property and you can add [additional `data`](But I don't know how to differentiate the marker click.... :) I tried else if but no effect.)

Also **do not** declare the event listener twice.

> I want to obtain the coordimnates from the generated marker

Which coordinates ? There are two sets of coordinates : x/y on the original panorama file or longitude/latitude in the viewer.

> if I interpreted correctly... I tried but I don't get the result.

Again you are basically saying "it does not work" but you are not explaining what you want.

> I have the compass plugin but it does not show

This is because you declared the `plugins` array twice, the second one is completely overriding the first one.

**Comment by mistic100** [comment]
I'll ask you to be more precise in your questions, if you would explain what you are trying to achieve it would be much easier for me to help. For example why are you trying the get the coordinates of generated markers ? There is not a single anwser, and it will depend on what you are trying to achieve.

**Comment by haldo98** [comment]
sorry my bad....   I apologize if I wrote something wrong. I did not mean "It does not work"

Yes i declare the array twice....   I'm learning and I'm making mistakes. I corrected and now displays both compass and markers.
Thank You.

About the marker. I want that when I click the red marker opens 1 webpage and when i click the blue marker opens another webpage.

Coordinates. 
The generated pin is not permanent, but volatile. If I refresh the page is not there anymore.
I want to obtain the coordinates (long and lat) of the generated pin.  Or to read it somewhere so I can put them in a declared marker.

I hope I have explained things better than before...
Thank You again for your patience.

**Comment by mistic100** [comment]
> About the marker. I want that when I click the red marker opens 1 webpage and when i click the blue marker opens another webpage.

As I said, use the `marker` parameter

```js
markersPlugin.on('select-marker', function(e, marker, data) {
  if (data.dblclick && marker.id === 'c') {
    window.location.href = 'https://www.corriere.com';
  }
  else if (data.dblclick && marker.id === 'g') {
    window.location.href = 'https://www.google.com';
  }
});
```

> Coordinates. The generated pin is not permanent, but volatile. If I refresh the page is not there anymore. I want to obtain the coordinates (long and lat) of the generated pin.

Then just save the data somewhere in your `click` handler.... You don't have to obtain anything you already have the coordinates.

```js
viewer.on('click', function(e, data) {
  if (!data.rightclick) {
    // add the marker, you already did that

    // save `data.longitude` and `data.longitude` for later use
  }
});
```
