### ISSUE TITLE
360 fisheye compatible?

### ISSUE THREAD

**Issue by bonomite** [mistic100/Photo-Sphere-Viewer#63]
Does the fisheye effect allow your system to correctly display images like this?
![vr](https://cloud.githubusercontent.com/assets/13803343/17368049/7e367e26-5960-11e6-8736-aed745577002.jpg)

**Comment by mistic100** [comment]
No. The source image must be an equirectangular projection.

The fisheye option is only for the render mode.

There must be software to convert images between different projectios (with quality loss of course).
