### ISSUE TITLE
Virtual Tour new config

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#630]
I applied what is new in #622 

the new feature and it works. After the click and the change of the pano it rotates to the point where it came from.

I noticed that just after clicking on the link there's a movement towards up and this up-position applies also to the new image.

Is there a way to apply different defaultZoomLvl to the second (and third ... and so on) pano ?

https://www.tadini.it/photosphere/test/panorama_bregagno.htm

Thank You

**Comment by mistic100** [comment]
Are you talking about latitude or  zoom ? `defaultZoomLvl` is for... zoom

Anyway the answer is still the same, the defaults cannot be changed.

----

If this automatic rotation does not suits you, which is understandable by your use case, just disable it :  
https://photo-sphere-viewer.js.org/plugins/plugin-virtual-tour.html#configuration

**Comment by mistic100** [comment]
Also the code I gave you **can** be modified, you can add an offset to the `latitude`

```js
  virtualTour.on('node-changed', (e, nodeId, data) => {
    if (data.fromLinkPosition) {
      viewer.animate({
        longitude: data.fromLinkPosition.longitude - Math.PI,
        latitude: data.fromLinkPosition.latitude + Math.PI / 10, // <= HERE
        speed: 1000,
      });
    }
  });
```

**Comment by haldo98** [comment]
Thank You for your patience....
