### ISSUE TITLE
[Suggestion] Convert equirectangular images to cubemaps internally

### ISSUE THREAD

**Issue by Skayo** [mistic100/Photo-Sphere-Viewer#633]
After my research for #631 yesterday I kept wondering why you don't use cube maps everywhere instead of using these spheres to render the panorama. There is a clear benefit of using them, even if it's just converted internally!
I've found this thread [here](https://discourse.threejs.org/t/how-to-render-360-degree-images-on-three-js-without-noize-like-panolens-js/21020), which kinda demonstrates how to do that without much effort. [Here's a demo](https://jsfiddle.net/btwz3261/)

I'm not sure how complicated that would actually be for your codebase and adapters. But this is just a suggestion on how you could improve the panorama a lot. It could definitely affect the performance too, because you just need wayyy less polygons!
But after all, I'm no expert. So if you want to keep everything like it is right now, that's fine.
Maybe I'll actually look into writing my own panorama viewer using just plain three.js....

**Comment by mistic100** [comment]
Interesting, it does not even seems to be a an actual conversion (I already looked at that and the math is really painful), only a clever shader applied to the scene.

I will look into this, it could not be used for the Equirectangular Tiles adapter, for sure it could improve the Equirctangular adapter.

**Comment by mistic100** [comment]
For the record the base renderer is from the original library https://github.com/JeremyHeleine/Photo-Sphere-Viewer and I never tried to change it.

**Comment by mistic100** [comment]
So it works very well. Only problem for now is that the scene background cannot be rotated (to appli panoData and sphereCorrection). But as it uses a simple BoxGeometry with shaders I could replicate it to my own mesh https://github.com/mrdoob/three.js/blob/master/src/renderers/webgl/WebGLBackground.js#L66-L78

**Comment by mistic100** [comment]
Unfortunately that won't be possible, the necessary internals  are not exported by three package, I don't want to copy so much code.
