### ISSUE TITLE
Unable to use `addMarker` in NEXT.js

### ISSUE THREAD

**Issue by huedaya** [mistic100/Photo-Sphere-Viewer#634]
## The Problem
Hi, I tried to implement PSV using NEXT.js and am still unable to use `addMarker` function inside `useEffect()` hook. Previously I tried to code it in React and working, but don't know why isn't working here. The weirdest thing is.... the console says nothing. 

Here I provide the example code. Need help, thanks in advance.

## Specification
- Browser: Brave [Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)] / Kubuntu 20.10
- PSV Version: 4.4.1

## Code Example that Not Working  
- https://stackblitz.com/edit/nextjs-bve86a?file=pages/index.js

## Solved :heavy_check_mark: 
- Working code: https://stackblitz.com/edit/nextjs-ro9gee?file=pages/index.js

**Comment by huedaya** [comment]
Adding more debug info:

When I tried calling `addMarker` the value of the current viewer is changed and the marker added into the variable (`markers`), indicating that that function is called successfully. But nothing pops up, is it something wrong with the render-ish function?
![image](https://user-images.githubusercontent.com/4969689/151506834-2b73249b-1070-4660-94d9-4f6d91ba7c9f.png)


But, what's makes this thing more confusing is when I tried to inject those markers when a view created for the first time, it's showing up, but the value of `markers` is empty? maybe anyone can help explain this condition?
![image](https://user-images.githubusercontent.com/4969689/151507120-01dfbf6a-dfc6-400a-b039-aa8098073977.png)

**Comment by mistic100** [comment]
1. this is not how you get the instance of the plugin, it is explained here https://photo-sphere-viewer.js.org/plugins/#import-official-plugins (there is incorrect `new` on the example code, I will remove it)

```js
let marker = spherePlayerInstance.getPlugin(MarkersPlugin);
```

2. you must wait for the `ready` event before calling methods https://photo-sphere-viewer.js.org/guide/methods.html

```js
spherePlayerInstance.once('ready', () => {
  ...
});
```

**Comment by huedaya** [comment]
Alright, working like a charm! Thanks, @mistic100!!

I attach the working code here https://stackblitz.com/edit/nextjs-ro9gee?file=pages/index.js, just in case someone found this PR useful.

**Comment by mistic100** [comment]
I am absolutely not an expert in react but I though  `useEffect` is called everytime the component needs to update. Not a problem here as there is nothing to update, but if the component grows, won't it constantly destroy and recreate the viewer ?

**Comment by huedaya** [comment]
I'm also still new in React, and for demo purposes, I skip that but for the project, I currently working on, I pass the second argument which made the `userEffect` hook only watch specific state changes. Thanks for your suggestion :+1:

**Comment by mkubdev** [comment]
Hi @huedaya, i'm using your code to add PSV into next.js ! But i'm facing two major issue :
* First is since i'm adding the `.destroy()`, i get `TypeError: Cannot read properties of undefined (reading 'loader')` error, so i need to remove it.

* Second, the `useEffect()` hook generate 2 or 3 (it's inconsistent) PSV instance on my page which is not a desired behaviour. How do you manage to only create one instance of PSV ?

Kudos for @mistic100 for PSV, already using in Angular framework and it's working like a charm. ✨
