### ISSUE TITLE
Zoom Slider

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#636]
I noticed that with 4.4.3 the zoom slider  in the navbar does not show the modification of the zoom level when I click on the +or - button and even when using the slide itself.

It remains stuck on the defaultZoomLvl that I declared on the page.

https://www.tadini.it/photosphere/test/panorama_bregagno.htm

Thank You again for your great work.

**Comment by mistic100** [comment]
This was caused by a bug in uevent 2.1.0 I released yesterday. I just published 2.1.1 which fixes the issue.

As always you will have to wait a few hours for jsdelivr CDN to propagate the new version.
