### ISSUE TITLE
Tour configuration

### ISSUE THREAD

**Issue by AdamMiltonBarker** [mistic100/Photo-Sphere-Viewer#637]
Hi great project! I am working on implementing tours into my system, I have a few questions that are not specifically mentioned in the documentation:

- For node position (GPS) what is the third value, I know 1 and 2 are lat and long, is value 3 the zoom or something?
-  Is node position what determines where the arrow is located ?
- How can we determine the coordinates of the location we want to use for the node, is there a way to get the coordinates from the sphere?

I think that is all the questions for now :) Thanks in advance.

**Comment by mistic100** [comment]
>     * For node position (GPS) what is the third value, I know 1 and 2 are lat and long, is value 3 the zoom or something?

https://photo-sphere-viewer.js.org/plugins/plugin-virtual-tour.html#position-required-in-gps-mode  
however the altitude is only relevant when using markers links, as arrows are always displayed on the same plane


>     * Is node position what determines where the arrow is located ?

yes

>     * How can we determine the coordinates of the location we want to use for the node, is there a way to get the coordinates from the sphere?

that's up to you, the system is flexible, you can give a single pre-configured JSON object containing all nodes, are have a HTTP server responds to `getNode` and `getLinks`

**Comment by AdamMiltonBarker** [comment]
> > For node position (GPS) what is the third value, I know 1 and 2 are lat and long, is value 3 the zoom or something?
> 
> https://photo-sphere-viewer.js.org/plugins/plugin-virtual-tour.html#position-required-in-gps-mode however the altitude is only relevant when using markers links, as arrows are always displayed on the same plane
> 
> > Is node position what determines where the arrow is located ?
> 
> yes
> 
> > How can we determine the coordinates of the location we want to use for the node, is there a way to get the coordinates from the sphere?
> 
> that's up to you, the system is flexible, you can give a single pre-configured JSON object containing all nodes, or have a HTTP server responds to `getNode` and `getLinks`

Thanks for the reply, ok so the third value is altitude (Wasn't provided in the docs, I have read the link you gave me) 

For the last question, I wasn't meaning what you thought I meant :) I was meaning, how do you actually find the coordinates, so I have a 360, I want to connect it to another, but I do not know how to calculate the coordinates. 

Hope that explains a bit better and thanks again for the help, and the quick reply.

**Comment by mistic100** [comment]
> Thanks for the reply, ok so the third value is altitude (Wasn't provided in the docs, I have read the link you gave me)

Excuse me what ? it clearly says in the doc `[longitude, latitude, altitude]`

> For the last question, I wasn't meaning what you thought I meant :) I was meaning, how do you actually find the coordinates, so I have a 360, I want to connect it to another, but I do not know how to calculate the coordinates.

That's also up to you, that's not something you calculate but you know, either be having a GPS module on your camera, or finding aproximate coordinates on Google Earth (that's what I did for the demo virtual tour)

**Comment by AdamMiltonBarker** [comment]
> [longitude, latitude, altitude]

Yer you are right, sorry I looked at link position which did not. Missed that. 

Ok a bit confused, I have seen you saying a number of times while reading through issues that the GPS coordinates are not real world, they are local, or maybe I got mixed up with you talking about manual.

I think you are right as my plan is that there will be an admin system where the user clicks to set the coordinates, possibly manual will be better for this.

Thanks I understood about manual.

Cheers for the help will come back to this issue later.

**Comment by mistic100** [comment]
Totally right, when you see a property named `longitude` and `latitude` those are not global coordinates, for the virtual tour plugin this is called `manual` positionning mode.

Byt the virtual tour plugin also supports actual GPS through the `position` property.

This example has both modes https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/example/plugin-virtual-tour.html

**Comment by AdamMiltonBarker** [comment]
Ok thanks got it, thanks for explaining. Still struggling a bit with the position even in manual, same question, is there a good way to find the pixel coordinates in a given image?

**Comment by mistic100** [comment]
Huh ? For pixels coordinates use your favourite image editor.

Or create a viewer with a 'click' event handler, it will give you all the information about where you click.

Sent from MailDroid

-----Original Message-----

**Comment by AdamMiltonBarker** [comment]
The pixel coordinates I was giving it were not giving me the expected outcome, so I figured there was maybe some additional processing done. I will keep working on it and let you know. Cheers/

**Comment by AdamMiltonBarker** [comment]
@mistic100 ok cool got it, I know how to build the system now, thanks for you help mate.

**Comment by AdamMiltonBarker** [comment]
Sorry :) Ok it is not working well. I got it working for one image but others will not. For example:

The dot in the center of the circle is where I want the arrow to be pointing direct.

![issue](https://user-images.githubusercontent.com/6291410/151891001-59985741-87f7-420a-b9f5-938233179601.jpg)

The coordinates are: 

`
{
   nodeId: '1',
   x: 220,
   y: 1203
 }`

This should point back to the first node, however it does not, what I get, no matter where I set the coordinates in that area is:

![issue2](https://user-images.githubusercontent.com/6291410/151891173-881af5f4-3fa5-4288-b2e3-557b92141287.jpg)

When I click the arrow it moves the view round to somewhere over the other side of the beach, then it takes me back to node 1, but it is not facing the correct way. When I manually click the thumbnail, it is alligned as expected.

**Comment by AdamMiltonBarker** [comment]
Full code, completely wrong to what it has been told to do

`virtualTour.setNodes([
                            {
                                id      : '1',
                                panorama: '/portfolio/assets/360/<?=$project['360']; ?>',
                                thumbnail: 'https://photo-sphere-viewer-data.netlify.app/assets/tour/key-biscayne-1-thumb.jpg',
                                name    : '<?=$project['360_title']; ?>',
                                links   : [
                                    {
                                        nodeId: '2',
                                        x: 3197,
                                        y: 1118
                                    },
                                ],
                                panoData: { poseHeading: 10 },
                            },
                            {
                                id      : '2',
                                panorama: '/portfolio/assets/360/porth-eilian-llaneilian-anglesey-360.jpg',
                                thumbnail: 'https://photo-sphere-viewer-data.netlify.app/assets/tour/key-biscayne-2-thumb.jpg',
                                name    : 'Porth Eilian, Llaneilian, Anglesey',
                                links   : [
                                    {
                                        nodeId: '1',
                                        x: 92,
                                        y: 1292
                                    }],
                                panoData: {
                                    poseHeading: -60,
                                    posePitch: 0,
                                    poseRoll: 0

                                },
                            }], '1');`

**Comment by AdamMiltonBarker** [comment]
Final example, 1 is where I collected the coordinates in photoshop, 21 is where it is pointing, no matter where I get the coordinates for that bottom left section it points to pretty much the same locatio
![porth-eilian-llaneilian-anglesey-360](https://user-images.githubusercontent.com/6291410/151892541-77052838-90bf-448e-8462-ed78e957fb0c.jpg)
n

**Comment by mistic100** [comment]
It is impossible to understand what you want without a live example.

But what I am sure of is that you are overthinking it. There is no intelligence in this system, you are just placing markers on the image, and clicking this marker will load another image. For example If the the next image does not have the same orientation, the result will be unexpected (that's why I used sphereCorrection on each node of the demo to correct the orientation)

**Comment by AdamMiltonBarker** [comment]
I want the arrow to point the way it is told to point, no matter where I put the coordinates in that image it points to the location of 2. The image with the arrow two images above, that is the location of the arrow no matter what coordinate used,it should be faing up the road from the beech.

**Comment by mistic100** [comment]
Okay but i cannot answer without a live example.

**Comment by AdamMiltonBarker** [comment]
https://www.angleseydrones.co.uk/portfolio/360-tours-portfolio-anglesey-north-wales/entry/360-tour-llaneilian

**Comment by mistic100** [comment]
I ain't really helping me helping you here.... How am I supposed to find the viewer declaration in your codebase to understand the issue ?

I will quote the template issue you should have seen from the start :

> Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

thank you

**Comment by AdamMiltonBarker** [comment]
That is the live example, right click and view source ?

**Comment by AdamMiltonBarker** [comment]
Full source, not sure what else you would need:

```

                        <script>
                            var viewer = new PhotoSphereViewer.Viewer({
                            container: 'photosphere',
                            loadingImg: 'https://photo-sphere-viewer.js.org/assets/photosphere-logo.gif',
                            touchmoveTwoFingers: true,
                            mousewheelCtrlKey: true,
                            caption    : '<?=$project['360_title']; ?>',
                            defaultLong: '100deg',
                            plugins    : [
                                [PhotoSphereViewer.MarkersPlugin, {
                                    hideButton: false,
                                listButton: false,
                                }],
                                [PhotoSphereViewer.VirtualTourPlugin, {
                                positionMode: PhotoSphereViewer.VirtualTourPlugin.MODE_MANUAL,
                                renderMode  : PhotoSphereViewer.VirtualTourPlugin.MODE_3D,
                                }],
                            ],
                            });

                            var virtualTour = viewer.getPlugin(PhotoSphereViewer.VirtualTourPlugin);

                            virtualTour.setNodes([
                            {
                                id      : '1',
                                panorama: '/portfolio/assets/360/<?=$project['360']; ?>',
                                thumbnail: 'https://photo-sphere-viewer-data.netlify.app/assets/tour/key-biscayne-1-thumb.jpg',
                                name    : '<?=$project['360_title']; ?>',
                                links   : [
                                    {
                                        nodeId: '2',
                                        x: 3197,
                                        y: 1118
                                    },
                                ],
                                panoData: { poseHeading: 10 },
                            },
                            {
                                id      : '2',
                                panorama: '/portfolio/assets/360/porth-eilian-llaneilian-anglesey-360.jpg',
                                thumbnail: 'https://photo-sphere-viewer-data.netlify.app/assets/tour/key-biscayne-2-thumb.jpg',
                                name    : 'Porth Eilian, Llaneilian, Anglesey',
                                links   : [
                                    {
                                        nodeId: '1',
                                        x: 3911,
                                        y: 1008
                                    }],
                                panoData: {
                                    poseHeading: 285,
                                    posePitch: 0,
                                    poseRoll: 0

                                },
                            }], '1');
                        </script>

                        <?php

                            } else if($project['360']){
                        ?>

                        <div id="viewer" style="width: 100%; height: 700px;"></div>
                        <script src="https://cdn.jsdelivr.net/npm/three/build/three.min.js"></script>
                        <script src="https://cdn.jsdelivr.net/npm/uevent@2/browser.min.js"></script>
                        <script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.js"></script>
                        <script>
                            var viewer = new PhotoSphereViewer.Viewer({
                                container: document.querySelector('#viewer'),
                                panorama: '/portfolio/assets/360/<?=$project['360']; ?>',
                                caption: '<?=$project['360_title']; ?>'
                            });
                        </script>
```

**Comment by mistic100** [comment]
> That is the live example, right click and view source ?

Sure.... you cannot expect me to dig through you whole app source code to find where is the viewer.  
Here is some reading when asking for help on Open Source projects https://stackoverflow.com/help/minimal-reproducible-example

---

Now the problem seems to be that the `panoData` is not taken into account when converting texture coordinates to local coordinates. I'll what can be done.

**Comment by AdamMiltonBarker** [comment]
@mistic100 I have added it here https://jsfiddle.net/2b7dc39q/2/ for some reason it is not working.

**Comment by AdamMiltonBarker** [comment]
> > That is the live example, right click and view source ?
> 
> Sure.... you cannot expect me to dig through you whole app source code to find where is the viewer. Here is some reading when asking for help on Open Source projects https://stackoverflow.com/help/minimal-reproducible-example
> 
> Now the problem seems to be that the `panoData` is not taken into account when converting texture coordinates to local coordinates. I'll what can be done.
> 
> https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/services/DataHelper.js#L85

I didn't expect that, a simple ctrl f would take you straight to the code.  I deleted the code and added it to jsfiddle.

**Comment by mistic100** [comment]
> @mistic100 I have added it here https://jsfiddle.net/2b7dc39q/2/ for some reason it is not working.

That's because your server does not allow cross origin requests to fetch the image.

----

Tha core issue was solved https://github.com/mistic100/Photo-Sphere-Viewer/commit/b5776ce2258870a7a6254da2c64c11411bd5ff48  
It stills need some more testing

**Comment by AdamMiltonBarker** [comment]
@mistic100 glad I was able to help find something. Do you know roughly when it will be live ? Will I need to change the links for the JS etc ?

**Comment by mistic100** [comment]
> Do you know roughly when it will be live ? 

no

> Will I need to change the links for the JS etc ?

If you use use jsdelivr targeting "4" it will be automatic

**Comment by AdamMiltonBarker** [comment]
Ok cool yes, I do. Please let me know once live, have to get this project finished. Thanks for the help and fixing it quick.

**Comment by AdamMiltonBarker** [comment]
@mistic100 does this bug fix fix the issue of the arrow pointing in completely the wrong direction ?  The third image of the lighthouse, the arrow should be pointing back towards the beach, again it is completely off and it doesn't matter how many times I change the coordinates it always points in the same direction.

https://www.angleseydrones.co.uk/portfolio/360-tours-portfolio-anglesey-north-wales/entry/360-tour-llaneilian

**Comment by AdamMiltonBarker** [comment]
Hi @mistic100 I see the issue has been closed but the problem still exists.

**Comment by mistic100** [comment]
Wait for a release please

**Comment by AdamMiltonBarker** [comment]
@mistic100 ok, not sure if you are aware but it is completely broken now:

https://www.angleseydrones.co.uk/portfolio/360-tours-portfolio-anglesey-north-wales/entry/360-tour-llaneilian

**Comment by mistic100** [comment]
Unfortunately jsdelivr takes time to propagate versions, it does not update each file at the same time  
you can see this one is 4.5.0 https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.js but this one is 4.4.3 https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/plugins/virtual-tour.min.js

There is nothing I can do about that, just wait.

In production environnement you should fix your versions (at least to the patch, that means using "@4.5" instead of "@4")

**Comment by mistic100** [comment]
Usually I close the [milestone](https://github.com/mistic100/Photo-Sphere-Viewer/milestone/30) only when I checked the CDN is up to date. Today it is very slow, I published 6 jours ago and it still not finished.
