### ISSUE TITLE
VirtualTourPlugin issue ? Multiple exceptions "side is undefined" thrown

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#639]
Hi,

Still working on my project, and got repeatedly firing exceptions for an unknown reason.

## Environment

- Browser : Firefox 91, Chromium 98
- OS : Arch Linux 64bits
- PSV 4.4.3 and 4.5.0, with VirtualTourPlugin enabled (Modes GPS, 3D, Server)

## How to reproduce

- Go to either https://jsfiddle.net/5qgjf1ps/ or https://files.pavie.info/clients/geovelo/
- Trigger a picture load (by clicking on tour arrows), and during picture load, move view using mouse

What is expected : picture loading is done without any errors

What happens : randomly (~75% of the time), errors span in bulk in browser console, always with same message :

```
Uncaught TypeError: can't access property "side", t is undefined
    y three.module.js:10889
    checkBufferGeometryIntersection three.module.js:10961
    value three.module.js:10823
    _intersectObject three.module.js:46476
    _intersectObject three.module.js:46486
    value three.module.js:46454
    getIntersection DataHelper.js:197
    __onMouseMove index.js:604
    handleEvent index.js:318
    init index.js:239
    trigger EventEmitter.js:156
    Viewer Viewer.js:282
    setTimeout handler*Viewer/< Viewer.js:279
    trigger EventEmitter.js:156
    render Renderer.js:224
    __renderLoop Renderer.js:211
    setTexture Renderer.js:239
    onAnimationFrame three.module.js:26511
    onAnimationFrame three.module.js:12365
    start three.module.js:12378
    setAnimationLoop three.module.js:26537
    setTexture Renderer.js:239
    loadingPromise Viewer.js:517
    promise callback*o/_e</n.setPanorama Viewer.js:515
    setCurrentNode index.js:438
    promise callback*o/_</r.setCurrentNode index.js:391
    value Viewer.js:156
    Viewer Viewer.js:63
    <anonymous> (index):27
three.module.js:10889:20
```

Once triggered, this error shows up like 95% of the time after a picture load. I'm not sure what exactly triggers it, but it's very frequent and seems to be linked to mouse over / move during picture load.

Best regards.

**Comment by mistic100** [comment]
To be honnest I don't know what can be done, it happens because the raycaster crashes when a scene object has no material, which is the case for a few milliseconds when switching panorama with the tiles adapter.

I could add a try/catch and just ignore everything...

**Comment by PanierAvide** [comment]
If that's a "normal" situation, adding a try/catch to ignore this seems reasonable. Currently, all exceptions thrown cause either performance issues (due to browser parsing source maps) or fullscreen warnings on a dev server.

**Comment by mistic100** [comment]
So that's was a wrong clue. The problem is the sphere Mesh has an incorrect array of materials, it should contains 2048 elements but it actually contains many empty spaces. I have no idea way, I doesn't happen everytime.

**Comment by mistic100** [comment]
An additional linked bug but easier to fix : if there is not "baseUrl" the error is thrown straigth from the beginning for each tile not yet loaded.

**Comment by mistic100** [comment]
Ok I found it : it is because of the preload feature of the virtual plugin, and the fact that the tiles adapter incorrectly clears the materials on texture load and not on texture application. I am even surprised the display is coherent and not a mix of multiple images...

**Comment by mistic100** [comment]
Hmm you don't have preload enabled on your demo... I certainly fixed some bugs but perhaps not everything.

**Comment by PanierAvide** [comment]
Well I didn't see the preload option, but I will definitely use it ! I tried activate it on the demo, but errors now are thrown directly at opening... Hosted here, but makes the browser laggy : https://files.pavie.info/clients/geovelo/preload/

**Comment by mistic100** [comment]
Yes that's fixed already I think.

I wonder what browser you use, personally if the dev console is not open the number of errors has no impact on performances.

-----

On a totally different topic I wonder what are the local laws in France regarding publishing photos with visible numberplates. Google Streets View blurs everything.

**Comment by PanierAvide** [comment]
OK great, thanks for your fix :grinning: 

Well numberplates and faces should not be visible, the pictures available on these dev instances are just here for testing, and will be removed when a real production instance (with correctly blurred pictures) will be deployed.

**Comment by mistic100** [comment]
Did further tests and it seems to work well.
