### ISSUE TITLE
Viewer gris lorsque intégré dans une popin

### ISSUE THREAD

**Issue by jerep6** [mistic100/Photo-Sphere-Viewer#64]
Bonjour,

Vu que tu es Français, je me permets d'écrire l'issue en français ;)

Je souhaite intégrer la visualisation des photos spheres à [angular-bootstrap-lightbox](http://compact.github.io/angular-bootstrap-lightbox/demo5/)
J'y suis parvenu mais lorsque la popin s'ouvre, le viewer de Photo-Sphere-Viewer reste gris. Il suffit d'un tout petit redimensionnement de la fenêtre pour que le contenu s'affiche. J'ai testé avec la version original de Jeremy Heleine et je n'ai pas ce problème.

Aurais-tu une idée ?
J'ai attaché [en pièce jointe](https://github.com/mistic100/Photo-Sphere-Viewer/files/405654/issue.zip) un exemple complet.

Question subsidiaire : comment arrives-tu à avoir une qualité de visualisation aussi belle comparé à la version de Jérémy ? 

Merci d'avance

**Comment by mistic100** [comment]
Bonjour,

j'ai vraiment pas la foi d'aller farfouiller dans votre version modifée de lightbox.

Je suppose que le viewer est initialisé trop tot, pendant que la lightbox est en cours d'ouverture.
Vous pouvez appeller manuellement la méthode `render` une fois que tout est bien terminé ou si ça ne marche pas `_onResize`

----

Je n'ai pas utilisé la version de Jérémy depuis la création du fork, je ne sais pas en quoi c'est mieux. En vrac des modifications potentielles : la sphere n'a pas la même taille dans le contexte WebGL, la sphere est constituée de plus de triangles, la texture est chargée avec des paramètres différents (qui viennent d'un autre contributeur).

**Comment by jerep6** [comment]
Merci pour la réponse. Le viewer était en effet initialisé un peu tôt.
