### ISSUE TITLE
Marker tooltip on mobile

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#640]
Hi, and thank you again for your great work.

I noticed a possible issue with marker's tooltip on mobile, that does not appear when I am single tapping on the marker. (like mouse over on desktop)

Xiaomi MI 11 with android 11

https://www.tadini.it/test/panorama_suretta.htm

double tapping on marker opens correctly the other pano.

Thank You.

**Comment by mistic100** [comment]
Tooltips are shown on mouse over, and there is no mouse over on touch screens.

Making them showing on any other interaction could interfer with event handlers  users may have added.

You can add event handlers yourself, the "click" event has a rightclick flag corresponding to longtouches for example.

Or always display all ttooltips: ​markers​.​toggleAllTooltips​(​)​;
