### ISSUE TITLE
[VirtualTour+Tiles] Inconsistent rendering if setCurrentNode is called too soon

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#642]
Hello again (sorry for opening too frequently issues :stuck_out_tongue_winking_eye: )

I'm trying to implement a sequence player buttons in navbar (custom buttons system is really convenient to use by the way :+1: ), and I have an issue on rendering when VirtualTourPlugin's `setCurrentNode` function is called during last panorama tiles loading / rendering. 

## Environment

- Browser : Firefox 97, Chromium 98
- OS : Manjaro Linux 21
- PSV 4.5.1, with VirtualTourPlugin enabled (Modes GPS, 3D, Server)

## How to reproduce

- Go to https://files.pavie.info/clients/geovelo/
- Wait for first picture to load, then double or triple click on next image button in navbar (right arrow next to play button)

What is expected : last loaded picture is still visible while low-res picture is loading, then low-res pic is visible while tiles are loading

What happens : until tiles completely loads, we have this broken kind of rendering
![Capture d’écran 2022-02-18 à 10 38 53-fullpage](https://user-images.githubusercontent.com/1349014/154657231-800dc58d-a4d4-4c60-8917-afaecd649dbd.png)
![Capture d’écran 2022-02-18 à 10 39 04-fullpage](https://user-images.githubusercontent.com/1349014/154657243-8de048b7-1025-472b-bac2-08f5c536938e.png)

I managed to avoid this while clicking on "play" button by waiting the rendering queue of tiles adapter is empty. But this can't be avoided if user clicks on next picture button by himself several times. I guess there could be a way to avoid calling `setCurrentNode` until last picture fully renders, but maybe there can be some improvements on PSV side to avoid this ? Thanks again for your time and efforts spent on the library which is really helpful !

Best regards.

**Comment by mistic100** [comment]
Can you try with this version https://github.com/mistic100/Photo-Sphere-Viewer/tree/tiles-swap (you will have to build it) ?

I could reproduce once but not anymore, anyway I see where the problem could be.

Also this change is probably a good step toward #644

**Comment by PanierAvide** [comment]
Thanks for your quick fix, it works like a charm :grinning:  We still have a very rarely and randomly tile from previous picture showing up (~5% of the time, probably when server is long to respond), but rendering is less disturbing as it's not whole pano showing up in a tile.
