### ISSUE TITLE
[EquirectangularTilesAdapter] Transition and preload support

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#644]
Hello,

Currently, Equirectangular tiles adapter [doesn't support transition/preload](https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/adapters/equirectangular-tiles/index.js#L90). To have a faster and smoother transition when combined with Virtual Tour Plugin, would it be complex to add this support ? Is there any technical issues that could block implementing this ?

Best regards.

**Comment by mistic100** [comment]
Would you mind testing this ? :)  
https://github.com/mistic100/Photo-Sphere-Viewer/tree/tiles-preload

**Comment by PanierAvide** [comment]
Thanks for this work, I will test it tomorrow and send you feedback

**Comment by PanierAvide** [comment]
Tested and this is really nice :+1: 

There are some glitches (vertical stripes of two different images) when you go programmatically to next node several times in a row (while previously called pano isn't fully loaded yet), but only visible for like 1/4 of second.

**Comment by mistic100** [comment]
I cannot replicate what you describe, do you have an example ?

**Comment by PanierAvide** [comment]
Updated demo app here : https://files.pavie.info/clients/geovelo/

If you click on button to go to next pano while previous is loading, these vertical strips appears randomly.

**Comment by mistic100** [comment]
It's a mystery. I do see the stripes on your example but not in local.  
I even tried with your own photos but no luck.

I also checked your source code on framasoft and there is so little code I don't think the problem is caused by your config.

**Comment by PanierAvide** [comment]
I have no clue of how your implementation works, but could it be some sort of ThreeJS glitch because two different spheres are overlapping at a certain time and at same position ? Could having a minor size difference between both spheres avoid this behavior ? (Sorry if this makes no sense)

**Comment by mistic100** [comment]
There is already a size difference, the onloading sphere is half the size of the base one.

Sent from MailDroid

-----Original Message-----

**Comment by mistic100** [comment]
I think it has to do with a missing cleanup of the scene when interrupting the transition, hence actually having two spheres of the same size at the same time.

Quickly tried to fix it but my promise-like Animation helper is flawed and chaining does not work as expected...

**Comment by mistic100** [comment]
@PanierAvide I updated the branch, can you give it another try ?

**Comment by mistic100** [comment]
On a different topic, I worked on less ugly arrows

![arrows](https://user-images.githubusercontent.com/41597/156647521-fb93fd7f-a73a-4d50-a702-0e49f0f82746.PNG)

**Comment by PanierAvide** [comment]
Thanks for your update, updated the demo here : https://files.pavie.info/clients/geovelo/

Rendering is now perfect, no more glitches even when calling next panorama while previous loads. However, with this version you can experience "back to n-2" situations when you loads successively two panoramas while the current one is loaded in SD but tiles not loaded yet. Also, there are some "Panorama can't be loaded" error showing over viewer, accompanied by these exceptions in console :

```
TypeError: r.psv is undefined
    o Viewer.js:518
    promise callback*o/n.setPanorama Viewer.js:514
    x index.js:439
    promise callback*o/r.setCurrentNode index.js:399
    value Viewer.js:192
    value Viewer.js:273
    value NextButton.js:26
    E AbstractButton.js:85
    AbstractButton AbstractButton.js:83
    _createSuper Babel
    NextButton NextButton.js:17
    setButtons Navbar.js:111
    setButtons Navbar.js:106
    Viewer Viewer.js:261
    _createSuper Babel
    Viewer Viewer.js:31
    <anonymous> (index):27
Viewer.js:500:8
    done Viewer.js:500
    (Asynchrone : promise callback)
    setPanorama Viewer.js:542
    x index.js:439
    (Asynchrone : promise callback)
    setCurrentNode index.js:399
    value Viewer.js:192
    value Viewer.js:273
    value NextButton.js:26
    E AbstractButton.js:85
    (Asynchrone : EventListener.handleEvent)
    AbstractButton AbstractButton.js:83
    _createSuper Babel
    NextButton NextButton.js:17
    setButtons Navbar.js:111
    setButtons Navbar.js:106
    Viewer Viewer.js:261
    _createSuper Babel
    Viewer Viewer.js:31
    <anonyme> (index):27


Uncaught (in promise) TypeError: r.psv is undefined
    o Viewer.js:518
    promise callback*o/n.setPanorama Viewer.js:514
    x index.js:439
    promise callback*o/r.setCurrentNode index.js:399
    value Viewer.js:192
    value Viewer.js:273
    value NextButton.js:26
    E AbstractButton.js:85
    AbstractButton AbstractButton.js:83
    _createSuper Babel
    NextButton NextButton.js:17
    setButtons Navbar.js:111
    setButtons Navbar.js:106
    Viewer Viewer.js:261
    _createSuper Babel
    Viewer Viewer.js:31
    <anonymous> (index):27
Viewer.js:518:10
    x index.js:501
    (Asynchrone : promise callback)
    setCurrentNode index.js:399
    value Viewer.js:192
    value Viewer.js:273
    value NextButton.js:26
    E AbstractButton.js:85
    (Asynchrone : EventListener.handleEvent)
    AbstractButton AbstractButton.js:83
    construct self-hosted:2741
    _createSuper Babel
    NextButton NextButton.js:17
    setButtons Navbar.js:111
    forEach self-hosted:208
    setButtons Navbar.js:106
    Viewer Viewer.js:261
    construct self-hosted:2741
    _createSuper Babel
    Viewer Viewer.js:31
    <anonyme> (index):27

```

On arrows, the new ones looks great :+1: An user feedback I had recently is that these arrows are kind of too high in picture and can sometimes block vision. We use the Mapillary viewer as reference, and arrows feel way more in the bottom, example https://www.mapillary.com/app/?panos=true&lat=48.204233525294&lng=-1.7361975835611&z=17.344137950295472&pKey=756253131753181&focus=photo&x=0.22460974901520947&y=0.471539530307376&zoom=0

![Capture d’écran 2022-03-04 à 10 39 31](https://user-images.githubusercontent.com/1349014/156738833-70d2a439-5afd-41a9-a0a2-87a7fb402373.png)

**Comment by mistic100** [comment]
This error is just a bad copy-paste between components. Fixed.

As for the arrows I lowered them a bit. Its rather difficult to configure correclty because the arrows are in the main THREE scene, when, I guess, Mapillary and other use an overlay not subject to zoom.
