### ISSUE TITLE
Improved link arrow

### ISSUE THREAD

**Issue by AdamMiltonBarker** [mistic100/Photo-Sphere-Viewer#646]
Hi mate. Is it possible to modify the arrow image used in the links? Also is it possible to place the links on the floor or on a wall as in the example provided for Kuula, I have not been able to find this info in the documentation and assume it is not yet possible, Maybe wrong?

https://kuula.co/share/NqTY1/collection/7qlkm

**Comment by mistic100** [comment]
Changing the image is possible with markers rendering, it is documented in the virtual tour plugin page.

Changing the orientation is not possible, it would require 3d information.

Sent from MailDroid

-----Original Message-----
From: AdamMiltonBarker ***@***.***>
To: mistic100/Photo-Sphere-Viewer ***@***.***>
Cc: Subscribed ***@***.***>
Sent: mer., 02 mars 2022 6:39
Subject: [mistic100/Photo-Sphere-Viewer] Improved link arrow (Issue #646)

Hi mate. Is it possible to modify the image used in the link? Also is it possible to place the links on the floor or on a wall as in the example provided for Kuula, I have not been able to find this info in the documentation and assume it is not yet possible, Maybe wrong?

https://kuula.co/share/NqTY1/collection/7qlkm

-- 
Reply to this email directly or view it on GitHub:
https://github.com/mistic100/Photo-Sphere-Viewer/issues/646

**Comment by mistic100** [comment]
Actually you could achieve something like this with an "imageLayer" marker, but it won't be automatic, you will need to find tune the position of each marker and have different images for each orientations

**Comment by AdamMiltonBarker** [comment]
@mistic100  do you have an example of using the markers plugin for the links, or have I missed it ?

**Comment by AdamMiltonBarker** [comment]
OK thanks will check it out, last one sorry, people have been saying on mobile that the images are too zoomed in, I can't seem to find a zoom configuration, although I am guessing I have missed it :D

**Comment by mistic100** [comment]
perhaps use the search (of the site or of your browser)

https://photo-sphere-viewer.js.org/guide/config.html#minfov  
https://photo-sphere-viewer.js.org/guide/config.html#defaultzoomlvl

**Comment by AdamMiltonBarker** [comment]
Ok thank you for pointing me in the right direction, once I get this done will send you the link so you can see your hard work in action :)

**Comment by mistic100** [comment]
I am currently woking on the "imageLayer" markers to be able to declare the orientation.

Example of a perfectly round image which is oriented.
![imageLayer-marker](https://user-images.githubusercontent.com/41597/156562430-8dde238a-2f60-4121-a026-69e5409d0588.png)

**Comment by AdamMiltonBarker** [comment]
Honestly mate the whole thing is great, but making that change above will massively improve it, a lot, that will be a great feature mate! I am having issues with tours its just not flowing right and when you have multiple arrows, the orientation navigating around is a bit weird, I will add more info after but its my birthday today so not doing much, I feel with a few improvements this library will be unbeatable!
