### ISSUE TITLE
Idle autorotate

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#647]
Currently the autorotate starts automatically after init if no user interraction happens before `autorotateDelay`.

Once the autorotate is stopped, it never starts again automatically. It would be interresting to restart after and idle time.

Must be cautious on the implementation to not mess up with the gyro plugin.

On a side note `autorotateDelay=0` does not work if we want to start immediately, the minimum is 1 millisecond.

**Comment by haldo98** [comment]
Hi... I noticed that with newer versions a click on the panorama stops again the rotation.   like I asked in #629 

Thanl You for your great work. Works perfect for me.
