### ISSUE TITLE
Wireframe shown when webgl is not supported

### ISSUE THREAD

**Issue by Sheep-y** [mistic100/Photo-Sphere-Viewer#65]
## Problem
When webgl is not supported by the browser, three.js will fall back to canvas renderer.
This would cause the display of [wireframe](https://github.com/mrdoob/three.js/issues/1044). [Screenshot](https://cloud.githubusercontent.com/assets/4466495/17506459/95690eda-5e3b-11e6-8395-a7c508980ea2.jpg).

## Reproduce
Navigate the [doc/demo site](http://photo-sphere-viewer.js.org/) by either:
* Using Firefox, goto "about:config" and set "webgl.disabled" to true.
* Use a virtual machine without gfx acceleration (usually configurable in VM hardware settings)

Tested Firefox 48 and Chrome 52.

## Fix
[Patch diff](https://github.com/mistic100/Photo-Sphere-Viewer/files/408323/diff-Fix-wireframe-on-CanvasRenderer.zip).

**Comment by mistic100** [comment]
Thank you so much, don't know how I didn't find the solution...
