### ISSUE TITLE
virtual tour showing large icons 

### ISSUE THREAD

**Issue by RAHULBAWA777** [mistic100/Photo-Sphere-Viewer#652]
i am using the latest version using cdn links for virtual tour ... but on running the program the virtual tour canvas is appearing small and all the navbar icons are enlarged .....
![Screenshot (265)](https://user-images.githubusercontent.com/91609324/158743848-f087945b-bcc0-447b-a4f9-478524e18503.png)

**Comment by mistic100** [comment]
you are missing on or more CSS files, there is one main file and one for the plugin, check the documentation.

**Comment by RAHULBAWA777** [comment]
Yes I've used both the css cdn links... One main cdn link and other two are
for markers and virtual tour

**Comment by RAHULBAWA777** [comment]
Can you please send me a link of a demo vitual tour made by you using
photosphere veiwer please..... I'll tally the code and will figure out the
mistake that's causing the error.... Please just make a simple tour in your
vs code and send the link after hosting it.... Please

**Comment by RAHULBAWA777** [comment]
Or just the GitHub code I mean... Of course why would you host it... I'll
run the code using live server

**Comment by mistic100** [comment]
There is already a demo jsfiddle on the plugin page, here is the direct link https://jsfiddle.net/mistic100/y0svuLpt/

and there is the examples folder https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/example/plugin-virtual-tour.html

**Comment by RAHULBAWA777** [comment]
I know but the demo that they have shown is not the complete code.... It's
just the main code.... They have not mentioned all the cdn links and the
code is not show  from scratch which makes it difficult to tally my code
with the demo code.

**Comment by RAHULBAWA777** [comment]
Okay I've got it thanks  mate

**Comment by mistic100** [comment]
Just click on "Ressources" to see the JS and CSS files
![jsfiddle](https://user-images.githubusercontent.com/41597/158800271-7b5e99ba-80f2-468a-bea4-f969c95cbd28.PNG)

**Comment by RAHULBAWA777** [comment]
Got it, thanks!
