### ISSUE TITLE
Import Markers and Virtual tour on Typescript / Es Import

### ISSUE THREAD

**Issue by DrMkcTheHandSome** [mistic100/Photo-Sphere-Viewer#653]
Import Markers and Virtual tour on Typescript / Es Import

I'm having hard time implementing the markers and virtual on typescript. Here is the code snippet::

![image](https://user-images.githubusercontent.com/44965214/159283897-09194730-7c2c-4c47-9d79-1289c680a055.png)
![image](https://user-images.githubusercontent.com/44965214/159283925-8f86ff9f-ef54-47e2-8af0-9da941668422.png)

**Comment by DrMkcTheHandSome** [comment]
Error when hovered:

![image](https://user-images.githubusercontent.com/44965214/159291444-b3b1064a-a358-4e50-837e-1ad66d317dda.png)

**Comment by DrMkcTheHandSome** [comment]
I mean, I cannot import either marker or virtual on my typescript application (es import) do you any code snippet that I could check out?

**Comment by DrMkcTheHandSome** [comment]
The remaining error I encounter is this one. I hope you could help me with this one. Thanks a lot. @mistic100 

![image](https://user-images.githubusercontent.com/44965214/159414670-a742f657-901f-41a8-bf4f-3b2e961b39d4.png)

**Comment by mistic100** [comment]
import { MODE_3D } from "photo-sphere-viewer/dist/plugins/virtual-tour";

You know if you control+click on the plugin import, your IDE will tell you what are the exported members.

**Comment by DrMkcTheHandSome** [comment]
Thanks for the tip it helps a lot.
