### ISSUE TITLE
Cannot import MODE_3D, MODE_GPS

### ISSUE THREAD

**Issue by DrMkcTheHandSome** [mistic100/Photo-Sphere-Viewer#655]
Hi mate,

I tried the last comment you said to control + click the link to know what I can import on virtual tour.d.ts both MODE_3d and MODE_GPS does not exist in virtual-tour.d.ts.

![image](https://user-images.githubusercontent.com/44965214/159482072-5a20c508-6176-4dae-9db6-e167ae0ad27d.png)

I tried to global search it which I can't find still which file should I source the import.

![image](https://user-images.githubusercontent.com/44965214/159482165-9a0498c1-18e9-4499-87a0-82ced17d9a76.png)

I hope you could help on this. Thanks a lot mate.

**Comment by mistic100** [comment]
I also modified the exports so you can use any of these syntaxes :

A.
```ts
import { VirtualTourPlugin, MODE_3D } from 'photo-sphere-viewer/dist/plugins/virtual-tour';

...
plugins: [
  [VirtualTourPlugin, {
    renderMode: MODE_3D,
  }],
],
```
B.
```ts
import { VirtualTourPlugin } from 'photo-sphere-viewer/dist/plugins/virtual-tour';

...
plugins: [
  [VirtualTourPlugin, {
    renderMode: VirtualTourPlugin.MODE_3D,
  }],
],
```

it should ease the transition from the demos to ES imports

**Comment by DrMkcTheHandSome** [comment]
How to pull your changes on git/npm?
