### ISSUE TITLE
THREE.Quaternion is not a constructor

### ISSUE THREAD

**Issue by ChanderShekharKestone** [mistic100/Photo-Sphere-Viewer#656]
## 
Hi i facing this error with latest version.
![image](https://user-images.githubusercontent.com/87749356/159529549-0bc9fbe2-455b-46b0-b37d-e239d875098e.png)

**Comment by mistic100** [comment]
which version of three.js ? do you have an online demo of the issue ?

**Comment by mistic100** [comment]
Anyway Quaternion has existed as long as three.js exists, so you must have an issue without your own setup.

**Comment by ChanderShekharKestone** [comment]
> which version of three.js ? do you have an online demo of the issue ?

I am using latest version attached screen shot and i don't have online demo.
Steps i used:
npx create-react-app
yarn add photo-sphere-viewer
yarn add three
yarn add uevent

4.4.3 is working, but i want imageLayer marker so i used latest.
And one question is there any option to add video like imageLayer, embedded into the THREE.js scene.

![image](https://user-images.githubusercontent.com/87749356/159637698-bf02bb42-3dd4-4207-b029-67b1bf6ba772.png)

**Comment by mistic100** [comment]
Please share a repo, I don't know React.

---

No imageLayers cannot contain a video

**Comment by Jodelopa** [comment]
hi, getting exactly the same error after upgrading to react-scripts 5 thas has stricter error checks.
the error messages indicates that the (default) constructor is not existing, i after a quick search only one with 4 arguments.

**Comment by mistic100** [comment]
if you want my help on this issue please provide a siple demo repository

**Comment by lord-xeon** [comment]
@mistic100 here's a sample repo that uses create-react-app that's giving myself and likely @Jodelopa the problem:

https://github.com/lord-xeon/_psv656

I put comments into `App.js` explaining the current issue.  As far as I can tell it's webpack related for how it's bundling the source.  I found this [open ticket on CRA's repo](https://github.com/facebook/create-react-app/issues/9991), but I haven't been able to get it working yet.  I've tried a few other `loaders` with webpack and still no luck.

The version of webpack I'm using (behind the scenes) is `5.64.x`

Let me know if you need any additional info from me.

**Comment by mistic100** [comment]
Importing from the source is not a solution. Event if you manage to setup webpack to handleall the SVG, SCSS and custom rollup setup I have, it will break as soon as I change something.

Now I have no idea what is going on, when I do `import * as THREE from 'three';` in the ap itself, three.js is resolved correctly. When done from the lib, THREE is equal to this string `/static/media/three.e4260f43945fc039f60b.cjs`.

It is definitely some weird webpack configuration done from react-scripts. From my point of view PSV is a standard UMD library and is doing nothing wrong  
https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/dist/photo-sphere-viewer.js#L1-L12 (it is generated by rollup anyway).

Perhaps it as to do with the complex configuration of three.js itself https://github.com/mrdoob/three.js/blob/dev/package.json#L6-L16

I will close this issue I cannot do anything more. If you find a working configuration, feel free to open an issue or a PR to update the doc. Or better, propose a change, if necessary, directly to three.js

**Comment by huedaya** [comment]
Experiencing the same error, but I am unable to recreate it on StackBlitz, maybe it's something wrong with TypeScript? :thinking: 

https://stackblitz.com/edit/react-ts-uthswx?file=package.json

**Comment by huedaya** [comment]
Still facing the same problem, but unable to recreate it on StackBlitz but here is the exact code that shows those error 

- https://github.com/huedaya/psv-react-test
- https://stackblitz.com/edit/react-vk7nx7?file=src%2FApp.js

![image](https://user-images.githubusercontent.com/4969689/167568746-1dc5918c-39af-47fd-8228-373b9f55c93e.png)

**Comment by Jodelopa** [comment]
cloned the repo and changed in rollup.config.js the output.format to 'es' from 'umd', seems fixed it for me.

**Comment by Jodelopa** [comment]
Investigated a bit further and seems that newer webpack versions can have a problem with circular dependencies in UMD modules.
used dpdm on the code and it detects 3 dependencies

```
Photo-Sphere-Viewer> dpdm --no-warning --no-tree src/index.js
✔ [49/49] Analyze done!
• Circular Dependencies
  1) src\utils\index.js -> src\utils\Dynamic.js
  2) src\utils\index.js -> src\utils\MultiDynamic.js
  3) src\buttons\DescriptionButton.js -> src\components\NavbarCaption.js
```
maybe this could help to solve the problem. 
unfotunately i dont have the time try this out in an non TS project

**Comment by mistic100** [comment]
@Jodelopa if using the bundle in "dist" this shouldn't not be a problem, yes there is a circular dependency but it is internal to the bundle

**Comment by Jodelopa** [comment]
The circular dependency was not the problem, indeed. 
Maybe consider to move away from UMD anyway.
