### ISSUE TITLE
How to pull your recent changes on npm package?

### ISSUE THREAD

**Issue by DrMkcTheHandSome** [mistic100/Photo-Sphere-Viewer#657]
I use npm to install your library, is there a way I could access the recent changes? I tried uninstalling and reinstalling it back but changes did not reflect.

**Comment by amipei** [comment]
You can download the source code, package it and use it locally

**Comment by mistic100** [comment]
> You can download the source code, package it and use it locally

This would required to setup your build chain to match my Rollup configuration, especially for SVG files and plugins dependency to the core.

TLDR : wait for a release
