### ISSUE TITLE
Gyroscope - Stereo Plugin

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#664]
https://www.tadini.it/test/ps_.htm

with my xiaomi mi 11 - android 12  - chrome browser    

I noticed some strange behaviour in this page where I have enabled gyroscope and stereo plugins

I read in the gyroscope plugin page that there are inconsistency in the orientation. But if I toggle on and off the gyroscope button without moving at all my phone the orientation change by itself. This happens when I toggle the gyroscope button ON.

here's a video of the issue. 
https://www.tadini.it/test/Screenrecorder.mp4

and also....   I managed to add the "stereo" button in the navbar... but when i turn my phone horizontally the button is not shown.

Thank You. Always great work. I love it.

**Comment by mistic100** [comment]
If you want the gyroscope to always pick the same starting point you will need the `absolutePosition` option https://photo-sphere-viewer.js.org/plugins/plugin-gyroscope.html#configuration

----

I'll check the stereo plugi later. There might be something wrong in the feature detection.

**Comment by haldo98** [comment]
Thank You... with absolutePosition: true   works perfectly. 

and also .......   with this configuration enabled the stereo button is now present.     Don't know if this is the supposed behaviour.

Thank You
