### ISSUE TITLE
Low resolution panorama not loading for Equiractangular tiles adapter in chrome

### ISSUE THREAD

**Issue by shamsul-onetobeam** [mistic100/Photo-Sphere-Viewer#668]
## Low-resolution panorama not loading for Equiractangular tiles adapter in chrome

- **photo-sphere-viewer: ^4.5.1**
- At the place of equirectangular tile , black tile is coming first instead of low-resolution panorama only in chrome mobile & desktop.

**Comment by mistic100** [comment]
> - Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.
