### ISSUE TITLE
Marker selection with gyroscope: true not working

### ISSUE THREAD

**Issue by upupupandaway** [mistic100/Photo-Sphere-Viewer#67]
I'm seeing an issue when gyroscope is enabled. Markers are no longer selectable; clicking on one does not load the content. Clicking the nav button to disable gyroscope allows the markers to work as expected.

**Comment by wwlxz22** [comment]
I want to add a tip on the sphere photo to describe the place or add a link to load a new picture .how can do it .

**Comment by Strae** [comment]
@wwlxz22 http://photo-sphere-viewer.js.org/markers.html

**Comment by wwlxz22** [comment]
@Strae I open the example/index.htm and it's blank,should I config some files?

**Comment by mistic100** [comment]
Run 'bower install'  in the root directory. But you are of topic ! Open a new issue.

**Comment by AlexandreDelan** [comment]
Hello,
I have the same issue.... 
Is there somebody working on it? is there a date for the 3.2.2 milestone?

Thank a lot for this great work :)
Alex

**Comment by mistic100** [comment]
Nope, no target date

**Comment by AlexandreDelan** [comment]
OK, I am going to have a look.
Thank you for your quick answer.

**Comment by AlexandreDelan** [comment]
Here is a correction. I can commit the correction :)
```
PhotoSphereViewer.prototype._stopMove = function(evt) {
  if (this.isGyroscopeEnabled()) {
    this._click(evt);
    return;
  }  
```

**Comment by mistic100** [comment]
that's a totally ugly hack, better find the source of the problem.

**Comment by AlexandreDelan** [comment]
lol...
please have a look at the complete function code.

In gyroscope mode, this function will never do this._click(evt);
And this is why the click event is not propagated.

`PhotoSphereViewer.prototype._stopMove = function(evt) {
  if (this.prop.moving) {
    // move threshold to trigger a click
    if (Math.abs(evt.clientX - this.prop.start_mouse_x) < PhotoSphereViewer.MOVE_THRESHOLD && Math.abs(evt.clientY - this.prop.start_mouse_y) < PhotoSphereViewer.MOVE_THRESHOLD) {
      this._click(evt);
      this.prop.moving = false;
    }
    // inertia animation
    else if (this.config.move_inertia) {
      this._logMouseMove(evt);
      this._stopMoveInertia(evt);
    }
    else {
      this.prop.moving = false;
    }
  }

  this.prop.mouse_history.length = 0;
  this.prop.zooming = false;
};`

**Comment by AlexandreDelan** [comment]
we can also fix it like this:
`PhotoSphereViewer.prototype._onMouseUp = function(evt) {
if (this.isGyroscopeEnabled()) {
   this._click(evt);
}
else
{
  this._stopMove(evt);
}

};
`

**Comment by mistic100** [comment]
Ok I didn't remember the click detection was reimplemented like this :-)

Your second solution won't work on touch screens, the first one is better.

(edited all your messages with valid Markdown...)
