### ISSUE TITLE
Navigation bar zoom button, move button, display problems in the mobile phone

### ISSUE THREAD

**Issue by Qs-cic** [mistic100/Photo-Sphere-Viewer#671]
The zoom button and move button in the navigation bar will not be displayed on the mobile terminal, or the zoom button and move button will disappear after you click the screen of the mobile phone with your finger. Do you have a good solution? Thank you very much.

**Comment by mistic100** [comment]
this is totally normal : those buttons are hidden because they take to much space and much less convenient that using you finger (or two to zoom)

as to why they disappear after touching the screen : this is the only reliable solution to know if the device actually supports touch events

**Comment by gleatherman** [comment]
is there a way to disable this feature or work around? i am using a touchscreen monitor but when the code recognizes the touchscreen it hides those buttons as well - i'd like them to remain so both options are available to the user

**Comment by mistic100** [comment]
It the latest versions, if you don't interact with your touchscreen on the viewer, the buttons will re-appear after the first mouse event. And the information is persisted in localstorage so it will only "glitch" the first time.

The full implementation is here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/data/system.js#L90-L129

I think this adaptative system is the best solution. I am not willing to add another option.
