### ISSUE TITLE
Support to IE11 seems to be broken

### ISSUE THREAD

**Issue by antoninmeunier** [mistic100/Photo-Sphere-Viewer#672]
Hello, 

I'm trying to make the viewer to run on IE11 on a vue APP but I've got an error in my chunk vendors, it looks like it's linked to ThreeJS and the keyword "class" which is not known by IE11 : 

![three](https://user-images.githubusercontent.com/61155194/164215993-404cd063-22cd-41ae-adb7-c23239b32d0c.png)

I'm using the last version of the viewer : 4.6.1.

Is IE11 still supported? If not which version should I take? I've looked the anterior ones (<4) but in the package.json, the Three JS version are referenced as ">= X" so it automatically get the last one with the same error.

Thanks for your help and thanks for this amazing viewer!

**Comment by mistic100** [comment]
IE11 is not supported nor from PSV since version 4.6.0 nor from Three.js since un unknown version (since they removed ES5 support).

If you really need it you will have to create yourself an ES5 bundle using babel.js and some polyfils.  
I will not provide support on this matter.
