### ISSUE TITLE
PSV v4.6.1 destroy problem

### ISSUE THREAD

**Issue by DanielePancottini** [mistic100/Photo-Sphere-Viewer#677]
Hi,
same problem of #658 but with VirtualTourPlugin, in addition the changes done by the commit 7909967b4ad50bc395412f258aeeab33d414afd6 aren't visible with the dist 4.6.1 I believe.

Thanks for support :)

**Comment by mistic100** [comment]
It cannot be the same problem if it is not the same plugin.

Please read the issue guidelines and to the necessary : error logs and reproduction of the issue

**Comment by mistic100** [comment]
Also the commit you linked **is** released https://github.com/mistic100/Photo-Sphere-Viewer/blob/4.6.1/dist/plugins/video.js#L843-L853
