### ISSUE TITLE
Can't make gyroscope work

### ISSUE THREAD

**Issue by archimedo** [mistic100/Photo-Sphere-Viewer#678]
Hi everyone,
I'm making a simple virtual tour website and it seems that your viewer is exactly what I need.
I've tried doing a very simple example where I wanted to show a 360pic and when on mobile move it around with gyroscope.

this is sample code I wrote:

```
<script src="https://cdn.jsdelivr.net/npm/three/build/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uevent@2/browser.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.css"/>
<script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/photo-sphere-viewer.min.js"></script>

<!-- the viewer container must have a defined size -->
<div id="viewer" style="width: 100vw; height: 100vh;"></div>

<script>
  const viewer = new PhotoSphereViewer.Viewer({
    container: document.querySelector('#viewer'),
    panorama: 'https://i.ibb.co/2dKWcHX/01881815-UTAH-SKI-360-2880-compressed-1024x512.jpg',
    gyroscope: true,
  });
</script>
```

The problem is that when I added the `gyroscope: true,` the viewer is not showing anymore. I read the documentation but I'm not sure to import the Gyroscope plugin. Can you help me figure out what I'm doing wrong?

Thank you!

**Comment by mistic100** [comment]
where did you see `gyroscope: true` ?  
this is not what is written in the documentation https://photo-sphere-viewer.js.org/plugins/plugin-gyroscope.html

you will need to import `https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4.6.1/dist/plugins/gyroscope.js`

**Comment by mistic100** [comment]
Did you open the developper console what facing the issue ? Most probably there is a clear error indicating that "gyroscope" is not a known option.

**Comment by archimedo** [comment]
Thank you very much for your reply and I'm sorry but I've probably messed a bit with the documentation and wrote the wrong thing. I've tried with importing ` https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4/dist/plugins/gyroscope.js` and modifying my code like this and it worked. 

`<script>
  const viewer = new PhotoSphereViewer.Viewer({
    container: document.querySelector('#viewer'),
    panorama: 'https://i.ibb.co/2dKWcHX/01881815-UTAH-SKI-360-2880-compressed-1024x512.jpg',
    plugins: [
      PhotoSphereViewer.GyroscopePlugin,
    ],
  });
</script>`

Now I can see the gyroscope button and when I press it I can navigate around the image with my phone, the thing is that I would like the panorama to be interactive by default.

Is there any way to enable the gyroscope (if available) by default as soon as the page loads?

Thank you!

**Comment by mistic100** [comment]
no the browsers don't allow to automatically enable the gyroscope

---

use three ` for code blocks

**Comment by archimedo** [comment]
Thanks, I fixed the code block.

Ok, so it can't be set by default but can I at least use a custom html button in my page, let's say ` <button type="button" id="mybutton">activate gyroscope</button> ` to trigger the gyroscope on click?

Many thanks for your help

**Comment by mistic100** [comment]
Yes, the API is documented here https://photo-sphere-viewer.js.org/api/psv.plugins.gyroscopeplugin

```js
viewer.getPlugin(PhotoSphereViewer.GyroscopePlugin).start();
```

**Comment by archimedo** [comment]
Oh, thanks I was doing it the wrong way! `viewer.plugin.GyroscopePlugin.start();`

The only thing is that when I'm on mobile and open my panorama I see a buttons bar that seems the one on desktop, then as soon as I touch the screen, the menu bar changes and it keeps only few buttons.

[this is how I see it when I first open the page](https://ibb.co/DMJ78gZ)

and [this is how I see after the first touch on the screen
](https://i.ibb.co/r4HmvPj/screen-2.jpg)

Can you help me understand why this happens?

**Comment by mistic100** [comment]
Created another issue for that https://github.com/mistic100/Photo-Sphere-Viewer/issues/679

**Comment by jywarren** [comment]
> no the browsers don't allow to automatically enable the gyroscope

I think this may no longer be true? I saw it activated by default at https://spano.pyrik.dev/

Love this library btw, ty!

**Comment by mistic100** [comment]
perhaps, you can try it yourself

```ts
viewer.addEventHandler('ready', () => {
  viewer.getPlugin('gyroscope').start();
}, { once: true });
```
