### ISSUE TITLE
rotate method not work

### ISSUE THREAD

**Issue by wzk319** [mistic100/Photo-Sphere-Viewer#68]
when i use the rotate method ,its not work ,the console output a error "TypeError: angle is undefined in 1518:3" my code is

```
 var ro = 1;
    setInterval(function(){
          PSV.rotate({
            longitude: (-10*ro)+"deg",
            latitude:  (-10*ro)+"deg"
        });
          ro++;
    },1000)
```

**Comment by mistic100** [comment]
Just tested on version 3.2.1 and it totally works, not error. So setup a live example if you really think there is a problem.

---

By I don't really understand what you are trying to achieve, jumping 10 degrees by 10 degrees is really ugly. The "time_anim", "anim_speed" and "anim_lat" options exist exactly for this. And there is also the "animate" function which is like "rotate" but smooth.

**Comment by wzk319** [comment]
but I'm not found the "animate" function in  "photo-sphere-Viewer.js"

**Comment by mistic100** [comment]
If you don't say which version you are using I can't help you.

And use the doc instead of exploring the code http://photo-sphere-viewer.js.org

**Comment by wzk319** [comment]
I ues the version is the 3.2.1

**Comment by mistic100** [comment]
Then the animate function is here https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/dist/photo-sphere-viewer.js#L1624

**Comment by wzk319** [comment]
ok

**Comment by wzk319** [comment]
Thanks ,the error had resolved
