### ISSUE TITLE
imageLayer different size on different displays.

### ISSUE THREAD

**Issue by amaze-escape** [mistic100/Photo-Sphere-Viewer#680]
## Technical Details

PSV version: 4.6.1
Browsers:
Linux: Chromium
Macbook: Chromium

## Description

The imageLayer is different in size on different screens/computers. I suspect that this is because of scaling on higher resolution screens. Unfortunately I could not fully test this as all our macs have high resolution screens and all our linux PC' s HD monitors. So technically it could be an OS thing as well.

## Code

```
{
                id: "fire",
                imageLayer: "/src/assets/panoramas/fire.png",
                anchor: "center center",
                orientation: "front",
                width: 50,
                height: 100,
                x: 4507,
                y: 4026,
                tooltip: "Fire Extuingisher",
                visible: true,
},
```

## Additional info

This example gives the same result: https://photo-sphere-viewer.js.org/plugins/plugin-markers.html#example
The yellow tent is roughly twice the size on our macs and is even touching the green line, while the tent is much smaller on the HD screens.

## Fire extinguisher example

![Screenshot 2022-05-11 14:13:43](https://user-images.githubusercontent.com/52074740/167864261-08af5c6a-ca35-43cf-b328-9ff7a5a5f14f.jpg)

**Comment by mistic100** [comment]
Can you try by removing the two `* photoSphereViewer.SYSTEM.pixelRatio` on this line
https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/dist/plugins/markers.js#L1068

**Comment by amaze-escape** [comment]
Thank you very much! That fixed it :D
Will this change be included in a future update or should we create a fork with this change?

**Comment by mistic100** [comment]
I'll change it for the next release.
