### ISSUE TITLE
iOS video plugin switching video to fullscreen mode on iPhone

### ISSUE THREAD

**Issue by schaplain** [mistic100/Photo-Sphere-Viewer#681]
Hi, 

I'm trying to use PSV 4.6.1 in an Angular App and I have an issue with video plugin. On iOS when you open a 360 video with autoplay or normal play button, the default behavior on iOS on iPhone is to open this video with native player in a fullscreen mode. 
You can test with going to your demo page with an iPhone and hit play button ==>  https://photo-sphere-viewer.js.org/plugins/plugin-video.html#example.

Solution is to add the "playsinline" attribute on the video tag that the plugin generates (https://developer.apple.com/documentation/webkitjs/htmlvideoelement/2528111-playsinline). The video will play inside the video element and not switch to fullscreen. 

For the moment, I add it into my project, but it should come with PSV as a standard behavior. 

Best, 
Stephane

**Comment by mistic100** [comment]
Thank you.

I'll trust you on that mater because I can't test :-)  
I had this parameter on an early version of the adapter my somehow removed it.

**Comment by schaplain** [comment]
OK. Thank you for taking this feedback in your roadmap.
