### ISSUE TITLE
Stopped working everywhere

### ISSUE THREAD

**Issue by kilavila** [mistic100/Photo-Sphere-Viewer#686]
The photo sphere viewer stopped working for me, even in the examples on your site.
Tested on multiple devices, will this be resolved soon or is there anything I can do to fix this my self?
Maybe another version or anything like that?

Thank you :)

**Comment by stevencsimpson** [comment]
Hi, I think this is because of the recent three.js version released yesterday. Looking at the Photo Sphere Viewer guide, where the three.min.js cdn script is, no version is specified so it just uses the most recent version. You can use three@0.140.2 and it should work. Hope this helps.

**Comment by Ross2609** [comment]
> Hi, I think this is because of the recent three.js version released yesterday. Looking at the Photo Sphere Viewer guide, where the three.min.js cdn script is, no version is specified so it just uses the most recent version. You can use three@0.140.2 and it should work. Hope this helps.

Thanks for offering your solution, Steven! Have you created an issue on their repo letting them know about this breaking change? I am sure they're aware but always nice to be helpful :)

**Comment by kilavila** [comment]
Thank you for providing a solution so fast!

**Comment by StevenEserv** [comment]
> > Hi, I think this is because of the recent three.js version released yesterday. Looking at the Photo Sphere Viewer guide, where the three.min.js cdn script is, no version is specified so it just uses the most recent version. You can use three@0.140.2 and it should work. Hope this helps.
> 
> Thanks for offering your solution, Steven! Have you created an issue on their repo letting them know about this breaking change? I am sure they're aware but always nice to be helpful :)

Hi Ross. I think that this issue 'Stopped working everywhere' probably covers it but there is also pull request to update the three js dependency that failed and subsequently notified/assigned the owner. Thank you though!

**Comment by stevencsimpson** [comment]
> > Hi, I think this is because of the recent three.js version released yesterday. Looking at the Photo Sphere Viewer guide, where the three.min.js cdn script is, no version is specified so it just uses the most recent version. You can use three@0.140.2 and it should work. Hope this helps.
> 
> Thanks for offering your solution, Steven! Have you created an issue on their repo letting them know about this breaking change? I am sure they're aware but always nice to be helpful :)

Hi Ross. I think this issue probably covers it, but there is also a failed pull request regarding the new three js version so this has notified the owner. Thank you though!
