### ISSUE TITLE
Question about video plugin and Markers

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#690]
<sup>Originally posted by **schaplain** June  8, 2022</sup>
Hi, 

I'm trying to setup a web app with PSV and 360 videos. I have to populate 360 view with image markers. 
I use addMarker function and provide coordinates x and y expressed in pixels.

```js
markersPlugin.addMarker({
            id: poi.id,
            x: poi.x * width, // Convert coordinates to pixels 
            y: poi.y * height, // X and Y are [0..1] coordinates of th poi on the texture
            width: 50,
            height: 50,
            anchor: 'center center',
            tooltip: { content: 'New Title', position: 'bottom center' },
            image: poi.image,
          });
```

This code works fine when 360 is an image (EquirectangularAdapter) but not when 360 is a video (VideoAdapter). 
If I provide correct values for width and height ==> I see in inspector that the psv-marker is added but it lacks the last part in its style ('transform(....)). So marker is not visible...

So my question is : Which value should I provide to marker plugin for x and y when using video plugin ? Does marker plugin works only with latitude and longitude position definition when using VideoPlugin ? 

Thank you for your answer, 
Best 
Stéphane

**Comment by mistic100** [comment]
@schaplain discussions are not for support

----

Are you using the EquirectangularVideo adapter or the CubemapVideoAdapter ?

For cubemap, x+y cannot work and you should see a `Current adapter does not support texture coordinates.` error in the console.

For equirectangular it should work, if not I will take a look.

**Comment by schaplain** [comment]
I'm using EquirectangularVideoAdapter. 
And i get video resolution from Three texture (texture.source.data.videoWidth) :
