### ISSUE TITLE
Blurred image in Chrome for Android

### ISSUE THREAD

**Issue by vekin03** [mistic100/Photo-Sphere-Viewer#696]
Hello,

First of all, a **big thank you** for this fabulous project that allows me to post and share my photo spheres online!

However, I noticed that the panorama rendering in the Android version of Chrome is very bad :-(

On **Firefox** for Android (101.2.0):
<a href="https://user-images.githubusercontent.com/3709747/173349006-cb17c5e6-eada-4446-bc18-2451d7af5804.png"><img src="https://user-images.githubusercontent.com/3709747/173349006-cb17c5e6-eada-4446-bc18-2451d7af5804.png" width="400"/></a>

On **Chrome** for Android (102.0.5005.78):
<a href="https://user-images.githubusercontent.com/3709747/173355034-f64b9cfe-27a2-4f1c-bd45-53b92d149bde.png"><img src="https://user-images.githubusercontent.com/3709747/173355034-f64b9cfe-27a2-4f1c-bd45-53b92d149bde.png" width="400"/></a>

_Click to enlarge._

We can see that the image is _very blurry_ on Chrome at the zoom max! It's the same with the integrated web browser (I suspect a Chrome-like browser).

You can visualize it online here: https://drone.vuilleumier.tv/valbirse-juin-2022.html

On desktop, the rendering is fine on Firefox and Edge, both in latest versions (I don't test on Chrome).

I'm using the latest version of the project (4.6.3) with bundled uevent and Three.js versions. I have an Huawei Mate 20 Pro with Android 10.

Any ideas to enhanced the image quality? Thanks!

**Comment by mistic100** [comment]
Hello

nothing can be done see https://github.com/mistic100/Photo-Sphere-Viewer/issues/684#issuecomment-1141185185
