### ISSUE TITLE
VideoPlugin: Unable to work in IOS application

### ISSUE THREAD

**Issue by hu-snail** [mistic100/Photo-Sphere-Viewer#698]
## system information 
- ios 15.1.1
- Wechat browser /  safari browser

## result
Display a blank screen, not even the navigation bar， But this is normal on the PC and Android

**Comment by hu-snail** [comment]
## supplement
ios safari browser is normal, Wechat browser is always loading

**Comment by mistic100** [comment]
same answer as #691, sorry I won't keep bug reports for Wechat as I don't have the resources to debug it.
