### ISSUE TITLE
Distorted straight lines at the bottom of the panorama

### ISSUE THREAD

**Issue by vekin03** [mistic100/Photo-Sphere-Viewer#699]
Hello,

At the bottom of one of my photos posted with PSV, we can see a sports field. Its lines are very distorted:

![image](https://user-images.githubusercontent.com/3709747/174466623-06078e6d-cf9d-4fc1-a0b7-d090e8a65261.png)

See also the stairs on the right. We also notice that the white "rectangle" at the bottom of the fields is very aliased.

Other viewers do not have these problems.

_FSPViewer_:

![image](https://user-images.githubusercontent.com/3709747/174466679-a5cd374b-9ac5-4915-bb96-8f2f03f92acb.png)

_ForgeJS_:

![image](https://user-images.githubusercontent.com/3709747/174466709-7f01481e-39b9-4adc-b455-f620b550de46.png)

In the code, I specify the image with the field "panorama".

I tried to split the image into tiles and display it with the "EquirectangularTilesAdapter", then to increase the resolution, but without success.

Is it possible to make the lines straighter in PSV? As ForgeJS also uses Three.js and is open source, maybe it is possible to improve this point by taking inspiration from their project?

Thanks and have a good sunday!

**Comment by mistic100** [comment]
I know why the view is distorded : it uses a simple sphere geometry which have very small faces in the bottom. Probably nothing can be done unless using other rendering techniques, which I have no will to investigate.

Also I don't have time to dig into another project (which is much more big and complex).

Feel free to a open an PR if you find a solution.
