### ISSUE TITLE
Ability to provide custom transition effect / parametize the default one

### ISSUE THREAD

**Issue by Strae** [mistic100/Photo-Sphere-Viewer#70]
Actually the .setPanorama() method directly invoke the _transition method, but there is no way to provide a custom animation function, nor to parameterize the current one.

Would be great to have the ability to provide a custom animation function while calling setPanorama and/or set the default transition while initializing the PSV object (using config)

**Comment by mistic100** [comment]
What do you mean "a custom animation function" ? The whole code instanciating the new image and performing the transition ? https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/src/js/PhotoSphereViewer.core.js#L274-L379

**Comment by Strae** [comment]
Sorta.
In my case, for example, i've been required to remove the [second half of the transition](https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/src/js/PhotoSphereViewer.core.js#L333) because the customer didn't like it.

It's a matter of taste of course, but for me is really important; I can try to implement this if you'll like.

**Comment by mistic100** [comment]
It's way too much complicated.

As in JavaScript, everything is kinda public, you can do it yourself in an external method. Or you can override the prototype

```js
// include the lib

// override prototype
PhotoSphereViewer.prototype._transition = function(texture, position) {
  // your implementation
};

// init the viewer
```
