### ISSUE TITLE
Panorama => Base64

### ISSUE THREAD

**Issue by imyelxx** [mistic100/Photo-Sphere-Viewer#700]
How can I load a base64 file in the panorama

**Comment by imyelxx** [comment]
![image](https://user-images.githubusercontent.com/102043695/175338479-f60d0124-18f5-49cb-91d0-a76822ab0a69.png)

**Comment by imyelxx** [comment]
![image](https://user-images.githubusercontent.com/102043695/175340014-c172b18c-18b9-47df-a959-20c5f5d5aa95.png)

**Comment by mistic100** [comment]
what does your `panorama` looks like ?
