### ISSUE TITLE
Marker plugin  -  feature

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#703]
Hi ... thank you again for your great work.

I have done everything I needed (with your help) and set all my panos.... Thank You

I have a question / suggestion 

I use equirectangular panos and when I click on a Marker (from the marker list) the clicked marker places itself in the exact center of the screen.
In this way though there is a large portion of the screen that it's black

https://www.tadini.it/temp/panorama_colmegnone.htm

I searched everywhere and there's no way to set the position of the view triggered by the click on the marker.

Is it worth it as a new feature?

**Comment by mistic100** [comment]
try https://photo-sphere-viewer.js.org/plugins/plugin-visible-range.html

**Comment by haldo98** [comment]
great!!!!!!!

works perfectly.....

    [PhotoSphereViewer.VisibleRangePlugin, {
      usePanoData: true,
    }],

Thank You so much  !!!
