### ISSUE TITLE
The panorama can't be loaded : Unable to detect system capabilities (getMaxCanvasWidth)

### ISSUE THREAD

**Issue by aroy314** [mistic100/Photo-Sphere-Viewer#708]
Hi, 

### Background
I just upgraded Photo Sphere Viewer from 3.6.0 to 4.6.4 and followed the Upgrade Guide. 

I got it all working, excepted the error `Unable to detect system capabilities` that happened on my console.
I am unable to resolve it or find any documentation about it (neither an issue in the github).

### Environment
- I use Laravel with Webpack 5 and Laravel Mix 6, PHP 8.1 and Node 16. 
- My local dev compiles assets with Node from Windows, my production server compiles assets with Node from Debian. 
- It works on Firefox Version 102.0.1 (local dev & production)
- It works on Chrome Version 103.0.5060.114 (local dev & production)
- On Brave Version 1.40.113 Chromium: 103.0.5060.114 : Everything works great on development mode, but on production I have the error `Unable to detect system capabilities` in console and the Viewer does not load. 

![image](https://user-images.githubusercontent.com/14325646/178495757-ead73a97-a43b-4fc0-8ea3-ab618a89d21f.png)

### Analysis
So I went down the rabbit hole to try to find where it comes from. It seems its from the function `getMaxCanvasWidth()`. 

```javascript
/**
   * @summary Gets max canvas width supported by the browser.
   * We only test powers of 2 and height = width / 2 because that's what we need to generate WebGL textures
   * @param maxWidth
   * @return {number}
   * @private
   */
  function getMaxCanvasWidth(maxWidth) {
    var canvas = document.createElement('canvas');
    var ctx = canvas.getContext('2d');
    canvas.width = maxWidth;
    canvas.height = maxWidth / 2;
    while (canvas.width > 1024) {
      ctx.fillStyle = 'white';
      ctx.fillRect(0, 0, 1, 1);
      try {
        if (ctx.getImageData(0, 0, 1, 1).data[0] === 255) {
          return canvas.width;
        }
      } catch (e) {// continue
      }
      canvas.width /= 2;
      canvas.height /= 2;
    }
    throw new PSVError('Unable to detect system capabilities');
  }
```

If I understand correctly, the method tries to create a canvas, fills it with a white rectangle and gets data from it. The format of  `ctx.getImageData(0, 0, 1, 1).data` is an _Uint8ClampedArray_ and you retrieve the first value to test if it is 255. If so, you return the canvas width, if not, it throws the error. 

In all browsers I tested, `ctx.getImageData(0, 0, 1, 1).data[0]` return the value 255 whereas Brave on production, the array of `ctx.getImageData(0, 0, 1, 1).data` looks like this : 

```json
{
    "data": {
        "0": 254,
        "1": 255,
        "2": 254,
        "3": 255
    },
    "colorSpace": "srgb"
    "height": 1
    "width": 1
}
```

### What I tried
I tried to change the code with a comparison like `if (ctx.getImageData(0, 0, 1, 1).data[0] === 255 || ctx.getImageData(0, 0, 1, 1).data[0] === 254)` and then the Viewer loads without any error. So I guess the value "255" is not really important, its just a test to see if the canvas loaded properly the rectangle. 

### Solution proposition
I have no idea why Brave decided to put these values in the canvas instead of the usual 255, but I'm wondering if the purpose of this test is really to match the value 255. There might be a way of doing this differently so we avoid these edge cases. Maybe just a comparison like `ctx.getImageData(0, 0, 1, 1).data[0] > 250` would be enough ?

Let me know if you need more details. 

Thanks

**Comment by mistic100** [comment]
I think the issue is https://github.com/brave/brave-browser/issues/10000

It is caused by the anti-fingerprinting feature. Si I will loosen the test.
