### ISSUE TITLE
Minimap/radar

### ISSUE THREAD

**Issue by Strae** [mistic100/Photo-Sphere-Viewer#71]
I built a simple map-radar functionality:
![screenshot - 09022016 - 10 30 30 am](https://cloud.githubusercontent.com/assets/142003/18197658/b0004dd8-70f8-11e6-9d79-21888d332f25.png)
![screenshot - 09022016 - 10 31 07 am](https://cloud.githubusercontent.com/assets/142003/18197659/b0010106-70f8-11e6-860b-7c3da176a865.png)

While changing to a panorama to another the radar updates showing the position of the panorama on the map, and the rotation of the radar follow the scene longitude.

To do that, we need some other data:
- Map image (obviously)
- For every panorama image:
  - X and Y position on the map
  - Rotation adjustment factor

So this require to add more information when calling `setPanorama()` or `preloadPanorama`.

Actually I implemented this feature using an external wrapper, without touching the PhotoSphereViewer code; I'm just wondering if is worth to add it into the core (and if yes, I can take care of it)

**Comment by mistic100** [comment]
I don't really understand why the viewer should know these data as the panorama is not changed from the inside of the lib but only by a call to "setPanorama".

PS: did you see I have a tour library base the PSV ? https://github.com/mistic100/Photo-Sphere-Tour
it's a really early stage though

**Comment by Strae** [comment]
Well, the viewer shouldn't, the correct place for this information is an external wrapper (like a tour object who give commands to the viewer)

But the radar should stay inside the HUD, and the HUD is a part of the viewer
In my use case, I inject the markup for the map and radar inside the psv container; it works, but still, it is not the 'correct' place imho.

I didn't see your tour library, i'll take a look at it

**Comment by mistic100** [comment]
I think it is. Why couldn't you modify the HUD ? And if you don't like it, add another HUD above the whole viewer.

To answer your question : no this has nothing to do in this lib, perhaps in PhotoSphereTour but there is still a lot of work for me to accept merge requests.
