### ISSUE TITLE
How to switch to asteroid Perspective

### ISSUE THREAD

**Issue by hu-snail** [mistic100/Photo-Sphere-Viewer#713]
Hello, is there any way to switch the perspective of panorama, such as asteroids

**Comment by mistic100** [comment]
What does that mean ?

**Comment by Admin0x002** [comment]
Maybe he wants the <littleplanetintro> functionality of <krpano>?
![GIF](https://user-images.githubusercontent.com/25890854/181872420-d0c3c918-06a5-4fc5-9ca6-fb7008ddda03.gif)

**Comment by Admin0x002** [comment]
Maybe he wants the "littleplanetintro" functionality of "krpano"?

![GIF](https://user-images.githubusercontent.com/25890854/181872443-0f4619e2-a19c-40f6-bcbd-a9e96ee96593.gif)

**Comment by mistic100** [comment]
I won't be able to provide a transition like this.

I am currently fiddling with a little planet mode (always on).
