### ISSUE TITLE
Unable to select button

### ISSUE THREAD

**Issue by kongqizhizi** [mistic100/Photo-Sphere-Viewer#714]
Bug: Unable to select button
<img width="516" alt="image" src="https://user-images.githubusercontent.com/67044460/180660576-96903d62-d3ed-4cd8-96d9-4a4f5da1c0ab.png">

Chrome： 102.0.5005.115 (arm64)

**Comment by mistic100** [comment]
Works well for me on Chrome 103.

This is not part of the library so I will not investigate further.
