### ISSUE TITLE
Support for esm moudle output?

### ISSUE THREAD

**Issue by beginor** [mistic100/Photo-Sphere-Viewer#716]
Hi, does photo-sphere-viewer support es module output format? 

I have tried to change the output format from `umd` to `es` in the rollup.config.js, and then I run `npm run compile` command  generate output in esm format, but when I run an example in browser, I got the flowing error: 

```
TypeError: Class constructor EventEmitter$1 cannot be invoked without 'new'
    at new Viewer (Viewer.js:54:5)
    at App.run (app.ts:10:20)
    at main.ts:9:7
```

**Comment by mistic100** [comment]
Not in V4, see https://github.com/mistic100/Photo-Sphere-Viewer/discussions/593

**Comment by beginor** [comment]
Sorry, I have not seen the discussions.
