### ISSUE TITLE
Autorotation stuck

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#718]
Chrome latest version
PSV version 4.7.0

A strange behaviour happens with some pano I have in my pages
after loading....  I have set the autorotateDelay to 3000. When this time is expired the autorotate button is toggled as expected, but nothing happens. The autoration is stuck.
This happens only in some pano.... In other panos the behaviour is as expected and the autoration starts as planned

Stucked autoration pano:
https://www.tadini.it/panorama/saccarello/panorama_saccarello.htm

normal autoration
https://www.tadini.it/panorama/gusmeroli/panorama_gusmeroli.htm

Thank U.

**Comment by mistic100** [comment]
I think it is because of the VisibleRangePlugin and the fact your panorama is very narrow, it evens logs a warning because the range is invalid.

**Comment by mistic100** [comment]
probably a side effect of this rework https://github.com/mistic100/Photo-Sphere-Viewer/commit/dec99cb1bf999376a5f699704581665278e10147

**Comment by mistic100** [comment]
Actually the mentionned commit only agravated an existing bug : the computed latitude range was inverted and it didn't handle properly the case of narrow images when the range is smaller than the viewport.
