### ISSUE TITLE
Memory leak issue "The memory used by the ThreeJS context is not totally cleared"

### ISSUE THREAD

**Issue by cijianzy** [mistic100/Photo-Sphere-Viewer#719]
Anotation in 

https://github.com/mistic100/Photo-Sphere-Viewer/blob/db1becbb34fe89677f7acaf02b16af971a9a60b9/src/Viewer.js#L296
   
* @description The memory used by the ThreeJS context is not totally cleared. This will be fixed as soon as possible.

Want to know is there has any plan to fix it?

Thanks very much.

**Comment by cijianzy** [comment]
We are facing page reload problem caused by this issue.

In one page, we will change panorama photo when customer click "next" button.  so every time customer click "next", we will destroy old and create new Viewer. if customer click enough "next" button, this page will crash becuase of memory issue.

Forgive my poor English.

**Comment by mistic100** [comment]
First you don't have to recreate the viewer when changing panorama, there is the `setPanorama` method.

Secondly there is no remediation for this issue, I already dispose every object possible. The rest is up to Three.js developpers.

**Comment by cijianzy** [comment]
@mistic100 Thanks for replay, but there still some strange bug when we change VirtualTour (like Geoguessr). so i use simple way just destroy and recreate.

Maybe i will create another  issue about VirtualTour change.
