### ISSUE TITLE
THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().

### ISSUE THREAD

**Issue by Zolcsimus** [mistic100/Photo-Sphere-Viewer#72]
I just opened my Chrome today and I get these messages in the console also the whole Photosphere Viewer got a grid all around it.

THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().
735three.min.js:772 THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox().
2289617console messages are not shown.
three.min.js:772 THREE.Box2: .empty() has been renamed to .isEmpty().
7333three.min.js:773 THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().
731three.min.js:772 THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox().
three.min.js:772 THREE.Box2: .empty() has been renamed to .isEmpty().
7335three.min.js:773 THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().
729three.min.js:772 THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox().
three.min.js:772 THREE.Box2: .empty() has been renamed to .isEmpty().
7328three.min.js:773 THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().
737three.min.js:772 THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox().
three.min.js:772 THREE.Box2: .empty() has been renamed to .isEmpty().
7313three.min.js:773 THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().
751three.min.js:772 THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox().
three.min.js:772 THREE.Box2: .empty() has been renamed to .isEmpty().
7316three.min.js:773 THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().
748three.min.js:772 THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox().
three.min.js:772 THREE.Box2: .empty() has been renamed to .isEmpty().
7341three.min.js:773 THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().
724three.min.js:772 THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox().
three.min.js:772 THREE.Box2: .empty() has been renamed to .isEmpty().
7316three.min.js:773 THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().
748three.min.js:772 THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox().
three.min.js:772 THREE.Box2: .empty() has been renamed to .isEmpty().
7324three.min.js:773 THREE.Box3: .isIntersectionBox() has been renamed to .intersectsBox().
740three.min.js:772 THREE.Box2: .isIntersectionBox() has been renamed to .intersectsBox().

**Comment by mistic100** [comment]
The grid is visible when you don't have webgl and it will fixed in the next version https://github.com/mistic100/Photo-Sphere-Viewer/commit/55a3fc156fd24b2b311f462a0b48c4316ef922be

All these warnings come from internal Three.js code.

**Comment by mistic100** [comment]
Certainly not, I can't tell sorry.
