### ISSUE TITLE
Gallery plugin

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#720]
Hello...

I tried the new gallery plugin...   
https://www.tadini.it/temp/panorama_colmegnone.htm

I have a few questions:

- The thumbnail seems to have a fixed height and width...   My Thumbnails are 120*80 but it seems there are scaled up to fill the dimension of the container.
- The paths in the items only point to another image... not a web page. ( I tried web page in panorama 3 - but gives error)
This way though the markers and other stuff are not useful anymore, since are related to the original pano image

It also seems that the new pano image takes the dimension of the original pano.  Pano 1 and pano 2 are distorted, once i click on the link to show them.

Thank You for your great work.

**Comment by mistic100** [comment]
- use CSS if the dimensions doesn't suits you

- yes the plugin is only a wrapper arround `setPanorama` method, this won't change  
As explained in the documentation you can add an `options` property to each item https://photo-sphere-viewer.js.org/plugins/plugin-gallery.html#options

particulary you need to to provide `options.panoData` for each item. Because `setPanorama` assumes it's a totally different panorama and thus ignores the default value (even though it is a function).

As for markers you need to manage this yourself using events

```js
viewer.on('panorama-loaded', (e, data) => {
  markers.setMarkers(....);
  // depends on `data.panorama` which is the url of the new panorama
});
```

same goes for other stuff like compass hotspots, etc

**Comment by mistic100** [comment]
For `panoData` I created a new issue #721

**Comment by haldo98** [comment]
Thank You... always useful and kind.

**Comment by haldo98** [comment]
Thank You....

please be patient...

I manage to get the result with option.panoData as you suggested, and now the pano is not distorted anymore but it seems, as per Api.documentation, that default.Long, defaultZoom, minFov, maxFov autorotateDelay are not supported.   Is it correct?

I wanted to remove markers in the linked pano and i tried this

viewer.on('panorama-loaded', (e, data) => {
  if (data.panorama === '../panorama/angeloga/panorama_angeloga.htm') {
    markers.removeMarker(1);
  }
  });

but it's not working. What am I doing wrong?

**Comment by mistic100** [comment]
your panorama is `../panorama/angeloga/panorama_angeloga.jpg` nor `../panorama/angeloga/panorama_angeloga.htm`

**Comment by haldo98** [comment]
I modified the page

https://www.tadini.it/temp/panorama_colmegnone.htm

but the markers are still there....   
sorry

**Comment by mistic100** [comment]
`removeMarkers(1,2,3,4)`

that is NOT how it is done, if you read the doc https://photo-sphere-viewer.js.org/api/psv.plugins.markersplugin#removeMarkers, it takes an array, also your ids are strings, not numbers

so `removeMarkers(['1', '2', '3', '4'])`

if you want to remove everything: `clearMarkers()`

----

once again **USE THE BROWSER DEBUGUER**, there is a big red error when accessing the first panorama, because you use a `markers` variable that you never initialized, you are missing this line after creating the viewer

```
const markers = viewer.getPlugin(PhotoSphereViewer.MarkersPlugin);
```

---

I am sorry I will have to stop to answer if you don't know how to develop in Javascript, I only provide help for Photo Sphere Viewer.

**Comment by haldo98** [comment]
You're right.. sorry !!  You have always been kind.  My bad.

about PSV.. I previously asked if the default.Long, defaultZoom, minFov, maxFov are supported in the gallery plugin option?

**Comment by mistic100** [comment]
You can change the default lat, long, zoom with the `options` of each item, all options are https://photo-sphere-viewer.js.org/api/psv#.PanoramaOptions (pay attention it inherits from `ExtendedPosition` so you can provide `options.longitude` and `options.latitude`).

the minFov and maxFov can only be changed globally with [`viewer.setOptions`](https://photo-sphere-viewer.js.org/api/psv.viewer#setOptions) so if you want to change them for each item you will have to use the same `panorama-loaded` event.

**Comment by haldo98** [comment]
Thank You SO MUCH  !!!

**Comment by haldo98** [comment]
with your precious help (thank You again) I managed to get everything working....   as I expected.
except for the zoom....   I put it in the options of the item but it remains at maxFov
i can use viewer.zoom    but I want to know if I did something wrong...

Thank you.

**Comment by haldo98** [comment]
I also noticed a strange behaviour....

In the same page linked before the autorotation starts correctly as usual...   (the    defaultZoomLvl is set to 2)

if I zoom completely out (slider totally on the left) the autorotation is not starting even if I toggle the button

maybe is connected with #718

**Comment by haldo98** [comment]
I made some trial and error and I find out that the zoom level set in the option of the item actually works.
If I set different value the zoom is different, but then, the maxFov and minFov set, changes the position of the zoom in the slider
The slider range is correct but the position of the bar is not where it should (maxFov)
Hope this helps

Thanks again

**Comment by haldo98** [comment]
same page i linked before...

https://www.tadini.it/temp/panorama_colmegnone.htm


Thank you so much.

**Comment by mistic100** [comment]
1) Post code here in Github, it is not practical to look at the source of your website

2) you don't have any `zoom` in the options of the gallery items

**Comment by mistic100** [comment]
I just tested in the example file to add `zoom: 50` (50 is default) to every item `options` it works perfectly

**Comment by haldo98** [comment]
You're right.. I was playing with other stuff... and I used viewer.zoom to get the result I wanted and delete the zoom in the options

now i changed the page
https://www.tadini.it/temp/panorama_colmegnone.htm

back to the zoom in the options of the gallery items....

please click first on "angeloga"  The zoom is not at 2 where it is supposed to be

and then click on "bregagno" and look at the strange display of the bregagno pano....

then back to angeloga . The zoom is now correct....

Thank you!!!!!!

**Comment by mistic100** [comment]
I don't see anything wrong the viewer zooms out when changing panorama as expected.... 

The only problem is the VisibleRange plugin and fixed in #718

**Comment by haldo98** [comment]
I'll wait then when 4.7.1 will be released ..
Thank you again for your patience with me...

**Comment by mistic100** [comment]
@haldo98 I added a `thumbnailSize` option https://photo-sphere-viewer.js.org/plugins/plugin-gallery.html#thumbnailsize

It will be releases soon with version 4.7.1

**Comment by haldo98** [comment]
Great!!!
