### ISSUE TITLE
web console messages

### ISSUE THREAD

**Issue by jhonjeins** [mistic100/Photo-Sphere-Viewer#722]
After the update to version 4.7.0 the messages of the web console in the Crhome browser do not match the paths of the code, it directs to other files and not the correct one

**Comment by mistic100** [comment]
Do you have any example ?

**Comment by jhonjeins** [comment]
for example the correct path of a console.log is this "modalInformativo.js:9"
![Captura](https://user-images.githubusercontent.com/57718184/185182052-aea0d5c8-0acc-4f01-b5ee-29e74328da0b.JPG)

but it is throwing wrong path "tableExport.min.js:9" 
![WhatsApp Image 2022-08-16 at 11 17 08 AM](https://user-images.githubusercontent.com/57718184/185182443-8d40ef5d-762f-4819-9de5-ad6528b4f350.jpeg)

and this is happening right after updating photo-sphere, if i go back to version 4.2.0 it works fine
