### ISSUE TITLE
VR marker

### ISSUE THREAD

**Issue by ChanderShekharKestone** [mistic100/Photo-Sphere-Viewer#725]
For now the markers are totally disabled when entering VR mode, because they are not in the ThreeJS scene but on a layer on top of it, I have now idea how to display them in VR mode without having a ghosting effect.

Please tell how to display and it will work for tour (or change image).

**Comment by mistic100** [comment]
This is only possible for the `imageLayer` markers, I can make a change to not hide those.

But it will **never** work for standard "flat" markers.

**Comment by mistic100** [comment]
Actually `imageLayer` markers are already kept visible when entering VR.
