### ISSUE TITLE
How to use adapters and plugins in React?

### ISSUE THREAD

**Issue by mikepianka** [mistic100/Photo-Sphere-Viewer#729]
I am currently working on implementing photo-sphere-viewer in a React app. I was having the same problems that others encountered in #656 with the "THREE.Quaternion is not a constructor" error. My workaround was to switch the rollup output target from umd to es, run a build, and then import the Viewer class directly from that local build rather than node_modules. 

That approach is working fine for a plain viewer, but now that I am trying to add adapters and plugins I am hitting that THREE.Quaternion... error again even using my local build which has the output rollup target set to es. I also tried esm but the error is still there trying to import the plugins or adapters. 

I am not a rollup pro so I'm wondering is there any other config that might need to be changed for the adapters and plugins? Is their build step handled differently than the main Viewer?

I'm sure I'm not the only person trying to get this going in React so hopefully someone has some advice. I would be happy to make an example for the docs that could help others once this is figured out. 

Thanks!

**Comment by mikepianka** [comment]
I was able to get a compass plugin and equirectangular tiles adapter both working in React (TypeScript and bootstrapped with create-react-app) albeit in a somewhat hacky way.

1. Switched the rollup output target from `umd` to `es`, compiled and copied the output to a directory called `lib`, and then imported the Viewer like `import { Viewer } from "./lib/photo-sphere-viewer";`. This solved the initial `THREE.Quaternion is not a constructor` error that was getting thrown trying to use the Viewer. I was then able to create a basic Viewer inside a React function component.

2. Trying to import CompassPlugin like `import { CompassPlugin } from "./lib/plugins/compass";` would cause a constructor error to start showing up again but this time it alternated somewhat randomly between `THREE.Vector2 is not a constructor` and `THREE.Vector3 is not a constructor`. I noticed in `lib/photo-sphere-viewer.js` that these were getting declared in the outer scope of the file like `var vector2 = new THREE.Vector2();` and then used in some various functions also declared there. I moved the `vector2` and `vector3` declarations out of the outer scope and into the functions using them. After these changes, the error went away (but a last final error showed up, see #3). This is strange because there are other things declared this way on the outer scope like `eulerZero` that didn't throw errors.

```js
// before
var vector3 = new THREE.Vector3();

// after
_proto.sphericalCoordsToTextureCoords = function sphericalCoordsToTextureCoords(position) {
    var vector3 = new THREE.Vector3();
    var panoData = this.prop.panoData;
    // etc...
```

3. After that fix, the last error showing up was just that `photo-sphere-viewer` could not be found in `compass.js` and `equirectangular-tiles.js`. Looking at that, the import just needed to go up one directory. Adding a `../` fixed it, like `import {SYSTEM, CONSTANTS, AbstractPlugin, utils} from "../photo-sphere-viewer";`

After those changes, things run fine with the dev server and the app can build successfully too. I am not sure if the switch in output format from `umd` to `es` is totally necessary after having to make the Vector2/3 changes afterwards because those errors just seem pretty strange. There doesn't seem to be anything particularly unique about THREE.Quaternion that would throw an error like that.

@mistic100 do you have any ideas?

**Comment by mistic100** [comment]
No more ideas than in the previous issue.

**Comment by mikepianka** [comment]
After some more testing, it seems that just steps 1 and 3 mentioned above are needed. Step 2 I believe was not necessary and was just a side effect of step 3 not being completed yet.

Is there a setting in the rollup config that I could change so that the plugins look one directory up for photo-sphere-viewer? It's easy enough to just add the `../` but I feel like I am just undoing something that rollup is doing.

**Comment by mistic100** [comment]
> Is there a setting in the rollup config that I could change so that the plugins look one directory up for photo-sphere-viewer? It's easy enough to just add the `../` but I feel like I am just undoing something that rollup is doing.

Just remove the "replace" plugin. The source uses ".." already by it's replaced by "photo-sphere-viewer" at build time.

**Comment by mikepianka** [comment]
Removing that replace plugin increased the build size alot - dist went from about 2 MB to 7 MB. Seems like instead of referencing imports from photo-sphere-viewer it was instead copying what would have been imported from photo-sphere-viewer into each file.

Alternatively, I found running the following find and replace using sed on the dist after build could keep the small build size while also fixing the path to photo-sphere-viewer.js:

`sed -i "s|from 'photo|from '../photo|g" *`

**Comment by mistic100** [comment]
> Removing that replace plugin increased the build size alot - dist went from about 2 MB to 7 MB. Seems like instead of referencing imports from photo-sphere-viewer it was instead copying what would have been imported from photo-sphere-viewer into each file.

Yes, that might be because of the "external" getting out of sync. Honnestly you'd better stick to you sed.  
PSV v5 will modernize the packaging but there is no planning for it.

And again, I am convinced the toolset for React is doing something wrong, there is not reason this UMD module breaks.  

As for the "globals" Vector3, Quaternion, Euler, etc. I will not move them. This is common practice as advised by ThreeJS to not re-instanciate this kind of objects in functions that can be executed 60 times par seconds.

**Comment by mikepianka** [comment]
Yes I do believe there is some issue between the UMD module and Webpack 5 that Create React App uses. I find examples on stackoverflow from a couple years ago where people were able to successfully use PSV in React with a standard import from node_modules, but this no longer works. Create React App switched from Webpack 4 to 5 since then so I do think that is probably the cause of why this is not working.

**Comment by mistic100** [comment]
I don't know what this discussion is about. This is so old you should not expect to have significant answers here, create a new issue if needed. But keep in mind I don't know anything about React and won't be of any help for any form of integration.

There is already a React wrapper created by another user, give it a try https://www.npmjs.com/package/react-photo-sphere-viewer
