### ISSUE TITLE
the bar about virtual-reality

### ISSUE THREAD

**Issue by wwlxz22** [mistic100/Photo-Sphere-Viewer#73]
How can I add the virtual-reality button on the Nav bar?
I try to add 'vr','virtual-reality' in the Nav bar{ },but it doesn't work ,and destroy the operation

**Comment by Strae** [comment]
I dont think VR mode (like cardboard) is supported at the moment..

**Comment by mistic100** [comment]
http://photo-sphere-viewer.js.org/#navbar It's not listed, so it does not exists.

I know JeremyHeleine version has VR support, but as I don't have any VR device I can't implement it.

I am not against it but only if some one create a merge request or I get a VR device.

**Comment by wwlxz22** [comment]
@mistic100 thanks so much , I have watched the code of Jeremy.Your answer so quickly . If you live in China ,I'm willing to provide you a VR device. Thanks for your work.

**Comment by Strae** [comment]
wow, didnt know the original repo has this feature.. i'll try to add it in the near future.

**Comment by mistic100** [comment]
It uses the standard Three.js StereoEffect
http://threejs.org/examples/webgl_effects_stereo.html

**Comment by Strae** [comment]
@wwlxz22 first try with stereoeffect (vr): https://github.com/Strae/Photo-Sphere-Viewer/tree/vr

Once active, there is a problem with markers position (and also a small issue with fullscreen&window size, but this one should be easy)

**Comment by Strae** [comment]
Implementing the stereo effect is dead simple, the big problem is how to update the marker rendering to be _aware_ of the stereo effect..

**Comment by mistic100** [comment]
Please open a new issue to discuss about what need to be done.
