### ISSUE TITLE
pano image color is muted 

### ISSUE THREAD

**Issue by gleatherman** [mistic100/Photo-Sphere-Viewer#730]
**Issues guidelines**

- **Indicate your Photo-Sphere-Viewer, three.js and web browser versions**
- photo sphere 4.7, firefox dev 105.0b1

getting a weird effect where the photo displayed is muted with a green tone compared to the original image (which was color corrected). Cant find anything CSS wise that might be causing it.

here it is in the viewer: https://gleatherman.github.io/kz-iowa-courts/
here is the orig pano image: https://gleatherman.github.io/kz-iowa-courts/images/fisheye-color-corrected-small.jpg

any ideas?

**Comment by mistic100** [comment]
What do you mean color corrected ? ThreeJS/WebGL/Canvas API only fully supports sRGB colorspace, if you something else or a ICC profile this behavirous is expected.
