### ISSUE TITLE
Using the MarkersPlugin in TypeScript

### ISSUE THREAD

**Issue by mikepianka** [mistic100/Photo-Sphere-Viewer#731]
In a TypeScript project, after importing MarkersPlugin like this:
`import { MarkersPlugin } from "./lib/plugins/markers";`

and then implementing it like this:
```js
    const viewer = new Viewer({
      plugins: [
        CompassPlugin,
        [
          MarkersPlugin,
          {
            markers: [
              {
                // image marker that opens the panel when clicked
```

the markers display fine in the viewer. However, trying to get a reference to the plugin like this:

```js
    viewer.once("ready", () => {
      setViewerReady(true);
      const markersPlugin = viewer.getPlugin(MarkersPlugin);
      /**
       * Create a new marker when the user clicks somewhere
       */
      viewer.on("click", function (e, data) {
        if (!data.rightclick) {
          markersPlugin.addMarker({
```

Results in two TypeScript errors. The first is for viewer.getPlugin is _Argument of type 'typeof MarkersPlugin' is not assignable to parameter of type 'string | PluginConstructor<AbstractPlugin>'.
  Types of construct signatures are incompatible."_

The second is for markersPlugin.addMarker and is _Property 'addMarker' does not exist on type 'AbstractPlugin'._

Do you have any suggestions? Thanks!

**Comment by mistic100** [comment]
The type declaration is tested (successfully) here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/tests/types/index.ts#L68

you can always use `viewer.getPlugin<MarkersPlugin>('markers')`

**Comment by mikepianka** [comment]
Doing it like this suppresses the error on `viewer.getPlugin` but still the issue for `addmarker`

![image](https://user-images.githubusercontent.com/47948499/186471034-9c910145-4273-4d9a-a59b-2a391317ae78.png)

**Comment by mistic100** [comment]
I don't know, I don't have time to push it further in a complete TS application.

Use `viewer.getPlugin('markers') as any as MarkersPlugin`

**Comment by mistic100** [comment]
Isn't this due to the fact you use a custom build ? Did you applied your "sed" to d.ts files too ? If both `viewer` and `markers` don't refer to the same AbstractPlugin (different files) it can be the cause.

**Comment by mikepianka** [comment]
OK I can give that a try. Yes I did apply sed to all files including the d.ts. Thank you for the continued help!

**Comment by mikepianka** [comment]
> I don't know, I don't have time to push it further in a complete TS application.
> 
> Use `viewer.getPlugin('markers') as any as MarkersPlugin`

This solved the .addMarker error, thanks! I do think something is still not quite right with TS though because I have noticed other instances where TS should throw an error but it doesn't. For example, I can pass an int as the id when defining a new marker which should be a string but TS does not complain.
