### ISSUE TITLE
The Viewer can't destroy

### ISSUE THREAD

**Issue by tzfun** [mistic100/Photo-Sphere-Viewer#737]
## Env
photo-sphere-viewer: 4.7.0
browser: Chrome 103.0.5060.134
OS: MacOS 12.3.1

## Error
```
TypeError: Cannot set properties of undefined (setting 'keyboardEnabled')
    at EventsHandler.disableKeyboard (photo-sphere-viewer.js?d518:6897:1)
    at Viewer.stopKeyboardControl (photo-sphere-viewer.js?d518:9655:1)
    at Viewer.destroy (photo-sphere-viewer.js?d518:8935:1)
```

<img width="515" alt="image" src="https://user-images.githubusercontent.com/34815354/187029939-5fc0abd9-e1fe-4264-87fa-54b164a28b46.png">

When invoke destroy method, it throw the `state` is undefined, just using plugin: GyroscopePlugin.

**Comment by mistic100** [comment]
I cannot reproduce the issue unless I call "destroy" twice. Are you 100% sure you are not calling "destroy" more than once ? (put some breakpoints)

**Comment by mistic100** [comment]
Pro tip : clear your variable once you destroyed the viewer.

```js
init() {
   this.viewer = new Viewer();
}

destroy() {
   this.viewer?.destroy();
   this.viewer = null;
}
```

that way you won't take any risk

**Comment by tzfun** [comment]
Sorry I found my problem, I did call it twice, thanks for the correction.
