### ISSUE TITLE
Why my GyroscopePlugin is always not available?

### ISSUE THREAD

**Issue by tzfun** [mistic100/Photo-Sphere-Viewer#738]
## Env
photo-sphere-viewer: 4.7.0
vue: 2.6.14
browser: 
1. iphone 11, IOS 15.4.1, Safari
2. NOVA-9, Harmony OS 2.0.1, Chrome
3. iphone 11, IOS 15.4.1, WeChat Browser

## Question

I've tried to use GyroscopePlugin on mobile devices and none of them work, but I can make sure other sites can use the gyroscope on these devices.

Am I using it wrong or is there a bug in this plugin? Hope that helps, thanks!

It's my code:
```vue
<template>
  <div class="page">
    <div id="viewer" style="width: 100vw;height: 100vh;padding: 0"></div>
  </div>
</template>
<script>
import 'photo-sphere-viewer/dist/photo-sphere-viewer.css'
import {Viewer} from 'photo-sphere-viewer'
import {GyroscopePlugin} from "photo-sphere-viewer/dist/plugins/gyroscope";

export default {
    name: "ViewPage",
    data: () => {
        return {
            url: require("@/assets/panorama.jpg"),
            instance: null
        }
    },
    mounted() {
        this._renderVr({
                    fisheye: false,
                    zoom: 50
                }, this.url)
    },
    methods: {
        _renderVr(model, photo) {
            if (this.instance != null) {
                this.instance.destroy()
                this.instance = null
            }
            let viewer = new Viewer({
                container: document.querySelector("#viewer"),
                panorama: photo,
                plugins: [GyroscopePlugin],
                lang: {
                    gyroscope: 'Gyroscope',
                },
                size: {
                    width: document.body.offsetWidth,
                    height: document.body.offsetHeight
                },
                fisheye: 1,
                minFov: 1,
                maxFov: 160,
                defaultZoomLvl: 10,
                defaultLong: -Math.PI / 2,
                defaultLat: -Math.PI / 2,
                autorotateDelay: 2000,
                autorotateIdle: true,
                autorotateSpeed: "1rpm",
                autorotateLat: 0,
                mousemove: true,
                mousewheel: false,
                loadingImg: require("@/assets/loading.gif"),
                useXmpData: true,
                sphereCorrection: {
                    pan: 2 * Math.PI,
                    tilt: 2 * Math.PI,
                    roll: 2 * Math.PI
                },
                navbar: false
            })
            this.instance = viewer

            viewer.once('ready', () => {
                viewer.plugins.gyroscope.start()
                viewer.animate({
                    longitude: Math.PI / 2,
                    latitude: 0,
                    fisheye: false,
                    zoom: model.zoom,
                    speed: '9rpm'
                }).then(() => {
                    viewer.setOptions({
                        minFov: 40,
                        maxFov: 80
                    })
                })
            })
        }
    }
}
</script>
```

Error track in WeChat App
<img width="857" alt="image" src="https://user-images.githubusercontent.com/34815354/187036590-95b73b61-63f8-43d0-989d-56929843355b.png">

**Comment by mistic100** [comment]
Is your website using HTTPS ?

The Device Orientation API is not available in HTTP https://developer.mozilla.org/en-US/docs/Web/Events/Detecting_device_orientation

**Comment by mistic100** [comment]
Also if it won't work in local network unless you are able to produce a valid self signed certitificate and install it on your dev server.

For local dev I use https://localtunnel.github.io/www/

**Comment by tzfun** [comment]
> https://developer.mozilla.org/en-US/docs/Web/Events/Detecting_device_orientation

Yes, I can't even deploy it on https

**Comment by mistic100** [comment]
Did you try to implement yourself a basic device orientation handler ? does it work ?

The thing is it works for me, I don't really know how I could debug something so tightly linked to your specific device.

**Comment by tzfun** [comment]
> Did you try to implement yourself a basic device orientation handler ? does it work ?
> 
> The thing is it works for me, I don't really know how I could debug something so tightly linked to your specific device. Also without a online example of your whole app, it's a dead end.

Would it confirm the issue if I gave you my https link?

If so how can I privately message you my link?

**Comment by mistic100** [comment]
No sorry I refuse private communications for assistance.

**Comment by tzfun** [comment]
Okay, so can you review if there are any problems with my code? I will solve the rest of the device testing by myself, can I finally connect a demo that uses your plugin to successfully run the gyroscope? (and the SPV version number that made this demo)

> No sorry I refuse private communications for assistance.

**Comment by mistic100** [comment]
There is no problem with your code, unless to useless call to `viewer.animate` **after** activating the gyroscope, but shouldn't be an issue.

There is a demo here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/example/plugin-gyroscope-stereo.html, launch it, use local tunnel, and you're good.

**Comment by tzfun** [comment]
Thanks for your help! I will fix my problem and reply under this issue.
