### ISSUE TITLE
`after-position-changed` event?

### ISSUE THREAD

**Issue by sk-zk** [mistic100/Photo-Sphere-Viewer#739]
- **Indicate your Photo-Sphere-Viewer, three.js and web browser versions**
Photo Sphere Viewer 4.7.0, three.js 0.143.0, Firefox 104.0

The `position-updated` event fires continuously as the user is changing the view. Is there an event that only fires after the user stops moving?

**Comment by mistic100** [comment]
I am sorry this won't be possible reliably, there are too many ways to change the position (API, mouse, navbar buttons, keyboard, animations, gyroscope).

If you problem is the frequency of events, use your favorite debounce or throttle utility.

Using RxJs for example

```ts
fromEventPattern(
  handler => viewer.on('position-updated', handler),
  handler => viewer.off('position-updated', handler)
)
    .pipe(
        throttleTime(1000, null, { leading: false, trailing: true })
    )
    .subscribe(() => something);
```
