### ISSUE TITLE
Fullscreen of the container.

### ISSUE THREAD

**Issue by AlexandreDelan** [mistic100/Photo-Sphere-Viewer#74]
In my project, I've added a top bar.
In the html code, this new div has been added in the container div (the one given in the container option).

This issue is the fullscreen is not done another "container". The name of the variable is confusing as 
"option.container != this.container".

see bellow.
```js
this.parent = (typeof options.container == 'string') ? document.getElementById(options.container) : options.container;
// create actual container
this.container = document.createElement('div');
this.container.classList.add('psv-container');
this.parent.appendChild(this.container);
```
Anyway I suggest the following update to toggle fullscreen on option.container and not this.container.

**Before:**
```js
PhotoSphereViewer.prototype.isFullscreenEnabled = function() {
  return PSVUtils.isFullscreenEnabled(this.container);
};
PhotoSphereViewer.prototype.toggleFullscreen = function() {
  if (!this.isFullscreenEnabled()) {
    PSVUtils.requestFullscreen(this.container);
  }
  else {
    PSVUtils.exitFullscreen();
  }
};
```

**After - replacing this.container by this.parent:**
```js
PhotoSphereViewer.prototype.isFullscreenEnabled = function() {
  return PSVUtils.isFullscreenEnabled(this.parent);
};
PhotoSphereViewer.prototype.toggleFullscreen = function() {
  if (!this.isFullscreenEnabled()) {
    PSVUtils.requestFullscreen(this.parent);
  }
  else {
    PSVUtils.exitFullscreen();
  }
};
```

**Comment by mistic100** [comment]
When posting a block of code use triple back-quote with language code (see your message I edited)

----

I'll see why it's not done like this and if it has impacts.

**Comment by mistic100** [comment]
The confusion between parent and container exists because I had to include another layer of DOM to simplify relative positioning, and in the process I forgot to migrate this particular lines of code.

**Comment by mistic100** [comment]
Now I remember why the fullscreen was not on the parent : #83

**Comment by mistic100** [comment]
@AlexandreDelan for the sake of simplicity I had to revert back to the old version.
If you want to add a custom toolbar, move it to the container after the viewer has been built (use the "ready" event).
