### ISSUE TITLE
overlayOpacity TypeError on EquirectangularTilesAdapter

### ISSUE THREAD

**Issue by mikepianka** [mistic100/Photo-Sphere-Viewer#746]
After upgrading from v4.7.0 to v4.7.1 in my project I'm getting this error. I am using the equirectangular tiles adapter without overlays. The docs say that only the equirectangular adapter supports overlays. Is the overlay property trying to be read from an interface that doesn't use it?

![image](https://user-images.githubusercontent.com/47948499/188953054-dd68def1-78b5-44e2-9b3a-58b315ddb485.png)

**Comment by mistic100** [comment]
Does it block the viewer or it is just an error in the console ? (in order to decide if this needs to be released ASAP)

**Comment by mikepianka** [comment]
It does block the viewer, I am getting the "panorama can't be loaded" message. 

I also just confirmed that switching the pano collection to regular non-tiled equirectangular panos works fine. So the issue is just with the equirectangular tiles adapter.

**Comment by mistic100** [comment]
Hmm, it does not block the viewer on the demo... whatever I'll release 4.7.2

**Comment by mikepianka** [comment]
My project is TS, so if the demo is only JS maybe it is just ignoring the undefined property.

**Comment by mistic100** [comment]
> My project is TS, so if the demo is only JS maybe it is just ignoring the undefined property.

No that is not possible. This is a runtime error.

**Comment by mikepianka** [comment]
Ah, right. My bad.
