### ISSUE TITLE
CubemapAdapter flipTopBottom not working as expected.

### ISSUE THREAD

**Issue by wuuuaaaa** [mistic100/Photo-Sphere-Viewer#748]
Hi,

I am trying to use PhotoSphereViewer.CubemapAdapter, while some of the cubemap images is not properly rotated.
I tried `flipTopBottom: true` but it seems like not working.

The demo cubemap from https://photo-sphere-viewer.js.org/guide/adapters/cubemap.html is generated in format below
```
         [T]
[L][F][R][B]
         [B]
```

While the cubemap i get to generated has format as below
```
   [T]
[L][F][R][B]
   [B]
```

Sample Code 
https://jsfiddle.net/kk8401/967vtswg/4/

Photo Sphere Viewer 4.7.1
Three.js latest
Firefox 104.0.2

**Comment by 88act** [comment]
flipTopBottom  is invalid， help ！！！
i try it ，and find  flipTopBottom   opt is invalid

===================================

   _proto.setTexture = function setTexture(mesh, textureData) {
      var texture = textureData.texture;
	   console.log("setTexture --------2---3--4-5-6 " )
      //alert("setTexture ")
      for (var i = 0; i < 6; i++) {
         if (this.config.flipTopBottom && (i === 2 || i === 3)) { 
			  console.log("i===== ",i)
		      texture[i].center = new three.Vector2(1, 1);
              texture[i].rotation =  Math.PI/4; 
            }   
      } 
      this.setOverlay(mesh, null);
    }

**Comment by wuuuaaaa** [comment]
Ok. i found another example which using this xyz mapping and it turns out working correcting without the need of flipTopBottom.

```
left  : PX
front : NZ
right : NX
back  : PZ
top   : PY
bottom: NY

    [PY]
[NX][PZ][PX][NZ]
    [NY]
```

**Comment by wuuuaaaa** [comment]
> flipTopBottom is invalid， help ！！！ i try it ，and find flipTopBottom opt is invalid
> 
> ===================================
> 
> _proto.setTexture = function setTexture(mesh, textureData) { var texture = textureData.texture; console.log("setTexture --------2---3--4-5-6 " ) //alert("setTexture ") for (var i = 0; i < 6; i++) { if (this.config.flipTopBottom && (i === 2 || i === 3)) { console.log("i===== ",i) texture[i].center = new three.Vector2(1, 1); texture[i].rotation = Math.PI/4; } } this.setOverlay(mesh, null); }

this config has to apply to adapter itself
`dist/adapters/cubemap.js`
https://photo-sphere-viewer.js.org/guide/adapters/cubemap.html#fliptopbottom
```

const viewer = new PhotoSphereViewer.Viewer({
  container: 'viewer',
  adapter: [PhotoSphereViewer.CubemapAdapter, {flipTopBottom: true}],
...
});
```

**Comment by mistic100** [comment]
@wuuuaaaa was is expected ? I don't understand the problem with the information you provided.

`flipTopBottom` only applies a 180° rotation to the top and bottom textures

**Comment by mistic100** [comment]
I think the error appeared with this commit https://github.com/mistic100/Photo-Sphere-Viewer/commit/64447a5c15e0e3414eda1081d9b30c36e05424a1

The new shader does not use the texture rotation. So the flag has no effect.

You can use version 4.7.0 before I fix it.
