### ISSUE TITLE
Possible to limit movement horizontally only?

### ISSUE THREAD

**Issue by kunalm** [mistic100/Photo-Sphere-Viewer#75]
Is it possible to limit user movement i.e. drag/touch/gyroscope to horizontal axis only? Need to make it work more like a 180 panorama viewer actually. 

Not sure but what about the "longitude_range" and "latitude_range" options, will they be of any help?

**Comment by mistic100** [comment]
Yes it's exactly what you want.

`latitude_range: [0, 0]`

If the doc is not clear enough, please suggest another description :-)

**BUT** there seems to be a bug with extreme values for the range, I'll fix it.

**Comment by kunalm** [comment]
Thanks, Will try this and let you know how it goes. Any chance of adding option to zoom in and out by given value and not just 1?

**Comment by mistic100** [comment]
It will not work (read my last sentence).

---

PSV.zoom(PSV.getZoomLevel() + 10);

**Comment by kunalm** [comment]
I tried using latitude_range: [0, 0] but that makes the sliding very jumpy. But using longitude_range[0,0] works smoothly. Here are the settings I'm using.

psViewer = new PhotoSphereViewer({
        panorama: {pathToImg},
        container: 'psv-view-wrap',
        navbar: false,
        mousewheel: false,
        gyroscope: true,
        anim_speed: '1rpm',
        default_fov: 70,
        time_anim: 3000,
        autoload: true,
        latitude_range: [0, 0],
        move_inertia: false,
    });

**Comment by mistic100** [comment]
That's exactly what I said....

**Comment by kunalm** [comment]
Can you please comment on when do you expect to fix the bug?

**Comment by mistic100** [comment]
no I can't

**Comment by kunalm** [comment]
Will it help if I pay for your time to fix only this bug asap? You can contact me on mukherjiikunal@gmail.com if you are interested.

**Comment by mistic100** [comment]
No, I don't do payed work for any of my OS projects.

**Comment by Strae** [comment]
@mistic100 just for curiosity, may I ask why?

**Comment by mistic100** [comment]
Because I don't want to be accountable for anybody. And I don't want to spend my time doing administrative papers of the number of requests (and revenues) increases.

**Comment by Strae** [comment]
Well I guess this is not the right place to talk about this, so I will not.. I respect your opinion even if I can't say that I totally agree with it.

@kunalm I've seen a platform for things like this, "bounty source alert" or something like that where you can put a bounty on a bug/feature requests and who fix it get the prize.. never used it, but the idea was not bad, maybe its worth a try if you really need this bug to be fixed quickly

**Comment by kunalm** [comment]
@mistic100 I am doing a project where I need the only horizontal movement as a mandatory requirement. I tried other plugins but they are missing one or many other features which I need. Everything works with yours and just need the horizontal movement to work, that's it. No need to go through any kind of paperwork. I can simply send you $ via paypal. Just this one issue I'm stuck with.

**Comment by kunalm** [comment]
@Strae Can you help? I can simply send you $ via paypal. Just this one issue I'm stuck with.

**Comment by Strae** [comment]
@kunalm sorry at the moment I can't, until next week im out of office and dont have with me my work laptop.
Sorry dude, try to look at the source maybe is not hard to fix

**Comment by kunalm** [comment]
@Strae Ya I looked at it. It will be time taking. I still have to code other parts of the project otherwise could have looked into this.

**Comment by Strae** [comment]
Monday or Tueasday I should be able to give it a look if the bug will still be open

**Comment by kunalm** [comment]
@Strae Cool! will wait for your reply. Will be great if you can get a fix for this by Monday. you can email me directly at mukherjiikunal@gmail.com. Thanks.

**Comment by Strae** [comment]
Please note im not making promises!

**Comment by kunalm** [comment]
@Strae Sure, I understand. I am also looking for other plugins. If you can help I will share a part of the project fee with you (:

**Comment by Strae** [comment]
..we are a bit off-topic now ;)
however I already have a job, if you're willing to make a donation for this, [here you go](http://www.emergency.it/en-index.html).
Another one [here](www.greenpeace.org/eastasia/donate/).
Or [here maybe](https://www.debian.org/donations).

You'll find a lot of people to help with money ;)

**Comment by kunalm** [comment]
@Strae Not off topic actually cause I had no idea that you are already doing a  full time job. Anyway noted on the donation links, if you can help will donate a part of the fee there. Thanks.

**Comment by mistic100** [comment]
done

**Comment by kunalm** [comment]
@mistic100 Hey thanks for the help! Appreciate it.
