### ISSUE TITLE
Event when animation is complete / rendering has stopped

### ISSUE THREAD

**Issue by mikepianka** [mistic100/Photo-Sphere-Viewer#752]
Is there any event for the viewer that would signify it has gone idle? Basically an event that fires once any animations are complete and rendering has stopped. I have looked at `stop-all` and `render` but they don't seem to be what I'm looking for.

**Comment by mistic100** [comment]
"idle" may have many definitions, is it only for autorotate ? or also user interactions ? what about single clicks (which since #724 will not cancel ongoing animations).

What is your goal ? It is like #739 ? if so my answer is the same. There are too many sources of interaction to have something reliable.

**Comment by mikepianka** [comment]
OK just figured I would ask. Yes my goal is similar to #739. I think I found something that should work then for what I need. I'll run `Date.now()` on each `render` event and store it in a variable. Then I can just check that some time has elapsed since the last timestamp to consider it idle. Thanks.

**Comment by mistic100** [comment]
that's one of my favorite throttle utility, the "manual" :)

**Comment by mistic100** [comment]
The user in the other issue never responded, but if this is a recurrent need (so exactly "the render loop is paused", which may never happen if using plugins like gyroscope) I could add an event

**Comment by mikepianka** [comment]
Haha yeah exactly just a manual debounce. I think this method works well enough for my purposes, I just didn't want to miss an official event if there was one. It is definitely a bit tricky to track because like you said updates to the view can come from many different inputs.
