### ISSUE TITLE
Not working gyroscope

### ISSUE THREAD

**Issue by sevenor** [mistic100/Photo-Sphere-Viewer#755]
I downloaded the basic version 4.7.2 from the website.
I tried to run the gyroscope / stereo example.
http://ie.octav-sreda.ru/360/example/plugin-gyroscope-stereo.html

Replaced only the script connection paths with
<script src="https://cdn.jsdelivr.net/npm/three/build/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/uevent@2/browser.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4.7.3/dist/photo-sphere-viewer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/photo-sphere-viewer@4.7.3/dist/plugins/gyroscope.js"></script>

With the most default settings, the gyroscope does not start on phones. As is the stereo mode.

What happened wrong?

**Comment by mistic100** [comment]
Gyroscope requires a secure context, it cannot work over HTTP (not S).
