### ISSUE TITLE
Cannot manually start autorotate

### ISSUE THREAD

**Issue by yumu7777777** [mistic100/Photo-Sphere-Viewer#758]
**Issues guidelines**

- **Indicate your Photo-Sphere-Viewer, three.js and web browser versions**
- Please search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.

**Comment by mistic100** [comment]
I have no idea what that means

**Comment by yumu7777777** [comment]
用中文可以吗

**Comment by yumu7777777** [comment]
In asteroid mode, the initialization of automatic rotation does not work

**Comment by yumu7777777** [comment]
![image](https://user-images.githubusercontent.com/104643678/191449635-b745beb8-a555-4e67-8cba-04c75274b767.png)

**Comment by yumu7777777** [comment]
![image](https://user-images.githubusercontent.com/104643678/191454851-6c3e8a0c-2f5d-491b-a536-e2b4a10bcb66.png)

**Comment by mistic100** [comment]
Please don't write texts on screenshots, why don't you write the same thing directly on the issue ?

----

There is is indeed a behavior I don't understand. In the meantime you can call `viewer.__stopAll();` before `startAutorotate`.

**This is internal API**

**Comment by yumu7777777** [comment]
ok, thank you very much.

**Comment by mistic100** [comment]
Don't close issues when the bug is acknowledged and a milestone is linked !

**Comment by mistic100** [comment]
@yumu7777777 So I looked deeper and into this and it is not a bug. `Animation` cannot be used while to autorotate system is active.

The solution is to change the settings after the end of the animation.

```js
    viewer.setOptions({
      autorotateDelay: 1000,
      autorotateIdle: true,
    });
```

Demo : https://jsfiddle.net/7oz6yhw4/ (notice the `autorotateDelay` and `autorotateIdle` are not set in the initial options).
