### ISSUE TITLE
Marker list feature

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#759]
just a thought.....

I use markers to indicate some peaks that are shown on the panorama. But sometime the marker points to some peak that needs to be zoomed in to show something, because it is far away.

it would be nice if after clicking on a marker on the marker list there were some parameters to set...  like the zoom level.

as I said ... just a thought

**Comment by mistic100** [comment]
That's interesting, I'll try to implement a `zoomLvl` marker option that would be applied by the `gotoMarker()` method (and thus the markers list).
