### ISSUE TITLE
Gallery plugin - minFov maxFov

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#763]
Sometime ago I Opened the #720  issue and I wrote that I was waiting for the 4.7.1 update.

But I never came back to my test page.

Now I did. 

https://www.tadini.it/temp/panorama_colmegnone.htm

I have this code to set the zoom for each item and to hide buttons and clear markers

```js
viewer.on('panorama-loaded', (e, data) => {
if (data.panorama === '../panorama/bregagno/panorama_bregagno.jpg') {
    markers.clearMarkers(); 
    viewer.setOptions ({    
    minFov: 5,
    maxFov: 47,
    });
    viewer.navbar.getButton('I').hide();
    viewer.navbar.getButton('P').hide();
  }  
else if (data.panorama === '../panorama/angeloga/panorama_angeloga.jpg') {
    markers.clearMarkers(); 
    viewer.setOptions ({    
    minFov: 5,
    maxFov: 67,
    });
    viewer.navbar.getButton('I').hide();
    viewer.navbar.getButton('P').hide();
  }
  });
```

Try this: load the page and then, on the gallery, click the "bregagno" one. the view seems fine. but markers are not cleared and buttons are visible.
 
Now on the gallery click "angeloga". Markers are cleared, buttons are hidden, but the zoom is not completely out as it should.

Reload the same page and then, this time, click first on "angeloga" on the gallery. Markers are cleared, buttons are hidden, but the zoom is not completely out.

Click "bregagno". the view is not as expected. 

Click again to "angeloga". Now the zoom is correct.

It is strange.

I tried with this

https://www.tadini.it/temp/panorama_test.htm

to start with another panorama (with different size and minFov and maxFov) and the behaviour in the gallery is different
Bregagno is not shown correct and angeloga has the correct zoom from the beginning.

It seems maxFov and minFov are not applied correctly.

About the hiding of the buttons, for sure, I'm doing something wrong... :D :D

**Comment by mistic100** [comment]
I already asked you, multiple times, to use your browser debuguer.

On line 249 you declare
```js
panorama: '../panorama/Bregagno/panorama_bregagno.jpg',
```

and on line 
```js
if (data.panorama === '../panorama/bregagno/panorama_bregagno.jpg') {
```

See the problem ? the case is not consistent (capital B vs lower b).  You constants and you won't have problems.

---

For "but the zoom is not completely out as it should" and "but the zoom is not completely out" I don't know what that means. From my test it works exactly as expected : apply the new min/max and try to keep the current zoom level. If you want to also reset the zoom then call `viewer.zoom(zoomLvl)`.

---

note : you don't need to redeclare the `panoData` function anymore. This was fixed in [4.7.1](https://github.com/mistic100/Photo-Sphere-Viewer/releases/tag/4.7.1)

**Comment by haldo98** [comment]
> I already asked you, multiple times, to use your browser debuguer.
> 
> On line 249 you declare
> 
> ```js
> panorama: '../panorama/Bregagno/panorama_bregagno.jpg',
> ```
> 
> and on line
> 
> ```js
> if (data.panorama === '../panorama/bregagno/panorama_bregagno.jpg') {
> ```
> 
> See the problem ? the case is not consistent (capital B vs lower b). Use constants and you won't have problems.



Oh my.... I'm so stupid.  Thank you.



> 
> For "but the zoom is not completely out as it should" and "but the zoom is not completely out" I don't know what that means. From my test it works exactly as expected : apply the new min/max and try to keep the current zoom level. If you want to also reset the zoom then call `viewer.zoom(zoomLvl)`.


![Cattura](https://user-images.githubusercontent.com/97630238/192139133-1a3504fa-9f3f-4e0e-a7fd-5b34d0a7ea74.JPG)

the slider should be completely out (angeloga pano) 

If i add the `viewer.zoom(zoomLvl)  it works, I tried already but I thought it inherit the defaultZoomLvl.   

The strange thing is that if I click on Bregano the zoom slider is in the correct position (completely on the left)

On angeloga the slider is like in the pic attached


> 
> note : you don't need to redeclare the `panoData` function anymore. This was fixed in [4.7.1](https://github.com/mistic100/Photo-Sphere-Viewer/releases/tag/4.7.1)

**Comment by mistic100** [comment]
I swear there is absolutely no problem with the current behaviour but here is a break down:

- initial config is minfov: 5, maxfov: 43, zoomlvl: 2 => effective fov = 42.24
- in the configuration for "Angeloga" you have "zoom: 2" => after loading the panorama, effective fov is still 42.24
- after loading you change to minfov: 5, maxfov: 67 => effective fov is **not**changed, so the zoom level is modified accrodingly to 40, hence the zoom is at 40%

So as I said : call `viewer.zoom(0)` or `viewer.animate({ zoom: 0 }) after changing minFov,maxFov.

**Comment by haldo98** [comment]
> effective fov is **not** changed, so the zoom level is modified accordingly to 40

I guessed it was something like that....    Now it is clear.

Thank You

I will add viewer.zoom(0}
