### ISSUE TITLE
Equirectangular Tiles Adapter ignores poseHeading

### ISSUE THREAD

**Issue by ManuelFeller** [mistic100/Photo-Sphere-Viewer#766]
When using the **Equirectangular Tiles Adapter** the `poseHeading` parameter is ignored, even if `panorama.basePanoData.poseHeading` is set as the documentation says. The viewer always loads the panorama at heading 0.

Photo Shpere Viewer Version: 4.7.3
Browsers: Firefox 105.0.1, Chrome 106.0.5249.61 & 106.0.5249.91 (all MacOS)

How to Recreate:
- open https://jsfiddle.net/ymoarevj/5/
- manipulate the `poseHeading` value in line 11
- safe - and see that nothing changes :(

I have already tried to trace some things as good as possible in the dist-package.

It seems to me that the value is passed down, but ignored for some reason when the image is rendered.  
If I go into the `loadTexture` method (file `dist/adapter/equirectangular-tiles.js`, line 448) I managed to have the heading corrected when I use the `panorama.basePanoData`in line 523 (instead of `panoData`), but that leads to the effect that the tiles in view are no loaded; only the small preview image is shown. The tiles get properly loaded for heading 0 though, and once I made a full turn all parts are loaded as they should.  
So my guess woudl be that something in the rendering of the combined full size image is not taking the heading into account; but the way how that is done exceeds my current understanding of the code I have seen... :(

**Comment by mistic100** [comment]
This is documented here https://photo-sphere-viewer.js.org/guide/config.html#panodata

> Only the default equirectangular adapter and low-resolution panorama of equirectangular-tiles supports panoData, for other adapters you can only use [sphereCorrection](https://photo-sphere-viewer.js.org/guide/config.html#spherecorrection) if the tilt/roll/pan needs to be corrected.

[#](https://photo-sphere-viewer.js.org/guide/config.html#requestheaders)

**Comment by ManuelFeller** [comment]
Oh, sorry for missing that :( , thanks for sharing...
