### ISSUE TITLE
CSS not working with NextJS/React

### ISSUE THREAD

**Issue by tap2k** [mistic100/Photo-Sphere-Viewer#768]
Browser Version: Chrome 106.0.5249.61
PSV Version: 4.7.3

Im using PSV with NextJS/React, where including CSS file results in the viewer not being shown. Also, the height parameter to the PSV is not respected and is always shown at a fixed height, regardless of the width parameter, resulting in a skewed aspect ratio for any width other than 240px. See below for my example code. 

```
import React, { useEffect } from "react";
import { Viewer } from "photo-sphere-viewer";
import "../node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.css";

export default () => {
  const sphereElementRef = React.createRef();

  useEffect(() => {
    const spherePlayerInstance = new Viewer({
      container: sphereElementRef.current,
      panorama:
        "https://upload.wikimedia.org/wikipedia/commons/f/f0/Colonia_Ulpia_Traiana_-_Rekonstruktion_r%C3%B6mischer_Schiffe-0010560.jpg",
      navbar: [],
      size: { width: "240px" }
    });

    // unmount component instructions
    return () => {
      spherePlayerInstance.destroy();
    };
  }, []); // will only be called when the src prop gets updated

  return <div ref={sphereElementRef} />;
};
```

**Comment by mistic100** [comment]
This is a question for the NextJS/React community.

Regarding the height I don't understand your problem.... You don't provide a height value !

**Comment by mistic100** [comment]
By the way you probably won't be able to show a panorama hosted on wikipedia, there is a thing called Cross Origin Ressource Sharing that will prevent to manipulate images stored on another server, unless the necessary HTTP headers are set by wikipedia itself.

**Comment by tap2k** [comment]
Sorry, in my other example I have set the height. Also, I am able to access the images from wikipedia, I just neglected to include here.
