### ISSUE TITLE
Bug sur IE11

### ISSUE THREAD

**Issue by AdrienPoupa** [mistic100/Photo-Sphere-Viewer#77]
Bonjour,

Vu que tu es français, je me permets de ne pas rédiger ce ticket en anglais :)

Sur IE11, j'ai un problème quand je veux ajouter un diaporama: l'interface se charge mais pas l'image. Dans la console:

SCRIPT5007: Impossible d’obtenir la propriété  « add » d’une référence null ou non définie

Ligne 3970:

`container.querySelector('svg').classList.add('psv-button-svg');`

ça fonctionne avec:

```
if (container.querySelector('svg').classList) {
                container.querySelector('svg').classList.add('psv-button-svg');
            }
```

RàS sur Chrome et Firefox. Une idée du pourquoi du comment?

Merci d'avance :)

**Comment by mistic100** [comment]
classList est censé être supporté par IE11

est-ce que vous n'êtes pas en mode de compatibilité ?

**Comment by mistic100** [comment]
Non d'accord IE11 ne gère pas classList sur les SVG, c'est vraiment un navigateur pourri ce truc.

**Comment by AdrienPoupa** [comment]
Je n'ai pas dit le contraire! Malheureusement il est encore utilisé... merci pour la réponse en tout cas. Mon fix fait cependant fonctionner le script.

**Comment by AdrienPoupa** [comment]
Non, le commit n'est pas bon désolé...

SCRIPT5045: Affectation aux propriétés en lecture seule non autorisée en mode strict

**Comment by mistic100** [comment]
Après IE11 à  moitié implémenté on à la spec JS complètement idiote.
Là c'est mieux ?

**Comment by AdrienPoupa** [comment]
👍
