### ISSUE TITLE
Virtual tour map

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#772]
Study the possibility of displaying an interactive 2D map integrated with the virtual tour.

Exemple :
![map](https://user-images.githubusercontent.com/41597/196042827-d946b39f-9053-40b9-a669-e86a7c845aa5.PNG)

**Comment by haldo98** [comment]
well... maybe not only for virtual tour...

like a topographic map (custom uploaded or from a site that provides such service - like https://map.geo.admin.ch/  ) and centered in the longitude latitude data of the panorama. 
It would be very small and perhaps not so usable. But maybe it could be opened with a click

just a thought

**Comment by mistic100** [comment]
@haldo98 you can already use the `description` parameter to display complex HTML in the side panel, like a Google Maps (or what ever) iframe, an image, etc. 

Demo https://photo-sphere-viewer.js.org/demos/basic/2-description.html

I think this cover most basic usages.

**Comment by haldo98** [comment]
yes. I already use that to show some html.  But it's static.

What I meant was that...  some image (like the topographic map for instance) rotates with the rotation of the pano following the orientation.

That is the use I think You want to achieve with the example you have showm.
The 2d image of the layout of the apartment will rotate with the rotation of the pano image.

**Comment by mistic100** [comment]
ok I understand, if I implement this feature I will try to make it a standalone plugin that can work without the virtual tour, or an update of the compass...

**Comment by mistic100** [comment]
Work in progress

![map](https://user-images.githubusercontent.com/41597/211911492-fca865a5-5b20-413c-8513-11471dd24626.PNG)

**Comment by mistic100** [comment]
First preview version is available : #830
