### ISSUE TITLE
When I use the setPanorama method, the memory increases

### ISSUE THREAD

**Issue by tanghx** [mistic100/Photo-Sphere-Viewer#774]
In my application, I use the setPanorama method to switch scenes. Each time you switch scenarios, memory increases. When memory grows enough, the page reloads. How should this problem be solved

**Comment by mistic100** [comment]
Try one of these two solutions :

- before creating the viewer, completely disable the cache 
```js
THREE.Cache.enabled = false;
```

- every few change of panorama, clear the cache
```js
THREE.Cache.clear();
```

**Comment by tanghx** [comment]
Thank you for your reply. I tried it, but it didn't work out very well. Memory will still grow

**Comment by mistic100** [comment]
Please provide an online demo.

**Comment by tanghx** [comment]
[https://bjvrh5.metamer.cn/#/panorama?id=5&name=%25E5%258D%258E%25E7%2586%2599%25E4%25BA%2594%25E6%25A3%25B5%25E6%259D%25BE](demo)
If I switch scenes quickly and frequently, the memory footprint keeps increasing. If I pause for a moment every time I switch between scenes, the memory will go down a little bit.
It looks like threejs clearing the cache should work

**Comment by tanghx** [comment]
If I switch scenes quickly and frequently, the memory footprint keeps increasing. If I pause for a moment every time I switch between scenes, the memory will go down a little bit.
It looks like clearing the cache worked.
I tried, and now the problem of page reloading does not occur under the non-extreme operation.thank you!
