### ISSUE TITLE
Moving the picture and call viewer.destory(), it will pop up error

### ISSUE THREAD

**Issue by xuchong26** [mistic100/Photo-Sphere-Viewer#777]
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'animationPromise')
    at EventsHandler.js:627:35

**Comment by mistic100** [comment]
not enough information, please read the [issue guidelines](https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/.github/ISSUE_TEMPLATE.md)
