### ISSUE TITLE
How to combine the video and markersplugin

### ISSUE THREAD

**Issue by f3k-tech** [mistic100/Photo-Sphere-Viewer#780]
Dear Mistic100 or reader,

Do you have an example of how to combine the markers plugin with the video plugin? I can use them individually but when combining I get this error: 
```
message: 'Un undefined value was given for plugins.'
```
I have made an example in codepen: https://codepen.io/electronics-amaze/pen/abKmeMd

Thank you very much!
Kind regards,
Freek

**Comment by mistic100** [comment]
The error is clear : you provided ''undefined" as a plugin. Because you forgot to inclide `markers.js` and `markers.css`.

**Comment by f3k-tech** [comment]
Wow thanks! That was such a rookie mistake... Sorry for wasting your time!
