### ISSUE TITLE
Gallery overlaps menu

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#782]
On small screens, open the menu, then the gallery. One can click on the menu button again but it opens under the gallery. And there is not way to close the gallery without changing panorama.

**Comment by DevGabrielDeSouza** [comment]
I'm also having problems with the gallery. It's not showing up at all for me.

**Comment by mistic100** [comment]
@DevGabrielDeSouza Please create a new issue with a test case.
