### ISSUE TITLE
Can't zoom page on mobile (outside viewer)

### ISSUE THREAD

**Issue by sidelux** [mistic100/Photo-Sphere-Viewer#783]
Hello.
I'm using the latest version of library.
This is my js code:
`const viewer = new PhotoSphereViewer.Viewer({
	container: document.querySelector('#wall_viewer'),
	panorama: 'images/IMG_20221113_180732_00_merged.jpg',
	loadingTxt: 'Carico...',
	autorotateDelay: 3000,
	autorotateIdle: true,
	navbar: ['zoom'],
});`

And my html code:
`<div id="wall_viewer" style="width: 100vw; height: 50vh;"></div>`

My problem is that when a user try to pinch (zoom) on a mobile device, zoom does not work. Only works inside the viewer but not in all of the page.

How can be fix this?

Thanks

**Comment by mistic100** [comment]
How is this a problem ? I don't understand why it would zoom if you do not interact with the viewer.

**Comment by sidelux** [comment]
If i try to pinch to zoom in other webpage area it does not zoom as default behavior to a browser when the library is loaded.
Probably is the same problem as described in #592 .

Below a screenshot that shows that in red areas i can't pinch to zoom the webpage with Chrome on iOS.
![img](https://user-images.githubusercontent.com/18572941/202145320-be9ac16f-28b4-4100-aa28-d10294ec89d0.jpg)

**Comment by mistic100** [comment]
Absolutely not the same problem, the forementionned issue is about not being able to zoom on the viewer.

Did you try to only disable the viewer ? (comment the Viewer instanciation but leave everything else as it). If it stil does not work then it is not a problem with PSV.

Perhaps you have a `meta` which prevent page zoom

`<meta name="viewport" 
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">`

**Comment by sidelux** [comment]
If i remove the library the pinch to zoom works well, so i think this is a problem where the library _catch_ the zoom event of all of the page instead of only the specific area.

**Comment by mistic100** [comment]
Thank you for the exact test case, the fix will be released soon.
