### ISSUE TITLE
Marker Plugin zoomLvl

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#785]
PSV 4.8 - Chrome 107

I tried the new zoomLvl feature and it works as expected. Thank You so much.

https://www.tadini.it/temp/panorama_andolla.htm

I noticed some strange behaviour. 

For instance: 

When I click on "pizzo Diei" marker the pano turns in the right direction with the correct zoom level but the marker is not in the center of the screen.

When I click on the "pizzo Pioltone" marker, which is in the vicinity, the pano turns correctly with the right zoom and now the marker is in the center of the screen.

If i click again on "pizzo Diei" marker now the marker is in the center of the screen.

(the same result happens if I click on "pizzo Diei" and after that again another time. The second time pano goes with the marker in the center of the screen)

It seems that when the difference between the zoom level is high there's something with the positioning of the marker in the center of the screen.

Hope it helps

**Comment by mistic100** [comment]
This is caused by the VisibleRangePlugin. I cannot just disable it during the animation because it will cause overshoot for example for "Pizzo d'Andolla" which is very close to the edge.

No solution yet.

**Comment by haldo98** [comment]
yes.. I added zoomLvl (50) for "Pizzo Andolla" marker and the outcome is strange....  (with the first click)

With the second click it shows correctly.
