### ISSUE TITLE
gotoMarker problem

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#786]
PSV 4.8 Chrome 107

I tried to implement the gotoMarker method to smooth the transition between markers

https://www.tadini.it/temp/panorama_a.htm

I use this code:

                 var markersPlugin = viewer.getPlugin(PhotoSphereViewer.MarkersPlugin);

                 markersPlugin.gotoMarker('3', 3500)
                    .then(/* animation complete */);

but I get the error:        PSVError: cannot find marker "3"

Needless to say that the marker "3" does exist.

Am I doing something wrong?

**Comment by mistic100** [comment]
You are calling the method too soon, you need to wait for viewer initialization.  
this is explained here https://photo-sphere-viewer.js.org/guide/methods.html#presentation

```js
viewer.once('ready', () => {
    markersPlugin.gotoMarker('3', 3500)
                .then(/* animation complete */);
});
```

**Comment by haldo98** [comment]
Thank You so much!!!!!!
