### ISSUE TITLE
How to navigate between 2 videos panorama?

### ISSUE THREAD

**Issue by mkubdev** [mistic100/Photo-Sphere-Viewer#789]
Hello, using the latest version of PSV, I'm asking how can we navigate between 2 video panoramas.

The `setPanorama` method isn't available for `EquirectangularVideoAdapter`. Is it possible to extend it in some way?
Do i need to destroy the instance and redraw it?

Best regards,

**Comment by mistic100** [comment]
call `setPanorama` on the viewer.

**Comment by mkubdev** [comment]
> call `setPanorama` on the viewer.

Yes, that's what i'm using, your exemples are very well done so never i struggling to use any API functions (thanks again for this lib), but with the `EquirectangularVideoAdapter`, once i call `setPanorama` it throw the following error:
```error
PSVError: Invalid panorama configuration, are you using the right adapter?
```
Then, i checked the API docs for [`EquirectangularVideoAdapter`](https://photo-sphere-viewer.js.org/api/psv.adapters.equirectangularadapter) and [`AbstractAdapter`](https://photo-sphere-viewer.js.org/api/psv.adapters.abstractadapter), and it look like the method `setPanorama` isn't listed.

Am i right?

**Comment by mistic100** [comment]
```js
viewer.setPanorama({ source: '/london_hd.mp4' })
```

this is exactly like the `panorama` base option

explained here https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-video.html#panorama-options

**Comment by mkubdev** [comment]
Dam. Thanks Damien. ✨ I can't believe i'm misusing the lib since i'm calling this method everywhere the **same** way you shared above....

Sorry to bother you,
Have a great day, and happy week-end!
