### ISSUE TITLE
Gyroscope support not functioning 

### ISSUE THREAD

**Issue by kunalm** [mistic100/Photo-Sphere-Viewer#79]
As per the documentation I have included [DeviceOrientationControls.js](https://github.com/mrdoob/three.js/blob/master/examples/js/controls/DeviceOrientationControls.js) but still the Gyroscope support doesn't seem to work. The viewer is suppose to move left/right or up/down based on the device's gyroscope tilt, right?

or do I need to add additional code to get this working? Kindly help.

Thanks.

**Comment by mistic100** [comment]
You need to set "gyroscope" to true http://photo-sphere-viewer.js.org/#options

It will add a new toolbar button if the device supports the orientation API, and you will have to tap on it.

**Comment by kunalm** [comment]
I did set "gyroscope" to true, but the toolbar is set to false. So is there anyway I can use this feature like if user tilts the phone to left the viewer will rotate left and so on?

**Comment by mistic100** [comment]
Use the methods to enable the gyroscope yourself http://photo-sphere-viewer.js.org/#methods

You will have to use a timeout :

```js
setTimeout(function() {
  PSV.startGyroscopeControl();
}, 2000);
```

As I keep repeating : everything is in the doc !!!

**Comment by kunalm** [comment]
Sorry forgot to mention. I already tried that in the "ready" event. Like this:
`viewer.on('ready', function() {
  PSV.startGyroscopeControl();
});`

Then tried to tilt the phone left/right and nothing happened but touch rotate works.

**Comment by mistic100** [comment]
`viewer` and `PSV` ?? there is a problem here.

If you want further help, but your code online somewhere I can test with my phone.

**Comment by kunalm** [comment]
No I copied the code from your doc mine is different. No issues there. Checked already. Will create a codepen and update here.

**Comment by mistic100** [comment]
The problem is the following : there is no reliable way to know if the device supports the orientation API, so the lib just wait the first orientation event with coherent data to enable the gyroscope support.

The listener is added on init, so you need to wait _a bit more_ before enabling the gyro:

```js
PSV.on('ready', function() {
  setTimeout(function() {
    PSV.startGyroscopeControl();
  }, 1000);
});
```

**Comment by kunalm** [comment]
Thanks, will try this and let you know. Appreciate your help.

**Comment by kunalm** [comment]
​Awesome! gyroscope seems to be working now. Great work!

Only problem is vertical movement also works whereas latitude_range is set to [0,0]. Any possible fix for this?​

**Comment by kunalm** [comment]
Any possible workaround using the following?

`viewer.on('position-updated', function(position) {
  // position has longitude and latitude
});`

**Comment by mistic100** [comment]
You can't lock anything using the gyroscope.

**Comment by kunalm** [comment]
Ok, got it. Possible for the photo map to be both gyroscope and scrollable via click and drag?

**Comment by mistic100** [comment]
No, not together.

**Comment by kunalm** [comment]
The gyroscope is working but the marker added is not clickable anymore on mobile. Did you try this?

**Comment by mistic100** [comment]
#67

**Comment by kunalm** [comment]
Oh ok, thanks! How do I apply this fix to my min.js file? I am using the one from your git repo. Sorry I am new to JS.

**Comment by mistic100** [comment]
Well you don't apply anything to a minified fields to start with.

Checkout the `dev` branch and then everything is explained here https://github.com/mistic100/Photo-Sphere-Viewer#build

**Comment by kunalm** [comment]
Sorry to ask again. But can you please help me with some more details? Like how do I get your latest dev files to my local pc?

**Comment by mistic100** [comment]
You don't know git either ? If not sorry but I don't have time for that.

**Comment by kunalm** [comment]
Yup I know git but haven't used grunt before so not sure how that will help actually. Sorry.

**Comment by mistic100** [comment]
Really I don't know what I can do for you... you want all the exact commands ?

```bash
$ git clone git@github.com:mistic100/Photo-Sphere-Viewer.git
$ cd Photo-Sphere-Viewer
$ git checkout dev
$ apt-get install nodejs-legacy npm
$ apt-get install ruby-dev
$ npm install -g grunt-cli
$ npm install -g bower
$ gem install sass
$ npm install
$ bower install
$ grunt
```

Here, exactly what I said above

**Comment by kunalm** [comment]
Thanks for your time. Will try this and let you know. Sorry to bother you again and again.

**Comment by tunnelduck** [comment]
I wanted to enable gyroscopic control immediately if the device supported it. After looking at PSVNavBarGyroscopeButton.js decides to show the gyro button is shown I came up with the following that appears to work well. Would be nice to have a PSV event, perhaps I'll code one up later and submit pr.

`PSV.on('ready', function() {
  PhotoSphereViewer.SYSTEM.deviceOrientationSupported.promise.then(function() {
    PSV.startGyroscopeControl();
  });
});`

**Comment by mistic100** [comment]
Good idea, you can name it `gyroscope-available`
