### ISSUE TITLE
button svg render error

### ISSUE THREAD

**Issue by heoyongun** [mistic100/Photo-Sphere-Viewer#791]
use vue3 quasar framework 
use es import 
package json  > "photo-sphere-viewer": "^4.8.0"

code
![스크린샷, 2022-12-06 11-46-27](https://user-images.githubusercontent.com/6076067/205796678-9ca2a9cc-1618-4857-ab2a-6ad450cf6199.png)

render
![스크린샷, 2022-12-06 11-33-24](https://user-images.githubusercontent.com/6076067/205796727-9aa749b3-3b55-4b00-9420-65bb57306c1b.png)

navbar visible false
![스크린샷, 2022-12-06 11-46-15](https://user-images.githubusercontent.com/6076067/205855916-cb882364-ee6e-45a7-b68d-bdb28e248937.png)

render
![스크린샷, 2022-12-06 11-38-46](https://user-images.githubusercontent.com/6076067/205796842-af58cc1c-2a96-4fb8-b39e-2abe8007f0d3.png)

**Comment by mistic100** [comment]
Did you imported the stylesheet ?

https://photo-sphere-viewer.js.org/guide/#your-first-viewer

**Comment by heoyongun** [comment]
thank you. 
work for me.
