### ISSUE TITLE
VisibleRangePlugin Demo Example Error

### ISSUE THREAD

**Issue by heoyongun** [mistic100/Photo-Sphere-Viewer#792]
https://photo-sphere-viewer.js.org/plugins/plugin-visible-range.html#example

![스크린샷, 2022-12-09 16-24-47](https://user-images.githubusercontent.com/6076067/206647802-3df23a07-b8b7-4836-b375-7a170d0c7328.png)

**Issues guidelines**
- Speak English or French.
- Indicate your Photo-Sphere-Viewer, three.js and web browser versions.
- Search in the [documentation](http://photo-sphere-viewer.js.org) before asking.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc.
- Any issue without enough details won't get any answer and will be closed.

**Comment by mistic100** [comment]
It works for me, try to reload.
