### ISSUE TITLE
MarkersPlugin - gotoMarker on polygons with coordinates spanning over 0 longitude centers incorrectly

### ISSUE THREAD

**Issue by blacj** [mistic100/Photo-Sphere-Viewer#794]
[JSFiddle Example](https://jsfiddle.net/bLyh90xe/)

`select-marker` event calls `gotoMarker(marker)` which centers the viewer on the opposite longitude value.

This appears to be happening because the lat/lng of the points are averaged to find the center point for the marker. The marker in the example spans over the 0 longitude line, and as a result the average longitude is incorrect. For example averaging longitudes 6.1 and 0.1 will result in 3.1 and send the viewer to the opposite longitude of the true center point in the marker. 

photo-sphere-viewer 4.8.1
three.js r147
Chrome Version 107.0.5304.123

**Comment by mistic100** [comment]
https://github.com/mistic100/photo-sphere-viewer5/commit/d7ec8b178caff50aafe6367e2bbadea3f1f31961

(this repository will be merged here on v5 release)
