### ISSUE TITLE
New events usage

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#799]
### Describe your problem

I tried to migrate to v5 and it seems that everything works fine. 

I struggled a little with the new event but eventually everything works as before with v4.8.

I have a question though:

I use the "doubleClick" but when I click on the "pizzo Pioltone" marker that is the number '4' the page loads even with a single click.

Here's my code

```
var markersPlugin = viewer.getPlugin(PhotoSphereViewer.MarkersPlugin);

markersPlugin.addEventListener('select-marker', ({ marker, doubleClick }) => {
  if (marker.id === '4') {
    window.location.href = 'https://www.tadini.it/panorama/pioltone/panorama_pioltone.htm';
  }
  });
```

### Online demo URL

https://www.tadini.it/panorama/andolla/panorama_andolla.html

### Photo Sphere Viewer version

5.0

### Plugins loaded

autorotate, compass, markers, visible-range

**Comment by mistic100** [comment]
You do not use the `doubleClick` variable at all, you must update your `if` condition

**Comment by haldo98** [comment]
I had (with v4.8)

markersPlugin.on('select-marker', function(e, marker, data) {
  if (data.dblclick && marker.id === '4') 

but I don't know what to replace with data.dblclick

sorry

**Comment by mistic100** [comment]
replace it with `doubleClick` !

**Comment by haldo98** [comment]
```
markersPlugin.addEventListener('select-marker', ({ marker, doubleClick }) => {
  if (doubleClick && marker.id === '4') {
    window.location.href = 'https://www.tadini.it/panorama/pioltone/panorama_pioltone.htm';
  }
  });
```

now works. Thank You....
