### ISSUE TITLE
removeMarker() -- screen drag

### ISSUE THREAD

**Issue by Davidx7** [mistic100/Photo-Sphere-Viewer#8]
A little bug 

When doing a `refresh` of the markers (to perform different angular actions), grabbing the `PSV.hud.markers` object, iterating and removing all markers, will work, BUT the markers that are in the view point NOW, when remove is performed, will stick to the screen in a `X,Y` coordinates method. 

Easy fix is `.remove()` by ID or class , but just wanted to submit the bug

**Comment by mistic100** [comment]
Not a bug.

There is no data binding inside the lib itself, you are not supposed to alter the storage directly. If you use `removeMarker` method it works as intended.

**Comment by mistic100** [comment]
It's missing an `updateMarker` too

**Comment by mistic100** [comment]
Sorry I made a mistake, even removeMarker does not clean the DOM

**Comment by Davidx7** [comment]
I'm trying to work around the data binding and making that in angular as an overlay for your plugin. 
That way they both have proper integrity
