### ISSUE TITLE
Consider to add the "this" returning value to "addEventListener" func

### ISSUE THREAD

**Issue by Elius94** [mistic100/Photo-Sphere-Viewer#804]
### Describe the feature

Hi!
Migrating to V5 I noticed that now the events are managed in different way, like you wrote in the migratin guide.
Now the event managing method (addEventListener) extended by the viewer class, is not returning the whole instance of the caller class (this).
If it will be possible to add this change, i suppose that it will be useful, because you can write a better code when you concatenate a sequence of event listeners.

### Alternatives you've considered

```js
Viewer
.addEventListener("position-updated", handler)
.addEventListener("zoom-updated", handler)
.addEventListener("click", handler)
```

I don't know how this kind of events works but in some case it should be done by adding a `return this` at the end.

**Comment by mistic100** [comment]
I will stick to the standard which returns nothing https://developer.mozilla.org/docs/Web/API/EventTarget/addEventListener
