### ISSUE TITLE
ViewerEvents type is not exported from the core module

### ISSUE THREAD

**Issue by Elius94** [mistic100/Photo-Sphere-Viewer#805]
### Describe the bug

![image](https://user-images.githubusercontent.com/14907987/208639261-721c3dad-203c-4ed4-bdf1-c6dac88eab5d.png)

Hi, 
I found that ViewerEvents type is not exported by the module. So it's a problem for who is using your lib in Typescript.

### Photo Sphere Viewer version

v5

### three.js version

_

### OS & browser

_

### Additional context

Thanks

**Comment by mistic100** [comment]
Why don't you use the actual event type ? like `events.ClickEvent`

**Comment by Elius94** [comment]
Ok nice, thank you :D
