### ISSUE TITLE
gotoMarkerSpeed irregularities

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#808]
### Describe the bug

I use gotoMarkerSpeed as global configuration for all the markers

```
   [PhotoSphereViewer.MarkersPlugin, {
   gotoMarkerSpeed: '4rpm',
   markers: [
   {
   "id": "1",.................
```
but I noticed that it works correctly not every time.

For instance in the online demo the transition between markers is correcr for all the markers except for "Piz Surgonda"
The configuration for the marker is the same as the others, but it's the only on the opposite side of almost all the others...

So there's a lot of rotation to do. And the rotation is very fast.

Check the online demo. Go to marker "Pizzo Badile" and the "Piz Surgonda"

### Online demo URL

https://www.tadini.it/panorama/grevasalvas/panorama_grevasalvas.htm

### Photo Sphere Viewer version

5.0

### Plugins loaded

autorotate, compass, markers, visible-range

### three.js version

https://cdn.jsdelivr.net/npm/three/build/three.min.js

### OS & browser

win11 - chrome 108

**Comment by mistic100** [comment]
This feature/bug fix has been released in [version 5.0.1](https://github.com/mistic100/Photo-Sphere-Viewer/releases/tag/5.0.1).
