### ISSUE TITLE
Can't resolve '@photo-sphere-viewer/shared'

### ISSUE THREAD

**Issue by Elius94** [mistic100/Photo-Sphere-Viewer#809]
### Describe the bug

Can't resolve '@photo-sphere-viewer/shared'

When I Install one of the adapters, this package doesn't be created in the @photo-sphere-viewer node-modules folder.

Thanks for help. 

### Photo Sphere Viewer version

5.0.0

### OS & browser

Windows 11, Edge

**Comment by mistic100** [comment]
The whole shared package is messed up, this goal was to **include** the content of this package into each plugin/adapter (I prefer that over bloating the core or adding another cross dependency)

The UMD file is ok (though the tree-shaking is broken) but the ES file does not contains the shared code at all.

**Comment by mistic100** [comment]
This feature/bug fix has been released in [version 5.0.1](https://github.com/mistic100/Photo-Sphere-Viewer/releases/tag/5.0.1).
