### ISSUE TITLE
Next release.

### ISSUE THREAD

**Issue by TheBox193** [mistic100/Photo-Sphere-Viewer#81]
Just wonder when the next release is planned. Would be great to get npm version updated a bit. 👍

**Comment by mistic100** [comment]
When the milestone is complete https://github.com/mistic100/Photo-Sphere-Viewer/milestone/4
Which mean : I don't know.

**Comment by TheBox193** [comment]
Can you run a `npm publish` to get npm version updated from `3.2.0` to `3.2.2`? Looks like it hasn't be run recently: https://www.npmjs.com/package/photo-sphere-viewer-sa

**Comment by mistic100** [comment]
Don't you see this package is not mine ?
This is the right one https://www.npmjs.com/package/photo-sphere-viewer

**Comment by TheBox193** [comment]
Oh oops. nope didn't see that. Interesting it points to your github repo.

**Comment by mistic100** [comment]
anyone can register anything on NPM, it does not check that you actually are the owner.
