### ISSUE TITLE
React Wrapper Correctly Upgraded to 5.0.0

### ISSUE THREAD

**Issue by Elius94** [mistic100/Photo-Sphere-Viewer#810]
### Describe the feature

Hi Damien!
I've upgraded my Reacr.js Wrapper to the psv-5.0.0!
All readme is updated and I've also closed three issues.
Please, update the docs if you need
Thanks

**Comment by Elius94** [comment]
[NPM](https://www.npmjs.com/package/react-photo-sphere-viewer)
[GitHub](https://github.com/elius94/react-photo-sphere-viewer)

**Comment by mistic100** [comment]
I will remove the "v4" badge. Thank you.
