### ISSUE TITLE
Type error with getPlugin method

### ISSUE THREAD

**Issue by JFGagnon** [mistic100/Photo-Sphere-Viewer#813]
### Describe the bug

First of all, thank you for this library ❤️ 

I'm getting the following TS error when calling the `getPlugin` method. The same error is happening with the `CompassPlugin` as well. I haven't tested with any other plugins

<img width="2014" alt="Screenshot 2022-12-28 at 12 08 40 PM" src="https://user-images.githubusercontent.com/1037108/209847924-555d60bc-105e-462a-a395-04a586143e43.png">

### Photo Sphere Viewer version

5.0.1

### OS & browser

-

**Comment by mistic100** [comment]
Thank you
