### ISSUE TITLE
Custom keyboard action

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#822]
### Describe the feature

https://photo-sphere-viewer.js.org/guide/config.html#keyboard

The keybord action are the ones listed above.
Have you considered a custom action that can be triggered by pressing a key ?

I was thinking about the immersive mode in the fullscreen mode - hiding bar and compass - with, for instance, pressing the "H" key on the keyboard.  Or other custom actions....

**Comment by mistic100** [comment]
I could add to possibility to configure a callback for specific keys in addition to existing constants.

**Comment by mistic100** [comment]
Will be possible in the next version

https://github.com/mistic100/Photo-Sphere-Viewer/blob/11bccff1fcb4c0bfebac2550bac2dcc07111ce7d/examples/equirectangular.html#L107-L119

**Comment by haldo98** [comment]
Great!!!!!
