### ISSUE TITLE
100% height for responsive use on mobile

### ISSUE THREAD

**Issue by AdamMiltonBarker** [mistic100/Photo-Sphere-Viewer#823]
### Describe your problem

Currently, or at least las time I looked, you have to hardcode the height, which makes it awkward for use on mobile responsive sites.  How would you make it so the frame is completely responsive?

### Online demo URL

https://www.innov8digitalmedia.com/portfolio/360-photography-videography/360-photography-portfolio/entry/360-photography-storiel-bangor-north-wales

### Photo Sphere Viewer version

5.0.1

**Comment by mistic100** [comment]
Use vh unit and an "calc" to account for your header/footer/margin etc   
https://developer.mozilla.org/en-US/docs/Web/CSS/length#relative_length_units_based_on_viewport

**Comment by AdamMiltonBarker** [comment]
Doesn't answer the question, did you look at the example?

**Comment by AdamMiltonBarker** [comment]
I worked out how to do it using a custom embed I made ( https://hosted.innov8digitalmedia.com/360/photo/1 ), but without using an iframe this issue is still unresolved.

**Comment by mistic100** [comment]
Then I don't understand the question. No I didn't look at your source code, I don't when it is cluttered inside a complex app.

Provide a complete explanation of what you want.

**Comment by AdamMiltonBarker** [comment]
I wasn't asking you to look at the source code, the simple web page shows the issue if you view on mobile it is not responsive height wise as the height is hard coded. I have resolved this using my own embedding system, but others won't be able to make truly responsive solutions using your code.

**Comment by mistic100** [comment]
Yes I see that but I still don't understand what is your goal, because the vpage as a lot of content. Thats why I proposed `height: 100vh;`. If this does not suit you I need a example, a mockup of what you want.

**Comment by mistic100** [comment]
As the doc says, the viewer as no defined height, it is totally up to the container div.

**Comment by AdamMiltonBarker** [comment]
If you set 100% on the height of the container div the viewer will not show, you have to hard code it the height which results in it being very tall and thin in responsive view. We can close this as I resolved the issue for myself, but I have seen others are still asking for this to be fixed since the original repo.

**Comment by mistic100** [comment]
I feel you don't read my message.... `100vh` is not the same as `100%`

**Comment by AdamMiltonBarker** [comment]
If you did check the example I provided you would see that it would not work using viewport height. 100vh would cover the whole screen.

**Comment by mistic100** [comment]
auto to what ? why do you refuse to explain exactly what behaviour you want ?

**Comment by AdamMiltonBarker** [comment]
CSS height auto? I have explained exactly the situation.

**Comment by mistic100** [comment]
To be able to use `height: auto` the element must have some content to determine what the height is. Here **it is not possible**, the viewer does not have a content, it is the content, so it must have a computable size.

So I will close this discussion has you have a working solution for your specific case.
