### ISSUE TITLE
How to re-show gallery once a gallery item has been selected?

### ISSUE THREAD

**Issue by seanforyou23** [mistic100/Photo-Sphere-Viewer#824]
### Describe your problem

Hi, awesome lib! Been using it for a while, but only now getting into the plugin usage. I'm using a custom navbar config, and when I select a photo from the gallery - the new photo renders as expected - but the gallery items go away. Is there a way I can make my custom gallery button re-show the gallery items?

The stock gallery button works fine if I don't use a custom nav config, but I don't see a way to get around this as I don't want some of the other options it comes with, like download. Maybe there is a way to remove unwanted navbar items like that?

Ultimately on my way to making use of the tour feature, but I ran into quite a few bumps so am trying to settle for basic gallery usage for an incremental step. Any advice is appreciated. Thank you!

### Online demo URL

http://dev-csms.surge.sh/locations/raleigh

### Photo Sphere Viewer version

5.0.1

### Plugins loaded

Gallery

### Additional context

Using [Patternfly React Seed](https://github.com/patternfly/patternfly-react-seed) as build system (similar to CRA) - on webpack 5 and react 17.

**Comment by mistic100** [comment]
Add the 'gallery' button to your navbar

Buttons section of the plugin documentation https://photo-sphere-viewer.js.org/plugins/gallery.html#buttons

**Comment by seanforyou23** [comment]
Ah, that was it! Had a good chuckle for missing that one, makes sense now :) thanks for the quick response!
