### ISSUE TITLE
toggleFullscreen

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#827]
### Describe your problem

Hi Damien, Thank You for your great work.

I was playing with the new custom keyboard options...
and I defined a key (among the others) for toggling on/off the fullscreen mode

`    'f': (viewer) =>  
          viewer.toggleFullscreen(),
`

But it seems to work only one time. After toggling fullscreen mode on and then off   ... all the other keys I defined (fullscreen included) stop working.

Am I doing something wrong or maybe there's an issue....   

because if I manually hit the fullscreen button on the navbar (fullscreen ON) the other keys work again.

check the demo.

### Online demo URL

https://www.tadini.it/photosphere/andolla/PS_andolla.html

### Photo Sphere Viewer version

5.0.2

### Plugins loaded

autorotate compass

**Comment by mistic100** [comment]
The keyboard control is designed **only** for fullscreen use. You force enable it with `viewer.startKeyboardControl()` but once fullscreen is disabled, so is the keyboard.

https://github.com/mistic100/Photo-Sphere-Viewer/blob/50e4aeb8014963bcf6d5eb929161dbec3e53afa6/packages/core/src/services/EventsHandler.ts#L378-L393

And it is was the doc says https://photo-sphere-viewer.js.org/guide/config.html#advanced-options

---

If you want a global keyboard listener, do it yourself

```js
window.addEventListener('keydown', (event) => {
  console.log(event.key);
}, { passive: false });
```

**Comment by mistic100** [comment]
I will add an option to choose if the keyboard is only enabled in fullscreen or always.

**Comment by haldo98** [comment]
> I will add an option to choose if the keyboard is only enabled in fullscreen or always.

well that will solve it.
Thank You.

**Comment by mistic100** [comment]
https://github.com/mistic100/Photo-Sphere-Viewer/blob/9b4d3003bd26bd922ad7390d1250b1ae81dd962a/examples/equirectangular.html#L107-L121

will have to wait for the next minor version because it can break some configs (though general retrocompatibility should work)
