### ISSUE TITLE
imageLayer type marker,  removeMarker not work 

### ISSUE THREAD

**Issue by heoyongun** [mistic100/Photo-Sphere-Viewer#828]
### Describe the bug

![1](https://user-images.githubusercontent.com/6076067/211614881-cc3ba51b-c09a-4bbf-99cd-26c1bab93c5f.jpg)
1. add markers image and imageLayer

![2](https://user-images.githubusercontent.com/6076067/211615169-c6113e64-7815-4dfb-b8ac-1734fd8abc92.jpg)
2. image type marker, call removeMarker method is work, and then viewer render is ok

![3](https://user-images.githubusercontent.com/6076067/211615162-d7dc52a9-8cdd-4d37-ac90-065091af9c7c.jpg)
3. imageLayer type marker, call removeMarker method  is work, and then viewer render is fail  

![4](https://user-images.githubusercontent.com/6076067/211615578-d0e3b803-6e5a-41c3-a314-48af149f7dfd.png)
this is removeMarker method 

removeMarker call is success, no error message, but viewer inside 'imageLayer'  maker is not remove.

### Photo Sphere Viewer version

4.8.1

### Plugins loaded

MarkersPlugin

### OS & browser

ubuntu 22.04 and  chrome

**Comment by mistic100** [comment]
I don't reproduce the problem, nor on the playground https://photo-sphere-viewer.js.org/playground.html nor on the examples.

Provide an online demo iyou want this to be investigated.

**Comment by mistic100** [comment]
I don't reproduce in version 5. If this is exclusive to version 4 I will not fix it.

**Comment by heoyongun** [comment]
ok I will switch to v5.
