### ISSUE TITLE
Full screen does not work in Chrome (desktop and mobile)

### ISSUE THREAD

**Issue by icexuick** [mistic100/Photo-Sphere-Viewer#83]
The preview/sample on http://photo-sphere-viewer.js.org/ does noet work fullscreen on the latest Chrome (dekstop & mobile) versions. 

You get a black screen.

Firefox and IE Edge however do work in fullscreen.

**Comment by mistic100** [comment]
Reverted the problematic commit, see my comment on the other issue.

**Comment by mistic100** [comment]
Release 3.2.3 includes the fix. sorry for the delay.
