### ISSUE TITLE
Can't properly resize the Viewer, problems with Navbar

### ISSUE THREAD

**Issue by PeytonHanel** [mistic100/Photo-Sphere-Viewer#836]
### Describe your problem

Hi,

I'm not sure if this is a bug, my fault, or a problem with the framework I'm using. I'm using Sveltekit and have imported your code as such:

```
<script lang='ts'>
  import { InfoPageHeader } from '$components'
  import {Viewer} from '@photo-sphere-viewer/core'
  import { onMount } from 'svelte'
  import Tour from '$assets/3d.jpg'

  let virtualTour: HTMLElement

  onMount(() => {

    const viewer = new Viewer({
      container: virtualTour,
      panorama: Tour,
    })
  })
</script>

<svelte:head>
    <!-- for optimal display on high DPI devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</svelte:head>

<InfoPageHeader class="" title="THE SHOP" titleFont={280} />

<div bind:this={virtualTour} style='width: 1000px; height: 1000px;'></div>
```

My `Tour` image is a full 3D photo I made using my Google phone which I downloaded from Google Photos, and it works properly in your playground. But in my project using the above code it produces a very tall rectangle that stretches a mile down the page, as seen in this photo:

![image](https://user-images.githubusercontent.com/26446761/213789229-783f916e-cba1-4a12-8e33-a038adf62be2.png)

Now when I change my code so that I define the viewer with a navbar as such:

```
const viewer = new Viewer({
      container: virtualTour,
      panorama: Tour,
      navbar: [
      ]
    })
```
I get these results, which looks normal but it won't actually allow me to resize the height at all, so it's always very thin.

![image](https://user-images.githubusercontent.com/26446761/213789907-3733d52c-29e8-428e-86cf-7340fae26cc8.png)

When I define navbar buttons, they are HUGE and flow all the way to the bottom of the screen. I'm really not sure what's going on here.

And when I simply copy your `direct import` code from your [guide](https://photo-sphere-viewer.js.org/guide/#your-first-viewer) and replace the path to the panorama with my image path, it doesn't load anything.

Please help me :smile: Thank you.

### Photo Sphere Viewer version

5.0.2

### Plugins loaded

N/A

**Comment by mistic100** [comment]
I think you just forgot to import the stylesheet

**Comment by PeytonHanel** [comment]
@mistic100  So I'm not using SCSS, how would I go about importing it into my global css file?

**Comment by mistic100** [comment]
The package provide a CSS file, it is indicated in the guide.

I don't know your framework so I don't know how you are supposed to import it.

**Comment by PeytonHanel** [comment]
Thank you for your help, the way I solved this was by adding this to `app.css`: 
```
@import '/node_modules/@photo-sphere-viewer/core/index.css';
```
