### ISSUE TITLE
Map plugin - rotation not fluid with smartphones

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#844]
### Describe your problem

I'm adding the map plugin to all the panos I have published and I noticed that with smartphones (Xiaomi MI 11 - Android 13)
the movement is not as smooth as the same pano without the map plugin.  

It goes jerkily and not fluid and smooth.

At first I thought the map images were too heavy (6 Mb each) 
I use two maps because i have a button to switch between them (topo and google earth)

But then I reduced the size to 2.5 Mb each and the effect is the same....   still not fluid...

This the pano without map plugin

https://www.tadini.it/panorama/Sass%20Da%20Le%20Undesc/panorama_Sass%20Da%20Le%20Undesc.htm

this with map plugin:

https://www.tadini.it/panorama/Sass%20Da%20Le%20Undesc/panorama_Sass%20Da%20Le%20Undesc.html

Is 2.5 mb (x2)   still too much?

### Online demo URL

https://www.tadini.it/panorama/Sass%20Da%20Le%20Undesc/panorama_Sass%20Da%20Le%20Undesc.html

### Photo Sphere Viewer version

5.1.0

### Plugins loaded

map

**Comment by mistic100** [comment]
The size of the map definitely has an incidence. But it shouldn't be that slow. In term of complexity, the paint of the map is much much simplier that the viewer itself.

In Chrome performance monitor I can see that each frame spend 100ms in "Image decode", I don't really know what it is. The map image is not reloaded on each frame of course.  
My rough guess is that for some reason the map canvas is not rendered by the GPU.

Stay tuned.

**Comment by haldo98** [comment]
if You wanna further investigate....

this one works smoothly
https://www.tadini.it/temp/panorama_colombe.htm

even if it has the same configuration and also the map sizes are larger and the pano image is larger.
(so maybe the sizes in Mb are not an issue)

Hope it helps

**Comment by mistic100** [comment]
I made some tests and the performance issue happens when the texture is bigger than than the maximum canvas width (generally 4096 pixels on handled devices, 8192 on desktop). That makes sense, the sphere image itself also have to be resized. So I will handle this case in the plugin and automatically downscale large maps.
