### ISSUE TITLE
Support for Leaflet.js (or OpenStreetMap) on Map plugin

### ISSUE THREAD

**Issue by alexsaleh** [mistic100/Photo-Sphere-Viewer#845]
### Describe the feature

It would be amazing to have the Map Plugin support having a dynamic [Leaflet](https://leafletjs.com) map instead of a static image. 
This would allow the user to also interact with the map in order to change the panorama image using events.

### Alternatives you've considered

Currently I'm overlaying a map on top of photo-sphere-viewer.

**Comment by mistic100** [comment]
I will leave this issue open for reference but will probably never do it my self. The complexity and diversity of GIS is not something I want to dive into (I already have to do some maintenance on Open Layers at work and I don't like it).

Someone else probably can [create another plugin](https://photo-sphere-viewer.js.org/plugins/writing-a-plugin.html)

**Comment by mistic100** [comment]
Preview of the new plugin "plan" (because "map" is already taken) using Leaflet

![Screenshot 2024-01-21 at 20-11-58 PhotoSphereViewer - plan demo](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41597/7bd4faef-600e-497a-9f1f-af892b8349d1)

disclaimer : no availability date, it's done when it's done :)

**Comment by mistic100** [comment]
The plan is now working with the virtual tour (and if you are being fancy you can use the plan and the map together... but why ?)

![plan](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41597/5f2fb427-0c90-408b-acd0-d3ff9f82a6a7)

**Comment by mistic100** [comment]
The plugin is available for testing in version 5.7.0-alpha.1

doc : https://photo-sphere-viewer.js.org/plugins/plan.html  
example : https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/examples/plugin-plan.html

**Comment by mistic100** [comment]
That's a problem with the UMD package, I will fox it. But anyway you should switch to ES modules. ThreeJS will remove non ESM builds shortly, as visible in the console

> Scripts "build/three.js" and "build/three.min.js" are deprecated with r150+, and will be removed with r160.

The installation guide now uses ESM https://photo-sphere-viewer.js.org/guide/#your-first-viewer

**Comment by haldo98** [comment]
switched the same page to ESM

https://www.tadini.it/temp/Panorama_Test_Plan.html

but the rendering of the OpenStreetMap is weird and not complete...

The console says   A form field element should have an id or name attribute

**Comment by mistic100** [comment]
You are missing leaflet CSS.

https://leafletjs.com/examples/quick-start/
