### ISSUE TITLE
Transition Options

### ISSUE THREAD

**Issue by jstruthers** [mistic100/Photo-Sphere-Viewer#85]
Hi, thanks so much for this robust library. I've been tinkering with it, and I love the flexibility it offers. I was wondering if you thought to introduce options for transitions.

I'm trying to adapt this to a virtual house tour widget, and I was poking around in  the `PhotoSphereViewer.prototype._transition` method, which seems to hold the brunt of the code for the fade/zoom transition between panoramas. I was going to try to implement something a bit more subtle, like [this example over at three.js](PhotoSphereViewer.prototype._transition), but I don't have any experience with three.js.

Just wondering if you had any plans on fleshing out transitions, or if you had any advice from your experience writing this code.

If not, cheers anyway, and thanks again for this!

**Comment by mistic100** [comment]
Your link is broken.

I'm not happy with the current transition effect, I want to implement something cleaner and without the shader (which is very resource consuming).
But it will never be configurable (too much hassle)

**Comment by jstruthers** [comment]
Sorry, [this should work](https://threejs.org/examples/webgl_postprocessing_crossfade.html).

Thanks for the response. Yeah, I figured that was the case.

**Comment by mistic100** [comment]
For now I removed all effects on the transition but opacity.

I have a few ideas to mimic what Google Streets View does.
