### ISSUE TITLE
Fullscreen not working on WebKit Browsers (Safari MacOS, iPadOS)

### ISSUE THREAD

**Issue by ceage** [mistic100/Photo-Sphere-Viewer#850]
### Describe the bug

I’ve noticed that with v5 I can no longer enter fullscreen on Safari on MacOS or iPadOS. This was working in versions v4 and lower before.

Error information is

```
TypeError: this.container.requestFullscreen is not a function. (In 'this.container.requestFullscreen()', 'this.container.requestFullscreen' is undefined)
[f] enterFullscreen - Viewer.ts:729
[f] toggleFullscreen - Viewer.ts:747
[E] onClick - FullscreenButton.ts:35
[f] (anonyme Funktion) - AbstractButton.ts:124
```

No issues for Firefox or Chrome/Edge, though. Could it be that there’s still a prefix needed for WebKit browsers as indicated here:[https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen?retiredLocale=de](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen?retiredLocale=de)?

### Photo Sphere Viewer version

5.1.0

### OS & browser

Safari on MacOS 13.2 and iPadOS 16.3

**Comment by mistic100** [comment]
Safari is seriously the new Internet Explorer ! the only browser not supporting standard API.

I will re-add the fallbacks with "webkit" prefix but won't be able to test.
