### ISSUE TITLE
mapPlugin.hide() mapPlugin.show()   small issue

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#851]
### Describe the bug

Just a minuscule thing...

I use a custom key to toogle some immersive mode

 ```
   'm': (viewer) => { 
       if (viewer.isFullscreenEnabled()) { 
          viewer.navbar.show();
          compassPlugin.show();
          mapPlugin.show(); 
          mapPlugin.open();
          viewer.toggleFullscreen();
          } else { 
          viewer.navbar.hide(); 
          compassPlugin.hide();
          viewer.panel.hide();
          mapPlugin.minimize();
          mapPlugin.close();
          mapPlugin.hide();
          viewer.toggleFullscreen();
          } 
    },
```
When the map is maximized and I hit the "m" key...  map closes,  navbar, compass and map hides and the viewer goes fullscreen as expected.

When I hit again the "m" key the viewer exits fullscreen,  compass and bar appears but the map does not have the `overlayImage`

This happens only if the map is maximized and only with `mapPlugin.hide()` and `mapPlugin.show()`  if I remove those two lines the overlayImage is shown correctly.

### Online demo URL

https://www.tadini.it/temp/panorama_colombe.htm

### Photo Sphere Viewer version

5.1.1

### Plugins loaded

map

### OS & browser

win 11 - chrome 109

**Comment by mistic100** [comment]
Fixed.

By the way you don't need to call "close" and "open", it is enough to call "minimize"+"hide" and "show"
