### ISSUE TITLE
Manual set virtual tour 3D arrows (links)

### ISSUE THREAD

**Issue by yuan116** [mistic100/Photo-Sphere-Viewer#855]
### Question:
Is there a function to call for manual set the 3D arrows (links) in virtual tour plugin instead of passing everything at **intializing viewer** or **`setNodes()`**?

### Reason for manual set arrows (links):
I dont want to use default animation used by virtual tour plugin.
As I currently created a custom animation for navigation from panorama A to panorama B

I noticed there is a private function **`__renderLinks`** from **`getPlugin(VirtualTourPlugin)`** to render links, should i use this function?

### Online demo URL

https://yuan116.gitlab.io/demo-photosphere/

### Photo Sphere Viewer version

5.1.1

### Plugins loaded

CubemapTilesAdapter, GyroscopePlugin, StereoPlugin, MarkersPlugin, VirtualTourPlugin

**Comment by mistic100** [comment]
No, the plugin needs the whole configuration of the node to configure everything.

I don't understand how manually setting the links would allow to change the transition animation, the plugin would still call the standard `setPanorama()`  method.

---

So the real question is : how to change the default transition animation?

This is not possible, if you show me what you current animation looks like and how it is implemented, I could see if the necessary config and events can be added in the core.

**Comment by yuan116** [comment]
Sorry for the confuse, there are changes done after i created this question (issue)

The question is: How could I manual set/render 3D arrows without passing everything in **`VirtualTourPlugin constructor`** or **`setNodes()`** ?

Reason to manual set/render 3D arrows instead of passing everything in Virtual Tour Plugins:
currently Im working on project which allow user to dynamically add panoramas, and navigations with marker.
there are users setup more than 20 panoramas in 1 single photosphere.
with allowing user dynamically add navigations in panorama.
it can be very tedious work for passing everything (eg: 20 panoramas and 2-4 navigations in each panorama) in **`setNodes()`** while user is only configuring few navigations in current working panorama

---

In the demo, i not using a proper way to set/render 3D arrows and animation
Below are the steps
1. Im using predefined panoramas and markers
2. add necessary event listener (click), and remove VirtualTourPlugin click event listener
3. after load/render panorama, then set markers
4. get all markers, then remove rendered markers
    reason for get all markers: afaik there are no helpers or utils available to get a center position of `polygon` marker
    so i have render and get the marker center position
5. with the previous obtained markers in **step 4**, i set/render 3D arrows by call **`viewer.getPlugin('virtual-tour').__renderLinks({links: [...]})`**, which is not a proper way to render 3D arrows
6. with previous setup event listener (click) in **step 2**, i check each object's userData to match my navigation data
7. if matched
    - rotate viewer to arrow's direction
    - preload panorama
    - show custom animation with `utils.Animation({...})`
    - update panorama (`setPanorama(...)`) while in the midst of animation
    - after finish animation, render 3D arrows (repeat of step 3 and 4)

**Comment by yuan116** [comment]
### Not related to this issue

i noticed **`setOverlay`** from **`CubemapTilesAdapter`** is throwing error `throw new PSVError("EquirectangularTilesAdapter does not support overlay");`
but in version 4, it was extend from CubemapAdapter and not throwing any error

is this a typo or mistake?

**Comment by mistic100** [comment]
I have no acceptable answer for you. I am not willing to expose more internal API regarding 3D arrows.  
I know other softwares which only uses markers while configuring and switch to a proper Virtual Tour when the configuration is complete.

----

It is not a type, CubemapTilesAdapter is indeadd not compatible with overlay.

**Comment by mistic100** [comment]
If you don't want to set the markers only the get the polygon centers, copy the necessary code in your app https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/markers-plugin/src/utils.ts#L45-L55

**Comment by yuan116** [comment]
Ok, and just out of curiosity
May I know what the reason that you are not willing to expose more internal API and export function for getting polygon center?

---

> I could see if the necessary config and events can be added in the core.

For this part, may I know what are the config and events will be add in the future?

**Comment by mistic100** [comment]
Because more public API means more maintenance and retrocompatibility issues.

---

That totally depends on the need, as I said I need to know what **you** need in order to, perhaps, come with an extendable transition system. Your previous description is not enough and your exemple page is minified.

**Comment by yuan116** [comment]
Sorry, been busy recently

here is the code for the demo
[https://gitlab.com/yuan116/demo-photosphere](https://gitlab.com/yuan116/demo-photosphere)

I have update demo to use the virtual tour plugins demo
besides that, I noticed **`CubemapAdapter`** and **`CubemapTilesAdapter`** not able to change `panoData` by passing it as 2nd argument in `setPanorama()`
could you have a check on this?

**Comment by yuan116** [comment]
@mistic100 
Hi, is there any update on the `panoData` parameter on `CubemapAdapter` and `CubemapTilesAdapter`?

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/guide/config.html#panodata

> Only the default [equirectangular](https://photo-sphere-viewer.js.org/guide/adapters/equirectangular.html) adapter and low-resolution panorama of [equirectangular-tiles](https://photo-sphere-viewer.js.org/guide/adapters/equirectangular-tiles.html) supports panoData, for other adapters you can only use [sphereCorrection](https://photo-sphere-viewer.js.org/guide/config.html#spherecorrection) if the tilt/roll/pan needs to be corrected.

**Comment by yuan116** [comment]
ok, thank you so much

you may have a look at the code provided, maybe you would have new idea/feature to be implement
