### ISSUE TITLE
Wish support unofficial Google streetview rectangular tiles

### ISSUE THREAD

**Issue by cijianzy** [mistic100/Photo-Sphere-Viewer#859]
### Describe your problem

Some unofficial streetview width:height is not 2:1, like this [streetview](https://www.google.com/maps/@49.78936,10.6604338,3a,87.8y,149.26h,83.67t/data=!3m7!1e1!3m5!1sAF1QipMn1OFEDkjcWNUMsmro-KO-rPRUmkqcCFyZIfxn!2e10!3e11!7i10059!8i3181), the width of this streetview is 10059, the height is 3181. but google streetview display seems OK.

You can open developer tools to see it's tiles, it has 20x7 tiles. not power of 2.

So I wish can support this type of  rectangular tiles, thx.

### Photo Sphere Viewer version

5.1.1

**Comment by mistic100** [comment]
Partial panorama configuration is explained here https://photo-sphere-viewer.js.org/guide/adapters/equirectangular.html#cropped-panorama

**Comment by mistic100** [comment]
I am not able to do that because how I designed the renderer. It would required to start from scratch.

By the way StreetView supports multiple resolutions by zoom level, which is not supported by PSV either.
