### ISSUE TITLE
Urgent: Stereo view

### ISSUE THREAD

**Issue by Geeksltd** [mistic100/Photo-Sphere-Viewer#86]
Hi guys

Thanks for your great work.

Can you please add support for Stereo mode (to view with VR Glasses)? The original v2.7 has this feature. But we're using your version 3.2.2 which doesn't seem to have it.

We need this ASAP please and even if there is a cost involved to get it done, please let me know.

Thanks
Paymon

**Comment by mistic100** [comment]
This is not a place to request for "urgent" features.

I am alone on this project and don't have enough free time for this in the next months.

**Comment by pat-sullivan** [comment]
Wow
