### ISSUE TITLE
Fullscreen not working on iPhone (Safari iOS)

### ISSUE THREAD

**Issue by soniumandy** [mistic100/Photo-Sphere-Viewer#860]
### Describe the bug

I’ve noticed that with v5.1.1 I can not enter fullscreen on iPhone (Safari iOS 16.3)

### Photo Sphere Viewer version

5.1.1

### OS & browser

Safari iOS 16.3

**Comment by mistic100** [comment]
Does it work with a previous version ? Is there an error in the debuguer ?

I don't have an iphone so you will have to help me.

**Comment by mistic100** [comment]
Borrowed an iPad and an iPhone at work. It is still the same problem : Apple disabled the fullscreen API on iPhones. There is not thing I can do.
