### ISSUE TITLE
setPanorama() transition stutter with large images

### ISSUE THREAD

**Issue by yusufarsln98** [mistic100/Photo-Sphere-Viewer#864]
Is there disolve or different effect available, as in the galery plugin, when switch the panorama by setPanorama()?
When I change the screen, it wait for a time then opens the new screen suddenly.

I'm using react-photo-sphere-viewer 3.3.3-psv5.1.1.

**Comment by mistic100** [comment]
The gallery plugin uses setPanorama, which already handle the fade-in transition.

And the method itself works perfectly (can be tested on the example https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/examples/equirectangular.html)

If it does not work for you, perhaps it is a problem with the React wrapper (in such case, ask the author)

**Comment by yusufarsln98** [comment]
I found the reason. 
I tried the same code with smaller size images it worked, but not in large images (~12Mb size)

**Comment by yusufarsln98** [comment]
Here is the codesandbox link sir, as I said, it worked with some small-sized random images but not for these images.

https://codesandbox.io/s/react-photo-sphere-viewer-setpanorama-example-1qi35m?file=/src/App.js

**Comment by mistic100** [comment]
I made a test with a 34MB jpeg. With this panorama the first frame of the animation is already at 88% of progression, so it looks like an instant switch between the two panoramas.

I am able to bring this down to 28% by doing a pre-render before the animation. But I don't understand why it still stutter.
