### ISSUE TITLE
How can I limit the viewable area?

### ISSUE THREAD

**Issue by yusufarsln98** [mistic100/Photo-Sphere-Viewer#866]
### Description

Hello, I have a partial panoramic photo and I want to limit the movement.
For example, I want to prevent users from making vertical movements, and I want to be able to move horizontally only at a certain interval.

I got the panoData perfectly on the website, the image looks great, but because the photo is partial, there is a black area on the back. I want to get a more accurate view of the limitations I mentioned.

I added the codesandbox example. Although I wrote the code with React, I would like to state that I followed the original documentation.

Sincerely.

### Online demo URL

https://codesandbox.io/s/partial-panorama-react-photo-sphere-viewer-z7f3mk

### Photo Sphere Viewer version

5.1.1

**Comment by mistic100** [comment]
https://photo-sphere-viewer.js.org/plugins/visible-range.html

**Comment by yusufarsln98** [comment]
Thank you sir!
