### ISSUE TITLE
Pano Images Marker positions are not matching with web and iOS mobile device

### ISSUE THREAD

**Issue by manoj1416** [mistic100/Photo-Sphere-Viewer#869]
### Describe the bug

We are placing the markers in mobile iOS device and capturing the corresponding latitude and longitude of each marker and when we try to render the same panorama in browser with same marker coordinates. Please find the below links for mismatch in marker placement as they are slightly drifting.

iOS photo sphere rendered viewer along with Markers placement
https://s3.amazonaws.com/tw-inlineimages/258925/0/0/5265b7a1c05ed881151b2278f1aed311.png

Browser photo sphere rendered viewer along with Markers placement
https://s3.amazonaws.com/tw-inlineimages/258925/0/0/526f16d70cfd3d9c01b3b622e2965257.png

### Photo Sphere Viewer version

5.1.1

### OS & browser

Mobile & safari

**Comment by mistic100** [comment]
I need a live demo. This cannot be analyzed without access to your (running) code.

**Comment by manoj1416** [comment]
Thanks for your reply. Can you please let me know how to provide live demo to you. Shall I post the code we have used here?

**Comment by manoj1416** [comment]
Please find the below code snippets used in mobile and web platforms
In iOS platform, html page is loaded in Webkit by passing the panorama image as parameter to JS function. Below is the code 
 <script>

        var viewer;
        var markersPlugin;
        var isHotspotPlaced = false;
        var hotspot_icon_path = ""
        const Marker_Size = 25;


        function loadImageWithoutAddHotspot(path, hotspotIconPath, hotspotData) {
            hotspot_icon_path = hotspotIconPath
            window.webkit.messageHandlers.getSelectedHotspot.postMessage(JSON.stringify(hotspotData));
            let markersData = []
            if (hotspotData != "") {
                var decodedData = window.atob(hotspotData);
                var hotspotParseData = JSON.parse(decodedData);

                for (let item of hotspotParseData) {
                    let json = {
                        id: item["hotspot_id"],
                        image: hotspotIconPath,
                        width: Marker_Size,
                        height: Marker_Size,
                        longitude: parseFloat(item["hotspot_longitude"]),
                        latitude: parseFloat(item["hotspot_latitude"]),
                    }
                    markersData.push(json)
                }
            }

            viewer = new PhotoSphereViewer({
                container: document.querySelector('#viewer'),
                panorama: path,
                markers: markersData,
                default_long: 0,
                default_lat: 0,
                time_anim: false,
                navbar: [
                    'zoom'
                ],
               
            });
            viewer.zoom(1)
            viewer.on('select-marker', (marker) => {
                console.log(`Clicked on marker ${marker.id}`);
                window.webkit.messageHandlers.getSelectedHotspot.postMessage(marker.id);
            });
        }

        function loadImage(path, hotspotIconPath, id, hotspotDetails) {
            hotspot_icon_path = hotspotIconPath
            markersArr = []
            if (hotspotDetails != "") {
                isHotspotPlaced = true
                var decodedData = window.atob(hotspotDetails);
                var hotspotDetailsParseData = JSON.parse(decodedData);
                let json = {
                    id: hotspotDetailsParseData["hotspot_id"],
                    image: hotspotIconPath,
                    longitude: parseFloat(hotspotDetailsParseData["hotspot_longitude"]),
                    latitude: parseFloat(hotspotDetailsParseData["hotspot_latitude"]),
                    width: Marker_Size,
                    height: Marker_Size,
                    data: {
                        new: true
                    }
                }
                markersArr.push(json)
            }
            viewer = new PhotoSphereViewer({
                container: document.querySelector('#viewer'),
                panorama: path,
                markers: markersArr,
                default_long: 0,
                default_lat: 0,
                time_anim: false,
                navbar: [
                    'zoom'
                ],
            });
            viewer.zoom(1)
            viewer.on('click', (e) => {
                window.webkit.messageHandlers.onclick.postMessage(JSON.stringify(e));
                if (isHotspotPlaced) {
                    viewer.updateMarker({
                        id: id,
                        longitude: e.longitude,
                        latitude: e.latitude,
                    });
                } else {
                    isHotspotPlaced = true;
                    viewer.addMarker({
                        id: id,
                        longitude: e.longitude,
                        latitude: e.latitude,
                        image: hotspotIconPath,
                        width: Marker_Size,
                        height: Marker_Size,
                        data: {
                            new: true
                        }
                    });
                }
                window.webkit.messageHandlers.getCoordinates.postMessage(JSON.stringify({ "pitch": `${e.latitude}`, "yaw": `${e.longitude}` }));
            });


        }

        function removeAllHotspots() {
            viewer.clearMarkers()
        }

        function addHotspot(id, postion) {

            var decodedData = window.atob(postion);
            var hotspotParseData = JSON.parse(decodedData);

            viewer.addMarker({
                id: id,
                longitude: parseFloat(hotspotParseData["yaw"]),
                latitude: parseFloat(hotspotParseData["pitch"]),
                image: hotspot_icon_path,
                width: Marker_Size,
                height: Marker_Size,
            });
        }

        function deleteHotspot(id) {
            viewer.removeMarker(id)
        }

        function focusHotspot(id) {
            viewer.gotoMarker(id)
        }

        function updateMarkerPosition(id, postion) {
            var decodedData = window.atob(postion);
            var data = JSON.parse(decodedData);
            viewer.updateMarker({
                id: id,
                longitude: parseFloat(data.yaw),
                latitude: parseFloat(data.pitch),
            });
        }

    </script> 

I will generate the json file based on the marker postions and sent the same data to server. We have a web platform where users can see the placed markers( uploaded from mobile) in web page. In web page the uploaded hotspot markers data is used to place markers. Please find below the web page code
var hotspots = (data && data.markers) ? data.markers : [];
--
  |  
  | var navBarDataDesktop = ['autorotate', 'zoom', 'caption', 'gyroscope'];
  | var navBarDataMobile = ['autorotate', 'caption', 'gyroscope'];
  |  
  | var navBarData = isTouchDevice ? navBarDataMobile : navBarDataDesktop;
  |  
  | // if (onlyIphone()) navBarData.pop();
  |  
  | if(document.fullscreenEnabled){
  | navBarData.push({
  | id: 'toggleFullScreenButton',
  | title: 'Fullscreen',
  | className: 'psv-button--hover-scale',
  | content: fullScreenIcon,
  | onClick: toggleFullScreen
  | });
  | }
  |  
  | var PSV = new PhotoSphereViewer.Viewer({
  | panorama: '/images/AFDCF566-E5F0-4081-B6F8-3146AED136A8_pano.jpg',
  | container: 'three-sixty-view',
  | loadingImg: "/assets/images/photosphere-logo.gif",
  | navbar: navBarData,
  | mousewheel: false,
  | panoData: {
  | poseHeading: 0,
  | posePitch: 0,
  | poseRoll: 0,
  | },
  | plugins: [
  | PhotoSphereViewer.GyroscopePlugin,
  | [
  | PhotoSphereViewer.MarkersPlugin, {
  | markers: getMarkers(hotspots)
  | }],
  | ],
  | lang: {
  | gyroscope: 'Gyroscope'
  | }
  | });
  |  
  | var markersPlugin = PSV.getPlugin(PhotoSphereViewer.MarkersPlugin);
  |  
  | if (data && data.markers && data.markers.length) {
  | data.markers.forEach(function (marker) {
  | generateHtmlTemplate(marker.data.contentId, marker.tooltip, marker.data.thumbnail, marker.data.description);
  | })
  | }
  |  
  | var selectedMarker;
  |  
  | markersPlugin.on('select-marker', (e, marker) => {
  | markersPlugin.gotoMarker( marker.id, 500);
  | selectedMarker = marker
  | });
  |  
  | markersPlugin.on('goto-marker-done', function (e, marker) {
  | if (marker.data && marker.data.contentId) {
  | if (document.getElementsByClassName('highlight-viewer.show').length > 0) {
  | closeHighlight();
  | }
  |  
  | parent.postMessage(JSON.stringify({"action":"removeCross"}),"*");
  | document.getElementById(marker.data.contentId).classList.add('show');
  | document.getElementById(marker.data.contentId).querySelector('.highlight-content-box').style.display = 'block';
  | }
  | });

After pre-filling the markers data(which is uploaded from iOS platform) in web page marker positions are drifting little downwards compared to original position they where placed.

Please let me know if you have any findings/suggestions on this issue which will be appreciable. Thanks for your time.

**Comment by mistic100** [comment]
Yout code is not legible, please use markdown syntax for code blocks

**Comment by manoj1416** [comment]
Can you please check now
Please find the below code snippets used in mobile and web platforms
In iOS platform, html page is loaded in Webkit by passing the panorama image as parameter to JS function. Below is the code
<script>
  var viewer;
  var markersPlugin;
  var isHotspotPlaced = false;
  var hotspot_icon_path = ""
  const Marker_Size = 25;

  function loadImageWithoutAddHotspot(path, hotspotIconPath, hotspotData) {
    hotspot_icon_path = hotspotIconPath window.webkit.messageHandlers.getSelectedHotspot.postMessage(JSON.stringify(hotspotData));
    let markersData = []
    if (hotspotData != "") {
      var decodedData = window.atob(hotspotData);
      var hotspotParseData = JSON.parse(decodedData);
      for (let item of hotspotParseData) {
        let json = {
          id: item["hotspot_id"],
          image: hotspotIconPath,
          width: Marker_Size,
          height: Marker_Size,
          longitude: parseFloat(item["hotspot_longitude"]),
          latitude: parseFloat(item["hotspot_latitude"]),
        }
        markersData.push(json)
      }
    }
    viewer = new PhotoSphereViewer({
      container: document.querySelector('#viewer'),
      panorama: path,
      markers: markersData,
      default_long: 0,
      default_lat: 0,
      time_anim: false,
      navbar: ['zoom'],
    });
    viewer.zoom(1) viewer.on('select-marker', (marker) => {
      console.log(`Clicked on marker ${marker.id}`);
      window.webkit.messageHandlers.getSelectedHotspot.postMessage(marker.id);
    });
  }

  function loadImage(path, hotspotIconPath, id, hotspotDetails) {
    hotspot_icon_path = hotspotIconPath markersArr = []
    if (hotspotDetails != "") {
      isHotspotPlaced = true
      var decodedData = window.atob(hotspotDetails);
      var hotspotDetailsParseData = JSON.parse(decodedData);
      let json = {
        id: hotspotDetailsParseData["hotspot_id"],
        image: hotspotIconPath,
        longitude: parseFloat(hotspotDetailsParseData["hotspot_longitude"]),
        latitude: parseFloat(hotspotDetailsParseData["hotspot_latitude"]),
        width: Marker_Size,
        height: Marker_Size,
        data: {
          new: true
        }
      }
      markersArr.push(json)
    }
    viewer = new PhotoSphereViewer({
      container: document.querySelector('#viewer'),
      panorama: path,
      markers: markersArr,
      default_long: 0,
      default_lat: 0,
      time_anim: false,
      navbar: ['zoom'],
    });
    viewer.zoom(1) viewer.on('click', (e) => {
      window.webkit.messageHandlers.onclick.postMessage(JSON.stringify(e));
      if (isHotspotPlaced) {
        viewer.updateMarker({
          id: id,
          longitude: e.longitude,
          latitude: e.latitude,
        });
      } else {
        isHotspotPlaced = true;
        viewer.addMarker({
          id: id,
          longitude: e.longitude,
          latitude: e.latitude,
          image: hotspotIconPath,
          width: Marker_Size,
          height: Marker_Size,
          data: {
            new: true
          }
        });
      }
      window.webkit.messageHandlers.getCoordinates.postMessage(JSON.stringify({
        "pitch": `${e.latitude}`,
        "yaw": `${e.longitude}`
      }));
    });
  }

  function removeAllHotspots() {
    viewer.clearMarkers()
  }

  function addHotspot(id, postion) {
    var decodedData = window.atob(postion);
    var hotspotParseData = JSON.parse(decodedData);
    viewer.addMarker({
      id: id,
      longitude: parseFloat(hotspotParseData["yaw"]),
      latitude: parseFloat(hotspotParseData["pitch"]),
      image: hotspot_icon_path,
      width: Marker_Size,
      height: Marker_Size,
    });
  }

  function deleteHotspot(id) {
    viewer.removeMarker(id)
  }

  function focusHotspot(id) {
    viewer.gotoMarker(id)
  }

  function updateMarkerPosition(id, postion) {
    var decodedData = window.atob(postion);
    var data = JSON.parse(decodedData);
    viewer.updateMarker({
      id: id,
      longitude: parseFloat(data.yaw),
      latitude: parseFloat(data.pitch),
    });
  }
</script>

I will generate the json file based on the marker postions and sent the same data to server. We have a web platform where users can see the placed markers( uploaded from mobile) in web page. In web page the uploaded hotspot markers data is used to place markers. Please find below the web page code

 |  var hotspots = (data && data.markers) ? data.markers : []
  | var navBarDataDesktop = ['autorotate', 'zoom', 'caption', 'gyroscope'];
  | var navBarDataMobile = ['autorotate', 'caption', 'gyroscope'];
  |  
  | var navBarData = isTouchDevice ? navBarDataMobile : navBarDataDesktop;
  |  
  | // if (onlyIphone()) navBarData.pop();
  |  
  | if(document.fullscreenEnabled){
  | navBarData.push({
  | id: 'toggleFullScreenButton',
  | title: 'Fullscreen',
  | className: 'psv-button--hover-scale',
  | content: fullScreenIcon,
  | onClick: toggleFullScreen
  | });
  | }
  |  
  | var PSV = new PhotoSphereViewer.Viewer({
  | panorama: '/images/AFDCF566-E5F0-4081-B6F8-3146AED136A8_pano.jpg',
  | container: 'three-sixty-view',
  | loadingImg: "/assets/images/photosphere-logo.gif",
  | navbar: navBarData,
  | mousewheel: false,
  | panoData: {
  | poseHeading: 0,
  | posePitch: 0,
  | poseRoll: 0,
  | },
  | plugins: [
  | PhotoSphereViewer.GyroscopePlugin,
  | [
  | PhotoSphereViewer.MarkersPlugin, {
  | markers: getMarkers(hotspots)
  | }],
  | ],
  | lang: {
  | gyroscope: 'Gyroscope'
  | }
  | });
  |  
  | var markersPlugin = PSV.getPlugin(PhotoSphereViewer.MarkersPlugin);
  |  
  | if (data && data.markers && data.markers.length) {
  | data.markers.forEach(function (marker) {
  | generateHtmlTemplate(marker.data.contentId, marker.tooltip, marker.data.thumbnail, marker.data.description);
  | })
  | }
  |  
  | var selectedMarker;
  |  
  | markersPlugin.on('select-marker', (e, marker) => {
  | markersPlugin.gotoMarker( marker.id, 500);
  | selectedMarker = marker
  | });
  |  
  | markersPlugin.on('goto-marker-done', function (e, marker) {
  | if (marker.data && marker.data.contentId) {
  | if (document.getElementsByClassName('highlight-viewer.show').length > 0) {
  | closeHighlight();
  | }
  |  
  | parent.postMessage(JSON.stringify({"action":"removeCross"}),"*");
  | document.getElementById(marker.data.contentId).classList.add('show');
  | document.getElementById(marker.data.contentId).querySelector('.highlight-content-box').style.display = 'block';
  | }
  | });

After pre-filling the markers data(which is uploaded from iOS platform) in web page marker positions are drifting little downwards compared to original position they where placed.

Please let me know if you have any findings/suggestions on this issue which will be appreciable. Thanks for your time.

**Comment by mistic100** [comment]
You can see yourself it is not. 
See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

Just edit you message and add the fences with language name

**Comment by manoj1416** [comment]
> Also I would much prefer a **online demo**
Can I provide you the recorded videos for demo?

**Comment by manoj1416** [comment]
Can you please check the format now
Please find the below code snippets used in mobile and web platforms
In iOS platform, html page is loaded in Webkit by passing the panorama image as parameter to JS function. Below is the code
```

    <script>

        var viewer;
        var markersPlugin;
        var isHotspotPlaced = false;
        var hotspot_icon_path = ""
        const Marker_Size = 25;

        function loadImageWithoutAddHotspot(path, hotspotIconPath, hotspotData) {
            hotspot_icon_path = hotspotIconPath
            window.webkit.messageHandlers.getSelectedHotspot.postMessage(JSON.stringify(hotspotData));
            let markersData = []
            if (hotspotData != "") {
                var decodedData = window.atob(hotspotData);
                var hotspotParseData = JSON.parse(decodedData);

                for (let item of hotspotParseData) {
                    let json = {
                        id: item["hotspot_id"],
                        image: hotspotIconPath,
                        width: Marker_Size,
                        height: Marker_Size,
                        longitude: parseFloat(item["hotspot_longitude"]),
                        latitude: parseFloat(item["hotspot_latitude"]),
                    }
                    markersData.push(json)
                }
            }

            viewer = new PhotoSphereViewer({
                container: document.querySelector('#viewer'),
                panorama: path,
                markers: markersData,
                default_long: 0,
                default_lat: 0,
                time_anim: false,
                navbar: [
                    'zoom'
                ],
            });
            viewer.zoom(1)
            viewer.on('select-marker', (marker) => {
                console.log(`Clicked on marker ${marker.id}`);
                window.webkit.messageHandlers.getSelectedHotspot.postMessage(marker.id);
            });
        }

        function loadImage(path, hotspotIconPath, id, hotspotDetails) {
            hotspot_icon_path = hotspotIconPath
            markersArr = []
            if (hotspotDetails != "") {
                isHotspotPlaced = true
                var decodedData = window.atob(hotspotDetails);
                var hotspotDetailsParseData = JSON.parse(decodedData);
                let json = {
                    id: hotspotDetailsParseData["hotspot_id"],
                    image: hotspotIconPath,
                    longitude: parseFloat(hotspotDetailsParseData["hotspot_longitude"]),
                    latitude: parseFloat(hotspotDetailsParseData["hotspot_latitude"]),
                    width: Marker_Size,
                    height: Marker_Size,
                    data: {
                        new: true
                    }
                }
                markersArr.push(json)
            }
            viewer = new PhotoSphereViewer({
                container: document.querySelector('#viewer'),
                panorama: path,
                markers: markersArr,
                default_long: 0,
                default_lat: 0,
                time_anim: false,
                navbar: [
                    'zoom'
                ],
            });
            viewer.zoom(1)
            viewer.on('click', (e) => {
                if (isHotspotPlaced) {
                    viewer.updateMarker({
                        id: id,
                        longitude: e.longitude,
                        latitude: e.latitude,
                    });
                } else {
                    isHotspotPlaced = true;
                    viewer.addMarker({
                        id: id,
                        longitude: e.longitude,
                        latitude: e.latitude,
                        image: hotspotIconPath,
                        width: Marker_Size,
                        height: Marker_Size,
                        data: {
                            new: true
                        }
                    });
                }
                window.webkit.messageHandlers.getCoordinates.postMessage(JSON.stringify({ "pitch": `${e.latitude}`, "yaw": `${e.longitude}` }));
            });
        }

        function removeAllHotspots() {
            viewer.clearMarkers()
        }

        function addHotspot(id, postion) {

            var decodedData = window.atob(postion);
            var hotspotParseData = JSON.parse(decodedData);

            viewer.addMarker({
                id: id,
                longitude: parseFloat(hotspotParseData["yaw"]),
                latitude: parseFloat(hotspotParseData["pitch"]),
                image: hotspot_icon_path,
                width: Marker_Size,
                height: Marker_Size,
            });
        }

        function deleteHotspot(id) {
            viewer.removeMarker(id)
        }

        function focusHotspot(id) {
            viewer.gotoMarker(id)
        }

        function updateMarkerPosition(id, postion) {
            var decodedData = window.atob(postion);
            var data = JSON.parse(decodedData);
            viewer.updateMarker({
                id: id,
                longitude: parseFloat(data.yaw),
                latitude: parseFloat(data.pitch),
            });
        }
    </script>

```

I will generate the json file based on the marker postions and sent the same data to server. We have a web platform where users can see the placed markers( uploaded from mobile) in web page. In web page the uploaded hotspot markers data is used to place markers. Please find below the web page code

```
var hotspots = (data && data.markers) ? data.markers : [];

    var navBarDataDesktop = ['autorotate', 'zoom', 'caption', 'gyroscope'];
    var navBarDataMobile = ['autorotate', 'caption', 'gyroscope'];

    var navBarData = isTouchDevice ? navBarDataMobile : navBarDataDesktop;

    if(document.fullscreenEnabled){
      navBarData.push({
        id: 'toggleFullScreenButton',
        title: 'Fullscreen',
        className: 'psv-button--hover-scale',
        content: fullScreenIcon,
        onClick: toggleFullScreen
      });
    }

    var PSV = new PhotoSphereViewer.Viewer({
      panorama: '/images/98F4D59A-3614-4E9F-92F1-74F2F14225A1_pano.jpg',
      container: 'three-sixty-view',
      loadingImg: "/assets/images/photosphere-logo.gif",
      navbar: navBarData,
      mousewheel: false,
      panoData: {
        poseHeading: 0,
        posePitch: 0,
        poseRoll: 0,
      },
      plugins: [
        PhotoSphereViewer.GyroscopePlugin,
        [
          PhotoSphereViewer.MarkersPlugin, {
          markers: getMarkers(hotspots)
        }],
      ],
      lang: {
        gyroscope: 'Gyroscope'
      }
    });

    var markersPlugin = PSV.getPlugin(PhotoSphereViewer.MarkersPlugin);

    if (data && data.markers && data.markers.length) {
      data.markers.forEach(function (marker) {
        generateHtmlTemplate(marker.data.contentId, marker.tooltip, marker.data.thumbnail, marker.data.description);
      })
    }

    var selectedMarker;

    markersPlugin.on('select-marker', (e, marker) => {
      markersPlugin.gotoMarker( marker.id, 500);
      selectedMarker = marker
    });

    markersPlugin.on('goto-marker-done', function (e, marker) {
      if (marker.data && marker.data.contentId) {
        if (document.getElementsByClassName('highlight-viewer.show').length > 0) {
          closeHighlight();
        }

        parent.postMessage(JSON.stringify({"action":"removeCross"}),"*");
        document.getElementById(marker.data.contentId).classList.add('show');
        document.getElementById(marker.data.contentId).querySelector('.highlight-content-box').style.display = 'block';
      }
    });

```

After pre-filling the markers data(which is uploaded from iOS platform) in web page marker positions are drifting little downwards compared to original position they where placed.

**Comment by mistic100** [comment]
No I cannot do a live demo with you. There are online services like jsfiddle and codepen to share demos.

----

Your second code is not complete, where is the `getMarkers` function ?

----

ANYWAY: I will not answer you if you don't provide a online, complete, working demonstration of the problem. There are too much variables at stake. If you cannot create such demo you can close the issue. I am a lone developper working on my spare time and don't want to invest time in trying to understand what you are doing. Thank you.

**Comment by manoj1416** [comment]
Thanks for your support so far.
We have observed the marker css property transform-origin value is set to '50% 0%', in this scenario marker placement is not matching and if  transform-origin value is set to '50% 50%' marker placement is matching.
How to override the marker css property transform-origin to '50% 50%'?

```
    width: 40px;
    height: 40px;
    background-image: url(https://media.flickfusion.net/ava/apps/360playerV5/img/fa-bullseye.svg);
    transform-origin: 50% 50%;
    transform: translate3d(99px, 148px, 0px);
```
The above code works properly for marker position placement

```
    width: 40px;
    height: 40px;
    background-image: url(https://media.flickfusion.net/ava/apps/360playerV5/img/fa-bullseye-b.svg);
    transform-origin: 50% 0%;
    transform: translate3d(114.5px, 158px, 0px);
```
The above code is having drifting issue after placing markers

**Comment by mistic100** [comment]
The transformOrigin is computed from the [`anchor`](https://photo-sphere-viewer.js.org/plugins/markers.html#anchor)  marker property. So perhaps your two viewers are not configured with the same anchor

**Comment by manoj1416** [comment]
Thanks for your support.
