### ISSUE TITLE
Bug with multiple elements with full-screen controls

### ISSUE THREAD

**Issue by blakemartin13** [mistic100/Photo-Sphere-Viewer#87]
I'm having an issue with image not displaying/rendering if PSV is hidden (display:none on container) and another element activates full-screen.  I'm working on a slideshow viewer where available items are normal images (actually DZI images), panoramic, and videos.  Depending on the item selected, I programmed the page to show one of the viewers depending on the type selected (Openseadragon for DZI, PhotoSphereViewer for panoramic, and HTML5 video tags for mp4 videos).  In my page, I'm using jQuery so I'm using the hide and show methods. In the plunkr below I'm using pure javascript but doing what jQuery basically does as far as hiding.

Here's a plunkr with a demonstration: https://plnkr.co/edit/8CWqOTuYsJd6q92uEtbr?p=preview

Steps:
0. Start in separate window viewer. Can't have iframes.
1. Hide PSV with Toggle Pano Container button.
2. Enable fullscreen on video control and then exit full screen on video.
3. Show PSV with Toggle Pano Container Button.

At this point, there will be no image displayed in PSV. Changing image doesn't fix it.  Calling render doesn't fix it. Two ways to fix: 1. enable fullscreen for PSV and image will begin to display. 2. Destroy PSV and reinitialize.

I'm currently using 2 as a work around since it is least disruptive to the user's experience.

Happens in Chrome 55 and IE 11.

**Comment by mistic100** [comment]
The problem is a "resize" event is triggered while the container is hidden (hence null size).

You just need to reset the size of the viewer after displaying it, either by triggering a resize event at window level or call "_onResize()" method of the viewer.

**Comment by blakemartin13** [comment]
Thanks for the quick reply! Decided on calling _onResize() and now it's much nicer since it doesn't destroy the cache.  Thanks for the help and continuing to make a great plugin!
