### ISSUE TITLE
Getting Errors on node_modules/@photo-sphere-viewer/core/index.d.ts when loading into a TypeScript file.

### ISSUE THREAD

**Issue by JoseRobertoReyesEncora** [mistic100/Photo-Sphere-Viewer#879]
### Describe the bug

I have these errors when trying to compile a TypeScript file with th `Viewer` imported into it.
```
Error: node_modules/@photo-sphere-viewer/core/index.d.ts:549:5 - error TS2416: Property 'addEventListener' in type 'TypedEventTarget<TEvents>' is not assignable to the same property in base type 'EventTarget'.
  Type '<T extends TEvents["type"], E extends TEvents & { type: T; }>(type: T, callback: EventListenerObject | ((e: E) => void), options?: boolean | AddEventListenerOptions | undefined) => void' is not assignable to type '(type: string, callback: EventListenerOrEventListenerObject | null, options?: boolean | AddEventListenerOptions | undefined) => void'.
    Types of parameters 'callback' and 'callback' are incompatible.
      Type 'EventListenerOrEventListenerObject | null' is not assignable to type 'EventListenerObject | ((e: TEvents & { type: string; }) => void)'.
        Type 'null' is not assignable to type 'EventListenerObject | ((e: TEvents & { type: string; }) => void)'.

549     addEventListener<T extends TEvents['type'], E extends TEvents & {

Error: node_modules/@photo-sphere-viewer/core/index.d.ts:556:5 - error TS2416: Property 'removeEventListener' in type 'TypedEventTarget<TEvents>' is not assignable to the same property in base type 'EventTarget'.
  Type '<T extends TEvents["type"], E extends TEvents & { type: T; }>(type: TEvents["type"], callback: EventListenerObject | ((e: E) => void), options?: boolean | EventListenerOptions | undefined) => void' is not assignable to type '(type: string, callback: EventListenerOrEventListenerObject | null, options?: boolean | EventListenerOptions | undefined) => void'.
    Types of parameters 'callback' and 'callback' are incompatible.
      Type 'EventListenerOrEventListenerObject | null' is not assignable to type 'EventListenerObject | ((e: TEvents & { type: TEvents["type"]; }) => void)'.
        Type 'null' is not assignable to type 'EventListenerObject | ((e: TEvents & { type: TEvents["type"]; }) => void)'.

556     removeEventListener<T extends TEvents['type'], E extends TEvents & {
```
Te error is triggered by just trying to import the `Viewer` in the file.
```import { Viewer } from '@photo-sphere-viewer/core';```

Three is already installed in the project through npm.

TypeScript Version: 4.9.5

### Photo Sphere Viewer version

5.1.1

### OS & browser

macOS 13 "Ventura"

**Comment by mistic100** [comment]
Can you validate the following changes solves the problem ?

Edit the file in your node_modules to replace the definition of `TypedEventTarget` by

```ts
declare class TypedEventTarget<TEvents extends TypedEvent<any>> extends EventTarget {
    dispatchEvent(e: TEvents): boolean;
    /**
     * @template T the name of event
     * @template E the class of the event
     */
    addEventListener<T extends TEvents['type'], E extends TEvents & {
        type: T;
    }>(type: T, callback: ((e: E) => void) | EventListenerObject | null, options?: AddEventListenerOptions | boolean): void;
    /**
     * @template T the name of event
     * @template E the class of the event
     */
    removeEventListener<T extends TEvents['type'], E extends TEvents & {
        type: T;
    }>(type: TEvents['type'], callback: ((e: E) => void) | EventListenerObject | null, options?: EventListenerOptions | boolean): void;
}
```

(Added `null` as possible type for the callbacks)

**Comment by JoseRobertoReyesEncora** [comment]
> Can you validate the following changes solves the problem ?
> 
> Edit the file in your node_modules to replace the definition of `TypedEventTarget` by
> 
> ```ts
> declare class TypedEventTarget<TEvents extends TypedEvent<any>> extends EventTarget {
>     dispatchEvent(e: TEvents): boolean;
>     /**
>      * @template T the name of event
>      * @template E the class of the event
>      */
>     addEventListener<T extends TEvents['type'], E extends TEvents & {
>         type: T;
>     }>(type: T, callback: ((e: E) => void) | EventListenerObject | null, options?: AddEventListenerOptions | boolean): void;
>     /**
>      * @template T the name of event
>      * @template E the class of the event
>      */
>     removeEventListener<T extends TEvents['type'], E extends TEvents & {
>         type: T;
>     }>(type: TEvents['type'], callback: ((e: E) => void) | EventListenerObject | null, options?: EventListenerOptions | boolean): void;
> }
> ```
> 
> (Added `null` as possible type for the callbacks)

Validated! The changes fixes the bug. Anything else you need for testing?

**Comment by mistic100** [comment]
Thanks, I will integrate the fix in the next version.

**Comment by JoseRobertoReyesEncora** [comment]
Thank you very much! If it is ok with you, I want to ask When will be deployed the next version?
