### ISSUE TITLE
Markers Plugin: textureX and textureY ignored

### ISSUE THREAD

**Issue by mxmtsk** [mistic100/Photo-Sphere-Viewer#881]
### Describe the bug

Based on the [documentation](https://photo-sphere-viewer.js.org/plugins/markers.html#position-required-for-all-but-polygons-polylines), I should be able to define coordinates as pixel values with `textureX` and `textureY` properties in `position`. 

However, the values are ignored and the markers don't show up (they get rendered, but they don't have `transform` values).

I'm trying to render a `html` marker:

```js
            markerPlugin.addMarker({
              id: markerItem.title,
              position: { textureX: 150, textureY:300 },
              
              data: {
                markerItem: markerItem,
              },
              tooltip: {
                content: renderToString(
                        <TextMarker
                          title={markerItem.title}
                          text="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
                        />
                      ),
                className: 'custom-tooltip',
                position: 'top',
                trigger: 'click',
              },
              html: ReactDOMServer.renderToString(
                React.createElement('div', {
                  dangerouslySetInnerHTML: {
                    __html: renderComponent,
                  },
                })
              ),
            });
```

### Photo Sphere Viewer version

5.1.2

### Plugins loaded

MarkersPlugin

### OS & browser

macOS, Chrome (however, all browsers and OS affected)

**Comment by mistic100** [comment]
Do you have a an example ? I just tested in the [example file](https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/examples/plugin-markers.html#L137-L145) with `position: { textureX: 3000, textureY: 1200 }` and it works just fine.

**Comment by mxmtsk** [comment]
I'm sorry, entirely my fault. I did something wrong while migrating to the new version. 🫣
