### ISSUE TITLE
panorama-loaded and gallery plugin

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#883]
### Describe your problem

Hi Damien

I have this:

```
var panoName = ({ data }) => {
    console.log(data.panorama);
};

viewer.addEventListener('panorama-loaded', panoName);
```

it should log the name of the panorama that it is loaded.  Works with the first one that is loaded.
But with the gallery plugin when i'm loading other panoramas....   nothing happens.

Am I missing something?
Thanks.

### Online demo URL

https://www.tadini.it/temp/pano5.html

### Photo Sphere Viewer version

5.1.2

### Plugins loaded

gallery

**Comment by mistic100** [comment]
Thanks
