### ISSUE TITLE
zoom + button weirdness 

### ISSUE THREAD

**Issue by invincible09** [mistic100/Photo-Sphere-Viewer#89]
Hi,

This is a weird issue.. clicking on the + to zoom twice highlights the text beside it?

e.g - the homepage 360 does it too
http://photo-sphere-viewer.js.org/

any idea how to fix this?

**Comment by mistic100** [comment]
It's not really weird... it's the basic behaviour of double-click in a browser.

I'll stop the propagation of the click event on buttons.

ps: click and hold works better than multiple clicks on zoom buttons

**Comment by invincible09** [comment]
thanks guys!
