### ISSUE TITLE
Blend / transition between two images

### ISSUE THREAD

**Issue by mikepianka** [mistic100/Photo-Sphere-Viewer#890]
### Describe the feature

I was thinking of a feature where two panoramas could be blended together, basically one with a transparency on top of the other that could then be controlled with a slider bar. For example if you took two images at the same location - maybe night /day, summer / winter, etc., and then could transition between them. My first idea was to abuse the `overlay` functionality but ideally it would also work with equirectangular tile adapter so the images could be high resolution but still load quickly. This is a pretty specific feature so I understand if it is too specific for the scope of this project, but was just curious what approach you would take.

**Comment by mistic100** [comment]
It could be done by using the same (kinda) [shader](https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/core/src/adapters/AbstractAdapter.ts#L99-L143) on the tiles adapter. But I don't really want to have to manage two sets of materials. It is complex enough right now.

**Comment by mikepianka** [comment]
> It could be done by using the same (kinda) [shader](https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/core/src/adapters/AbstractAdapter.ts#L99-L143) on the tiles adapter. But I don't really want to have to manage two sets of materials. It is complex enough right now.

Yeah I see what you mean. That EquirectangularTilesAdapter is a beast!
