### ISSUE TITLE
Switching between cropped panoramic images with different sizes

### ISSUE THREAD

**Issue by yusufarsln98** [mistic100/Photo-Sphere-Viewer#892]
### Describe your problem

Hello, 
I have panoramic photographs that are cropped in different dimensions.

When I switch between these panoramic photographs using the setPanorama() function, I first load the image using setPanorama() and then adjust the visible area using the VisibleRangePlugin. Due to this, when switching between cropped images of different dimensions, a black screen is displayed before the next image and then the range is adjusted. 

[YouTube](https://www.youtube.com/watch?v=WdGktVK3PCw)

The code that how I load panorama and set visible range (It is ReactJs):
```
psvRef.current
	.setPanorama(pano, {
		panoData: panoData, // taking this from function parameter
	})
	.then(() => {
		const visibleRange = psvRef.current.getPlugin(VisibleRangePlugin);
		visibleRange.setRangesFromPanoData();
		visibleRange.setVerticalRange([0, 0]);
	});
```

So, the problem is actually quite clear: first I'm loading the new photograph with respect to the previous visible range, then I'm adjusting the new visible range. What I am requesting your help with is whether it is possible to solve this issue by resetting the initial yaw and pitch values (this is because setPanorama continues from the last yaw and pitch values). If this is possible, I would appreciate any assistance on how to set initial yaw and pitch values or alternative suggestions you may have. Thank you very much.

### Photo Sphere Viewer version

5.1.1

### Plugins loaded

VisibleRangePlugin

### Additional context

panoData example1: 
panoData: {
	fullWidth: 8640,
	fullHeight: 4320,
	croppedWidth: 4320,
	croppedHeight: 4320,
	croppedX: 2160,
	croppedY: 0,
},

panoData example2:
panoData: {
	fullWidth: 8640,
	fullHeight: 4320,
	croppedWidth: 6480,
	croppedHeight: 4320,
	croppedX: 1080,
	croppedY: 0,
},

**Comment by mistic100** [comment]
What is the initial yaw and pitch, is it a know value ? you can call `viewer.rotate({ yaw: 0, pitch: 0 })` or viewer.animate({ yaw: 0, pitch: 0, duration: 1000 })` (wait for the promise)

**Comment by yusufarsln98** [comment]
Okey, sir thank you very much. Setting yaw: 0 and pitch: 0, I hope will solve my problem, thank you :-)

**Comment by yusufarsln98** [comment]
I tried your suggestions Sir, but since rotate and animate methods require the panorama to be loaded, setting yaw: 0 and pitch: 0 before calling setPanorama() results in poor visual transition, as it renders the view from the current position to 0, 0 before switching to the new screen.

What I actually need is to start a picture that I uploaded with setPanorama from 0 yaw and 0 pitch (the image starts with the yaw and pitch of the previous screen when I don't do anything). This way, I can provide a seamless transition. Do you have any suggestions for this?

@mistic100

**Comment by yusufarsln98** [comment]
It perfectly worked, I did not that know and see in the documentation `setPanorama` accepts yaw and pitch. Thank you very much!
