### ISSUE TITLE
Add extension when download image

### ISSUE THREAD

**Issue by Edo2610** [mistic100/Photo-Sphere-Viewer#895]
### Describe the bug

Hi,
I load an image on photosphere using the base64 source and when I donwnload the image it will downloaded without extension and with the first characters of the base64 code as name
![image](https://user-images.githubusercontent.com/39258457/225959556-773f48b1-937c-4084-a70b-4c99a8814324.png)

There's a way to customize the download name of the image adding also the extension?

Thank you

### Photo Sphere Viewer version

5.1.2

### OS & browser

Chrome 111.0.5563.65 and Edge 111.0.1661.41

### Additional context

If I change the extension of the downloaded file, the image is shown correctly, so the file is good!

**Comment by mistic100** [comment]
Two improvements for the next version :
- will use `panorama.[type]` as default name when the panorama is base64
- add `downloadName` option is needed
