### ISSUE TITLE
Cannot use 'in' operator to search for 'photoSphereViewer_touchSupport' in null"

### ISSUE THREAD

**Issue by duoduodady** [mistic100/Photo-Sphere-Viewer#897]
### Describe the bug

The Error Message：
"Uncaught TypeError: Cannot use 'in' operator to search for 'photoSphereViewer_touchSupport' in null"
source: PSV472/dist/photo-sphere-viewer.js (846)

![image](https://user-images.githubusercontent.com/13536089/226097923-5b5db700-f7dc-4404-ba62-ed6d08ccc6c8.png)

I used webview to show the pano in the mobile, I can't see anything.

But,The chrome browser can display all right  when I debugger in mobile device type.

What should I do for this Error????

### Photo Sphere Viewer version

4.7.2

### OS & browser

android 12

**Comment by mistic100** [comment]
Can't you enable the local store in your webview ? For Android : https://stackoverflow.com/a/5934650/1207670

I can add a test to disable this code if the LS is not avaibale but **it will be for Photo Sphere Viewer 5** I don't update version 4 anymore.

**Comment by duoduodady** [comment]
It's good solution  to resolve my problem。Thanks!
