### ISSUE TITLE
gotoMarker() does not trigger 'selected-marker' event

### ISSUE THREAD

**Issue by Davidx7** [mistic100/Photo-Sphere-Viewer#9]
When using `gotoMarker()` which works fine and looks cool with the transition effect, but does not trigger the `selected-marker` event as a click would. 

I could use the ID to fetch, but would make more sense to if it would trigger.
What do you think?

**Comment by mistic100** [comment]
I prefer to let user events and programmatic actions apart.
It's simpler for developers to call the same method they use as event callback than differentiate what/who triggered the event.
