### ISSUE TITLE
Disable autorotation when press Space

### ISSUE THREAD

**Issue by vinihvc** [mistic100/Photo-Sphere-Viewer#906]
### Describe your problem

I have a floating Input on top of the `sphere-view` and every time `Space-bar` toggles the autorotation, I would like to know how to disable the space key

### Photo Sphere Viewer version

5.1.4

### Plugins loaded

Autorotate

**Comment by mistic100** [comment]
I fixed the plugin to respect the main `keyboard` config, ie: only enabled in fullscreen if `keyboard: 'fullscreen'` (default) and always enabled if `keyboard: 'always'`.

This was the behavior in v4 before the autorotate feature was moved to a plugin.
