### ISSUE TITLE
How to use requestHeaders to panoramics photos

### ISSUE THREAD

**Issue by Rafael-C-S** [mistic100/Photo-Sphere-Viewer#914]
### Describe your problem

Hello everything is fine?

I'm having color problems with the images I need to render in the browser. I saw that there is a requestHeader setting in the documentation. Could you please explain to me how to use them?

### Photo Sphere Viewer version

5.1.4

**Comment by mistic100** [comment]
I don't really know what I can add to the documentation.... You set a map of HTTP headers to add to the request.

I don't know how that could solve any color problem though. You need to now that Three.js (and the web in general) only supports sRGB color profile, all other ICC profiles will have issues.

**Comment by Rafael-C-S** [comment]
Hello, thanks for the reply!

This is the screenshot of my error. It's in Brazilian Portuguese.

I need to set the header to be able to load the image. The settings on the server are already [Access-Control-Allow-Origin: *] but I still get the image error.

![error](https://user-images.githubusercontent.com/10452043/228962394-4b238a3c-ab31-422a-b510-c03427677de2.PNG)

**Comment by mistic100** [comment]
CORS are not something that can be corrected from the client, thus the "requestHeaders" option will not help you.

I cannot help you further on this matter as it only depends on your server. Access-Control-Allow-Origin is not the only header that controls CORS, there are other Access-Control-Allow-XXX that can be used.

**Comment by Rafael-C-S** [comment]
Hello,
I greatly appreciate your attention.
Congratulations on the tool!
