### ISSUE TITLE
Safari - Fullscreen mode not working

### ISSUE THREAD

**Issue by invincible09** [mistic100/Photo-Sphere-Viewer#92]
is there a fix for this?

Thanks!

**Comment by mistic100** [comment]
Safari on MacOS ? Sorry I can't test at all.

**Comment by invincible09** [comment]
Yeah. Even the demo on your frontpage when on fullscreen mode it is completely blank/black.

**Comment by gocebonev** [comment]
Any update on this bug?

**Comment by mistic100** [comment]
Do you want to try to fix it ? I still don't have a Mac

**Comment by gocebonev** [comment]
It is not on Mac, Chrome on windows 10 exhibits the same problem, if you give me a hint where to look for it I can try

**Comment by mistic100** [comment]
The fullscreen request is here https://github.com/mistic100/Photo-Sphere-Viewer/blob/dev/src/js/PhotoSphereViewer.public.js#L489

Did you try with the last release or on dev branch ? There was an issue I fixed here https://github.com/mistic100/Photo-Sphere-Viewer/commit/5fd830b56bc911314828fc90cbbff700130936b9

**Comment by gocebonev** [comment]
Thanks it fixes the issue. Thank you

**Comment by mistic100** [comment]
@invincible09 can you test on MacOS ?

**Comment by runtim** [comment]
This issue is on iOS in either Safari and Chrome.

**Comment by gatlo** [comment]
This is not a problem with PSViewer but with Safari on iOS. It doesn't have Fullscreen API - http://caniuse.com/#feat=fullscreen

**Comment by mistic100** [comment]
Thank you @gatlo

**Comment by ciadavid** [comment]
What about to change button if IOS and allow to open full height/width div to simulate fullscreen? I have made a similar solution on mi integration: when I detect IOS iphone/ipad I add a button to open on new tab whit full heigth/width whiout other web interface, I can help.
