### ISSUE TITLE
Basic request: Disable download from visible icons as default

### ISSUE THREAD

**Issue by mycloudvip** [mistic100/Photo-Sphere-Viewer#935]
### Describe the feature

Awesome script, but I was not able to find a shortcut or code example to start the viewer without the download button visible and without having to set the entire array of buttons. Is there a shortcut for this?

Thanks

**Comment by mistic100** [comment]
```js
viewer.addEventListener('ready', () => {
  viewer.navbar.getButton('download').hide();
}, { once: true });
```

**Comment by mycloudvip** [comment]
Worked like a charm!

**Comment by mistic100** [comment]
Other possibility

```js
navbar: PhotoSphereViewer.DEFAULTS.navbar.filter(n => n !== 'download')
```
