### ISSUE TITLE
Error when showing multiple photospheres one one page

### ISSUE THREAD

**Issue by tap2k** [mistic100/Photo-Sphere-Viewer#936]
### Describe the bug

When showing multiple photospheres on one page, I get the following error. Verified on Chrome and Safari, Windows and Mac.

Unhandled Runtime Error
IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-5) is negative.
Call Stack
Loader.setProgress
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (5774:0)
eval
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (2995:0)
eval
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (8299:0)
new Promise

TextureLoader.loadFile
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (8297:0)
EquirectangularAdapter.__loadXMP
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (3062:0)
EquirectangularAdapter.loadTexture
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (2994:0)
Viewer.setPanorama
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (9379:0)
new Viewer
node_modules/react-photo-sphere-viewer/dist/node_modules/photo-sphere-viewer/dist/photo-sphere-viewer.js (9097:0)
eval
node_modules/react-photo-sphere-viewer/dist/index.js (99:0)
commitHookEffectListMount
node_modules/react-dom/cjs/react-dom.development.js (23150:0)
commitPassiveMountOnFiber
node_modules/react-dom/cjs/react-dom.development.js (24926:0)
commitPassiveMountEffects_complete
node_modules/react-dom/cjs/react-dom.development.js (24891:0)
commitPassiveMountEffects_begin
node_modules/react-dom/cjs/react-dom.development.js (24878:0)
commitPassiveMountEffects
node_modules/react-dom/cjs/react-dom.development.js (24866:0)
flushPassiveEffectsImpl
node_modules/react-dom/cjs/react-dom.development.js (27039:0)
flushPassiveEffects
node_modules/react-dom/cjs/react-dom.development.js (26984:0)
commitRootImpl
node_modules/react-dom/cjs/react-dom.development.js (26935:0)
commitRoot
node_modules/react-dom/cjs/react-dom.development.js (26682:0)
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (26117:0)
flushSyncCallbacks
node_modules/react-dom/cjs/react-dom.development.js (12042:0)
eval
node_modules/react-dom/cjs/react-dom.development.js (25651:0)

### Photo Sphere Viewer version

5.1.4

### OS & browser

Chrome, MacOS

**Comment by mistic100** [comment]
I don't have the issue on the demo files. Please provide a demo as requested.

**Comment by tap2k** [comment]
Im actually using the react-photosphere-viewer wrapper but Ive traced the error to the underlying library. It seems it is trying to load the photosphere without the underlying canvas being initialized. I will recreate using the base library and send an example.

**Comment by tap2k** [comment]
I figured out this happened when the photosphere was wrapped in an inline-block without specifying the width.
