### ISSUE TITLE
Equirectangular tiles + basePanoData + cropped panorama doesn't show in Chrome

### ISSUE THREAD

**Issue by PanierAvide** [mistic100/Photo-Sphere-Viewer#937]
### Describe the bug

Hello,

On our work using PhotoSphereViewer for showing street pictures, we're using both Equirectangular Tiles Adapter and `basePanoData` for showing in some cases a cropped panorama (which allows us to display a flat picture in PSV). This works very well under Firefox 110, but for an unknown reason it doesn't work under Chromium 111.0.5563.64 (Linux).

Given URL example works with Firefox, not Chromium. Chromium doesn't show any issue, and seem to load against network the picture file, but shows a black screen instead of picture.

The `basePanoData` for this example is the following :

```js
{
  "fullWidth": 26660.571428571428,
  "fullHeight": 13330.285714285714,
  "croppedWidth": 5184,
  "croppedHeight": 3888,
  "croppedX": 10738.285714285714,
  "croppedY": 4721.142857142857,
  "poseHeading": 268
}
```

Best regards.

### Online demo URL

https://panoramax.ign.fr/#focus=pic&map=19/46.1991528/1.2987483&pic=1aac9b53-2c7e-455a-825a-09e74d9eb552&xyz=268.00/0.00/0

### Photo Sphere Viewer version

5.1.4

### OS & browser

Linux + Chromium 111

**Comment by PanierAvide** [comment]
Sorry, here you go, a minimal example working under Firefox but not Chromium : https://codesandbox.io/s/magical-morning-5b699e

**Comment by mistic100** [comment]
1. this looks to be related to the size of the canvas used to scale the base image, if I hardcode 8192 https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/packages/core/src/data/system.ts#L49 I can get it work
2. when using the same image in the standard equirectangular demo _with the above change_, it **doesn't** work either !

**Comment by mistic100** [comment]
Looks like it has something to do with the size of the canvas used to downscale the image. The lib detects the maximum size is 16384px, but if I force it to 8192px it works.

What's odd is that the same image loaded on the standard equirectangular adapter works.

**Comment by mistic100** [comment]
This seems to be cause by the blur filter applied to the base image. I am not really willing to file a Chrome bug....

However I think in your case you will want to disable this blur. Set `baseBlur: false` in the adapter options.

**Comment by mistic100** [comment]
By the way I changed the current hardcoded "1px" to a value depending on the actual image dimensions, so it will be much more visible in your case and you will have to disable it.
