### ISSUE TITLE
What panorama formats are supported?

### ISSUE THREAD

**Issue by mrdance** [mistic100/Photo-Sphere-Viewer#94]
I wonder what kind of input formats are supported? I am looking at this page: http://wiki.panotools.org/Panorama_formats

Will it work with Rectilinear panoramas?

Thanks

**Comment by mistic100** [comment]
It only fully supports Equirectangular projections (and one day, cubic projections)

If you want to use partial projections (like rectilinear) you must define the corresponding area using XMP tags, see my answer here https://github.com/mistic100/Photo-Sphere-Viewer/issues/78#issuecomment-253438049

**Comment by mistic100** [comment]
example of what a partial panorama will look like https://galerie.strangeplanet.fr/picture.php?/3520/category/119
this one is 360° x 45° aproximately

**Comment by mrdance** [comment]
Would you recommend that it is better for experience if I convert image in tool to Equirectangular than using XMP tags?

**Comment by mistic100** [comment]
You mean completing the areas with black (or other color) ? It's totally useless and will decrease performances (bigger texture to load)

It's better to define the viewport with XMP tags and leave the image itself untouched (image you want to download it...)

**Comment by mrdance** [comment]
Can I consult you on some quick questions on your personal email? If yes, please email me on henrik@neteject.com

**Comment by mistic100** [comment]
Nope, I don't do personal assistance.

**Comment by mrdance** [comment]
I understand.

1. would I lose any part of picture if adding XMP and show it into photosphere?
2. does it take a lot of CPU to "convert" through XMP in photosphere?

Thanks again!

**Comment by mistic100** [comment]
XMP are just metadata, you don't lose anything. Of course if your specify invalid values it will show nothing or only a part of the picture.

Why would it ? it's just coordinates, the 3D Webgl renderer takes a tremendous quantity of resources compared to this.
