### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by leonardtkt** [mistic100/Photo-Sphere-Viewer#941]
### Describe the feature

Hello there,

I struggled for more than a day and a half with the MarkersPlugin for a professional Vue project.
After I finally figured out that I needed to import the css from the markers plugins !

So I don't know if we could call this a Feature request, but unless I missed something reading the documentation, it would be nice for future Photo Sphere Viewer users to add it clearly in the doc? :)

 Other than that, great job and thank you for offering this beautiful library!
 
 PS : Salut de Paris ;)

**Comment by mistic100** [comment]
It is written on the "Import official plugins" section here https://photo-sphere-viewer.js.org/plugins/

And in bold text in the introduction here https://photo-sphere-viewer.js.org/plugins/markers.html

If you have any suggestion to make it more visible, I'll take it.

**Comment by mistic100** [comment]
I don't know how to display it, there are as many ways to import CSS files as there are frontend frameworks, hence the sentence in your screenshot.

**Comment by mistic100** [comment]
by the way the "link rel=stylesheet" is on the "Direct import" tab too
