### ISSUE TITLE
Control StartMove 

### ISSUE THREAD

**Issue by romulYurch** [mistic100/Photo-Sphere-Viewer#943]
### Describe the feature

I'm using v4 now, but as i see my issue works the same in v5.
So when you clicking on marker and using viewer.animate to point the camera to the marker - you expect that nothing will break this animation and viewer.animate.then will work to set new panorama by using viewer.setPanorama.
But if you click in any point of the viewer during animation, it stopped, because `StartMove `fires and it tries to start new rotation of the viewer.
It`ll be great if you give ability to control StartMove method with some property.

### Alternatives you've considered

For my goals, i had to create new global variable `ignoreMoving` and set it `true` before animate() and set it `false` when .then() fired. And i changed method __startMove() in library by adding return if ignoreMoving eq `true`.

>.... `ignoreMoving = true;`
			this.viewer.animate({
				                    longitude: clickedMarkerData.longitude,
				                    latitude: clickedMarkerData.latitude,
				                    zoom: 100,
				                    speed: '-5rpm',
			                    }).then( () =>
			                             {
				                             `ignoreMoving = false;`
				                             this.viewer.setPanorama(image.path, {
					                             zoom: 0,
					                             transition: false,
					                             longitude: pov.longitude,
					                             latitude: pov.latitude,
				                             }).then( () => {
					                             this.drawMarkers();
					                             if(then)
						                             then(image);
				                             });
			                             });
....

> _proto.__startMove = function __startMove(evt) {
      var _this5 = this;
     ` if(ignoreMoving)`
        return;
.....

**Comment by mistic100** [comment]
You can disable "mousemove" before starting the animation

```js
  viewer.setOption('mousemove', false);
  viewer.animate({
      yaw: .....,
      pitch: ......,
  })
  .then(() => {
      viewer.setOption('mousemove', true);
  });
```

Currently, click+drag will still cancel the animation but I will fix that.
