### ISSUE TITLE
Help to start ...

### ISSUE THREAD

**Issue by casagou** [mistic100/Photo-Sphere-Viewer#95]
Hi, I'm currently trying to embed in a classic photography website some 360 photos. My goal is to implement your "Photo-Sphere-Viewer" and add some overlays labels and links (same as your website example).

However, I'm not sure where to start. How do I install Node and Bower? Do I need to run on Linux?

Documentation: "Install Node and Bower dependencies npm install & bower install then run grunt in the root directory to generate production files inside dist."

Thanks for your support,
Joachim

**Comment by mistic100** [comment]
What you read is the "Build" process, you don't need that.

Just grab the files in the dist directory on the master branch https://github.com/mistic100/Photo-Sphere-Viewer/tree/master and same thing for the four dependencies.

Or preferably run "bower install Photo-Sphere-Viewer" or "npm install photo-sphere-viewer".

I will not teach what are npm and bower and how to install them.

**Comment by mistic100** [comment]
I just added a direct link ot the archive in the popup opening when clicking on Download http://photo-sphere-viewer.js.org
