### ISSUE TITLE
VisibleRangePlugin issue ?

### ISSUE THREAD

**Issue by leonard-colin** [mistic100/Photo-Sphere-Viewer#950]
### Describe your problem

Hi there,

I am trying to add VisibleRangePlugin in my Vue project.
No problem when using MarkersPlugin.
But I keep getting the same issue when trying to initiate a viewer with ranges. 
My console error: `Uncaught (in promise) PSVError: An undefined value was given for plugin 0. `

Here is the code:
```javascript
import { Viewer } from '@photo-sphere-viewer/core'
import { MarkersPlugin } from '@photo-sphere-viewer/markers-plugin'
import { VisibleRangePlugin } from '@photo-sphere-viewer/visible-range-plugin'
import '@photo-sphere-viewer/core/index.css'
import '@photo-sphere-viewer/markers-plugin/index.css'
//....//

state.viewer = new Viewer({
      container: 'viewer',
      panorama: props.store.panoramicImage,
      navbar: ['zoom', 'move', 'markers', 'fullscreen'],
      plugins: [
        [VisibleRangePlugin, {
          // usePanoData: false,
          horizontalRange: [-Math.PI / 2, Math.PI / 2],
          verticalRange: [-Math.PI / 3, Math.PI / 3],
        }],
        [MarkersPlugin, { markers: state.markers }],
      ],
    })
    state.viewer.addEventListener(
      'ready',
      () => {
        state.isPSVReady = true
      },
      { once: true }
    )
```

I am using PSV v5.1.5 as well as for Markers and Ranges

Any help would be very much appreciated :)

### Photo Sphere Viewer version

5.1.5

### Plugins loaded

MarkersPlugin, VisibleRangePlugin

**Comment by leonard-colin** [comment]
Not right now, unfortunately..

**Comment by mistic100** [comment]
I did, and it works without any problem https://github.com/mistic100/test-psv-vue

**Comment by leonardtkt** [comment]
Ok, thanks ! Don't what's happening for me... I will check again after this weekend...

**Comment by leonard-colin** [comment]
Ok, thanks ! Don't what's happening for me... I will check again after this weekend...

**Comment by leonard-colin** [comment]
Hey, just an update here. It works well now !
It seems it was a cache issue, even if I cleared it several times... Weird magic problem that drives you crazy..!
Anyway, thanks for your quick support !

**Comment by leonard-colin** [comment]
Ok, this time maybe a real issue to fix: 
If you set a visible range with degrees, the limits are going on and off as you zoom in or out..
I took over your test repo, and just added these:

```javascript
const visibleRangePlugin = viewer.getPlugin(VisibleRangePlugin)
visibleRangePlugin.setHorizontalRange(['0deg', '100deg'])
visibleRangePlugin.setVerticalRange(null)
```

In my project, I had to set a maxFox < 74 to avoid the issue

**Comment by mistic100** [comment]
No problem with degrees, the problem, I think, is when the viewable horizontal range is smaller than the viewport
