### ISSUE TITLE
Viewer size varies between desktop & mobile browser

### ISSUE THREAD

**Issue by pcolmer** [mistic100/Photo-Sphere-Viewer#954]
### Describe the bug

I've used `<div id="viewer" style="width: 40vw; height: 40vh;"></div>` to describe the viewer container. It looks OK when viewed on a desktop browser but viewing it on a mobile browser shows the container is half the width:

![Screenshot_20230506-074313](https://user-images.githubusercontent.com/1979931/236582607-c000b734-fa48-4186-8dad-1c776581b88c.png)

Compared with:

![Screenshot 2023-05-05 234517](https://user-images.githubusercontent.com/1979931/236582629-ce8a5315-4185-46a4-887a-11c27cefac47.png)

### Online demo URL

https://techietravelling.papillonproductions.co.uk/2023/05/04/day6.html

### Photo Sphere Viewer version

5.1.5

### OS & browser

Android + Edge on mobile, Windows 11 + Edge on desktop

**Comment by mistic100** [comment]
`40vw` means 40% of the window width, so no problem here., perhaps you just use `100%` which will be 100% of your parent element

https://www.freecodecamp.org/news/css-unit-guide/
