### ISSUE TITLE
Fullscreen mode not working on iOS- Safari or Chrome

### ISSUE THREAD

**Issue by runtim** [mistic100/Photo-Sphere-Viewer#96]
Fullscreen is not triggered on an iOS device (10.2.1/iPhone 6).

Even after using the fix in #74, iOS , it doesn't fix the issue.

The strange thing is this is present in both Safari and Chrome on iOS.

Any ideas?

**Comment by mistic100** [comment]
Duplicate #92, see my message 5 days ago in this thread.

**Comment by runtim** [comment]
I used that and it didn't work.

**Comment by mistic100** [comment]
As I said in the other issue, I don't have a Mac, I CANNOT test at all.
That why I leave the other issue open, but one is enough.
