### ISSUE TITLE
Virtual tour: manage overlapping arrows

### ISSUE THREAD

**Issue by mistic100** [mistic100/Photo-Sphere-Viewer#960]
### Describe the feature

When two arrows are close to each other, it becomes hard to click them.

Example in Panoramax IGN project  
![Capture d’écran du 2023-05-12 16-39-16](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41597/e72d6f20-0a8e-4139-b61d-0dcabf516864)

How to make the display more usable ? Merge the arrows and display the different targets in a popin ? (how to do that if there is no link title ?)

@PanierAvide perhaps you have an idea ? :smile:

**Comment by PanierAvide** [comment]
I'm not sure what would be the best solution in that case. As a comparison, Mapillary always only display like 4/5 arrows at a time, and always a single one is a given direction. Maybe in that case of overlapping, only the arrow pointing to the nearest picture should be kept ?

**Comment by PanierAvide** [comment]
Example : https://www.mapillary.com/app/?lat=48.85831137992798&lng=2.3423689499919647&z=19.9&pKey=491266305399268&focus=photo&x=0.5221951073772472&y=0.5840510160844226&zoom=0

**Comment by floatline** [comment]
Possibly offset the arrows from the viewer's point of view? Maybe it should be dependent on the gps value, in case it's provided (closer to the viewer, if the distance is smaller, further, if the distance is bigger)?

**Comment by mistic100** [comment]
> Possibly offset the arrows from the viewer's point of view? Maybe it should be dependent on the gps value, in case it's provided (closer to the viewer, if the distance is smaller, further, if the distance is bigger)?

That somehow works, I multiplied the position of the arrow by a factor from 0.5 to 1.5, mapped to the GPS distance to the node.
![arrows](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41597/b4554207-3f4e-4f68-acd4-96797b8dfa6b)

For the manual mode I guess I could add a `depth` property to the already existing `linkOffset`.
