### ISSUE TITLE
Map plugin: custom shape

### ISSUE THREAD

**Issue by ziakor** [mistic100/Photo-Sphere-Viewer#964]
### Describe the feature

hi,

- be able to use a custom shape instead of this circle for the map plugin.

**Comment by mistic100** [comment]
Please read the documentation, there are pinImage and spotImage options

**Comment by haldo98** [comment]
maybe was the shape of the widget....    now it's only round.

**Comment by ziakor** [comment]
yes it was that ...

**Comment by mistic100** [comment]
You can change the "compass" overlay with `overlayImage` but it will still be a circle.

The entire UI and behavior is crafted arround the circle element, I cannot offer a way to change it.
