### ISSUE TITLE
Infinite Zoom Bug? 

### ISSUE THREAD

**Issue by leomuehlfeld** [mistic100/Photo-Sphere-Viewer#965]
### Describe your problem

Hi! 

Im using @photo-sphere-viewer/core with React, Nextjs and Typescript. Everythings works except the picture infinitely starts zooming without ever stopping. Maybe i am overseeing something here…

```
import { Viewer } from "@photo-sphere-viewer/core";
import React, { useEffect } from "react";


export default function Pano() {
  const sphereElementRef = React.createRef<HTMLDivElement>();

  useEffect(() => {
    const shperePlayerInstance = new Viewer({
      container: sphereElementRef.current,
      panorama: "./img/eis.jpg",
    });

    return () => {
      shperePlayerInstance.destroy();
    };
  }, []);
  return(
   <div className="pano" ref={sphereElementRef}></div> 
  )};
```

```
.pano{
  position: fixed;
  top: 0;
  left: 0;
  z-index: 0;
  width: 100vw;
  height: 100vh;
}
````

I am suspecting a correlation with the threejs bug of infinite canvas resizing in height direction 
https://github.com/pmndrs/react-three-fiber/issues/1684

Here is a screenshot from chromes inspector regarding the rendered canvas element.

<img width="525" alt="Bildschirmfoto 2023-05-24 um 17 48 45" src="https://github.com/mistic100/Photo-Sphere-Viewer/assets/22169889/c302e13c-640e-4d12-aac5-2b871f86e470">

help is much appreciated, thanks for the module! ✨

best,
Leo

### Photo Sphere Viewer version

5.1.5

### Additional context

Tested on Safari 16.4. and Chrome 113.0.

**Comment by Zonciu** [comment]
You forgot to import the css file:
```
import '@photo-sphere-viewer/core/index.css';
```

**Comment by leomuehlfeld** [comment]
> You forgot to import the css file:
> 
> ```
> import '@photo-sphere-viewer/core/index.css';
> ```

😬 … as simple as that. Thank you for pointing it out. Don't know why I forgot that.
