### ISSUE TITLE
Load panorama with data image

### ISSUE THREAD

**Issue by RomainSauvaire** [mistic100/Photo-Sphere-Viewer#97]
I would like to create a panorama from a user-uploaded file (but not yet saved on the server) to allow him a preview of what it will look like.

The ideal would be to pass the result of a `FileReader` `readAsDataUrl()` directly to the `panorama` property.

Can you think about it and/or explain me your point of view please ?

**Comment by mistic100** [comment]
Did you try it ? It should work, because https://threejs.org/docs/api/loaders/ImageLoader.html supports it.

**Comment by RomainSauvaire** [comment]
Haha, nope I haven't tried yet. Never thought it would be feasible.

Cheers

ps: thank you, I'm aware of it, still migrating from PHP 5.4 to 7.0 and my clients are my top priority.

**Comment by mistic100** [comment]
Browsers treat URL starting with `http://` and

**Comment by RomainSauvaire** [comment]
Just tested it, working fine. Thank you
