### ISSUE TITLE
360-movies colors washed

### ISSUE THREAD

**Issue by GeorgLegato** [mistic100/Photo-Sphere-Viewer#970]
### Describe the bug

I produce videos for the Photosphere viewer. In normal players, like VLC, mplayer, browsers etc. the videos are ok, regards the colors, saturation etc.
Playing the 360-movie using the equi-video-adapter, it is losing saturation a lot:
(left browser-video-canvas, right: Photosphere viewer)
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/7210708/1f6855b4-dbcd-4837-9a3f-06f10c4fdbee)

Here is the FFPROBE output of my video:
```
 Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:00:02.00, start: 0.000000, bitrate: 7474 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 2496x1536, 7465 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
```
Actually ok, it follows the BT709 / sRGB html standard.

what I tried already:
* convert to libx264RGB : no effect
* checked the  canvas-html-element and tried severl "color-rendering"-policies: no effect
* 

### Photo Sphere Viewer version

5.1.5

### Plugins loaded

equie-movie

### OS & browser

chrome, edge, firefox

### Additional context

just for your information:
I produce zomming with "my" stable-diffusion extension
https://github.com/v8hid/infinite-zoom-automatic1111-webui

and the  360-viewer-integration comes from my repo:
https://github.com/GeorgLegato/sd-webui-panorama-viewer

**Comment by GeorgLegato** [comment]
https://github.com/mistic100/Photo-Sphere-Viewer/assets/7210708/17c65957-346f-44ef-a36d-e402130a6b54

**Comment by mistic100** [comment]
I do not get the same result, here is what it looks like on my machine on both Firefox and Chrome

![Capture](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41597/10ae05b8-25e3-45dd-a46f-c060427bbbcd)

By the way the library does not do any transformation to the video, it is a standard `<video>` element feed directly to Three.js  
So I don't what could be changed.

**Comment by GeorgLegato** [comment]
i have other issues due to dark theming in browsers ( or by the window manager like gnome) . could it be some clever dark theme is modifying video as well?
i see my prob on ubuntu/chrome/ff and on win10/edge

but already good too know it is not an video encoding issue

i will try more browser/dark/light theme tests

**Comment by GeorgLegato** [comment]
> I do not get the same result, here is what it looks like on my machine on both Firefox and Chrome
> 
> 
> 
> ![Capture](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41597/10ae05b8-25e3-45dd-a46f-c060427bbbcd)
> 
> 
> 
> By the way the library does not do any transformation to the video, it is a standard `<video>` element feed directly to Three.js  
> 
> So I don't know what could be changed.
> 
> 

42 days ago the 360 video had correct colors, see in my video 

https://www.reddit.com/r/aiArt/comments/12npyx4/preview_infinitezoom360panoramamovie_high_res/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1

the photosphere js is loaded via <script> resource.

**Comment by mistic100** [comment]
I don't know what changed in the world 42 days ago :-)

Perhaps you could provide a demo of your specific setup.

Also can you try to add `viewer.renderer.renderer.outputEncoding = THREE.sRGBEncoding;` after init but before setting the panorama (you can init the viewer without `panorama` option then call `setPanorama()`)

**Comment by GeorgLegato** [comment]
let me summarize:

Linux Ubuntu Firefox/chrome / windows11 Edge - NOK
Intel UHD770 NOK 
Nvidia 3080 NOK (windows11)
Nvidia-Videosettings (Range 16-255 or 0.-255) NOK
Equi-Movie Demo on your page NOK
!!! Cubemap-Movie-Demo on your page **OK** !!! (SRC points to a WEBM; equi video is referring a MP4)

viewer.rendere.render = three.srgb: NOK

Test on the PC of my son: NOK, same issues as with my setup. (windows, nvidia 3060)

That is complicated. What is your setup, when the minions movie was displayed correct?
Thanks for your support, btw

## Details:

## in my environment, same in Win11-edge-bright-theme, nvidia 3080
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/7210708/20882c3d-d622-4606-8dc9-d71ed799bf6e)

## Windows 11-Edge, Bright theme, Nvidia 3080 latest driver. Even your demo is bad for me.

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/7210708/a3d6686b-6dd7-496c-ae07-c01817134f34)


## But the cubemap video adapter seems OK
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/7210708/ca2c5aa1-6382-41c3-9ae5-19d13ad70957)


## testing nvidia video-quality-setting.
nothing takes effect

## trying the sRGB-rendering
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/7210708/847a88c6-e575-4fa8-af2e-f7cd2f485038)
no effect
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/7210708/942f3e47-859f-467b-bd8f-0aa10383ef29)

**Comment by GeorgLegato** [comment]
I found this WORKING example of ThreeJS.
https://threejs.org/examples/#webgl_video_panorama_equirectangular
the code behind should something slightly different on setup/loading texture/colorspaces.
Playing the "pano.mp4" from threejs.-example in the Photosphere.viewer results again dull colors. 
I ve read a lot about "srbg-linear" as threejs-colorworkspace and tried to enable colormgt, but still no effect:

   
    THREE.ColorManagement.enabled = true;
create...
    panoviewer.renderer.renderer.outputColorSpace = THREE.SRGBColorSpace;
    panoviewer.renderer.physicallyCorrectLights = true
    panoviewer.renderer.outputEncoding = THREE.sRGBEncoding
    panoviewer.renderer.toneMapping = THREE.ACESFilmicToneMapping
    panoviewer.renderer.toneMappingExposure = 1.3

**Comment by mistic100** [comment]
After upgrading geforce drivers from 527 to 532 I have the issue too.

No idea what needs to be changed, and even IF something needs do be changed, perhaps it is a bug in the driver.

**Comment by GeorgLegato** [comment]
I found some medicine:

1. panoviewer.renderer.renderer.outputColorSpace='srgb-linear'
1. panoviewer.renderer.renderer.toneMapping=5

here my "hack and trial" code snippet, which fixes it somehow:
```
...
    THREE.ColorManagement.enabled = true;
    panoviewer.renderer.renderer.outputColorSpace='srgb-linear'
    panoviewer.renderer.physicallyCorrectLights = true
    panoviewer.renderer.outputEncoding = THREE.sRGBEncoding
    panoviewer.renderer.toneMapping = 5 // THREE.ACESFilmicToneMapping, i need custom
    panoviewer.renderer.toneMappingExposure = 1
...
```
I tested it interactively in this demo: https://threejs.org/examples/#webgl_tonemapping
btw, three-js is great

Could you add and test in your code of equirectVideoAdapater.ts to set the the ColorSpace of loaded texture explicetely to
SRGB, like in the example of three.js?

![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/7210708/32db32bf-e5c5-4572-ae85-48908a9bc2d1)


![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/7210708/3ac0fa2a-7ea3-44e6-9ecc-3d0e192d4a65)

**Comment by mistic100** [comment]
By adding `texture.colorSpace = SRGBColorSpace` to the VideoTexture it solves the Equirectangular Video, however the Cubemap Video becomes too dark. So I need to find a way to automatically detect the input color space, or, if not possible, add an option.

**Comment by mistic100** [comment]
So this is caused by THREE 152 wich changed a lot of things in colors management, even thes tiles adapter have bad colors.

Following this guide https://discourse.threejs.org/t/updates-to-color-management-in-three-js-r152/50791 I will apply the "Can I opt out ?" configuration.
