### ISSUE TITLE
Freeze when zoom in and out maximum several times by keyboard Shortcut Action

### ISSUE THREAD

**Issue by hotbrainy** [mistic100/Photo-Sphere-Viewer#972]
### Describe the bug

when I do zoom in and out maximum by keyboard shortcut action, viewer sometimes freezes so need to reload panorama.
What is the issue?
Seems cause of buffering or cache?

### Photo Sphere Viewer version

5.1.5

### OS & browser

Ubuntu 22.04, Chrome 113

**Comment by mistic100** [comment]
Please provide more informations. I cannot debug with just "sometimes". Check the developper console for errors. Provide a demo where you experience this, etc.
