### ISSUE TITLE
Clicking on the viewer while panning the animation causes the image to shake

### ISSUE THREAD

**Issue by Steve245270533** [mistic100/Photo-Sphere-Viewer#977]
### Describe the bug

Clicking on the viewer while panning the animation causes the image to shake。

![error](https://github.com/mistic100/Photo-Sphere-Viewer/assets/46118247/2b706648-1d4f-436f-8c67-c00d20e0d0f1)

Is there any way to prevent the viewer from clicking during smooth animation execution?

### Photo Sphere Viewer version

5.1.6

### OS & browser

Chrome v114.0

**Comment by mistic100** [comment]
I might have messed up something if the lastest changes. I will try to fix it soon.
