### ISSUE TITLE
Tooltip Position - Hover scaling marker

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#984]
### Describe your problem

In the latest version 5.1.6 there's the new hover scaling feature for markers ...  but I noticed that - in case of the default and custom scaling marker - the tooltip overlaps the marker and it is not in the top center position.

https://photo-sphere-viewer.js.org/demos/markers/hover-scale.html

is there a way to avoid that?

### Photo Sphere Viewer version

5.1.6

**Comment by mistic100** [comment]
There still are edgecase I don't want to fix but the general usage is good now.
