### ISSUE TITLE
Can't enter fullscreen in iOS safari/chrome.

### ISSUE THREAD

**Issue by liesahead** [mistic100/Photo-Sphere-Viewer#985]
### Describe the bug

Clicking the `fullscreen` button doesn't do anything.

Steps to reproduce:
1. Open chrome or safari on iPhone
2. Open the playground [https://photo-sphere-viewer.js.org/playground.html](url)
3. Click on `fullscreen` button

Expected result: panorama opens in fullscreen mode
Actual result: nothing happens

### Online demo URL

https://photo-sphere-viewer.js.org/playground.html

### Photo Sphere Viewer version

5.1.6

### OS & browser

iOS Safari v16.5; Chrome latest

**Comment by mistic100** [comment]
See #860

**Comment by liesahead** [comment]
@mistic100 , https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

From what I see API is now available

**Comment by liesahead** [comment]
Also, another option would be to make a panorama element of fixed position and coordinates `top: 0; bottom: 0; left: 0; right: 0;`, we currently use `marzipano.js` and do that to make it fullscreen. Works like a charm on every device.

**Comment by liesahead** [comment]
@mistic100 , indeed, that's sad. But what's confusing me more is that the same problem exists in the chrome browser on iPhone.
