### ISSUE TITLE
Inconsistent Zoom Functionality on "CHROME"

### ISSUE THREAD

**Issue by kumardeepakxyz** [mistic100/Photo-Sphere-Viewer#986]
### Describe the bug

There seems to be a substantial problem with the zoom feature. It's unresponsive to both mouse wheel movements and keyboard inputs. In some cases, it may allow zooming out once but doesn't permit zooming back in. There are also instances where it doesn't allow any zooming in or out at all.

Intriguingly, this problem is exclusive to "Chrome". My testing has shown that the functionality works as expected on both Firefox and Safari.

### Online demo URL

https://panorama.wiplink.xyz/

### Photo Sphere Viewer version

5.1.6

### Plugins loaded

None

### OS & browser

CHOME - Version 114.0.5735.106 (Official Build) (arm64)

**Comment by kumardeepakxyz** [comment]
I've shared my experience and observations during my work, it's your prerogative whether you want to wait for other users to report similar problems. Even after updating my Chrome browser to the latest version, 114.0.5735.133 (Official Build) (arm64), the issue persists. I'm confident that browser extensions or similar factors are not contributing to this problem.

Fingers crossed for a fortuitous resolution in this situation.

**Comment by mistic100** [comment]
Are you on MacOS ? I had issues on both Chrome and Safari on a Mac at work today. The zoom becomes unresponsive once either the max or min fov is reached once.

**Comment by kumardeepakxyz** [comment]
> Are you on MacOS ? I had issues on both Chrome and Safari on a Mac at work today. The zoom becomes unresponsive once either the max or min fov is reached once.

Yes, If details can help, its a iMac M1 with macOS Ventura. My demo link does work on Safari but I haven't tested for long on that browser.
