### ISSUE TITLE
Custom tooltip on Map Plugin

### ISSUE THREAD

**Issue by haldo98** [mistic100/Photo-Sphere-Viewer#989]
### Describe the bug

I use custom tooltip like shown here:
https://photo-sphere-viewer.js.org/demos/markers/custom-tooltip.html

works perfectly also on my panos...

But I noticed that in the map Plugin, the tooltip shown when the mouse goes over an hotspot  has the picture not resized.

check my demo: 

stop the rotation - open the map - and mouse over the hotspot "Pizzo Cornagiera"

### Online demo URL

https://www.tadini.it/panorama/olino/panorama_olino.html

### Photo Sphere Viewer version

5.1.7

### Plugins loaded

map marker

### OS & browser

win 11 - chrome 114

**Comment by mistic100** [comment]
Now the custom CSS class defined on the marker tooltip will be kept for the tooltip on the map, tgus allowing the same sizes config
