### ISSUE TITLE
Grab tooltip marker

### ISSUE THREAD

**Issue by RomainSauvaire** [mistic100/Photo-Sphere-Viewer#99]
I would like to access the marker data when hovering *any* type of marker in the `show-tooltip` event or a new one `hover-marker` for example.

How would you do that if that is doable ?

**Comment by RomainSauvaire** [comment]
That's great thank you @mistic100 !
ps: don't forget to update documentation ;)

**Comment by mistic100** [comment]
Only when released

**Comment by RomainSauvaire** [comment]
Just noticed the `over-marker` naming rather than `hover-marker`.  Is it a misspelling or on-purpose name ?

**Comment by mistic100** [comment]
same semantic has mouseover and mouseleave
