### ISSUE TITLE
Problem using PhotoSphere Viewer with Bootstrap modal

### ISSUE THREAD

**Issue by mtran21** [mistic100/Photo-Sphere-Viewer#992]
### Describe your problem

I am implementing PhooSphere Viewer with Bootstrap modal, when click on a button, it pops up the modal and then display Photosphere viewer player. However, it does not show anything, just a blank player like this
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/13279623/1e455372-0cf9-49b9-8711-55d6d5d19d49)

But when I click on the Full Screen button, then the image is there. Then I escape full screen, it shows just normal
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/13279623/1c27156b-5092-4287-9052-375101a939b0)

How can I fix this? Please help

Thanks

### Photo Sphere Viewer version

other

**Comment by mistic100** [comment]
Please provide a online demo

**Comment by mtran21** [comment]
@mistic100 
Here is a demo site https://twu.edu/t4/tests/michael-tests/test-modal/

I will probably need to remove it once it is resolved. Thanks for your help.

**Comment by mistic100** [comment]
Also you might be interested in this plugin https://photo-sphere-viewer.js.org/plugins/gallery.html

**Comment by mtran21** [comment]
Sorry, here is a much simple demo URL https://twu.edu/t4/tests/michael-tests/test-modal/index2.php

**Comment by mtran21** [comment]
Not sure how to initiating the viewer from modal

**Comment by mtran21** [comment]
Thanks for you help. Finally, I got it working as the code below

`<div class="container">
	<div class="row">
		<div class="col-md-3">
		<a href="#" class="thumb">
			<img class="img-responsive" src="/media/images/scheduling/panorama/test/ACT_601.jpg">
		</a>
		  <div class="modal fade" id="121658" tabindex="-1" role="dialog" aria-labelledby="121658" aria-hidden="true">
		  <div class="modal-dialog modal-lg">
			<div class="modal-content">
			  <div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="myModalLabel"></h4>
			  </div>
			  <div class="modal-body">
				<div class="panorama-margin" id="photosphere121658"></div>
			  </div>
			</div>
		  </div>
		</div>
		</div>
	</div>	
</div>	

<script type="text/javascript">
    $(function () {
        $(".thumb").click(function () {
            $("#121658").modal("show");
			$('#121658').on('shown.bs.modal', function (e){
				var PSV = new PhotoSphereViewer({
			panorama: "/media/images/scheduling/panorama/test/ACT_601.jpg",
			container: 'photosphere121658',
			caption: '',
			navbar: 'autorotate zoom caption fullscreen',
			time_anim: false,
			loadingImg: '/media/images/scheduling/panorama/test/ACT_601.jpg',
			default_fov: 70,
			default_lat: 0.3,
			mousewheel: false,
			touchmove_two_fingers: true,
			size: {
			  height: 500
			}
		  });
			})
        });
    });
</script>	`

**Comment by mistic100** [comment]
don't forget to `destroy()` the viewer when you close the modal

**Comment by mtran21** [comment]
@mistic100  Thanks for the suggestion of using `destroy()`  but here is my code and it is not working when I close the modal. After I closed the modal and I open it back on, the photosphere is not showing anymore. Any help would appreciated. 

```
<script type="text/javascript">
    $(function () {
        $("#thumb121658").click(function () {
            $("#121658").modal("show");
			$('#121658').on('shown.bs.modal', function (e){
				var PSV = new PhotoSphereViewer({
			panorama: "/image/image.jpg",
			container: 'photosphere121658',
			caption: '',
			navbar: 'autorotate zoom caption fullscreen',
			time_anim: false,
			default_fov: 70,
			default_lat: 0.3,
			mousewheel: false,
			touchmove_two_fingers: true,
			size: {
			  height: 500
			}
		  });
			})
        });
		$("#close121658").click(function () {
            $("#121658").modal("hide");
			$('#121658').on('hidden.bs.modal', function () {
				$("#photosphere121658").remove();
			})
        });
    });
</script>
```

**Comment by mistic100** [comment]
destroy is a method on PSV variable, it has nothing to do with jQuery remove.

Sorry but I am not here to do bootstrap specific implementation.
