### ISSUE TITLE
Do you have any plan for Drag and drop functionalities? For markers and maybe a drop event on the viewer

### ISSUE THREAD

**Issue by Codename-404** [mistic100/Photo-Sphere-Viewer#996]
### Describe the feature

First of all, Thank you very much for this great plugin. This is very well developed and has a lot of features.

However it might be a nice to have a drag and drop feature for markers, and maybe a drop event on the viewer.
It would be great to be able to drag and drop points in the viewer from outside also maybe change marker position after placing.

### Alternatives you've considered

I have setup some listeners that works for dnd, however I can't properly get the screen to sphere coords. So, if not drag and drop atleast exposing the function to get sphere coors from screen position function would be helpful. Which I can't as I do not have access to the camera.

**Comment by mistic100** [comment]
Could you provide examples of what you implemented ? My problem is that it can get really complex and not be useful for much people. So I prefer not to provide any support and let developpers customize it.

----

Mouse position to spherical coordinates :

```ts
const viewerPos = PhotoSphereViewer.utils.getPosition(viewer.container); // this is a faster version of getBoundingClientRect()

const sphericalCoords = viewer.dataHelper.viewerCoordsToVector3({
  x: event.clientX - viewerPos.x,
  y: event.clientY - viewerPos.y,
});
```

**Comment by Codename-404** [comment]
Thank you very much for the solution. I did not see that you exposed all these. Sorry about that.

Uses would be in my case, I am planning to allow users to pin point by dragging points. However I can see how that can be very project specific. And I agree that it's not necessary to have a dnd feature in the main package, rather specific to the project that needs, which would eliminate unwanted complexity.

Again, Thank you very much for the great package ~
