### ISSUE TITLE
EquirectangularTilesAdapter does not change to low res tiles when zooming back out from higher level

### ISSUE THREAD

**Issue by julianstolp** [mistic100/Photo-Sphere-Viewer#997]
### Describe the bug

EquirectangularTilesAdapter does not change to low res tiles when zooming back out from higher level. This results in ugly aliasing when viewing from lower zoom levels. I can not host the images but here is my example code. 

high res, zoomed out 
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41152397/bade7e95-840b-46a1-9133-ae0fef45c6c9)
low res, zoomed out
![image](https://github.com/mistic100/Photo-Sphere-Viewer/assets/41152397/c83a4c7c-0e97-4745-afbc-893628d6c053)

```

<head>
    <!-- for optimal display on high DPI devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@photo-sphere-viewer/core/index.min.css" />
</head>

<script src="https://cdn.jsdelivr.net/npm/three/build/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@photo-sphere-viewer/core/index.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@photo-sphere-viewer/equirectangular-tiles-adapter/index.min.js"></script>

<body style="margin: auto;">
<!-- the viewer container must have a defined size -->
<div id="viewer" style="width: 100%; height: 100%;"></div>
</body>

<script>

const viewer = new PhotoSphereViewer.Viewer({
    container: 'viewer',
    adapter: PhotoSphereViewer.EquirectangularTilesAdapter,
    panorama: {
        levels: [
    {
        width: 19106*0.25, //width: 6298,
        cols: 32,
        rows: 16,
        zoomRange: [0, 80],
    },
    {
        width: 19106,
        cols: 32,
        rows: 16,
        zoomRange: [80, 100],
    },
],
        baseUrl: '<filename>_low.jpg',
        tileUrl: (col, row, level) => {
            return `<filename>_${col}_${row}_${level}.jpg`;
        },
    },
});
</script>
```

### Photo Sphere Viewer version

5.1.7

### Plugins loaded

None

### OS & browser

Windows 10 / Chrome Version 114.0.5735.134 (Official Build) (64-bit)

**Comment by mistic100** [comment]
That was exactly on purpose, it is simpler to track what tiles are loaded, and will have zero overhead when zooming out.

I am willing to try to tweak the renderer settings if you can provide some sample files.

**Comment by julianstolp** [comment]
Thanks for your answer, I have used this picture from [Wikipedia](https://upload.wikimedia.org/wikipedia/commons/b/b6/Afterglow_of_a_sunset.jpg) as I cant not share the original files. 
Note that this example image is only 8192x4096. The image where these aliasing effects are much stronger is 20000 x 10000 with a lot of fine details.

[output.zip](https://github.com/mistic100/Photo-Sphere-Viewer/files/11892677/output.zip)

**Comment by mistic100** [comment]
Please try this :
- download the unminified library files from Github releases page and use them in your page instead of jsdelivr
- in the index.js file of @photo-sphere-viewer/core, find the `createTexture` function and comment the two lines
```js
    // texture.minFilter = LinearFilter;
    // texture.generateMipmaps = false;
```

This should fix your display issue but I am interrested in potential performance drawbacks.

(For the record this mipmaps were disabled for the standard adapter, because generating the mipmaps for a whole equirectangular texture takes time, but perhaps it makes sens to reenable it for tiles adapters)

**Comment by julianstolp** [comment]
This fixes the aliasing entirely. The performance is very similar, no real differences encountered. Very similar Loading, Scripting, Rendering, Painting times. FPS also comparable. All tests were run locally on a 2018 mid range notebook.
I tried a bit with the different filters written in the docs[threejs.org](https://threejs.org/docs/#api/en/constants/Textures) but the default filter THREE.LinearMipmapLinearFilter looks the best. 

I think this is almost an style question, because the three.js default is more smooth even a tiny bit to soft in my opinion. But I will stick with it. Maybe this could be a configuration choice in a further release.
Thank you for your time.

**Comment by mistic100** [comment]
yes I see the softness too, setting `texture.anisotropy = 2;` seems to be a bit better (I don't see any difference with higher values)

**Comment by julianstolp** [comment]
Hello @mistic100 I tested a bit with texture.anisotropy but I will stick to the already implemented default to maintain the sharpness. Thanks a lot for your quick and helpful answers.

**Comment by mistic100** [comment]
I don't understand, you stick to what ? Now that you shown me the aliasing problem (even visible on the examples files), I must enable the mipmaps, I think it is much nicer.

**Comment by julianstolp** [comment]
I would stick to your already implemented solution with disabled mipmaps. As written early maybe you could introduce a configuration parameter.
